### ISSUE TITLE
vod_hls_force_unmuxed_segments ignores files with hevc.

### ISSUE THREAD

**Issue by enmaca** [kaltura/nginx-vod-module#1000]
Hi,

Im using nginx-vod-module in a mapped enviroment.

I am facing a situation that when I enable the option vod_hls_force_unmuxed_segments, ignores the files that are encoded with hevc.

This is the playlist with option disabled:
#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="Stereo Español",LANGUAGE="es",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="https://serverurl/index-f1-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="Surround Ingles",LANGUAGE="en",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="5",URI="https://serverurl/index-f2-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="Stereo Ingles",LANGUAGE="en",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://serverurl/index-f3-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=933367,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.40.2",AUDIO="audio0"
https://serverurl/index-f4-v1-f1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1312830,RESOLUTION=854x480,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.40.2",AUDIO="audio0"
https://serverurl/index-f5-v1-f1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2497164,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.640029,mp4a.40.2",AUDIO="audio0"
https://serverurl/index-f6-v1-f1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3151373,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="hvc1.1.2.L120.00,mp4a.40.2",AUDIO="audio0"
https://serverurl/index-f7-v1-f1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6655667,RESOLUTION=3840x2160,FRAME-RATE=23.974,CODECS="hvc1.1.2.L150.00,mp4a.40.2",AUDIO="audio0"
https://serverurl/index-f8-v1-f1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=11448,RESOLUTION=640x360,CODECS="avc1.64001f",URI="https://serverurl/iframes-f4-v1-f1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=17863,RESOLUTION=854x480,CODECS="avc1.64001f",URI="https://serverurl/iframes-f5-v1-f1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=35523,RESOLUTION=1280x720,CODECS="avc1.640029",URI="https://serverurl/iframes-f6-v1-f1-a1.m3u8"

This is the play list with the option enabled.

#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="Stereo Español",LANGUAGE="es",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="https://serverurl/index-f1-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="Surround Ingles",LANGUAGE="en",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="5",URI="https://serverurl/index-f2-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="Stereo Ingles",LANGUAGE="en",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://serverurl/index-f3-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=933367,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.40.2",AUDIO="audio0"
https://serverurl/index-f4-v1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1312830,RESOLUTION=854x480,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.40.2",AUDIO="audio0"
https://serverurl/index-f5-v1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2497164,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.640029,mp4a.40.2",AUDIO="audio0"
https://serverurl/index-f6-v1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=11448,RESOLUTION=640x360,CODECS="avc1.64001f",URI="https://serverurl/iframes-f4-v1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=17863,RESOLUTION=854x480,CODECS="avc1.64001f",URI="https://serverurl/iframes-f5-v1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=35523,RESOLUTION=1280x720,CODECS="avc1.640029",URI="https://serverurl/iframes-f6-v1.m3u8"

This is the json mapped response:

{"sequences":[{"clips":[{"type":"source","id":1,"path":"/opt/u00/mp4/5/0/f/6/b/d14876aa309dd1d9235b61b844bcfd8927311b8d1a585157350569560c1.mp4","encryptionKey":"m+WIUKAlD1lGTYBQ31VAqA=="}],"label":"Stereo Español"},{"clips":[{"type":"source","id":2,"path":"/opt/u00/mp4/9/a/f/4/6/31255fdd3057eeed989879e417e1bd0105146b10a5c7db7e0dd3126dda9.mp4","encryptionKey":"m+WIUKAlD1lGTYBQ31VAqA=="}],"label":"Surround Ingles"},{"clips":[{"type":"source","id":3,"path":"/opt/u00/mp4/e/8/1/c/6/45a2b1a2dbea5f2a77feb483eb0fde881dc64d7097b6a24c9489130664c.mp4","encryptionKey":"m+WIUKAlD1lGTYBQ31VAqA=="}],"label":"Stereo Ingles"},{"clips":[{"type":"source","id":4,"path":"/opt/u00/mp4/2/0/e/6/c/58643b97174672144937483346da66a2bb7572f5a9b7edf3e4265b8ca2b.mp4","encryptionKey":"m+WIUKAlD1lGTYBQ31VAqA=="}]},{"clips":[{"type":"source","id":5,"path":"/opt/u00/mp4/8/2/c/3/d/a4df85e213b2cc3a212bf99c88caf92d386b06557ce2cc7db61a4545af1.mp4","encryptionKey":"m+WIUKAlD1lGTYBQ31VAqA=="}]},{"clips":[{"type":"source","id":6,"path":"/opt/u00/mp4/9/3/2/a/0/f745729f8c4b69f43ed9affaf09d0f158ef4dd49ab78df2d01570eb0eee.mp4","encryptionKey":"m+WIUKAlD1lGTYBQ31VAqA=="}]},{"clips":[{"type":"source","id":7,"path":"/opt/u00/mp4/5/a/0/4/f/f156cc33afe26d9e4564a22bf3a40844fa49532030cc82cd40411215672.mp4","encryptionKey":"m+WIUKAlD1lGTYBQ31VAqA=="}]},{"clips":[{"type":"source","id":8,"path":"/opt/u00/mp4/f/7/5/4/2/017088093fb0ea51dc762257d30ccae6a7f86e1679b53a6f966502d5438.mp4","encryptionKey":"m+WIUKAlD1lGTYBQ31VAqA=="}]}]}

This can be a bug???

**Comment by erankor** [comment]
Indeed looks like a bug, try #1005

**Comment by enmaca** [comment]
@erankor problem fixed. 

only as an observation, the use of the vod_hls_force_unmuxed_segments option arises because without this option and having separated the video from the audio, every so often a segment with only audio and no video came.

**Comment by erankor** [comment]
Thanks, merged.
Regarding what you wrote, I'm not familiar with such a phenomenon, normally it can happen only at the end of the video - the last segment may contain only audio/video in case one stream is longer than the other. If you are getting it in the middle of the stream, there may be some problem with the video file, e.g. frames that are too widely spaced.

**Comment by enmaca** [comment]
@erankor Not only in the middle of the stream, it happens every x seconds (multiplied by the duration of the segment) only if the muxing happens in nginx, if it happens in the player everything looks good. If you think it is convenient to open another issue to investigate this behavior, just tell me.

**Comment by erankor** [comment]
yes, please provide the MP4 file and nginx.conf
