### ISSUE TITLE
[Ubuntu 16.04, Standard Installation] 502 Error on urls

### ISSUE THREAD

**Issue by puneetas3** [kaltura/nginx-vod-module#1002]
Hi, I have made a clean installation on a new server with Ubuntu 16.04 with following commands-

```
wget -O - http://installrepo.kaltura.org/repo/apt/xenial/kaltura-deb-256.gpg.key|apt-key add -
echo "deb [arch=amd64] http://installrepo.kaltura.org/repo/apt/xenial naos main" > /etc/apt/sources.list.d/kaltura.list
```

No changes are made to default nginx conf files in `/opt/kaltura/nginx/conf/base.conf`
All ports are open, no iptable rules are set.. Base dir is 'assets'. Uploaded a video 'sample.mp4' in 'assets'.  Here is the url-

`140.82.42.127/assets/sample.mp4/master.m3u8`

Receiving 502 error header on this and on any page. The access and error logs at `/opt/kaltura/log/nginx/` are empty 

Checked nginx process and ports, its working and listening at port 88. What can be the process to track down the error.

**Comment by erankor** [comment]
I suggest trying to fix the logs first... 
I can think of 2 possible reasons for this -
1. Some permission issue on the log folder itself or any of its parents
2. Maybe nginx doesn't write to where you think, you can try to run `lsof | grep nginx | grep log` to see which files are held by nginx

**Comment by puneetas3** [comment]
Hi, thanks for the prompt reply. Here is the requested output with some other useful ones-

```
root@vod:~# lsof | grep nginx | grep log
nginx     21314           root    2w      REG              253,1        0     256954 /opt/kaltura/log/nginx/kaltura_nginx_errors.log
nginx     21314           root    4w      REG              253,1        0     256954 /opt/kaltura/log/nginx/kaltura_nginx_errors.log
nginx     21314           root    5w      REG              253,1        0     256955 /opt/kaltura/log/nginx/kaltura_nginx_access.log
nginx     21315        kaltura    2w      REG              253,1        0     256954 /opt/kaltura/log/nginx/kaltura_nginx_errors.log
nginx     21315        kaltura    4w      REG              253,1        0     256954 /opt/kaltura/log/nginx/kaltura_nginx_errors.log
nginx     21315        kaltura    5w      REG              253,1        0     256955 /opt/kaltura/log/nginx/kaltura_nginx_access.log
```

Checked users/groups of error and access log and sample video file

```
root@vod:~# ls -l /opt/kaltura/log/nginx/error.log
-rw-r--r-- 1 kaltura root 0 Jun  1 17:54 /opt/kaltura/log/nginx/error.log
root@vod:~# ls -l /opt/kaltura/log/nginx/kaltura_nginx_access.log
-rw-r--r-- 1 kaltura root 0 Jun  1 17:54 /opt/kaltura/log/nginx/kaltura_nginx_access.log
root@vod:~# ls -l /opt/kaltura/log/nginx/kaltura_nginx_errors.log
-rw-r--r-- 1 kaltura root 0 Jun  1 17:54 /opt/kaltura/log/nginx/kaltura_nginx_errors.log

root@vod:/assets# ls -l video.mp4
-rw-r--r-- 1 root root 288772802 Sep 21  2018 video.mp4
```
Kaltura user belongs to 2 groups-
```
root@vod:~# groups kaltura
kaltura : kaltura www-data
```
Checking nginx process user and group-
```
root@vod:/assets# ps axfo pid,euser,egroup,args
  PID EUSER    EGROUP   COMMAND
21314 root     root     nginx: master process /opt/kaltura/nginx/sbin/nginx
21315 kaltura  kaltura   \_ nginx: worker process
```
Ports listening on-
```
root@vod:/assets# sudo netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      895/sshd
tcp        0      0 0.0.0.0:88              0.0.0.0:*               LISTEN      21314/nginx
tcp6       0      0 :::22                   :::*                    LISTEN      895/sshd

```
Is there any user permission conflict here?

**Comment by erankor** [comment]
The file permissions look ok, but maybe 'kaltura' doesn't have write permission to one of the folders in the path. Maybe try to run `su kaltura` and then `echo test >> /opt/kaltura/log/nginx/kaltura_nginx_access.log` to see if it works.

**Comment by puneetas3** [comment]
Yes, its writing to the access log as kaltura user. I am a bit confused here with the port of nginx. Is it 88, then shouldn't I access it at `http://140.82.42.127:88/assets/video.mp4/master.m3u8`

It is just a test server. I can share ssh details if needed to understand the configuration issue and then destroy it to create new one. Thanks

**Comment by erankor** [comment]
Yes, you should use 88
