### ISSUE TITLE
I need to help. / hls not working ( just keep 'wating for localhost') 

### ISSUE THREAD

**Issue by JiyeonLuda** [kaltura/nginx-vod-module#1007]
hi !  
I am student and try to install & use vod server but i failed. 
 
I installed Nginx & nginx_vod_module,
at virtual machine / ubuntu 16.04 
( cpu 1 core / mem 1GB / ssd 10gb )
and followed this way.

> -----------------------------------------------------------------

**1. download Nginx source & kaltura - nginx_vod_module**
cd/opt
- nginx:  wget http://nginx.org/download/nginx-1.12.2.tar.gz
- nginx-vod-module : git clone https://github.com/kaltura/nginx-vod-module.git

**2. unzip and configuration**

./configure --add-module=/opt/nginx-vod-module --with-file-aio --with-threads --with-cc-opt="-O3" --prefix=/usr/local/nginx

=> install success !

**3. set  configuration**

at :  /usr/local/nginx/conf/nginx.conf
> -----------------------------------------------------------------
worker_processes  1;
events {  

 worker_connections  1024;

}

http {

    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {

        listen       80;
        server_name  localhost;

        location / {
           root   html;
           index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;

        location = /50x.html {

        root   html;

        }

        # vod settings
        vod_mode local;
        vod_fallback_upstream_location /fallback;
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;

        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        vod_segment_duration 1000;
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        aio on;

       location /vod/ {

                root /usr/local/nginx/html/;

                vod hls;
                add_header Access-Control-Allow-Headers '*';
                add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                add_header Access-Control-Allow-Origin '*';
                expires 100d;
        } 
    #location end
    }
  #server end
}
#http end

> -----------------------------------------------------------------

4. upload mp4 file 
upload to  " /usr/local/nginx/html/test_vod.mp4 "  
(my VOD location root )

5. send request to nginx server ( at firefox )
 to :  " http://localhost/vod/test_vod.mp4/index.m3u8 " 

**But it is not working . just keep waiting for localhost....**

I don't know why it is not working...

I didn't make index.m3u8 file But how it works? 
Is vod_module make m3u8 file ? if it is,  I just guessing my local server had too small memory ( I test at virtual machine) .

I hope to my server to streaming vod. 
Thank you to read my issue.
please help me.

**Comment by erankor** [comment]
Did you verify nginx started successfully? is the process running? is it indeed listening on port 80?
Also, I don't see any 'error_log' directive in the config you pasted. If it is really missing, you should add one, restart nginx, and check the error log file for errors.

**Comment by JiyeonLuda** [comment]
> nginx가 성공적으로 시작되었는지 확인 했습니까? 프로세스가 실행 중입니까? 참으로 포트 80에서 청취하고 있습니까? 
> 또한 붙여 넣은 구성에 'error_log'지시문이 표시되지 않습니다. 실종 되었다면, 하나 추가하고, nginx를 다시 시작하고, 오류 로그 파일에서 오류를 확인해야합니다.

Thank you erankor.  I solved this problem !  ;-) 

my Nginx working well. ( with 80 port )
And I checked  nginx 'error_log' too.

>------------------------------------------------------------------------------------------------
<img width="733" alt="2019-06-12_nginx_errorlog" src="https://user-images.githubusercontent.com/39063893/59327426-72732a80-8d24-11e9-965d-33f3c75c2e3b.png">

>------------------------------------------------------------------------------------------------

so , I made vod directory ( /usr/local/nginx/html/vod/) , and copied test_vod.mp4 file to there.

after, I send request to : " http://localhost/vod/test_vod.mp4/index.m3u8 ".
now it is works .



>  location /vod/ {
>  root /usr/local/nginx/html/; }

I thought it When i send request to " http://localhost/vod/ ", Nginx server will find files at "/usr/local/nginx/html / " But they looking for 'vod' directory at root path.
 
Thank you for your kindness.

**Comment by erankor** [comment]
Great, btw, the reason it's looking under 'vod' is that you used the 'root' directive, if you change it to 'alias' it will look for the files under 'html' (this is standard nginx behavior, not specific to this module)

**Comment by JiyeonLuda** [comment]
> 대단해, btw, 'vod'아래에있는 이유 는 'root'지시어를 사용했을 때 '별칭'으로 변경하면 'html'아래의 파일을 찾습니다 (표준 nginx 동작이 아니라 s 이 모듈에만 해당)

you rock ! Thanks for your answer. now i clearly understand why it is happened.
