### ISSUE TITLE
DASH Clear Key isn't working

### ISSUE THREAD

**Issue by hoang-hai** [kaltura/nginx-vod-module#1015]
Hi everyone,
I have configured DASH + clear key as this configuration (https://github.com/kaltura/nginx-vod-module/blob/master/test/dash_clear_key.php)
but it doesn't work,
Can everyone help me

dash_clear_key.php return as below

> [
>   {
>     "key": "6JDXwILoGcZuYDKGNPiXgA==",
>     "key_id": "ASNFZ4mrze8BI0VniavN7w==",
>     "pssh": [
>       {
>         "uuid": "1077efec-c0b2-4d02-ace3-3c1e52e2fb4b",
>         "data": "AAAAAQEjRWeJq83vASNFZ4mrze8AAAAA"
>       }
>     ]
>   }
> ]

I play with the Shaka player

> player.configure({
>                 drm: {
>                     servers: {
>                         'org.w3.clearkey': 'http://domain/dashkeyserver/dash_clear_key.php'
>                     }
>                 }
>             });

nginx conf

> vod dash;
> vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;
> vod_dash_manifest_format segmenttemplate;
> vod_align_segments_to_key_frames on;		
> vod_drm_enabled on;
> vod_drm_clear_lead_segment_count 0;
> vod_drm_upstream_location /dashkeyserver/;
> vod_drm_request_uri /dash_clear_key.php;

**Comment by hoang-hai** [comment]
can anyone help me :(

**Comment by hoang-hai** [comment]
@erankor Can you help me

**Comment by erankor** [comment]
Are you seeing any errors in the browser console? did you see the player issue a license request? was the license request successful?

**Comment by hoang-hai** [comment]
No errors return

`"GET /path/video.mp4/manifest.mpd HTTP/1.1" 200 2842 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"`

`"GET /dash_clear_key.php HTTP/1.0" 200 171 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"`

Do I need to change anything in this file?
https://github.com/kaltura/nginx-vod-module/blob/master/test/dash_clear_key.php

**Comment by erankor** [comment]
I think that since the browser handles it like DRM, everything has to be HTTPS

**Comment by hoang-hai** [comment]
I have used two links above with https but also still error, 
does the **dash_clear_key.php** file have any problems? I have not changed anything from the example file

**Comment by hoang-hai** [comment]
it was fixed, thank you

**Comment by minhpl** [comment]
> it was fixed, thank you

Hi Hoang Hai, what do you do to fix it?
