### ISSUE TITLE
Errors during make

### ISSUE THREAD

**Issue by Another1982** [kaltura/nginx-vod-module#1017]
This Error Occures during make of a nginx-1.17.1 compile with nginx-vod-module on a fedora 30 system:
make -f objs/Makefile
make[1]: Entering directory '/download/nginx-1.17.1'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I /usr/include/libxml2 \
        -o objs/addon/mp4/mp4_parser.o \
        ../nginx-vod-module//vod/mp4/mp4_parser.c
In file included from src/core/ngx_core.h:51,
                 from ../nginx-vod-module//vod/mp4/../input/../common.h:91,
                 from ../nginx-vod-module//vod/mp4/../input/read_cache.h:5,
                 from ../nginx-vod-module//vod/mp4/../input/frames_source.h:5,
                 from ../nginx-vod-module//vod/mp4/../media_format.h:5,
                 from ../nginx-vod-module//vod/mp4/mp4_parser_base.h:4,
                 from ../nginx-vod-module//vod/mp4/mp4_parser.h:5,
                 from ../nginx-vod-module//vod/mp4/mp4_parser.c:1:
../nginx-vod-module//vod/mp4/mp4_parser.c: In function 'mp4_parser_parse_frames':
src/core/ngx_string.h:88:42: error: 'memset' offset [105, 248] from the object at 'context' is out of the bounds of referenced subobject 'stss_start_pos' with type 'const uint32_t *' {aka 'const unsigned int *'} at offset 96 [-Werror=array-bounds]
   88 | #define ngx_memzero(buf, n)       (void) memset(buf, 0, n)
      |                                          ^~~~~~~~~~~~~~~~~
../nginx-vod-module//vod/mp4/../input/../common.h:139:29: note: in expansion of macro 'ngx_memzero'
  139 | #define vod_memzero(buf, n) ngx_memzero(buf, n)
      |                             ^~~~~~~~~~~
../nginx-vod-module//vod/mp4/mp4_parser.c:3114:3: note: in expansion of macro 'vod_memzero'
 3114 |   vod_memzero(&context.stss_start_pos, sizeof(context) - offsetof(frames_parse_context_t, stss_start_pos));
      |   ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1914: objs/addon/mp4/mp4_parser.o] Error 1
make[1]: Leaving directory '/download/nginx-1.17.1'
make: *** [Makefile:8: build] Error 2

The make config string:
./configure --add-module="../nginx-vod-module/" --with-file-aio --with-threads
Some Version Numbers:
GNU Make 4.2.1
gcc (GCC) 9.1.1 20190503 
kernel: 5.1.16-300.fc30.x86_64
used yesterdays master of the nginx-vod-module git export

**Comment by erankor** [comment]
This is what happens when compilers try to be too smart... 
Try to change this line to - 
```
vod_memzero((void*)&context.stss_start_pos, sizeof(context) - offsetof(frames_parse_context_t, stss_start_pos));
```
If that doesn't help, try maybe - 
```
vod_memzero((u_char*)&context + offsetof(frames_parse_context_t, stss_start_pos), sizeof(context) - offsetof(frames_parse_context_t, stss_start_pos));
```

**Comment by Another1982** [comment]
First Solution Test:
make -f objs/Makefile
make[1]: Entering directory '/download/nginx-1.17.1'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I /usr/include/libxml2 \
        -o objs/addon/mp4/mp4_parser.o \
        ../nginx-vod-module//vod/mp4/mp4_parser.c
In file included from src/core/ngx_core.h:51,
                 from ../nginx-vod-module//vod/mp4/../input/../common.h:91,
                 from ../nginx-vod-module//vod/mp4/../input/read_cache.h:5,
                 from ../nginx-vod-module//vod/mp4/../input/frames_source.h:5,
                 from ../nginx-vod-module//vod/mp4/../media_format.h:5,
                 from ../nginx-vod-module//vod/mp4/mp4_parser_base.h:4,
                 from ../nginx-vod-module//vod/mp4/mp4_parser.h:5,
                 from ../nginx-vod-module//vod/mp4/mp4_parser.c:1:
../nginx-vod-module//vod/mp4/mp4_parser.c: In function 'mp4_parser_parse_frames':
src/core/ngx_string.h:88:42: error: 'memset' offset [105, 248] from the object at 'context' is out of the bounds of referenced subobject 'stss_start_pos' with type 'const uint32_t *' {aka 'const unsigned int *'} at offset 96 [-Werror=array-bounds]
   88 | #define ngx_memzero(buf, n)       (void) memset(buf, 0, n)
      |                                          ^~~~~~~~~~~~~~~~~
../nginx-vod-module//vod/mp4/../input/../common.h:139:29: note: in expansion of macro 'ngx_memzero'
  139 | #define vod_memzero(buf, n) ngx_memzero(buf, n)
      |                             ^~~~~~~~~~~
../nginx-vod-module//vod/mp4/mp4_parser.c:3115:17: note: in expansion of macro 'vod_memzero'
 3115 |                 vod_memzero((void*)&context.stss_start_pos, sizeof(context) - offsetof(frames_parse_context_t, stss_start_pos));
      |                 ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1914: objs/addon/mp4/mp4_parser.o] Error 1
make[1]: Leaving directory '/download/nginx-1.17.1'
make: *** [Makefile:8: build] Error 2

The 2nd Solution looks like work:
The NGINX was builded without errors.
Short test for the start and curl the index file worked.
Looks like ok will performe further tests but looks fine.
**Thank you so much for the Fast Help!!! 
KR
Markus**

**Comment by Another1982** [comment]
As fare as i could test everthing works as aspect. THX again

**Comment by erankor** [comment]
Merged, thanks
