### ISSUE TITLE
MSS and HLS DRM

### ISSUE THREAD

**Issue by gandinod** [kaltura/nginx-vod-module#102]
Hello,
Is it correct that DRM is supported only for DASH?

vod_drm_enabled

syntax: vod_drm_enabled on/off
default: off
context: http, server, location
When enabled, the module encrypts the media segments according to the response it gets from the drm upstream. Currently supported only for dash.

Any plans to support it on HLS and MSS?

Thanks!

**Comment by erankor** [comment]
Also supported for MSS (Play Ready), I will update the readme.
For HLS, the module supports AES 128 encryption (not DRM), afaik, there is no single standard for DRM encryption on HLS (there are several different schemes used by different vendors)

**Comment by gandinod** [comment]
Thanks
