### ISSUE TITLE
Generate sprite/vtt thumbnail file with nginx-vod-module?

### ISSUE THREAD

**Issue by izay4kun** [kaltura/nginx-vod-module#1020]
Hey guys, so for the past few days i'm struggling with a way to generate a thumbnail-sprite.jpg to then call it on a thumbnail.vtt, is there a way to do it automatically with nginx-vod-module? i'm already using vod thumb, images are generating smoothly if use the param thumb-1000.jpg etc.

But i need a vtt file based on a sprite with all scenes from the video, i did some workarounds like using php/ffmpeg to do it manually but i have more than 20k videos, so i was hoping that the module has something that i'm missing! Thank you.

Something like: https://example.com/thumb/file.mp4/thumbnails.vtt

**Comment by erankor** [comment]
Not supported.
Is this a jwplayer-specific feature or are there more players that support this format?

**Comment by izay4kun** [comment]
Videojs (with extension), fluid player etc. But in my case it is jwplayer, well that's sad, but hey @erankor thank you for the quick reply!

**Comment by erankor** [comment]
Well, if it somehow gets into the HLS spec, I may consider it :)
