### ISSUE TITLE
Inconsistency of styp, tfhd and ISO/IEC 14496-12

### ISSUE THREAD

**Issue by xoiss** [kaltura/nginx-vod-module#1021]
**The problem relates to MP4 segments and their compliancy with ISO/IEC 14496-12.**

Current implementation utilizes `default-base-is-moof (0x020000)` flag of the `tfhd` box.

On the other hand, `styp` box manifests the file's (the MP4 segment's) compliancy with brands `isom,iso6,dash` -- note, _the `isom` brand is listed_.

But ISO/IEC 14496-12 states:
> The presence of a brand in the `compatible_brands` list of the `ftyp` box is a claim and a permission. It is a claim that the file conforms to all the requirements of that brand, and a permission to a reader implementing potentially only that brand to read the file.

> **Support for the `default-base-is-moof` flag is required under the ‘iso5’ brand, and it shall not be used in brands or compatible brands earlier than iso5.**

> NOTE The use of the `default-base-is-moof` flag breaks the compatibility to earlier brands of the file format, because it sets the anchor point for offset calculation differently than earlier. Therefore, **the `default-base-is-moof` flag cannot be set when earlier brands are included in the File Type box**.

The Segment Type (styp) box is about the same as File Type (ftyp) box
> A segment type (styp) has the same format as an 'ftyp' box [4.3], except that it takes the box type 'styp'.

---

So, either the `styp` box shall not mention `isom` brand in the list of compatible brands, or the `tfhd` box shall not use (set to 1) the `default-base-is-moof (0x020000)` flag.

---

Actually, if there is only one `traf/tfhd` (track fragment) per each `moof` (movie fragment), the `default-base-is-moof (0x020000)` flag value has no meaning. It's value influences only the second and further track fragments within the same movie fragment.

However, I can see code in nginx-vod-module that potentially may produce a number of track fragments in a single movie fragment:
https://github.com/kaltura/nginx-vod-module/blob/3b1d656d1e22d9d775ba68c5bce093152eef4e7d/vod/mp4/mp4_muxer.c#L682

Due to this, it's not possible just to clear the `default-base-is-moof (0x020000)` flag:
https://github.com/kaltura/nginx-vod-module/blob/3b1d656d1e22d9d775ba68c5bce093152eef4e7d/vod/mp4/mp4_fragment.c#L25

To remove this flag and become true compatible with `isom`, this function shall be reworked:
https://github.com/kaltura/nginx-vod-module/blob/3b1d656d1e22d9d775ba68c5bce093152eef4e7d/vod/mp4/mp4_muxer.c#L381

Another way: not to claim the compatibility (that is actually broken) with `isom` -- to remove it from the brands list in `styp` box:
https://github.com/kaltura/nginx-vod-module/blob/3b1d656d1e22d9d775ba68c5bce093152eef4e7d/vod/dash/dash_packager.c#L250

But, I'm not sure if it's Ok to completely remove compatibility with the legacy version of MP4 format.

---

What do you think?

**Comment by erankor** [comment]
Thanks you very much for the detailed feedback. 
At this point, unless there is a concrete playback issue, I'd rather not touch the implementation, as it requires major regression tests across platforms and has a significant risk.

**Comment by xoiss** [comment]
> Thanks you very much for the detailed feedback.
> At this point, unless there is a concrete playback issue, I'd rather not touch the implementation, as it requires major regression tests across platforms and has a significant risk.

Hello, @erankor !
Thank you for reply!
Ok, we'll continue using the de-facto existing implementation.
If we faced a compatibility issue with a legacy decoder, I'll reopen this question.
Thank you!
- Alex (aka xoiss)
