### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by jalowin** [kaltura/nginx-vod-module#1024]
Hi everybody, I am using the base local conf in my nginx and always that I play my video obtain this error in nginx's logs

2019/07/23 10:42:47 [error] 5649#5649: *1 ngx_file_reader_update_state_file_info: open() "/root/videos/bbb.mp4" failed (13: Permission denied), client: 188.76.207.124, server: sportsvr.tv, request: "GET /content/bbb.mp4/index.m3u8 HTTP/1.1", host: "sportsvr.tv"

My files are in

/root/videos

This is my config

        # vod settings
        vod_mode local;
        vod_fallback_upstream_location /fallback;
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;

        # vod caches
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        # file handle caching / aio
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        aio on;

        location /content/ {
                alias /root/videos/;
                vod hls;

                vod_base_url "https://sportsvr.tv/";
                vod_segments_base_url "https://sportsvr.tv/";

                add_header Access-Control-Allow-Headers '*';
                add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                add_header Access-Control-Allow-Origin '*';
                expires 100d;
        }

Thanks for all

Best regards

**Comment by jalowin** [comment]
directory permissions, set ok 

Sorry

**Comment by NangenX** [comment]
my solution change the SELINUX=enforcing to SELINUX=disabled and reboot the server.
