### ISSUE TITLE
Weird problem with failed identify the file format while reading media header

### ISSUE THREAD

**Issue by dastious** [kaltura/nginx-vod-module#1027]
[videoproblem.zip](https://github.com/kaltura/nginx-vod-module/files/3436324/videoproblem.zip)

So I use nginx vod in mapped config with an api that return segmented file that I record with ffmpeg. Like a replay manager.

It's weird because it return  :

`ngx_http_vod_identify_format: failed to identify the file format .....FILEPROBLEME.mp4 while reading media header, client: 10.10.10.125, server: , request: "GET /hls/test.json/master.m3u8`

The file seems good it's h264 with ac3. But if I do : 
`ffmpeg -i FILEPROBLEME.mp4 -c copy FILEPROBLEME2.mp4`

And ask the api to return this file, everything is working fine with fileprobleme2.mp4.
So I don't understand, not sure what's wrong or if it's a bug.

Can I upload the file somewhere ?

**Comment by erankor** [comment]
If your nginx server is accessible, easiest solution would be to set up some location to serve the file.
Another option, that few people here used in the past, is to upload the video to Drive and share the link.

**Comment by dastious** [comment]
I made a zip with the file

**Comment by erankor** [comment]
URL?

**Comment by dastious** [comment]
It's the first link, in the first comment that I updated.

https://github.com/kaltura/nginx-vod-module/files/3436324/videoproblem.zip

**Comment by erankor** [comment]
This is not an MP4 -
```
# mediainfo FILEPROBLEME.mp4
General
ID                                       : 1 (0x1)
Complete name                            : FILEPROBLEME.mp4
Format                                   : MPEG-TS
...
```
MPEG-TS input is not supported.

**Comment by dastious** [comment]
Okay, understood. Thank you.
