### ISSUE TITLE
Question about integrating irdeto drm

### ISSUE THREAD

**Issue by dionisioC** [kaltura/nginx-vod-module#1028]
Hello everyone 

This question is similar to #1025 but with irdeto as drm provider.

Has anyone integrated irdeto as drm provider? I am not able to find any documentation.

The problem (I think) is with the key ID which is in a GUID format like aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa and is expecting a base64 encoded key identifier (128 bit) key_id. 

I tried several approaches but no luck with any of them.

This is related to widevine but also any help with playready and fairplay is welcome

**Comment by erankor** [comment]
Have no experience with Irdeto, but regarding the key id, the problem may be related to byte order. A GUID is composed of DWORD, WORD, WORD, BYTEs, the byte order of DWORD + 2 WORDs may be reversed, you can try to flip them.

**Comment by dionisioC** [comment]
Thanks @erankor! but I am not sure if I followed you. 
Checking the encoding I was doing, I found a we that gave me different results as they were using little endian. This is what you mean or other thing?

**Comment by erankor** [comment]
What I meant is to try and swap the bytes of the GUID DWORD/WORDs (little/big endian), and see if it helps. 
E.g. if you currently try with 12345678-aabb-ccdd-xxx, try 78563412-bbaa-ddcc-xxx

**Comment by dionisioC** [comment]
I have done an example in nodejs that I think reflects what you say

`    const uuidParse = require('uuid-parse');
      const uuidParseLe = require('uuid-parse-le');

      const UUID = 'd8c56de7-e530-4758-9bab-29284c85d974';
      console.log('UUID', UUID);
      let bytes = uuidParseLe.parse(UUID);
      let buff = Buffer.from(bytes);
      console.log('Little endian encoded', uuidParse.unparse(bytes));
      let KeyIdBase64 = buff.toString('base64');
      console.log('Little endian encoded base 64', KeyIdBase64);

      bytes = uuidParse.parse(UUID);
      buff = Buffer.from(bytes);
      console.log('encoded', uuidParse.unparse(bytes));
      KeyIdBase64 = buff.toString('base64');
      console.log('encoded base 64', KeyIdBase64);`

The output is

`UUID d8c56de7-e530-4758-9bab-29284c85d974
Little endian encoded e76dc5d8-30e5-5847-9bab-29284c85d974
Little endian encoded base 64 523F2DDlWEebqykoTIXZdA==
encoded d8c56de7-e530-4758-9bab-29284c85d974
encoded base 64 2MVt5+UwR1ibqykoTIXZdA==
`

Unfortunately it is not working, but at this point I am not sure if it is the key or something else

**Comment by erankor** [comment]
Yes, this is what I meant... unfortunately, I don't have any experience with Irdeto.

**Comment by dionisioC** [comment]
Thanks for the help @erankor ! I will keep trying 👍

**Comment by flavioribeiro** [comment]
hey @dionisioC any progress on this?

**Comment by dionisioC** [comment]
> hey @dionisioC any progress on this?

No progress here, when I have something I will publish here so the knowledge will be here

**Comment by zsiec** [comment]
@dionisioC I've had some initial success with tests using Fairplay. I'm converting the `contentId` to base64 using a method like the following: `python -c "import uuid; import base64;print(base64.b64encode(uuid.UUID(\"your-uid-here\").bytes_le))"`

**Comment by dionisioC** [comment]
> @dionisioC I've had some initial success with tests using Fairplay. I'm converting the `key_id` to base64 using a method like: `python -c "import uuid; import base64;print(base64.b64encode(uuid.UUID(\"your-key_id-here\").bytes_le))"`

Thanks, I will try to check asap

**Comment by zsiec** [comment]
@dionisioC not sure where you are with this, but in case it's helpful, you can see what we're trying here: https://github.com/cbsinteractive/drm-proxy We've gotten successful playback with Fairplay and Widevine and are testing PlayReady now.

**Comment by dionisioC** [comment]
Thanks @zsiec !!! that looks amazing. The last thing I checked was using cpix as seems with ezdrm the endpoint is cpix and it was working, but I don't have the time to work on this so I dont know if that is going to work.

The example is here

```
https://www.ezdrm.com/Documentation/EZDRM%20Integration%20with%20Kaltura%20CE%20-%20Nginx%20v1.0.pdf

page 5
vod_drm_upstream_location /drmdashinfo;
 vod_drm_enabled on;
 vod_drm_request_uri "u=username&p=password&c=$2"; 

location /drmdashinfo {
 internal;
 proxy_pass "http://cpix.ezdrm.com/kaltura.aspx?";
 } 
```

I close the issue ass seems you have done an outstanding progress
