### ISSUE TITLE
AVERAGE-BANDWIDTH attribute in HLS-manifests for VBR encoding

### ISSUE THREAD

**Issue by sunny1403** [kaltura/nginx-vod-module#1029]
Hello! 

My name is Maria, I'm Head of RnD team at ivi. ivi is online cinema number one in Russia.
We're using nginx-vod-module for VOD. It's  really great! Thank you so much for your job!

We have encountered some difficulties and need  your help=)

Prehistory: 

* Our content catalogue is about 120 000 titles 
* We use VBR encoding settings, which gives us difference between average and peak bit rates about 100% of the average bitrate. it meets Apple's specification: "1.30. For VOD content the peak bit rate SHOULD be no more than 200% of the average bit rate." For example, ffmpeg avg bitrate is 5.1 mbps, peak bitrate is 9.8 mbps
* As we understand, in case of adaptive streaming to specify the correct bitrates critically important for correct job of the ABR-algorithm on the player side. 

    * Apple's specification: 1.26. For VOD content, the average segment bit rate MUST be within 10% of the AVERAGE-BANDWIDTH attribute. (See Declared versus measured values of bandwidths.)
    * Apple's specification: 1.27. For VOD content, the measured peak bit rate MUST be within 10% of the BANDWIDTH attribute.
    * SO/IEC 23009-1: Consider a hypothetical constant bitrate channel of bandwidth with the value of this attribute in bits per second (bps). Then, if the Representation is continuously delivered at this bitrate, starting at any SAP that is indicated either by @startWithSAP or by any Segment Index box, a client can be assured of having enough data for continuous playout providing playout begins after @minBufferTime * @bandwidth bits have been received (i.e. at time @minBufferTime after the first bit is received). For dependent Representations this value specifies the bandwidth according to the above definition for the aggregation of this Representation and all complementary Representations.
* We notice 
    * There'is no AVERAGE-BANDWIDTH attribute in HLS-manifests created by nginx-vod-module
    * BANDWIDTH attribute in HLS master-manifest and bandwidth attribute in DASH manifests created by nginx-vod-module seems like ffmpeg avg bitrate (i know you analyse first 100K frames) for our encoding settings.
    * as the result, we had non-compliant bandwidth attributes for our encoding settings
* We conducted a series of experiments to change the bandwidth values  and got positive results in user experience
    * HLS: increasing the average playback bitrate 
    * DASH: reducing playback problems (stall events)

We would ask you 
* to add AVERAGE-BANDWIDTH attribute to HLS master-manifests
* to give us an opportunity  to set BANDWIDTH attribute, AVERAGE-BANDWIDTH attribute (HLS), bandwidth attribute (DASH, MSS) via JSON  relying on information  stored in our database. As I understand, we already can use 'bitrate' parameter for HLS BANDWIDTH attribute, DASH and MSS bandwidth attribute https://github.com/kaltura/nginx-vod-module#sequence
* also we find it interesting to test different vod_segment_duration values for different devices. Now we have to set the values in the config, which is not very convenient
Let's find the best solution together=)

We are ready to consider any kind of cooperation convenient for you.
Please contact us with any questions
* Maria Belyakova, Head of RnD - mbelyakova@ivi.ru 
* Evgeny Rossinsky, Chief Technology Officer - erossinsky@ivi.ru 

Best regards, 
Maria Belyakova
ivi.ru

**Comment by zoharbabin** [comment]
Thank you for using Kaltura and the feedback!
Igor from our team will reach out via email to discuss further.
