### ISSUE TITLE
nginx-vod-module with nginx secure link

### ISSUE THREAD

**Issue by artnurr** [kaltura/nginx-vod-module#1031]
Hello!
Please help me with this issue.
My conf is
`server {
    listen 443 ssl http2;

...

        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        vod_mode local;
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 256m;

        location /vd/ {				
            alias /var/vid/3OQ/;			
            vod hls;

			vod_segments_base_url "";
			vod_align_segments_to_key_frames on;
            		vod_manifest_segment_durations_mode accurate;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;	
location ~* \.(m3u8)$ {
     set $sec secret111;
        secure_link $arg_t,$arg_e;
        secure_link_md5 $remote_addr$arg_e$sec;
		if ($secure_link = ""){
            return 403;
        }

        if ($secure_link = "0") {
            return 403;
        }
	}	
}`
nginx version: nginx/1.16.0
I have installed also nginx-secure-token-module.
Tokens working from all ips. What's wrong?
Location of m3u8 for nginx-rtmp-module works fine for live streams.
I need to get this construct of url
https://domain.ltd/vd/tet5/221.mp4/index.m3u8?t=o7nRk4tbQcSw&e=1565391948

**Comment by artnurr** [comment]
Fixed myself

**Comment by AquileaSFX** [comment]
Hello @artnurr 

how did you solve it sir?

thank you.

**Comment by artnurr** [comment]
@AquileaSFX hello!
Add to location
`secure_token_types application/vnd.apple.mpegurl;
secure_token $args;`

**Comment by ylouylou** [comment]
> @AquileaSFX hello!
> Add to location
> `secure_token_types application/vnd.apple.mpegurl; secure_token $args;`

HI Could you post a complete working nginx.conf file?

or email me: ylouylou@gmail.com

Thanks a lot.

**Comment by michaeltoohig** [comment]
Just add the line @artnurr gave to the `/hls` location block. It will automatically append the original request args to the video file segment urls.
