### ISSUE TITLE
How to distinguish URIs of multi subtitles in HLS master playlist?

### ISSUE THREAD

**Issue by peipeiguo** [kaltura/nginx-vod-module#1032]
Hi, 
With mapped mode of vod-module, I want to support HLS live vedio with WebVTT subtitles. 
1: Should generate multi subtiltes when client try to get HLS master m3u8 file. 
2: I think client will choose one subtitle URI and try to get the subtitle media m3u8 file.
3: Client will get the vtt segments according to the subtitle m3u8 file.

But acturally, all the subtitle URIs in m3u8 file are same, seems have some prblems:
```
#EXTM3U

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs0",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES,URI="test.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs0",LANGUAGE="fr",NAME="France",AUTOSELECT=NO,DEFAULT=NO,URI="test.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs0",LANGUAGE="cn",NAME="Chinese",AUTOSELECT=NO,DEFAULT=NO,URI="test.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=462564,RESOLUTION=640x360,FRAME-RATE=25.000,CODECS="avc1.4d401e,mp4a.40.2",AUDIO="audio0",SUBTITLES="subs0"
test-v1-a1.m3u8
```

I checked the function `manifest_utils_append_tracks_spec`, but it only add media type letter for vedio and audio. So subtitle URI is only the `prefix.m3u8`.
I read the filename structure in readme, it does not mention any rule about the subtitle media playlist name. 
Any one who know how to distinguish URIs of multi subtitles in HLS master playlist?

**Comment by erankor** [comment]
Can you provide a sample mapping JSON? 
I'm not sure how you got this result, I'd expect something like test-f1.m3u8.

**Comment by peipeiguo** [comment]
I am trying to get the subtitles dirrectly from subtitle tracks in mp4 file, not from seperately srt files. As vod-module do not support this scenario, I got this result. I want to change code to support this.

JSON content for vod type as below:
```
{
   "discontinuity" : false,
   "durations" : [ 5960 ],
   "playlistType" : "vod",
   "segmentDuration" : 6000,
   "sequences" : [
      {
         "clips" : [
            {
               "path" : "/home/test/20190815101006-1500-179.mp4",
               "type" : "source"
            }
         ]
      }
   ]
}
```

**Comment by erankor** [comment]
So yes, track selection for subtitles is not supported, because in the existing code, it is not possible to generate such a scenario.
You'll probably need to assign some letter to identify the subtitles media type (maybe t=text, since s & c are already used) and handle it both in the request parsing code and in the URL generation code.

**Comment by peipeiguo** [comment]
Thanks for your good suggestions. I will use letter t (text) to identify subtitles media type. 
The difficult is to process the subtitle frames. I think need refer hls_ts_segment_request code to make sure the exsiting code can go to STATE_FILTER_FRAMES state. It is a little complex for the code of reading frames.

**Comment by peipeiguo** [comment]
Thanks erankor. Close the issue as I know how to do.
