### ISSUE TITLE
mp4_cenc_encrypt_video_write_buffer: Packet size too big

### ISSUE THREAD

**Issue by leejunkit** [kaltura/nginx-vod-module#1040]
Trying to play one of my files through DRM result in a 404 from the 3rd segment onwards and this error showing up in the logs: 

```
2019/09/09 09:10:50 [error] 10#10: *57790198 mp4_cenc_encrypt_video_write_buffer: packet size 185116778 too big, nalu size 4, frame size 136929 while sending to client, client: 10.0.0.26, server: localhost, request: "GET /dash-hq/0deb3099-c08c-4cec-ac93-8aaffbf2c586/s-3-f1-v1-x3.m4s HTTP/1.1", host: "example.com"
```
Not very sure what is causing this... we've tried to re-encode the source asset multiple times, changing multiple presets, but to no avail. 

Any pointers would be much appreciated!

**Comment by erankor** [comment]
This error usually implies that the file is corrupt - a frame of size 136K contains an h264/5 packet with size=185M...
Does the file play correctly without DRM?

**Comment by leejunkit** [comment]
You're right, playing without DRM fails too. What's strange is that the source MP4 files play fine. We'll keep working at it!
