### ISSUE TITLE
hcxdumptool.c:20:10: fatal error: openssl/evp.h: No such file or directory

### ISSUE THREAD

**Issue by Mikewins1** [kaltura/nginx-vod-module#1046]
Kali Linux Virtualbox
After running the make command this is what happens.  I have never had this before.  I purged openssl and then reinstalled and got same error

root@kali:~/hcxdumptool# make install
cc -O3 -Wall -Wextra -std=gnu99  -o hcxpioff hcxpioff.c 
cc -O3 -Wall -Wextra -std=gnu99  -o hcxdumptool hcxdumptool.c  -lcrypto
hcxdumptool.c:20:10: fatal error: openssl/evp.h: No such file or directory
   20 | #include <openssl/evp.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:21: build] Error 1

**Comment by erankor** [comment]
Wrong repo? how is this related to this module?

**Comment by Mikewins1** [comment]
I apologize. I'm new to Linux and kali and was following an online instructions. How do I get the correct one

**Comment by erankor** [comment]
The dump shows you're trying to compile https://github.com/ZerBea/hcxdumptool, this repo is https://github.com/kaltura/nginx-vod-module, I don't understand why you decided to post here...

**Comment by Mikewins1** [comment]
I apologize. Now that I'm reading deeper into this I don't understand either. Somehow Google pointed me here and I apologize and look stupid. Sorry
