### ISSUE TITLE
504 when there is no file

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#1050]
Hi! I use remote mode, when there is no file on remote nas, kaltura responces with 504 instead of 404, is there any way to resolve it?

**Comment by erankor** [comment]
If you get 504, it probably means that nginx timed out while trying to pull the MP4 from upstream. If there is no file, I'd expect the upstream to return 404, and in that case, IIRC, the module will respond with 404 as well.

**Comment by erankor** [comment]
In what you pasted, the URLs do not match - 3800 is not listed in the multi URL.
Anyway, you can try to capture the traffic with the tcpdump, clearly the upstream did not respond.

**Comment by kuznetcoff777** [comment]
My fault, replaced urls not accureately, changed it.
Yep, i will try to tcpdump

**Comment by kuznetcoff777** [comment]
I had in config 4 remote upstreams, two of them marked as backup, i deleted them, just two remained.

![404](https://user-images.githubusercontent.com/15265762/65518182-87975200-deec-11e9-9510-14ae39ebdb55.png)
Both of them gives 404, but in error lig i see this:
`[error] 30215#30215: *1039706 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client,]`

in acces log i see 502

**Comment by erankor** [comment]
Yes, 502 makes more sense... the module returns 502 for any invalid status code returned from upstream (what I wrote earlier was wrong...)

**Comment by kuznetcoff777** [comment]
So here is my main question, why 404 is concenred as invalid status? Why not to give 404 status to client? We collect statistics for responces to clients and we cannot separate which one is related to invalid urls and which one are related to real problems with kaltura

**Comment by erankor** [comment]
From the module's perspective - it tried to pull data from upstream, and failed, hence "bad gateway". 
This status is returned when -
1. The upstream returned an unexpected status (not 200/206)
2. The upstream sent only partial data
3. The configured buffer size for upstream response is insufficient
It will not be returned in case of an invalid MP4, request for non-existing segment etc.

If you want more details on the specific status returned from upstream, you can try nginx's $upstream_status variable.

**Comment by kuznetcoff777** [comment]
But 404 - is not unknown reason, it is pretty clear status for module.
Is there any way to fix it on code of module? I still see no reason not to do it.

Or it shoud be done via some workaround such as:
if $upstream_status=404, then $status = 404

**Comment by erankor** [comment]
Sorry, I'm not going to change the code to handle this status explicitly.
You can try to change the status using some nginx rewrite logic, as you wrote, or just output more error info to log as I suggested. If you choose the second option, you can also print $vod_status, that provides more details on errors generated by this module.

**Comment by znorris** [comment]
@kuznetcoff777 Do you mind sharing your final resolution? I'd really like to send a 404 to requesting clients.

I haven't had luck with `upstream_status` being set. I've seen examples of setting the `error_page` directive but that hasn't gotten me anywhere either. I was trying not to bring in another module, such as lua.
