### ISSUE TITLE
7 hour duration encode fails with max frames error

### ISSUE THREAD

**Issue by bitbytebit-cr** [kaltura/nginx-vod-module#1057]
2019/10/10 16:10:40 [error] 3173#3173: *480150 mp4_parser_parse_stts_atom: frame count exceeds the limit 1048576, client: 10.0.0.1, server: ~v\.(cx|etp)-proto0\.com$, request: "GET /encode.mp4/index-v1-a1.m3u8 HTTP/1.1", host: "v.etp-proto0.com"

#3173: *480150 mp4_parser_parse_stts_atom: frame count exceeds the limit 1048576

https://github.com/kaltura/nginx-vod-module/blob/3b1d656d1e22d9d775ba68c5bce093152eef4e7d/vod/mp4/mp4_parser.c#L1031

Interesting file: https://github.com/kaltura/nginx-vod-module/blob/bda77e2cd782654fdf2d7f7f17267aa1dbc6c4ed/vod/media_format.h#L19 with Limits (doesn't seem to be the main issue)

hitting max_frame_count:
https://github.com/kaltura/nginx-vod-module/blob/b91f8a6f765535c4791794867c1c23cc6385b4f9/ngx_http_vod_module.c#L51

https://github.com/kaltura/nginx-vod-module/blob/b91f8a6f765535c4791794867c1c23cc6385b4f9/ngx_http_vod_module.c#L1516

Source video file mediainfo -F output...
[out.txt](https://github.com/kaltura/nginx-vod-module/files/3714525/out.txt)

**Comment by erankor** [comment]
It makes sense - 7H x 3600 x 60fps = 1512000.
You're probably using `vod_manifest_segment_durations_mode accurate`, disabling it would solve the issue.

**Comment by Leeaandrob** [comment]
The same here, disabling the error is gone!

**Comment by misiek08** [comment]
Can we make this a config parameter? I can try making PR with changes, but I need to know if patch will be accepted :)

**Comment by erankor** [comment]
I'm ok with having this limit configurable
