### ISSUE TITLE
Not Found!

### ISSUE THREAD

**Issue by thinkwithever** [kaltura/nginx-vod-module#1058]
Vod setup link broken please help

http://installrepo.kaltura.org/repo/apt/xenial/kaltura-deb-256.gpg.key

Ubuntu 16.04 all version error

**Comment by jessp01** [comment]
Hello @thinkwithever,

Please use http://installrepo.origin.kaltura.org/repo/apt/xenial-15.8.0 instead of http://installrepo.kaltura.org/repo/apt/xenial pro tem.

We'll fix the symlink shortly.

**Comment by SlaSerX** [comment]
how to add new repo ? old repo not work

**Comment by SlaSerX** [comment]
yes its work

**Comment by jessp01** [comment]
Symlink is now in place.
Thanks for reporting.
