### ISSUE TITLE
Building on Arch Linux 32bit fails with error: cast to pointer from integer of different size 

### ISSUE THREAD

**Issue by iomihai** [kaltura/nginx-vod-module#1061]
Building on Arch Linux ARM 32bit (on a Raspberry Pi) failed with

../nginx-vod-module/vod/hls/hls_muxer.c: In function 'hls_muxer_init_id3_stream':
../nginx-vod-module/vod/hls/hls_muxer.c:271:31: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
   cur_track->frame.size = p - (u_char*)cur_track->frame.offset;

How can I get this to build?
Thank you.

**Comment by erankor** [comment]
Please try this pull #1062

**Comment by iomihai** [comment]
The issue is fixed for me, thank you for the quick response.
