### ISSUE TITLE
nginx-aws-auth module not working with multiple bitrate ?

### ISSUE THREAD

**Issue by scoo-by-18** [kaltura/nginx-vod-module#1067]
Hello,
First of all, huge congratulations for you amazing work on nginx-vod-module ! It really rocks :)

for a small project, I have to set up a streaming server with MP4 located on AWS S3.

I used your new module nginx-aws-auth but it seems it is not working correctly with multiple bitrate ( but works well on each streams separately ).

I have 3 different resolutions file: 360p.mp4, 540p.mp4, 720p.mp4

here the sample url I am using: 
`https:/myserver/web/test/,36,54,72,0p.mp4.urlset/master.m3u8`

In order to work, I need to enter this URL 3 times.

The first time, 720p.mp4 access was ok, but got:
`http proxy status 403 "403 Forbidden"` on the 540p.mp4

The second time, got 403 on 360p.mp4, and the third time, it works.

I am using openresty 1.13.6.2 ( because I need some LUA operations ).

My nginx sample config: 

[nginx_debug_test.conf.txt](https://github.com/kaltura/nginx-vod-module/files/3808826/nginx_debug_test.conf.txt)

The error log after 1st call:
[nginx-vod-debug.txt](https://github.com/kaltura/nginx-vod-module/files/3808853/nginx-vod-debug.txt)

Any hint of what I am doing wrong ?

Many thanks for your help.

Cheers.

**Comment by erankor** [comment]
This may be because of nginx's variable caching, try changing the `0` in:
https://github.com/kaltura/nginx-aws-auth-module/blob/master/ngx_http_aws_auth_module.c#L870
to:
`NGX_HTTP_VAR_NOCACHEABLE`

**Comment by scoo-by-18** [comment]
Damned ! It's working !
Many thanks for your help.
Cheers.

**Comment by erankor** [comment]
Thanks, merged
