### ISSUE TITLE
Problem with remote-mode(502 bad Gateway)

### ISSUE THREAD

**Issue by yanfang123-hash** [kaltura/nginx-vod-module#1068]
hello,
I use the vod module and I got an error while trying to serve vod to the client.

### [root@localhost ]# curl -I "http://10.70.60.64:8001/hls/test.mp4/index.m3u8"
HTTP/1.1 502 Bad Gateway
Server: nginx/1.8.0
Date: Fri, 08 Nov 2019 03:39:31 GMT
Content-Type: text/html
Content-Length: 537
Connection: keep-alive
ETag: "5dbbfe18-219"

And the error.log:
2019/11/08 11:39:31 [alert] 40590#0: *3 upstream buffer is too small to read response while reading response header from upstream, client: 10.70.60.64, server: localhost, request: "HEAD /hls/test.mp4/index.m3u8 HTTP/1.1", subrequest: "/proxy/hls/test.mp4", upstream: "http://10.70.60.64:80/test.mp4", host: "10.70.60.64:8001"

Two nginx are running, one is used for proxy(with port 8001) and the other one is used as upstream server.

My nginx.conf :
[root@localhost conf]# cat nginx.conf

#user  nobody;
worker_processes  1;

error_log  /var/log/nginx/error.log debug;
error_log  /var/log/nginx/error.log  notice;
error_log  /var/log/nginx/error.log  info;

#pid  /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
  include    mime.types;
  default_type  application/octet-stream;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $bytes_sent $request_time "$http_referer" '
    '"$http_user_agent" "$http_x_kaltura_f5_https" $http_x_kaltura_f5_remote_addr '
    '"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
    '$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
    '"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
    '$connection ';

  access_log /var/log/nginx/access.log main;
  
#  sendfile on;
#  tcp_nopush on;
#  tcp_nodelay on;

#  keepalive_timeout 60;
#  keepalive_requests 1000;
#  client_header_timeout 90;
#  client_body_timeout 90;
#  reset_timedout_connection on;
#  send_timeout 90;

#  add_header X-Me $hostname;

#  gzip  on;
#  gzip_types application/vnd.apple.mpegurl;
  
  # common file caching / aio
  open_file_cache max=100 inactive=5m;
  open_file_cache_valid 2m;
  open_file_cache_min_uses 1;
  open_file_cache_errors on;
  aio on;
  
  server {
    listen 8001;
    server_name localhost;
    
    proxy_buffer_size 20m;
    proxy_buffers 100 1m;
    large_client_header_buffers 4 16m;
    client_max_body_size 100m;
 	 
	  # base.conf -- base locations
	  # nginx status page
	  location = /nginx_status {
		stub_status on;
		access_log off;
	  }
          
	  # vod status page
	  location = /vod_status {
	 	vod_status;
		access_log off;
	  }
	
  	# static files (crossdomain.xml, robots.txt etc.) + fallback to api
	location / {
		root   html;
		index index.html index.htm;
	}

	# vod settings
	vod_mode remote;
	vod_upstream_location /proxy;
	vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
	vod_last_modified_types *;
        vod_max_upstream_headers_size 8k;

	# vod caches
	vod_metadata_cache metadata_cache 512m;
	vod_response_cache response_cache 128m;
	
	# gzip manifests
	#gzip on;
	#gzip_types application/vnd.apple.mpegurl;
	
	#internal location for vod subrequests
	location /proxy/hls/ {
		internal;
		proxy_pass http://10.70.60.64:80/;
		proxy_read_timeout 30;
		proxy_connect_timeout 30;
		proxy_set_header Host $http_host;
	}
	
	# serve flavor HLS
	location /hls/ {
		vod hls;
		add_header Access-Control-Allow-Headers "Origin,Range,Accept-Encoding,Referer,Cache-Control";
		add_header Access-Control-Expose-Headers "Server,Content-Length,Content-Range,Date";
		add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
		add_header Access-Control-Allow-Origin "*";
		expires 100d;
	}

    	# redirect server error pages to the static page /50x.html
    	#
    	error_page   500 502 503 504  /50x.html;
    	location = /50x.html {
      		root   html;
    	}
    }
}
 I am wondering if there is something wrong with my command, or is it not possible to set the param (vod_max_upstream_headers_size) or (proxy_buffers ).
please give me some advance, thank you very much.

**Comment by erankor** [comment]
I would suggest -
1. Try a simpler configuration, like the sample here - https://github.com/kaltura/nginx-vod-module#remote-configuration. Maybe one of the directives here is messing it up.
2. Capture the upstream request + response - by default, the module issues a range request for the first 4k of the file. If, for some reason, the upstream server ignores the range, and sends the whole file, you would get this error. This can be done using tcpdump (or similar), or you can compile nginx with debug enabled, and then you'll have the upstream request + response headers in the error log.

**Comment by yanfang123-hash** [comment]
> I would suggest -
> 
> Try a simpler configuration, like the sample here - https://github.com/kaltura/nginx-vod-module#remote-configuration. Maybe one of the directives here is messing it up.
> Capture the upstream request + response - by default, the module issues a range request for the first 4k of the file. If, for some reason, the upstream server ignores the range, and sends the whole file, you would get this error. This can be done using tcpdump (or similar), or you can compile nginx with debug enabled, and then you'll have the upstream request + response headers in the error log.

Thank you very much for your reply.
The issue had been resolved by using a different server as upstream.

And I am wondering with the remote-mode the mp4 files doesn't be saved as a local file?

**Comment by erankor** [comment]
Not sure I understand the question... the module doesn't save the files to disk, it's all done in memory, if that was what you meant.

**Comment by yanfang123-hash** [comment]
I got it.
Thank you very much ~
