### ISSUE TITLE
Buffer size is smaller than moov size

### ISSUE THREAD

**Issue by gstrat88** [kaltura/nginx-vod-module#1069]
Hello I am recieving this error
mp4_metadata_reader_read: buffer size 1052299 is smaller than moov size 1430559 while reading media header

My version is 1.23

exiftools ffmpeg etc says header is ok.

Any idea?

Thanks!

**Comment by erankor** [comment]
Please provide a URL to the MP4 file + nginx.conf

**Comment by gstrat88** [comment]
link:
https://www.dropbox.com/s/mpx9hz21u1hcq27/1573552383_1573554101.mp4?dl=0

config:
```

# common vod settings
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;
        vod_expires 100d;
        vod_expires_live 30;
        vod_expires_live_time_dependent 3;
        vod_align_segments_to_key_frames on;
        vod_output_buffer_pool 64k 32;


# file handle caching / aio
        open_file_cache max=1000 inactive=5m;
        open_file_cache_valid 2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors on;
        aio on;


location /static {
                        vod hls;
                        vod_mode local;
                        vod_segment_duration 10000;
                        vod_manifest_segment_durations_mode accurate;
                        alias /static;
                        open_file_cache off;
                        add_header Cache-Control no-cache; # Prevent caching of HLS fragments;
                        vod_expires 0;
                       add_header Access-Control-Allow-Headers "Origin,Range,Accept-Encoding,Referer,Cache-Control";
                        add_header Access-Control-Expose-Headers "Server,Content-Length,Content-Range,Date";
                        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
                        add_header Access-Control-Allow-Origin "*"
                }
```

thanks a lot!

**Comment by erankor** [comment]
Tested it now, it plays fine for me. 
Any chance you tried to stream it before it finished downloading or something like that? 
In this case, the moov atom is at the end of the file, if the file was incomplete on the server at the time of the request, it makes sense that you got this error.

**Comment by gstrat88** [comment]
No i certainly tried a long after. I will try with 1.25 release and let you
know

Στις Κυρ, 17 Νοε 2019, 22:30 ο χρήστης erankor <notifications@github.com>
έγραψε:

**Comment by erankor** [comment]
I don't recall changing anything that could have caused this, so I doubt upgrading will make a difference... but to make sure I understand - you're saying it still reproduces for you consistently with this file?

**Comment by gstrat88** [comment]
I am very sorry it seems everything is playing fine... 
Maybe it was something related to the filesystem I dont know.

**Comment by skyl** [comment]
https://github.com/kaltura/nginx-vod-module/issues/1316#issuecomment-1486426420
