### ISSUE TITLE
Remote upstream with arguments on url problem.

### ISSUE THREAD

**Issue by brooklyn097** [kaltura/nginx-vod-module#1074]
Hello,

I'm currently can make remote mode work with a no parameters  url like this one:

`http://filedomain.com/imafolder/imavideo.mp4`

and hls url would be like:

`http://mydomain.com/imafolder/imavideo.mp4/index.m3u8` 

But my problem is trying to make the url like this work:

`http://filedomain.com/video?expire=1574767832&fileid=mNTcXePtM8aouQWn-JaYCA&ip=xx.xx.xx.xx&cp=QVNMVkhfVlhRQ1hOOk9BRU5kNS1DM1NZeTNJRDZqMmhWeUtRTU5yUk1nY0M0azhscGo0dXAyODQ&mime=video/mp4&dur=4823.272&lmt=1574659341687524`

hls url would be like:

`http://mydomain.com/video?expire=1574767832&fileid=mNTcXePtM8aouQWn-JaYCA&ip=xx.xx.xx.xx&cp=QVNMVkhfVlhRQ1hOOk9BRU5kNS1DM1NZeTNJRDZqMmhWeUtRTU5yUk1nY0M0azhscGo0dXAyODQ&mime=video/mp4&dur=4823.272&lmt=1574659341687524/index.m3u8`

this is what i get in error.log

`2019/11/27 14:26:44 [error] 2664#2664: *58 ngx_http_vod_hls_parse_uri_file_name: unidentified request, client: xxx.xxx.xxx.xxx, server: _, request: "GET video?expire=1574767832&fileid=mNTcXePtM8aouQWn-JaYCA&ip=xx.xx.xx.xx&cp=QVNMVkhfVlhRQ1hOOk9BRU5kNS1DM1NZeTNJRDZqMmhWeUtRTU5yUk1nY0M0azhscGo0dXAyODQ&mime=video/mp4&dur=4823.272&lmt=1574659341687524/index.m3u8` HTTP/1.1", host: "xx.xx.xx.xx"
`

This is my whole configs:

```
server {
        listen 80;
	server_name _;
	
        # vod settings
		vod_mode remote;
		vod_upstream_location /kalapi;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;
		
		location ^~/kalapi/ {
			proxy_pass http://filedomain.com;
			proxy_set_header Host $http_host;
		}
		
		location ~ ^/ {
			vod hls;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
}

```

I've done some research but got no luck so please help me to understand how to make it works with that type of url.

**Comment by ESPNMichaelKidd** [comment]
https://github.com/kaltura/nginx-vod-module#vod_upstream_extra_args may be helpful  I've used this to pass query params from the m3u8 request to the upstream

**Comment by erankor** [comment]
In the URL you pasted, `/index.m3u8` is part of the query string, it's not part of the path (it comes after the `?`). The path of the URL has to end with `/index.m3u8` (or some other filename that the module recognizes...)

**Comment by brooklyn097** [comment]
> In the URL you pasted, `/index.m3u8` is part of the query string, it's not part of the path (it comes after the `?`). The path of the URL has to end with `/index.m3u8` (or some other filename that the module recognizes...)

Oh i see now, can you give me an advise please, cuz the remote url is from 3rd party so i can't change anything on it.
I think i can use nginx lua to do stuff but it's not a easy way for me so i would like to heard a easier way from you if possible.

**Comment by erankor** [comment]
You can move the fileid (and possibly other params) to the path, something like -
```
location ^~/kalapi/video/file_id/([^/])+/ {
    proxy_pass http://filedomain.com?$args&$1;
    proxy_set_header Host $http_host;
}
```
I didn't try it, but should be solvable this way, may require some trial & error...

Another problem you have here is that some of the params are expiring, if you just move them to the path, they will become part of the cache key, and the cache won't be efficient. The solution for this may be to generate these params on the proxy location, using set_by_lua / set_misc etc. The proxy location will get only the fileid (on the path) and will generate the rest.

**Comment by brooklyn097** [comment]
> You can move the fileid (and possibly other params) to the path, something like -
> 
> ```
> location ^~/kalapi/video/file_id/([^/])+/ {
>     proxy_pass http://filedomain.com?$args&$1;
>     proxy_set_header Host $http_host;
> }
> ```
> 
> I didn't try it, but should be solvable this way, may require some trial & error...
> 
> Another problem you have here is that some of the params are expiring, if you just move them to the path, they will become part of the cache key, and the cache won't be efficient. The solution for this may be to generate these params on the proxy location, using set_by_lua / set_misc etc. The proxy location will get only the fileid (on the path) and will generate the rest.

I've done it with help of Lua script and it works just fine til now. anw thank you for your help and the greatest module i've ever know.
