### ISSUE TITLE
adaptive url not playing on web 

### ISSUE THREAD

**Issue by keenersup** [kaltura/nginx-vod-module#1079]
I made master.m3u8 using urlset, it's not played on web browser with hls.js

it is only playing on local vlc player. 

is there any other option for using in web browser??

please let me know what I am missing

### nginx option ###
 location /hls/ {
        root /;
        vod hls;
        
        vod_mode local;
        vod_segment_duration 5000;
        vod_hls_segment_file_name_prefix   segment;
        vod_hls_absolute_index_urls        off;
        vod_hls_absolute_master_urls       off;
        vod_hls_absolute_iframe_urls       off;
    
        vod_hls_output_iframes_playlist off;
    
        vod_hls_force_unmuxed_segments off;
        vod_align_segments_to_key_frames   on;
    
        vod_last_modified_types *;
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header 'Access-Control-Allow-Origin' '*';
        expires 100d;
    }

### url ###
http://localhost/hls/data/,720,1080,.mp4.urlset/master.m3u8

### master.m3u8 ###
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1593312,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.6b"
index-f1-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3310883,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.6b"
index-f2-v1-a1.m3u8

**Comment by keenersup** [comment]
I change my audio codec to acc then works well.
Thanks your help~

**Comment by ufukomer** [comment]
Mine has been fixed after setting audio channels with `-ac` option in `ffmpeg`, which is weird and I don't know why it's necessary for this module to work properly.
