### ISSUE TITLE
GET params to upstream

### ISSUE THREAD

**Issue by ppllaxxa** [kaltura/nginx-vod-module#1084]
Hello,

Is it possible to push GET params from manifest url to upstream server (which generates JSON config in mapped mode).

**Comment by ESPNMichaelKidd** [comment]
you may be looking for https://github.com/kaltura/nginx-vod-module#vod_upstream_extra_args

**Comment by ppllaxxa** [comment]
But how I can pass though GET params from original link to manifest file?

**Comment by ESPNMichaelKidd** [comment]
check out http://nginx.org/en/docs/http/ngx_http_core_module.html#var_args

try something like `vod_upstream_extra_args $args;`

**Comment by ppllaxxa** [comment]
Thank you!
