### ISSUE TITLE
parse_uri_file_name failed 400

### ISSUE THREAD

**Issue by KlimSidorov** [kaltura/nginx-vod-module#1086]
Hi, thank you for this module.

I am trying to hide path to video while streaming. I want use to do request to https://mysite.com/api/hls?id={{file_uuid}}, then I do proxy path to exchange file_uuid to path. It works great and now I have full path from root to the file I need to stream.

**But how to provide full path to the .mp4 file to this module?**

Here is a part of my nginx.conf file:
```
upstream docker-storage {
  server storage:9000;
}

server {
  listen 9000;
  server_name localhost;
  root /srv/static;

  location = /auth {
    internal;
    proxy_pass $auth_request_uri;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
    set $filepath $upstream_http_x_file_path;
  }

  location /hls {
    set $auth_request_uri "http://docker-storage/info/videos/path?id=$arg_id";
    auth_request /auth;
    auth_request_set $filepath $upstream_http_x_file_path;

    vod hls;

    add_header X-debug-message "Here I get full path to file: $filepath/$arg_id" always;

    alias $filepath/$arg_id/master.m3u8;   <-- I know that it is crazy, but I have tried to provide the path to mp4 file. How to do it the right way?
    add_header Access-Control-Allow-Headers '*';
    add_header Access-Control-Allow-Origin '*';
    add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
  }
}
```

**Comment by KlimSidorov** [comment]
So the idea is to tell this module: "I have a path for you, just go to this path and take the .mp4 file".

Right now I have an error that it fails to parse the uri

**Comment by erankor** [comment]
The path of the request URL has to end with a file name that the module recognizes (e.g. master.m3u8 / index.m3u8 / etc.).
What you can do is use a request URL like - http://domain/hls/id/123456/master.m3u8, extract the id parameter using regex (on the location that does proxy_pass), then you can send it as query argument or whatever.

**Comment by KlimSidorov** [comment]
Thank you for fast response! I have forgot that this module only recognize such names, I have fixed it. It works amazing, thanks to this beautiful module!

**Comment by amirreza1751** [comment]
@KlimSidorov  Could you please explain how you did you solve the video segments authentication in nginx config?
