### ISSUE TITLE
adaptive bitrate doesn't work over the air?

### ISSUE THREAD

**Issue by facsiaginsa** [kaltura/nginx-vod-module#1088]
Hi, I already read many issue about adaptive bitrate here, but still something is wrong. Let me explain my use case:

1. using 1 json file
I already create 1 json file goes like this:
```
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/var/www/stream/video/transformers_360p.mp4"
				}
			]
		},
		{
			"clips": [
				{
					"type": "source",
					"path": "/var/www/stream/video/transformers_720p.mp4"
				}
			]
		}
	]
}
```
this is the url i used for streaming: http://192.168.5.26/hls/transformers.json/master.m3u8
i stream the video using VLC player, while playing the video i look at the codec information to see video resolution:

![image](https://user-images.githubusercontent.com/20637480/72043085-d5409a80-32e2-11ea-9893-58205f4ab3b9.png)

I stream the video with no bandwidth limit. In a few first seconds, the video play at 360p and then changed to 720p by it self. And then i try to limit my bandwidth to only 0.5Mbps, the video not change to 360p, it keep in 720p with a lot of buffering.

2 using 2 json file
fist json:
```
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/var/www/stream/video/transformers_360p.mp4"
				}
			]
		}
	]
}
```
second json:
```
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/var/www/stream/video/transformers_720p.mp4"
				}
			]
		}
	]
}
```
this is the url i used for streaming (using multi-url-structure): http://192.168.5.26/hls/transformers_,360,720,p.json.urlset/master.m3u8

The result is the same. the stream not change resolution when we limit the bandwidth over the air. 

So the question is: Is there any parameter that i should define to mapping the user bandwidth and the stream resolution? Maybe like bandwidth= 2M will play the 360p, bandwidth = 5M will play the 720p. 
Or it is just client problem?

other info, this is what it looks like when we curl the both url:
![image](https://user-images.githubusercontent.com/20637480/72043849-dd99d500-32e4-11ea-9848-8602042dc391.png)

**Comment by erankor** [comment]
The server does not choose the bitrate, the player does, the server's role is only to present all the options to the player. From what you pasted, it seems that it's done correctly. A different player may react better to changing network conditions.

**Comment by facsiaginsa** [comment]
Thank you for your reply! I'm not sure about my configuration before, now its clear based on your reply.

btw, 1 last question, do you have any reference what player maybe better than VLC to simulate this use case?

**Comment by erankor** [comment]
Try hls.js maybe

**Comment by facsiaginsa** [comment]
thx! i will close this
