### ISSUE TITLE
Is it possible to encrypt the filename/path?

### ISSUE THREAD

**Issue by francoism90** [kaltura/nginx-vod-module#1091]
I'm a bit confused about the _URL encryption_ part, is it possible to encrypt the target filename?
Let's say this is the DASH url:
`https://example.com/stream/450/test.mp4/manifest.mpd`

Would it be possible to 'hide' the `450/test.mp4` and use something else instead?
`https://example.com/stream/encrypted/manifest.mpd`

The only alternative I can think of is Lua encryption/decryption using a module, or by simple changing the folder structure itself.

Thanks for your module and help! :)

**Comment by xXxSPYxXx** [comment]
https://github.com/kaltura/nginx-secure-token-module

**Comment by francoism90** [comment]
@xXxSPYxXx Could you please give more details? I'm confused, like how does this work without using a CDN?

**Comment by francoism90** [comment]
I got it working.. sort of.. I'm using a proxy but the path doesn't get populated in the manifest, even when using `vod_segments_base_url` and `vod_base_url`

**Comment by francoism90** [comment]
```
server {
    listen 1935;

    server_name localhost;

    set $base /var/mp4s;

    # vod settings
    vod_mode local;
    #vod_base_url $http_x_base_url;
    vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
    vod_last_modified_types *;

    # vod segments
    #vod_align_segments_to_key_frames on;
    #vod_manifest_segment_durations_mode accurate;

    # vod caches
    vod_metadata_cache metadata_cache 512m;
    vod_response_cache response_cache 128m;
  
    location / {
        root $base;

        vod dash;  
        vod_secret_key "password$1";

        secure_token_types application/dash+xml;

        secure_token_encrypt_uri on;
        secure_token_encrypt_uri_key 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f;
        secure_token_encrypt_uri_iv 00000000000000000000000000000000;
        secure_token_encrypt_uri_part $1;
     
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
    }
}
```

`php encryptUrl.php http://localhost:1935/ test.mp4/manifest.mpd 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f 00000000000000000000000000000000`

It doesn't work at all, the file isn't played.

**Comment by francoism90** [comment]
Has been solved.
