### ISSUE TITLE
Support for AV1

### ISSUE THREAD

**Issue by mforchner** [kaltura/nginx-vod-module#1093]
Hi , is there any support for AV1 via Dash on the roadmap? I could not find information in the readme or current open issues. We would be interested to test and use this feature and could supply test files (like [this one](https://apps.digitalconcerthall.com/temp/kaltura_av1_testing/bphm_digital_concert_hall_av1_test.mp4)), if needed.

**Comment by erankor** [comment]
Do you happen to have sample DASH/HLS streams as well? If so, I can look into it. Usually, adding support for additional codecs is a fairly easy task.

**Comment by mforchner** [comment]
Hi Erankor, sorry for following up so late. The following examples might help with this:

- Demo by Unified Streaming / Bitmovin: https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-av1.ism/.mpd

- Bitmovin Sample: ([see website](https://bitmovin.com/demos/av1))
  - https://storage.googleapis.com/bitmovin-demos/av1/stream.mpd
  - https://storage.googleapis.com/bitmovin-demos/av1/stream_chrome.mpd 

- Multi Codec Dash Set, Paper by Uni Klagenfurt / Bitmovin ([see paper](https://arxiv.org/pdf/1803.06874.pdf), [see test data](http://ftp.itec.aau.at/datasets/mmsys18/))
  - http://ftp.itec.aau.at/datasets/mmsys18/testing/Beauty_4sec/multi-codec.mpd

- mp4box generates working Dash with AV1 like this: `MP4Box -dash 1000 -profile onDemand file_av1.mp4
` ([read more](https://gpac.wp.imt.fr/2018/10/27/official-av1-and-vp9-support-in-gpac/))

**Comment by erankor** [comment]
@mforchner, please check out #1135. 
I tested on Firefox - the original MP4 you posted here doesn't play for me in both DASH & progressive, but this one is working for me in DASH - https://github.com/SPBTV/video_av1_samples

**Comment by mforchner** [comment]
Thank you very much, we will test asap and double check our encoding settings against the working example!

**Comment by mforchner** [comment]
On first glimpse it looks good: 78.47.153.235/dash/dch/52589-1/AV1_LOW2.mp4/manifest.mpd

When testing in Firefox this plays just fine. Our previous sample was a 10bit one, this one is 8bit and works fine.
http://demo.theoplayer.com/test-your-stream-with-statistics?url=//78.47.153.235/dash/dch/52589-1/AV1_LOW2.mp4/manifest.mpd

VLC player however plays only audio, does not recognize the video track.

We will test with more samples with the recent encoder updates and also check ABR switching, will update the ticket then.

**Comment by mforchner** [comment]
It seems to work fine, we encoded new samples from our content: `78.47.153.235:80/dash/dch/52589-1/AV1_,TE,TE2,.mp4.urlset/manifest.mpd``

It seems to work just fine in Firefox:
http://demo.theoplayer.com/test-your-stream-with-statistics?url=//78.47.153.235:80/dash/dch/52589-1/AV1_,TE,TE2,.mp4.urlset/manifest.mpd

We will now test with more devices and players, next step might be a build of Exoplayer for Android 10 with AV1 extension: https://medium.com/google-exoplayer/playing-av1-videos-with-exoplayer-a7cb19bedef9

More feedback from the community would be welcome of course, but for now #1135 seems to be working very well.

**Comment by erankor** [comment]
Thanks @mforchner! merged.

**Comment by riccardotreso** [comment]
> On first glimpse it looks good: 78.47.153.235/dash/dch/52589-1/AV1_LOW2.mp4/manifest.mpd
> 
> When testing in Firefox this plays just fine. Our previous sample was a 10bit one, this one is 8bit and works fine. http://demo.theoplayer.com/test-your-stream-with-statistics?url=//78.47.153.235/dash/dch/52589-1/AV1_LOW2.mp4/manifest.mpd
> 
> VLC player however plays only audio, does not recognize the video track.
> 
> We will test with more samples with the recent encoder updates and also check ABR switching, will update the ticket then.

Hi @mforchner, i have the same issue with out av1 encode. 
i'm tried to use another sample video (like this https://github.com/SPBTV/video_av1_samples) but kaltura plays only audio.
How do you solve this problem?
thanks a lot!
