### ISSUE TITLE
Working example with encryption implementation

### ISSUE THREAD

**Issue by georgio-sd** [kaltura/nginx-vod-module#1096]
I setup nginx-vod-module for MPEG DASH and HLS without encryption. Now, I am trying to understand how to setup encryption for both standards but I am confused. Maybe there's a basic configuration with other things that have to be done (certs, scripts and etc)? Or a tutorial how to configure it step by step. 

And one more question. I'd like to make one-time video links. I did not find any option to do that. So, I decided to make an empty file with $arg_expires-$arg_md5 name every time when a user runs a new video and check if it exists later to prevent using links a few times. The problem is with creating an empty file. I found a way to do it with the lua module but it looks complicated to rebuild nginx with the vob module and lua, and a few more modules. Is there any way to create a file or run a system command without dealing with lua?

**Comment by Alexdrr** [comment]
https://github.com/kaltura/nginx-vod-module/issues/923#issuecomment-456071406

**Comment by georgio-sd** [comment]
Alexdrr, your eample is about security links, not encryptions.

I found HLS example here
https://github.com/kaltura/nginx-vod-module/issues/426

Now, I am looking for something similar but for DASH.

**Comment by erankor** [comment]
The question is about clear keys or DRM? 
If clear keys, it's discussed here:
https://github.com/kaltura/nginx-vod-module/issues/547#issuecomment-297624379
And there's a sample PHP for the "license" server here:
https://github.com/kaltura/nginx-vod-module/blob/master/test/dash_clear_key.php
DRM is more complicated...

**Comment by georgio-sd** [comment]
Thanks!
