### ISSUE TITLE
Segmenting of fragmented MP4 files?

### ISSUE THREAD

**Issue by elogy** [kaltura/nginx-vod-module#1099]
Hey everyone,
perhaps this is fairly obvious, but I'm really not sure how to go about doing this.
I'm streaming MP4 files from a network volume using VOD mapped mode, this works fine as long as the file is sane and encoded completely.
Suppose I now have to segment an MP4 while it's still being encoded. As far as my (quite limited) understanding of H.264 goes, the only way for this to be possible would be to use a fragmented MP4 file where every fragment has its own MOOV atom, something like this:

```bash
ffmpeg -i 1.mp4 -g 90 -acodec copy -vcodec libx264 -vb 1500k -f mp4 -movflags frag_keyframe+empty_moov+separate_moof+delay_moov 1_fragmented.mp4
```

When I try to open this file while it's still encoding, I get the following error inside the NGINX error log:
```
2020/02/16 11:08:43 [error] 1738#0: *10 ngx_http_vod_validate_streams: no matching streams were found while sending to client, client: [...], server: $server_addr, request: "GET /vod/1_fragmented.mp4/master.m3u8 HTTP/1.0", host: […]
```
The same file plays fine once the encoding process is finished.

Is there another way (if there is any) to handle these fragmented MP4 files?
Any hints would be greatly appreciated.

**Comment by erankor** [comment]
Fragmented MP4 is not supported, it was mentioned in a few issues already...

**Comment by elogy** [comment]
Shoot, I should have looked that up. Didn't occur to me to check out the older issues, my bad.
Thanks anyway!
