### ISSUE TITLE
MSS config example with encryption

### ISSUE THREAD

**Issue by georgio-sd** [kaltura/nginx-vod-module#1103]
Hi,
I configured DASH and HLS encryption (without DRM) and now I am looking for something similar for the Microsoft standard. Do you have any conf example?

**Comment by erankor** [comment]
AFAIK, there is no such feature in MSS.
I once bumped into a sample stream from Azure Media Services that had this feature, but the stream played only in Azure player, so I didn't bother adding support for it.

**Comment by georgio-sd** [comment]
Gotcha, thanks.
