### ISSUE TITLE
Response code 000 when enable DRM

### ISSUE THREAD

**Issue by trungtran0689** [kaltura/nginx-vod-module#1108]
I got this issue when enable DRM. The response code is "000", and body size is 0.

Here is my config
`
   location ~ /gcs-proxy/((drmdash)/)?(?<path>.*)$ {
      set $proxy_url http://origin-ip/$path;
      proxy_pass $proxy_url;

      proxy_redirect     off;
      proxy_http_version 1.1;
      proxy_set_header   Connection "";
    }
   location /drmdash  {
	    vod dash;
      vod_mode remote;
      vod_upstream_location /gcs-proxy;

      vod_segment_duration 4000;
      vod_bootstrap_segment_durations 3500;
      vod_align_segments_to_key_frames on;
      vod_dash_manifest_format segmenttemplate;

      sub_filter '-x3' '';
      sub_filter_once off;
      sub_filter_types application/dash+xml;

      vod_drm_enabled on;
      vod_drm_request_uri "/drm.json";
      vod_drm_upstream_location "/drm";
    }
  
    location /drm {
      internal;
      index drm.json;
      alias /etc/nginx/html;
    }`

Nginx log
`==> /var/log/nginx/access.log <==
192.168.32.1 - - [27/Feb/2020:04:53:44 +0000] "GET /drmdash/videos/transcoded/08-ep-03b-tennis-kids-popskids/640x360_600000.mp4/manifest.mpd HTTP/1.1" 000 0 "127.0.0.1" "-" "PostmanRuntime/7.22.0" "-"`

Please help me to overcome this issue.

**Comment by erankor** [comment]
Does it happen for all requests? If it happens only for a small portion of the requests, it's probably ok - nginx may output this code in the access log if the client disconnects prematurely (IIRC, in some cases it will output 499 on client disconnect and in some cases 000)

**Comment by trungtran0689** [comment]
@erankor it happen for all requests that enable DRM. The rest without DRM are fine

**Comment by trungtran0689** [comment]
@erankor  do you have any suggestions?

**Comment by erankor** [comment]
I just noticed the DRM location doesn't have proxy_pass - it must have proxy_pass, you can't serve a local file directly there. You should check the error log, there should be some error about this there...

**Comment by trungtran0689** [comment]
It works like a charm. Thank you very much
