### ISSUE TITLE
How to use DRM feature using the CPIX API

### ISSUE THREAD

**Issue by rightly** [kaltura/nginx-vod-module#1112]
Hi,
I want to use to DRM feature with CPIX.

This is my work flow
```
Request -> nginx-vod -> drm-proxy --request cpix api--> Multi DRM Vendor
                     <--response cpix json-- drm-proxy <- Multi DRM Vendor                       
```
```
then drm vendor's response example
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cpix:CPIX id="your-content-id" xmlns:cpix="urn:dashif:org:cpix" xmlns:speke="urn:aws:amazon:com:speke" xmlns:pskc="urn:ietf:params:xml:ns:keyprov:pskc">
   <cpix:ContentKeyList>
       <cpix:ContentKey explicitIV="MDEyMzQ1Njc4OWFiY2RlZg==" kid="12ea753c-23e7-bc02-4474-b2b976c43beb">
           <cpix:Data>
               <pskc:Secret>
                   <pskc:PlainValue>SzC1qc1cEpyFU6t/lL7Byw==</pskc:PlainValue>
               </pskc:Secret>
           </cpix:Data>
       </cpix:ContentKey>
   </cpix:ContentKeyList>
   <cpix:DRMSystemList>
       <!-- Common encryption / MSS (Playready) -->
       <cpix:DRMSystem kid="12ea753c-23e7-bc02-4474-b2b976c43beb" systemId="9A04F079-9840-4286-AB92-E65BE0885F95">
           <cpix:PSSH>AAACwnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAqKiAgAAAQABAJgCPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBQAEgAWABxAEUAdQBjAGoAQQByAHgARQBkAEwASwA1AGQAcwBRADcANgB3AD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AC8ARgA3AEIAMQBmAEgAMgBlADAAYwA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAHQAZQBzAHQAdABvAGsAeQBvAC4AcABhAGwAbAB5AGMAbwBuAC4AYwBvAG0ALwByAGkALwBwAGwAYQB5AHIAZQBhAGQAeQAvAGwAaQBjAGUAbgBzAGUATQBhAG4AYQBnAGUAcgAuAGQAbwA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cpix:PSSH>
       </cpix:DRMSystem>
       <!-- Common encryption (Widevine)-->
       <cpix:DRMSystem kid="12ea753c-23e7-bc02-4474-b2b976c43beb" systemId="EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
           <cpix:PSSH>AAAAVXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADUIARIQEup1PCPnvAJEdLK5dsQ76xoMaW5rYWVudHdvcmtzIg1jcGl4LXRlc3QtY2lkKgJIRA==</cpix:PSSH>
       </cpix:DRMSystem>
   </cpix:DRMSystemList>
</cpix:CPIX>
```
```
Proxy convert this xml response to json
{
  "pssh":  [
    {
      "data":{<PSSH>},
      "uuid":{<DRMSystem kid>}
    }, ..
  ]
  "key_id": {<pskc:PlainValue>}, // ?????
  "key": ????
}
```

I don't know which of the cpix api responses uses "key" and "key_id".
Or How can I integration DRM with CPIX
Please help me.

**Comment by inbal-ben-david** [comment]
Hi
Assuming you are the one implementing the drm proxy then for cenc the json should look like:
{
  "pssh":  [
    {
      "data":{<PSSH>},
      "uuid":{<DRMSystem systemId >}
    }, ..
  ]
  "key_id": :{<DRMSystem kid>}
  "key": {<pskc:PlainValue>}
}

You can distinguish between the different drm systems in the response using the uuid.

**Comment by rightly** [comment]
@inbal-ben-david 
THX very much! 
I'll try and update :)

**Comment by rightly** [comment]
@inbal-ben-david 
Hi, May I ask you one more question?

if DRMSystem kid is '12ea753c-23e7-bc02-4474-b2b976c43beb', should this be used by base64 encoding after aes128 encryption?

I used this after base64 encoding, but an error occurred 'parse_utils_parse_fixed_base64_string'.
(base64 encoded: MTJlYTc1M2MtMjNlNy1iYzAyLTQ0NzQtYjJiOTc2YzQzYmVi)

Sorry for the stupid question.

**Comment by rightly** [comment]
@inbal-ben-david
HI, may I ask you one more question?

I encrypted the DRMSystem key with AES, encoded base64 and tried it.
But I faced a parse_utils_parse_fixed_base64(key_id) error...

Encryption is AES 128 (32-byte key), CBC, and PKCS7 padding.

for example,
DRMSystem kid: `12ea753c-23e7-bc02-4474-b2b976c43beb`
-> AES encrypt and base64 encoding
base64 string: `9lha5ejwkHAEQhYQHS3jq5sth30kw8ztfLH1VQjvhf5O9uEmtjXeeyRb8/DuBBBz/f6CBDpRIPY1jwkz4VYNbg==`
(result string is 88 byte)

I'm sorry I asked a stupid question.
Can you tell which part is wrong?

**Comment by erankor** [comment]
I didn't understand why you are encrypting or with what key... but the key/key_id should be the binary 128 bit value encoded in base64. So, if it's `12ea753c-23e7-bc02-4474-b2b976c43beb`, the base64 that you need to put in the JSON is: 
>>> '12ea753c-23e7-bc02-4474-b2b976c43beb'.replace('-','').decode('hex').encode(
'base64').strip()
'Eup1PCPnvAJEdLK5dsQ76w=='

**Comment by rightly** [comment]
@erankor 
Thanks a lot. I totally misunderstood.
It works well!! (_ _)

**Comment by tanmayapatramuvi** [comment]
@rightly 
Hi, 
Can you help me to know how can we use that pssh/key JSON with our video play! I mean how we pass that pssh/key file to somewhere so that Kaltura can make the normal video play to DRM video play

@erankor Could you please help me on how to use this json with kaltura ?

Thanks in advance
