### ISSUE TITLE
Append last small segment to previous one

### ISSUE THREAD

**Issue by flashick** [kaltura/nginx-vod-module#1115]
Hello!

Some my chunklists looks like that:
```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
seg-1-v1-a1.ts
#EXTINF:10.000,
seg-2-v1-a1.ts
#EXTINF:10.000,
seg-3-v1-a1.ts
#EXTINF:10.000,
seg-4-v1-a1.ts
#EXTINF:10.000,
seg-5-v1-a1.ts
#EXTINF:10.000,
seg-6-v1-a1.ts
#EXTINF:10.000,
seg-7-v1-a1.ts
#EXTINF:10.000,
seg-8-v1-a1.ts
#EXTINF:0.016,
seg-9-v1-a1.ts
#EXT-X-ENDLIST
```

Any player return error "TS packet did not start with 0x47" while playing the last segment (its duration is 0.016)
For example, wowza returns that chunklist for same video:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.0,
media_w998615820_0.ts
#EXTINF:10.0,
media_w998615820_1.ts
#EXTINF:10.0,
media_w998615820_2.ts
#EXTINF:10.0,
media_w998615820_3.ts
#EXTINF:10.0,
media_w998615820_4.ts
#EXTINF:10.0,
media_w998615820_5.ts
#EXTINF:10.0,
media_w998615820_6.ts
#EXTINF:10.016,
media_w998615820_7.ts
#EXT-X-ENDLIST 
```
In this case, the duration of the last fragment is 10 + 0.016 and there are no errors during playback

How can I prevent this situation? May be there is some fix, or I can improve my ffmpeg settings?

**Comment by erankor** [comment]
You can add `vod_segment_count_policy last_rounded` to nginx.conf.
However, we're using the default `last_short` policy, and haven't seen such issues.

**Comment by flashick** [comment]
> You can add `vod_segment_count_policy last_rounded` to nginx.conf.
> However, we're using the default `last_short` policy, and haven't seen such issues.

Wow, it works! Thank you!
