### ISSUE TITLE
How can i change the .ts suffix inside the index.m3u8?

### ISSUE THREAD

**Issue by landerson-almeida** [kaltura/nginx-vod-module#1122]
Hi there.

I already tried to change:

> static vod_str_t m3u8_ts_suffix = vod_string(".x2z\n"); (inside the m3u8_builder.c)
> static const u_char ts_file_ext[] = ".x2z"; (inside the ngx_http_vod_hls.c)

Then i recompiled the module, but i still get the '.ts.' as suffix.

I want to change '.ts' to '.x2z', is there any way i can achieve that?

**Comment by erankor** [comment]
The changes you listed should have done it, maybe you are still running the old version somehow, or you have some manifest cached

**Comment by landerson-almeida** [comment]
It was indeed cache, my mistake.. Thank you very much Eran.
