### ISSUE TITLE
Failed to proxy to node.js (mapped + remote)

### ISSUE THREAD

**Issue by tan-tan-kanarek** [kaltura/nginx-vod-module#1124]
Hey @erankor, @jessp01.
Actually it's the same as https://github.com/kaltura/nginx-vod-module/issues/819 but on NGINX 1.17.10 and nginx-vod-module-1.25 and current master.

My node.js code is streaming mp4 file that uploaded as base64 chunks to redis:
```
const redis = require("redis");
const express = require('express');
const bluebird = require('bluebird');

bluebird.promisifyAll(redis.RedisClient.prototype);
bluebird.promisifyAll(redis.Multi.prototype);

const redisRead = redis.createClient();
redisRead.on("error", (err) => console.error("Redis Read Error " + err));

const CHUNK_SIZE = 1024 * 1024;

const app = express();

app.get('/json/*', async (req, res) => {
    console.log(req.url);
    var token = req.url.replace(/^\/json\//, '');
    var upload = await redisRead.getAsync('u-' + token);
    if(!upload) {
        return res.sendStatus(404);
    }
    upload = JSON.parse(upload);
    var map = {
        sequences: [
            {
                clips: [
                    {
                        type: 'source',
                        path: `/${token}`
                    }
                ]
            }
        ]
    };
    res.contentType = 'application/json';
    res.send(map);
});

app.get('/segments/*', async (req, res) => {
    console.log(req.url, req.headers.range);

    var token = req.url.replace(/^\/segments\//, '');
    var upload = await redisRead.getAsync('u-' + token);
    if(!upload) {
        return res.sendStatus(404);
    }
    upload = JSON.parse(upload);

    var cursur = 0;
    var done = 0;
    var start = 0;
    var end = upload.size;

    if(req.headers.range) {
        var match = /bytes=(\d+)-(\d+)/.exec(req.headers.range);
        if(match) {
            start = parseInt(match[1]);
            end = parseInt(match[2]);
        }
        var cursur = start;
        var done = start;
        if(cursur % CHUNK_SIZE) {
            cursur -= CHUNK_SIZE;
        }

        if(end > upload.size) {
            console.error(`Range ${start}-${end} is out of bounds ${upload.size}`)
            res.writeHead(416, {
                'Content-Range': `bytes */${upload.size}`
            });
            return res.end();
        }

        res.status(206);
        res.header('Content-Length', end - start + 1);
        res.header('Content-Range', `bytes ${start}-${end}/${upload.size}`);
        res.header('Accept-Ranges', `bytes`);
        res.header('Content-Type', 'video/mp4');
    }

    while(done < end) {
        var chunks = await redisRead.zrangebyscoreAsync('c-' + token, cursur, end, 'WITHSCORES', 'LIMIT', 0, 2);
        if(!chunks.length) {
            break;
        }
        for(var i = 0; i < chunks.length; i += 2) {
            var chunkStart = chunks[i + 1];
            var bufferStart = start - chunkStart;
            var bufferEnd = bufferStart + end - start + 1;
            var buffer = Buffer.from(chunks[i], 'base64').slice(bufferStart, bufferEnd);
            res.write(buffer);
            done += buffer.length;
        }
        cursur += (CHUNK_SIZE * 2);
    }
    res.end();
});

app.get('/*', (req, res) => {
    console.error(404, req.url);
    res.sendStatus(404);
});

app.listen(3001);
```

My NGINX Configuration:
```
worker_processes  4;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

	upstream jsonupstream {
		server localhost:3001;
	}

	server {
        listen 8088;
        server_name  localhost;
		
		# vod settings
		vod_mode mapped;
		vod_upstream_location /json;
		vod_remote_upstream_location /proxy;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		vod_mapping_cache mapping_cache 5m;

		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

		# file handle caching / aio
		open_file_cache	  max=1000 inactive=5m;
		open_file_cache_valid    2m;
		open_file_cache_min_uses 1;
		open_file_cache_errors   on;
		aio on;

		location ^~ /json/hls/ {
			internal;
			proxy_pass http://jsonupstream/json/;
			proxy_set_header Host $http_host;
		}

		location ^~ /proxy/ {
			internal;
			proxy_pass http://jsonupstream/segments/;
			proxy_set_header Host $http_host;
		}

        location / {
            root   html;
            index  index.html index.htm;
        }

		location ~ ^/hls/ {
			vod hls;

			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
		
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
	}
}
```

NGINX log (I can paste the debug log if you think it may help):
```
2020/04/23 13:37:47 [error] 10225#10225: *6 upstream timed out (110: Connection timed out) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /hls/lf5vq904jms/seg-1-v1-a1.ts HTTP/1.1", subrequest: "/proxy/lf5vq904jms", upstream: "http://127.0.0.1:3001/segments/lf5vq904jms", host: "localhost:8088"
2020/04/23 13:37:47 [error] 10225#10225: *6 ngx_child_request_wev_handler: upstream connection was closed with 151820 bytes left to read while sending to client, client: 127.0.0.1, server: localhost, request: "GET /hls/lf5vq904jms/seg-1-v1-a1.ts HTTP/1.1", host: "localhost:8088"
```

T.

**Comment by erankor** [comment]
Hi Tantan, 

This error means that the nginx server didn't get the size reported in the content length header. Try pulling different ranges from the node server and see what you get...
For example - I think this line is wrong 'cursur -= CHUNK_SIZE', should probably be 'cursur -= cursur % CHUNK_SIZE'

**Comment by tan-tan-kanarek** [comment]
Thanks Eran,
Actually, cursur -= CHUNK_SIZE is correct because redis.[zrangebyscore](https://redis.io/commands/zrangebyscore) will return the next chunk that its score is larger than cursur, this way the start always will be in the first returned chunk.
(When I place the chunks in redis I give them the score of their position in the chunk upload.)
Using curl or postman, I get the correct content length, matching to the actual returned bytes, so the cause is probably something else.
If you're interested, I can share the code that save the chunks to redis as well.

**Comment by erankor** [comment]
Ok, so it's not that, but I'm still sure the problem is on the node side... 
Unless I'm missing something, the slicing seems wrong - it is correct for a single chunk but not for multiple chunks. For all chunks but the first, 'start - chunkStart' will be negative, while it should be zero (it will strip off some bytes from the beginning).  The last chunk also returns more bytes than needed.

I suggest the following:
1. Find out which range was requested by the module (you can either look at the error log if running in debug / add logs in node / whatever...)
2. Set up some nginx location to serve the file as-is (using `root` / `alias`)
3. Curl this range from both nginx & node and compare the results

Other than that, I'd reconsider:
1. The base64 adds quite some overhead (+33% memory on redis + node decode CPU), I don't think redis has any problem saving binary data.
2. Since you know exactly which offsets to read, you can use simple SET & MGET, no need for anything fancy

**Comment by tan-tan-kanarek** [comment]
I prefer keeping the chunks in a single ordered set, this way I can delete / expire all the chunks together, and I can iterate through the entire set without calculating the keys.
I adopter your recommendation to skip the base64 encoding and the cursor calculation.

As for the returned buffer, I compared the following options, they all returned the exact same buffer:

- Reading from redis (Buffer.slice).
- Reading from the local file (fs.createReadStream).
- Reading range from my node.js server (request)
- Reading from nginx (request)

I believe the issue is different, maybe the connection closed before all bytes are read.
The issue doesn't happen on small ranges (4095).

**Comment by tan-tan-kanarek** [comment]
Just to be sure, I checked also against nginx 1.14.2, I get the same issue.

**Comment by erankor** [comment]
You're still getting the same error? can you send a pcap?

**Comment by tan-tan-kanarek** [comment]
My response is fine, looks the same as reading from file or nginx. It happens only on windows (Ubuntu subsystem), on real linux it's all fine.
I know @jessp01, it's my fault :).

I removed express, redis, async, reading now directly from file:
```
const fs = require('fs');
const http = require('http');

const FILE_PATH = './test1.mp4';
const stat = fs.statSync(FILE_PATH);
const size = stat.size;

http.createServer((req, res) => {
    console.log(req.url, req.headers.range);
    
    if(req.url.match(/^\/json\//)) {
        var map = {
            sequences: [{
                clips: [{
                    type: 'source',
                    path: `/whatever`
                }]
            }]
        };
        res.setHeader('Content-Type', 'application/json');
        res.write(JSON.stringify(map));
        res.end();
    }
    else if(req.url.match(/^\/segments\//)) {
        var start = 0;
        var end = size;
        if(req.headers.range) {
            var match = /bytes=(\d+)-(\d+)/.exec(req.headers.range);
            if(match) {
                start = parseInt(match[1]);
                end = parseInt(match[2]);
            }

            if(end > size) {
                console.error(`Range ${start}-${end} is out of bounds ${size}`)
                return res.writeHead(416, {
                    'Content-Range': `bytes */${size}`
                }).end();
            }

            res.statusCode = 206;
            res.setHeader('Content-Length', end - start + 1);
            res.setHeader('Content-Range', `bytes ${start}-${end}/${size}`);
            res.setHeader('Accept-Ranges', `bytes`);
            res.setHeader('Content-Type', 'video/mp4');
        }

        var stream = fs.createReadStream(FILE_PATH, {start, end});
        stream.on('data', buffer => {
            res.write(buffer, 'binary');
        });
        stream.on('end', () => {
            res.end(null, 'binary');
        });
        stream.read(end - start + 1);
    }
    else {
        res.writeHead(404).end();
    }

}).listen(3001, '127.0.0.1');
```

Another thing, the first time the request works fine, only the second time I access the same chunk I see the problem.

**Comment by jessp01** [comment]
Hi @tan-tan-kanarek ,

If it only happens on Windoze, then I'm afraid I can't help you:) 
> Another thing, the first time the request works fine, only the second time I access the same chunk I see the problem.

Just to clarify, this is still only in Windoze, right?

**Comment by tan-tan-kanarek** [comment]
Correct, windows only.

**Comment by jessp01** [comment]
Well, you know I can't reproduce that since I refuse to work on Windoze.. that said, can you get us a pcap file?
You can use Wireshark for this purpose, if you can use `tcpdump`. With tcpdump, you can do it like so:
> tcpdump -i $I_F -p -s 65535 -c 300 "tcp and host $YOUR_HOST and port $PORT" -w

Where $I_F is the network interface (i.e - eth0 or whatever), $YOUR_HOST is probably localhost in this case, $PORT - 80 or 443, I'd imagine.

Cheers,

**Comment by jessp01** [comment]
Also, 
> I removed express, redis, async, reading now directly from file
Anything new in the log following that? Let's make sure to run in debug mode.
Another thought, what happens when you try without `aio`?

**Comment by tan-tan-kanarek** [comment]
Same with aio off.
But I don't want to waste your time nor mine on windows if it's working on linux.

**Comment by jessp01** [comment]
Since I don't even consider Windoze to be an OS, you know I agree it isn't worth another second of our time, nonetheless, it would have been interesting to get to the bottom of this, from an academic standpoint:)

May the source be with you,

Jess Portnoy

________________________________

**Comment by tan-tan-kanarek** [comment]
As you know, I didn't spend much time on academic research in my life.
I recommend closing this issue, it's a waste of your time.

**Comment by jessp01** [comment]
Like I said, fine by me:)
Excerpts from Johnathan Amit Kanarek's message of 2020-04-25 07:14:54 -0700:
> As you know, I didn't spend much time on academic research in my life.
> I recommend closing this issue, it's a waste of your time.
> 

-- 
May the source be with you,

Jess Portnoy
