### ISSUE TITLE
Installation on ubuntu 18.04

### ISSUE THREAD

**Issue by SamuelNitsche** [kaltura/nginx-vod-module#1126]
I tried to install nginx-vod-module on ubuntu 18.04 but couldn't get it to work.

I get the following error:
```
apt-get install kaltura-nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kaltura-nginx : PreDepends: kaltura-ffmpeg but it is not going to be installed
                 Depends: kaltura-postinst but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I use the repo noted in [https://github.com/kaltura/nginx-vod-module/issues/494#issuecomment-268232786](https://github.com/kaltura/nginx-vod-module/issues/494#issuecomment-268232786). I think this is the problem.

**Comment by radiantshaw** [comment]
@SamuelNitsche I think this problem occurs with newer versions of Ubuntu.

So you basically have two options. Compile this with NGINX as a static module or compile it as a dynamic module and link NGINX to it.

For me the latter worked.

**Comment by SamuelNitsche** [comment]
Thanks, that worked.
