### ISSUE TITLE
Specifying streams that should not be encrypted when using DRM

### ISSUE THREAD

**Issue by rightly** [kaltura/nginx-vod-module#1130]
How do I specify a stream that should not be encrypted when using DRM?

Can I using "ContentKeyUsageRuleList" ?
How do I select a stream to not encrypt?

Thanks for help.

**Comment by francoism90** [comment]
You may want to add a second `server` that simple handles the non encrypted streams.

**Comment by erankor** [comment]
That would work, but usually it's easier to just set up a different `location`, e.g. we are using /dash for clear and /edash for DRM.

**Comment by rightly** [comment]
Thanks for reply :)

I was mispresented it.

stream (x) -> track (o)
ex) video track: encrypt, audio track: clear

How do I select a track to not encrypt?

**Comment by erankor** [comment]
I don't think it's possible with the current code. 
However, you can implement it externally if it's important - have the module serve two streams (e.g. /dash and /edash) and merge their MPDs - take the video adaptationSet from /edash and the audio adaptationSet from /dash.

**Comment by rightly** [comment]
@erankor 
Got it!

Thank you for idea.
If I really need a function, I'll try to do it from the outside.
