### ISSUE TITLE
Any way of time limiting

### ISSUE THREAD

**Issue by interlark** [kaltura/nginx-vod-module#1145]
Is there any ways to limit max size of hls\dash chunks particular ip could consume?
Like if set ```segmentDuration``` to 2 seconds and restrict particular ip to get up to 1200 segments maximum, so a user could then only get up to 40 minutes in summary out of all VODs on the server.

**Comment by erankor** [comment]
The assumption is that usually there is a CDN in front of this module, so no.
But you can probably build something like what you wrote using ngx_lua.

**Comment by interlark** [comment]
Ok, I'll check ```ngx_lua``` out, thank you.
