### ISSUE TITLE
Failed to fetch during installation

### ISSUE THREAD

**Issue by odinotisan** [kaltura/nginx-vod-module#1151]
During installation, on both centos/ubuntu.

`E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-ffmpeg/kaltura-ffmpeg_4.0.2-3_amd64.deb  404`
`E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-nginx/kaltura-nginx_1.17.10-1_amd64.deb  404`

**Comment by skhalymon** [comment]
Same issue here...

**Comment by jessp01** [comment]
Hi all,

Please see https://github.com/kaltura/nginx-vod-module/issues/892#issuecomment-413271054

Thanks,

**Comment by jessp01** [comment]
Hi all,

Can you please confirm the issue is resolved and, if so, close it?
Thanks,

**Comment by jessp01** [comment]
Closing due to lack of response. Feel free to reopen if there's still an issue.
Thanks,

**Comment by odinotisan** [comment]
Confirmed. It's working right now.
