### ISSUE TITLE
Subtitles size limitation

### ISSUE THREAD

**Issue by interlark** [kaltura/nginx-vod-module#1153]
It looks like that subtitles sized more than 2MB aren't working.
My subtitles' size is around 5Mb.
I stops showing them somewhere at **segment-n.vtt**, 
and gives **404 Not Found** on any further **segment-k.vtt**, k>n.
Is that because of file size? And are there any walkarounds?

**Comment by interlark** [comment]
Besides, **segment-n.vtt** comes truncated.

**Comment by interlark** [comment]
Logs for 
```bash
curl http://*test.vtt/index.m3u8
```
https://pastebin.com/h91w5wyR

Other subtitles bigger than 2Mb also comes defective. Feels like it stops reading after 2Mb passed.

**Comment by interlark** [comment]
Content of ***.vtt/index.m3u8**:
```text
#EXTINF:6.000,
http://127.0.0.1/hls/test.vtt/segment-439.vtt
#EXTINF:6.000,
http://127.0.0.1/hls/test.vtt/segment-440.vtt
#EXTINF:6.000,
http://127.0.0.1/hls/test.vtt/segment-441.vtt
#EXTINF:6.000,
http://127.0.0.1/hls/test.vtt/segment-442.vtt
#EXTINF:0.852,
http://127.0.0.1/hls/test.vtt/segment-443.vtt
#EXT-X-ENDLIST

```
The last one is **segment-n.vtt**

**Comment by interlark** [comment]
I reduced each subtitles' text entry, just replaced it with small test data to get result file size less than 2Mb.
And it works, nothing is missing. Indeed, looks like the problem is the file size. Any ways to solve it?

**Comment by erankor** [comment]
Yes, there is an hardcoded limit of 2MB for subtitles -
https://github.com/kaltura/nginx-vod-module/blob/master/vod/subtitle/subtitle_format.c#L27

Out of curiosity, can you share such a file? I find it hard to imagine a subtitles file so large...

**Comment by interlark** [comment]
Oh, thank you for the link.

Well, I can not share. But I could say that subtitles contains compressed data structures.
