### ISSUE TITLE
Does nginx-vod-module not support CPIX documents?

### ISSUE THREAD

**Issue by rightly** [kaltura/nginx-vod-module#1154]
I tried Integrate DRM with CPIX API.
But, it was impossible to integrate all but the Pallycon DRM.

I received this reply from VUDRM.
```
As the NGINX Vod Module does not support CPIX documents,
the standard CPIX response cannot be converted to a format that 
works with the NGINX Vod module without code that is only permitted with the Certified Widevine companies.
```

Can't I use CPIX responses in nginx-vod-module?
Please help me.

**Comment by erankor** [comment]
CPIX is not supported, I'm not sure it even existed when this module started supporting DRM...

**Comment by rightly** [comment]
@erankor 
Thanks.
Then, Is "ezdrm" the only vendor that provides a DRM that can work with nginx-vod-module?
Please could you tell me which vendors you can work with? (_ _)

**Comment by erankor** [comment]
Sorry, I have no idea what these vendors support, we are using our own DRM server...
But I assume you could write some middleware to translate CPIX to the format this module expects.

**Comment by rightly** [comment]
@erankor 
Oh, Middleware to translate CPIX?
Can you explain it in more detail?

**Comment by erankor** [comment]
Some web server that will get the request from nginx-vod-module, build from it a request for the upstream DRM provider, and translate the CPIX response to the format this module needs. Can be implemented in some high level language, like PHP/Python/...

**Comment by rightly** [comment]
aha.. I know that. 
I used proxy (middleware) to change the CPIX document to the format required by nginx-vod-module.
#1112 

However, other than certain CPIX documents, CPIX documents could not be playback normally even after translation 
(License authentication failed).

After that, I contacted the DRM server provider and got this answer.
```
As the NGINX Vod Module does not support CPIX documents,
the standard CPIX response cannot be converted to a format that 
works with the NGINX Vod module without code that is only permitted with the Certified Widevine companies.
```

My proxy extracts the value required by nginx-vod-module from the CPIX response and responds as it is.
If you have an idea to solve this, I would appreciate it if you could tell me.
