### ISSUE TITLE
Deallocation memory question

### ISSUE THREAD

**Issue by interlark** [kaltura/nginx-vod-module#1167]
During vtt utf16->utf8 conversion with iconv, we replace source with converted subtitles (```output_arr```) without freeing previous.
Shall we free pool's memory before the replacement and put
```c 
ngx_pfree(request_context->pool, output->data)
```
before this line
https://github.com/kaltura/nginx-vod-module/blob/f46eee22d984a6a7eb96f360b3dedf6b7e69e20f/vod/subtitle/webvtt_format.c#L159
?

**Comment by erankor** [comment]
I think this could lead to double free if there are additional files to process (e.g. master manifest with additional subtitles/media files). Anyway, as far as I remember, the iconv is performed before the subtitles enter the cache, so if multiple requests for subtitle segments reach the same server, it will run only once.

**Comment by interlark** [comment]
Now I see, thanks.
