### ISSUE TITLE
Non-continuous live streaming don't start at the edge and video sometimes goes back a segment

### ISSUE THREAD

**Issue by leandromoreira** [kaltura/nginx-vod-module#1168]
I'm trying to build an example of [non-continuous live using nginx+lua+ffmpeg](https://github.com/leandromoreira/kaltura-tests) and I could make it work (with yours/friend's help). 

However, I'm noticing some weird behaviors, like the `live edge` doesn't seem to be correct with the `mapped.json` response, and occasionally the stream goes `back` a segment.

I'm using the `initialClipIndex, initialSegmentIndex, clipTimes, clipSegments` scheme to handle live edge/timing.

I created six 30s long video plus one 60s with time embed into it, so it's easy to notice this issue:

<img width="632" alt="Screen Shot 2020-07-19 at 3 42 27 PM" src="https://user-images.githubusercontent.com/55913/87882692-466eb200-c9d8-11ea-8f91-65831345abb2.png">

I read your `playlist.php` example, watched mapped respsonse and couldn't figure it out why this is happening. Anyway, here's how you can replicate the same behavior: (`make sure you have docker-compose`)

```bash
cd /tmp
git clone https://github.com/leandromoreira/kaltura-tests.git
cd kaltura-tests
#make sure to have docker-compose
make run
```

You can watch the [live stream](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cDovL2xvY2FsaG9zdDo4MC9obHMvdGVzdC5qc29uL21hc3Rlci5tM3U4JywKICBwb3N0ZXI6ICdodHRwOi8vY2xhcHByLmlvL3Bvc3Rlci5wbmcnLAogIG11dGU6IHRydWUsCiAgaGVpZ2h0OiAzNjAsCiAgd2lkdGg6IDY0MAp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTsK) using the url http://localhost:80/hls/test.json/master.m3u8  

And you can also inspect the mapped json response:

```
$ curl -s localhost:8080/api/hls/test.json | jq '. | {clipSegments: .clipSegments, clipTimes: .clipTimes, currentTime: .currentTime, discontinuity: .discontinuity, durations: .durations, initialClipIndex: .initialClipIndex, initialSegmentIndex: .initialSegmentIndex, playlistType: .playlistType}'
{
  "clipSegments": [
    3,
    3,
    3,
    3,
    3,
    3,
    6
  ],
  "clipTimes": [
    1595183812000,
    1595183842000,
    1595183872000,
    1595183902000,
    1595183932000,
    1595183962000,
    1595183992000
  ],
  "currentTime": 1595183845000,
  "discontinuity": true,
  "durations": [
    30000,
    30000,
    30000,
    30000,
    30000,
    30000,
    60000
  ],
  "initialClipIndex": 2,
  "initialSegmentIndex": 4,
  "playlistType": "live"
}
```

I mean, the api response seems to be right, so why are the live streaming starting at a different segment? and why does it goes back a segment once in a while?

**Comment by leandromoreira** [comment]
I added the `currentTime` so I could manually check if clip index, segment index were right.

**Comment by erankor** [comment]
You most likely have a bug in your implementation... 
I suggest you review again the description of the fields in the readme and the sample php.
Also, you can test with the sample php as-is (only change the files array...). If you somehow manage to reproduce the issue with the sample php, I will happily review it, but I don't have the time to review custom implementations for generating the JSON.

**Comment by leandromoreira** [comment]
Just out of curiosity, I misunderstood the fields `initialClipIndex` and `initialSegmentIndex`. I thought they were related to how the server figures out the live edge, but it seems that they required to keep state of something like the `media sequence` throughout non-continuous live streaming, and the live edge might be guessed through a current epoch in ms.
