### ISSUE TITLE
support auto birate based on internet speed

### ISSUE THREAD

**Issue by ddev687** [kaltura/nginx-vod-module#1171]
Allow multiple resolution video streaming from single video url - It's possible with this package or I need to create different-different resolution file and set them?

**Comment by erankor** [comment]
By default, master.m3u8 returns all video tracks in the MP4 file

**Comment by bharatdevparmar** [comment]
Thanks for quick reply @erankor ,
@erankor should I need to pass multiple bitrate for generate all resolution video track,
In my case I'm getting only one resolution in master.m3u8 file.

**Comment by shubham2385** [comment]
Thanks for quick reply @erankor ,
@erankor should I need to pass multiple bitrate for generate all resolution video track,
In my case I've already set bitrate and avg_bitrate property but still getting only one resolution(video original resolution) in master.m3u8 file.

**Comment by erankor** [comment]
To clarify - the module doesn't transcode the video, it doesn't generate multiple bitrates by itself. 
The multiple bitrates can be provided in a single MP4 file or multiple MP4 files, both options are supported.

**Comment by bharatdevparmar** [comment]
Hi @erankor 
I've use [https://github.com/nytimes/gcs-helper](https://github.com/nytimes/gcs-helper) for access gcs video.

```
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/gcs_url/video1.mp4"
				}
			],
                         bitrate: {v: 600000}
		}
	]
}
```

for support multiple bitrate I need to set bitrate as array? like **bitrate: [{v: 600000}, {v:40000}, {v:30000}]** or create separate array. like bellow

 ```
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/gcs_url/video1.mp4"
				}
			],
                         bitrate: {v: 900000}
		},
                {
			"clips": [
				{
					"type": "source",
					"path": "/gcs_url/video1.mp4"
				}
			],
                         bitrate: {v: 700000}
		},
                {
			"clips": [
				{
					"type": "source",
					"path": "/gcs_url/video1.mp4"
				}
			],
                         bitrate: {v: 500000}
		}
	]
}
```

**Comment by erankor** [comment]
1. The bitrate attribute is optional, you don't need it in most cases - the module will detect it automatically. We are using it only in live, in order to force it to a fixed value.
2. AFAIK GCS supports S3 authentication, and if so, I would consider using our module for generating the authentication header (https://github.com/kaltura/nginx-aws-auth-module) instead of proxying all the traffic through another component.
3. Please avoid posting in unrelated issues, if it's a new question/problem, open a new issue.

**Comment by bharatdevparmar** [comment]
Okay thanks @erankor
