### ISSUE TITLE
unknown directive error about "vod_dash_subtitle_format" configure

### ISSUE THREAD

**Issue by rightly** [kaltura/nginx-vod-module#1173]
I configed the dash subtitle directive below, but it's occurred unknown directive error. 
please help me.

```
location /test/vodstaton-test/dash/ {
     vod dash;
     vod_multi_uri_suffix  ".smil";
     vod_base_url "";
     vod_segment_duration 5000;
     vod_dash_manifest_format "segmenttimeline";
     vod_align_segments_to_key_frames on;
     vod_upstream_location /remote_storage_proxy;

     #subtitle test
     vod_dash_subtitle_format "webvtt";
}
```

```
$ ./apps/nginx/sbin/nginx -t
nginx: [emerg] unknown directive "vod_dash_subtitle_format" in /data/vodstation/nginx/test.conf:17
nginx: configuration file /home1/irteamsu/apps/nginx/conf/nginx.conf test failed
```

**Comment by jessp01** [comment]
Hello @rightly ,

What version of the VOD module are you using? This directive was introduced in April, See 62e8fd867134bf3b5b37c0c8b50907f81f813765.

**Comment by rightly** [comment]
@jessp01 
Thanks... T.T
I'm using nginx-vod-module v1.25. I need a version upgrade.

Separately, I made a request for dash webvt in a similar way to hls webvtt.
However, subtitles were not exposed.
Do I have to upgrade the version to use the dash subtitles?
![image](https://user-images.githubusercontent.com/17899505/89361297-f09f4700-d705-11ea-875c-93ea8de2d945.png)

**Comment by jessp01** [comment]
Like I said, `vod_dash_subtitle_format` was introduced in a commit from Apr 2020, whereas, 1.25 was tagged in 2019 so naturally, 1,25 will not have it.

**Comment by rightly** [comment]
Thanks for reply.
I'll update the version and try to use this feature.

**Comment by rightly** [comment]
@jessp01 
nginx-vod-module update and configuration completed.
```
location /test/dash/ {
     vod dash;
     vod_multi_uri_suffix  ".smil";
     vod_base_url "";
     vod_segment_duration 5000;
     vod_dash_subtitle_format "webvtt"; # <--
     vod_dash_manifest_format "segmenttimeline";
     vod_align_segments_to_key_frames on;
     vod_upstream_location /remote_storage_proxy;
}
```

https://xcxhamgwzbdk1325777.cdn.beta.ntruss.com/hls/,sea.mp4,sample.vtt,.smil/master.m3u8 --> hls subtitle works well
https://xcxhamgwzbdk1325777.cdn.beta.ntruss.com/dash/,sea.mp4,sample.vtt,.smil/manifest.mpd -> Dash subtitles inoperative.

How can I get advice on how to use DASH subtitles?
