### ISSUE TITLE
Language code in multiple subtitle languages

### ISSUE THREAD

**Issue by rightly** [kaltura/nginx-vod-module#1177]
#### 1. When I build multiple subtitle, Should I use a three-digit language code in ISO 639-3? (e.g kor, eng, spa ...)
`/hls/vod/sea/,sea_1080.mp4,lang/kor/sea_ko.vtt,lang/eng/sea_sub_en.vtt,.smil/master.m3u8`
-> is works well.

`/hls/vod/sea/,sea_1080.mp4,lang/ko/sea_ko.vtt,lang/en/sea_sub_en.vtt,.smil/master.m3u8`
-> but this url is not works.

#### 2. Should the subtitle filename and video filename match?

`/hls/vod/sea/,sea_2160.mp4,sea_1080.mp4,lang/kor/test-sea1-ko.vtt,lang/eng/test-sea1-en.vtt,.smil/master.m3u8`
-> is works well.

`/hls/vod/sea/,sea_2160.mp4,sea_1080.mp4,lang/kor/sea-ko.vtt,lang/eng/sea-en.vtt,.smil/master.m3u8`
-> also works well.

**Comment by erankor** [comment]
1. Yes
2. The module doesn't care about the file names, it just needs to be able to access the files

**Comment by rightly** [comment]
@erankor 
Thanks for comment :)
