### ISSUE TITLE
caching seems to make no difference

### ISSUE THREAD

**Issue by arikkrol1** [kaltura/nginx-vod-module#118]
Hi.
I'm using the module to transmux mp4 to hls.

This is my cahce config:

vod_moov_cache moov_cache 4096m; #was 4096
vod_response_cache response_cache 512m;
vod_cache_buffer_size 256k; #was 512m

There seem to be no difference weather these settings are enabled or not.
Any ideas?

Thanks.

**Comment by erankor** [comment]
1. what do you mean by 'no difference' ? the execution time of the requests is the same whether these settings are enabled or disabled ?
2. did you verify the caches are actually working, by looking at the hit/miss values in the vod status page ?

**Comment by arikkrol1** [comment]
1. yes, the execution time is the same.
2. can you explain how to access the vod status page (I'm new to nginx)? thanks.

**Comment by erankor** [comment]
you need to add to your nginx.conf something like:
        # vod status page
        location = /vod_status {
                vod_status;
        }
and then curl <your server>/vod_status to get the status.
In addition, you should enable nginx-vod performance counters (preferably inside the 'server' block) using:
       vod_performance_counters perf_counters;

**Comment by jessp01** [comment]
Hello @arikkrol1,

Can this be closed or do you have additional questions?

Thanks,

**Comment by arikkrol1** [comment]
you can close it. thanks.

**Comment by mlevkov** [comment]
> Hi.
> I'm using the module to transmux mp4 to hls.
> 
> This is my cahce config:
> 
> vod_moov_cache moov_cache 4096m; #was 4096
> vod_response_cache response_cache 512m;
> vod_cache_buffer_size 256k; #was 512m
> 
> There seem to be no difference weather these settings are enabled or not.
> Any ideas?
> 
> Thanks.

@erankor There is not even a directive called vod_moov_cache and that is probably why it did not make any difference. It should have been
`vod_metadata_cache moov_cache 4096m;`
in lieu of 
`vod_moov_cache moov_cache 4096m;`

**Comment by jessp01** [comment]
Hi @arikkrol1,

That's correct and the directive is documented here:
https://github.com/kaltura/nginx-vod-module#performance-recommendations

The directive was renamed in Feb 2016, see:
https://github.com/kaltura/nginx-vod-module/blob/ae1f434e22996b384e8f20d701df2a63561a1a3d/CHANGELOG.md#20160203---added-support-for-matroska-container

**Comment by mlevkov** [comment]
@jessp01 Does this cache into memory or local drive?

**Comment by erankor** [comment]
Memory
