### ISSUE TITLE
DFXP/TTML in dash input failed

### ISSUE THREAD

**Issue by antoinecozzi** [kaltura/nginx-vod-module#1181]
Hi,

I try to use DFXP/TTML in dash stream input. XML header is :

    <tt ttp:timebase="media"

    xml:lang="fr"

    ttp:cellResolution="50 30"

    xmlns:smpte="http://www.smpte-ra.org/schema/2052-1/2010/smpte-tt"

    xmlns:ebuttm="urn:ebu:tt:metadata"

    xmlns="http://www.w3.org/ns/ttml"

    xmlns:tts="http://www.w3.org/ns/ttml#styling"

    xmlns:ttp="http://www.w3.org/ns/ttml#parameter">

Nginx build is:

NGINX_VERSION=1.19.2
VOD_MODULE_VERSION=1.27

./configure --prefix=/usr/local/nginx \
	--add-module=../nginx-vod-module \
	--with-http_ssl_module \
	--with-file-aio \
	--with-threads \
	--with-cc-opt="-O3"

NGINX config is :

vod_mode                                     local;

vod_metadata_cache                  metadata_cache 16m;

vod_response_cache                  response_cache 512m;

vod_last_modified_types             *;

vod_segment_duration                9000;

vod_align_segments_to_key_frames    on;

vod_dash_fragment_file_name_prefix  segment;

vod_manifest_segment_durations_mode accurate;

vod_dash_subtitle_format            smpte-tt;

But the stream crashes :

[error] 7#7: *4 ngx_http_vod_identify_format: **failed to identify the file format /opt/static/videos/test.ttml while reading media header,** client: 172.17.0.1, server: localhost, request: "GET /dash/,lang/eng/en-2mono-merge-stereo.mp4,lang/fra/fr-2mono-merge-stereo.mp4,h264-mute.mp4,lang/fra/test.ttml,.urlset/manifest.mpd HTTP/1.1"

Should I have to add libxml2 in Nginx build to solve this ?

very best

**Comment by erankor** [comment]
Yes, need to have libxml2 installed on the server. Check the result of 'configure' it should have `checking for libxml2 ... found` for this to work. I'm using 'libxml2-dev' on Ubuntu.

**Comment by antoinecozzi** [comment]
Hi, Thank you. This is working. I add libxml2 libxml2-devel on centos7.

**Comment by antoinecozzi** [comment]
Hi @erankor,
 
It's look like head.styling and head.layout are removed in the ttml segments from the original ttml.

[sub.ttml.txt](https://github.com/kaltura/nginx-vod-module/files/5142938/sub.ttml.txt)
[segment.ttml.txt](https://github.com/kaltura/nginx-vod-module/files/5142945/segment.ttml.txt)

Do you have any idea? 
Thank you
