### ISSUE TITLE
Play alternative audio stream on one of the clips fails

### ISSUE THREAD

**Issue by tan-tan-kanarek** [kaltura/nginx-vod-module#1196]
Hey.

I have sequence of three stream while one of them contains two audio streams.
I want to enable switching between the streams.

My video mediainfo:
> General
Complete name                            : .\test.2.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 1.58 MiB
Duration                                 : 24 s 299 ms
Overall bit rate                         : 546 kb/s
Writing application                      : Lavf58.29.100
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 24 s 275 ms
Bit rate                                 : 278 kb/s
Width                                    : 768 pixels
Height                                   : 432 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.035
Stream size                              : 823 KiB (51%)
Writing library                          : x264 core 158 r2984 3759fcb
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 
/ deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Codec configuration box                  : avcC
Audio #1
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 24 s 299 ms
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 380 KiB (23%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Audio #2
ID                                       : 3
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 24 s 278 ms
Bit rate mode                            : Constant
Bit rate                                 : 132 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 387 KiB (24%)
Default                                  : No
Alternate group                          : 1

My JSON:
> {
    "durations": [7000, 24274, 700],
    "sequences": [{
            "label": "default",
            "clips": [{
                    "type": "source",
                    "tracks": "v1-a1",
                    "path": "/segments/e/1280/720/FFFFFF",
                    "clipTo": 7
                }, {
                    "type": "source",
                    "tracks": "v1-a1",
                    "path": "/segments/07011omsel/112/Chapter/0agp0ggwsl/2/preview",
                    "clipTo": null
                }, {
                    "type": "source",
                    "tracks": "v1-a1",
                    "path": "/segments/e/1280/720/FFFFFF",
                    "clipTo": 0.7
                }
            ]
        }, {
            "label": "denoised",
            "clips": [{
                    "type": "source",
                    "clipTo": 7,
                    "path": "/segments/e/1280/720/FFFFFF",
                    "tracks": "a1"
                }, {
                    "type": "source",
                    "clipTo": null,
                    "path": "/segments/07011omsel/112/Chapter/0agp0ggwsl/2/preview",
                    "tracks": "a2"
                }, {
                    "type": "source",
                    "clipTo": 0.7,
                    "path": "/segments/e/1280/720/FFFFFF",
                    "tracks": "a1"
                }
            ]
        }
    ]
}

The resulted m3u8:
```#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="default",LANGUAGE="un",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="http://localhost:8088/hls/07011omsel/133/index-f1-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="denoised",LANGUAGE="un",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="http://localhost:8088/hls/07011omsel/133/index-f2-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=14723,RESOLUTION=768x432,FRAME-RATE=30.000,CODECS="avc1.f4001e,mp4a.40.2",AUDIO="audio0"
http://localhost:8088/hls/07011omsel/133/index-f1-v1.m3u8
```

The first stream plays perfect but when I try to switch to the alternative audio stream I get the following error:
> 2020/10/06 13:58:48 [error] 6#6: *4664 ngx_http_vod_validate_streams: no matching streams were found, probably invalid segment index while sending to client, client: 172.17.0.1, server: app.peech-ai.com, request: "GET /hls/07011omsel/103/seg-3-f2-a1.ts HTTP/1.1", host: "localhost:8088", referrer: "http://localhost:801/"
172.17.0.1 - - [06/Oct/2020:13:58:48 +0000] "GET /hls/07011omsel/103/seg-3-f2-a1.ts HTTP/1.1" 404 188 "http://localhost:801/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"

Any idea?

**Comment by tan-tan-kanarek** [comment]
BTW, it might be easier for me to deliver the alternative audio from a separate audio only mp4 or mp3 file.

**Comment by erankor** [comment]
Hi,

I think this is the same as this one - 
https://github.com/kaltura/nginx-vod-module/issues/1209#issuecomment-748296968

**Comment by tan-tan-kanarek** [comment]
Thanks Eran.
I have few video streams and few audio streams and I want to enable playback of their different combinations. 
I understand from your answer that I can serve them from different files as long as I always use the first audio or first video stream of each file?

**Comment by erankor** [comment]
Yes, if you don't select a track with index > 1 in the JSON, it should be fine

**Comment by tan-tan-kanarek** [comment]
Thank you, I appreciate it.

**Comment by sridhard** [comment]
@tan-tan-kanarek can you please give your map file for streaming audio and video streams from different files?

**Comment by tan-tan-kanarek** [comment]
If you change the path property, it will use a different file according to the new path.
For example:

```
{
"durations": [7000, 24274, 700],
"sequences": [{
"label": "default",
"clips": [{
"type": "source",
"tracks": "v1-a1",
"path": "/segments/file1.mp4",
"clipTo": 7
}, {
"type": "source",
"tracks": "v1-a1",
"path": "/segments/file2.mp4",
"clipTo": null
}, {
"type": "source",
"tracks": "v1-a1",
"path": "/segments/file1.mp4",
"clipTo": 0.7
}
]
}, {
"label": "denoised",
"clips": [{
"type": "source",
"clipTo": 7,
"path": "/segments/file1.mp4",
"tracks": "a1"
}, {
"type": "source",
"clipTo": null,
"path": "/segments/file3.mp4",
"tracks": "a1"
}, {
"type": "source",
"clipTo": 0.7,
"path": "/segments/file1.mp4",
"tracks": "a1"
}
]
}
]
}
```
