### ISSUE TITLE
First segment zero bytes length

### ISSUE THREAD

**Issue by AlexEbral** [kaltura/nginx-vod-module#1217]
Hello, the following line sometimes appears in nginx logs: 
```
10.10.10.4 - - [16/Nov/2020:18:08:06 +0100] "GET /videos/456254322/vid_,24,36,48,72,0p.mp4/multi/seg-1-f4-v1-a1.ts HTTP/1.1" 200 0 "-" "-" 0.000 - .
```

where "200 0" is "$status $body_bytes_sent" (nginx log_format). But if I request this chunk one more time - $body_bytes_sent will be > 0. How can I fix this problem? 
As I can see in logs, this problem appears only for first segment (seg-1-) of file.

NGINX_VERSION=1.19.4
VOD_MODULE_VERSION=1.27

**Comment by munrad** [comment]
I also faced this. Can someone comment on that?

**Comment by AlexEbral** [comment]
And $vod_frames_bytes_read  in log is also zero.
