### ISSUE TITLE
windows compile error,who can help me,thanks.

### ISSUE THREAD

**Issue by HearRain** [kaltura/nginx-vod-module#1218]
cl -c -O2  -W4 -WX -nologo -MT -Zi -Fdobjs/nginx.pdb -DFD_SETSIZE=1024 -DNO_SYS_TYPES_H -Yungx_config.h -Fpobjs/ngx_config.pch -I src/core  -I src/event  -I src/event/modules  -I src/os/win32  -I ../nginx-rtmp-module-1.2.0  -I ../pcre-8.40  -I ../openssl-1.0.2l/openssl/include  -I ../zlib-1.2.11  -I objs  -I src/http  -I src/http/modules  -Foobjs/addon/dash/edash_packager.obj  ../nginx-vod-module-1.27/vod/dash/edash_packager.c
edash_packager.c
../nginx-vod-module-1.27/vod/dash/edash_packager.c(1) : error C2220: 警告被视为错误 - 没有生成“object”文件
../nginx-vod-module-1.27/vod/dash/edash_packager.c(1) : warning C4627: “#include "edash_packager.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(2) : warning C4627: “#include "dash_packager.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(3) : warning C4627: “#include "../read_stream.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(4) : warning C4627: “#include "../mp4/mp4_cenc_passthrough.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(5) : warning C4627: “#include "../mp4/mp4_cenc_encrypt.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(6) : warning C4627: “#include "../mp4/mp4_init_segment.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(7) : warning C4627: “#include "../mp4/mp4_write_stream.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(8) : warning C4627: “#include "../mp4/mp4_defs.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(9) : warning C4627: “#include "../udrm.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(10) : warning C4627: “#include "../common.h"”: 在查找预编译头使用时跳过
        将指令添加到“ngx_config.h”或重新生成预编译头
../nginx-vod-module-1.27/vod/dash/edash_packager.c(595) : fatal error C1010: 在查找预编译头时遇到意外的文件结尾。是否忘记了向源中添加“#include "ngx_config.h"”?
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.

**Comment by treneth333** [comment]
It may be hanging up on the Unicode and non-unicode characters, especially with the special characters.

If they were all one or the other for example the compiler wouldn't get confused it would know exactly what to encode and how to process it.

This is just what I would look into first.
 
if it's not I can cross that off and keep troubleshooting.

**Comment by HearRain** [comment]
I find two methods to avoid this question:
1、The first line of code must be added to each source file #include “ngx_config.h”* 
2、In Makefile delete all *-Yungx_config.h
