### ISSUE TITLE
Make error with latest master

### ISSUE THREAD

**Issue by watershine** [kaltura/nginx-vod-module#122]
I can't run "make" with latest master commits.

I'm using a 32bits version of ubuntu server (virtual machine).

Find attached a screenshot of the error.
![make error](https://cloud.githubusercontent.com/assets/6065917/8770919/468054c4-2eec-11e5-9f2c-698649dcdf6b.PNG)

**Comment by erankor** [comment]
please try this branch: https://github.com/kaltura/nginx-vod-module/tree/uncompress-32bit-fix
if it works I'll merge it to master

**Comment by watershine** [comment]
It works, you can merge it into master.
Thank you for you fast help as usual.

**Comment by erankor** [comment]
Great, merged, thanks
