### ISSUE TITLE
Next release (with prom metrics)?

### ISSUE THREAD

**Issue by ufou** [kaltura/nginx-vod-module#1220]
Sorry, this is not an issue - just noticed the prometheus metrics in master and wondered if there might be a releases soon to take advantage of it (rather than compiling from master)?

Thanks!

**Comment by lynxnot** [comment]
That's interesting, i've recently implemented a quick-and-dirty [exporter](https://github.com/lynxnot/nginx-vod-exporter) for the vod-status endpoint.

**Comment by erankor** [comment]
tagged 1.28
