### ISSUE TITLE
apt-get update returns error on Debian 10 bullseye

### ISSUE THREAD

**Issue by SebaRossi94** [kaltura/nginx-vod-module#1222]
Following the [install](https://github.com/kaltura/nginx-vod-module#installation) guide returns an error when executing
`apt-get update` command

Output:

```
W: Error GPG: http://installrepo.kaltura.org/repo/apt/debian propus InRelease: Following signatures are not valid: 8118B7B578D4BA50032E3B740E221B84C95650AB
E: The repository «http://installrepo.kaltura.org/repo/apt/debian propus InRelease» is not signed.
```

Any suggestions here? I don't want to force the update of this specific repo due to security conerns

**Comment by jessp01** [comment]
Hello @SebaRossi94,

What distro are you running on?

Thanks,

**Comment by SebaRossi94** [comment]
Hello @jessp01,
Here ir is the output of `lsb_release -a`

```
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        testing
Codename:       bullseye

```

**Comment by jessp01** [comment]
Hi @SebaRossi94 ,

We do not offer a deb package compatible with Debian 10 (bullseye). I am well familiar with it as Debian happens to be my distro of choice but most of our users opt for Ubuntu or RHEL/CentOS and unfortunately, the matrix of commonly used distros is too vast to satisfy everyone.

Having said that, the Ubuntu Focal repo [20.04], will allow you to install the `kaltura-nginx` deb on Bullseye but the `nginx` binary depends on `libx265.so.179` (the version available in the focal repos) whereas, on my machine with:
```
# lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	9.13
Codename:	stretch
```
A different version is available (libx265-165) so, you'd have a problem at runtime.. 
If you'd like, you could build your own deb based on the specs here: https://github.com/kaltura/platform-install-packages/tree/Propus-16.11.0/deb/kaltura-nginx/debian, which you'll need to adjust some as per the above.
Alternatively, and probably the easier/faster option, you can just compile the module as an SO (see https://github.com/kaltura/nginx-vod-module#build) and load it onto the `nginx` as provided in the official Debian package.

**Comment by jessp01** [comment]
Closing this for now but feel free to reopen should you have follow up questions.

**Comment by SebaRossi94** [comment]
hey @jessp01 i did some testing here and i was able to succesfully execute `apt-get update`

But when i execute `apt-get install kaltura-nginx` i have dependencies issues with kaltura-ffmpeg and libx264 libraries. Specifically with versions 142, 148 and 155

When i try to install them output says they're obsolete (i can install libx264-160) but this version doesn't fulfill the dependencies.

Any suggestions for a workaround here?

**Comment by SebaRossi94** [comment]
Hello @jessp01 any suggestions here?

**Comment by t-900-a** [comment]
Running into this issue on ubuntu 20.10
