### ISSUE TITLE
How to playback adaptive bitrate and subtitle in mapped mode?

### ISSUE THREAD

**Issue by rightly** [kaltura/nginx-vod-module#1229]
First of all, thank you for your help.

I'm testing for abr playback and live mode with remote + mapped mode.
Before testing live mode, I saw the playlist.php file.

I'm trying to play abr + vtt in vod mode using playlist.php, but it doesn't work well.
How can it work well?
http://IP:PORT/mapped/vod/hls.json/master.m3u8
![image](https://user-images.githubusercontent.com/17899505/102960361-23b36d00-4525-11eb-8e78-2eaf4a22c11a.png)

please refer below json (hls.json response).
```
{
        "sequences": [
                {
                        "clips": [
                                {
                                        "type": "source",
                                        "path": "/vod/360p.mp4"
                                },
                                {
                                        "type": "source",
                                        "path": "/vod/sub-eng.vtt"
                                },
                                {
                                        "type": "source",
                                        "path": "/vod/sub-kor.vtt"
                                }
                        ]
                },
                {
                        "clips": [
                                {
                                        "type": "source",
                                        "path": "/vod/1080p.mp4"
                                },
                                {
                                        "type": "source",
                                        "path": "/vod/sub-eng.vtt"
                                },
                                {
                                        "type": "source",
                                        "path": "/vod/sub-kor.vtt"
                                }
                        ]
                }
        ]
}
```

I checked that abr playback(without subtitle) works well with json below.
```
{
        "sequences": [
                {
                        "clips": [
                                {
                                        "type": "source",
                                        "path": "/vod/360p.mp4"
                                }
                        ]
                },
                {
                        "clips": [
                                {
                                        "type": "source",
                                        "path": "/vod/1080p.mp4"
                                }
                        ]
                }
        ]
}
```

**Comment by erankor** [comment]
This JSON doesn't make sense...
1. It doesn't have the `durations` element, which is mandatory when using multiple clips
2. You have subtitles and video in the same sequence, a sequence contains clips that should be played one after the other. You can't play video for X sec and then subtitles for Y sec, they should be played together...

**Comment by rightly** [comment]
@erankor 
but,  adaptive set example doesn't have duration.
I don't understand the advice number 2. If you don't mind, could you make an example JSON response?

#### Adaptive set

As an alternative to using multi URL, an adaptive set can be defined via JSON:

```
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/path/to/bitrate1.mp4"
				}
			]
		},
		{
			"clips": [
				{
					"type": "source",
					"path": "/path/to/bitrate2.mp4"
				}
			]
		}
	]
}
```

**Comment by erankor** [comment]
1. Because each sequence has only one clip here, in the adaptive bitrate sample
2. If you have 2 renditions + subtitles, it will look like -
```
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/path/to/bitrate1.mp4"
				}
			]
		},
		{
			"clips": [
				{
					"type": "source",
					"path": "/path/to/bitrate2.mp4"
				}
			]
		},
		{
			"language": "eng",
			"clips": [
				{
					"type": "source",
					"path": "/path/to/subtitles.srt"
				}
			]
		}
	]
}```

**Comment by tanmayapatramuvi** [comment]
@rightly @erankor 

I just want some urgent help. I am stuck at something.

- Please guide me **where could I store JSON file** so that kaltura can detect and play videos. Please give me a detailed process if possible. I will be really glad for your help.

### **What I tried**
i am placing the json file inside /opt/kaltura/nginx/html/default.json and then I am hitting the url "http://localhost:88/mapped/vod/default.json/master.m3u8" in the browser but it gives me 404 Error !

My Json file is a s follow :

**Comment by erankor** [comment]
did you check the error log?

**Comment by tanmayapatramuvi** [comment]
@erankor 

I checked the error log and its blank.

error log: /opt/kaltura/log/nginx/error.log

**Comment by erankor** [comment]
nginx.conf? usually when you get 404 and there's nothing in the error log, it means no location matched the uri...

**Comment by tanmayabbsr09** [comment]
@erankor 

I am trying since 2 weeks on this part to correctly use JSON but no luck till now. So, can you please instruct me how to do this ? I am new to NGINX so I am not used to with the NGINX configurations. So it will be great if you guide me on this Json part.

**Comment by tanmayapatramuvi** [comment]
@erankor 

I am trying since 2 weeks on this part to correctly use JSON but no luck till now. So, can you please instruct me how to do this ? I am new to NGINX so I am not used to with the NGINX configurations. So it will be great if you guide me on this Json part.

**Comment by ashiskumarsahu** [comment]
@erankor 
Hey, I am having the same issue with mapped mode json. Could you please share any proper guide to do this? I need the following:

- Configuration after installation for mapped mode (I have currently installed for local mode)
- URL structure
- JSON (My files are in s3)

**My JSON:**
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "http://muvi-staging.s3.amazonaws.com/1753/EncodedVideo/uploads/movie_stream/full_movie/12630/Sicario_TRAILER_1__2015_.mp4"
				}
			]
		},
		{
			"clips": [
				{
					"type": "source",
					"path": "http://muvi-staging.s3.amazonaws.com/1753/EncodedVideo/uploads/movie_stream/full_movie/12630/Sicario_TRAILER_1__2015__360.mp4"
				}
			]
		},
		{
			"clips": [
				{
					"type": "source",
					"path": "http://muvi-staging.s3.amazonaws.com/1753/EncodedVideo/uploads/movie_stream/full_movie/12630/Sicario_TRAILER_1__2015__240.mp4"
				}
			]
		},
		{
			"clips": [
				{
					"type": "source",
					"path": "http://muvi-staging.s3.amazonaws.com/1753/EncodedVideo/uploads/movie_stream/full_movie/12630/Sicario_TRAILER_1__2015__144.mp4"
				}
			]
		}
	]
}


**kaltura-nginx.conf**
Path: /opt/kaltura/nginx/conf/kaltura-nginx.conf

include /opt/kaltura/nginx/conf/main.conf;

http {
	upstream kalapi {
		server @WWW_HOST@;
	}

	include /opt/kaltura/nginx/conf/http.conf;

	# vod mapped settings
	vod_mode mapped;
	vod_upstream_location /kalapi_proxy;
	vod_upstream_extra_args "pathOnly=1";
	vod_mapping_cache mapping_cache 64m;

	# file handle caching / aio
	open_file_cache max=1000 inactive=5m;
	open_file_cache_valid 2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors on;
	aio on;

	server {
		listen 88;
		server_name kaltura-vod;
		include /opt/kaltura/nginx/conf/server.conf;
	}

	include /opt/kaltura/nginx/conf/ssl.conf;
}
# RTMP configuration
rtmp {
    server {
        listen 1935; # Listen on standard RTMP port
        chunk_size 4000;

        # This application is to accept incoming stream
        application kLive {
                live on; # Allows live input from above

            	# ADAPTIVE BITRATE SUPPORT 
		# Once the stream is alive, transcode for adaptive streaming
            	# This single ffmpeg command takes the input and transforms
            	# the source into 4 different streams with different bitrate
            	# and quality. The scaling done here respects the aspect
            	# ratio of the input.

		# This is commented by default as it is CPU and RAM intensive 
		# If you opt to enable it, ensure you have sufficient resources.

            	#exec /opt/kaltura/bin/ffmpeg -i rtmp://kaltura-vod:1935/$app/$name -async 1 -vsync -1
                #        -c:v libx264 -b:v 256k -b:a 32k -vf "scale=480:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -crf 23 -f flv rtmp://kaltura-vod:1935/kLive/$name_low
                #        -c:v libx264 -b:v 768k -b:a 96k -vf "scale=720:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -crf 23 -f flv rtmp://kaltura-vod:1935/kLive/$name_mid
                #        -c:v libx264 -b:v 1024k -b:a 128k -vf "scale=960:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -crf 23 -f flv rtmp://kaltura-vod:1935/kLive/$name_high
                #        -c:v libx264 -b:v 1920k -b:a 128k -vf "scale=1280:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -crf 23 -f flv rtmp://kaltura-vod:1935/kLive/$name_hd720
                #        -c copy -f flv rtmp://kaltura-vod:1935/kLive/$name_src;

                dash on;
                dash_path /var/tmp/dashme;

                hls on; # Enable HTTP Live Streaming
            	# Instruct clients to adjust resolution according to bandwidth
            	hls_variant _low BANDWIDTH=288000; # Low bitrate, sub-SD resolution
            	hls_variant _mid BANDWIDTH=448000; # Medium bitrate, SD resolution
            	hls_variant _high BANDWIDTH=1152000; # High bitrate, higher-than-SD resolution
            	hls_variant _hd720 BANDWIDTH=2048000; # High bitrate, HD 720p resolution
            	hls_variant _src BANDWIDTH=4096000; # Source bitrate, source resolution

                hls_cleanup on;
                hls_sync 100ms;
                hls_fragment 2s;
		hls_playlist_length 300m;
                hls_path /var/tmp/hlsme/;

                # Enable recording archived files of each stream
                record all;
                # This does not need to be publicly accessible since we'll convert and publish the files later
                record_path /var/tmp/rec;
                record_suffix _%Y-%m-%d_%H-%M-%S.flv;
                record_lock on;

                # Define the two scripts that will run when recording starts and when it finishes
                exec_publish /opt/kaltura/bin/create_live_entry.php $args;
                exec_record_done /opt/kaltura/bin/upload_live_recording.php $args $path;


        }
    }
}


Please help here, I am stuck on this from last 15 days.

Thanks in advance.

**Comment by erankor** [comment]
"any proper guide"? seriously?! the module has a readme of 2k lines, other than the gazillion online guides for general nginx setup...
Other than that -
1. The conf you pasted is partial, the file is including another file, and I can't see which locations you have there
2. You didn't mention the URL you tried to call
3. You didn't include the error log

**Comment by ashiskumarsahu** [comment]
Hi @erankor ,
Thanks for the quick update. I am trying with the below link,
http://localhost:88/mapped/test.json/master.m3u8


Here is the code for **main.conf** file,

```
user  kaltura;
worker_processes  auto;

error_log  /opt/kaltura/log/nginx/kaltura_nginx_errors.log;

pid		/opt/kaltura/nginx/logs/nginx.pid;

events {
	worker_connections  1024;
	worker_aio_requests 512;
	multi_accept on;
	use epoll;
}
```
Could you please check and update?

Thank you

**Comment by erankor** [comment]
This is not the file I need... did you change anything in the conf or you just took the default one?
The default one doesn't work with a URL like the one you pasted, it expects our URL format (e.g. /p/123/serveFlavor/...)
I suggest you take a simpler config like this one https://github.com/kaltura/nginx-vod-module#mapped-configuration and start with that

**Comment by ashiskumarsahu** [comment]
@erankor 
Hi, I was doing with default config. I am trying with your given config. I just want some clarity on this. Here what I am trying to achieve:

- My files are on s3 and I want them to package them with kaltura.
- I have kaltura-vod in my local machine.
- I can able to package hls and mpd with local mp4 files

For my scenario which mode will be best? Is there any similar example? I am new to this so getting bit confused. Could you please navigate me to right place.

As per your suggestion for localhost, the below config requires to be changed right? But I am trying from localhost, so will this be localhost.
```
upstream kalapi {
		server www.kaltura.com:80;
	}

	upstream fallback {
		server fallback.kaltura.com:80;
	}

```

Thank you

**Comment by ashiskumarsahu** [comment]
@erankor 
Hi erankor,
Now I have config (kaltura-nginx.conf) like below,
```
http {
	upstream jsonupstream {
		server upstream.mystudio.com:80;
	}

	server {
		# vod settings
		vod_mode mapped;
		vod_upstream_location /;
		vod_remote_upstream_location /proxy;
		vod_upstream_extra_args "pathOnly=1";
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		vod_mapping_cache mapping_cache 5m;

		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

		# file handle caching / aio
		open_file_cache	  max=1000 inactive=5m;
		open_file_cache_valid    2m;
		open_file_cache_min_uses 1;
		open_file_cache_errors   on;
		aio on;

		location ^~ / {
			internal;
			proxy_pass http://upstream.mystudio.com/;
			proxy_set_header Host $http_host;
		}

		location ~ /proxy/([^/]+)/(.*) {
			internal;
			proxy_pass $1://$2;
			resolver 8.8.8.8;
		}

		location ~ ^/hls/ {
			vod hls;

			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}
```
I am trying to access following json located in http://upstream.mystudio.com/test2.json (Setup another local server apache for upstream).
```
{
	"sequences": [{
		"clips": [{
				"type": "source",
				"path": "/sample_1080.mp4"
		}]
	}]
}
```

Trying to access this with url: http://localhost:88/hls/test2.json/master.m3u8

I am getting following error from kaltura_nginx_error.log

2020/12/31 12:50:50 [error] 8613#0: *5 ngx_http_vod_identify_format: failed to identify the file format /var/www/html/jitp/test2.json while reading media header, client: 127.0.0.1, server: kaltura-vod, request: "GET /hls/test2.json/master.m3u8 HTTP/1.1", host: "localhost:88"

I tried the below too
 http://localhost:88/mapped/test2.json/master.m3u8
but returning 404 not found.

Could you please help here? What I am missing?

Thanks in advance.

**Comment by erankor** [comment]
Well, there are several mistakes in this conf...
1. jsonupstream is defined but not referenced anywhere
2. You are using `^~` on the `/` location, this makes nginx skip matching regex locations, so the /hls location doesn't get hit. In general, I wouldn't recommend putting such a location as the default location, would be better to give it some name, like /json/ or something.
3. The JSON has some relative path, while the config you are using in /proxy, expects something like - /http/domain/path

If I remove the `^~`, and have `/hls/test2.json` on the json upstream return this JSON:
```
{
        "sequences": [{
                "clips": [{
                                "type": "source",
                                "path": "/http/localhost/a.mp4"
                }]
        }]
}
```
And also, arrange so that http://localhost/a.mp4 will serve some MP4 file, then it works.

**Comment by ashiskumarsahu** [comment]
Hi @erankor ,
I tried as per your advice but no luck.
Please check my config below,

```
http {
	upstream jsonupstream {
		server upstream.mystudio.com:80;
	}

	server {
		# vod settings
		vod_mode mapped;
		vod_upstream_location /json;
		vod_remote_upstream_location /proxy;
		vod_upstream_extra_args "pathOnly=1";
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		vod_mapping_cache mapping_cache 5m;

		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

		# file handle caching / aio
		open_file_cache	  max=1000 inactive=5m;
		open_file_cache_valid    2m;
		open_file_cache_min_uses 1;
		open_file_cache_errors   on;
		aio on;

		location ^~ /json/hls/ {
			internal;
			proxy_pass http://jsonupstream/;
			proxy_set_header Host $http_host;
		}

		location ~ /proxy/([^/]+)/(.*) {
			internal;
			proxy_pass $1://$2;
			resolver 8.8.8.8;
		}

		location ~ ^/hls/ {
			vod hls;

			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}
# RTMP configuration
rtmp {
    server {
        listen 1935; # Listen on standard RTMP port
        chunk_size 4000;

        # This application is to accept incoming stream
        application kLive {
                live on; # Allows live input from above

            	# ADAPTIVE BITRATE SUPPORT 
		# Once the stream is alive, transcode for adaptive streaming
            	# This single ffmpeg command takes the input and transforms
            	# the source into 4 different streams with different bitrate
            	# and quality. The scaling done here respects the aspect
            	# ratio of the input.

		# This is commented by default as it is CPU and RAM intensive 
		# If you opt to enable it, ensure you have sufficient resources.

            	#exec /opt/kaltura/bin/ffmpeg -i rtmp://kaltura-vod:1935/$app/$name -async 1 -vsync -1
                #        -c:v libx264 -b:v 256k -b:a 32k -vf "scale=480:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -crf 23 -f flv rtmp://kaltura-vod:1935/kLive/$name_low
                #        -c:v libx264 -b:v 768k -b:a 96k -vf "scale=720:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -crf 23 -f flv rtmp://kaltura-vod:1935/kLive/$name_mid
                #        -c:v libx264 -b:v 1024k -b:a 128k -vf "scale=960:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -crf 23 -f flv rtmp://kaltura-vod:1935/kLive/$name_high
                #        -c:v libx264 -b:v 1920k -b:a 128k -vf "scale=1280:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -crf 23 -f flv rtmp://kaltura-vod:1935/kLive/$name_hd720
                #        -c copy -f flv rtmp://kaltura-vod:1935/kLive/$name_src;

                dash on;
                dash_path /var/tmp/dashme;

                hls on; # Enable HTTP Live Streaming
            	# Instruct clients to adjust resolution according to bandwidth
            	hls_variant _low BANDWIDTH=288000; # Low bitrate, sub-SD resolution
            	hls_variant _mid BANDWIDTH=448000; # Medium bitrate, SD resolution
            	hls_variant _high BANDWIDTH=1152000; # High bitrate, higher-than-SD resolution
            	hls_variant _hd720 BANDWIDTH=2048000; # High bitrate, HD 720p resolution
            	hls_variant _src BANDWIDTH=4096000; # Source bitrate, source resolution

                hls_cleanup on;
                hls_sync 100ms;
                hls_fragment 2s;
		hls_playlist_length 300m;
                hls_path /var/tmp/hlsme/;

                # Enable recording archived files of each stream
                record all;
                # This does not need to be publicly accessible since we'll convert and publish the files later
                record_path /var/tmp/rec;
                record_suffix _%Y-%m-%d_%H-%M-%S.flv;
                record_lock on;

                # Define the two scripts that will run when recording starts and when it finishes
                exec_publish /opt/kaltura/bin/create_live_entry.php $args;
                exec_record_done /opt/kaltura/bin/upload_live_recording.php $args $path;


        }
    }
}

```
**Url I tried:**
http://localhost:88/json/hls/test2.json/master.m3u8
http://localhost:88/hls/test2.json/master.m3u8

**My JSON**
http://localhost/jitp/test2.json
with vertual host:
http://upstream.mystudio.com/test2.json

```
{
	"sequences": [{
		"clips": [{
				"type": "source",
				"path": "/http/localhost/jitp/sample_1080.mp4"
		}]
	}]
}
```

Getting same error as earlier. Please let know if I am missing anything.

Thank you.
