### ISSUE TITLE
Questions around live and DRM

### ISSUE THREAD

**Issue by qchroman** [kaltura/nginx-vod-module#1239]
Hello all,

Am I right to presume that the kaltura-vod-module has nothing to do with live (except simulating one) and it is taken care of by the nginx-rtmp-module?

One may ingest RTMP into the set up and get DASH/HLS as outputs, but is it possible to apply DRM to the output using the kaltura module?

**Comment by erankor** [comment]
We are using the module for live as well, but it's a fairly complicated setup... we have RTMP going in, converted into HLS, then we have some component that transforms the HLS to the JSON structure required by this module, and from that, this module generates all delivery protocols. Anyway, we are in the process of rebuilding our live architecture...
It is not possible to use this module to apply DRM to an HLS/DASH stream generated elsewhere.

**Comment by qchroman** [comment]
Thank you
