### ISSUE TITLE
Is AV1 supported?

### ISSUE THREAD

**Issue by Binklebonk** [kaltura/nginx-vod-module#1245]
Resolved issue #1093 suggests AV1 support has been added, as well as "AV1" being mentioned in a number of project files.

The [Features](https://github.com/kaltura/nginx-vod-module/blob/master/README.md#features) detailed in the Readme doesn't mention it though.

> Video codecs: H264, H265 (DASH/HLS), VP9 (DASH)

I intend to give it a go in any case, but I thought I'd mention this in case the [Readme](https://github.com/kaltura/nginx-vod-module/blob/master/README.md) might need updating?

**Comment by erankor** [comment]
Updated, thanks
