### ISSUE TITLE
Remove first audio track

### ISSUE THREAD

**Issue by DeadInside1985** [kaltura/nginx-vod-module#1249]
Hello @erankor  thank you for this awesome module. 
I was generate this master manifest.

> #EXTM3U
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="rus0",LANGUAGE="ru",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="index-a1.m3u8"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="rus8",LANGUAGE="ru",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="index-a2.m3u8"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="ukr9",LANGUAGE="uk",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="index-a3.m3u8"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="eng10",LANGUAGE="en",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="index-a4.m3u8"
> 
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=900690,RESOLUTION=1280x720,FRAME-RATE=24.000,CODECS="avc1.64001f,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="audio0"
> index-v1-a1.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=374737,RESOLUTION=640x360,FRAME-RATE=24.000,CODECS="avc1.64001e,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="audio0"
> index-v2-a1.m3u8
> 
> #EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=65993,RESOLUTION=1280x720,CODECS="avc1.64001f",URI="iframes-v1-a1.m3u8",VIDEO-RANGE=SDR
> #EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=24397,RESOLUTION=640x360,CODECS="avc1.64001e",URI="iframes-v2-a1.m3u8",VIDEO-RANGE=SDR`

By this config 
 

>        vod_mode local;
>        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
>        vod_last_modified_types *;
>        vod_parse_hdlr_name on;
>        vod_hls_force_unmuxed_segments off;
> 
>         location ~ ^/.+\.m3u8|ts$ {
>             vod_initial_read_size 8k;
>             vod_cache_buffer_size 512k;
>              vod_output_buffer_pool 1024k 512;
> 
>             root /home/rsync;
>             vod_base_url '';                     # Sets the CACHE SERVER for manifests.
>             vod_segments_base_url '';            # Sets the CACHE SERVER for video segments.
>             vod hls;
>             vod_segment_duration 10000;                     # Sets the segment duration in milliseconds.
>             vod_align_segments_to_key_frames on;
>             vod_manifest_segment_durations_mode accurate;                       # Report the correct segment durations in the manifest.
    
And when I play manifest in player, chosed first track downloaded first audio and audio + video chunk. Its possible to remove first audio track? Its no reason to download audio + video and same audio.

**Comment by erankor** [comment]
You can change `vod_hls_force_unmuxed_segments` to on, then you won't have audio muxed with the video segments

**Comment by DeadInside1985** [comment]
Yes but old devices like Smart TV played video without audio.

**Comment by erankor** [comment]
Yeah, well, that's the reason that by default the module muxes the audio with the video...
So I don't really understand your request, I can't fix the old TVs...

**Comment by DeadInside1985** [comment]
Problem that downloaded seg-1-v1-a1.ts and seg-1-a1.ts together, but I understand that its normal and you can do nothing with this. Thank you.

**Comment by erankor** [comment]
Only thing you can do, if this really bothers you, is to have two different locations/urls - one with muxed audio (for old players), and one with unmuxed/multi-audio (for modern players). The problem is that you'll have to manage a list of user agents in order to choose the correct stream for each device...

**Comment by DeadInside1985** [comment]
Thank you @erankor
