### ISSUE TITLE
expose vod_metadata_cache, vod_response_cache and vod_mapping_cache size?

### ISSUE THREAD

**Issue by damex** [kaltura/nginx-vod-module#1251]
hello,

  nginx-vod-module have this three types of caches vod_metadata_cache, vod_response_cache and vod_mapping_cache and their hitrate is exposed in prometheus (we interested in that one) or xml format.

  is there a way to export metrics about vod cache sizes? like currently set size and how much is used.

  we want to be able to investigate how full they're and if we might need to (i.e.) increase them depending on what we're doing.

  currently i see no way of checking that cache sizes.

  thank you

**Comment by erankor** [comment]
If you are exposing the metrics using `vod_status` and pulling in prom format, you have a metric called `vod_cache_data_size` that indicates the size of data currently in cache

**Comment by damex** [comment]
thanks, it seems like we can not get `vod_cache_data_size` from 'global' `vod_status` but it has to be done on each vhost that use kaltura-vod.

**Comment by erankor** [comment]
I would recommend putting the the vod_xxx_cache directives in some top level (http/server) so that they will be visible to all relevant locations

**Comment by damex** [comment]
thanks, my question is answered and situation about visibility of `vod_xxx_cache` become clear. closing the issue
