### ISSUE TITLE
If any chance to reuse segments from cache when use clips?

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#1256]
When make a hls clip from full main video, a new uri is used, so new segments appears. If any way to reuse segments from main full video to use cache at maximum?

**Comment by erankor** [comment]
Not supported... the clipping is performed in keyframe resolution, so the clipped segments may not even be aligned with the original ones. Technically, it is possible to add a different feature of "manifest clipping" where the module will segment the video normally, but will return only a subset of the segments in the manifest. But this feature doesn't currently exist.

**Comment by kuznetcoff777** [comment]
I thought that it will be possible to reuse segments from main video, but only on borders make new one. Anyway i think you got an idea, maybe it will be helpful for you somehow
