### ISSUE TITLE
Pruning cache

### ISSUE THREAD

**Issue by giulioprovasi** [kaltura/nginx-vod-module#1264]
Hello,
Is it possible to clear `vod_mapping_cache` data ? I have some use cases where my mappings may change over time and this leads to errors like this one : 

```
ngx_http_vod_validate_streams: invalid sequence count 4 while sending to client
```

If I restart my pod and drop the cache, everything is fixed.

So question is : is there a way to prune the metadata cache ? and ideally other caches too ?

Cheers,
Giulio

**Comment by giulioprovasi** [comment]
ping, this issue is quite blocking for me :/

What happens : 
 - video has N encodings (that encodes simultaneously)
 - as soon as 1 encoding is available, video is server in mapped mode (master manifest returns 1 stream)
 - as soon as another encoding is available, now mapped mode returns 2 streams, but because of metadata cache, I get the above error

how may I fix this ?

**Comment by erankor** [comment]
If I understand your issue correctly, `vod_force_sequence_index on;` should solve it, it will make the module output `-f1` when there is only one sequence. If you are only appending sequences at the end, it won't break.
But I would strongly consider using versioning here - have some version on the playback URL, and have the server building the json return consistent results for a given version. 
This way, a user who starts playing version 1 will always be using the JSON of version 1, and you won't have any problems. This also solves the problem of master.m3u8 (or other URLs) getting stuck in the CDN with a subset of the renditions.

**Comment by giulioprovasi** [comment]
Thanks I will try `vod_force_sequence_index`

But for versioning, I would like the manifest to be enforced to latest rendition, always.
Let's take an example, I encode my video in 360/480/720/1080p

As soon as one is available (360p should be quicker) my server returns something like : 

```
{
    "sequences": [
        {
            "clips": [
                {
                    "path": "/vod-channel-1jhvl2upwom9j/1jhvl2upwpz5d",
                    "type": "source"
                }
            ]
        }
    ]
}

```

And as soon as every other quality is encoded, server updates the manifest.m3u8 route to return all 4 renditions

```
{
    "sequences": [
        {
            "clips": [
                {
                    "path": "/vod-channel-1jhvl2upwom9j/1jhvl2upwpz5d",
                    "type": "source"
                }
            ]
        },
        {
            "clips": [
                {
                    "path": "/vod-channel-1jhvl2upwom9j/1jhvl2upwpz5c",
                    "type": "source"
                }
            ]
        },
        {
            "clips": [
                {
                    "path": "/vod-channel-1jhvl2upwom9j/1jhvl2upwpz5b",
                    "type": "source"
                }
            ]
        },
        {
            "clips": [
                {
                    "path": "/vod-channel-1jhvl2upwom9j/1jhvl2upwpz5a",
                    "type": "source"
                }
            ]
        }
    ]
}

```

Which cause the module to return:
```
2021/04/29 11:37:38 [error] 11#11: *4724 ngx_http_vod_validate_streams: invalid sequence count 4 while sending to client, client: 10.42.2.5, server: localhost, request: "GET /hls/r5203u7ebhc/r5203u7ebh3/index-v1-a1.m3u8 HTTP/1.1"
```

**Comment by erankor** [comment]
In our system, we have an API that redirects to the latest version, so when a user starts playing, he gets redirected to the current latest. Even if a new version is added during playback, the user will keep playing the same version, and no error will occur.
Another possible solution here is to move from using JSON for adaptive, to using multi url. If you do that, the set of renditions is encoded on the URL, and will remain constant for any given user.

**Comment by giulioprovasi** [comment]
Just for me to understand: is the manifest checked/invoked during playback? because from what I see in Network tab, it gets called once at the beginning of the playback and then only chunks are called.
When I get the `ngx_http_vod_validate_streams` error is it because the module checks periodically the manifest and get mixed up between what it was told at first (1 rendition) vs what is told later ? (4 renditions)

**Comment by erankor** [comment]
The master manifest is normally pulled only once, the manifests of the renditions are pulled when the player wants to switch to one of them. 
The reason for the error is that in the beginning there is only one sequence, so the module doesn't output the sequence specifier (-f1) on the index url/segment urls. But then the module gets a request for the index/segments, and now there is more than one sequence, and the request fails - it can't use more than one sequence in these types of requests.

**Comment by giulioprovasi** [comment]
Ok so I am exploring both your ideas but have some questions:

 > But I would strongly consider using versioning here

How would you do that ? I guess by requesting something like `/hls/media1.m3u8?version=1` etc.. but as I understand, my issue is that `response|mapping_cache` stores the incomplete data, so module doesn't output the sequence specifier (-f1)
Can I specify a caching key for metadata ?

> In our system, we have an API that redirects to the latest version

Would you be kind to share some config on how may I achieve that ?

Cheers

**Comment by erankor** [comment]
In our system, the versioning is transparent to nginx-vod-module -
1. The API that generates the playback URL puts the latest version on the path of the URL, e.g. /v/2/.../master.m3u8. So, when a player calls, it will get the most recent version at the time of the call.
2. The API that generates the mapping JSON for nginx-vod-module extracts the version from the URL, and uses it to return the correct file.

In most cases, we use multiurl and each mapping JSON contains a single MP4 file, this makes the versioning very simple.
For example, a user may get a URL like -
`/hls/serveFlavor/entryId/0_abcd/flavorId/0_,1234/v/1,5678/v/2,/a.mp4.urlset/master.m3u8`
entryId is the id of the video, and flavorId is the id of each rendition. In this example, the first rendition has a version of 1, and the second one has a version of 2. 
The mapping API just needs to provide the right MP4 file path according to the version. If the set of renditions changes (e.g. one is added/removed) that is not a problem in this case - users will just get new URLs with more/less renditions in them.

**Comment by giulioprovasi** [comment]
Ok so I switched to multi url setup and it works perfectly, I will add a canonical url that will be redirected to the latest version so user can have a "final" url that will adapt to different renditions.

Thanks for your follow up and great module ;)
