### ISSUE TITLE
Difficulty getting "play from beginning" working

### ISSUE THREAD

**Issue by rhummelmose** [kaltura/nginx-vod-module#1265]
Hi @erankor

Thanks for the amazing work you guys have done with this module.

We're using the module for on-demand/live streaming and everything works well.

We stream to an input server that grabs an RTMP input stream and encodes that to 10s segments using ffmpeg. For every segment we store relevant information in a JSON file that sits beside it (preventing us from having to ffprobe at runtime).

However, I'm trying to build functionality that allows "start from beginning" of a currently streaming show. I cannot get this to work, as I'm experiencing that **_playlistType: live_** results in media playback from the most recent (live) time when used with offset 0 and **_playlistType: vod_** results in a returned list with #EXT-X-ENDLIST causing the player to consider the result final.

Is this achievable using your module?

Thanks in advance.

Sample mapped response live:
```json
{
  "cache": false,
  "clipFrom": 0,
  "playlistType": "live",
  "firstClipTime": 1618670195671,
  "discontinuity": true,
  "durations": [
    60092
  ],
  "sequences": [
    {
      "clips": [
        {
          "type": "concat",
          "durations": [
            10048,
            10011,
            10016,
            10000,
            10006,
            10011
          ],
          "basePath": "/Users/rhummelmose/Development/duah-web/temp/broadcasts/140/segmented/",
          "paths": [
            "test__0000.mp4",
            "test__0001.mp4",
            "test__0002.mp4",
            "test__0003.mp4",
            "test__0004.mp4",
            "test__0005.mp4"
          ],
          "firstKeyFrameOffset": 41,
          "keyFrameDurations": [
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980,
            1980
          ]
        }
      ]
    }
  ]
}
```

**Comment by erankor** [comment]
I think what you described should be achievable with `#EXT-X-PLAYLIST-TYPE:EVENT`. The module currently doesn't support writing this tag (only supports VOD), but you can try to patch it to return this value, and check whether the behavior is as you expect.
If it is, it should be fairly easy to add an option for this.

**Comment by rhummelmose** [comment]
Closed by references PR

**Comment by spinitron** [comment]
I'm using `"playlistType": "event"` and HLS playlists are being created as expected (afaict). But players start playing from close to the end of the playlist, always with the 2nd last segment. Is this something that nginx-vod-module can do something about?

Here's an example mapping...

```json
{
  "playlistType": "event",
  "firstClipTime": 1642874280000,
  "segmentBaseTime": 1642874280000,
  "discontinuity": false,
  "referenceClipIndex": 1,
  "durations": [
    120022,
    3599673,
    3599999
  ],
  "sequences": [
    {
      "clips": [
        {
          "type": "source",
          "path": "/home/debian/ark/var/audio/WZBC/WZBC-20220122T170000Z.mp4",
          "clipFrom": 3480000
        },
        {
          "type": "source",
          "path": "/home/debian/ark/var/audio/WZBC/WZBC-20220122T180000Z.mp4"
        },
        {
          "type": "source",
          "path": "/home/debian/ark/var/audio/WZBC/WZBC-20220122T190000Z.mp4"
        }
      ]
    }
  ]
}
```

and the corresponding playlist as expected does not have `#EXT-X-ENDLIST`

```
#EXTM3U
#EXT-X-TARGETDURATION:23
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:23.000,
https://ark3.spinitron.com/ark2/WZBC-20220122T185000Z/seg-1-a1.ts
#EXTINF:23.000,
https://ark3.spinitron.com/ark2/WZBC-20220122T185000Z/seg-2-a1.ts
#EXTINF:23.000,
https://ark3.spinitron.com/ark2/WZBC-20220122T185000Z/seg-3-a1.ts
...

#EXTINF:23.000,
https://ark3.spinitron.com/ark2/WZBC-20220122T185000Z/seg-337-a1.ts
#EXTINF:23.000,
https://ark3.spinitron.com/ark2/WZBC-20220122T185000Z/seg-338-a1.ts
#EXTINF:23.000,
https://ark3.spinitron.com/ark2/WZBC-20220122T185000Z/seg-339-a1.ts
```

(Thanks for @rhummelmose  and @erankor this feature and for nginx-vod-module. It's very useful.)

**Comment by rhummelmose** [comment]
Hey Spinitron,

I experience the same and I think it is just the default behavior. In our apps we seek to 0 after having loaded the stream and with AVPlayer on iOS we initially have to seek to -duration as it perceives 0 to be that position it starts at. Super weird, yes.

Let me know if you discover something :)

**Comment by spinitron** [comment]
Good to know. Thanks @rhummelmose.

We want to allow anyone to use our stream (m3u8) URLs so I guess this means the default needs to be a VOD playlist. Players can use a more complicated version of the URL if they are prepared to seek to the start.

**Comment by rhummelmose** [comment]
@spinitron keep in mind that if the event stream has come to an end, players will default to playing from the beginning (y)
