### ISSUE TITLE
[question] High async_read_file every 10 minutes

### ISSUE THREAD

**Issue by Oinari** [kaltura/nginx-vod-module#1274]
Hello.
The vod performance counters shows a multiple increase async_read_file metric every 10 minutes. This server also increases iowait. At the same time, the client load on the server does not change, and there are no metadata eviction events.

![image](https://user-images.githubusercontent.com/1106550/118143360-b09f8a00-b424-11eb-9140-706a219ece86.png)

What could it be?

**Comment by erankor** [comment]
there are no timers/periodic tasks in this module, so this must be something external - either more requests, or something that loads the storage/network and slows it down.
