### ISSUE TITLE
[Question] How to change order of audio tracks in manifest?

### ISSUE THREAD

**Issue by brooklyn097** [kaltura/nginx-vod-module#1275]
Hello, thanks for this awesome module!!!

I'm currently using mapped mode local to build manifest.

The master url is: `http://127.0.0.1/test.json/master.m3u8`

and manifest content like this:

`#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="日本語",LANGUAGE="ja",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="http://127.0.0.1/test.json/index-f1-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="English",LANGUAGE="en",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="http://127.0.0.1/test.json/index-f1-a2.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=522320,RESOLUTION=480x360,FRAME-RATE=25.000,CODECS="avc1.640015,mp4a.40.2",AUDIO="audio0"
http://127.0.0.1/test.json/index-f1-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1002922,RESOLUTION=960x720,FRAME-RATE=25.000,CODECS="avc1.64001f,mp4a.40.2",AUDIO="audio0"
http://127.0.0.1/test.json/index-f2-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1780528,RESOLUTION=1440x1080,FRAME-RATE=25.000,CODECS="avc1.640028,mp4a.40.2",AUDIO="audio0"
http://127.0.0.1/test.json/index-f3-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=28946,RESOLUTION=480x360,CODECS="avc1.640015",URI="http://127.0.0.1/test.json/iframes-f1-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=63757,RESOLUTION=960x720,CODECS="avc1.64001f",URI="http://127.0.0.1/test.json/iframes-f2-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=104565,RESOLUTION=1440x1080,CODECS="avc1.640028",URI="http://127.0.0.1/test.json/iframes-f3-v1-a1.m3u8"`

There are 2 audio tracks Japanese and English so my question is how can i move English above of Japanese without changing their index in video metadata ? I only want to change their order in manifest but not AUTOSELECTED or DEFAULT parameters.

**Comment by erankor** [comment]
The module always outputs AUTOSELECT=YES & DEFAULT=YES for the first audio and NO for the rest, so you can't change the order without affecting the DEFAULT/AUTOSELECT.

**Comment by brooklyn097** [comment]
> The module always outputs AUTOSELECT=YES & DEFAULT=YES for the first audio and NO for the rest, so you can't change the order without affecting the DEFAULT/AUTOSELECT.

Hi @erankor , thanks for your quick response.

I've tested json like this

`{
	"sequences": [
	{
		"language": "kor",
 		"label": "Korean",
		"clips": [{
			"type": "source",
			"path": "/path/to/file/360.mp4"
		}]
	},
	{
		"language": "chi",
 		"label": "Chinese",
		"clips": [{
			"type": "source",
			"path": "/path/to/file/720.mp4"
		}]
	},
	{
		"clips": [{
			"type": "source",
			"path": "/path/to/file/1080.mp4"
		}]
	}
	]
}`

and the module prints out manifest like this:

`#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="Japanese",LANGUAGE="ja",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="http://127.0.0.1/test.json/index-f1-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="English",LANGUAGE="en",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="http://127.0.0.1/test.json/index-f2-a1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="日本語",LANGUAGE="ja",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="http://127.0.0.1/test.json/index-f3-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=522320,RESOLUTION=480x360,FRAME-RATE=25.000,CODECS="avc1.640015,mp4a.40.2",AUDIO="audio0"
http://127.0.0.1/test.json/index-f1-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1002922,RESOLUTION=960x720,FRAME-RATE=25.000,CODECS="avc1.64001f,mp4a.40.2",AUDIO="audio0"
http://127.0.0.1/test.json/index-f2-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1780528,RESOLUTION=1440x1080,FRAME-RATE=25.000,CODECS="avc1.640028,mp4a.40.2",AUDIO="audio0"
http://127.0.0.1/test.json/index-f3-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=28946,RESOLUTION=480x360,CODECS="avc1.640015",URI="http://127.0.0.1/test.json/iframes-f1-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=63757,RESOLUTION=960x720,CODECS="avc1.64001f",URI="http://127.0.0.1/test.json/iframes-f2-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=104565,RESOLUTION=1440x1080,CODECS="avc1.640028",URI="http://127.0.0.1/test.json/iframes-f3-v1-a1.m3u8"`

We can see the module added 2 new audios KOR and CHI (they actually don't exist) but the JPN audio still there in the config at 3rd because i don't configure the language on 1080 file so is there any chance for an unofficial way to do that, im mean tell the module that use my configs instead of automatically generate?

**Comment by erankor** [comment]
Is it possible you pasted non-matching JSON + manifest? the JSON has Korean & Chinese while the manifest has English & Japanese...
If what you want is to ignore the audio of the third file, easiest solution is to add "tracks": "v1" to its source object in the JSON.

**Comment by brooklyn097** [comment]
> Is it possible you pasted non-matching JSON + manifest? the JSON has Korean & Chinese while the manifest has English & Japanese...
> If what you want is to ignore the audio of the third file, easiest solution is to add "tracks": "v1" to its source object in the JSON.

Thank you @erankor, i will close this issue ^^
