### ISSUE TITLE
Unknown stream in .ts segments (HLS segmenter)

### ISSUE THREAD

**Issue by theMaskedMushroom** [kaltura/nginx-vod-module#128]
When using the HLS packager, the resulting .ts segments have 3 input streams (1 video, 1 audio, and 1 unknown).

The streams are still digestible by my Flash client (using mangui's HLS plugin), but the logs do read 1 error and 1 warning ("unsupported type 15 in PMT", and "length too short! = 4").

It's a detail, not crucial, but I'm still unable to explain the phenomenon. Also, I can't tell if other clients will choke on this detail...

Here's the ffprobe output on the source .mp4 file:
--------------------------------------------
 ./ffprobe /mnt/video_sources/videos/localization/archimedes_english.mp4
ffprobe version 2.1.3 Copyright (c) 2007-2013 the FFmpeg developers
  built on Apr 11 2015 16:52:59 with gcc 4.7 (Debian 4.7.2-5)
  configuration: --prefix=opt/kaltura/ffmpeg-2.1.3 --libdir=opt/kaltura/ffmpeg-2.1.3/lib --shlibdir=opt/kaltura/ffmpeg-2.1.3/lib --extra-cflags=' -fPIC -I/opt/kaltura/include' --extra-ldflags=-L/opt/kaltura/lib --disable-devices --enable-bzlib --enable-libfaac --enable-libgsm --enable-libmp3lame --enable-libschroedinger --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-filter=movie --enable-avfilter --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libvpx --enable-libspeex --enable-libass --enable-postproc --enable-pthreads --enable-static --enable-shared --enable-gpl --disable-debug --disable-optimizations --enable-libfdk-aac --enable-nonfree --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-pthreads --enable-swscale --enable-vdpau --enable-bzlib --disable-devices --enable-filter=movie --enable-version3 --enable-x11grab
  libavutil      52. 48.101 / 52. 48.101
  libavcodec     55. 39.101 / 55. 39.101
  libavformat    55. 19.104 / 55. 19.104
  libavdevice    55.  5.100 / 55.  5.100
  libavfilter     3. 90.100 /  3. 90.100
  libswscale      2.  5.101 /  2.  5.101
  libswresample   0. 17.104 /  0. 17.104
  libpostproc    52.  3.100 / 52.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/video_sources/videos/localization/archimedes_english.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2014-03-07 10:31:32
  Duration: 00:03:00.49, start: 0.000000, bitrate: 2543 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 2348 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 191 kb/s (default)
    Metadata:
      creation_time   : 2014-03-07 10:31:33
      handler_name    : IsoMedia File Produced by Google, 5-11-2011
----------------------------------------------------

Here's the ffprobe output for one of the segments generated from the above source (as described in the generated m3u8 manifest):
------------------------------------------------
 ./ffprobe http://10.100.4.247/videos/localization/archimedes_english.mp4/seg-8-v1-a1.ts
ffprobe version 2.1.3 Copyright (c) 2007-2013 the FFmpeg developers
  built on Apr 11 2015 16:52:59 with gcc 4.7 (Debian 4.7.2-5)
  configuration: --prefix=opt/kaltura/ffmpeg-2.1.3 --libdir=opt/kaltura/ffmpeg-2.1.3/lib --shlibdir=opt/kaltura/ffmpeg-2.1.3/lib --extra-cflags=' -fPIC -I/opt/kaltura/include' --extra-ldflags=-L/opt/kaltura/lib --disable-devices --enable-bzlib --enable-libfaac --enable-libgsm --enable-libmp3lame --enable-libschroedinger --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-filter=movie --enable-avfilter --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libvpx --enable-libspeex --enable-libass --enable-postproc --enable-pthreads --enable-static --enable-shared --enable-gpl --disable-debug --disable-optimizations --enable-libfdk-aac --enable-nonfree --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-pthreads --enable-swscale --enable-vdpau --enable-bzlib --disable-devices --enable-filter=movie --enable-version3 --enable-x11grab
  libavutil      52. 48.101 / 52. 48.101
  libavcodec     55. 39.101 / 55. 39.101
  libavformat    55. 19.104 / 55. 19.104
  libavdevice    55.  5.100 / 55.  5.100
  libavfilter     3. 90.100 /  3. 90.100
  libswscale      2.  5.101 /  2.  5.101
  libswresample   0. 17.104 /  0. 17.104
  libpostproc    52.  3.100 / 52.  3.100
[NULL @ 0x7fd0e0] start time is not set in estimate_timings_from_pts
[mpegts @ 0x7f51e0] Could not find codec parameters for stream 2 (Unknown: none ([21][0][0][0] / 0x0015)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'http://10.100.4.247/videos/localization/archimedes_english.mp4/seg-8-v1-a1.ts':
  Duration: 00:00:03.71, start: 26.377256, bitrate: 3216 kb/s
  Program 1
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 193 kb/s
    Stream #0:2[0x102]: Unknown: none ([21][0][0][0] / 0x0015)
Unsupported codec with id 0 for input stream 2
-------------------------------------------------------------

P.S.: Thank you a million times for this splendid module!!! Really.

**Comment by theMaskedMushroom** [comment]
This is my configuration file:

```
user  root;
worker_processes  4;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;
    tcp_nodelay     on;

    keepalive_timeout  65;


    server {
        listen       80;
        server_name  streaming-box;

        # shared memory zones
        vod_moov_cache moov_cache 1024m;
        vod_path_mapping_cache mapping_cache 64m;
        vod_response_cache response_cache 64m;
        vod_performance_counters perf_counters;

        # common file caching
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        aio on;



        location / {
                root /mnt/video_sources;
                vod hls;
                vod_mode local;

                # Segments
                vod_segment_duration                    5000;
                vod_bootstrap_segment_durations         2000;
                vod_bootstrap_segment_durations         2000;
                vod_bootstrap_segment_durations         2000;
                vod_bootstrap_segment_durations         4000;

                vod_align_segments_to_key_frames        on;
                vod_manifest_segment_durations_mode     accurate;

                #gzip on;
                #gzip_types application/vnd.apple.mpegurl;

                expires 100d;
                add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
                add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
                add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
        }

        # Serve the crossdomain from the mounted samba share
        location = /crossdomain.xml {
                root /mnt/video_sources;
        }

        # vod status page
        location /vod_status {
                vod_status;
                access_log off;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

    }

}

```

**Comment by erankor** [comment]
The "unknown" stream is the ID3 stream, added here: https://github.com/kaltura/nginx-vod-module/blob/master/vod/hls/mpegts_encoder_filter.c#L379.
Currently, it's not really used, the module does not output anything on this stream, but we may use it in the future for sending time based metadata on the stream (encoded as ID3 tags).
I really doubt it will cause any issues as I've seen other packagers, e.g. Wowza, that send it.

**Comment by theMaskedMushroom** [comment]
Splendid! Understood.

Thanks again for the awesome work.
