### ISSUE TITLE
Fallback vod_upstream_location

### ISSUE THREAD

**Issue by kolevgeorgie** [kaltura/nginx-vod-module#1280]
We've been using the plugin for more than an year now and its working flawlessly. Now, we are trying to add another upstream for the VOD files as backup in case the first one fails (most expected fail is 404). 

Problem is that the two storage locations are using different providers/integrations (e.g. S3 and Google) which prevents us from simply adding another server in the proxy_pass upstream block due to different security and headers required. 

Can you recommend a solution?

**Comment by erankor** [comment]
Not sure what exactly is the behavior you're looking for... but if you know in advance which fallback you'll want to use, you call put something on the URL that will indicate it (e.g. /fallback/s3/ vs. /fallback/gcp/). If you do that, you can use 2 fallback locations, each one will handle one type of fallback (set the required headers etc.) and catch only the relevant requests using regex on the uri.

**Comment by kolevgeorgie** [comment]
Unfortunately I cannot know in advance where the file will be stored. 

Behavior should be the following:
1. Client requests file
2. nginx tries serving from `/storage1` where we have configured  hls remote vod mode.
3. if `/storage1` fails then serve from `/storage2`

**Comment by phillipseamore** [comment]
You should be able to use `error_page` in nginx to try another location. Something like:
```
location ~/vod/(.*)$ {
    #nginx-vod-module settings for S3
    error_page 404 /vodGCS/$1;
}
location ~/vodGCS/(.*)$ {
    #nginx-vod-module settings for GCS
}
```

**Comment by kolevgeorgie** [comment]
In case someone is having the same issue, my solution was to have two server blocks for each storage and then use them in upstream.
