### ISSUE TITLE
Compile error with recent ffmpeg changes

### ISSUE THREAD

**Issue by rhummelmose** [kaltura/nginx-vod-module#1287]
I get the following with the newest compiler on macos:
```
../nginx-vod-module/vod/filters/audio_decoder.c:14:16: error: assigning to 'AVCodec *' (aka 'struct AVCodec *') from 'const AVCodec *' (aka 'const struct AVCodec *') discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        decoder_codec = avcodec_find_decoder(AV_CODEC_ID_AAC);
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It seems like a sensible error as the const returned from the function is assigned to a static that might break the const promise?

**Comment by erankor** [comment]
yeah, looks like ffmpeg changed it...
https://github.com/FFmpeg/FFmpeg/commit/626535f6a169e2d821b969e0ea77125ba7482113

**Comment by rhummelmose** [comment]
@erankor see linked PR
