### ISSUE TITLE
Forumulating a urlset with language information

### ISSUE THREAD

**Issue by pacepace** [kaltura/nginx-vod-module#1295]
I've got many files that have multiple audio tracks, but these tracks are not labeled properly.  I'm hoping that I can formulate a url that can fix this issue.  I've seen some examples of how to do this on various issues, but none of the formats work for me.  I cannot share our URLs, but hopefully examples will work.

Here's a simplified URL that points to an mp4 urlset (audiotest_adaptive1.mp4 through audiotest_adaptive6.mp4) each with a single video and two audio tracks, both audio tracks are not tagged with a language:

https://mycdn.com/mycustomer/audiotest_adaptive,1,2,3,4,5,6,.mp4.urlset/master.m3u8

Is there a way to specify the languages in that url somehow?

The first track is English, the second track is Spanish, but as I said not specified:

![image](https://user-images.githubusercontent.com/24831802/126882413-fe8c02e5-8974-4b59-9897-8c70c5195ace.png)

Thanks in advance for help!
pace

**Comment by erankor** [comment]
It would be quite a nasty URL... something like this -
`https://mycdn.com/mycustomer/,tracks/v1-a1/lang/eng/1,tracks/a2/lang/spa/1,2,3,4,5,6,.mp4.urlset/master.m3u8`

The module takes each middle part (between commas) and builds a URL out of it, so the sample I wrote will expand to -
`https://mycdn.com/mycustomer/tracks/v1-a1/lang/eng/1.mp4.urlset/master.m3u8` (1.mp4 video + English track)
`https://mycdn.com/mycustomer/tracks/a2/lang/spa/1.mp4.urlset/master.m3u8` (1.mp4 Spanish track)
`https://mycdn.com/mycustomer/2.mp4.urlset/master.m3u8` (2.mp4 video - audio will be ignored since it has not label)
...

**Comment by pacepace** [comment]
I should note that the following work to properly select the language on a single video:

ENG: https://mycdn.com/mycustomer/audiottest_adaptive1.mp4/tracks/v1-a1/lang/eng/master.m3u8
SPA: https://mycdn.com/mycustomer/audiottest_adaptive1.mp4/tracks/v1-a2/lang/spa/master.m3u8

**Comment by pacepace** [comment]
Lots of trial and error and some code reading has produce the follow working url:

https://mycdn.com/mycustomer/audiotest_adaptive,1.mp4/tracks/v1-a1/lang/eng,1.mp4/tracks/v1-a2/lang/spa,2.mp4/tracks/v1-a1/lang/eng,2.mp4/tracks/v1-a2/lang/spa,3.mp4/tracks/v1-a1/lang/eng,3.mp4/tracks/v1-a2/lang/spa,4.mp4/tracks/v1-a1/lang/eng,4.mp4/tracks/v1-a2/lang/spa,5.mp4/tracks/v1-a1/lang/eng,5.mp4/tracks/v1-a2/lang/spa,6.mp4/tracks/v1-a1/lang/eng,6.mp4/tracks/v1-a2/lang/spa,.urlset/master.m3u8

This one does not work:
https://mycdn.com/mycustomer/audiotest_adaptive,1/tracks/v1-a1/lang/eng,1/tracks/v1-a2/lang/spa,2/tracks/v1-a1/lang/eng,2/tracks/v1-a2/lang/spa,3/tracks/v1-a1/lang/eng,3/tracks/v1-a2/lang/spa,4/tracks/v1-a1/lang/eng,4/tracks/v1-a2/lang/spa,5/tracks/v1-a1/lang/eng,5/tracks/v1-a2/lang/spa,6/tracks/v1-a1/lang/eng,6/tracks/v1-a2/lang/spa,.mp4.urlset/master.m3u8

The difference is in the first I added .mp4 to each filename and in the second I used .mp4.urlset to try to add it automatically.  It does not add the MP4 and you can see that it does not by the error message it produces:

2021/07/27 22:29:12 [error] 8#8: *9538 ngx_file_reader_update_state_file_info: open() "/opt/static/videos/mycustomer/audiotest_adaptive6" failed (2: No such file or directory), client: 10.64.7.1, server: localhost

It is quite true that the above file does not exist without the .mp4 on it.

Should I bug this?

**Comment by erankor** [comment]
It's not a bug... you need to understand how these URLs work... if we look at the non-working one -
prefix = https://mycdn.com/mycustomer/audiotest_adaptive
first middle part = 1/tracks/v1-a1/lang/eng
suffix = .mp4.urlset/master.m3u8

if you concat these together, you get -
https://mycdn.com/mycustomer/audiotest_adaptive1/tracks/v1-a1/lang/eng.mp4.urlset/master.m3u8

And, as you can see, the .mp4 extension is next to the language, it's not next to the filename.
