### ISSUE TITLE
400 Bad Request fetching last segment causes Apple's AVPlayer to stop refreshing live playlist

### ISSUE THREAD

**Issue by rhummelmose** [kaltura/nginx-vod-module#1297]
I understand that the returned error is sent because we don't want the incomplete segment to be stored in caches, but wouldn't it be possible not to include the incomplete segment in the playlist at all?

The problem I'm observing is that the most recent AVPlayer will stop requesting the playlist when it encounters 400 bad request. When the playlist has played till the end it will finally request the playlist again and jump back a few seconds causing both a stop and a bad experience.

Hope for advice.

**Comment by erankor** [comment]
The module is not expected to return a URL for a segment that is not ready in the manifest. 
I don't know what is your setup, but if you have multiple servers whose clocks are not synchronized, that is one possible cause for this.

**Comment by rhummelmose** [comment]
@erankor interesting, I actually decreased the number of replicas of the VOD instance to check whether this might be the cause of the issue. I can however see that it is actually returning the segment in the playlist. Could the cause of this be that I am using the branch with playlist-type event? The code path follows the same behavior as playlist-type vod, apart from the fact that it doesn't return "end list" and it sets another tag.

**Comment by rhummelmose** [comment]
Example:

`
➜  ~ curl https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/index-a1.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:9.941,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-1-a1.ts
#EXTINF:9.900,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-2-a1.ts
#EXTINF:7.920,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-3-a1.ts
#EXTINF:9.900,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-4-a1.ts
#EXTINF:7.920,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-5-a1.ts
#EXTINF:9.900,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-6-a1.ts
#EXTINF:7.920,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-7-a1.ts
#EXTINF:9.900,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-8-a1.ts
#EXTINF:7.920,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-9-a1.ts
#EXTINF:8.893,
https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-10-a1.ts
➜  ~ wget https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-10-a1.ts
--2021-08-12 10:13:10--  https://stream.denuafhaengige.dk/vod/hls/broadcasts/412/segments/segment-10-a1.ts
Løser stream.denuafhaengige.dk (stream.denuafhaengige.dk)... 40.115.41.78
Tilslutter stream.denuafhaengige.dk (stream.denuafhaengige.dk)|40.115.41.78|:443... forbundet.
HTTP forespørgsel sendt, afventer svar... 400 Bad Request
2021-08-12 10:13:10 FEJL 400: Bad Request.

➜  ~ 
`

**Comment by rhummelmose** [comment]
Okay, so I've tested _playlistType_ **live** and as you say, that option does not include incomplete segments in the playlist. With _vod_live_window_duration_ **0** I actually get exactly the desired behavior, with the exception of the fact that the playlist type has to be changed. With that in mind I will try to understand how I can alter the open PR to fix this.
