### ISSUE TITLE
dash smpte-tt subtitle working?

### ISSUE THREAD

**Issue by fingul** [kaltura/nginx-vod-module#1298]
Hi!

Dash smpte-tt subtitle look not working. (When request subtitle it returns 404 error)

 Any idea?

> setting : vod_dash_subtitle_format smpte-tt;

**Comment by erankor** [comment]
Did you check the nginx error log?

**Comment by fingul** [comment]
https://github.com/fingul/test_subtitle_nginx_vod

**Comment by fingul** [comment]
> MANFEST REQUEST : http://localhost:3030/dashs/devito,360p.mp4,.en_US.vtt,.urlset/manifest.mpd

<img width="847" alt="Screen Shot 2021-08-11 at 11 05 06 PM" src="https://user-images.githubusercontent.com/894739/129043776-092b2b60-459d-45d0-b2f5-25af672c33c0.png">

> SUBTITLE SEGMENT REQUEST : http://localhost:3030/dashs/devito,360p.mp4,.en_US.vtt,.urlset/init-f2.

400 BadRequest

> NGINX SERVER LOG 

172.17.0.1 - [11/Aug/2021:14:08:24 +0000] "GET /dashs/devito,360p.mp4,.en_US.vtt,.urlset/init-f2. HTTP/1.1" 400 "-" "HTTPie/2.3.0"
2021/08/11 14:08:24 [error] 7#7: *4 ngx_http_vod_dash_parse_uri_file_name: unidentified request, client: 172.17.0.1, server: localhost, request: "GET /dashs/devito,360p.mp4,.en_US.vtt,.urlset/init-f2. HTTP/1.1", host: "localhost:3030"

**Comment by erankor** [comment]
I think it broke in #1219... the init/media segments are missing the file extension.
Try this PR #1299

**Comment by fingul** [comment]
PR #1299 works! Thank you!

**Comment by erankor** [comment]
Merged, thanks!
