### ISSUE TITLE
moov_cache on file?

### ISSUE THREAD

**Issue by doublex** [kaltura/nginx-vod-module#130]
Hello,
First: Excellent code!
A question: Is there a chance to cache the moov-atoms on file, e.g. on a SSD?
Thanks a lot
Markus

**Comment by erankor** [comment]
Currently, only caching in shared memory (RAM) is supported, sorry. We may add it in the future.
However, if you can allocate several GBs that should be more than enough for most deployments, we are working with 4GB and we get more than 90% cache hit.
