### ISSUE TITLE
Cannot install in Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by joseproig** [kaltura/nginx-vod-module#1300]
I have a Raspberry Pi 4 with Ubuntu Server 20.04.2 LTS and I was trying to install kaltura-nginx (with multiverse repository activated) and when i tried to install kaltura-nginx package (with all the steps explained) it appeared me this following error "E: Unable to locate package kaltura-nginx"

**Comment by jessp01** [comment]
Hi @joseproig,

What repo did you try to use?

Thanks,

**Comment by joseproig** [comment]
I tried the  Ubuntu 20.04 repo, but it didn't work

**Comment by jessp01** [comment]
Hi @joseproig,

To be clear, here are the commands you're meant to run:
```
# wget -O - http://installrepo.kaltura.org/repo/aptn/focal/kaltura-deb-256.gpg.key|apt-key add -
# echo "deb [arch=amd64] http://installrepo.kaltura.org/repo/aptn/focal quasar main" > /etc/apt/sources.list.d/kaltura.list
# apt update
# apt install kaltura-nginx
```

Please provide the full output for the above and we can take it from there.

Thanks,

**Comment by joseproig** [comment]
Hi @jessp01,

I follewed this steps before and I have obtained no result again.

![doubt_1](https://user-images.githubusercontent.com/43382694/129928608-08fece01-ba7d-4e95-a12f-7e01fc1ac83d.jpg)

**Comment by jessp01** [comment]
Hi @joseproig,

I missed the Raspberry Pi part before.
As you can gather from the documentation, we only package for `amd64` whereas, Raspberry Pi is `arm`:
> The Raspberry Pi 4 uses a Broadcom BCM2711 SoC with a 1.5 GHz 64-bit quad-core ARM Cortex-A72 processor, with 1 MB shared L2 cache.

You can compile the module yourself, however, see https://github.com/kaltura/nginx-vod-module#compilation

Cheers,
