### ISSUE TITLE
mp4 files to hls no sound only video picture

### ISSUE THREAD

**Issue by poorboy1991** [kaltura/nginx-vod-module#1308]
the mp4 files with opus audio stream , use nginx-vod-module generate hls, there is no sound when play m3u8

**Comment by erankor** [comment]
Opus is supported only in DASH

**Comment by poorboy1991** [comment]
But when I choose DASH, links: http://localhost:9200/dash/11-10-13.mp4/manifest.mpd,  then I get
mp4_parser_process_moov_atom_callback: no extra data was parsed for track, client: 10.9.114.24, server: , request: "GET /dash/11-25-14.mp4/manifest.mpd HTTP/1.0"

mp4 file:
https://user-images.githubusercontent.com/5009620/134800221-233622c8-ece7-466a-a679-ee7bc6af5862.mp4

**Comment by erankor** [comment]
The file is corrupt, it has no `dOps` atom in `stsd`, ffmpeg can't parse it as well -
$ ffprobe -i 134800221-233622c8-ece7-466a-a679-ee7bc6af5862.mp4 -select_streams a -show_frames
...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000002cbeac0] Could not find codec parameters for stream 1 (Audio: none (Opus / 0x7375704F), 48000 Hz, 2 channels, 29 kb/s): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
...
Unsupported codec with id 0 for input stream 1

**Comment by poorboy1991** [comment]
then we use ffmpeg transform opus mp4 to aac fixed it.
