### ISSUE TITLE
remote upstream doesn't work with chunked transfers (no Content-Length)

### ISSUE THREAD

**Issue by benwilber** [kaltura/nginx-vod-module#131]
[Relevant line of code](https://github.com/kaltura/nginx-vod-module/blob/master/ngx_child_http_request.c#L202)

Example server:
```
$ wget -qS -O /dev/null --header="Range: bytes=0-4096" http://sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4
  HTTP/1.1 206 Partial Content
  Server: nginx/1.4.0
  Date: Fri, 14 Aug 2015 01:28:26 GMT
  Content-Type: video/mp4
  Transfer-Encoding: chunked
  Connection: keep-alive
  Expires: Sun, 13 Sep 2015 01:28:26 UTC
  Vary: Origin
  Content-Range: bytes 0-4096/1055736
  Etag: "8d402ae-101bf8-51ab1b3309640"
  Last-Modified: Thu, 13 Aug 2015 21:57:29 GMT
  Cache-Control: max-age=2592000
```

The code always expects a `Content-Length` header, which wont be present with chunked transfers.  I was able to hack it to work with the following `header_filter_by_lua` script:

```
if not ngx.header.content_length and ngx.header.content_range then
  local start_byte, end_byte = ngx.header.content_range:match("bytes (%d+)-(%d+)/%d+")
  if start_byte and end_byte then
    ngx.header.Content_Length = (end_byte - start_byte) + 1
  end
end
```

**Comment by erankor** [comment]
Hi @benwilber, 

It shouldn't be too hard to change the code so that it will not require the Content-Length header, however I'm curious regarding the configuration of the upstream server, is this a server you manage ? can you share its configuration ?
It's quite weird that the server uses chunked encoding when it knows the exact content length (as can be seen in the content-range header that you use in your Lua script)

**Comment by benwilber** [comment]
Hi @erankor, unfortunately no I don't manage this site and am unsure what the configuration is.  It's just one of a few different publicly hosted mp4 sites I've been using to test my HLS remote configuration.

**Comment by erankor** [comment]
In that case, you're lucky they support range requests ;-)
I'll see if I have some time this week to address it, one way to solve it would be to look at the content range like you did with Lua, but I'll need to check whether I can work without having both content length and content range.

Btw, with your Lua work around, is it working for you end-to-end ? I just wasn't sure whether the chunked encoding will be stripped correctly by nginx in this flow

**Comment by benwilber** [comment]
Yeah it seems to work just fine with the Lua script.  I've tested both HLS and DASH and I haven't seen any issue with it.  I thought that nginx would prefer to drop the `Content-Length` where `Transfer-Encoding: chunked`, but maybe that test happens before my Lua script runs?  Either way, it's not present in the upstream response and adding it after the fact doesn't seem to hurt anything.

**Comment by erankor** [comment]
Should be resolved with latest master since nginx-vod now uses proxy_pass to issue upstream requests, please let me know if it resolves the issue for you
