### ISSUE TITLE
Opus audio always detected as webm container + how to switch between codecs

### ISSUE THREAD

**Issue by ufou** [kaltura/nginx-vod-module#1317]
Hi,

We've used this wonderful module for sometime now, streaming single bitrate m4a (aac).

We have a new requirement which is to offer multi-bit rate hls/dash, which again this module does really nicely  - we have this working too, however we notice an issue for dash where if one of the adaptive set files uses `aac` codec and the other uses `opus` (both in mp4 container), depending on the client connection, either aac or opus file will only play and regardless of changing bitrate capability of the client will not switch to the other - I suspect this is due to the fact that opus is forced by the module to the `webm` container as opposed to `mp4` but I could be wrong?

Assuming I'm correct, would there be any plans to allow opus audio in mp4 container?

Thanks!

**Comment by erankor** [comment]
Hi,

No plans to support opus in mp4 output... 
But I doubt that would be enough to have the client dynamically switch between them. Regardless of the container used, the module outputs different codecs in different adaptation sets (this is true for both audio & video). But, even if it would output both on the same adaptation set, I'm not sure the player would support such a switch.
I think the implementation of multiple codecs usually involves having the entire ladder on both codecs. The player is supposed to choose the most "efficient" codec it can hold. For example, in this case, if Opus normally provides better quality for a given bitrate than AAC, the player should prefer the Opus ladder, and fall back to the AAC ladder only if Opus is not supported on the device.

**Comment by ufou** [comment]
Thanks, this confirms what I thought might be the case, though I'd hoped otherwise - we were trying to avoid having to duplicate m4a/opus at each bit rate, thanks for replying!

**Comment by ufou** [comment]
Actually shaka player does allow switching between codecs, if the container is the same :(
```
--allow_codec_switching
If enabled, allow adaptive switching between different codecs, if they have the same language, media type (audio, video etc) and container type.
```

**Comment by erankor** [comment]
yeah, but on the other hand, they did decide to have it 'false' by default :)
I'm not sure you can have perfectly aligned segments cross-codec. For example, AAC uses frames of 1024 samples, if OPUS uses 1500 (don't know what the actual number is...), the frames will have different timestamps, and switching between the codecs will likely produce a noticeable glitch.
