### ISSUE TITLE
Mapping requests for each segment?

### ISSUE THREAD

**Issue by spinitron** [kaltura/nginx-vod-module#1325]
I'm using mapped mode to provide on-demand HLS playback of past radio programs. A PHP script generates the mappings and it writes logs describing its activity. I am surprised to see segment requests in the log like this...

```
Dec 12 11:32:08 "/ark2/KBCS-20211212T050000Z/seg-134-a1.ts" Sent cache file: /home/admin/ark2/src/../var/cache/mapper/responses/KBCS/20211212T050000Z
Dec 12 11:32:18 "/ark2/KBCS-20211212T050000Z/seg-135-a1.ts" Sent cache file: /home/admin/ark2/src/../var/cache/mapper/responses/KBCS/20211212T050000Z
Dec 12 11:32:28 "/ark2/KBCS-20211212T050000Z/seg-136-a1.ts" Sent cache file: /home/admin/ark2/src/../var/cache/mapper/responses/KBCS/20211212T050000Z
Dec 12 11:32:38 "/ark2/KBCS-20211212T050000Z/seg-137-a1.ts" Sent cache file: /home/admin/ark2/src/../var/cache/mapper/responses/KBCS/20211212T050000Z
```

Why? I would think only playlist requests need to be mapped. When the client requests a segment, nginx-vod-module should be able to deliver that with the already mapped playlist request, no? I don't even know what the mapper script is supposed to do with the segment file name in the request.

Relevant nginx configs

```
server {
    vod_mode mapped;
    vod_upstream_location /kalapi;
    vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
    vod_last_modified_types *;
    vod_manifest_segment_durations_mode accurate;
    vod_path_response_prefix '{';
    vod_max_mapping_response_size 128k;
    vod_open_file_thread_pool default;
    vod_metadata_cache metadata_cache 512m;
    vod_response_cache response_cache 128m;
    vod_mapping_cache mapping_cache 5m 300s;
    gzip on;
    gzip_types application/vnd.apple.mpegurl;
    open_file_cache max=1000 inactive=5m;
    open_file_cache_valid 2m;
    open_file_cache_min_uses 1;
    open_file_cache_errors on;
    aio on;

    location ^~ /kalapi/ {
        internal;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME {{ pillar.ark2_app_root }}/web/index.php;
    }

    location ^~ /ark2/ {
        vod hls;
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 14d;
    }
}

upstream netdata {
    server 127.0.0.1:19999;
    keepalive 64;
}
```

**Comment by erankor** [comment]
The module cannot assume that it will get a manifest request before a segment request, there are many scenarios in which this assumption would break (e.g. multiple servers, server restart etc.). So, when it comes to mapping, it makes no distinction between segments and manifests.
But, that said, I agree it makes no sense to call the mapping endpoint for each segment... for this reason, the module has support for caching the mapping response in shared memory. From what I see, you already have this cache enabled - vod_mapping_cache. 
Maybe the config you pasted is not the actual config that is running (reload failed maybe)? 
You can add a location with 'vod_status' handler, and curl it to get stats on the cache usage (hit/miss etc.). 
Another option is to compile nginx with debug logs enabled (`--with-debug`) and look for the messages `mapping cache hit` / `mapping cache miss`.

**Comment by spinitron** [comment]
Thank you for the swift answer. That really helps me understand how to tune this system for performance.

Yes, I think the mapping_cache line was likely commented out when I was looking at the logs.

I now have 5 minutes mapping cache in the nginx-vod-module and up to 14 days in the mapper script.

**Comment by LodyWang** [comment]
> 

I originally planned to use the mapping mode to interact with the background interface system, but  I gave up  mapping mode decisively...... when I found play by HLS，the segment file request would interact with the interface system every time.
