### ISSUE TITLE
using ceph storage instead directory

### ISSUE THREAD

**Issue by rezaalimorady** [kaltura/nginx-vod-module#1326]
I want to serve mp4 files from ceph storage.
not from local directory.
how could i do that?

i have many mp4 files in ceph storage.
my kaltura vod module in another machine.
what shuld i put instaed location -> alias?

**Comment by erankor** [comment]
Not really familiar with ceph, but in my understanding, it's compatible with s3. 
So, you can take a conf similar to this - https://github.com/kaltura/nginx-vod-module/#remote-configuration
Set the upstream host to point to ceph, and start from there.

**Comment by rezaalimorady** [comment]
could you say pattern example?

i have mp4 file with this url
http://site.com/video1.mp4 and http://site.com/video2.mp4

how could use this two video with kaltura?

**Comment by erankor** [comment]
The sample config assumes our URL structure... you can edit it to something like this -
```
http {
	upstream storage {
		server your.storage.domain.com:80;
	}

	server {
		# vod settings
		vod_mode remote;
		vod_upstream_location /storage;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;

		# vod caches
		vod_metadata_cache metadata_cache 512m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;
		
		location ~ ^/storage/[^/]*/(.*) {
			internal;
			proxy_pass http://storage/$1;
			proxy_set_header Host $http_host;
		}

		location /hls/ {
			vod hls;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}
```
and then call `nginx-vod-domain/hls/video1.mp4/master.m3u8`

**Comment by rezaalimorady** [comment]
Thanks
works for me :)
