### ISSUE TITLE
Selfcompiled ffmpeg: Checking for libavcodec ... not found 

### ISSUE THREAD

**Issue by JokerGT** [kaltura/nginx-vod-module#1338]
im desperate trying to compile nginx + vod-modue linking to my self compiled ffmpeg like explained here: 

[ffmpeg compile insstructions](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu)

the result is a working **static** ffmpeg build with all the modules i added to it
 
however trying now to compile nginx including the vod-module, it does not detect my include/libs correctly:

checking for libavcodec ... not found
checking for libswscale ... not found
checking for libavfilter ... not found

i found in other issues to add:
env "LD_LIBRARY_PATH=$ROOTDIR/ffmpeg_build/lib" "LIBRARY_PATH=$ROOTDIR/ffmpeg_build/lib" "C_INCLUDE_PATH=$ROOTDIR/ffmpeg_build/include"

but this still does not help. the lib's aren't found.

maybe my static ffmpeg build is the problem? 

any help appreciated

**Comment by JokerGT** [comment]
i found the solution myself, hope this is helpful for others....

1st. actual nginx-vod-module depends on ffmpeg version < 5.x to work. otherwise avfilter fails to be detected. if you download the snapshot source from ffmpeg it is version 5.x
2nd you need to compile ffmpeg with --enable-shared to be detected by nginx-vod-module

for this to work you need todo this:

- use make CFLAGS=-fPIC instead of just make on all modules you add to ffmpeg - otherwise resulting .so files cannot link with nginx
- add   -pkg-config-flags="--static"  --enable-shared  --extra-cflags="-I/your/ffmpeg_build/include"  --extra-ldflags="-L/your/ffmpeg_build/lib" 
to your ffmpeg configure

**Comment by movy** [comment]
For those on Ubuntu with ffmpeg5, this worked:
```
apt-get install libavcodec-dev libswscale-dev

```

Configure & compile nginx:

```
./configure \
 --prefix=/etc/nginx \
 --conf-path=/etc/nginx/nginx.conf \
 --error-log-path=/var/log/nginx/error.log \
 --http-log-path=/var/log/nginx/access.log \
 --pid-path=/run/nginx.pid \
 --sbin-path=/usr/sbin/nginx \
 --with-http_ssl_module \
 --with-http_v2_module \
 --with-http_stub_status_module \
 --with-http_realip_module \
 --with-file-aio \
 --with-threads \
 --with-stream \
 --with-cc-opt="-O3 -mpopcnt" \
 --add-module=../nginx-vod-module-1.30

make && make install
 ```
