### ISSUE TITLE
Subtitle language codes in multi-URL mode

### ISSUE THREAD

**Issue by Media182** [kaltura/nginx-vod-module#1339]
I've checked many old issues and figured out that we can specify subtitle language code like this:
http://example.com/hls/videos/,video_400.mp4,video_900.mp4,/lang/eng/video.srt,.urlset/master.m3u8
or even without extensions like this shorter way:
http://example.com/hls/videos/,video_400,video_900,/lang/eng/video,.urlset/master.m3u8

But I really don't want to create extra subfolders /lang/eng/ + /lang/rus/...I want to keep all files in same folder and name them like:
video_400
video_900
video_eng
video_rus

So what I want is: when you parse the file and see it's Subtitle type AND its filename ends on _3 chars then use them as language ISO code to form correct .m3u8 manifest.

**Comment by erankor** [comment]
You don't need to create separate folders... the module removes from the URL the params that it uses (clipTo, clipFrom, speed, tracks, lang)

**Comment by Media182** [comment]
Thanks for clearing this out! Works just fine.
It's only long ugly URL, but I can live this this I guess.

**Comment by erankor** [comment]
Indeed, ugly urls... we use mapped mode, so we don't have this issue :)

**Comment by Media182** [comment]
Mapped mode is good and powerful, but we're trying not to use extra script calls for the best performance.
