### ISSUE TITLE
Building URL with separate video audio files

### ISSUE THREAD

**Issue by rguedes** [kaltura/nginx-vod-module#1343]
Hey, 

I'm using [nginx-vod-module] as local mode.

Domain.tld

Files: 

video: TITLE.720p.6f934a9.mp4
video: TITLE.1080p.6f934a9.mp4

audio: TITLE.AAC2.0.en.5ab34b.mp4
audio: TITLE.AC3.5.1.en.5ab34b.mp4

audio: TITLE.AAC2.0.de.6bb34b.mp4

subs: TITLE.en.d9cba4.srt
subs: TITLE.pt-PT.3c49f2.srt
subs: TITLE.fi.a679e2.srt

How can I build the url to DASH and HLS?

With a single video+audio file, I'm building like that:
https://Domain.tld/dash/,TITLE.720p.AAC2.0.en.mp4,lang/eng/TITLE.en.d9cba4.srt,lang/por/TITLE.pt-PT.3c49f2.srt,.urlset/manifest.mpd
or
https://Domain.tld/dash/,TITLE.1080p.AAC2.0.en.mp4,TITLE.720p.AAC2.0.en.mp4,lang/eng/TITLE.en.d9cba4.srt,lang/por/TITLE.pt-PT.3c49f2.srt,.urlset/manifest.mpd

But now, I want to build with separate video and audio files, because I want to reuse the audios with different resolutions and subs, depending on device type and user language.

**Comment by rguedes** [comment]
similar: https://github.com/kaltura/nginx-vod-module/issues/908

**Comment by erankor** [comment]
Sorry, I don't understand the question...
In general, you can take all the URLs you want (video, audio, captions) and combine them in multi-url syntax. 
The sample files you listed seem problematic though, because you have English AC3/5.1, without a matching German file, so don't see how that would work...

**Comment by rguedes** [comment]
I have:
- video1.1080p.mp4 (only with video stream)
- video2.mp4 (only with video stream)
- audio_en_aac.mp4 (only audio stream)
- audio_en_ac3mp4 (only audio stream)
- audio_de_aac.mp4 (only audio stream)
- subsN.str

I want to build different urls like that:
- video1 + audio_en_aac (https://domain/dash/,video1.1080p.mp4,lang/eng/audio_en_aac.mp4,.urlset/manifest.mpd
- video1 + audio_en_ac3
- video2 + audio_en_aac
- video2 + audio_en_ac3
- video2 + audio_de_aac
- etc
- 
But if I try to do that, I got an error:

ngx_http_vod_validate_streams: no matching streams were found while reading media header,

**Comment by rguedes** [comment]
I try with mapped too:

`
{
  "sequences": [
    {
      "clips": [
        {
          "type": "source",
          "path": "/media/a2b1e3/video1.1080p.mp4"
        }
      ]
    },
    {
      "clips": [
        {
          "type": "source",
          "path": "/media/a2b1e3/video1.720p.mp4"
        }
      ]
    },    
	{
      "clips": [
        {
          "type": "source",
          "path": "/media/a2b1e3/audio_ac3_en.mp4"
        }
      ]
    },    
	{
      "clips": [
        {
          "type": "source",
          "path": "/media/a2b1e3/audio_aac_en.mp4"
        }
      ]
    },
    {
      "language": "por",
      "clips": [
        {
          "type": "source",
          "path": "/media/a2b1e3/subs.pt-PT.3c49f2.srt"
        }
      ]
    },
    {
      "language": "eng",
      "clips": [
        {
          "type": "source",
          "path": "/media/a2b1e3/subs.en.d9cba4.srt"
        }
      ]
    }
  ]
}

`

error: ngx_http_vod_validate_streams: no matching streams were found while getting mapping

**Comment by rguedes** [comment]
Fixed.

I used MP4Box to "remux" the mp4 again and that fixed my problem ;)

Thx for support and feedback.
