### ISSUE TITLE
Multiple audio tracks with same language

### ISSUE THREAD

**Issue by mahe-ymc** [kaltura/nginx-vod-module#1355]
Hi,
some of our MP4 files come along with two audio tracks tagged with same language. One of them is the normal variant, the other one is further tagged with a "visually impaired" disposition.

As I can infer from other related issues, I think it's a known limitation that nginx-vod-module sets kind of a unique constraint on the language tag, resulting in mapping just one track of each unique language tag to (at least) HLS and ignoring the others.

We are open to address this issue by ourselves and PRing it back to you, but it would be nice to have some hints and insights from an existing library maintainer. We're curious if there's a deeper cause we just don't see yet or whether it's just an implementation level limitation.

**Comment by erankor** [comment]
The unique constraint is not on 'language' it's on 'label', under the assumption that it doesn't make sense to present the end user with two identical options. 
I don't know how the 'visually impaired' track is tagged, but most likely it's not recognized. And, in this case, both tracks get a default label derived from the language code, and one of them is ignored.
Assuming you want the module to pull this info from the MP4 file (the alternative is using the label field in mapping JSON...), there are currently two options - `vod_parse_hdlr_name` / `vod_parse_udta_name`. These options (both off by default) can extract a label for the track from the atom indicated in the option name.
So, for example, you can set a name of 'English - audio description' in hdlr + enable `vod_parse_hdlr_name`, and then you'll get both tracks.

**Comment by mahe-ymc** [comment]
Thanks for the pointer! Exactly like you said, works like a charm :partying_face:
