### ISSUE TITLE
vod variables

### ISSUE THREAD

**Issue by shaharmor** [kaltura/nginx-vod-module#136]
Hi,

Is there a list of available variables that i can use in the nginx config related to this module?

Specifically i want to add a header that will let me know if this request came from the cache or not

**Comment by erankor** [comment]
There are 2 variables, documented here:
https://github.com/kaltura/nginx-vod-module/#nginx-variables

There are no variables for checking whether a specific request used one of the caching layers, but you can enable the performance counters and set up a status page to check the overall cache hit/miss ratios
