### ISSUE TITLE
Multi URL structure support on files with commas in their name

### ISSUE THREAD

**Issue by ordasf** [kaltura/nginx-vod-module#1372]
Hi there, 

I am trying to use the Kaltura nginx-vod-module to serve HLS streams multi-bitrate for some content that has comma on their name. For example:

`http://localhost/hls/content/ac527e11-dddf-46a7-bd4c-bb916ec4431e/ac527e11-dddf-46a7-bd4c-bb916ec4431e,test-string.x264.,315,625,1240,.mp4.urlset/master.m3u8`

The list of files that serves that content would be:

`
content/ac527e11-dddf-46a7-bd4c-bb916ec4431e/ac527e11-dddf-46a7-bd4c-bb916ec4431e,test-string.x264.315.mp4
content/ac527e11-dddf-46a7-bd4c-bb916ec4431e/ac527e11-dddf-46a7-bd4c-bb916ec4431e,test-string.x264.625.mp4
content/ac527e11-dddf-46a7-bd4c-bb916ec4431e/ac527e11-dddf-46a7-bd4c-bb916ec4431e,test-string.x264.1240.mp4
`

If instead of using multi URL, I access each of the files individually it works, for example, this URL works:

`http://localhost/hls/content/ac527e11-dddf-46a7-bd4c-bb916ec4431e/ac527e11-dddf-46a7-bd4c-bb916ec4431e,test-string.x264.315.mp4/master.m3u8`

I tried escaping the comma name in the URL using %2C with no luck, I did not find anything in the documentation for this use case. Is there any way in the nginx-vod module to support multi URL structure for files with comma in their names? 

Many thanks.

**Comment by erankor** [comment]
Nope, this is not supported

**Comment by ordasf** [comment]
Thanks for the response
