### ISSUE TITLE
Getting 404 when accessing m3u8

### ISSUE THREAD

**Issue by jinyeng** [kaltura/nginx-vod-module#1374]
I have completed all instructions up to https://github.com/kaltura/nginx-vod-module#url-structure . Also have a video file in the location as asked after the installation of module. But when I try to play using http://localhost/hls/videos/video.mp4/index.m3u8 , I am getting a 404.

http://localhost works fine. Am I missing something ? Would really appreciate your help.

**Comment by erankor** [comment]
Did you check the nginx error log?

**Comment by JabbariDEV1** [comment]
Hi 
I have same problem too
anyone can help ?

**Comment by erankor** [comment]
Did you look at the error log? 
There can be many reasons for 404... without additional info it's impossible to guess what the problem is...
