### ISSUE TITLE
HLS error on merged duration

### ISSUE THREAD

**Issue by ErblinH** [kaltura/nginx-vod-module#1377]
Hello there, I have some errors when using mapped configuration for creating a m3u8 file from two mp4 files. 

I have a bunch of mp4 files and I try to merge them one by one by using nginx vod module.

After creating my m3u8 file I convert it to mp4 to get the merged file and after that I update the json file to merge the new mp4 segment. It works perfectly but when the duration of the merged files reaches a new minute it will merge only audio and when I get the ffprobe of the ts files generated by the nginx module I get this behaviour

```
ffprobe -hide_banner -print_format json -show_format http://127.0.0.1/video/playlist.json/seg-2-v1-a1.ts
{
[mpegts @ 0000023f66f020c0] start time for stream 2 is not set in estimate_timings_from_pts
Input #0, mpegts, from 'http://127.0.0.1/video/playlist.json/seg-2-v1-a1.ts':
  Duration: 00:00:10.09, start: 10.108800, bitrate: 1057 kb/s
  Program 1
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 132 kb/s
  Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Unsupported codec with id 100358 for input stream 2
    "format": {
        "filename": "http://127.0.0.1/video/playlist.json/seg-2-v1-a1.ts",
        "nb_streams": 3,
        "nb_programs": 1,
        "format_name": "mpegts",
        "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
        "start_time": "10.108800",
        "duration": "10.085611",
        "size": "1332920",
        "bit_rate": "1057284",
        "probe_score": 50
    }
}
```

I enabled vod_align_segments_to_key_frames, but still it doesn't work. This only happens when the duration of the merged files reaches a new minute, then it will work fine and crash again when reaching a new minute. When the duration is approaching a new minute I would manually specify the video codec in the ffmpeg command in order to work properly. 

The ffmpeg command I am using to convert m3u8 file to mp4 is:

ffmpeg -y -i http://.../video/playlist.json/master.m3u8 -c copy index.mp4

(I could specify the codec of the video and audio in the command but it is not effective when the mp4 file is 5+ hours)

**Comment by erankor** [comment]
It's a bit hard to understand what you're doing... but I'm guessing you're making the module generate segments with a duration that doesn't match the GOP size of the MP4 file. For example, if the MP4 file has a key frame every 20 sec, and you try to create 10 sec segments, some segments won't have any keyframe, and their video stream won't be decodable.
About the vod_align_segments_to_key_frames option, IIRC, when you use a non-trivial mapping (multiple MP4's in the JSON is an example) it won't work unless you provide the key frame positions in the JSON as well.
