### ISSUE TITLE
A/B test configurations

### ISSUE THREAD

**Issue by shacharz** [kaltura/nginx-vod-module#138]
Hi,

I have a configuration under a specific server/location so for instance the index file is:
http://www.pathToVod.com/path/to/origin/file.mp4/index.m3u8

What is the easiest way to switch configurations for end-users and create A/B testing between them.
http://www.pathToVod.com/config1/path/to/origin/file.mp4/index.m3u8
http://www.pathToVod.com/config2/path/to/origin/file.mp4/index.m3u8

but I'm not sure how to config the vod module to drop the /config#/ path from the origin file path.

**Comment by erankor** [comment]
This is currently not supported by nginx-vod itself, but you should be able to accomplish what you want by:
1. use nginx's rewrite directive to map http://www.pathToVod.com/config.../path/to/origin/file.mp4/index.m3u8 to http://www.pathToVod.com/path/to/origin/file.mp4/index.m3u8
2. configure nginx-vod to generate relative URLs in the manifests - vod_hls_absolute_index_urls off

**Comment by shaharmor** [comment]
@erankor, what were trying to do is change the vod_segment_duration dynamically, but it seems that its expecting a hardcoded number in the config.

Any way to make it changeable?

**Comment by shaharmor** [comment]
The issue we're having is that we want to have different routes with different segment durations.

When we use your suggestion of rewriting, the main path (http://www.pathToVod.com/path/to/origin/file.mp4/index.m3u8) is not using the configurations from the rewrite path (http://www.pathToVod.com/config1/path/to/origin/file.mp4/index.m3u8), so it's not helping us.

**Comment by erankor** [comment]
Sorry, this is currently not supported. I may change the module in the future to use nginx's built-in proxy module (proxy_pass) for making HTTP requests, and then this use case will be supported. 
If this is important for you, I can write you a small patch on a side branch that will support what you need, by adding some ugly config parameter like 'upstream_strip_prefix' which will contain the prefix you would like to remove, but it will not be merged to the master.

**Comment by erankor** [comment]
The latest master now builds on proxy_pass for issuing upstream requests, so this should be supported, please let me know if it works for you
