### ISSUE TITLE
Prevent concurrent rendering a segment

### ISSUE THREAD

**Issue by rezakho** [kaltura/nginx-vod-module#1386]
What is the solution for prevent concurrent rendering of a segment with same params

**Comment by erankor** [comment]
The module doesn't cache the segments, so the question is a bit meaningless...
If you are caching the segments outside this module, any locking should be implemented there. If you use nginx for caching, you can use proxy_cache_lock. If you are using a CDN, some CDNs have this capability, often referred to as "origin shielding".

**Comment by rezakho** [comment]
Thanks.
