### ISSUE TITLE
video buffer length

### ISSUE THREAD

**Issue by 0instance** [kaltura/nginx-vod-module#139]
how do I increase number of segments and overall buffer of a video? right now I've set vod_segment_duration to 10000 and it seems new segments always stops being downloaded when there are two segments ahead downloaded. Is there a way to increase number of segments buffer or something like that?

**Comment by erankor** [comment]
The buffer size is determined by the player, the server can not control it, not sure why you want a larger buffer, but you can try increasing the segment duration further, maybe it will help.
In DASH, there is an attribute that the server outputs that defines the minimum buffer time, but not sure all players will obey this value (my guess is that most of them won't). Currently, nginx-vod always outputs the segment duration as the DASH minBufferTime.

**Comment by 0instance** [comment]
Yes, it was exactly like you stated, the problem was with a player. After quick google search found HLSprovider and it was exactly what I needed. Thank you!
