### ISSUE TITLE
HLS encryption how to validate encryption key request.

### ISSUE THREAD

**Issue by rohit267** [kaltura/nginx-vod-module#1395]
How is this not working?

https://github.com/kaltura/nginx-vod-module/issues/713#issuecomment-331907228

I am trying the first method.

The video is not playing, every request is 200.

**Comment by rohit267** [comment]
Nodejs/Express is modifying the response from the vod-moudle. Any solution?

**Comment by erankor** [comment]
Sorry, but there is no info here, I can't guess what you're doing wrong

**Comment by rohit267** [comment]
> Sorry, but there is no info here, I can't guess what you're doing wrong

Was trying one or the methods to mentioned to validate the key and m3u8 file with secure endpoints.

When I was returning the key, express was sending it as text/html which is wrong. It is fixed now.

Anyone who end end up here please use 'request' package from npm to pass the request as it is.
