### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by wang-zhichuang** [kaltura/nginx-vod-module#1396]
Will AGPL affect docker projects that use nginx? Do we want to use Apache License Version 2.0 allowed? Use a method like the following project, which uses the Apache License Version 2.0, is this allowed?

https://github.com/nytimes/nginx-vod-module-docker

**Comment by erankor** [comment]
This repo is AGPL, the fact you use also the nytimes docker (which is Apache 2) doesn't change it - you are still using this code.
