### ISSUE TITLE
Not able to play audio only files

### ISSUE THREAD

**Issue by sridhard** [kaltura/nginx-vod-module#1398]
Hi,
I am trying to play a file which has only audio stream using mapped mode using DASH/HLS. Below is the mapped file:
{
  "sequences": [
  {
    "clips": [
        {
          "type": "source",
          "path": "/home/ubuntu/videos/a.mp4"
        }
    ]
  }
  ]
}

I am getting the below error:
2022/10/29 08:27:47 [error] 21727#0: *35 ngx_http_vod_validate_streams: no matching streams were found, probably invalid segment index while getting mapping, client: 49.37.156.47, server: vod-server, request: "GET /dash/test.json/fragment-1-f1-a1-x3.m4s HTTP/1.1", host: "vodserver.learnyst.com", referrer: "https://shaka-player-demo.appspot.com/"
2022/10/29 08:27:47 [error] 21727#0: *36 ngx_http_vod_validate_streams: no matching streams were found, probably invalid segment index while getting mapping, client: 49.37.156.47, server: vod-server, request: "GET /dash/test.json/fragment-1-f1-v1-x3.m4s HTTP/1.1", host: "vodserver.learnyst.com", referrer: "https://shaka-player-demo.appspot.com/"
2022/10/29 08:27:48 [error] 21727#0: *36 ngx_http_vod_validate_streams: no matching streams were found, probably invalid segment index while getting mapping, client: 49.37.156.47, server: vod-server, request: "GET /dash/test.json/fragment-1-f1-a1-x3.m4s HTTP/1.1", host: "vodserver.learnyst.com", referrer: "https://shaka-player-demo.appspot.com/"
2022/10/29 08:27:49 [error] 21727#0: *36 ngx_http_vod_validate_streams: no matching streams were found, probably invalid segment index while getting mapping, client: 49.37.156.47, server: vod-server, request: "GET /dash/test.json/fragment-1-f1-v1-x3.m4s HTTP/1.1", host: "vodserver.learnyst.com", referrer: "https://shaka-player-demo.appspot.com/"
2022/10/29 08:27:49 [error] 21727#0: *36 media_set_parse_sequences: request has no sequences while getting mapping, client: 49.37.156.47, server: vod-server, request: "GET /dash/test.json/fragment-1-f2-v1-x3.m4s HTTP/1.1", host: "vodserver.learnyst.com", referrer: "https://shaka-player-demo.appspot.com/"
2022/10/29 08:27:51 [error] 21727#0: *35 media_set_parse_sequences: request has no sequences while getting mapping, client: 49.37.156.47, server: vod-server, request: "GET /dash/test.json/fragment-1-f2-v1-x3.m4s HTTP/1.1", host: "vodserver.learnyst.com", referrer: "https://shaka-player-demo.appspot.com/"

**Comment by erankor** [comment]
From this output, I'm guessing is that you edited the json while the server was active, and you still have either some old JSON in cache, or maybe the manifest response returns from cache. I'm saying this because the log has URLs with 'f2' while the JSON has only one sequence. Try restarting the server + clearing all caches (incl browser cache) and try again. Another option is just to use a new file name (e.g. test2.json)

**Comment by sridhard** [comment]
@erankor below are the test results

```javascript
{
  "sequences": [
  {
    "clips": [
        {
          "type": "source",
          "path": "/home/ubuntu/videos/a.mp4"
        }
    ]
  }
  ]
}
```

**Comment by erankor** [comment]
Same as I wrote on the other thread - fragmented MP4 is not supported.

**Comment by sridhard** [comment]
Thanks. It is working
