### ISSUE TITLE
Vary output segment duration

### ISSUE THREAD

**Issue by mlevkov** [kaltura/nginx-vod-module#1399]
@erankor: Is there a way to target segment duration through a remote mode URL style? I understand that such an ability exists in the mapped mode. 

I have several cases where I would like to match the segment size of the surrounding periods when I inject the output of the packager. For example, if I make a GOP of 1 second in duration, I would like to output 4 seconds segments.

**Comment by mlevkov** [comment]
@erankor 

I've implemented a static location to address the need, however, I was wondering if you have a suggestion for a more elegant way of handling such case.

Example:
```nginx
         location ~ ^/hls/(?:[a-z0-9]+)/1/ {
            vod hls;
            vod_segment_duration 1000;
        }

        location ~ ^/hls/(?:[a-z0-9]+)/2/ {
            vod hls;
            vod_segment_duration 2000;
        }

        location ~ ^/hls/(?:[a-z0-9]+)/3/ {
            vod hls;
            vod_segment_duration 3000;
        }

        location ~ ^/hls/(?:[a-z0-9]+)/4/ {
            vod hls;
            vod_segment_duration 4000;
        }

        location ~ ^/hls/(?:[a-z0-9]+)/5/ {
            vod hls;
            vod_segment_duration 5000;
        }

        location ~ ^/hls/(?:[a-z0-9]+)/6/ {
            vod hls;
            vod_segment_duration 6000;
        }
```

**Comment by erankor** [comment]
As you wrote, this is supported for mapped-mode, so you can create a simple location to generate the mapping response, for example -
```
location ~/hls/([1-9])/(.*) {
        if ($remote_addr != '127.0.0.1') {
                return 403;
        }

        return 200 '{"sequences": [{"clips": [{"type": "source", "path": "/mp4base/$2"}]}], "segmentDuration": $1000}';
}
```
This regex allows segment durations between 1-9 sec, but it can be adjusted if you need more than 9 sec.
```
$ curl localhost:8001/hls/4/path/to/mp4
{"sequences": [{"clips": [{"type": "source", "path": "/mp4base/path/to/mp4"}]}], "segmentDuration": 4000}
$ curl localhost:8001/hls/6/path/to/mp4
{"sequences": [{"clips": [{"type": "source", "path": "/mp4base/path/to/mp4"}]}], "segmentDuration": 6000}
```

(Btw, the reason I used `if` is that `allow`/`deny` do not work with rewrite phase directives like `return`)

**Comment by mlevkov** [comment]
@erankor This is indeed a very interesting approach. Thank you so much for sharing the idea.

**Comment by mlevkov** [comment]
@erankor, I was finally able to use this technique. It worked like a charm. Thank you! Welcome to close this ticket.
