### ISSUE TITLE
HLS AV1 support

### ISSUE THREAD

**Issue by rezakho** [kaltura/nginx-vod-module#1408]
Hi
Do you have any plan for hls av1 support?

**Comment by erankor** [comment]
Do you have some player that can play AV1 in HLS?

**Comment by rezakho** [comment]
https://exoplayer.dev/supported-formats.html#sample-formats

**Comment by rezakho** [comment]
Maybe!
No I didn't test it and I can't deploy hls av1 server! 
But there is some info:
https://developers.cloudflare.com/stream/viewing-videos/av1-playback/

'https://customer-wi9sckcs7uxt7lh4.cloudflarestream.com/bb2eaea47dd47e87ecde343451b3e8a1/manifest/video.m3u8?betaCodecSuggestion=av1'

**Comment by erankor** [comment]
Apparently, hls.js can play it... pushed #1413.

**Comment by rezakho** [comment]
Which version will be released this push?

**Comment by erankor** [comment]
Tagged 1.31
