### ISSUE TITLE
WebOS 4.5, SegmentTemplate (without SegmentTimeline)

### ISSUE THREAD

**Issue by mlevkov** [kaltura/nginx-vod-module#1415]
@erankor I've recently gotten to deal with a rather peculiar issue. 
It appears that WebOS 4.5 supports only SegmentTemplate with DASH, not SegmentTimeline. 

Through forced keyframes and exact positioning of keyframes, I can get most of the segments to be the same size on the video part of the Period. However, when it comes to audio, the samples vary, which makes it impossible to collapse to exclude the SegmentTimeline through post-manifest manipulation. 
Is there a way to signal audio samples to stay the same size to make them collapsible, or, if possible, only output in SegmentTemplate without SegmentTimeline?

**Comment by mlevkov** [comment]
I could consider an avenue where each segment represents a short period. However, this approach will significantly increase the size of the manifest. It would be better if somehow I could make audio segments of the same size.

**Comment by erankor** [comment]
You can use `vod_dash_manifest_format segmenttemplate;`, it has no effect the duration of the segments, but the manifest will contain only SegmentTemplate.

**Comment by mlevkov** [comment]
That is interesting. Thank you! I will try.

**Comment by mlevkov-ias** [comment]
I think we are good. Please feel free to close the ticket. @erankor
