### ISSUE TITLE
Atom field parsing performance

### ISSUE THREAD

**Issue by rezakho** [kaltura/nginx-vod-module#1420]
Is moving atom fields to the beginning of the file effective on performance in remote mode?

```
ffmepg -movflags faststart ...
```

**Comment by erankor** [comment]
Using faststart saves 1 read operation while reading the moov atom - with faststart there are 2 reads, without faststart there are 3 reads. If you are using `vod_metadata_cache` and getting a good cache hit ratio, this may be less significant.
