### ISSUE TITLE
Can it not be used in the official nginx environment?

### ISSUE THREAD

**Issue by 0xddy** [kaltura/nginx-vod-module#1426]
Can it not be used in the official nginx environment? Is it necessary to use kaltura-nginx?

**Comment by erankor** [comment]
In the pre-built packages the module is statically linked to nginx, so naturally it can't be used with the official nginx package. However, if you want, you can build the module as a dynamic module, and run it with the official nginx binary using the load_module directive. Note that in this case, you have to build it with the same settings that were used to build the core nginx binary.

**Comment by 0xddy** [comment]
If I use the official nginx, need Thumbnail capture, do I need to install kaltura-fmpg?  @erankor

**Comment by 0xddy** [comment]
nginx cannot recognize ffmpeg

**Comment by 0xddy** [comment]
Nginx 1.22.1 + nginx-vod-module

yum install ffmpeg ffmpeg-devel;


Not  kaltura-nginx
Not kaltura-ffmpeg

**Comment by erankor** [comment]
The check for ffmpeg is here - https://github.com/kaltura/nginx-vod-module/blob/master/config#L147
It tries to compile a c file like -
```
#include <libavcodec/avcodec.h>

int main()
{
    avcodec_send_packet(NULL, NULL);
}
```
With the linker option `-lavcodec`.
You can try to do it manually, and check why it fails.

**Comment by 0xddy** [comment]
I see. Do I need to install ffmpeg ffmpeg-devel before compiling nginx？

@erankor

**Comment by erankor** [comment]
The ffmpeg detection runs as part of nginx's `configure`, so it should be done before that

**Comment by 0xddy** [comment]
@erankor  thinks you ,Problem solved ！  

```
yum install ffmpeg ffmpeg-devel -y

pushd /usr/include
ln -s ffmpeg/libavcodec
ln -s ffmpeg/libavdevice
ln -s ffmpeg/libavfilter
ln -s ffmpeg/libavformat
ln -s ffmpeg/libavresample
ln -s ffmpeg/libavutil
ln -s ffmpeg/libpostproc
ln -s ffmpeg/libswresample
ln -s ffmpeg/libswscale

```
