### ISSUE TITLE
Add support for pre-roll videos to Kaltura VOD module

### ISSUE THREAD

**Issue by mafazely** [kaltura/nginx-vod-module#1437]
I'm using the Kaltura VOD module and it's been working great so far. However, I now have a requirement to add a 5-second video to the beginning of all clips as a pre-roll.

I've looked through the module's documentation and code, but I'm not sure what the best and simplest solution would be. Is it possible to implement this feature in the Kaltura VOD module?

If so, could you provide some guidance on how to approach this? If not, do you have any suggestions for workarounds or alternative solutions?

Thank you for your help!

**Comment by mafazely** [comment]
Hello @erankor ,

I would be grateful for any advice or direction on accomplishing this feature or potentially incorporating it.

Thank you for your time.

**Comment by erankor** [comment]
you can use the 'playlist' feature to concatenate several videos, it's supported only in mapped mode, there's a sample JSON here - https://github.com/kaltura/nginx-vod-module/#playlist

**Comment by mafazely** [comment]
Thanks.
I have another question ...
I have a 5-second ad video,  is that any way not to pass the duration of the main video and just pass the ad duration? Alternatively, can I set a maximum duration value that guarantees all main videos are shorter than this duration? I attempted this approach, but the client periodically requests the last two ts files. Could you provide guidance on how to handle this situation effectively?

**Comment by mlevkov-ias** [comment]
You may want to setup a service that generates these values for you. Effectively, you can call into the packager itself with a url, grab a duration, pass it to the "duration" set, repeat it for all items in the duration list. However, there might be a better way.

**Comment by mafazely** [comment]
Thanks.
It seems that it is time to close the issue.
