### ISSUE TITLE
Unable to compile this with Alpine (Docker)

### ISSUE THREAD

**Issue by francoism90** [kaltura/nginx-vod-module#1442]
```
checking for libavcodec ... found
checking for libswscale ... found
checking for libavfilter ... not found
checking for libxml2 ... found
```
I tried doing this inside my `Dockerfile`:
```
ENV LIB_AV_UTIL=-libavutil
ENV LIB_AV_FILTER=-libavfilter
```
But it doesn't change anything. I have `ffmpeg-dev` installed.

Any help please. :)

**Comment by francoism90** [comment]
I think this happens because `ffmpeg-dev` is 6.0, what version is required, 4.0?

**Comment by erankor** [comment]
#1451 will probably fix this one too.
But ffmpeg 6 wasn't tested, we are using 4.

**Comment by francoism90** [comment]
@erankor Thanks, I've switched to `ffmpeg4`, and it indeed now uses `libavfilter`.
