### ISSUE TITLE
Thumbs support for av1 codec?

### ISSUE THREAD

**Issue by flashick** [kaltura/nginx-vod-module#1458]
Hello!

When I try to get thumbs from av1 video (from https://test-videos.co.uk/sintel/mp4-av1) I get 400 Bad request and  this error in logs:

`ngx_http_vod_validate_streams: no matching streams were found while reading media header`

At the same time, the video plays normally

Is there thumbs support for this codec?

**Comment by erankor** [comment]
Hi, please try this PR - #1461
This PR adds the required codec mapping, but naturally it requires AV1 decoding support in ffmpeg. I'm testing on a fairly old platform, so it's a bit of a mess to build it there... but if it works for you, I'll merge it.

**Comment by flashick** [comment]
> Hi, please try this PR - #1461 This PR adds the required codec mapping, but naturally it requires AV1 decoding support in ffmpeg. I'm testing on a fairly old platform, so it's a bit of a mess to build it there... but if it works for you, I'll merge it.

Yep! It works! Thank you!

For those who will google it:
you need to build ffmpeg with libaom support and then build vod module with that ffmpeg. Without it you will get 400 error without any information in error.log

**Comment by erankor** [comment]
thanks, merged
