### ISSUE TITLE
how to apply Subtitles language on multiurl remote mode if the video directonery location and subtitle are different

### ISSUE THREAD

**Issue by feralsja** [kaltura/nginx-vod-module#1475]
I've been looking for it for a few days but haven't found the reference yet.
 I have the video in folder

kutavideo
Vid720p.mp4
Vid480p.mp4

and the subtitles are at 
kutavideo/sub/
en.srt
may.srt

@erankor

can you give me an example of its application in remote mode some urls

Thank you

**Comment by erankor** [comment]
If you want to use multi-urls (=not mapping JSON), it would be something like -
`http://yourserver/location/kutavideo/,Vid720p.mp4,Vid480p.mp4,lang/eng/sub/en.srt,lang/may/sub/may.srt,.urlset/master.m3u8`

**Comment by feralsja** [comment]
Yey it works thanks
