### ISSUE TITLE
Token validate and mode mapped and remote minIO notworking, return 403

### ISSUE THREAD

**Issue by hataiit9x** [kaltura/nginx-vod-module#1485]
Please help me 
I config nginx.conf
```
worker_processes auto;
worker_rlimit_nofile 8192;

events {
    worker_connections 4096;
}

http {
    upstream jsonupstream {
        server 10.0.0.2:9000;
    }
    server {
        listen 80;

        # vod mode
        vod_mode mapped;
	vod_upstream_location /json;
        vod_remote_upstream_location /proxy;

        # vod caches
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;
        vod_mapping_cache mapping_cache 5m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        # file handle caching
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
		
		location ^~ /json/video/ {
            internal;
            proxy_pass http://jsonupstream/public/;
            proxy_set_header Host $http_host;
        }
		
	location ~ /proxy/([^/]+)/(.*) {
            internal;
            proxy_pass $1://$2;
            resolver 8.8.8.8;
        }

        location ^~ /video/ {
            alias /etc/nginx/json/;
            vod hls;

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
    }
}
```

and json content

`{
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/http/10.0.0.2:9000/public/transformers_720p.mp4"
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/http/10.0.0.2:9000/public/transformers_360p.mp4"
                }
            ]
        }
    ]
}`

And URL request from VLC
`http://IP/video/transformers.json/master.m3u8?token=exp=1698832554~acl=/*~hmac=aa79d602d727fac049a5c61b65b88ca4165fdd5c63beb37625758685be466a78`

And Error

`[error] 175394#175394: *62 ngx_child_request_wev_handler: upstream returned a bad status 403 while sending to client, client: 172.71.210.156, server: , request: "GET /video/transformers.json/master.m3u8?token=exp=1698832554~acl=/*~hmac=aa79d602d727fac049a5c61b65b88ca4165fdd5c63beb37625758685be466a78 HTTP/1.1", host: ""`

Please help me right config, thank so much

**Comment by erankor** [comment]
This error means that either the request for the JSON or the request for the MP4, returned a 403 error. Since you are using HTTP (not HTTPS), I think the easiest way to debug it is to capture the traffic with tcpdump. You should be able to see the failed request there, and reproduce the error / find what is wrong in the request.

**Comment by erankor** [comment]
Sorry, I can't understand what you wrote... but in general, the key that is returned to nginx-vod-module in the DRM JSON, must be the same key that is embedded in the license response that you return from the DRM server to the player.
