### ISSUE TITLE
Hello Dear,

### ISSUE THREAD

**Issue by Rezhann112** [kaltura/nginx-vod-module#1487]

**Comment by Rezhann112** [comment]
am using for MP4 to HLS , but the issue i have Srt file it was not working here my url 
http://10.0.70.100:8080/hls/,devito720p.mp4,lang/en/devito.en_US.srt,.urlset/master.m3u8
it will play the stream without any error but it will not showing srt , would please share with me mapping mode for json alos , thank you

**Comment by Rezhann112** [comment]
hello i found the issue and i fixed now its working 
http://10.0.70.100:8080/hls/,swan.mp4,swan1.srt,.urlset/master.m3u8
but i have one more issue which is hls auto convert srt to webvtt segment , is there any way to keep format as srt ?

thank you

**Comment by erankor** [comment]
According to the HLS specification, the only 2 supported formats for subtitles are WebVTT and IMSC.
SRT is not supported by HLS.

**Comment by Rezhann112** [comment]
Dear @erankor , thank you very much , but for me now the output format is webvtt how can i change to imsc please ?

**Comment by Rezhann112** [comment]
worker_processes  auto;

events {
	use epoll;
}

http {
	log_format  main  '$remote_addr $remote_user [$time_local] "$request" '
		'$status "$http_referer" "$http_user_agent"';

	access_log  /dev/stdout  main;
	error_log   stderr debug;

	default_type  application/octet-stream;
	include       /usr/local/nginx/conf/mime.types;

	sendfile    on;
	tcp_nopush  on;
	tcp_nodelay on;

	vod_mode                           local;
        vod_metadata_cache                 metadata_cache 512m;
        vod_response_cache                 response_cache 128m;
	vod_last_modified_types            *;
	vod_segment_duration               9000;
	vod_align_segments_to_key_frames   on;
	vod_dash_fragment_file_name_prefix "segment";
	vod_hls_segment_file_name_prefix   "segment";

        gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

	open_file_cache          max=1000 inactive=5m;
	open_file_cache_valid    2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors   on;

	aio on;

	server {
		listen 80;
		server_name localhost;
		root /opt/static;

		location ~ ^/videos/.+$ {
			autoindex on;
		}

		location /hls/ {
			vod hls;
			alias /opt/static/videos/;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Allow-Origin '*';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		}

		location /thumb/ {
			vod thumb;
			alias /opt/static/videos/;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Allow-Origin '*';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		}

		location /dash/ {
			vod dash;
			alias /opt/static/videos/;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Allow-Origin '*';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		}
	}
}

**Comment by Rezhann112** [comment]
i have changed configuration NGNIX , still the output is vtt for the subtitle 
here the configuration for the nginx , would you please tell me where was the issue ? and how can i control output to switching vtt to imsc please ? Thanks 





worker_processes  auto;

events {
	use epoll;
}

http {
	log_format  main  '$remote_addr $remote_user [$time_local] "$request" '
		'$status "$http_referer" "$http_user_agent"';

	access_log  /dev/stdout  main;
	error_log   stderr debug;

	default_type  application/octet-stream;
	include       /usr/local/nginx/conf/mime.types;

	sendfile    on;
	tcp_nopush  on;
	tcp_nodelay on;

	vod_mode                           local;
	vod_metadata_cache                 metadata_cache 16m;
	vod_response_cache                 response_cache 512m;
	vod_last_modified_types            *;
	

        gzip on;
        gzip_types application/vnd.apple.mpegurl;

	open_file_cache          max=1000 inactive=5m;
	open_file_cache_valid    2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors   on;

	aio on;

	server {
		listen 80;
		server_name localhost;
		root /opt/static;

		location ~ ^/videos/.+$ {
			autoindex on;
		}

		location /hls/ {
			vod hls;
			alias /opt/static/videos/;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Allow-Origin '*';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		}

		location /thumb/ {
			vod thumb;
			alias /opt/static/videos/;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Allow-Origin '*';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		}

		location /dash/ {
			vod dash;
			alias /opt/static/videos/;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Allow-Origin '*';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		}
	}
}

**Comment by Rezhann112** [comment]
i have test the dash is working with TTML , but for the HLS do you have any idea how can i change Webvtt to IMSO or TTML? i mean master.m3u8 thank you .

**Comment by Rezhann112** [comment]
mime.types
types {
    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    application/javascript                js;
    application/atom+xml                  atom;
    application/rss+xml                   rss;

    text/mathml                           mml;
    text/plain                            txt;
    text/vnd.sun.j2me.app-descriptor      jad;
    text/vnd.wap.wml                      wml;
    text/x-component                      htc;

    image/png                             png;
    image/tiff                            tif tiff;
    image/vnd.wap.wbmp                    wbmp;
    image/x-icon                          ico;
    image/x-jng                           jng;
    image/x-ms-bmp                        bmp;
    image/svg+xml                         svg svgz;
    image/webp                            webp;

    application/font-woff                 woff;
    application/java-archive              jar war ear;
    application/json                      json;
    application/mac-binhex40              hqx;
    application/msword                    doc;
    application/pdf                       pdf;
    application/postscript                ps eps ai;
    application/rtf                       rtf;
    application/vnd.apple.mpegurl         m3u8;
    application/vnd.ims.imsccv1p1         imscc;
    application/vnd.ms-excel              xls;
    application/vnd.ms-fontobject         eot;
    application/vnd.ms-powerpoint         ppt;
    application/vnd.wap.wmlc              wmlc;
    application/vnd.google-earth.kml+xml  kml;
    application/vnd.google-earth.kmz      kmz;
    application/x-7z-compressed           7z;
    application/x-cocoa                   cco;
    application/x-java-archive-diff       jardiff;
    application/x-java-jnlp-file          jnlp;
    application/x-makeself                run;
    application/x-perl                    pl pm;
    application/x-pilot                   prc pdb;
    application/x-rar-compressed          rar;
    application/x-redhat-package-manager  rpm;
    application/x-sea                     sea;
    application/x-shockwave-flash         swf;
    application/x-stuffit                 sit;
    application/x-tcl                     tcl tk;
    application/x-x509-ca-cert            der pem crt;
    application/x-xpinstall               xpi;
    application/xhtml+xml                 xhtml;
    application/xspf+xml                  xspf;
    application/zip                       zip;

    application/octet-stream              bin exe dll;
    application/octet-stream              deb;
    application/octet-stream              dmg;
    application/octet-stream              iso img;
    application/octet-stream              msi msp msm;

    application/vnd.openxmlformats-officedocument.wordprocessingml.document    docx;
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet          xlsx;
    application/vnd.openxmlformats-officedocument.presentationml.presentation  pptx;

    audio/midi                            mid midi kar;
    audio/mpeg                            mp3;
    audio/ogg                             ogg;
    audio/x-m4a                           m4a;
    audio/x-realaudio                     ra;

    video/3gpp                            3gpp 3gp;
    video/mp2t                            ts;
    video/mp4                             mp4;
    video/mpeg                            mpeg mpg;
    video/quicktime                       mov;
    video/webm                            webm;
    video/x-flv                           flv;
    video/x-m4v                           m4v;
    video/x-mng                           mng;
    video/x-ms-asf                        asx asf;
    video/x-ms-wmv                        wmv;
    video/x-msvideo                       avi;
}

**Comment by Rezhann112** [comment]
after 5 days to find out vtt segment change to IMSC there is no luck i hope find a way to change vtt segment.

**Comment by erankor** [comment]
Sorry, it seems you misunderstood what I wrote - I didn't say this module supports IMSC, I said that according to HLS spec, the only 2 options are WebVTT & IMSC, hence SRT is not an option for HLS streaming. 
This module supports only WebVTT in HLS, it is clearly stated in the beginning of the readme -
```
Output:

DASH - either a single WebVTT or SMPTE-TT segments (configurable)
HLS - segmented WebVTT (m3u8)
```
I have implemented support for IMSC in our live packager - https://github.com/kaltura/media-framework/tree/master/nginx-pckg-module#pckg_m3u8_subtitle_format, but not here...
Why can't you use WebVTT?

**Comment by Rezhann112** [comment]
There is no issue , but TTML is the package you can use for DVB , Zapper box to be read , closer caption is used for the WebVTT , that why i want to check it , by the way everything was great and very nice , and the system is very stable , 

one more think with Nginx configuration package can i crate pool for transcoding ABR ? 

That module is free to use but its very powerfull than the payment modules <3.

**Comment by Rezhann112** [comment]
sorry again am back to you , is there any way to change the font size , or background that its black to be no color ?

**Comment by Rezhann112** [comment]
Hi @erankor , sorry to bother you , is there any way to remove black subtitle background?
how can i edit without reinstalling please ?

**Comment by erankor** [comment]
Hi, this module does not alter the styles of the subtitles.
But, if you use WebVTT for both input & output, the styles will just pass through, so you can control the styles on the input WebVTT file.

**Comment by erankor** [comment]
SRT is not a "well defined" format, there is no specification of the possible styles you can apply. Some decoders support basic stuff like bold/underline/italics, some do not even support that. 
If you add WebVTT styles to your SRT file, it may actually work though, because the module uses a shared code to handle SRT & WebVTT (other than styles, the differences are minor). 
Anyway, I think the best way is to try it out end2end with the specific player you are using. For example, I remember Apple players did not support WebVTT text color styles, not sure if this was fixed already or not...

**Comment by Rezhann112** [comment]
@erankor again sorry am back to closedCaptions its only working with mapping mode ?
is there anything you can add to urlset ?

thank you.

**Comment by erankor** [comment]
Yes, if you are referring to `EXT-X-MEDIA` with `TYPE=CLOSED-CAPTIONS`, it's only supported in mapped mode.

**Comment by Rezhann112** [comment]
thank you very much, I appreciate your answer.

**Comment by Rezhann112** [comment]
Hi Dear @erankor ,
is there any way to change subtitle to be showing as arabic not change to

**Comment by Rezhann112** [comment]
Hi dear Bro @erankor ,
thank you i have fixed with language_x.h edit from there , thanks a lot.
