### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by regenun** [kaltura/nginx-vod-module#149]
Hello!
How does it work?
I installed it, but how i can run it?
my videos in /tmp/movie
http://85.25.41.41/

Best Regards,
Kirill

**Comment by erankor** [comment]
I would suggest the following - first set it up so that nginx just serves the MP4 files. This is generic nginx configuration, unrelated to nginx-vod-module, and you can probably find all sorts of tutorials for that on the Internet.
Once you have that configured, add to the location that serves the files in nginx.conf the directive: vod hls; (assuming you want HLS) and that should get you started.

**Comment by soufrk** [comment]
On "first set it up so that nginx just serves the MP4 files", I would like to ask you, is the the following configuration sufficient
-------------------------------------------------------------------------------------------------------------------------------
# VOD Module Configurations
        location /content {
            vod hls;
            vod_mode local;
            vod_moov_cache moov_cache 512m;

            root /var;

            #gzip on;
            #gzip_types application/vnd.apple.mpegur$
        }
-------------------------------------------------------------------------------------------------------------------------------
for streaming files from a location /var/content ?

**Comment by erankor** [comment]
yes, looks ok for getting started, there are other settings that are recommended, but not a must (e.g. setting caching headers if you are using a CDN, enabling compression on manifest requests, etc.)

**Comment by soufrk** [comment]
In continuation to previous post, tried lots of permutations & combinations. Still HTTP 400 is what is being returned. Can you help me diagnose what might be the issue?

**Comment by erankor** [comment]
The URL should be something like localhost/content/test.mp4/index.m3u8

**Comment by soufrk** [comment]
YOU ARE GOD !!! Works like a  charm !!

**Comment by erankor** [comment]
Don't know about god, maybe just an angel ;-)
Anyway, glad to hear it works.

**Comment by soufrk** [comment]
How to configure for DASH? I couldn't find any sample configuration.

**Comment by erankor** [comment]
Here is the default configuration we use:
```
	location ~ ^/dash/p/\d+/(sp/\d+/)?serveFlavor/ {
		vod dash;
		vod_segment_duration 4000;
		vod_align_segments_to_key_frames on;
		vod_dash_manifest_format segmenttemplate;
		
		vod_last_modified_types *;
		more_set_headers 'Access-Control-Allow-Headers: origin,range,accept-encoding,referer';
		more_set_headers 'Access-Control-Expose-Headers: Server,range,Content-Length,Content-Range';
		more_set_headers 'Access-Control-Allow-Methods: GET, HEAD, OPTIONS';
		more_set_headers 'Access-Control-Allow-Origin: *';
		expires 100d;
	}
```

**Comment by soufrk** [comment]
And we access it in similar way as that of HLS, right?
http://mydomain/_whatever-dash-location_/sample.mp4/manifest.mpd

**Comment by erankor** [comment]
correct

**Comment by soufrk** [comment]
DASH streaming seems to be not working...
Below is the configuration,
```
# VOD Module DASH Configurations
    location /dash{
	    vod dash;
	    vod_segment_duration 4000;
	    vod_align_segments_to_key_frames on;
	    vod_dash_manifest_format segmenttemplate;
	    root /var;
	    vod_last_modified_types *;
	    #more_set_headers 'Access-Control-Allow-Headers: origin,range,accept-encoding,referer';
	    #more_set_headers 'Access-Control-Expose-Headers: Server,range,Content-Length,Content-Range';
	    #more_set_headers 'Access-Control-Allow-Methods: GET, HEAD, OPTIONS';
	    #more_set_headers 'Access-Control-Allow-Origin: *';
	    expires 1d;
	}
```

Again, assuming there is a file ```/var/dash/test.mp4```
I request ```http://mydomain/dash/test.mp4/manifest.mpd```
I am using this player (http://dash-mse-test.appspot.com/dash-player.html)
But, the player is failing to load the content.
Any suggestions ?

**Comment by erankor** [comment]
you commented out all the set headers from the sample I sent you, so how can it work ?
if you don't have the nginx headers more plugin, you can use the builtin add_header, but anyway, without these CORS headers it won't be possible to load these resources from JavaScript

**Comment by soufrk** [comment]
The headers were producing the following error,
```unknown directive "more_set_headers"```
How to resolve it?

**Comment by erankor** [comment]
Yes, either add the nginx headers more plugin or change the conf to add_header

**Comment by soufrk** [comment]
OK, I made correction. Below is the corrected configuration.
```
# VOD Module DASH Configurations
	location /dash{
	    vod dash;
	    vod_segment_duration 4000;
	    vod_align_segments_to_key_frames on;
	    vod_dash_manifest_format segmenttemplate;
	    root /var;

	    vod_last_modified_types *;
	    add_header Access-Control-Allow-Headers "origin,range,accept-encoding,referer";
	    add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
	    add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
	    add_header Access-Control-Allow-Origin "*";
	    expires 1d;
	}
```
Now, the player is giving some other error (Ubuntu/Firefox)
```
616: EME not detected.
617: Media Source not found!
617: MSE not detected.
617: Required features not detected, aborting.
```
However the error is different on Windows/Chrome
```
20: DASH MSE/EME demo version 0.2-207-g3fb234e
20: -------- Initializing --------
21: 1, XHR for manifest sent
94: 2, Manifest received
131: 3, onSourceOpen()
634: Ending stream
635: Error (4)
1133: 2, Deregistering progress timer
```
Any guess to what is going wrong ?

**Comment by erankor** [comment]
try this player on Windows Chrome - http://dashif.org/reference/players/javascript/v1.5.1/samples/dash-if-reference-player/index.html
If that doesn't work, send a link to the video

**Comment by soufrk** [comment]
Yes, it is working in the browser you mentioned, but there is no audio. Below, is the link for the source file
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_60fps_normal.mp4

**Comment by erankor** [comment]
This file has 2 audio tracks - one is MP3, the other is AC-3, neither are supported, as written here https://github.com/kaltura/nginx-vod-module/#limitations

**Comment by dhalturin** [comment]
Hello, you can help me?

I generated m3u8 playlist and *.ts segments files:
`[00:41:40] {root@milena}/home/storage/video/hls/test> ls -lah
total 968K
drwxr-xr-x 2 www-data www-data 4.0K Mar 16 00:38 .
drwxr-xr-x 3 www-data www-data 4.0K Mar 16 00:34 ..
-rw-r--r-- 1 www-data www-data 147K Mar 16 00:38 00000.ts
-rw-r--r-- 1 www-data www-data 111K Mar 16 00:38 00001.ts
-rw-r--r-- 1 www-data www-data  80K Mar 16 00:38 00002.ts
-rw-r--r-- 1 www-data www-data  92K Mar 16 00:38 00003.ts
-rw-r--r-- 1 www-data www-data  27K Mar 16 00:38 00004.ts
-rw-r--r-- 1 www-data www-data  49K Mar 16 00:38 00005.ts
-rw-r--r-- 1 www-data www-data  38K Mar 16 00:38 00006.ts
-rw-r--r-- 1 www-data www-data  53K Mar 16 00:38 00007.ts
-rw-r--r-- 1 www-data www-data  49K Mar 16 00:38 00008.ts
-rw-r--r-- 1 www-data www-data  37K Mar 16 00:38 00009.ts
-rw-r--r-- 1 www-data www-data  43K Mar 16 00:38 00010.ts
-rw-r--r-- 1 www-data www-data  61K Mar 16 00:38 00011.ts
-rw-r--r-- 1 www-data www-data  36K Mar 16 00:38 00012.ts
-rw-r--r-- 1 www-data www-data  36K Mar 16 00:38 00013.ts
-rw-r--r-- 1 www-data www-data  75K Mar 16 00:38 00014.ts
-rw-r--r-- 1 www-data www-data  513 Mar 16 00:38 97fa8388b4.1080.m3u8`

And configure nginx location:
`    location /hls/test {
        root /home/storage/video;
        autoindex on;
        vod hls;
        vod_mode local;
        vod_bootstrap_segment_durations 2000;
        vod_bootstrap_segment_durations 2000;
        vod_bootstrap_segment_durations 2000;
        vod_bootstrap_segment_durations 4000;

        add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
        add_header Access-Control-Allow-Origin "*";
        expires 100d;
    }`

But code of my request - 400:
`curl -sI 'https://*****.ru/hls/test/97fa8388b4.1080.m3u8'
HTTP/1.1 400 Bad Request
Server: nginx
Date: Wed, 15 Mar 2017 21:43:26 GMT
Content-Type: text/html; charset=utf-8
Connection: close`

Output error log:
`[00:44:32] {root@milena}/etc/nginx> tail -n1 /var/log/nginx/****.ru.error.log
2017/03/16 00:43:26 [error] 7759#7759: *6970 ngx_http_vod_hls_parse_uri_file_name: unidentified m3u8 request, client: 10.0.0.209, server: ****.ru, request: "HEAD /hls/test/97fa8388b4.1080.m3u8 HTTP/1.1", host: "****.ru"`

What am i doing wrong?
