### ISSUE TITLE
Support for multiple m3u8 for multiple video codecs

### ISSUE THREAD

**Issue by aminvakil** [kaltura/nginx-vod-module#1494]
Let's say I have multiple codecs (av1 and h264) of a movie and I want to have multiple indexes the only thing different in them are video codec of them.

I checked this json:
```
{
    "sequences": [
        {
            "clips": [
                {
                    "path": "/usr/share/nginx/html/audiotest/shape_h264.mp4",
                    "type": "source",
                    "label": "avc1"
                }
            ],
            "clips": [
                {
                    "path": "/usr/share/nginx/html/audiotest/shape_av1.webm",
                    "type": "source",
                    "label": "av1"
                }
            ]
        }
    ]
}
```

And it always result of a single m3u8 which is the latest movie in list.

I guess something like https://github.com/kaltura/nginx-vod-module/pull/603 has to be done, right?

**Comment by aminvakil** [comment]
```
{
    "sequences": [
        {
            "clips": [
                {
                    "path": "/usr/share/nginx/html/audiotest/shape_h264.mp4",
                    "type": "source"
                }
            ],
            "clips": [
                {
                    "path": "/usr/share/nginx/html/audiotest/shape_av1.webm",
                    "type": "source"
                }
            ]
        }
    ]
}
```
results in:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1056373,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="av01.0.08M.08,mp4a.40.2"
index-v1-a1.m3u8
```
```
{
    "sequences": [
        {
            "clips": [
                {
                    "path": "/usr/share/nginx/html/audiotest/shape_av1.webm",
                    "type": "source"
                }
            ],
            "clips": [
                {
                    "path": "/usr/share/nginx/html/audiotest/shape_h264.mp4",
                    "type": "source"
                }
            ]
        }
    ]
}
```
results in:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2431977,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2",VIDEO-RANGE=SDR
index-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=37779,RESOLUTION=1920x1080,CODECS="avc1.640028",URI="iframes-v1-a1.m3u8",VIDEO-RANGE=SDR
```


I've also changed nginx-vod-module and compiled it:
```
diff --git a/ngx_http_vod_module.c b/ngx_http_vod_module.c
index 44ab3db..03adabd 100644
--- a/ngx_http_vod_module.c
+++ b/ngx_http_vod_module.c
@@ -250,7 +250,7 @@ static ngx_str_t empty_string = ngx_null_string;
 
 static media_format_t* media_formats[] = {
        &mp4_format,
-       // XXXXX add &mkv_format,
+       &mkv_format,
        &webvtt_format,
 #if (NGX_HAVE_LIBXML2)
        &dfxp_format,
```

**Comment by erankor** [comment]
I tested on my server, and I'm getting the expected result (=with both codecs). 
I used "multi-url" instead of JSON because it was easier to test, but it shouldn't make a difference -
```
$ curl localhost:8001/local/hls/content/,x,av1-2,.mp4.urlset/master.m3u8
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=807085,RESOLUTION=720x480,FRAME-RATE=24.000,CODECS="avc1.4d401e,mp4a.40.2"
index-f1-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=212819,RESOLUTION=960x540,FRAME-RATE=25.000,CODECS="av01.0.04M.08,mp4a.40.2"
index-f2-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=82778,RESOLUTION=720x480,CODECS="avc1.4d401e",URI="iframes-f1-v1-a1.m3u8"
```
Any chance you are requesting `master-f1.m3u8` or something, instead of `master.m3u8`? because that could explain what you wrote...

**Comment by aminvakil** [comment]
> Any chance you are requesting `master-f1.m3u8` or something, instead of `master.m3u8`? because that could explain what you wrote...

No, I'm not. What video are you trying with, I'm suspecting my video and conversion is wrong.

**Comment by erankor** [comment]
just a couple of test videos that I have... but if each one of the files works for you separately, it means the videos are fine. 
a bit of long shot, but maybe try to repackage the av1 into mp4 using ffmpeg?

**Comment by aminvakil** [comment]
> just a couple of test videos that I have... but if each one of the files works for you separately, it means the videos are fine. a bit of long shot, but maybe try to repackage the av1 into mp4 using ffmpeg?

It didn't make a difference.

I used this command to convert `ffmpeg -i shape_av1.webm shape_av1.mp4`, changed the json and restarted nginx.

**Comment by aminvakil** [comment]
Ah, something is wrong with my command, its codec has been changed to h264, I guess I should run ffmpeg differently.

**Comment by aminvakil** [comment]
I'm just pasting all the process here to see if there is something wrong
`ffmpeg -i shape_av1.webm -c:v libaom-av1 shape_av1.mp4`
failed with this:
```
[libaom-av1 @ 0x556928d1a480] The encoder 'libaom-av1' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
```
I'm now running ffmpeg with this command:
`ffmpeg -i shape_av1.webm -c:v libaom-av1 -strict -2 shape_av1.mp4`

FYI output of `ffmpeg -version` is this:
```
ffmpeg version 4.1.11-0+deb10u1 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100
```

**Comment by aminvakil** [comment]
The command is taking too long, I've also tried on ffmpeg 6 and it's faster, but still too slow.

But I've tried `cp shape_av1.webm shape_av1.mp4` and ffprobe returns 0 on it with correct codecs and everything, results are the same.

**Comment by aminvakil** [comment]
> I tested on my server, and I'm getting the expected result (=with both codecs). I used "multi-url" instead of JSON because it was easier to test, but it shouldn't make a difference -
> 
> ```
> $ curl localhost:8001/local/hls/content/,x,av1-2,.mp4.urlset/master.m3u8
> #EXTM3U
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=807085,RESOLUTION=720x480,FRAME-RATE=24.000,CODECS="avc1.4d401e,mp4a.40.2"
> index-f1-v1-a1.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=212819,RESOLUTION=960x540,FRAME-RATE=25.000,CODECS="av01.0.04M.08,mp4a.40.2"
> index-f2-v1-a1.m3u8
> 
> #EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=82778,RESOLUTION=720x480,CODECS="avc1.4d401e",URI="iframes-f1-v1-a1.m3u8"
> ```
> 
> Any chance you are requesting `master-f1.m3u8` or something, instead of `master.m3u8`? because that could explain what you wrote...

I just saw your tests are with different resolutions! My videos are the same resolution, both 1920x1080.

**Comment by erankor** [comment]
1. changing the file extension has no impact, the format is still MKV
2. you can change the container without retranscode by using `-c:v copy` in the ffmpeg command line, this should complete very fast.
3. having identical/different resolutions shouldn't matter - in HLS the module doesn't perform track deduplication. in DASH there is deduplication logic, but tracks with different codecs are considered different - https://github.com/kaltura/nginx-vod-module/blob/master/vod/dash/dash_packager.c#L317.

**Comment by aminvakil** [comment]
>     2. you can change the container without retranscode by using `-c:v copy` in the ffmpeg command line, this should complete very fast.

This didn't produce any difference as well. Still only the latest file in json.

**Comment by erankor** [comment]
Can you send me links to the 2 MP4s that you are now testing with? I want to try to reproduce on my side, I don't understand how you're getting this behavior...

**Comment by aminvakil** [comment]
I have downloaded this video: https://www.youtube.com/watch?v=Lqf406eSorw

**Comment by erankor** [comment]
I'm sorry, but don't really have the time to start playing with youtube downloaders... 
If you can send me links to the 2 MP4s, I can check it out.

**Comment by erankor** [comment]
I downloaded the files now, in order to reproduce the issue on my side, and after downloading the JSON, I noticed your problem :)
You have two `clips` keys under a single sequence object - the JSON is invalid.
You need to have 2 sequence objects, each one with its own `clips` property, as in the sample here - https://github.com/kaltura/nginx-vod-module/?tab=readme-ov-file#adaptive-set

**Comment by aminvakil** [comment]
Oops, sorry to take your time for this nonsense, it works perfectly now, for later users working json is:
```
{
    "sequences": [
        {
            "clips": [
                {
                    "path": "/usr/share/nginx/html/audiotest/shape_av1.mp4",
                    "type": "source"
                }
            ]
        },
        {
            "clips": [
                {
                    "path": "/usr/share/nginx/html/audiotest/shape_h264.mp4",
                    "type": "source"
                }
            ]
        }
    ]
}
```
