### ISSUE TITLE
different DRM encryption keys for different videos under HLS

### ISSUE THREAD

**Issue by Wooyulin** [kaltura/nginx-vod-module#1501]
I am trying to implement different DRM encryption keys for different videos under HLS. The configuration appears to work initially, and the m3u8 retrieval is successful. However, I observe that for each new m4s segment, there is an additional request made to /encodekeya/public/video/encodeKey. Notably, during these subsequent requests, the ticket is not included
my configuration
```
location /vod_back {
                        vod hls;
                        #vod dash;
                        #vod_mode local;
                        vod_mode remote;
                        vod_segment_duration 8000;
                        vod_align_segments_to_key_frames on;
                        vod_hls_container_format fmp4;
                        vod_hls_force_unmuxed_segments on;
                        vod_hls_absolute_index_urls off;
                        vod_hls_output_iframes_playlist off;
                        vod_manifest_segment_durations_mode accurate;
#                       vod_multi_uri_suffix .mp4;
                        include conf.d/options.conf;
                        add_header 'Access-Control-Allow-Origin' '*';
                        add_header 'Access-Control-Allow-Credentials' 'true';

                        #vod_metadata_cache metadata_cache 1024m;
                        #vod_response_cache response_cache 128m;
                        #vod_cache_buffer_size 512k;
                        #vod_mapping_cache mapping_cache 5m;
                        vod_hls_encryption_method aes-128; # 加密算法
                        vod_drm_enabled on; # 使用drm方式提供key
                        vod_drm_upstream_location  /encodekeya; # 上游服务器地址
                        vod_drm_request_uri /public/video/encodeKey?$ticket=$arg_ticket;
                        vod_hls_encryption_key_uri http://localhost/public/video/decodeKey?ticket=$arg_ticket;
                        #alias /usr/local/openresty/nginx/QP_HLS/;
                        vod_upstream_location /newgroup;

                        #open_file_cache          max=2000 inactive=10m;
                        #open_file_cache_valid    4m;
                        #open_file_cache_min_uses 1;
                        #open_file_cache_errors   on;
                        aio on;
                       # drm
                }```


eg:
get: https:///vod_back/group1/M00/01/E0/wKgl4GWJLBiAA_8JH3ylxlOanG8055.mp4/index.m3u8?ticket=oooticket
``` sh
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://localhost/public/video/decodeKeyticket=ooticket",IV=0x58E91179DA55B68354E36A1E93B31EB5
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-MAP:URI="init-v1-a1.mp4"
#EXTINF:8.100,
seg-1-v1-a1.m4s
#EXTINF:9.500,
seg-2-v1-a1.m4s
#EXTINF:10.000,
seg-3-v1-a1.m4s
#EXTINF:6.067,
seg-4-v1-a1.m4s
#EXTINF:10.033,
seg-5-v1-a1.m4s
#EXTINF:6.067,
seg-6-v1-a1.m4s
#EXTINF:8.000,
seg-7-v1-a1.m4s
#EXTINF:10.000,
seg-8-v1-a1.m4s
```
I have checked the documentation, but I'm unsure how to configure m4s to include parameters to achieve my desired effect. If that's not possible, I need to consider how to extract the ticket from the URL using Nginx.
thank

**Comment by erankor** [comment]
There are several options to solve this -
1. Use our [nginx-secure-token-module](https://github.com/kaltura/nginx-secure-token-module) to add the query arg to the returned segment URLs. This module was initially developed to embed CDN tokens in returned URLs, but it can add any query argument...
2. Move the parameter to the URL path - since you are using relative URLs, the parameter will just propagate by the player to the segments. You can then extract it to a variable using an nginx regex location.

If you are using a CDN/some other caching solution, you should consider the effect it may have on caching. For example, if query parameters are not included in the cache-key, and someone sends a bad ticket, it may corrupt the cache for other users.
Other than that, I'd recommend using vod_drm_info_cache, there's no reason to have the module request the key for every segment. But you need to solve the ticket propagation either way... do not assume that the key is already in cache.

**Comment by Wooyulin** [comment]
> There are several options to solve this -
> 
> 1. Use our [nginx-secure-token-module](https://github.com/kaltura/nginx-secure-token-module) to add the query arg to the returned segment URLs. This module was initially developed to embed CDN tokens in returned URLs, but it can add any query argument...
> 2. Move the parameter to the URL path - since you are using relative URLs, the parameter will just propagate by the player to the segments. You can then extract it to a variable using an nginx regex location.
> 
> If you are using a CDN/some other caching solution, you should consider the effect it may have on caching. For example, if query parameters are not included in the cache-key, and someone sends a bad ticket, it may corrupt the cache for other users. Other than that, I'd recommend using vod_drm_info_cache, there's no reason to have the module request the key for every segment. But you need to solve the ticket propagation either way... do not assume that the key is already in cache.

thank for help
