### ISSUE TITLE
Does the nginx-vod-module support ClearKey with an external key server for HLS and DASH?

### ISSUE THREAD

**Issue by nonth** [kaltura/nginx-vod-module#1507]
I am currently able to set up the nginx-vod-module to use HLS ClearKey by configuring the vod_secret_key and vod_hls_encryption_method as aes-128. but in production I'll have separate key server to store key and iv to encryption video.

Now, my questions are:
1. How do I set up the nginx-vod-module to use keys and initialization vectors (IV) from an external key server for ClearKey encryption in HLS and DASH?
2. Can the nginx-vod-module expose the IV from an external key server in the m3u8 manifest? As far as I know, the nginx-vod-module will expose the IV when the `vod_secret_key`, `vod_encryption_iv_seed`, and `vod_hls_container_format` are set to `fmp4`.

**Comment by nonth** [comment]
Hello @erankor 

Thanks for clarifying. Just a few more questions:

1. Is there any reason behind why the module doesn't expose IV to m3u8?
2. Is it possible to implement something like `pckg_m3u8_enc_output_iv`, similar to the nginx-pckg-module for option 1? I can work on that.

**Comment by erankor** [comment]
1. There just wasn't any need for this -
  - When using FairPlay DRM, the IV is served with the license
  - When using clear key with MPEG-TS, the module uses the default IV - derived from the segment index
  - When using clear key with fMP4, the module outputs the IV in the m3u8 - following a question I sent Apple long time ago :) they added this sentence to the HLS specification - 
```
If the Media Initialization Section declared by an EXT-X-MAP tag is
encrypted with a METHOD of AES-128, the IV attribute of the EXT-X-KEY
tag that applies to the EXT-X-MAP is REQUIRED.
```
2. It is possible, but I didn't quite understand why you need it.

**Comment by nonth** [comment]
@erankor I've submitted PR #1514  regarding this issue. Could you please review it? 

Thanks.
