### ISSUE TITLE
how to add extra info to the extinf tag?

### ISSUE THREAD

**Issue by sgrossiP** [kaltura/nginx-vod-module#1521]
hello everyone
any idea how to add extra info to the extinf tag? i need to send in the m3u8 file the start time of the mp4 file to know exactly what fragment is playing in the browser

th

edit:
im trying to add the clipFrom property but it does not appear to work, example below

{
   "playlistType":"vod",
   "discontinuity":true,
   "durations":[
      302994,
      300001,
      300002
   ],
   "sequences":[
      {
         "clips":[
            {
               "type":"source",
               "path":"/mnt/sda1/onvp/recordings/camera_459_2/2021/05/24/videos/camera_459_2-04-59-09.146895.mp4",
               "clipFrom":50854
            },
            {
               "type":"source",
               "path":"/mnt/sda1/onvp/recordings/camera_459_2/2021/05/24/videos/camera_459_2-05-04-12.141005.mp4"
            },
            {
               "type":"source",
               "path":"/mnt/sda1/onvp/recordings/camera_459_2/2021/05/24/videos/camera_459_2-06-59-24.172927.mp4",
               "clipFrom":300002
            }
         ]
      }
   ]
}

using .31 version

**Comment by erankor** [comment]
Adding extra info to EXTINF is not supported, but you can enable ID3 tags, which translate to metadata events in the player
