### ISSUE TITLE
Need a setup guide

### ISSUE THREAD

**Issue by sunnycamel** [kaltura/nginx-vod-module#154]
Hi,
There are some module that can do live steaming but less module can do vod.
And I only find this module can do vod and repackaging the media file to hls on-the-fly.
So I think I need this module.

I setup the nginx-vod-module by follow the READ.md, but it does not work.
So dear developers, can you write a guide and tell us how to set it up for some simple scenario.

below is my nginx.conf:

server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/vod;
    index index.html index.htm;

    # Make site accessible from http://localhost/
    server_name localhost;

    open_file_cache          max=1000 inactive=5m;
    open_file_cache_valid    2m;
    open_file_cache_min_uses 1;
    open_file_cache_errors   on;
    aio on;

    location / {
        vod hls;
        vod_mode local;
        vod_moov_cache moov_cache 512m;

        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        expires 100d;
        add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
        try_files $uri $uri/ =404;
    }

}

**Comment by erankor** [comment]
1. What is the URL that you tried ?
2. What error did you get ?
3. Are there any errors in the nginx error log ?

**Comment by sunnycamel** [comment]
hi,
thanks for your reply.
I found the root cause.
That because I add this line to the config:
try_files $uri $uri/ =404;
