### ISSUE TITLE
Problem compiling the module on Ubuntu 15.04

### ISSUE THREAD

**Issue by soufrk** [kaltura/nginx-vod-module#155]
Encountered the following error after executing 'make' after 'configure'
-----------------------------------------------------------------------------------------------------------------------
../nginx-vod-module/vod/hls/mpegts_encoder_filter.c: In function ‘mpegts_encoder_stuff_cur_packet’:
objs/ngx_auto_config.h:182:30: error: overflow in implicit constant conversion [-Werror=overflow]
 #define NGX_MAX_OFF_T_VALUE  9223372036854775807LL
                              ^
../nginx-vod-module/vod/hls/mpegts_encoder_filter.c:716:29: note: in expansion of macro ‘NGX_MAX_OFF_T_VALUE’
  state->send_queue_offset = NGX_MAX_OFF_T_VALUE;
                             ^
cc1: all warnings being treated as errors
objs/Makefile:1782: recipe for target 'objs/addon/hls/mpegts_encoder_filter.o' failed
make[1]: *** [objs/addon/hls/mpegts_encoder_filter.o] Error 1
make[1]: Leaving directory '/home/souvik/nginx-1.9.5'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
-------------------------------------------------------------------------------------------------------------------------------
New to working with nginx. Kindly help/let me know if any additional other information is required.

**Comment by erankor** [comment]
This is really weird, this variable has type off_t and it gets assigned with NGX_MAX_OFF_T_VALUE so I don't see why it breaks. 
Does nginx compile with this module ?
If it does, only explanation I can think of is that there are several different definitions of off_t in the system header files, nginx chooses one and nginx-vod chooses the other.
Try commenting out the lines:
#include <inttypes.h>
#include <sys/types.h>

in vod/common.h, this will make ngx_core.h the first file that is included and may resolve this problem.
If that doesn't help, please send the output of the configure command

**Comment by soufrk** [comment]
Yes, I have compiled nginx without this. I hope this does not create problem, if added alongwith nginx-rtmp-module. By the way, commenting the mentioned directives, works @erankor .

**Comment by soufrk** [comment]
Re-opening this thread for a new issue during compile

```
../nginx-vod-module/vod/audio_filter.c: In function ‘audio_filter_write_frame’:
../nginx-vod-module/vod/audio_filter.c:524:16: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  *cur_offset = (uint64_t)new_data;
                ^
../nginx-vod-module/vod/audio_filter.c: In function ‘audio_filter_process_frame’:
../nginx-vod-module/vod/audio_filter.c:714:2: error: ‘avcodec_get_frame_defaults’ is deprecated (declared at /usr/include/i386-linux-gnu/libavcodec/avcodec.h:3609) [-Werror=deprecated-declarations]
  avcodec_get_frame_defaults(state->decoded_frame);
  ^
cc1: all warnings being treated as errors
objs/Makefile:1665: recipe for target 'objs/addon/vod/audio_filter.o' failed
make[1]: *** [objs/addon/vod/audio_filter.o] Error 1
make[1]: Leaving directory '/home/souvik/nginx-1.9.5'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

```
Kindly, suggest what could be the issue.
Hope no extra information will be required.

**Comment by erankor** [comment]
Regarding the first warning, I assume you compile on 32 bit, change the (uint64_t) there to (uintptr_t).
Regarding the second warning, replace avcodec_get_frame_defaults with av_frame_unref.

**Comment by soufrk** [comment]
Issue not solved
```
../nginx-vod-module/vod/audio_filter.c: In function ‘audio_filter_write_frame’:
../nginx-vod-module/vod/audio_filter.c:525:13: error: assignment makes pointer from integer without a cast [-Werror]
  cur_offset = (uintptr_t)new_data;
             ^
cc1: all warnings being treated as errors
objs/Makefile:1665: recipe for target 'objs/addon/vod/audio_filter.o' failed
make[1]: *** [objs/addon/vod/audio_filter.o] Error 1
make[1]: Leaving directory '/home/souvik/nginx-1.9.5'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```
The interesting part is that, the same source code was getting compiled earlier.

**Comment by erankor** [comment]
could it be that you removed the asterisk that was there ?
it should be
```
*cur_offset = (uintptr_t)new_data;
```
what you pasted is missing the asterisk

**Comment by soufrk** [comment]
Yes, you are correct. Silly me. Now, it gets compiled.

But, I did not understand, how the module was compiling earlier? I did not update my code base. Any idea?

**Comment by erankor** [comment]
maybe you didn't have ffmpeg before ? the module can compile with or without this module, according to whether libavcodec/libavfilter is installed
