### ISSUE TITLE
HTTP header allow-cache defaults to 'YES'

### ISSUE THREAD

**Issue by soufrk** [kaltura/nginx-vod-module#159]
How can we turn caching option in M3U8 manifest generated? 
Below is the fragment from M3U8 file generated for VOD
```#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000 
```
As you can see, **allow-cache** header is set to **true** by default. How to set it false?

**Comment by erankor** [comment]
This is currently not configurable, what is the reason you want it set to FALSE ?

**Comment by soufrk** [comment]
Yes, I was going through the code and found the same. Actually, for testing purpose I'm using a custom developed player, and it is caching the fragments. If I make modifications to the source media file(without changing the name), it is not reflecting, until I request for refreshing the link.

**Comment by erankor** [comment]
Did you try changing the HTTP caching headers ?
We are using - Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0

**Comment by soufrk** [comment]
Looks like it's time modify source code.

**Comment by erankor** [comment]
Don't understand, changing the caching headers worked or not ?

**Comment by soufrk** [comment]
To change header, we need to modify source code, right?
Or, is there any other way?

**Comment by erankor** [comment]
No need to change the code, just use the standard nginx 'add_header' directive: http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header

**Comment by soufrk** [comment]
By adding 'Cache-Control' headers HTTP Header is changing, but not ```#EXT-X-ALLOW-CACHE:YES``` in m3u8 file.

**Comment by erankor** [comment]
I know it won't change EXT-X-ALLOW-CACHE, my question was - does the player you are testing with still cache the stream even when the HTTP headers tell it not to cache ?

**Comment by garybruckheimer** [comment]
even with EXT-X-ALLOW-CACHE there are some players on iOS (native) that
still caches the segments and manifests.

i set a rewrite to add a date-timestamp to milliseconds to the
*.ts?1234546 segemnts as well to the manifest ***.m3u8?12345678

and then the player was not able at all to cache.

maybe that can help.

gary


Am 13.10.15 um 16:23 schrieb erankor:

**Comment by garybruckheimer** [comment]
and forgot that also some CDN`s like level(3) with their caching nodes
caches all the ts and manifest, but with the timestamp i was albe to fix
it from that point. the issues you maybe can have with this in
combination with CDN´s is that the origin´s servers get all the load´s
for all new requests.

gary

Am 13.10.15 um 16:29 schrieb neve_capricorn@gmx.de:

**Comment by soufrk** [comment]
@erankor No it is not caching now.
