### ISSUE TITLE
vod_drm_upstream is null

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#160]
Hello! Firsr of all i want to thanks for such great soft.
Now about a problem:
10.130.130.1 - is the local test server, i want to test dash drm. So this server will be and as dash streamer and as drm server.

In default /etc/nginx/nginx.conf i added: 
        upstream drmservice {
        server 10.130.130.1;
        }

In /etc/nginx/conf.d/test.conf:

        location /pdash/ {
            vod dash;
            vod_mode local;
            vod_moov_cache moov_cache 512m;
            vod_multi_uri_suffix .urlset;

            vod_segment_duration 1000;

            vod_drm_enabled on;
            vod_drm_upstream drmservice;
            vod_drm_request_uri /pdash-key/key.js;

            alias /storage/;

            gzip on;
            gzip_types application/dash+xml;

            expires 600s;
        }
        location /pdash-key/ {
        alias /storage/;
        }

In /storage/key.js:
{"pssh": [{"data": "CAESEGMyZjg2MTczN2NjNGYzODIaB2thbHR1cmEiCjBfbmptaWlwbXAqBVNEX0hE", "uuid": "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"}], "key": "GzoNU9Dfwc//Iq3/zbzMUw==", "key_id": "YzJmODYxNzM3Y2M0ZjM4Mg=="}

So when i try to take mpd file in error log i see:

2015/10/23 17:35:05 [error] 22428#0: *4 ngx_http_vod_wev_handler: unexpected, upstream is null while sending response to client, client: 10.120.120.1, server: , request: "GET /pdash/test-,450,850,2800,.mp4.urlset/manifest.mpd HTTP/1.1", host: "10.130.130.1", referrer: "http://10.130.130.130/player/samples/index.html"

Is it my mistake or something works not properly?

**Comment by erankor** [comment]
You are missing a location such as:
```
        location ^~ /__child_request__/ {
            internal;
            vod_child_request;
        }
```
and then, in your location, you need to point to it by something like:
```
        vod_child_request_path /__child_request__/;
```
the module needs these setting in order to be able to issue an HTTP request.
I have a validation for that in mapped/remote modes, but forgot to add the validation for DRM as well.

**Comment by kuznetcoff777** [comment]
Thanks for a quick response.

My total config is:
        location /pdash/ {
            vod dash;
            vod_mode local;
            vod_moov_cache moov_cache 512m;
            vod_multi_uri_suffix .urlset;

            vod_segment_duration 1000;

            vod_drm_enabled on;
            vod_drm_upstream drmservice;
            vod_drm_request_uri /pdash-key/key.js;
            vod_child_request_path /child_request/;

            alias /storage/;

            gzip on;
            gzip_types application/dash+xml;

            expires 600s;
        }
        location /pdash-key/ {
        alias /storage/;
        }
        location ^~ /child_request/ {
            internal;
            vod_child_request;
        }


Manifest is downloadable and player takes it normally. But bit-dash player gets chunks but does not play it, black screen only, so it seems to be a a player issue. Thanks!

**Comment by erankor** [comment]
Maybe it doesn't know how to obtain the key, we have some custom code on the client side to handle that. Btw, we're testing with dashif player
