### ISSUE TITLE
GPG signature error

### ISSUE THREAD

**Issue by shaharmor** [kaltura/nginx-vod-module#161]
When using `apt-get install kaltura-nginx`:

```
W: GPG error: http://installrepo.kaltura.org jupiter InRelease: The following signatures were invalid: BADSIG E7EEDECAA1174D5E Kaltura deb repo <community@kaltura.com>
W: Failed to fetch http://installrepo.kaltura.org/repo/apt/debian/dists/jupiter/main/binary-i386/Packages  404  Not Found [IP: 54.230.161.88 80]
```

**Comment by jessp01** [comment]
Hi Shahar,

What do you have in your repo file?
Should be:
deb [arch=amd64] http://installrepo.origin.kaltura.org/repo/apt/debian-nightly kajam main

And you should import the key with:
\# wget -O - http://installrepo.kaltura.org/repo/apt/debian/kaltura-deb.gpg.key|apt-key add -

Then:
\# aptitude update
\# aptitude install kaltura-nginx

You can also use apt-get instead but aptitude has a better resolution algorithm and is therefore always recommended.

**Comment by shaharmor** [comment]
Hey Jess, long time :-)

I just followed the readme which points to this:

```
# wget -O - http://installrepo.kaltura.org/repo/apt/debian/kaltura-deb.gpg.key|apt-key add -
# echo "deb http://installrepo.kaltura.org/repo/apt/debian jupiter main" > /etc/apt/sources.list.d/kaltura.list
# apt-get update
# apt-get install kaltura-nginx
```

**Comment by jessp01** [comment]
Hi Shahar,

This warning:
W: Failed to fetch http://installrepo.kaltura.org/repo/apt/debian/dists/jupiter/main/binary-i386/Packages  404  Not Found [IP: 54.230.161.88 80]

Is simply meant to indicate there is no 32bit repo in existence, which is quite true, since we only support 64bit. It is none fatal but if you instead use the line I gave you which has ' [arch=amd64]' indicating to APT there is only a 64bit arch and there is no need to emit a warning. Anyhow, it is non fatal.

As far as the key, I suggest you reimport it, post changing the repo line as indicated above.
The stable version is now Kajam, no longer Jupiter.

**Comment by shaharmor** [comment]
I updated the repo, which fixed the first error, but the 404 still appears:

W: Failed to fetch http://installrepo.kaltura.org/repo/apt/debian/dists/Kajam/main/binary-amd64/Packages  404  Not Found [IP: 205.251.206.126 80]

Or this if i update the link to debian-nightly:
W: Failed to fetch http://installrepo.origin.kaltura.org/repo/apt/debian-nightly/dists/Kajam/main/binary-amd64/Packages  404  Not Found

**Comment by jessp01** [comment]
You have a typo, Kajam in your URL is upper cased and should not be...
http://installrepo.kaltura.org/repo/apt/debian/dists/kajam/main/binary-amd64/Packages
Repo line should be:
deb [arch=amd64] http://installrepo.origin.kaltura.org/repo/apt/debian kajam main
again, lower cased 'k'.
\# cat /etc/apt/sources.list.d/kaltura.list
deb [arch=amd64] http://installrepo.origin.kaltura.org/repo/apt/debian kajam main

\# apt-cache policy kaltura-nginx 
kaltura-nginx:
  Installed: 1.8.0-6+b3
  Candidate: 1.8.0-6+b3
  Version table:
 *** 1.8.0-6+b3 0
        500 http://installrepo.origin.kaltura.org/repo/apt/debian/ kajam/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by shaharmor** [comment]
Oops.

Thanks!

**Comment by tanmayabbsr09** [comment]
@shaharmor 

I am facing a issue while adding "apt-get install kaltura-nginx"

**Unable to locate package kaltura-nginx**

Can you help me with this ?
