### ISSUE TITLE
AAC encoder error when starting up

### ISSUE THREAD

**Issue by shaharmor** [kaltura/nginx-vod-module#163]
Hi,

When ever i'm restarting the service i'm seeing this error:
2015/11/01 10:33:35 [error] 6691#0: audio_filter_process_init: failed to get AAC encoder

The audio still works so i'm not sure if its related to something

**Comment by KalturaCommunity** [comment]
The relevant piece of code is this:
nginx-vod-module/vod/audio_filter.c:
         encoder_codec = avcodec_find_encoder_by_name(AAC_ENCODER_NAME);
         if (encoder_codec == NULL)
         {
                 vod_log_error(VOD_LOG_ERR, log, 0,
                         "audio_filter_process_init: failed to get AAC 
encoder");
                 return;
         }

It reproduces on my ENV as well. avcodec_find_encoder_by_name is a 
function defined in FFMPEG, see: 
https://ffmpeg.org/doxygen/2.7/group__lavc__encoding.html#gaa614ffc38511c104bdff4a3afa086d37

I'll run it with GDB and non stipped version of the ffmpeg avutil lib to 
check it out. We recently moved to a new version of FFMPEG [2.7.2] which 
might account to it.

Eran - if you get to it before I do, please let me know.

Thanks,

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by jessp01** [comment]
Hi Shahar,

This error means the FDK AAC encoder was not found.
Since compiling with FDK means you cannot distribute the resulting binary, 
We cannot compile the kaltura-ffmpeg deb with fdk support. Instead, we 
rely on ffmpeg's internal implementation of AAC, mentioned here:
https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio

We've run tests on it and found it to be functioning well.
However, if you wish to compile your own FFMPEG and include --enable-libfdk-aac 
---enable-nonfree in your compilation flags, you certainly can do so and 
use it instead of the binaries offered in the kaltura-ffmpeg package. It 
is legal just as long as you do not distribute it.

Thanks,



May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by erankor** [comment]
Note that the only functionality that is currently affected by this issue is the change of audio playback rate, other than that, everything should work fine. I may add fallback to libfaac included with ffmpeg, but as I recall it didn't work well for me in the past (some files just would not play)

**Comment by soufrk** [comment]
Same issue here. Ubuntu 15.04. Had **libfdk-aac** installed yet encountered the problem. Well, as @jessp01 pointed out "This error means the FDK AAC encoder was not found.", installed **aac-enc** as well, and the error seems to have been stopped.

**Comment by jaasco** [comment]
>  you certainly can do so and
use it instead of the binaries offered in the kaltura-ffmpeg package. 

Hi jessp01.
Could you explain me please how to configure kaltura nginx-vod-module to use other ffmpeg binaris (not kaltura-ffmpeg).
Thanks!

Mike

**Comment by jessp01** [comment]
Hi @jaasco,
First, you'll need to build ffmpeg with FDK support by passing:
```
--enable-libfdk-aac
--enable-nonfree
```
to its configure script. 
We use FFmpeg 3.2 at the moment, I recommend you use the same one.

Then, you'll need to build the VOD Nginx module, either statically into Nginx [required if you're running Nginx < 1.9.11] or as a shared object [SO] [if you're running Nginx >= 1.9.11]. Instructions on how to build the module are in the README. You need to make sure the FFmpeg libs and header files are available when running the Nginx configure command. If you've used a non standard prefix when building FFmpeg, you'll need to set these ENV vars:
```
LD_LIBRARY_PATH=$FFMPEG_PREFIX/lib
LIBRARY_PATH=$FFMPEG_PREFIX/lib
C_INCLUDE_PATH=$FFMPEG_PREFIX/include
```

**Comment by looped-monk** [comment]
Hello, 
Getting the same warning as the OP @shaharmor. Building using docker ubuntu 22.04 and installed ffmpeg separately.
`FFMPEG 7.1 `building from source and installed the dependency `libfdk-aac-dev` and 
`aac-enc` as well. 

What could be going wrong ?
