### ISSUE TITLE
Add ability to generate HLS master/variant playlist for nginx-vod-module

### ISSUE THREAD

**Issue by mcori** [kaltura/nginx-vod-module#165]
Hello,
Guys from https://www.quickflix.com.au/ want that I add the such support to your module. But they will approve my work only if you will add the support made by me into your module. May I expect that you will?
My name is Michail Korneev. If you need, you can write me to mchl.cori@gmail.com

Thank you.

**Comment by erankor** [comment]
Hi,

I don't quite understand what is the feature you would like to add, nginx-vod-module has the ability to generate a master playlist, as mentioned here - https://github.com/kaltura/nginx-vod-module/#filename-structure (master.m3u8).
Unless you are referring to a master playlist with multiple audio tracks ?

Anyway, regarding code contributions for this project, in general, we are happy to get pull requests. But we will only merge code that is coherent with the rest of the module. When I say coherent I refer to functionality, configuration, coding standards, performance etc.
For this reason, I cannot commit that a code contribution will be accepted in advance, but what I can say is that each contribution will be reviewed, and we will positively consider merging it.
Either way, before starting to implement a new feature, it would be a good idea to have a discussion with us on how it's going to be implemented, which configuration options will be added etc. This would significantly reduce the chances of the pull not being merged at the end. You can email me directly at eran.kornblau at kaltura dot com.

Thanks

Eran

**Comment by erankor** [comment]
Merged the pull by @mcori to latest master.
In case of an MP4 file containing multiple video tracks, the module will render each video track as a separate stream in HLS master requests.
