### ISSUE TITLE
mp4_parser_parse_stts_atom: frame count exceeds the limit 1048576 while reading moov atom

### ISSUE THREAD

**Issue by chakree30584** [kaltura/nginx-vod-module#175]
mp4 file cannot stream (mpd or m3u8 url return 404)
and I got this error in error.log

mp4_parser_parse_stts_atom: frame count exceeds the limit 1048576 while reading moov atom

please take a look

Thank you.

**Comment by erankor** [comment]
what is the video duration and frame rate ? can you send you nginx.conf ?
also, are you using vod_manifest_segment_durations_mode accurate ? if so, try changing it to estimate

**Comment by chakree30584** [comment]
video details from ffprobe for your information
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '2015-11-15_15-00_Tutor-Training1_HD.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 06:15:45.12, start: 0.023220, bitrate: 477 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1024x768, 333 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 137 kb/s (default)
    Metadata:
      handler_name    : SoundHandler


after change vod_manifest_segment_durations_mode from accurate to estimate 
everything is working now !

Thanks for you help.

**Comment by erankor** [comment]
Indeed a long video :) if the audio frame rate is about 50 (it's not shown in this ffprobe output) then it makes sense that it would hit the limit (6.25 x 3600 x 50 > 1M)

**Comment by s2pAIr** [comment]
+1

**Comment by movy** [comment]
For those googling, use `vod_max_frame_count: 2097152;` setting
