### ISSUE TITLE
Predownload segments

### ISSUE THREAD

**Issue by jos89** [kaltura/nginx-vod-module#177]
Hi everyone, I want to know if there is a way to download, most segments, after putting play.
Now, after putting play, download only the current segment, then just about to finish, it will begin downloading the next segment. I would like in this case, started to download at least 5-6 segments, following. (a kind of buffer).

it's possible?

thank you

**Comment by jos89** [comment]
for streaming HLS, sorry

**Comment by erankor** [comment]
The buffer size is controlled by the player, the server does not control it. Some players expose parameters for min/max buffer size, for example, our flash HLS player (https://github.com/kaltura/HLS-OSMF/) has such parameters

**Comment by jos89** [comment]
Perfect! I try it now!
also supports the FLV format? (old files not converted to mp4)

Thank you

**Comment by erankor** [comment]
This module only works with MP4, we may add more formats in the future, like WEBM, but most likely not FLV. You can easily repackage the FLV to MP4 with ffmpeg, something like - 
```
ffmpeg -i <input file> -acodec copy -vcodec copy -f flv -y <output file>
```
Since it doesn't do any transcoding, it should work pretty fast

**Comment by jos89** [comment]
I have 87k old files in flv, I will see how to handle it. Thanks for the support
