### ISSUE TITLE
Mapped mode: how it works?

### ISSUE THREAD

**Issue by vishnevyipirog** [kaltura/nginx-vod-module#180]
Hi there!

I have a task to make an adaptive hds streaming using your module. Everything was quite simple while I was testing local mode: it works great! But now I need to make my hds streams adaptive in order to give every viewer an opportunity to get best bitrate according to his technical environment. I tried to use mapped mode for this purpose but I'm not quite sure if I understand how to generate a JSON that can be readable by nginx-vod-module and how do (or don't) I choose a bitrate for every viewer? Is it somehow distributed in your module or am I supposed to do it with third party soft?
Or can I make an adaptive streaming using local mode?

Thanks in advance.

**Comment by erankor** [comment]
You can use adaptive stream in local mode using multi url - https://github.com/kaltura/nginx-vod-module/#multi-url-structure

**Comment by vishnevyipirog** [comment]
Thank you very much for your answer!

If I understand everything correctly, it should go like this:
http://<domain>/<location>/<prefix>,<middle1>,<middle2>,<middle3>,<postfix>.urlset/<filename>
http://test.com/vod/<prefix>,LowQuality.mp4,HighQuality.mp4,<postfix>.urlset/manifest.f4m

Documentation makes it quite clear how to change vod_multi_uri_suffix but what does <prefix> (and <postfix>) stand for?

**Comment by erankor** [comment]
prefix and postfix are just the common parts of the urls, for example, if you have:
http://mydomain.com/videos/coolvideo/media_low_bitrate.mp4
http://mydomain.com/videos/coolvideo/media_mid_bitrate.mp4
http://mydomain.com/videos/coolvideo/media_high_bitrate.mp4

then prefix will be 'coolvideo/media_' and postfix will be '_bitrate.mp4', so in this case the combined URL will be:
http://mydomain.com/videos/coolvideo/media_,low,mid,high,_bitrate.mp4.urlset/manifest.f4m

**Comment by vishnevyipirog** [comment]
Now it's clear, thank you again!
