### ISSUE TITLE
nginx-vod-module on FBSD

### ISSUE THREAD

**Issue by vishnevyipirog** [kaltura/nginx-vod-module#182]
Hi there again!
Is there a way to configure and install nginx with your module on FreeBSD?
Tried to add it to makefile in /usr/ports/www/nginx like other modules are added but it's a bit harder than I expected it to be.
Thanks in advance.

**Comment by erankor** [comment]
We do not test nor create packages for FreeBSD, but I believe it should work.
Did you follow the instructions in https://github.com/kaltura/nginx-vod-module/#build ?

**Comment by vishnevyipirog** [comment]
Thank you for your reply, Erankor!
Yeah, that was my first step. Sorry for not mentioning it.
Have had a lot of mistakes like these during 'make' process:
/home/nginx_test/nginx-vod-module-1.4/vod/hls/aes_cbc_encrypt.c:44: undefined reference to `EVP_CIPHER_CTX_init'
/home/nginx_test/nginx-vod-module-1.4/vod/hls/aes_cbc_encrypt.c:46: undefined reference to `EVP_aes_128_cbc'
/home//nginx_test/nginx-vod-module-1.4/vod/hls/aes_cbc_encrypt.c:46: undefined reference to `EVP_EncryptInit_ex'
... etc (can show you the whole error output if you need it).
And it finished with
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

**Comment by erankor** [comment]
Seems like nginx does not link against openssl.
Before the errors you pasted there should a line that contains all the libraries that it links against, e.g. mine is:
```
        -lpthread -lpthread -lcrypt -lrt -lavcodec -lavutil -lavfilter -lavutil -lpcre -lcrypto -lcrypto -lz
```
Can you paste this line ?

**Comment by vishnevyipirog** [comment]
Sure, mine is:
```
-lcrypt -L/usr/local/lib -lpcre -lmd -lmd -lz
```

**Comment by erankor** [comment]
edit the config file of nginx-vod-module and add the following after ngx_addon_name=ngx_http_vod_module:
```
CORE_LIBS="$CORE_LIBS -lcrypto"
```
then rerun configure and make

**Comment by vishnevyipirog** [comment]
That solved libraries problems for me, thank you very much for your support!

**Comment by erankor** [comment]
fixed in latest master - the module detects whether openssl is avail, if it is it adds -lcrypto, otherwise it compiles without DRM/enrypted HLS
