### ISSUE TITLE
nginx performance with reuseport (SO_REUSEPORT)

### ISSUE THREAD

**Issue by sergiyshutov** [kaltura/nginx-vod-module#185]
Hi erankor. 
What about new feature reuseport? Can we use this with vod-module? And what about performance with this? 
Thank you very much :)

**Comment by erankor** [comment]
Didn't try it, but it should work fine. This setting affects much lower layers in nginx, and is completely transparent to nginx-vod-module

**Comment by sergiyshutov** [comment]
Thank you very much.
