### ISSUE TITLE
Serving TS files with a 200 OK header

### ISSUE THREAD

**Issue by peace-** [kaltura/nginx-vod-module#191]
i just saw another HLS on demand generator which serves its TS files with a `206 Partial Content` header.

is that possible to use the module this way ?

**Comment by erankor** [comment]
Do you mean that media playlist (m3u8) will output the same URL for all segments but with a different range (#EXT-X-BYTERANGE) each time ?
What is the use case for this ?

**Comment by peace-** [comment]
Well , actually the problem is not the media playlist or segments.

there`s a way to prevent IDM to show its download popup , i saw another HLS on demand generator that when i play a video it prevents IDM from showing its popup , i`ve checked every single part of the requests , changed some headers and made the requests same as that component , but still does not work for me.

the only difference now is that they serve each TS file with `206 Partial Content` and we serve the TS files with a `200 OK` response.

so i was gonna check if i can change that.

**Comment by bahmanalidadi777** [comment]
oh;  I have this problem :(
I have a tutorial website, and I want to prevent download my videos;
I use your module; how do I can prevent IDM for download my videos?

**Comment by erankor** [comment]
Sounds very weird to me that a web server will return 206 when the client did not perform a range request... But anyway, you can probably configure another nginx location that will proxy_pass to nginx-vod and add to the request the header 'Range: bytes=0-', this should make nginx return 206.
Something like:
```
location /proxy/ {
    proxy_pass http://localhost/vod/;
    proxy_set_header Range bytes=0-;
}
```

**Comment by peace-** [comment]
Yes its actually really weird that component works so much confusing it removes `Connection` header from http headers too. unfortunately i dont have access to that , and as much i know , its a ASP .NET component.

The method you said works fine but does not resolve my problem. but thanks alot @erankor for your support and the awesome vod module
