### ISSUE TITLE
Multiple requests to upstream server in mapped mode

### ISSUE THREAD

**Issue by frankville** [kaltura/nginx-vod-module#194]
Hi everyone, I've noticed that kaltura (configured with mapped mode) is making several requests to the upstream server so I end up serving the same JSON over and over. I would like to know if  anyone experimented the same issue, if this is a bug or I'm missing something. Thanks a lot

**Comment by erankor** [comment]
You can enable vod_path_mapping_cache (https://github.com/kaltura/nginx-vod-module/) to have the module cache the JSON response

**Comment by frankville** [comment]
Thanks Eran, That was the solution. I'm gonna close this issue.
