### ISSUE TITLE
Multi URL format for Kaltura

### ISSUE THREAD

**Issue by anurag-dixit** [kaltura/nginx-vod-module#201]
Dear All,
We were trying to get the Multi URL working with Kaltura CE, single URL works.
Could anyone tell would be the right multi URL format for kaltura CE?
Thank you in advance for your help or advise.
Anurag

**Comment by erankor** [comment]
When working with Kaltura CE the Kaltura server can create the multi URL for you, the relevant delivery profiles are created as part of the installation. For example, these are the parameters of the DASH delivery profile: https://github.com/kaltura/server/blob/Kajam-11.5.0/deployment/base/scripts/init_data/07.DeliveryProfileVodPackagerDash.template.ini
If your environment is configured correctly, and you use the Kaltura player, it should just work. If you need to build the URL (for use in some other player) you need to use the Kaltura playManifest API for that.

**Comment by anurag-dixit** [comment]
Thanks.
This solves my problem.
