### ISSUE TITLE
Issue Using Module

### ISSUE THREAD

**Issue by BraydenGirard** [kaltura/nginx-vod-module#202]
Hello, I am trying to get this module working and have not been able to have success.

My mp4 file is stored locally on the nginx server at the following location:
/video_recordings/H22mzoDQ.mp4

I am trying to hit the following url in safari and I am getting a 404 Not Found:

http://1.engine.streamfit.tv/vod/H22mzoDQ/index.m3u8

Attached is my nginx configuration file. I am also using this module along with the nginx rtmp module.
[nginx.conf.zip](https://github.com/kaltura/nginx-vod-module/files/68753/nginx.conf.zip)

**Comment by erankor** [comment]
you are missing the .mp4 on the file name, when the file has an mp4 extension the url should end with .mp4/index.m3u8

**Comment by BraydenGirard** [comment]
http://1.engine.streamfit.tv/vod/H22mzoDQ.mp4/index.m3u8

Still gives me a 404 error.

**Comment by erankor** [comment]
the nginx error log does not say anything ?

**Comment by BraydenGirard** [comment]
Should have checked that, file structure was incorrect and it couldn't find the file. Thanks
