### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by vivek779** [kaltura/nginx-vod-module#203]
hello I tried to install nginx-vod-module but it gives following error when i use make install
make[1]: Leaving directory `/root/nginx-1.6.2'
make -f objs/Makefile install
make[1]: Entering directory `/root/nginx-1.6.2'
test -d '/usr/local/nginx' || mkdir -p '/usr/local/nginx'
test -d '/usr/local/nginx/sbin'                 || mkdir -p '/usr/local/nginx/sb                                                                                                                                                                               in'
test ! -f '/usr/local/nginx/sbin/nginx'                 || mv '/usr/local/nginx/                                                                                                                                                                               sbin/nginx'                     '/usr/local/nginx/sbin/nginx.old'
cp objs/nginx '/usr/local/nginx/sbin/nginx'
test -d '/usr/local/nginx/conf'                 || mkdir -p '/usr/local/nginx/co                                                                                                                                                                               nf'
cp conf/koi-win '/usr/local/nginx/conf'
cp conf/koi-utf '/usr/local/nginx/conf'
cp conf/win-utf '/usr/local/nginx/conf'
test -f '/usr/local/nginx/conf/mime.types'              || cp conf/mime.types '/                                                                                                                                                                               usr/local/nginx/conf'
cp conf/mime.types '/usr/local/nginx/conf/mime.types.default'
test -f '/usr/local/nginx/conf/fastcgi_params'          || cp conf/fastcgi_param                                                                                                                                                                               s '/usr/local/nginx/conf'
cp conf/fastcgi_params          '/usr/local/nginx/conf/fastcgi_params.default'
test -f '/usr/local/nginx/conf/fastcgi.conf'            || cp conf/fastcgi.conf                                                                                                                                                                                '/usr/local/nginx/conf'
cp conf/fastcgi.conf '/usr/local/nginx/conf/fastcgi.conf.default'
test -f '/usr/local/nginx/conf/uwsgi_params'            || cp conf/uwsgi_params                                                                                                                                                                                '/usr/local/nginx/conf'
cp conf/uwsgi_params            '/usr/local/nginx/conf/uwsgi_params.default'
test -f '/usr/local/nginx/conf/scgi_params'             || cp conf/scgi_params '                                                                                                                                                                               /usr/local/nginx/conf'
cp conf/scgi_params             '/usr/local/nginx/conf/scgi_params.default'
test -f '/usr/local/nginx/conf/nginx.conf'              || cp conf/nginx.conf '/                                                                                                                                                                               usr/local/nginx/conf/nginx.conf'
cp conf/nginx.conf '/usr/local/nginx/conf/nginx.conf.default'
test -d '/usr/local/nginx/logs'                 || mkdir -p '/usr/local/nginx/lo                                                                                                                                                                               gs'
test -d '/usr/local/nginx/logs' ||              mkdir -p '/usr/local/nginx/logs'
test -d '/usr/local/nginx/html'                 || cp -R html '/usr/local/nginx'
test -d '/usr/local/nginx/logs' ||              mkdir -p '/usr/local/nginx/logs'
make[1]: Leaving directory `/root/nginx-1.6.2'
please guide i am new here not able to figure out the problem

**Comment by erankor** [comment]
I don't see any errors there, that's how it's supposed like to look when nginx is installed successfully. The nginx build system does not print a 'success' message, if you don't see an error it means it's ok

**Comment by vivek779** [comment]
thanks for quick response i am not able to figuure that out thanks
