### ISSUE TITLE
HLS AES encryption - how to

### ISSUE THREAD

**Issue by soufrk** [kaltura/nginx-vod-module#214]
Well, this is not an issue. Can you simplify on a "how to" of AES Encryption on HLS. I have read through the issues raised by others, but couldn't obtain a complete working configuration needed for the same.

Below is part of nginx.config file
```
# VOD Module HLS Configurations
	location /content {
	    vod hls;
	    vod_mode local;
	    vod_moov_cache moov_cache 512m;
	    vod_secret_key "testKey-$vod_filepath";
	    types {
		application/vnd.apple.mpegurl m3u8;
		video/mp2t ts;
	    }

	    root /var;
	    add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
	    #gzip on;
	    #gzip_types application/vnd.apple.mpegurl;
	}
```
Now, when I'm trying to access the stream, it plays without any problem. I guess there is some other configuration as well that are missing. I read others configurations, but am not able to figure out which ones do I need to add. Kindly, help !!

**Comment by erankor** [comment]
you are missing `vod_hls_encryption_method aes-128`
here is a sample configuration:
```
	location ~ ^/enc/fhls/p/\d+/(sp/\d+/)?serveFlavor/ {
		vod hls;
		vod_secret_key "SomeSecret$vod_filepath";
		vod_hls_encryption_method aes-128;

		vod_last_modified_types *;
		more_set_headers 'Access-Control-Allow-Headers: *';
		more_set_headers 'Access-Control-Expose-Headers: Server,range,Content-Length,Content-Range,Date';
		more_set_headers 'Access-Control-Allow-Methods: GET, HEAD, OPTIONS';
		more_set_headers 'Access-Control-Allow-Origin: *';
		expires 100d;
	}	
```

**Comment by soufrk** [comment]
Thank you for the quick response. 
Is this all one needs? Any changes to URI to be made ??
And is the following header mandatory - ```vod_hls_encryption_key_file_name``` ??
What about the default value? Do we need to create a file ```emcryption.key``` or something ??

**Comment by erankor** [comment]
Yes, this is all that is needed.
`vod_hls_encryption_key_file_name` is not mandatory, it will default to encryption.key.
The encryption key is generated automatically by nginx-vod (it will evaluate `vod_secret_key` and hash the result), so you don't need to create any file.

**Comment by soufrk** [comment]
Thank you very much. Just one last question. 
*Is the playback supposed to happen with just the URL ?  I mean don't we need to pass the key explicitly or something ?*

**Comment by erankor** [comment]
In encrypted HLS the index.m3u8 contains a URL to the encryption key, so the player does not need anything else. You should see an `#EXT-X-KEY` tag in your index.m3u8 response.
We'll soon add a few configuration parameters to support Apple FairPlay DRM, and it will be a bit different there (the DRM server will provide the encryption key to nginx-vod instead of having nginx-vod generate the key)

**Comment by soufrk** [comment]
Yes, the key is present. So, the question is how do we restrict access to the key then ? I mean anyone who gets the URL will be able to play the content otherwise.

**Comment by erankor** [comment]
I don't know what is the flow you want to implement, but one way to implement such a thing would be to use a module such as our https://github.com/kaltura/nginx-akamai-token-validate-module to enforce a token on the encryption key request. 
Another may be to move the handling of the encryption key request to a separate nginx location (using regex), and apple some nginx access filter on that location

**Comment by soufrk** [comment]
That helps a lot. Thank u again !!

**Comment by arty777** [comment]
Can you please create any example config to restrict access to the encrypthon key with 
https://github.com/kaltura/nginx-akamai-token-validate-module

and exapmple config here please .

**Comment by soufrk** [comment]
I would have loved to more than anything, but sadly I am not working on this. I am currently trying to develop a HA load-balancer cluster front-end for Streaming Servers. I deeply admire the opportunity and wish I could have contributed to it. 
Let me see if I can come to it in near future.
