### ISSUE TITLE
nginx-vod-module and access_by_lua problem

### ISSUE THREAD

**Issue by dplesca** [kaltura/nginx-vod-module#215]
Hi,

I'm trying to use your module in conjunction with the nginx lua module. The nginx-vod-module is installed correctly and works as expected without an acces_by_lua check. Basically I have a simple [access_by_lua directive](http://46.101.136.48/access.lua.txt) that just checks the value of a GET param and acts accordingly. The nginx conf used is [this one](http://46.101.136.48/default.txt). The blocking of resources is done correctly (acces is denied on wrong token), but the content of the request is not the one I'd expect, i get a 404 response, something like:  
```2016/02/01 08:43:46 [error] 10384#0: *1 open() "/var/www/video/video_360p.mp4/master.m3u8" failed (20: Not a directory), client: xxxxxx, server: _, request: "GET /content/video_360p.mp4/master.m3u8?token=testtoken HTTP/1.1", host: "xxxxx"```.

This is the simplest test case we could find, otherwise our lua logic is more complex than this and we'd like to make sure we can still use it. Let me know if there's anything I'm missing or any additional info I could put forward.

**Comment by erankor** [comment]
I don't think the `vod hls` directive gets inherited to `location ~*.m3u8$`, and this location gets the nginx default handler that serves files. Try adding `vod hls` inside the m3u8 location

**Comment by dplesca** [comment]
Yes, that fixed it. Thank you for the response and for the amazing module!
