### ISSUE TITLE
Playback rate limitation

### ISSUE THREAD

**Issue by Classsic** [kaltura/nginx-vod-module#220]
Hi, I need playback rate x4 or x8, I understand this consume more cpu, but I really need faster playback. Where I can change de code to supress this limitation? Thanks.

**Comment by erankor** [comment]
You can edit rate_filter.c -
```
	if (rate->v.num.nom < 0 ||
		rate->v.num.denom > (uint64_t)rate->v.num.nom * 2 || (uint64_t)rate->v.num.nom > rate->v.num.denom * 2)
	{
		vod_log_error(VOD_LOG_ERR, context->request_context->log, 0,
			"rate_filter_parse: invalid rate %L/%uL, must be between 0.5 and 2", rate->v.num.nom, rate->v.num.denom);
		return VOD_BAD_MAPPING;
	}
```
Increase the 2 at the end of the first line to a higher value.
Note that while this will work for video, it won't work for audio - it's a limitation of the ffmpeg atempo filter. The only way to do it is to chain several atempo filters together and I preferred not to do it

**Comment by erankor** [comment]
Hi @Classsic, did this resolve the issue ? can this be closed ?

**Comment by Classsic** [comment]
Yes, this is ok, I will open a new issue about use kaltura with amazon s3. Thanks
