### ISSUE TITLE
Try files

### ISSUE THREAD

**Issue by celsoft** [kaltura/nginx-vod-module#221]
Hi. How to configure search using different drives? Try files. I have configured the caching of hot files on the ssd.
===
/megastorage1/aaa.video.org/files/
/megastorage2/bbb.video.org/files/
/megastorage3/ccc.video.org/files/
![clip2net_160209023341](https://cloud.githubusercontent.com/assets/5567863/12893647/a20a3f42-ced5-11e5-974d-e516b2100a4e.png)

**Comment by erankor** [comment]
This issue has been discussed here https://github.com/kaltura/nginx-vod-module/issues/143
