### ISSUE TITLE
hot link

### ISSUE THREAD

**Issue by celsoft** [kaltura/nginx-vod-module#223]
Hi! How to make a hot link protection? To protect the playlist and ts files.
![clip2net_160212203742](https://cloud.githubusercontent.com/assets/5567863/13005926/dc1ba7e8-d1c8-11e5-96b7-76f6316ed248.png)

**Comment by erankor** [comment]
I added a section to the readme regarding security - https://github.com/kaltura/nginx-vod-module#security
please let me know if that answers your question or you need any more info

**Comment by celsoft** [comment]
thank you. this is what you need.
