### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by momkin** [kaltura/nginx-vod-module#224]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I../nginx-rtmp-module-master  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
                -o objs/addon/nginx-vod-module-master/ngx_http_vod_dash.o \
                ../nginx-vod-module-master/ngx_http_vod_dash.c
cc1: warnings being treated as errors
../nginx-vod-module-master/ngx_http_vod_dash.c: In function ‘ngx_http_vod_dash_webm_handle_init_segment’:
../nginx-vod-module-master/ngx_http_vod_dash.c:263: error: dereferencing type-punned pointer will break strict-aliasing rules
make[1]: *** [objs/addon/nginx-vod-module-master/ngx_http_vod_dash.o] Error 1
make[1]: Leaving directory `/root/nginx-1.8.0'
make: *** [build] Error 2
root@de [~/nginx-1.8.0]#

**Comment by erankor** [comment]
try changing:
```
track_uid = *(uint64_t*)uri_key;
```
to:
```
ngx_memcpy(&track_uid, uri_key, sizeof(track_uid));
```
Also, on which environment are you compiling (OS, compiler, etc) ?

**Comment by momkin** [comment]
Centos 6.7 with nginx 1.8.0

**Comment by erankor** [comment]
Ok, and did the patch I suggested resolve the issue ?

**Comment by momkin** [comment]
I did try it
I used old version of your model and it worked

So i guess the problem only exist in the new version

**Comment by erankor** [comment]
That makes sense, this code is a new addition, but please let me know if the fix I wrote here resolves the problem in the latest version and I will commit it.
Also, are you using any special compilation parameters or just the nginx default ?

**Comment by momkin** [comment]
hello
i'm using this

./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx
--conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log
--http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid
--lock-path=/var/run/nginx.lock
--http-client-body-temp-path=/var/cache/nginx/client_temp
--http-proxy-temp-path=/var/cache/nginx/proxy_temp
--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp
--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp
--http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx
--with-http_ssl_module --with-http_realip_module
--with-http_secure_link_module --add-module=../nginx-vod-module-master
--with-file-aio --add-module=../nginx-rtmp-module-master
--with-http_addition_module --with-http_sub_module --with-http_dav_module
--with-http_flv_module --with-http_mp4_module --with-http_gunzip_module
--with-http_gzip_static_module --with-http_random_index_module
--with-http_secure_link_module --with-http_stub_status_module
--with-http_auth_request_module --with-mail --with-mail_ssl_module
--with-file-aio --with-ipv6 --with-http_spdy_module --with-cc-opt='-O2 -g
-pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector
--param=ssp-buffer-size=4 -m64 -mtune=generic'

unfortunately i cannot recompile nginx again as this is a client server i
just mention that so you can fix it in the next release thank you

**Comment by erankor** [comment]
Thanks @momkin, it appears that the -O2 flag triggered it.
We added -O3 to our CI build settings and updated the code
