### ISSUE TITLE
use s3 amazon with kaltura mapped

### ISSUE THREAD

**Issue by Classsic** [kaltura/nginx-vod-module#228]
Hi, I want storage my videos on amazon s3, and use goofys for mount it as local partition.
This work with the module, but the cache option keep open the files and this consume memory because is mounted as nfs. I try reducing the cache options, but still keep many files open. 
How can keep open only the files are using at the moment, or can disable cache options?
Thanks.

**Comment by erankor** [comment]
you need to disable the open_file_cache, this is standard nginx functionality, not part of nginx-vod-module

**Comment by Classsic** [comment]
Ok, i will tryit.
Anohter question, why mapped mode only can read local files, and not directly http url?

**Comment by erankor** [comment]
This is currently not supported, may be added in the future

**Comment by soufrk** [comment]
@Classsic Can you briefly explain and provide configurations on "how to setup with amazon s3" ?

**Comment by Classsic** [comment]
The same as default config, only mount s3 as local partition.
