### ISSUE TITLE
Adaptive set JSON format in Mapped configuration

### ISSUE THREAD

**Issue by Ivars** [kaltura/nginx-vod-module#235]
Hi,

I am trying to configure nginx-vod to use mapped configuration and everything works fine if I specify one sequence as described in "Simple mapping" documentation:

```
{
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/srv/video/low/movie_360Kbps_240p.mp4"
                }
            ]
        }
    ]
}
```

But if I define multiple files in JSON:

```
{
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/srv/video/low/movie_360Kbps_240p.mp4"
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/srv/video/medium/movie_512Kbps_360p.mp4"
                }
            ]
        }
    ]
}
```

Then I receive the following error in nginx log file:
4016#4016: *15 media_set_parse_sequence_clips: sequence clips count 1 does not match the durations count 0 while sending to client

From the error it seems that JSON is somehow incorrectly formatted or misses some additional parameters as the server picks up only one clip. 

I also tried to add _"duration": [5000, 5000]_ to the JSON file, and in this case the nginx creates the playlist and player (flowplayer) correctly plays 5 seconds sequentially from each file and then stops.

Are there any additional JSON or Nginx parameters needed to configure the server to combine multiple bitrate files in one playlist for adaptive video playback?

**Comment by erankor** [comment]
This was already fixed here: https://github.com/kaltura/nginx-vod-module/commit/336194ae979ee53db740a5c4353b31ea7137a5a9

It is possible that the latest pre-compiled version does not have the fix yet, you can compile the latest master to get it

**Comment by Ivars** [comment]
Thanks!
