### ISSUE TITLE
Playlist limit to 128 videos

### ISSUE THREAD

**Issue by Classsic** [kaltura/nginx-vod-module#238]
This module works great, but I need playlist with more than 128 videos, is there a way to brake this limit?
Thanks.

**Comment by erankor** [comment]
How many do you need ?

**Comment by Classsic** [comment]
3000. is possible?

**Comment by erankor** [comment]
I prefer at this point not to increase it to such a large number, it may change in the future. For now, you can just update the value of MAX_CLIPS defined in media_set.h locally in your environment, it should work fine.

**Comment by jsardas** [comment]
Is there any chance of updating the MAX_CLIPS value dynamically without having to edit media_set.h and recompile the entire module?
