### ISSUE TITLE
master m3u8 playlist generation

### ISSUE THREAD

**Issue by Ivars** [kaltura/nginx-vod-module#240]
Hi,

Are there some parameters which can be used in Nginx configuration to change how the master.m3u8 playlist is generated?

For example I need to test some m3u8 playlists without "CODEC" string in it:
https://github.com/kaltura/nginx-vod-module/blob/master/vod/hls/m3u8_builder.c#L14

Or I will need to make these changes in module source and recompile the module ?

**Comment by erankor** [comment]
Currently the configuration of the module does not offer this level of granularity, why do you need it ?

**Comment by Ivars** [comment]
I am currently researching possible migration from Adobe Media Server to Nginx Vod Module. 
In case of AMS we were using flash Flowplayer with PHP generated m3u8 playlists:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=700000
http://xxx.xxx.xxx.xxx/hls-vodfilmas/FLV_Low/2003 Foto 360p 700.mp4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1000000
http://xxx.xxx.xxx.xxx/hls-vodfilmas/FLV_Medium/2003 Foto 480p 1000.mp4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1250000
http://xxx.xxx.xxx.xxx/hls-vodfilmas/FLV_High/2003 Foto 576p 1250.mp4.m3u8
```

Nginx Vod module adds additional information Resolution and Codecs
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=551868,RESOLUTION=426x240,CODECS="avc1.640015,mp4a.40.2"
http://xxx.xxx.xxx.xxx/test/FLV_Low/testvideo_360Kbps_240p.mp4/index-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=703832,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.2"
http://xxx.xxx.xxx.xxx/test/FLV_Medium/testvideo_512Kbps_360p.mp4/index-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1191725,RESOLUTION=854x480,CODECS="avc1.64001f,mp4a.40.2"
http://xxx.xxx.xxx.xxx/test/FLV_High/testvideo_1000Kbps_480p.mp4/index-v1-a1.m3u8
```

The problem is that the first playlist works well on all browsers, but second playlist, when played in Firefox, stops in about 3-10 seconds. 

While investigating this problem, one of my colleagues remembered that when they were testing AMS (a while ago) they removed CODEC information from the generated playlist to avoid a similar issue.

So in order to test this assumption I need to somehow edit Nginx generated playlist as well.

**Comment by erankor** [comment]
You can try it out easily by manually editing the m3u8 - just download the m3u8, edit it and host it on some web server. Since by default the m3u8 uses absolute URLs, it doesn't have to be hosted on the same server, you can host the edited manifest anywhere you want

**Comment by Ivars** [comment]
Great idea. Thanks!

**Comment by Ivars** [comment]
Quick note:
Adding the nginx setting
`vod_align_segments_to_key_frames on;` 
as described in [#246](https://github.com/kaltura/nginx-vod-module/issues/246) fixed our Flowplayer playback issues in Firefox.

**Comment by erankor** [comment]
Great, thanks for the update
