### ISSUE TITLE
Issue with multiple sequences in mapped mode

### ISSUE THREAD

**Issue by Ivars** [kaltura/nginx-vod-module#242]
Hello again,
I am still dealing with the adaptive set of mp3 files for Mapped mode configuration as described here:
[#235](https://github.com/kaltura/nginx-vod-module/issues/235)

After installing new module version now JSON file with multiple sequences defined generates correct master.m3u8 playlist and also playlists for each file, but after that when player (flowplayer or VLC) requests actual .ts files I receive an error in log file:
`*93 ngx_http_vod_validate_streams: request has more than one sequence while only one is supported while reading media header, client: xxx.xxx.xxx.xxx, server: xxx.xxx.xxx.xxx, request: "GET /test/testvideo/seg-1-v1-a1.ts HTTP/1.1"`

As before - if I use JSON file with only one sequence - all playlists are generated correctly and video is opened correctly.

Is there any additional configuration missing? My nginx configuration is following:

```
http {
	upstream kalapi {
		#the same host
		server xxx.xxx.xxx.xxx:80;
	}
		
	include	/etc/nginx/mime.types;
	default_type  application/octet-stream;

	access_log /var/log/nginx/access.log main;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;

	keepalive_timeout 60;
	keepalive_requests 1000;
	client_header_timeout 20;
	client_body_timeout 20;
	reset_timedout_connection on;
	send_timeout 20;

	gzip  on;
	gzip_types application/vnd.apple.mpegurl video/f4m application/dash+xml text/xml;

	server {
		listen 80;
				
	    	location ^~ /kalapi/ {
                	internal;
                	proxy_pass http://kalapi/json/;
                	proxy_set_header Host $http_host;
            	}		
		
		# flowplayer files served from here 
		location /player/ {
			root   /var/www/;
		}
		
		# mapped json
		location /json/ {
			root   /var/www/;
			add_header Content-Type "application/json; charset=UTF-8";
		}

		#video test
                location /test/ {

                       vod hls;
                       vod_mode mapped;
		       vod_upstream_location /kalapi;
		       vod_upstream_extra_args "pathOnly=1";
                       
			#root /srv/video;
						
                        vod_secret_key "secret-$vod_filepath";
                        vod_hls_encryption_method aes-128;
                        vod_hls_encryption_key_file_name "secret";

                        add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
                        add_header Access-Control-Allow-Headers "*";
                        add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
                        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
                        add_header Access-Control-Allow-Origin "*";
			expires 100d;
                }
	}
}

```

**Comment by erankor** [comment]
can you paste the contents of the json and the master m3u8 ?

**Comment by Ivars** [comment]
json file (called testvideo):

```
{
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/srv/video/test/FLV_Low/testvideo_360Kbps_240p_test.mp4"
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/srv/video/test/FLV_Medium/testvideo_512Kbps_360p_test.mp4"
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/srv/video/test/FLV_High/testvideo_1000Kbps_480p_test.mp4"
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/srv/video/test/FLV_HD/testvideo_2500Kbps_720p_test.mp4"
                }
            ]
        }
    ]
}

```

and master.m3u8
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=551868,RESOLUTION=426x240,CODECS="avc1.640015,mp4a.40.2"
http://xxx.xxx.xxx.xxx/test/testvideo/index-f1-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=703832,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.2"
http://xxx.xxx.xxx.xxx/test/testvideo/index-f2-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1191725,RESOLUTION=854x480,CODECS="avc1.64001f,mp4a.40.2"
http://xxx.xxx.xxx.xxx/test/testvideo/index-f3-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2691104,RESOLUTION=1280x720,CODECS="avc1.640020,mp4a.40.2"
http://xxx.xxx.xxx.xxx/test/testvideo/index-f4-v1-a1.m3u8


I also just disabled encryption, because I noticed that even request to open secret.key generates the same error.

**Comment by erankor** [comment]
ok, one more thing, can you paste the contents of index-f1-v1-a1.m3u8 ?

**Comment by Ivars** [comment]
```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-1-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-2-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-3-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-4-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-5-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-6-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-7-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-8-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-9-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-10-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-11-v1-a1.ts

--- more segments ---

#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-559-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-560-v1-a1.ts
#EXTINF:10.000,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-561-v1-a1.ts
#EXTINF:1.200,
http://xxx.xxx.xxx.xxx/test/testvideo/seg-562-v1-a1.ts
#EXT-X-ENDLIST

```

**Comment by erankor** [comment]
Ok, I found the problem, change the if in this line:
https://github.com/kaltura/nginx-vod-module/blob/master/ngx_http_vod_module.c#L3146
To:
```
	if (mapped_media_set.sequence_count == 1 &&
		mapped_media_set.durations == NULL &&
		mapped_media_set.sequences[0].clips[0]->type == MEDIA_CLIP_SOURCE && 
		!mapped_media_set.has_multi_sequences)
```

(adding `&& !mapped_media_set.has_multi_sequences`)

**Comment by Ivars** [comment]
Yeah! Thanks!
I made your suggested change and then compiled Nginx and vod module from source and now all playlists are generated correctly from the received JSON file.

**Comment by erankor** [comment]
Thanks for the confirmation, merged: https://github.com/kaltura/nginx-vod-module/pull/244

**Comment by nehasalian** [comment]
can someone please tell me the url structure ? and the path where testvideo.json needs to be saved

**Comment by erankor** [comment]
For hls it would be: http://domain/location/path-to-json/master.m3u8
If you are using mapped mode with local files (=vod_upstream_location not set), the location of the json file is determined by nginx's builtin root/alias directives.

**Comment by erankor** [comment]
You provide the subtitles in the same way you provide renditions, so the JSON would look like this sample - https://github.com/kaltura/nginx-vod-module/#adaptive-set except it would have an SRT file instead of an MP4. 
In addition, for subtitles you'd probably want to provide the label / language fields of the sequence.
So something like -
```
{
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/path/to/video.mp4"
				}
			]
		},
		{
			"clips": [
				{
					"type": "source",
					"path": "/path/to/subtitle.srt"
				}
			],
			"language": "eng",
			"label": "English"
		}
	]
}
```
