### ISSUE TITLE
$vod_filepath and $vod_suburi parameters in mapped + Fairplay hls configuration

### ISSUE THREAD

**Issue by Ivars** [kaltura/nginx-vod-module#243]
#Hello,

I have configured nginx-vod-module as it was discussed in [#239](https://github.com/kaltura/nginx-vod-module/issues/239) and this configuration works with one key (specially created JSON file and binary key file).

In order to have different encryption key for every playlist I am trying to pass some variables to key generation urls.

I was expecting that with the following urls:
http://xxx.xxx.xxx.xxx/test/testvideo-1/master.m3u8
http://xxx.xxx.xxx.xxx/test/testvideo-2/master.m3u8
I will be able to pass testvideo-1 and testvideo-2 as a parameter to the keyserver and use it as ID to retrieve a key.

From reading the documentation it seems that it should be possible to retrieve this information using  $vod_suburi or $vod_filepath parameters, but whatever I try these parameters are always empty (checked in nginx access and error logs)

Please advise if there any more special parameters I need to set to pass $vod_suburi or $vod_filepath to vod_drm_request_uri and vod_hls_encryption_key_uri ?

My current nginx configuration is following:

```
server {
	listen 80;
	server_name www.filmas.lv;

	#mapped configuration server (separate host in future)
	location ^~ /kalapi/ {
		internal;
		proxy_pass http://kalapi/json/;
		proxy_set_header Host $http_host;
	}

	#key server (separate host in future)
	location ^~ /keyserver/ {
		internal;
		proxy_pass http://kalapi/key/;
		proxy_set_header Host $http_host;
	}

	# json
	location /json/ {
		root   /var/www/;
		add_header Content-Type "application/json; charset=UTF-8";
	}

	# json key
	location /key/ {
		root /var/www/;
		add_header Content-Type "application/json; charset=UTF-8";
	}
	

    # player files + currently secret.key as file (same host as /keyserver in future)
    location /player/ {
		root   /var/www/;
    }
		
	location /test/ {

		vod hls;
		vod_mode mapped;
		vod_upstream_location /kalapi;
			
		#what does this do:	
		#vod_upstream_extra_args "pathOnly=1";

		vod_hls_encryption_method aes-128;
		vod_hls_encryption_key_uri "http://xxx.xxx.xxx.xxx/player/secret.key?id=$vod_filepath";

		vod_drm_enabled on;
		vod_drm_upstream_location /keyserver;

		vod_drm_request_uri "/key.json?id=$vod_filepath";						
		#this also does not work:
		#vod_drm_request_uri "/$vod_suburi";

		gzip on;
		gzip_types application/vnd.apple.mpegurl video/f4m application/dash+xml text/xml;

		add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		add_header Access-Control-Allow-Headers "*";
		add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
		add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
		add_header Access-Control-Allow-Origin "*";
		expires 100d;
	}
}

```

**Comment by erankor** [comment]
$vod_suburi only works when using multi-url (https://github.com/kaltura/nginx-vod-module/#multi-url-structure) it doesn't work with JSON, since with JSON there is only a single uri for all bitrates. 
Earlier this week I added the ability to set an `id` for each sequence inside the JSON, and then use that id in a new variable called `$vod_sequence_id`, if I understand correctly, that should solve what you're trying to do

**Comment by Ivars** [comment]
Is there any parameter to access this single uri in Nginx configuration?

For example when accessing the following urls:

```
http://xxx.xxx.xxx.xxx/test/testvideo-2/master.m3u8
http://xxx.xxx.xxx.xxx/test/testvideo-2/index-f1-v1-a1.m3u8
```

it would be: 'testvideo-2'

Then I could use it to access the right key by performing DRM request like this:
```
vod_drm_enabled on;
vod_drm_upstream_location /keyserver;
vod_drm_request_uri "/key.json?id=testvideo-2";

```

**Comment by erankor** [comment]
You can do this with standard nginx capabilities - if you use a regular expression location, then you have the vars $1, $2, ... that resolve to matched expressions. 
It would be something like this:
```
location ~ ^/test/([^/]*)/.* {
    ...
    vod_drm_request_uri "/key.json?id=$1";
}
```

**Comment by Ivars** [comment]
Thanks it works!

**Comment by jaasco** [comment]
Hello, 
I have a similar question but don't want to start a new topic.
I'm also need to pass some GET parameters to the "key backend" to get pssh data return. 
Like this:

` location  /test/ {
                       ...
                        vod_drm_request_uri getpsshbox?param1=val1&param2=val2;
}
`
My backend log shows:
processing GET request for [/getpsshbox**%3F**param1=val1&param2=val2;]
And my question is - how to avoid URL-encoding for a '?' sign and get something like getpsshbox?param1=val1&param2=val2 in a request instead of /getpsshbox%3Fparam1=val1&param2=val2 ?
Or should I replace %3F to ? sign on a backend side?

**Comment by erankor** [comment]
The reason this happens is that nginx's proxy module escapes the uri. Currently, there is no parameter in nginx vod to pass args on drm requests (similar to vod_upstream_extra_args), but what you can probably do is map it on the proxy_pass location, something like this:
```
location ~ /drm_proxy/param1/([^/]+)/param2/([^/]+) {
	internal;
	proxy_pass http://drm/?param1=$1&param2=$2;
	proxy_set_header Host $http_host;
}
```
