### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by dan-quantox** [kaltura/nginx-vod-module#252]
I know this is not happiest place to put questions, if you have other form of communication please let me know. My question is, do you support events? For example, I would like to make call to external script/app before each HLS chunk is sent to determine is user allowed to see it. Not just on start of stream, but on each chunk. That external call could return 200 OK which would let user watch stream further, or 403 Forbidden to deny further streaming. 

Or any other solution to basically stop user stream in the middle whenever 3rd party tool decide.

**Comment by erankor** [comment]
You can probably configure something like that with access_by_lua

**Comment by dan-quantox** [comment]
Thank's for quick reply. Where I could get more info about this? Any documentation, sample config or anything.

**Comment by erankor** [comment]
This is not related to this module, the directive is documented here:
https://github.com/openresty/lua-nginx-module#access_by_lua
but you'll have to read some more on that page to understand how to implement the logic you need

**Comment by dan-quantox** [comment]
Thank you.
