### ISSUE TITLE
 x4 and x8 rate support

### ISSUE THREAD

**Issue by frankville** [kaltura/nginx-vod-module#253]
Hi, I would like to know if it is possible to add support for x4 and x8 rate values for playlist/mapped mode. Thanks

**Comment by erankor** [comment]
In mapped mode you should be able to nest several rateFilter's one on top of the other. 
Internally the module uses ffmpeg's atempo filter which is limited to the range 0.5-2, so even if the module will have native support for it, it will need to nest several filters together, and the result will be nearly the same

**Comment by frankville** [comment]
thanks for the reply, I've tried that and it worked so  I'll close this issue.
