### ISSUE TITLE
Mpeg-Dash manifest DASH-IF IOP 3.0 Compliance test

### ISSUE THREAD

**Issue by marzipi** [kaltura/nginx-vod-module#254]
Dear Eran,

I can not play Nginx dash video with Dash-if opensource player.

I have used an online manifest validatator to control Nginx manifest and it reports some errors on the frameRate* parameters.
 
The control can be done on http://www-itec.uni-klu.ac.at/dash/?page_id=605 and the errors reported are:

> Line:Col[11:46]:cvc-pattern-valid: Value ’**24.000**′ is not facet-valid with respect to pattern ‘[0-9]*[0-9](/[0-9]*[0-9])?’ for type ‘FrameRateType’.
Line:Col[11:46]:cvc-attribute.3: The value ’24.000′ of attribute ‘maxFrameRate’ on element ‘AdaptationSet’ is not valid with respect to its type, ‘FrameRateType’.
Line:Col[27:38]:cvc-pattern-valid: Value ’24.000′ is not facet-valid with respect to pattern ‘[0-9]*[0-9](/[0-9]*[0-9])?’ for type ‘FrameRateType’.
Line:Col[27:38]:cvc-attribute.3: The value ’24.000′ of attribute ‘frameRate’ on element ‘Representation’ is not valid with respect to its type, ‘FrameRateType’.
Line:Col[37:38]:cvc-pattern-valid: Value ’24.000′ is not facet-valid with respect to pattern ‘[0-9]*[0-9](/[0-9]*[0-9])?’ for type ‘FrameRateType’.
Line:Col[37:38]:cvc-attribute.3: The value ’24.000′ of attribute ‘frameRate’ on element ‘Representation’ is not valid with respect to its type, ‘FrameRateType’.
> 

It expects an integer and not decimal.
It may explain the problem as I can play the video with Bitdash for example.

Thank you for your advice.
Pierre

**Comment by erankor** [comment]
Thanks @marzipi, merged a fix for the frame rate issue to latest master https://github.com/kaltura/nginx-vod-module/pull/255.
However I have tested with Dash-If before and it was working well, so unless they made their code more strict lately, not sure that is the reason it doesn't play

**Comment by marzipi** [comment]
Thank you Eran.
I have done some others test as the previous one focused on Playready(cenc).

Dash-if works fine with DRM cenc on Chrome (widevine) and not on Edge/IE11 (playready).
Without DRM, it works fine on both browsers, so the problem doesn't come from the frame rate parameter...

Playready cenc and your module works fine with Bitdash player.

Do you try dash CENC with dash-if  and Microsoft?
Thank you again
Pierre

**Comment by erankor** [comment]
We are currently using a player by castLabs for DRM playback, as far as I know, it is based on dash-if. But don't think we ever tested dash-if directly with PlayReady DRM

**Comment by erankor** [comment]
Closing this one as it looks like a player issue
