### ISSUE TITLE
mapped rate support on DASH

### ISSUE THREAD

**Issue by frankville** [kaltura/nginx-vod-module#256]
Hi, I would like to know if rate filter is supported for DASH playlist in mapped mode. I tried to use rate filters with DASH but the video becomes like slow motion, like 1 frame per second. I read the docs but I couldn't find anything related to this issue. Thanks

**Comment by erankor** [comment]
Please try the branch centralized-time-scaling, I expect it to solve this issue

**Comment by erankor** [comment]
@frankville, did you try this branch ?

**Comment by frankville** [comment]
Hi @erankor, sorry I couldn't answer sooner. I saw today you merged that branch into master and made a new release, so I downloaded it and I ran some tests playing DASH  with rate filters and everything worked perfect. Hope this helps. Thanks

**Comment by erankor** [comment]
Great, thanks for confirming
