### ISSUE TITLE
Error audio_filter.c file

### ISSUE THREAD

**Issue by Boburjon** [kaltura/nginx-vod-module#257]
Hello, produces an error when adding a module 
OS: ubuntu 12.04
nginx: 1.8.1

> -o objs/addon/filters/audio_filter.o \
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c: В функции «audio_filter_flush_encoder»:
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1061:3: ошибка: «av_free_packet» is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4086) [-Werror=deprecated-declarations]
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c: В функции «audio_filter_read_filter_sink»:
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1147:4: ошибка: «av_free_packet» is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4086) [-Werror=deprecated-declarations]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/filters/audio_filter.o] Ошибка 1
make[1]: Выход из каталога `/tmp/nginx-1.8.1'
make: *** [build] Ошибка 2 

help to solve, thanks in advance!

**Comment by erankor** [comment]
Try to replace av_free_packet with av_packet_unref

**Comment by Boburjon** [comment]
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:58:2: error: unknown type name ‘AVFilterGraph’
  AVFilterGraph *filter_graph;
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:88:2: error: unknown type name ‘AVFilterGraph’
  AVFilterGraph *filter_graph;
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:89:2: error: unknown type name ‘AVFilterInOut’
  AVFilterInOut** outputs;
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:106:2: error: ‘AV_CH_LAYOUT_MONO’ undeclared here (not in a function)
  AV_CH_LAYOUT_MONO,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:107:2: error: ‘AV_CH_LAYOUT_STEREO’ undeclared here (not in a function)
  AV_CH_LAYOUT_STEREO,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:108:2: error: ‘AV_CH_LAYOUT_SURROUND’ undeclared here (not in a function)
  AV_CH_LAYOUT_SURROUND,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:109:2: error: ‘AV_CH_LAYOUT_4POINT0’ undeclared here (not in a function)
  AV_CH_LAYOUT_4POINT0,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:110:2: error: ‘AV_CH_LAYOUT_5POINT0_BACK’ undeclared here (not in a function)
  AV_CH_LAYOUT_5POINT0_BACK,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:111:2: error: ‘AV_CH_LAYOUT_5POINT1_BACK’ undeclared here (not in a function)
  AV_CH_LAYOUT_5POINT1_BACK,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:112:2: error: ‘AV_CH_LAYOUT_7POINT1_WIDE_BACK’ undeclared here (not in a function)
  AV_CH_LAYOUT_7POINT1_WIDE_BACK,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:182:2: error: unknown type name ‘AVFilterGraph’
  AVFilterGraph *filter_graph,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:186:2: error: unknown type name ‘AVFilterInOut’
  AVFilterInOut** outputs)
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:289:2: error: unknown type name ‘AVFilterGraph’
  AVFilterGraph *filter_graph,
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:293:2: error: unknown type name ‘AVFilterInOut’
  AVFilterInOut** inputs)
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c: In function ‘audio_filter_init_sources_and_graph_desc’:
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:605:3: error: implicit declaration of function ‘audio_filter_init_source’ [-Werror=implicit-function-declaration]
   return audio_filter_init_source(
   ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c: In function ‘audio_filter_alloc_state’:
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:654:2: error: unknown type name ‘AVFilterInOut’
  AVFilterInOut *outputs = NULL;
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:655:2: error: unknown type name ‘AVFilterInOut’
  AVFilterInOut *inputs = NULL;
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:722:2: error: implicit declaration of function ‘avfilter_graph_alloc’ [-Werror=implicit-function-declaration]
  state->filter_graph = avfilter_graph_alloc();
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:722:22: error: assignment makes pointer from integer without a cast [-Werror]
  state->filter_graph = avfilter_graph_alloc();
                      ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:763:2: error: implicit declaration of function ‘audio_filter_init_sink’ [-Werror=implicit-function-declaration]
  rc = audio_filter_init_sink(
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:776:2: error: implicit declaration of function ‘avfilter_graph_parse_ptr’ [-Werror=implicit-function-declaration]
  avrc = avfilter_graph_parse_ptr(state->filter_graph, (char*)init_context.graph_desc, &inputs, &outputs, NULL);
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:786:2: error: implicit declaration of function ‘avfilter_graph_config’ [-Werror=implicit-function-declaration]
  avrc = avfilter_graph_config(state->filter_graph, NULL);
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:798:3: error: implicit declaration of function ‘av_buffersink_set_frame_size’ [-Werror=implicit-function-declaration]
   av_buffersink_set_frame_size(state->sink.buffer_sink, state->sink.encoder->frame_size);
   ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:802:2: error: implicit declaration of function ‘av_frame_alloc’ [-Werror=implicit-function-declaration]
  state->decoded_frame = av_frame_alloc();
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:802:23: error: assignment makes pointer from integer without a cast [-Werror]
  state->decoded_frame = av_frame_alloc();
                       ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:809:24: error: assignment makes pointer from integer without a cast [-Werror]
  state->filtered_frame = av_frame_alloc();
                        ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:849:2: error: implicit declaration of function ‘avfilter_inout_free’ [-Werror=implicit-function-declaration]
  avfilter_inout_free(&inputs);
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c: In function ‘audio_filter_free_state’:
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:864:3: error: implicit declaration of function ‘av_free’ [-Werror=implicit-function-declaration]
   av_free(sources_cur->decoder);
   ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:868:2: error: implicit declaration of function ‘avfilter_graph_free’ [-Werror=implicit-function-declaration]
  avfilter_graph_free(&state->filter_graph);
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:869:2: error: implicit declaration of function ‘av_frame_free’ [-Werror=implicit-function-declaration]
  av_frame_free(&state->filtered_frame);
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c: In function ‘audio_filter_read_filter_sink’:
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1104:3: error: implicit declaration of function ‘av_buffersink_get_frame_flags’ [-Werror=implicit-function-declaration]
   avrc = av_buffersink_get_frame_flags(state->sink.buffer_sink, state->filtered_frame, AV_BUFFERSINK_FLAG_NO_REQUEST);
   ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1104:88: error: ‘AV_BUFFERSINK_FLAG_NO_REQUEST’ undeclared (first use in this function)
   avrc = av_buffersink_get_frame_flags(state->sink.buffer_sink, state->filtered_frame, AV_BUFFERSINK_FLAG_NO_REQUEST);
                                                                                        ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1104:88: note: each undeclared identifier is reported only once for each function it appears in
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1134:3: error: implicit declaration of function ‘av_frame_unref’ [-Werror=implicit-function-declaration]
   av_frame_unref(state->filtered_frame);
   ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c: In function ‘audio_filter_process_frame’:
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1210:2: error: implicit declaration of function ‘av_buffersrc_add_frame_flags’ [-Werror=implicit-function-declaration]
  avrc = av_buffersrc_add_frame_flags(source->buffer_src, state->decoded_frame, AV_BUFFERSRC_FLAG_PUSH);
  ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1210:80: error: ‘AV_BUFFERSRC_FLAG_PUSH’ undeclared (first use in this function)
  avrc = av_buffersrc_add_frame_flags(source->buffer_src, state->decoded_frame, AV_BUFFERSRC_FLAG_PUSH);
                                                                                ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c: In function ‘audio_filter_choose_source’:
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1233:3: error: implicit declaration of function ‘avfilter_graph_request_oldest’ [-Werror=implicit-function-declaration]
   ret = avfilter_graph_request_oldest(state->filter_graph);
   ^
/tmp/nginx-vod-module-master/vod/filters/audio_filter.c:1268:3: error: implicit declaration of function ‘av_buffersrc_get_nb_failed_requests’ [-Werror=implicit-function-declaration]
   failed_requests = av_buffersrc_get_nb_failed_requests(sources_cur->buffer_src);
   ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/filters/audio_filter.o] Ошибка 1
make[1]: Выход из каталога `/tmp/nginx-1.4.6'
make: *** [build] Ошибка 2

**Comment by Boburjon** [comment]
> ffmpeg version N-78590-g5590ab4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvidstab
  libavutil      55. 18.100 / 55. 18.100
  libavcodec     57. 24.103 / 57. 24.103
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 32.100 /  6. 32.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by Boburjon** [comment]
Updated with ubuntu 12.04 to 14.04
nginx 1.4.6
ffmpeg installed the latest version and libavfilter Library

Because of that such errors?

**Comment by Boburjon** [comment]
I delete all codecs, ffmpeg, libav-tools and re-assembled, it works!

**Comment by erankor** [comment]
Hi,

Sorry for the delay, the reason for the first error was that you are using a new ffmpeg in which they decided to deprecate this function (and nginx by default does not allow compiler warnings).
The second batch of errors is a bit weird to me, it seems as if nothing is defined in libavfilter.h.
We'll check it out in more detail once we upgrade our ffmpeg version to the latest.
Anyway, when you removed ffmpeg it compiled without the audio filtering feature (the module detects whether ffmpeg is installed) and that's why it worked

Eran
