### ISSUE TITLE
ngx_child_request_wev_handler: unexpected, upstream is null

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#261]
Hi!
Just like in a previous  time https://github.com/kaltura/nginx-vod-module/issues/160
But a newer version nginx-vod-module-master-1.5.2

Here is a config 

        location /pdash/ {
            vod dash;
            vod_mode local;
            vod_moov_cache moov_cache_pdash 512m;
            vod_multi_uri_suffix .urlset;

            vod_drm_enabled on;
            vod_drm_upstream_location /pdash-key;
            vod_drm_request_uri /key.js;

            alias /storage/;

            gzip on;
            gzip_types application/dash+xml;

            expires 600s;
            add_header 'Access-Control-Allow-Origin' '*';
        }
        location /pdash-key/ {
        alias /storage/;
        }

In a storage multibitrate videos and key.js:
[{"pssh": [{"data": "CAESEGMyZjg2MTczN2NjNGYzODIaB2thbHR1cmEiCjBfbmptaWlwbXAqBVNEX0hE", "uuid": "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"}], "key": "GzoNU9Dfwc//Iq3/zbzMUw==", "key_id": "YzJmODYxNzM3Y2M0ZjM4Mg=="}]

When i try to get mpd i see that errors:
2016/03/28 17:55:01 [warn] 18358#0: *2 ngx_child_request_initial_wev_handler: upstream is null while sending response to client, client: 10.130.130.2, server: , request: "GET /pdash/test-,650,950,.mp4.urlset/manifest.mpd HTTP/1.0", subrequest: "/pdash-key/key.js", host: "10.130.130.1"
2016/03/28 17:55:01 [error] 18358#0: *2 ngx_child_request_wev_handler: unexpected, upstream is null while sending response to client, client: 10.130.130.2, server: , request: "GET /pdash/test-,650,950,.mp4.urlset/manifest.mpd HTTP/1.0", host: "10.130.130.1"
2016/03/28 17:55:03 [info] 18358#0: *2 client prematurely closed connection while sending response to client, client: 10.130.130.2, server: , request: "GET /pdash/test-,650,950,,.mp4.urlset/manifest.mpd HTTP/1.0", host: "10.130.130.1"

Client is 10.130.130.2
Server is 10.130.130.1

**Comment by erankor** [comment]
the location `pdash-key` must be a location that uses an upstream (e.g. nginx's builtin `proxy_pass`), using a location that serves files is not supported

**Comment by kuznetcoff777** [comment]
Got it, now it works, thanks a lot.

May i ask a few questions about drm?
I read about how fairplay works. File is encrypted with master.key. Master.key is encrypted with user.key. User downloads file, decrypts master.key with user.key and then decrypts file with master.key 

-Am i correctly understand that other DRM (Widevine, Play Ready, Primetime) works in the same way?
-If encrypted master.key is included with file or it is sent separately from file?
-If it is sent separately (i suppouse it so) then if i correctly understand that for fragmented VOD it is true that (roughly speaking):
----each segment is encrypted with master.key (kaltura module gets it from CENC drm servers)
—-user get a segment (in a manifest there is additional info about key, keyid and drm servers
—-user goes to drm server to get encrypted master.key and user.key
—-user decrypts master.key and then decrypts file itself.

**Comment by AquileaSFX** [comment]
Hello @kuznetcoff777 

excuse me, would you please tell me how you solved the upstream thing?
I'm trying to put the json in a location just like you did, but I can't get it to work

thank you!

**Comment by kuznetcoff777** [comment]
@AquileaSFX 

```
 location /pdash/ {
            vod dash;
            vod_mode local;
            vod_moov_cache moov_cache_pdash 512m;
            vod_multi_uri_suffix .urlset;



            vod_drm_enabled on;
            vod_drm_upstream_location pdash-key-drm;
            vod_drm_request_uri /pdash-key/key.js;

            alias /storage/;

            gzip on;
            gzip_types application/dash+xml;

            expires 600s;
            add_header 'Access-Control-Allow-Origin' '*';
        }
        location pdash-key-drm {
        proxy_pass http://127.0.0.1/;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        }
        location /pdash-key/ {
        alias /storage/;
        }

```

**Comment by AquileaSFX** [comment]
@kuznetcoff777 

Thank you!!!

**Comment by erankor** [comment]
1. I'm not familiar with the details of how the key is transferred in each DRM technology, maybe @noam-arad can add more detail
2. The encryption key is not included in the output stream in any form, it is sent separately usually in the form of a license response
3. Your description of the flow looks correct, the additional info (key id, pssh) can be in the manifest and/or in the init segment (in case of DASH)

**Comment by kuznetcoff777** [comment]
Ok, thanks, 
-am i correctly understand that with help of mpeg-dash CENC (with your module) and drm service (like ezdrm) i can encrypt my VOD with Adobe Access, Microsoft PlayReady, and Google Widevine DRM?
-is there any success story you know who used your module and encrypted VOD with minimum 2 DRM CENC, or even all 3 DRM was used simultaneously?

**Comment by erankor** [comment]
We don't work with any DRM services like ezdrm, we have our own implementation, so can't comment about that, my guess is that it will be fine.
What I can say, is that the implementation of the encryption is correct, we successfully played all the following configurations:
1. DASH/CENC with PlayReady & Widevine PSSH together
2. MSS PlayReady
3. HLS FairPlay

**Comment by kuznetcoff777** [comment]
Yep, i just called ezdrm as an example.
Will you try to use also Adobe Primetime DRM?

**Comment by erankor** [comment]
It's in our roadmap

**Comment by kuznetcoff777** [comment]
Will it be described somehow (i mean how we will know about that test was successful?)

**Comment by erankor** [comment]
I can add a list of tested configurations in the DRM section in the readme

**Comment by kuznetcoff777** [comment]
It would be fine, thank you very much for the answers and a great job!

**Comment by noam-arad** [comment]
Hן @kuznetcoff777 ,
Regarding your questions about FPS and other DRMs.
Widevine and Playready (not sure about Primetime) don't expose exactly what they do with the key during transfer from the license server to the player but I assume it's very similar.
Since google and microsoft provide you with a license server or SDK we don't really know about the protocol of transferring the key to the CDM, just that it is encrypted somehow during the transfer.

Like you said they all encrypt the file with something you might call a "master.key".
When someone wants to decrypt the file the CDM sends a request with a random key, the request is encrypted with a public certificate of the encrypter. The encrypter returns the key encrypted with the random key given so only the CDM can open and see the key decrypted and only it can un-encrypt the file.

**Comment by kuznetcoff777** [comment]
@noam-arad
Thank you very much for response, it really helped me.
