### ISSUE TITLE
Trouble understanding simulated live streaming and mapped mode.

### ISSUE THREAD

**Issue by aronroberts** [kaltura/nginx-vod-module#263]
Hello,

I'm trying to configure NGINX + nginx-vod-module to do a simulated live stream via mapped mode. I admit I am new to NGINX config and many of my questions are almost certianly due to my limited knowledge of nginx config concepts. I am ReadingTFM as quickly as possible. The ultimate goal is to write something that allows a user to  begin listening to our stream at any arbitrary time within the last two weeks.  We are looking to replace a system here: [KEXP Streaming Archive](http://www.kexp.org/archive)   (This may or may not work when you try it which is why I am trying to replace it)

Background on what I am trying to do as a sanity check:  

I have 15 minute chunks of AAC audio generated by a Wowza server recording our live stream. They are named with timestamps and segment numbers but for the purposes of my test I have named them stream_chunk_1.mp4 through stream_chunk_10.mp4

chunks are in a directoiry named 'data' under the nginx root ('/usr/local/nginx/' at the same level as the 'html' dir)

I have an upstream server that currently returns a static json object (basically a modified version the example) as I am not sure what the date values are precisely refering to. (Obviously returning seconds since the epoch is not an issue I just don't know if the values should be now() or something else like now() + duration offset or similar) I can easily generate it dynamically but don't know the right values.

The test server is currenty an Ubuntu 14.04 VM on my workstation with the upstream server running directly on my workstation. 

I was hoping to get to the point where I could see some attempts to hit the upstream server and route appropriately for the requests from vod module.

So basically: 

I am 100% sure my nginx configuration is wrong.
I don't really know how to construct the URL for mapped mode.
I don't know what portion of the URL is passed to the upstream server.
I don't know if I am returning the proper JSON from the upstream server.
I'm not even sure my AAC chunks are reachable from the location configured.

I'm sorry for being this useless but I would happily write up this up as example documentation if I can get this working.

IP numbers
```
upstream: 192.168.44.1
nginx server: 192.168.44.132
```

nginx -V
```
root@nginx-test-1404:/usr/local/nginx/conf# /usr/local/nginx/sbin/nginx -V
nginx version: nginx/1.9.13
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
configure arguments: --add-module=../nginx-vod-module --with-file-aio --with-threads --with-cc-opt=-O3

```

nginx.conf
```
#user  nobody;
worker_processes  1;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log  logs/error.log  info;

pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

http {
    upstream api{
        server 192.168.44.1:8080;
    }

    # upstream fallback {
    #     server fallback.kaltura.com:80;
    # }

    server {
        # vod settings
        vod_mode mapped;
        vod_upstream_location /api;
        vod_upstream_extra_args "pathOnly=1";
        # vod_fallback_upstream_location /fallback;
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;

        # vod caches
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;
        vod_mapping_cache mapping_cache 5m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        # file handle caching / aio
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        aio on;

         # location ^~ /fallback/ {
         #    internal;
         #    proxy_pass http://fallback/;
         #    proxy_set_header Host $http_host;
         # }

	location /data/ {
	    root data;
        }

        location ^~ /api/ {
            internal;
            proxy_pass http://api/;
            proxy_set_header Host $http_host;
        }

        location ~ ^/p/\d+/(sp/\d+/)?serveFlavor/ {
            # encrypted has
            vod hls;
            # vod_secret_key "mukkaukk$vod_filepath";
            # vod_hls_encryption_method aes-128;

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
    }
}
```

sample json

`
{
    "sequences": [
        {
        "clips": [
            {"type": "source", "path": "/data/stream_chunk_1.mp4"}, 
            {"type": "source", "path": "/data/stream_chunk_2.mp4"}
            ]
        }
    ], 
    "discontinuity": false, 
    "playlistType": "live", 
    "durations": [900000, 900000], 
    "firstClipTime": 1451917506000, 
    "segmentBaseTime": 1451904060000
}
`

**Comment by erankor** [comment]
RTFM is always a good approach :) 
Anyway, I suggest the following to get you started - 
1. Take this sample PHP script https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php and host it on some web server. I'm using Apache with mod_php for this, but you can use nginx with fastCGI if you prefer, whatever is easiest for you to set up. I place the PHP script in a folder called `mapped` under the document root. 
2. Update the mp4 file paths inside the sample php to the absolute paths of a few MP4 files, and set the path of the ffprobe executable. If you don't have ffprobe, you can edit the PHP script and fill out the $durations variable manually with the durations of the MP4 files (in milliseconds). Here is a sample request showing how it looks like on my environment:
```# curl http://localhost/mapped/playlist.php/disc/0/type/live
{"firstClipTime":1459363105386,"segmentBaseTime":1459362939288,"discontinuity":false,"playlistType":"live","durations":[83049,83049,83049,83049],"sequences":[{"clips":[{"type":"source","path":"\/web\/content\/r71v1\/entry\/data\/241\/803\/0_p7y00o7h_0_93j6yqit_1.mp4"},{"type":"source","path":"\/web\/content\/r71v1\/entry\/data\/241\/803\/0_p7y00o7h_0_93j6yqit_1.mp4"},{"type":"source","path":"\/web\/content\/r71v1\/entry\/data\/241\/803\/0_p7y00o7h_0_93j6yqit_1.mp4"},{"type":"source","path":"\/web\/content\/r71v1\/entry\/data\/241\/803\/0_p7y00o7h_0_93j6yqit_1.mp4"}]}]}```
3. Configure nginx with a config similar to this (this is not a full config, but it shows the relevant parts):
```
http {
	upstream kalapi {
			server localhost;
	}

	server {
		listen     8001;
		
		vod_mode mapped;
		vod_upstream_location /kalapi_proxy;
		vod_max_mapping_response_size 64k;

		location ^~ /kalapi_proxy/ {
			internal;
			proxy_pass http://kalapi/;
			proxy_set_header Host $http_host;
		}
		
		location /mapped/ {
			vod hls;
			vod_align_segments_to_key_frames on;
			vod_live_segment_count 10;
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
		}
	}
}
```
I have the nginx listening on port 8001 and the Apache on port 80, with the above config, when I curl `http://localhost:8001/mapped/playlist.php/disc/0/type/live/index.m3u8` nginx-vod curls `http://localhost/mapped/playlist.php/disc/0/type/live`, gets the JSON and returns the HLS stream.
Here's how it looks like:
```
# curl -s http://localhost:8001/mapped/playlist.php/disc/0/type/live/index.m3u8 | head
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:137
#EXTINF:10.000,
http://localhost:8001/mapped/playlist.php/disc/0/type/live/seg-137-v1-a1.ts
#EXTINF:10.000,
http://localhost:8001/mapped/playlist.php/disc/0/type/live/seg-138-v1-a1.ts
#EXTINF:10.000,
```

Hope this helps...

**Comment by aronroberts** [comment]
Thank you this was very helpful. I tried to run the PHP script but for some reason (probably because I haven't used php since version 1), I kept getting Out Of Memory errors.  However it had enough information to translate the script to python and make a rudimentary django view. I still have a bit more to do but this has definitely gotten me on the right path.  Thanks Again!

**Comment by tabital0** [comment]
I decided to start over by using this example instead, but i get an error for "vod_max_mapping_response_size 10;" not being a valid function and bad gateway for finding playlist.php. For the backend server i use php which has APC installed http://localhost:11831/playlist.php. I don't understand why the other example can recognize it but fails to play and this perfect example fails to trace my playlist,php could it be outdated perhaps?

**Comment by erankor** [comment]
"vod_max_mapping_response_size 10;" - 10 bytes?

**Comment by tabital0** [comment]
Sorry i meant "vod_live_segment_count 10;". Is the only one i could not implement in my config file

**Comment by tabital0** [comment]
I don't know what to do anymore. Please help me. I still get 502 Bad Gateway error after typing in curl https://localhost:8888/mapped/playlist.php/disc/0/type/live/index.m3u8
This is the code i copied and my backend server handling key.json and playlist.php and playlist.json:
------------------------------------------------------------------------
worker_processes  1;

error_log  /var/log/nginx/error.log debug;
pid		/var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    upstream kalapi {
            server localhost:11831;
    }

    server {
        listen  8888 ssl;
		ssl_certificate /ssl/fullchain.pem;
		ssl_certificate_key /ssl/privkey.pem;		
		ssl_dhparam /ssl/dhparam.pem;

        vod_mode mapped;
        vod_upstream_location /kalapi_proxy;
        vod_max_mapping_response_size 64k;

        location ^~ /kalapi_proxy/ {
            internal;
            proxy_pass http://kalapi/;
            proxy_set_header Host $http_host;
        }

        location /mapped/ {
            vod hls;
            vod_align_segments_to_key_frames on;
            vod_live_window_duration 20;
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
        }
    }
#######################################################################################################################
#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#
#######################################################################################################################
	server {
		#server_name cdn.2432615184.com;
		listen 11831;
		#listen 11831 ssl;
		#ssl_certificate /ssl/fullchain.pem;
		#ssl_certificate_key /ssl/privkey.pem;		
		#ssl_dhparam /ssl/dhparam.pem;
		
		location /xmltv.xml {
			root /home/www/xmltv;
			try_files /xmltv.xml =404;
		}

		location /key.json {
			root /opt/static/keys;
			try_files /key.json =404;
		}
		
		location /playlist.json {
			root /opt/static/json;
			try_files /playlist.json =404;
		}

		location / {
			root /usr/local/nginx/html;
			try_files $uri /index.php$is_args$args;
			index  index.php index.htm;
		}
	
		location ~ ^/.+\.php(/|$) {
			# Pass the request to the host "php" and port 9000 (default PHP-FPM port).
			# The "php" host name is generated from the application name in the
			# Docker Compose file that was previously defined.
			fastcgi_pass  php:9000;
			# Include the default NGINX FastCGI Parameters
			include       fastcgi_params;
			# Define one additional parameter telling PHP-FPM where to find the file
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
		
		location ~ /\.ht {
			deny  all;
		}
	}
}
------------------------------------------------------------------------

**Comment by tabital0** [comment]
i don't know what to do anymore. Please help me? I still get 502 Bad Gateway error after tyrping
curl http://localhost:8888/mapped/playlist.php/disc/0/type/live/index.m3u8. 
This is the code i copied and my backend server handling key.json and playlist.php

-------------------------------------------------------
worker_processes  1;

error_log  /var/log/nginx/error.log debug;
pid		/var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
	include	   mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
		'$status $bytes_sent $request_time "$http_referer" '
		'"$http_user_agent" "$http_x_kaltura_f5_https" $http_x_kaltura_f5_remote_addr '
		'"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
		'$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
		'"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
		'$connection ';

	access_log /var/log/nginx/access.log main;

    upstream kalapi {
            server localhost:11831;
    }

    server {
        listen  8888 ssl;
		ssl_certificate /ssl/fullchain.pem;
		ssl_certificate_key /ssl/privkey.pem;		
		ssl_dhparam /ssl/dhparam.pem;

		# vod settings
        vod_mode mapped;
		vod_max_mapping_response_size 64k;
        vod_upstream_location /kalapi_proxy;
        vod_upstream_extra_args "pathOnly=1";
        # vod_fallback_upstream_location /fallback;
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;

        # vod caches
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;
        vod_mapping_cache mapping_cache 5m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        # file handle caching / aio
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        aio on;

        location ^~ /kalapi_proxy/ {
            internal;
            proxy_pass http://kalapi/;
            proxy_set_header Host $http_host;
        }

        location /mapped/ {
            vod hls;
            vod_align_segments_to_key_frames on;
            vod_live_window_duration 20;
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
        }
    }
#######################################################################################################################
#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#=#-#
#######################################################################################################################
	server {
		listen 11831;
		
		location /xmltv.xml {
			root /home/www/xmltv;
			try_files /xmltv.xml =404;
		}

		location /key.json {
			root /opt/static/keys;
			try_files /key.json =404;
		}
		
		location /playlist.json {
			root /opt/static/json;
			try_files /playlist.json =404;
		}

		location / {
			root /usr/local/nginx/html;
			try_files $uri /index.php$is_args$args;
			index  index.php index.htm;
		}
	
		location ~ ^/.+\.php(/|$) {
			# Pass the request to the host "php" and port 9000 (default PHP-FPM port).
			# The "php" host name is generated from the application name in the
			# Docker Compose file that was previously defined.
			fastcgi_pass  php:9000;
			# Include the default NGINX FastCGI Parameters
			include       fastcgi_params;
			# Define one additional parameter telling PHP-FPM where to find the file
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
		
		location ~ /\.ht {
			deny  all;
		}
	}
}
-------------------------------------------------------

**Comment by erankor** [comment]
As I wrote on the other thread - check the nginx error log!!!
Without looking at the error log, we can continue guessing here for years...

**Comment by tabital0** [comment]
This is the portion of the error as its output.

2022/11/28 14:24:09 [debug] 8#8: *1 http output filter "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1"
2022/11/28 14:24:09 [debug] 8#8: *1 http copy filter: "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1"
2022/11/28 14:24:09 [debug] 8#8: *1 http postpone filter "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1" 0000564F0C210D88
2022/11/28 14:24:09 [debug] 8#8: *1 http postpone filter in memory
2022/11/28 14:24:09 [debug] 8#8: *1 http postpone filter in memory 16 bytes
2022/11/28 14:24:09 [debug] 8#8: *1 http copy filter: 0 "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1"
2022/11/28 14:24:09 [debug] 8#8: *1 pipe write downstream done
2022/11/28 14:24:09 [debug] 8#8: *1 event timer: 12, old: 1723549758, new: 1723549867
2022/11/28 14:24:09 [debug] 8#8: *1 http upstream exit: 0000000000000000
2022/11/28 14:24:09 [debug] 8#8: *1 finalize http upstream request: 0
2022/11/28 14:24:09 [debug] 8#8: *1 finalize http proxy request
2022/11/28 14:24:09 [debug] 8#8: *1 free rr peer 1 0
2022/11/28 14:24:09 [debug] 8#8: *1 close http upstream connection: 12
2022/11/28 14:24:09 [debug] 8#8: *1 free: 0000564F0C26EA60, unused: 48
2022/11/28 14:24:09 [debug] 8#8: *1 event timer del: 12: 1723549758
2022/11/28 14:24:09 [debug] 8#8: *1 reusable connection: 0
2022/11/28 14:24:09 [debug] 8#8: *1 http upstream temp fd: -1
2022/11/28 14:24:09 [debug] 8#8: *1 http output filter "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1"
2022/11/28 14:24:09 [debug] 8#8: *1 http copy filter: "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1"
2022/11/28 14:24:09 [debug] 8#8: *1 http postpone filter "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1" 00007FFE794732B0
2022/11/28 14:24:09 [debug] 8#8: *1 http postpone filter in memory
2022/11/28 14:24:09 [debug] 8#8: *1 http copy filter: 0 "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1"
2022/11/28 14:24:09 [debug] 8#8: *1 http finalize request: 0, "/kalapi_proxy/mapped/playlist.php/disc/0/type/live?pathOnly=1" a:1, c:2
2022/11/28 14:24:09 [debug] 8#8: *1 ngx_child_request_finished_handler: error code 0
2022/11/28 14:24:09 [debug] 8#8: *1 http wake parent request: "/mapped/playlist.php/disc/0/type/live/index.m3u8?"
2022/11/28 14:24:09 [debug] 8#8: *1 http posted request: "/mapped/playlist.php/disc/0/type/live/index.m3u8?"
2022/11/28 14:24:09 [error] 8#8: *1 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 172.22.0.1, server: , request: "GET /mapped/playlist.php/disc/0/type/live/index.m3u8 HTTP/1.1", host: "cdn.2432615184.com:8888"
2022/11/28 14:24:09 [debug] 8#8: *1 ngx_http_vod_handle_read_completed: read failed 502
2022/11/28 14:24:09 [debug] 8#8: *1 http finalize request: 502, "/mapped/playlist.php/disc/0/type/live/index.m3u8?" a:1, c:1
2022/11/28 14:24:09 [debug] 8#8: *1 http special response: 502, "/mapped/playlist.php/disc/0/type/live/index.m3u8?"
2022/11/28 14:24:09 [debug] 8#8: *1 http set discard body
2022/11/28 14:24:09 [debug] 8#8: *1 HTTP/1.1 502 Bad Gateway

**Comment by erankor** [comment]
So you can see that the error is -
2022/11/28 14:24:09 [error] 8#8: *1 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 172.22.0.1, server: , request: "GET /mapped/playlist.php/disc/0/type/live/index.m3u8 HTTP/1.1", host: "cdn.2432615184.com:8888"

Meaning - the module tried to call the upstream to get the JSON, and it got error 404. So you need to fix that... 
This is no longer related to this module, it's about configuring nginx with php...

**Comment by tabital0** [comment]
JSON file of the playlist.php? Cause port 8888 is open but not the backend port 11831.

**Comment by kisso** [comment]
hi, can i use this feature to play one video live at 8PM? and end it on 8:30PM? video has duration 30 minutes, also want to be live and disable rewind, when watcher open link at 8:20PM I want it to be shifted 20 minutes
