### ISSUE TITLE
Concat filter

### ISSUE THREAD

**Issue by Classsic** [kaltura/nginx-vod-module#264]
Hi, I want to know exactly what  this filter works, I need generate a mp4 files from multiple clips, and download as mp4 file.
Right now, we use mapping (sequence). for generete a m3u8 playlist.
Thanks.

**Comment by erankor** [comment]
This feature is not supported.
Concat filter is very similar to using multiple clips with discontinuity set to false, the added value it provides is that the duration of the mp4s can be different across different sequences.

**Comment by khaliullov** [comment]
@erankor, is it still impossible to produce concatenated mp4 from several mp4 chunks?

**Comment by erankor** [comment]
yes
