### ISSUE TITLE
hls captions

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#265]
Hi! A few questions:

1-when i lauch hls vod - in a player i see that there is some "Unknown CC" subs exists. I dont see anythng in a playlist. Then  I found it - https://developer.apple.com/library/ios/qa/qa1801/_index.html. So is there any way to add this function in a module to disable this "Unknown CC" subs 

2-is there any way to add support of webvtt subs (For example - there are several videos Video-1, Video-2, Video 3 with different bitrates and additional file of subs Video-srt.srt, so request for master playlist will be http://IP_OF_SERVE/LOCATION/Video-,1,2,3,srt,.mp4.urlset/master.m3u8) and module will make webvtt from srt on-the-fly.

**Comment by erankor** [comment]
1. Not sure there's anything we can do about it on the server, I bumped into this post http://stackoverflow.com/questions/21442708/turn-closed-captioning-button-off-for-streaming-videos-m3u8-file-on-ios that explains how to hide it with JavaScript, you can try it out
2. We have this feature in our core server (https://github.com/kaltura/server/). Support for captions is currently not planned for this module

**Comment by kuznetcoff777** [comment]
Got it, thanks.

**Comment by sdahdaah** [comment]
Hello, any chance this feature was added recently so we can turn off closed captions on HLS for iOS?
