### ISSUE TITLE
DASH not working with Shaka Player

### ISSUE THREAD

**Issue by sergiyshutov** [kaltura/nginx-vod-module#266]
Dear erankor vod dash not working with Shaka Player.
https://github.com/google/shaka-player

Can you please check this?
Big thanks :)

**Comment by erankor** [comment]
Well, it is working perfectly for me, e.g.: `http://cfvod.kaltura.com/dasha/p/2035982/sp/203598200/serveFlavor/entryId/0_puvhjpxq/v/22/pv/5/flavorId/0_,xyk0awp0,lk97458b,ldfm75gt,zshpgvbw,/forceproxy/true/name/a.mp4.urlset/manifest.mpd`

Please send the URL that does not work.

Also, you can try setting `vod_align_segments_to_key_frames` to `on` in your conf, even though I don't have your stream, my guess is that this would be the answer.

**Comment by sergiyshutov** [comment]
Dear erankor. You right, it works (your's stream). Seems something wrong in my config file. I close this issue right now.
Big thanks :)
