### ISSUE TITLE
segments duration != video.duration

### ISSUE THREAD

**Issue by nknighter** [kaltura/nginx-vod-module#272]
Hello, in manifest.mpd we have this structure:

```
 <SegmentTimeline>
                <S d="1000"/>
                <S d="4000" r="49"/>
                <S d="2167"/>
 </SegmentTimeline>
```

So, total duration of segments should be 1000 + 4000 * 49 + 2167 = ~199167, but real video duration is ~203000. My thought is that "r" attribute is smaller than real.

**Comment by erankor** [comment]
your calculation is wrong, it should be `1000 + 4000 * 50 + 2167 = 203167`
from the dash specification:
```The SegmentTimeline element shall contain a list of S elements each of which describes a sequence of contiguous segments of identical MPD duration. The S element contains a mandatory @d attribute specifying the MPD duration, an optional @r repeat count attribute specifying the number of contiguous Segments with identical MPD duration minus one and an optional @t time attribute. The value of the @t attribute minus the value of the @presentationTimeOffset specifies the MPD start time of the first Segment in the series.```
(number of segments minus one)

**Comment by nknighter** [comment]
Okey, Thanks! Its clear now, will keep doing +1 to "r" attribute :)
