### ISSUE TITLE
How can I configure On-the-fly repackaging of MP4 files to MSS?

### ISSUE THREAD

**Issue by Natinux** [kaltura/nginx-vod-module#284]
Can I make it work with just this module with Adaptive bitrate support?

Thanks

**Comment by erankor** [comment]
You can take one of the sample hls configurations, and change `vod hls` to `vod mss`.
Other than that you'll probably want to add these parameters:
```
		vod_segment_duration 4000;
		vod_align_segments_to_key_frames on;
```

**Comment by Natinux** [comment]
Thank you.
Its seems that the xml have only one bitrate .
There is no need to define the bitrate in advance?

**Comment by erankor** [comment]
Not sure I understand the question, the module figures out the bitrate from the mp4 file, you don't need to input it manually.
If your question was about adaptive bitrate, then you need to use either multi url (https://github.com/kaltura/nginx-vod-module/#multi-url-structure) or a mapping JSON (https://github.com/kaltura/nginx-vod-module/#adaptive-set) to do that

**Comment by Natinux** [comment]
Thank you!

Yes I was talking about adaptive bitrate.
Can you please help me understand the prefix, middle and postfix in the multi url section? 

If I understand its correctly, I need to decode the original in advance. right?

Assume I have the following files:
```
sintel-480.mp4
sintel-720.mp4
sintel-1080.mp4
```
How the url should be structured?

**Comment by erankor** [comment]
Yes, you need to prepare the mp4 files in advance, if the urls of the separate files are:
```
http://yourdomain/path/sintel-480.mp4/manifest
http://yourdomain/path/sintel-720.mp4/manifest
http://yourdomain/path/sintel-1080.mp4/manifest
```
then the combined url would be:
```
http://yourdomain/path/sintel-,48,72,108,0.mp4.urlset/manifest
```

**Comment by Natinux** [comment]
Thank you very much!
