### ISSUE TITLE
Start error - failed to initialize the segmenter

### ISSUE THREAD

**Issue by soufrk** [kaltura/nginx-vod-module#291]
After long time I am back to this space on github. Whenever I start nginx `sbin/nginx -c conf/nginx.conf`, an error like below is displayed,

`nginx: [emerg] failed to initialize the segmenter -1000 in /usr/local/nginx/conf/nginx.conf:133`

I tried lots of combinations, recompilation, switch to 1.9.7, and it turns out whenever I am introducing VOD configurations, it skips to the end of the file. Saw this piece of String in your code, did not read through further. I guess you would be able tell right away, the cause for this.

**Comment by erankor** [comment]
you probably configured an invalid segment duration, it should be at least 500 (ms)

**Comment by soufrk** [comment]
Following is my configuration,

```
location /content {
    vod hls;
    vod_mode local;
    #vod_moov_cache moov_cache 512m;
    vod_segment_duration 30;

    root /var;
    gzip on;
    gzip_types application/vnd.apple.mpegurl;
    expires 100d;
}
```

**Comment by erankor** [comment]
so... it's as I wrote... if you intended to use 30 seconds you should have used 30000.
it is clearly stated here: https://github.com/kaltura/nginx-vod-module/#vod_segment_duration

**Comment by soufrk** [comment]
Ok, method parameters have changed I guess. As always, thank you for your valuable time.
