### ISSUE TITLE
delay while preparing .ts files

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#292]
Hi!
We made a test scheme, let me describe step-byt-step the vision of how it works
1-request from client for .ts (10 seconds segments, most of them with high bitrate about 4 mbit/s)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
2-nginx:80
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
3-local proxy cache (if not found such .ts)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
4-local porxy nginx:8080 (kaltura module)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
5-range request to remote storage nginx:80
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
6-range response to proxy nginx:8080 (kaltura module)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
7-kaltura module preparing .ts file 
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
8-.ts file goes to nginx:80 (simultaneously it writes to local proxy cache) and then to the client.

On step 7-8 sometimes i see as proxy kaltura module anwers with 5-10 seconds delay (access log $request_time). Also i see that remote storage answers to module pretty fast (less then 1 seconds).
So i try to understand the reason of such delays (i monitor processor load it is not heavy and have large reserve)
Can you explain how module works in remote mode? I mean when it gets range response - does it store that response in memory or on disk while preparing .ts file from it?

**Comment by erankor** [comment]
The module does not write anything to disk, it is all in memory. 
I didn't fully understand what you're trying to do, but in general, if you can install this module near the storage it would be better. The reason is that the module needs to read the full metadata (moov atom) of the mp4 file before it can service any request, and reading it can take time. For example, if you have a request for a master.m3u8 with 6 rendition, the module has to read the metadata of the 6 files before it can generate the response (it needs to know the bitrate, resolution etc.).
It is therefore highly recommended to enable caching of the metadata (vod_metadata_cache) if you don't do that already.

**Comment by kuznetcoff777** [comment]
We are trying to implement your module and prepeare for the users get the highest quality. I got your idea, that means that while this cache is off, kaltura module with every .ts request asked backend storage for moov atom (but to say the truth i didnot see any repeatable range requests for the same beginning of the file ranges (where moov atom locates)) - maybe there is some default small cache (is not it?). Anyway, somehow vod_metadata_cache was turned off, i just turned it on and put 4 gigs (i think it will be good for the beginning). Thanks for the idea.

**Comment by kuznetcoff777** [comment]
So, here is the point:
vod_metadata_cache = 4096m (i have additional question - if i choose another size should i restart or just reload is enough?)
and i see in logs as user gets ts files from one dedicatet video rile (so i assume that moov atom is in cache already) and after a while i see as the same user asks for another ts from the same video file and gets 10 seconds delay in preparing this ts file. Is there any way to monitor size consumption of vod_metadata_cache and if it is possible to somehow check if dedicated file moov atom is in that cache?

**Comment by kuznetcoff777** [comment]
Also i noticed periodical alerts like this "zero size buf in output t:0 r:0 f:0 00000000021938B0 00000000021938B0-00000000021948B0 0000000000000000 0-0 while sending to client".
I enlarged output_buffers but it seems to be did not help...

**Comment by erankor** [comment]
As I recall, reload is enough. 
You can see size of all the caches as well as hit/miss ratio and other statistics by setting a location with https://github.com/kaltura/nginx-vod-module/#vod_status. I would also recommend setting up https://github.com/kaltura/nginx-vod-module/#vod_performance_counters which can give you a breakdown of where the execution time goes.
Also, if you haven't do so already, I suggest going over https://github.com/kaltura/nginx-vod-module/#performance-recommendations, some of the recommendations there can have a significant effect

**Comment by kuznetcoff777** [comment]
Thanks for response, i take a break for several days, after a while i will write about how it goes

**Comment by kuznetcoff777** [comment]
@erankor, hi again, is there any detailed description for all items in that counters? I can guess several, but i want to be sure at 100%.

**Comment by kuznetcoff777** [comment]
For example:
<build_manifest>
<sum>13107</sum>
<count>1232</count>
<max>95</max>
<max_time>1462878428</max_time>
<max_pid>32355</max_pid>
</build_manifest>

What is sum? - that means that 13107 manifests was done since restart of module?
Then what is count?
what is max? - maximum simultanious bulit mainfests by pid 32355 in unix time 1462878428?

**Comment by erankor** [comment]
* sum - total time spent on the specific task in micro seconds since nginx restart / stats reset
* count - total number of samples collected
* max - largest (slowest) sample, in this case, the slowest 'build manifest' took 95 micro seconds 
* max_time / max_pid - the unix timestamp / process id in which 'max' was observed, can be used to correlate the stats with the access log, although it may not be enough to uniquely identify the request

**Comment by kuznetcoff777** [comment]
Here is what i figured out, most of timeouts that i described earlier (upstream timed out (110: Connection timed out) while reading upstream) happens in the same way:
for example client asks for segments:
...
60
61
62
63
64
65
66
65
67
...


2 times was asked 65 segment:
When i look at access log and greped by that 65 segment (put next lines in notepad++ to be more readable, log format is `[$time_local] 		$request_method "$scheme://$http_host$request_uri  $server_protocol $status $body_bytes_sent $sent_http_content_length complete=$request_completion $request_time  		"upaddr=$upstream_addr" "upstatus=$upstream_status" "uplen=$upstream_response_length"   "uptime=$upstream_response_time" "start=$arg_start" "range_req=$http_range"     "range_resp=$sent_http_content_range"`) :

```
[10/May/2016:16:37:40 +0300] GET "https://ip-server/test.mp4/seg-65-v1-a1.ts" HTTP/1.1 206 		3628280 		3628280 					complete=OK 				0.844    			"upaddr=127.0.0.1:8080" "upstatus=200" 				"uplen=4840248" 					"uptime=0.289" 						"start=-" 		"range_req=bytes=1211968-"  "range_resp=bytes 1211968-4840247/4840248"   

[10/May/2016:16:37:50 +0300] GET "https://ip-server/test.mp4/seg-65-v1-a1.ts" HTTP/1.1 200 		1211968 		4840248 					complete=   				13.750   			"upaddr=127.0.0.1:8080" "upstatus=200" 				"uplen=1227128" 					"uptime=13.750"						"start=-" 		"range_req=-" 				"range_resp=-" 

```

We can see 2 responses, one of them wokred fast, another worked for 13 seconds.

So i can see that client asks for full range "range_req=-" and got from module only 1227128 of necessary 4840248 (for 13,75 seconds -it means  that real request was sent at 16:37:36 and ended at 16:37:50). Also client asks for rest bytes (at 16:37:40) with "range_req=bytes=1211968-" and got 3628280 of necessary 3628280 bytes (for 0.289 seconds)

Then i looked at access logs of proxy (kaltura module which works in remote mode as i described in the beginning):
```

[10/May/2016:16:37:40 +0300] GET "https://ip-server/test.mp4/seg-65-v1-a1.ts" HTTP/1.1 200 		4840248 		4840248 					complete=OK 				0.300 				"upaddr=-" 				"upstatus=-" 				"uplen=-" 							"uptime=-" 							"start=-" 		"range_req=-" 				"range_resp=-" 
[10/May/2016:16:37:50 +0300] GET "https://ip-server/test.mp4/seg-65-v1-a1.ts" HTTP/1.1 200 		1227128 		4840248 					complete= 					13.750 				"upaddr=-" 				"upstatus=-" 				"uplen=-" 							"uptime=-" 							"start=-" 		"range_req=-" 				"range_resp=-" 

```
I looked for the remote storage and i saw normal multiple range responses that took one second for the answer for that request from vod-module. 

There was only one limit on front-end rate=20r/s, i updated it to 50r/s. And still the same problem appears (about 30 errors per 10 minutes while 120 users are active).

If i see the last problem at now, then i check performance counter and see all max_time, the latest is about 4-5 minutes back, so i suppose this counter give me nothing in this situation. The metadata and repsonse cache are not filled, so no any evicts happen.

What could be the reason of such behaviour?

**Comment by erankor** [comment]
I'm sorry but I can't really say anything intelligent based on the info you provided.
I suggest you will enable nginx debug logs (requires compilation with `--with-debug` and adding `debug` to the `error_log` directive) and maybe then you will be able to see on what the time is being spent

**Comment by kuznetcoff777** [comment]
I supposed that i provided a lot of info...
I will try to make debug error log, but i suppose there will be nothing valuable, cause it is common timeout error, there somthing with the module, it just possible if module will write soemthig in error log...

**Comment by kuznetcoff777** [comment]
I have just changed proxy_read_timeout to 20 seconds, so now i see that such timeouts happen with 20-30 seconds delay. Than means that for 20-30 seconds no any new byte of info came from vod module, it is very very odd.

**Comment by erankor** [comment]
Is there a request for it consistently happens ? can you capture a slow request with tcpdump ?

**Comment by kuznetcoff777** [comment]
Nope, always different with different files, and most of them are not initial segments (so that means that moov atom is already in cache). I will try to emulate this on client side and catch tcpdump.

**Comment by erankor** [comment]
I would like to look at a tcpdump of what came out of nginx-vod, as I understand your setup, if you will capture it on the client it will show what came out of the proxy which can be misleading

**Comment by kuznetcoff777** [comment]
my setup is 
client -> server1 (front :80) -> server1 proxy vod module :8080 (remote mode with proxy cache) -> server2 (backend:80)

Ok, i will try to catch at loopback interface

**Comment by kuznetcoff777** [comment]
[mix-kaltura.txt](https://github.com/kaltura/nginx-vod-module/files/260823/mix-kaltura.txt)
I left one user (me) and i did not manage to repeat problem and catch tcpdump yet...
But i managed to catched debug error kaltura log while problem appears (when was several users and several files opened) and part of this log is in attach (in the head is request from kaltura access log, where we can see that 10 seconds took for processing request)
In error log i can see that request came in at 22:27:51 and at 22:227:52 is over http finalize request: 0, "/test.mp4/seg-50-v1-a1.ts?" a:1, c:1
And after that we can see that at 22:28:02 request is over again (but by timeout)

It seems to be that vod module anwers to nginx fronted but somethig going wrong.

**Comment by kuznetcoff777** [comment]
I attempted to enlarge proxy_read_timeout from 10 to 40 seconds and still the same errors appears but delay is from 40-50 seconds obviously.
So here is my vision of a problem:
-client asks for ts segment
-nginx goes to cache
-nginx does not see what he need in cache
-goes then to the proxy 8080 port
-proxy goes to remote server with range requests
-proxy gets range responses
-proxy processing it and make ts
-proxy responding to the client with ts file and simultaneously writes it to cache
-???something happening???
-at that moment client managed to get 1211968 of 4840248 bytes (as my example above) and it seems to that client decides that there will be no any new info from server and asks for a rest of ts file with range request (as just example above ange_req=bytes=1211968-) and gets response from the proxy (not from cache), and simultaneously ts file is then written to cache.
-after proxy_read_timeout frontend decides to close connection with proxy

**Comment by erankor** [comment]
I looked at the log and I can see that indeed one of the requests got stuck.
The number of bytes sent by nginx-vod:
```
grep 19120 mix-kaltura.txt | grep "write new buf" | gawk "NR > 1 {s+=$(NF-4)} END {print s}"
4686840
```
Match the returned content length header:
```
2016/05/11 22:27:51 [debug] 11954#0: *19120 HTTP/1.1 200 OK
Server: nginx
Date: Wed, 11 May 2016 19:27:51 GMT
Content-Type: video/MP2T
Content-Length: 4686840
Connection: close
ETag: "-1-4783f8"
```
However, the actual number of bytes written to the socket is much less:
```
grep 19120 mix-kaltura.txt | grep "writev" | gawk "NR > 1 {s+=$(NF-2)} END {print s}"
2783169
```

Can you try to disable the rate limit entirely and see if it helps ?

**Comment by kuznetcoff777** [comment]
Limit is set under http context, so this limit_req_zone is used in many locations but with different burst settings. I set it to 1000 r/s, still the same. I catched ip of client (when time out happened) and greped access logs  for last hour, there was only 172 requests (with almost all of them with different time)...

I also noticed that disk utilization is pretty high with spikes up to 100%. If this can be the reason of such behaviour? Is there any other solution, except of changing disk to ssd?

**Comment by erankor** [comment]
I think it still would be a good idea to try without any limit, it is possible that the fact you have a limit makes nginx behave differently.
I don't think this is related to disk utilization, since at least in the log you sent me, nginx-vod-module finished fast, and the data just wasn't sent.

**Comment by kuznetcoff777** [comment]
Commented all limit_req* lines, still no luck...

**Comment by erankor** [comment]
I suggest the following - reduce your nginx.conf to the bare minimum that still reproduces the problem, you already removed the limit, remove the lua, and all other things you have there. You will probably end up with a single location that uses nginx-vod and a single location that uses proxy_pass to it.
Once you have that, send it here and I'll try to reproduce the problem on my environment

**Comment by driusha** [comment]
Thank you for help (kuznetcoff777 is my colleague).
The issue gone after we removed global options from nginx.conf:
    sendfile                  on;
    sendfile_max_chunk        512k;

**Comment by erankor** [comment]
thanks for updating
