### ISSUE TITLE
Multi bitrate from different paths and hosts?

### ISSUE THREAD

**Issue by sergiyshutov** [kaltura/nginx-vod-module#300]
Dear erankor. Can you please take a look this url files. How i  can generate multi bitrate url for hls example?

**v1**.localhost.lc/**1**/2016/**4**/**ytjyNlXP4LQJ4lwPTWLl**.mp4/index.m3u8 - 360
**v2**.localhost.lc/**2**/2016/**5**/**qaY8ZK4xXPWje1q5KU**.mp4/index.m3u8 - 720

**Comment by erankor** [comment]
I don't understand, you want different domains ? 
If so, that is not supported.
Consider that in MSS & HDS the module generates by default relative URLs (don't think MSS even supports absolute) so mixing several domains is not possible.
