### ISSUE TITLE
Dash DRM support

### ISSUE THREAD

**Issue by jacksonvm** [kaltura/nginx-vod-module#304]
Hi Support,

Thank you for the wonderful work you are doing here. I'm bit stuck with my project as I have managed to upload widevine encrypted MP4 flavours onto kaltura, but I'm facing difficulty in pckaging it on the fly. I'm able to request for an MPD file and the player is able to load it too, but the player is not decrypting it. In my investigation, I see a normal MPD file is generated by Nginx without the Widevine encryption info.

Can you please guide me through so that I can add the encryption details to the MPD on the fly.

Thanks in advance.

Jackson

**Comment by erankor** [comment]
First a clarification - in nginx-vod-module there is no direct connection between the way the files are stored (encrypted / clear) and the way they are served (encrypted / clear). So you could set up all 4 possible combinations. 
To serve encrypted content, you need to configure some upstream server that returns a JSON containing all the needed information (key, key id, pssh etc), this is documented here: https://github.com/kaltura/nginx-vod-module/#drm
(the component that handles this task in our system is not open source)
If the file is already encrypted, you will need to use mapped mode, and pass the encryption key on the source object https://github.com/kaltura/nginx-vod-module/#source-clip. If the key used to encrypt the file at rest matches the key that is used for playback, nginx vod will just serve the content as-is, if the keys do not match or the scheme does not match (e.g. the file was encrypted with AES-CTR and played with HLS AES-CBC) nginx-vod will have to decrypt and re-encrypt.

**Comment by erankor** [comment]
Hi @jacksonvm, can this be closed ?

**Comment by dazii-dev** [comment]
Sorry i see the thread is already closed. What if ineed stored encrypted file served in clear format. For support of players without decryption capabilities
