### ISSUE TITLE
vod_bootstrap_segment_durations

### ISSUE THREAD

**Issue by arty777** [kaltura/nginx-vod-module#310]
Hi, 

 when i use vod_bootstrap_segment_durations - video is choppy from time to time,
The picture freezes for a short time, it is choppy and the sound goes well at this time 
without vod_bootstrap_segment_durations  all fine
 please check .

 My config 
##segment setting
vod_bootstrap_segment_durations 1000; #1st segment
vod_bootstrap_segment_durations 1000; #2nd segment
vod_segment_duration 25000;
vod_hls_align_frames off;
vod_hls_interleave_frames on;

**Comment by erankor** [comment]
what is your GOP size ? if it does not divide 1 sec, then it doesn't make sense to configure it like that.
we use 2,2,2,4,10,... with a GOP of 2 sec and it works great

**Comment by arty777** [comment]
How to calculate GOP size? )) 
General
Complete name                            : D:\temp\test.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/iso2/avc1/mp41)
File size                                : 184 MiB
Duration                                 : 56mn 41s
Overall bit rate mode                    : Variable
Overall bit rate                         : 453 Kbps
Writing application                      : HandBrake 0.10.1 2015030800

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 56mn 41s
Bit rate                                 : 320 Kbps
Width                                    : 718 pixels
Height                                   : 400 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 fps
Minimum frame rate                       : 23.974 fps
Maximum frame rate                       : 23.981 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.046
Stream size                              : 130 MiB (71%)
Writing library                          : x264 core 142 r2389 956c8d8
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=6 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=320 / ratetol=1.0 / qcomp=0.70 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Tagged date                              : UTC 2016-05-23 07:42:11
Color range                              : Limited
Color primaries                          : BT.601 NTSC
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.601

**Comment by arty777** [comment]
an d i with 1,2 segments by 10 sec , i have mistake on my config ... and set 1 sec ...

**Comment by erankor** [comment]
you can see the gop size with ffprobe - 
```
ffprobe -i input.mp4 -show_frames -select_streams v
```
look at the timestamps of the key frames (pict_type=I), e.g. if you see key frames at 2,4,6,8.. the gop is 2 sec. note that there may be additional keyframes at arbitrary locations due to scenecuts

**Comment by arty777** [comment]
I tried a variety of  the size 8 8 10 / 10 10 25 / 8 8 24 etc, but no any good reaction

When i commented out
#vod_hls_align_frames off;
#vod_hls_interleave_frames on;
, and all is well now!

**Comment by erankor** [comment]
which player are you testing with ? these settings make a more compact hls packaging, but it is possible that some players do not handle it well

**Comment by arty777** [comment]
may be its player problem , i use uppod , but not very fresh version ,

**Comment by arty777** [comment]
i see 
[FRAME]
media_type=video
key_frame=0
pkt_pts=71321
pkt_pts_time=0.792456
pkt_dts=71321
pkt_dts_time=0.792456
best_effort_timestamp=71321
best_effort_timestamp_time=0.792456
pkt_duration=3753
pkt_duration_time=0.041700
pkt_pos=2566881
pkt_size=24011
width=718
height=400
pix_fmt=yuv420p
sample_aspect_ratio=N/A
pict_type=B
coded_picture_number=20
display_picture_number=0
interlaced_frame=0
top_field_first=0
repeat_pict=0


 in all file key_frame always 0 , what its mean? ))

**Comment by erankor** [comment]
Always best to test HLS on Safari (iPhone/iPad/Mac)
Regarding ffprobe, as I wrote above, you should look for pict_type=I, the frame you pasted has pict_type=B which means that it's not a key frame (there are 3 possible values I,P,B and I = key frame)

**Comment by arty777** [comment]
yes, sorry 
for pict_type=I , key_frame=1 always

**Comment by arty777** [comment]
as i understand my gop size is 1 ? 
and due to this fact, I have to put option is a multiple of 1?

**Comment by erankor** [comment]
I don't know what is your gop size since I didn't see the full log.
But if it is, then yes, it is recommended to use segment durations that are multiples of the gop
