### ISSUE TITLE
How Nginx is working

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#312]
Can you explain me on,  how on-the-fly conversion is happening and where the transcoded files are saving ? is it saving locally ? where can i find init file of MPEG-DASH transcoded file.

**Comment by erankor** [comment]
Everything is done in memory, the manifests / segments are not written anywhere. If you want to see the init segment (or any other segment/manifest) you will need to pull it via HTTP (e.g. using curl/wget)
