### ISSUE TITLE
Pricing 

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#313]
Hi, Erankor, 

Is your Nginx-Vod-Module ( including DRM module) is free of cost  ?

**Comment by erankor** [comment]
The module is free & open source with an AGPL license, as stated by the readme.

**Comment by Natarajan92** [comment]
Ok! So we can use it for commercial purpose ?

**Comment by erankor** [comment]
I'm not a lawyer, but in my understanding you can do whatever you want with it. However, if you make any changes to the code (add features etc.) you must contribute them back.

**Comment by garybruckheimer** [comment]
the license of the kaltura is agpl, means even when you host the
software as a service, you have to give access to the source code and
must publish your changes.

we use this license and have absolute no problem to publish our changes,
on the contrary, publishing fixes or features give the whole project
more live.

no commercial customer from us ever ask for the code or to download the
sources. most of them do not understand how to compile or to setup the
kaltura plugins in their own nginx instance.

that´s it..simple, effective.


Am 30.05.16 um 08:33 schrieb erankor:
