### ISSUE TITLE
Multi-profile HLS not playing in Apple device 

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#318]
Hi,

Multi-Profile Hls streaming is not playing in apple device except audio. But Multi-profile HLS plays in Android device default player 

Example of Multi-profile Url provided to apple device is : http://ip-address:portnumber/location/<path to mp4 file>.urlset/master.m3u8

If i give url of single profile as like this  http://ip-address:portnumber/location/path to mp4 file/index.m3u8 than it is playing in Apple device 

So, what might be the issue, why Apple device is unable to play the content, when i pass master.m3u8 file

**Comment by erankor** [comment]
All HLS features are tested on Apple (usually iPhone), if it doesn't play, it must be something specific to your videos, please send a URL

**Comment by Natarajan92** [comment]
Url of multiprofile hls is http://119.82.113.58:88/dash/dashtest-,700,1200,2000,198,k.mp4.urlset/master.m3u8

**Comment by erankor** [comment]
The beginning plays fine on my iphone, starts with 700kbps and settles on 2000kbps. If you are getting audio only, it is probably because you don't have enough bandwidth and the device falls back to the 198kbps file which is audio-only. 
However at some point, it freezes, and that's because the video stream is ~2 sec shorter than the audio stream. This fact, along with the fact that you are using separate video/audio mp4 files, makes the module generate a different PID for the audio of the last packet (all segments have video=0x100, audio=0x101, while the last segment has audio=0x100) and the player obviously doesn't like it...
If I clip both streams to the same duration, it plays fine till the end:
http://119.82.113.58:88/dash/clipTo/120000/dashtest-,700,1200,2000,198,k.mp4.urlset/master.m3u8

**Comment by Natarajan92** [comment]
Am testing all the url's locally, so i don't think so there will be bandwidth issue. The above URL which you gave http://local-ip-address:88/dash/clipTo/120000/dashtest-,700,1200,2000,198,k.mp4.urlset/master.m3u8 also not playing except audio for me 

I have tested without separating audio and video also that too doesn't work Public Url to that video is 
http://119.82.113.58:88/dash/trl-,700,1200,k.mp4.urlset/master.m3u8

If you need i can provide you access log also

**Comment by Natarajan92** [comment]
Hi Eran,

I have found out the problem, If we use this CODECS="avc1.64002a,mp4a.40.2" detail in m3u8 file it is not playing. If i remove that CODEC information than it is playing

**Comment by erankor** [comment]
Plays fine on my iPhone as well (iPhone 6s iOS 9.3.2)
However this stream uses h264 high profile level 4.2, which is higher than Apple's official statement:
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/FrequentlyAskedQuestions/FrequentlyAskedQuestions.html

What probably happens is that when you play multi-bitrate, the device sees the CODECS attribute, and dismisses the video because it's too high. When you play a single bitrate, the device does not know the codec in advance, so it just starts playing

**Comment by erankor** [comment]
Saw your last comment only now, I don't think hiding the CODECS is the correct solution, you should follow Apple's guidelines for transcoding

**Comment by Natarajan92** [comment]
Ok! I will try with these profiles H.264 Baseline Level 3.0, Baseline Level 3.1, Main Level 3.1, and High Profile Level 4.1. and will come back to you.

Thanks for your update too

**Comment by Natarajan92** [comment]
Thanks Eran, It is working now. The problem is on Profile compatibility only.  As you have iPhone 6s and version of 9.3.2 it works for you earlier with High Profile Level 4.2. After changing profile level to 4.1 or below to main level it is working smoothly. Thank you

**Comment by Natarajan92** [comment]
In mapped mode, multiprofile hls is not working and the same is working if i use index.m3u8 with simple mapping json containing only one mp4 file.  When i use multiple path's in mapping json file audio and video both not playing in Ipad version version is 9.3.2

**Comment by erankor** [comment]
it doesn't play at all, or plays audio only ? this master playlist starts with an audio only bitrate, which is generally a bad idea, you should order your sequences so that the audio will return last.

**Comment by Natarajan92** [comment]
just for 2 seconds audio is coming and after that no audio also.

**Comment by erankor** [comment]
Maybe your GOP does not match the segments you are using, so the player starts with the audio rendition, and when it tries to switch to video, it does not get a keyframe and therefore fails to decode it.

**Comment by Natarajan92** [comment]
i have checked with GOP and segment durations. Am using GOP size as 40, Command used in ffmpeg for that is " -g 40 -keyint_min 40 " and in configuration, i have not set segment duration for hls which is by default 10s in your module.

Configuration of vod hls location is below and am using encrypted mp4 files as input 

location ~ ^/videohls/([^-]+)-.* {
      	    vod hls;
	    vod_mode mapped;
	    #vod_segment_duration 4000;
	    #vod_align_segments_to_key_frames on;
	    vod_max_mapping_response_size 64k;
	    vod_upstream_location /kalapi_proxy/;
	    vod_media_set_map_uri video/$1.json;
            
            #vod_drm_enabled on;
            #vod_drm_upstream_location /kalapi_proxy/;
            vod_upstream_extra_args "pathOnly=1";
            #vod_drm_request_uri video/$1.js;
            #vod_hls_encryption_method sample-aes;
            #vod_hls_encryption_key_uri "base64 data";
            #vod_hls_encryption_key_format "com.apple.streamingkeydelivery";
            #vod_hls_encryption_key_format_versions "1";
	    
     	

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;

	}

After changing GOP to 40 from 96, there is no audio or video nothing. Am not seeing player seek bar itself.

**Comment by Natarajan92** [comment]
if you require any logs or details, please say i will provide.

**Comment by erankor** [comment]
it's not related to these libs. you probably just need to reorder the renditions so that the audio only will appear last. you can also try with `vod_align_segments_to_key_frames on` as it sounds like your keyframes are not a multiple of 10 seconds

**Comment by Natarajan92** [comment]
As you said, i have tried by enabling vod_align_segments_to_key_frames as  on and reordered sequences as like below 

{
    "sequences": [
	{
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/lab/videoenc/video-700k.mp4",
                    "encryptionKey": "g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/lab/videoenc/video-1200k.mp4",
                    "encryptionKey": "g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        },
	{
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/lab/videoenc/video-198k.mp4",
                    "encryptionKey": "g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        }
    ]
}

So the audio is represented at the last in m3u8 file also. . both audio and video doesn't play

**Comment by Natarajan92** [comment]
You need any other logs or data's to get solution for this problem ?

**Comment by erankor** [comment]
Please send a link to the stream

**Comment by Natarajan92** [comment]
Ok, i will mail you the link

**Comment by Natarajan92** [comment]
One doubt, Is it necessary/compulsory to use separate audio(mp4) and video(mp4) files for mpeg dash streaming ? or can we use multiplexed single mp4 file containing audio and video in it.

**Comment by erankor** [comment]
you can use muxed mp4

**Comment by Natarajan92** [comment]
Ok! I have send you link in mail

**Comment by erankor** [comment]
Incidentally, earlier today I bumped into the same issue that exists in your manifest...
Committed a fix here https://github.com/kaltura/nginx-vod-module/pull/350, try with latest master.
This bug affected HLS streams in which the audio and video come from different files.

**Comment by Natarajan92** [comment]
Ok! Thanks, i will try with latest master build

**Comment by Natarajan92** [comment]
Now, it is working

**Comment by Natarajan92** [comment]
Hi, 

Again we are seeing problem in ABR stream playback . 

While we play HLS stream in apple device,  video freeze and audio alone keep on playing, In access log no request to video segment. Only audio segment file is requested. 

On Seek video frame loaded but only audio playing. Video stalled

**Comment by erankor** [comment]
I will need more details... 
1. The stream URL
2. The video files
3. The mapping JSON
4. nginx.conf

**Comment by Natarajan92** [comment]
Error Log while streaming content for your information

2018/07/13 03:12:29 [info] 64636#64636: *649 client prematurely closed connection while processing frames, client: 119.82.113.58, server: 10.59.0.35, request: "GET /video/tvn/hlsEnc/VUBX0543215813858190MP4/TRL/hhd-/seg-1-f2-v1-f3-a1.ts HTTP/1.1", host: "66.223.155.217:8005"

**Comment by erankor** [comment]
I checked it now, plays fine for me.
Is it possible that you have a connectivity issue? since you are providing the audio using a separate sequence, the module outputs it as a separate EXT-STREAM-INF. If the player doesn't have enough bandwidth, it will fall back to play the audio only stream. 
You can try to remove the audio stream from the output, by using the mixFilter explicitly, something like this -
```
{
	"sequences": [{
		"clips": [{
			"type": "mixFilter",
			"sources": [{
				"path": "/nginx/test/hls/media-video-2.mp4",
				"type": "source"
			},
			{
				"path": "/nginx/test/hls/media-audio-en-mp4a.mp4",
				"type": "source"
			}]
		}]
	}]
}```
(this JSON shows one bitrate, you can replicate the sequence object for additional bitrates)

**Comment by Natarajan92** [comment]
Hi Eran, 

Ok Thank you. I will check on it and get back to you. 

Below JSON is correct for multiple bitrate ? In master m3u8 there is only child m3u8 details

{
"sequences": [{
		"clips": [{
			"type": "mixFilter",
			"sources": [{
				"path": "/nginx/test/hls/media-video-2.mp4",
				"type": "source"
			},
			{
				"path": "/nginx/test/hls/media-audio-en-mp4a.mp4",
				"type": "source"
			}]
		}]
	}],
"sequences": [{
		"clips": [{
			"type": "mixFilter",
			"sources": [{
				"path": "/nginx/test/hls/media-video-1.mp4",
				"type": "source"
			},
			{
				"path": "/nginx/test/hls/media-audio-en-mp4a.mp4",
				"type": "source"
			}]
		}]
	}]
}

(Same JSON can we use for DASH, If so Dash also will be packaged with muxed audio and video ? )

**Comment by erankor** [comment]
No, you wrote two attributes named `sequences` they override each other... you need to have two elements in the array under sequences. 
DASH is never muxed

**Comment by Natarajan92** [comment]
Ok, Thanks!

 Able to stream ABR stream with mixFilter.  Dash with separate audio and video. 

Will do multiple tests and update you soon.

**Comment by Natarajan92** [comment]
Thank you Eran! Works fine. If anything required will open ticket
