### ISSUE TITLE
mp4 direct?

### ISSUE THREAD

**Issue by arielesp** [kaltura/nginx-vod-module#321]
Hi,

I am in doubt whether the module is working properly.
The installation was successful.
I followed the example of local parameter settings , but how to know if the mp4 is being served properly by the module ?
Access Direct is the url of the file .mp4 , eg http://lars13.meu-servidor.com/_videos/2015/04/30/porno-completo-com-loira-de-tetas-grandes-360p.mp4

I'm using this time as follows:

http
{
aio on;
vod_mode local;
vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
vod_last_modified_types *;
vod_metadata_cache mp4_metacache 512m;
vod_response_cache mp4_response_cache 128m;

open_file_cache             max=1000 inactive=5m;
open_file_cache_valid       2m;
open_file_cache_min_uses    1;
open_file_cache_errors      on;

server
{
.....
location ~ \.(mp4|m4a|m4v)$ 
    {   
        vod dash;
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
    }
}
}
It's correct ?

**Comment by erankor** [comment]
The extensions used by the module in dash are mpd, mp4 and m4s, you'll need to match all 3 and build a url in the format <path to mp4>/manifest.mpd

**Comment by erankor** [comment]
hi @arielesp, is it working for you ? can this be closed ?
