### ISSUE TITLE
Zero-length HLS segments produced

### ISSUE THREAD

**Issue by ddunkin** [kaltura/nginx-vod-module#322]
The segmenter will produce a zero-length segment if there aren't enough keyframes. I have the 6 second segments configured, but if the source doesn't have enough keyframes, I get a HLS playlist that Safari considers invalid.

Here's my config:
```
            vod_segment_duration 6000;
            vod_align_segments_to_key_frames on;
            vod_manifest_segment_durations_mode accurate;
```
Here's the playlist: http://tv-vod.faithlifecdn.com/stream/1483228800/3225452.cNNgVGKob5AaHLcyzsX_yQ/index-6s-ka-v1-a1.m3u8
Here's the original media: https://files.logoscdn.com/v1/files/3225452/content.mp4?signature=B2HoC0xEXF4pWezIj0udbBTgzl4

**Comment by ddunkin** [comment]
I usually encode a keyframe every 2 seconds, but in some cases I need to serve videos that I didn't create.

**Comment by erankor** [comment]
I've just explained why this happens here https://github.com/kaltura/nginx-vod-module/issues/323.
For HLS since the manifest explicitly provides the URL of each segment, I can change the code to simply avoid printing segments with 0 duration.

**Comment by ddunkin** [comment]
Omitting zero-duration segments sounds good to me.

**Comment by erankor** [comment]
Fixed here: https://github.com/kaltura/nginx-vod-module/pull/329
