### ISSUE TITLE
nginx vod_status example

### ISSUE THREAD

**Issue by Boburjon** [kaltura/nginx-vod-module#324]
Hi, I wanted to use vod_status module to see the number of connected users, and display the result using php is real?

**Comment by erankor** [comment]
vod_status does not provide this info, it provides statistics that can be used to benchmark / troubleshoot the performance of the module. 
Btw, for most large scale deployments, there will be caching of the video segments outside this module (CDN / proxies...) in these cases, it is not even possible to determine the number of users in nginx vod
