### ISSUE TITLE
HLS_Fairplay

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#327]
Hi Eran, 
           We are able to test playback of clear HLS asset, How to test FairPlay encrypted assets ? Do you have any demo environment to test playback of fairplay encrypted assets ?

**Comment by erankor** [comment]
Unfortunately playing FPS requires a certificate from Apple, there is some process to get this, and afaik they only provide it to content owners

**Comment by Natarajan92** [comment]
Ok. As you mentioned in Readme.md, you have tested HLS fairplay with the certification provided by Apple ? 

According to your answer, the process of getting certification with Apple will take more time it seems, So is it possible to use your(Kaltura's) FPS certification to do test playback of our Fairplay encrypted assets ?

**Comment by erankor** [comment]
1. All playback methods were tested end to end, including FPS
2. As I wrote, they only provide it to content owners, so we don't have our own, we have customers that have.
3. I have to say that I find this request inappropriate, even if we had a certificate we wouldn't have shared it. It is not my place to become a backdoor for Apple's policies.
