### ISSUE TITLE
On-the-fly packaging of encrypted assets 

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#332]
Hi Eran,

Is it possible to use encrypted assets as input instead of clear .mp4 files for both dash and hls streaming ? So if i request as like this http://ip:port/dash/path to encryptedmp4file/manifest.mpd should deliver dash manifest file and if i request http://ip:port/dash/path to encryptedmp4file/master.m3u8 should deliver m3u8 file for hls playback.

**Comment by erankor** [comment]
Yes, this works only in mapped mode, you have to set the `encryptionKey` field on the clip object to the key that the mp4 was encrypted with. In DASH/MSS, if this key matches the key that appears in the DRM JSON, the module serves the encrypted data as is. In HLS, or if the keys do not match, the module will decrypt + re-encrypt the data.

**Comment by Natarajan92** [comment]
@erankor Thanks for your reply. As per the documents on mapped mode, i have tried to use mapped mode configuration to do conversion of encrypted assets. But am getting error on udrm_parse_responce

Error:
2016/06/16 12:10:56 [error] 26731#26731: *1015 udrm_parse_response: expected a single element array while sending to client, client: IP Address, server: IP Address, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "IP Address:8080"
2016/06/16 12:10:56 [error] 26731#26731: *1015 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: IP Address, server: IP Address, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "IP Address:8080"
2016/06/16 12:10:58 [error] 26731#26731: *1015 udrm_parse_response: expected a single element array while sending to client, client: IP Address, server: IP Address, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "IP Address:8080"
2016/06/16 12:10:58 [error] 26731#26731: *1015 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: IP Address, server: IP Address, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "IP Address:8080"

Am attaching my configuration file and mapped JSON file.

**Comment by Natarajan92** [comment]
What mistake am doing with this mapped configuration. Can you help ?

**Comment by Natarajan92** [comment]
@Erankor I have tried with different configurations also and issue is not resolved.

**Comment by erankor** [comment]
1. Your mapping JSON is 1131 bytes, the default limit is 1K (1024 bytes), so you have to increase it - e.g. `vod_max_mapping_response_size 64k;`. Btw, I got a different error message, so I think you are not using the latest master, maybe the latest pre-compiled
2. You didn't send the DRM JSON (you sent only the mapping), but after fixing what I wrote in 1, and using this sample JSON https://github.com/kaltura/nginx-vod-module/#drm as the DRM JSON, I am getting back the MPD with your config and mapping JSON.
3. Other than that, it makes completely no sense to use `$1` in a location that is not a regex location / a location that has no captures, it will always evaluate to empty string

**Comment by Natarajan92** [comment]
The version am using is 
[root@Natarajan ~]# nginx -v 
nginx version: nginx/1.8.1

and i have installed it by using this command for centos 6 

# rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
# yum install kaltura-nginx

**Comment by Natarajan92** [comment]
Error : 
2016/06/20 18:18:15 [error] 29789#29789: *3 ngx_http_vod_dash_parse_uri_file_name: unidentified request, client: ipaddress, server: localhost, request: "GET /json/dash/enc-jun15/TVN6068376-3000k.mp4?pathOnly=1 HTTP/1.0", host: "ipaddress:8001"
2016/06/20 18:18:15 [error] 29789#29789: *1 ngx_child_request_wev_handler: upstream returned a bad status 400 while sending to client, client: ipaddress, server: localhost, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "ipaddress:8001"


Am getting above error with the below mentioned configuration and json files. .  In last comment i have informed you, how i have installed NGINX-VOD-Module in centos 6 


config file :
#user  nobody;
worker_processes  4;

error_log  /opt/NGINX/error_log;

pid		/var/run/nginx.pid;

events {
	worker_connections  1024;
	multi_accept on;
	use epoll;
}

http {



	upstream kalapi {
		server Ip-Address:8001;
	}
		
	include	   mime.types;
	default_type  application/octet-stream;


	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
		'$status $bytes_sent $request_time "$http_referer" "$http_user_agent" "-" - '
		'"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
		'$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
		'"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
		'$connection ';

	access_log  /opt/NGINX/access_log main;



	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;

	keepalive_timeout 60;
	keepalive_requests 1000;
	client_header_timeout 20;
	client_body_timeout 20;
	reset_timedout_connection on;
	send_timeout 20;

	gzip  on;
	gzip_types application/vnd.apple.mpegurl video/f4m application/dash+xml text/xml;
	
	# common vod settings
	vod_mode mapped;
	vod_upstream_location /kalapi;
	vod_upstream_extra_args "pathOnly=1";

	# shared memory zones
	vod_metadata_cache metadata_cache 512m;
	vod_mapping_cache mapping_cache 64m;
	vod_response_cache response_cache 64m;
	vod_performance_counters perf_counters;

	# common file caching / aio
	open_file_cache max=1000 inactive=5m;
	open_file_cache_valid 2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors on;
	aio on;


server {
    listen 8001;
    server_name localhost;

    #mapped configuration server

    location ^~ /kalapi/ {
        internal;
        proxy_pass http://kalapi/json/;
        proxy_set_header Host $http_host;
    }

    #key server

    location ^~ /keyserver/ {
        internal;
        proxy_pass http://kalapi/;
        proxy_set_header Host $http_host;
    }

    # json

    location /json/ {
        root   /var/www/html;
        add_header Content-Type "application/json; charset=UTF-8";
    }


   location ~ /dash/([^\-]+)\-.* {
            
      	    vod dash;
            vod_segment_duration 4000;
	    vod_dash_manifest_format segmenttemplate;
	    vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;
            vod_drm_clear_lead_segment_count 0;
	    vod_drm_enabled on;
            vod_drm_upstream_location  /keyserver;
	    vod_drm_request_uri /dash/$2.js;
 
            root /var/www/html;


        add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
        add_header Access-Control-Allow-Headers "*";
        add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
        add_header Access-Control-Allow-Origin "*";
        expires 100d;
    }
}
}

Decryption key json file 

{
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/dash/enc-jun15/TVN6068376-198k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/dash/enc-jun15/TVN6068376-700k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/dash/enc-jun15/TVN6068376-1200k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/dash/enc-jun15/TVN6068376-3000k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        }
    ]
}


Encryption DRM json file : 

[{"key_id": "3hc679M7SAKvDgPJ9a2U/w==", 
"pssh": [{
"data": "CAESENA=", 
"uuid": "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"}, 
{"data": "base64", 
"uuid": "9A04F079-9840-4286-AB92-E65BE0885F95"}],
"key": "g4kQKd9XDUPp8G1m2quZwg=="
}]

**Comment by Natarajan92** [comment]
As you said above we have installed latest master build and i have made some changes in configuration file for regular expression and tried to decrypt file and than package it in mapped mode. 

Am getting following error while requesting for mpd file, 

Error:
2016/06/21 09:54:31 [error] 22438#22438: *3 ngx_http_vod_dash_parse_uri_file_name: unidentified request, client: IP-Address, server: localhost, request: "GET /json/dash/enc-jun15/TVN6068376-3000k.mp4?pathOnly=1 HTTP/1.0", host: "IP-Address:8001"
2016/06/21 09:54:31 [error] 22438#22438: *1 ngx_child_request_wev_handler: upstream returned a bad status 400 while sending to client, client: IP-Address, server: localhost, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "IP-Address:8001"

The way of using regular expression in mapped mode is correct ? 
[nginx.txt](https://github.com/kaltura/nginx-vod-module/files/324795/nginx.txt)

Following is the detail of nginx versions

[root@Natarajan ~]# nginx -V 
nginx version: nginx/1.10.0
built by gcc 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=kaltura --group=kaltura --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-http_v2_module --with-threads --with-cc-opt='-O3 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --add-module=/opt/NGINX/nginx-vod-module --add-module=/opt/nginx-rtmp-module-master
You have new mail in /var/spool/mail/root

**Comment by erankor** [comment]
Is it possible that the error you pasted does not match the configuration you attached ?
The error refers to port 8001, while the config has 8080, and also the error has the `pathOnly=1` suffix that we use in our configs, but your config doesn't have it

**Comment by Natarajan92** [comment]
Yes, sorry i have not noticed port number while changing configuration file. 

With proper port number and regular expression in location of configuration file. The error we got is 

2016/06/21 12:34:43 [error] 23976#23976: *1 media_set_parse_json: failed to parse json -1: expected digit got 0x0 while getting mapping, client: IP-Address, server: IP-Address, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "IP-Address:8080"
2016/06/21 12:35:56 [error] 24000#24000: *1 media_set_parse_json: failed to parse json -1: expected digit got 0x0 while getting mapping, client: IP-Address, server: IP-Address, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "IP_Address:8080"

**Comment by Natarajan92** [comment]
Encrypted Mp4 files are under /var/www/html/dash/enc-jun15/TVN6068376-700,1200,3000,198k.mp4 

JSON-DRM file is named as TVN6068376.js and located under /var/www/html/dash/enc-jun15/

Clip-JSON file with key information to decrypt is located under  /var/www/html/json/dash/enc-jun15/TVN6068376.js

Hope this may give you idea to resolve this issue or do you need some more information ?

**Comment by Natarajan92** [comment]
I have tried with debug option also, but no luck. Can you give me any idea or solution

**Comment by erankor** [comment]
Is it possible that one of your jsons is larger than 64k ? I don't why it should be, but that's what this log says... it has both `ngx_async_file_read: ngx_file_aio_read returned 65536` and `expected digit got 0x0` (which means the json was truncated)

**Comment by erankor** [comment]
If that is the case, you can just increase `vod_max_mapping_response_size` further

**Comment by Natarajan92** [comment]
Ok! Am having one more doubt.

 The sample url am requesting to get dash manifest file is http://IP-Address:8080/dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd

Encrypted Mp4 files are under /var/www/html/dash/enc-jun15/TVN6068376-700,1200,3000,198k.mp4

JSON-DRM file is named as TVN6068376.js and located under /var/www/html/dash/enc-jun15/

Clip-JSON file with key information to decrypt is located under /var/www/html/json/dash/enc-jun15/TVN6068376.js


The doubt is, the way am naming files and the way am keeping the files under these locations are correct ? In mapped mode, nginx configuration pointing these json files only ?

**Comment by Natarajan92** [comment]
I have checked JSON file sizes, both DRM-Json and Clip-Json file is below 1.7k.

**Comment by erankor** [comment]
The naming is determined by the configuration, and it can be controlled - 
1. The mapping JSON can be configured with `media_set_map_uri`
2. The DRM JSON can be configured with `vod_drm_request_uri`
3. The full path to MP4 is included in the mapping JSON and can be whatever you want
Other than these config vars, there are also ways to control it on the `proxy_pass` directive (including URI vs not including, the name of the proxy pass location etc.)
So, at the end it's up to, as I believe I already wrote somewhere, in our use 1 & 2 are not real files on disk but rather generated by code as they are requested.

**Comment by Natarajan92** [comment]
Ok! Am keeping it as static real files in disk. 

under location directory, am using like this 
#user nobody;
worker_processes 4;

error_log /opt/NGINX/error_log;

pid /var/run/nginx.pid;

events {
worker_connections 1024;
multi_accept on;
use epoll;
}

http {
upstream kalapi {
server xxx.xxx.xxx.xxx:8080;
}

include /etc/nginx/mime.types;
default_type  application/octet-stream;

log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $bytes_sent $request_time "$http_referer" "$http_user_agent" "-" - '
    '"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
    '$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
    '"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
    '$connection ';

access_log  /opt/NGINX/access_log main;

sendfile on;
tcp_nopush on;
tcp_nodelay on;

keepalive_timeout 60;
keepalive_requests 1000;
client_header_timeout 20;
client_body_timeout 20;
reset_timedout_connection on;
send_timeout 20;

gzip  on;
gzip_types application/vnd.apple.mpegurl video/f4m application/dash+xml text/xml;

server {
    listen 8080;
    server_name xxx.xxx.xxx.xxx;
    include /etc/nginx/conf.d/kaltura.conf.template;

         location ^~ /kalapi/ {
                internal;
                proxy_pass http://kalapi/;
                proxy_set_header Host $http_host;
            }       

    #video test

            location ~ /dash/([^\-]+)\-.* {

        vod dash;
        vod_mode mapped;
        vod_max_mapping_response_size 64k;
        vod_segment_duration 4000;
        vod_dash_manifest_format segmenttemplate;
        vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;
        vod_drm_clear_lead_segment_count 0;
        vod_drm_enabled on;
        vod_drm_upstream_location /kalapi;
        vod_upstream_extra_args "pathOnly=1";
        vod_drm_request_uri /dash/$1.js;
        vod_media_set_map_uri /dash/$1.js;
        root /var/www/html;

        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
            }
}
}

while using as like above am getting error as like this 
Error:
2016/06/22 10:20:56 [error] 10133#10133: *1 ngx_file_reader_update_state_file_info: open() "/dash/enc.js" failed (2: No such file or directory) while getting mapping, client: xxx.xx.xx.xx, server: xxx.xx.xx.xx, request: "GET /dash/enc-jun15/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "xx.xx.xx.xx:8080"

but under dash folder there is a js file in the name of enc.js

getting the mapping json file only is the problem for us. can you give us a solution with example

**Comment by Natarajan92** [comment]
Can anyone give a solution ?

**Comment by Natarajan92** [comment]
@erankor 

After some struggling am getting an error as like this, 

2016/06/23 11:04:26 [error] 19193#19193: *5 udrm_parse_response: expected an array containing a single object while sending to client, client: 172.168.0.1, server: localhost, request: "GET /nfs/vod/video-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "172.168.0.1:8005"

My apache log for getting Mapping-JSON file is 

[23/Jun/2016:11:02:45 +0530] "GET /map/enc.js HTTP/1.0" 200 304 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0"
127.0.0.1 - - [23/Jun/2016:11:02:46 +0530] "GET /map/enc.js HTTP/1.0" 200 304 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0

location ~ /nfs/([^\-]+)\-.* {
			 vod dash;
		         vod_mode mapped;
    		         vod_max_mapping_response_size 64k;
    			 vod_segment_duration 4000;
           		 vod_dash_manifest_format segmenttemplate;
    			 vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;
 			 vod_upstream_location /kalapi_proxy/;
    			 vod_media_set_map_uri map/enc.js;

                         vod_drm_clear_lead_segment_count 0;
    			 vod_drm_enabled on;
	                 vod_drm_upstream_location /kalapi_proxy/;
    			 vod_upstream_extra_args "pathOnly=1";
    			 vod_drm_request_uri nfs/$1.js;

My Mapping json file is below 

{
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/nfs/vod/video198k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/nfs/vod/video700k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/nfs/vod/video1200k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/www/html/nfs/vod/video3000k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        }
    ]
}

can you provide a solution ?

**Comment by Natarajan92** [comment]
@erankor Thanks for your help, it works.

**Comment by Natarajan92** [comment]
@erankor , HI 

With GPAC MP4Box  tool encrypted the mp4 file and kept in server physically. 

In mapping JSON file gave **"encryptionKey"** as per the document and from client requested to dash encrypted stream (playready/widevine). 

**"encryptionKey"** in vod_media_set_map_uri (JSON) and vod_drm_request_uri (JS) file are same.

Stream playing but full of green color patches, like not decrypted properly. 

If clear content is served as input to vod module and serve it as encrypted dash stream than player is able to play properly. 

# nginx -v
nginx version: nginx/1.10.3

Vod module is  build statically not installed through rpm 
Server OS - Centos 6

How to debug it ? If you need log or additional details am glad to provide .

**Comment by erankor** [comment]
Try to play the encrypted mp4 in clear dash (have nginx-vod-module decrypt it), from your description sounds like it will probably fail too, but worth trying

**Comment by Natarajan92** [comment]
Yes, that too failed, Clear stream also same issue.

**Comment by erankor** [comment]
Please provide - 
1. URL for the clear MP4
2. URL for the encrypted MP4
3. The encryption key

**Comment by Natarajan92** [comment]
@erankor , Hi 

Do you want URL's to MP4 files or will it be better, if i send you MP4 files ? 

If you want URL's than it need to be arranged for public access and that will take time. 

If you are Ok for MP4 files, pls share your ftp access to upload the files or share your email id I will send personally to your mail id through google drive.

**Comment by erankor** [comment]
I need the files, but I want to get them as URLs, so that I can easily pull them from my test server

**Comment by Natarajan92** [comment]
I have send you mp4 files through google drive to your email id. Please check on it

**Comment by Natarajan92** [comment]
Hi Eran, 

Have you got files ?

**Comment by erankor** [comment]
@Natarajan92, I checked it out, please try this pull - https://github.com/kaltura/nginx-vod-module/pull/868
It seems that MP4Box initially had a bug of placing the senc atom under stbl instead of trak. When I added support for playing encrypted files, I matched MP4Box, and therefore looked for this atom in the wrong place.
The MP4Box bug was fixed in https://github.com/gpac/gpac/commit/6ce744e85d72a049b680645cf8c9b3dc02a95252
and therefore newer MP4Box versions didn't work for you.
This patch supports both the old and the new formats.

**Comment by Natarajan92** [comment]
Ok! Thank you 

I will try and Update the status

**Comment by Natarajan92** [comment]
@erankor ,  With new pull -#868, it is working as expected. Thanks

**Comment by erankor** [comment]
Merged, thanks
