### ISSUE TITLE
Build Installation Error 

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#335]
Hi Eran,

Getting error, while trying to install Nginx-Vod-Module. Below are the steps i have performed to install module

1) cd NGINX source directory

2) ./configure --add-module=/opt/NGINX/nginx-vod-module --with-file-aio --with-cc-opt="-O3" --add-module=/opt/nginx-rtmp-module-master

output 
[root@Natarajan nginx-1.10.0]# ./configure --add-module=/opt/NGINX/nginx-vod-module --with-file-aio --with-cc-opt="-O3" --add-module=/opt/nginx-rtmp-module-master
checking for OS
 + Linux 2.6.32-573.18.1.el6.x86_64 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 
checking for gcc -pipe switch ... found
checking for -Wl,-E switch ... found
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for gcc builtin 64 bit byteswap ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... not found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... found
checking for Linux specific features
checking for epoll ... found
checking for EPOLLRDHUP ... found
checking for O_PATH ... found
checking for sendfile() ... found
checking for sendfile64() ... found
checking for sys/prctl.h ... found
checking for prctl(PR_SET_DUMPABLE) ... found
checking for sched_setaffinity() ... found
checking for crypt_r() ... found
checking for sys/vfs.h ... found
checking for nobody group ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for kqueue ... not found
checking for crypt() ... not found
checking for crypt() in libcrypt ... found
checking for F_READAHEAD ... not found
checking for posix_fadvise() ... found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... not found
checking for dlopen() in libdl ... found
checking for sched_yield() ... found
checking for SO_SETFIB ... not found
checking for SO_REUSEPORT ... found
checking for SO_ACCEPTFILTER ... not found
checking for IP_RECVDSTADDR ... not found
checking for IP_PKTINFO ... found
checking for IPV6_RECVPKTINFO ... found
checking for TCP_DEFER_ACCEPT ... found
checking for TCP_KEEPIDLE ... found
checking for TCP_FASTOPEN ... not found
checking for TCP_INFO ... found
checking for accept4() ... found
checking for kqueue AIO support ... not found
checking for Linux AIO support ... found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint32_t ... found
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 4 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for setproctitle() ... not found
checking for pread() ... found
checking for pwrite() ... found
checking for pwritev() ... found
checking for sys_nerr ... found
checking for localtime_r() ... found
checking for posix_memalign() ... found
checking for memalign() ... found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found
checking for System V shared memory ... found
checking for POSIX semaphores ... not found
checking for POSIX semaphores in libpthread ... found
checking for struct msghdr.msg_control ... found
checking for ioctl(FIONBIO) ... found
checking for struct tm.tm_gmtoff ... found
checking for struct dirent.d_namlen ... not found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional modules
adding module in /opt/NGINX/nginx-vod-module
checking for OpenSSL EVP library ... found
checking for clock_gettime() ... not found
checking for clock_gettime() in librt ... found
checking for libavcodec ... found
checking for libavfilter ... found
 + ngx_http_vod_module was configured
adding module in /opt/nginx-rtmp-module-master
 + ngx_rtmp_module was configured
checking for PCRE library ... found
checking for PCRE JIT support ... not found
checking for OpenSSL library ... found
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using system PCRE library
  + using system OpenSSL library
  + md5: using OpenSSL library
  + sha1: using OpenSSL library
  + using system zlib library

  nginx path prefix: "/usr/local/nginx"
  nginx binary file: "/usr/local/nginx/sbin/nginx"
  nginx modules path: "/usr/local/nginx/modules"
  nginx configuration prefix: "/usr/local/nginx/conf"
  nginx configuration file: "/usr/local/nginx/conf/nginx.conf"
  nginx pid file: "/usr/local/nginx/logs/nginx.pid"
  nginx error log file: "/usr/local/nginx/logs/error.log"
  nginx http access log file: "/usr/local/nginx/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"

3) make
 
objs/addon/filters/audio_filter.o: In function `audio_filter_free_state':
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:874: undefined reference to `av_frame_free'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:875: undefined reference to `av_frame_free'
objs/addon/filters/audio_filter.o: In function `audio_filter_read_filter_sink':
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:1131: undefined reference to `av_frame_unref'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:1101: undefined reference to `av_buffersink_get_frame_flags'
objs/addon/filters/audio_filter.o: In function `audio_filter_init_sink':
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:451: undefined reference to `av_int_list_length_for_size'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:451: undefined reference to `av_opt_set_bin'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:466: undefined reference to `av_int_list_length_for_size'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:466: undefined reference to `av_opt_set_bin'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:481: undefined reference to `av_int_list_length_for_size'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:481: undefined reference to `av_opt_set_bin'
objs/addon/filters/audio_filter.o: In function `audio_filter_alloc_state':
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:781: undefined reference to `avfilter_graph_parse_ptr'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:807: undefined reference to `av_frame_alloc'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:814: undefined reference to `av_frame_alloc'
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:803: undefined reference to `av_buffersink_set_frame_size'
objs/addon/filters/audio_filter.o: In function `audio_filter_process_frame':
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:1181: undefined reference to `av_frame_unref'
objs/addon/filters/audio_filter.o: In function `audio_filter_choose_source':
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:1230: undefined reference to `avfilter_graph_request_oldest'
objs/addon/filters/audio_filter.o: In function `audio_filter_process_frame':
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:1207: undefined reference to `av_buffersrc_add_frame_flags'
objs/addon/filters/audio_filter.o: In function `audio_filter_choose_source':
/opt/NGINX/nginx-vod-module/vod/filters/audio_filter.c:1265: undefined reference to `av_buffersrc_get_nb_failed_requests'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/opt/nginx-1.10.0'
make: *** [build] Error 2

**Comment by erankor** [comment]
Looks like you have some problem with ffmpeg (libavfilter/libavcodec), unless you need to use audio filtering, easiest solution would be remove ffmpeg. For example, `export LIB_AV_UTIL=xxx` should make the ffmpeg detection fail and compile without it.

**Comment by Natarajan92** [comment]
Thanks for your immediate response, But can you please explain more on disabling ffmpeg / ffmpeg detection fail. 

By compiling it without ffmpeg, wont affect dash/hls conversion ?

**Comment by erankor** [comment]
No, the only use of ffmpeg in this project is for audio filtering. Audio filtering enables:
1. mixing several audio streams together
2. changing the audio gain (volume)
3. changing the playback rate
Most deployments do not use these features, and therefore do not require ffmpeg

**Comment by Natarajan92** [comment]
Ok! thanks, How to disable this ffmpeg feature. The example you said "export LIB_AV_UTIL=xxx" is not clear to me. Where to use this command to disable ffmpeg while compling

**Comment by erankor** [comment]
Use it when you run configure, this environment variable can be used to configure how to link with ffmpeg (statically or dynamically) if you set it to some gibberish, compilation will fail during ffmpeg detection and ffmpeg will not be used.
Note that this will only work on the latest version.

**Comment by Natarajan92** [comment]
Nginx-vod-module source is "https://github.com/kaltura/nginx-vod-module.git"

NGINX - 1.10.0

1) cd nginx source
2) ./configure --add-module=/opt/NGINX/nginx-vod-module --with-file-aio --with-threads --with-cc-opt="-O3" --add-module=/opt/nginx-rtmp-module-master --with-http_ssl_module
3)make 

error:

-ldl -lpthread -lpthread -lcrypt -lcrypto -lrt -lavcodec xxx -lavfilter xxx -lpcre -lssl -lcrypto -ldl -lz \
	-Wl,-E
cc: error: xxx: No such file or directory
cc: error: xxx: No such file or directory
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/opt/nginx-1.10.0'
make: *** [build] Error 2
[root@Natarajan nginx-1.10.0]# 


As you said i have used export command for ffmpeg, even than error only

**Comment by erankor** [comment]
Sorry, I see now that LIB_AV_UTIL is not used in detection phase, use this instead:
```
export LIB_AV_CODEC=xxx
export LIB_AV_FILTER=xxx
```
After you do that, you should see this in the output of configure:
```
checking for libavcodec ... not found
checking for libavfilter ... not found
```
And that should compile

**Comment by Natarajan92** [comment]
Thanks, build is completed
