### ISSUE TITLE
Remote mode with S3 as upstream

### ISSUE THREAD

**Issue by lsc** [kaltura/nginx-vod-module#337]
I am sorry if this is the wrong place, but I couldn't find a mailing list or something similar.
All configuration is added at the end of the ticket.

We've succesfully used the vod module in local mode over NFS, but the decision was made to migrate over to AWS, and I am struggling to get the vod module to read the mp4 files from S3.

I've tried a bunch of different configuration options, having the vod configuration options in the server part, having it in the location part, having all of the configuration in one location instead of using an internal proxy. 

I based the configuration for the hls endpoint on the example configuration in the Readme.

So what part of this setup did i fuck up? 
Do you need or want more information?
Should I try a later tag (we are using 1.7 right now)? 
Do I need the PCRE library for any of this to work?
Is S3 just really annoying to work with? 

Any input, big or small, suggestions, ideas and criticism are welcome. If another fora is better for this kind of question feel free to inform me.

Thank you for taking the time.

Example request: 
` curl 'http://ec2-instance.eu-west-1.compute.amazonaws.com/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/,240p,.mp4.urlset/master.m3u8'``

And returns:       
`<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>`

My error log says 

`2016/06/20 09:50:05 [error] 24073#0: *112 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 212.181.123.156, server: _, request: "GET /hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/,240p,.mp4.urlset/master.m3u8 HTTP/1.1", host: "ec2-instance.eu-west-1.compute.amazonaws.com"`

But going to the test location and proxying over to S3 works if we remove the vod dependency.
`curl 'http://ec2-instance.eu-west-1.compute.amazonaws.com/test/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240p.mp4' -O`

`% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.7M  100 16.7M    0     0  7704k      0  0:00:02  0:00:02 --:--:-- 7707k`

Nginx is configured with:
 _**configure arguments: --add-module=../nginx-vod-module-1.7 --without-http_rewrite_module --prefix=/opt/nginx**_

And just to be sure that the vod module actually is loaded.

``` 
curl 'http://ec2-instance.eu-west-1.compute.amazonaws.com/status/' --verbose                                                                                      157ms  Mon Jun 20 12:20:03 2016
*   Trying 52.16.58.230...
* Connected to ec2-instance.eu-west-1.compute.amazonaws.com (xxx.xxx.xxx.xxx) port 80 (#0)
> GET /status/ HTTP/1.1
> Host: ec2-instance.eu-west-1.compute.amazonaws.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 20 Jun 2016 10:20:08 GMT
< Content-Type: text/xml
< Content-Length: 117
< Connection: keep-alive
< ETag: "-1-75"
<
<?xml version="1.0" encoding="utf-8" ?>
<vod>
<version>1.0</version>
<built>May 16 2016 08:36:06</built>
</vod>
* Connection #0 to host ec2-instance.eu-west-1.compute.amazonaws.com left intact 
```

**_nginx.conf_** (Comments removed for brevity)

```
user nginx;
worker_processes 1;
pid /opt/nginx/nginx.pid;
worker_rlimit_nofile 8192;

events {
  worker_connections  8000;
  use epoll;
}


http {
        sendfile on;
        tcp_nopush on; # off may be better for Comet/long-poll stuff
        tcp_nodelay off; # on may be better for Comet/long-poll stuff
        types_hash_max_size 2048;
        server_tokens off;
        server_names_hash_bucket_size 64;
        include /opt/nginx/conf/mime.types;
        default_type application/octet-stream;

        log_format   main '$remote_addr - $remote_user [$time_local]  $status '
                    '"$request" $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
        log_format   timed_combined '$remote_addr - $remote_user [$time_local]  $status '
                    '"$request" $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    '$request_time $upstream_response_time $pipe';
        access_log /opt/nginx/logs/access.log main;
        error_log /opt/nginx/logs/error.log;

        gzip on;
        gzip_disable "msie6";

        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 4;
        gzip_buffers 16 8k;
        gzip_min_length 512;
        gzip_http_version 1.1;

        gzip_types text/css text/javascript application/x-javascript text/xml text/plain text/x-component application/javascript application/json application/xml application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml;

        map $scheme $server_https {
                default off;
                https on;
        }

        limit_req_zone  $binary_remote_addr  zone=one:10m   rate=5r/s;
        include /opt/nginx/conf/vod.conf;
}
```

_*vod.conf*_
```
upstream s3bucket {
	server our-s3-bucket:80;
}

server {
	listen      80;
	server_name _;

	access_log /opt/nginx/logs/vod_access.log;
	error_log /opt/nginx/logs/vod_error.log;

	open_file_cache          max=1000 inactive=5m;
	open_file_cache_valid    2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors   on;

	gzip on;
	gzip_types application/x-mpegURL;

	location /test/ {
		proxy_pass http://s3bucket/;

		proxy_set_header       Authorization '';
		proxy_hide_header      x-amz-id-2;
		proxy_hide_header      x-amz-request-id;
		proxy_hide_header      Set-Cookie;
		proxy_ignore_headers   "Set-Cookie";
		proxy_buffering        off;
		proxy_set_header       Host our-s3-bucket;
	}

	location ^~ /s3/ {

		internal;
		proxy_pass http://our-s3-bucket

		proxy_set_header       Authorization '';
		proxy_hide_header      x-amz-id-2;
		proxy_hide_header      x-amz-request-id;
		proxy_hide_header      Set-Cookie;
		proxy_ignore_headers   "Set-Cookie";
		proxy_buffering        off;
		proxy_set_header       Host $http_host;

	}

	location ^~ /hls/ {

		vod hls;

		vod_mode remote;
		vod_upstream_location /s3;
		vod_metadata_cache metadata_cache 256m;
		vod_response_cache response_cache 256m;

		add_header Access-Control-Allow-Headers '*';
		add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
		add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		add_header Access-Control-Allow-Origin '*';

		proxy_set_header       Authorization '';
		proxy_hide_header      x-amz-id-2;
		proxy_hide_header      x-amz-request-id;
		proxy_hide_header      Set-Cookie;
		proxy_ignore_headers   "Set-Cookie";
		proxy_buffering        off;
		proxy_set_header       Host $http_host;

		expires 100d;
	}

	location /status/ {
		vod_status;
	}
}```

**Comment by erankor** [comment]
If I'm not mistaken, with your conf it will hit `http://ec2-instance.eu-west-1.compute.amazonaws.com/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240p.mp4`, not .../test/..
But easiest way to know for sure is to compile with debug strings - add `--with-debug` to the configure line and add `debug` to the error_log directive in the conf.
You'll then see exactly what URL was requested in the error log.

**Comment by lsc** [comment]
Yeah sorry, that's an error in my rewrite of the conf to exclude our specific bucket names.

Both /test/ and /s3/ proxies to our bucket on S3. 

Am I correct in assuming that the "vod_upstream_location" is a nginx location configured on the same nginx configuration? 

I will rebuild with debug logging on and see if that gives me more insight.

Thanks for the input

**Comment by erankor** [comment]
Yes, correct, nginx-vod uses nginx subrequests to other locations to issue http requests

**Comment by lsc** [comment]
I turned on the debug loggin on a new machine and stripped out most of the header hiding. 

The interesting part for me was this one (full log attached at the end).

Host: vod-bucket-staging.s3-eu-west-1.amazonaws.com
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
DNT: 1
Accept-Language: en,sv;q=0.8,en-GB;q=0.6,de;q=0.4
Range: bytes=0-4095

"
2016/06/21 09:56:53 [debug] 1370#0: *17 http cleanup add: 000000000139A758
2016/06/21 09:56:53 [debug] 1370#0: *17 get rr peer, try: 1
2016/06/21 09:56:53 [debug] 1370#0: *17 stream socket 12
2016/06/21 09:56:53 [debug] 1370#0: *17 epoll add connection: fd:12 ev:80002005
2016/06/21 09:56:53 [debug] 1370#0: *17 connect to 54.231.133.19:80, fd:12 #18
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream connect: -2
2016/06/21 09:56:53 [debug] 1370#0: *17 posix_memalign: 00000000013B1030:128 @16
2016/06/21 09:56:53 [debug] 1370#0: *17 event timer add: 12: 60000:1466503073137
2016/06/21 09:56:53 [debug] 1370#0: *17 http finalize request: -4, "/s3/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240pntm_384p.mp4?" a:1, c:3
2016/06/21 09:56:53 [debug] 1370#0: *17 http request count:3 blk:0
2016/06/21 09:56:53 [debug] 1370#0: *17 http run request: "/s3/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240pntm_384p.mp4?"
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream check client, write event:1, "/s3/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240pntm_384p.mp4"
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream recv(): -1 (11: Resource temporarily unavailable)
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream request: "/s3/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240pntm_384p.mp4?"
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream send request handler
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream send request
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream send request body
2016/06/21 09:56:53 [debug] 1370#0: *17 chain writer buf fl:1 s:482
2016/06/21 09:56:53 [debug] 1370#0: *17 chain writer in: 000000000139A770
2016/06/21 09:56:53 [debug] 1370#0: *17 writev: 482 of 482
2016/06/21 09:56:53 [debug] 1370#0: *17 chain writer out: 0000000000000000
2016/06/21 09:56:53 [debug] 1370#0: *17 event timer del: 12: 1466503073137
2016/06/21 09:56:53 [debug] 1370#0: *17 event timer add: 12: 60000:1466503073138
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream request: "/s3/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240pntm_384p.mp4?"
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream process header
2016/06/21 09:56:53 [debug] 1370#0: *17 recv: fd:12 591 of 8193
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy status 404 "404 Not Found"
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy header: "x-amz-request-id: E10F4E3969662F5A"
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy header: "x-amz-id-2: rjSD5c1Xm68FyLZhq47LKC7sfsqpOX1NTnF9RxZwbaCofw7AiLj2vfg/FAwd/HMXn7bIKdyyJ/w="
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy header: "Content-Type: application/xml"
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy header: "Date: Tue, 21 Jun 2016 09:56:52 GMT"
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy header: "Connection: close"
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy header: "Server: AmazonS3"
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy header done
2016/06/21 09:56:53 [debug] 1370#0: *17 http proxy filter init s:404 h:0 c:0 l:-1
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream process body on memory
2016/06/21 09:56:53 [debug] 1370#0: *17 recv: fd:12 -1 of 7602
2016/06/21 09:56:53 [debug] 1370#0: *17 recv() not ready (11: Resource temporarily unavailable)
2016/06/21 09:56:53 [debug] 1370#0: *17 event timer: 12, old: 1466503073138, new: 1466503073152
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream request: "/s3/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240pntm_384p.mp4?"
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream dummy handler
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream request: "/s3/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240pntm_384p.mp4?"
2016/06/21 09:56:53 [debug] 1370#0: *17 http upstream process body on memory
2016/06/21 09:56:53 [debug] 1370#0: *17 recv: fd:12 0 of 7602
2016/06/21 09:56:53 [debug] 1370#0: *17 finalize http upstream request: 0
2016/06/21 09:56:53 [debug] 1370#0: *17 finalize http proxy request
2016/06/21 09:56:53 [debug] 1370#0: *17 free rr peer 1 0
2016/06/21 09:56:53 [debug] 1370#0: *17 close http upstream connection: 12
2016/06/21 09:56:53 [debug] 1370#0: *17 free: 00000000013B1030, unused: 48
2016/06/21 09:56:53 [debug] 1370#0: *17 event timer del: 12: 1466503073138
2016/06/21 09:56:53 [debug] 1370#0: *17 reusable connection: 0
2016/06/21 09:56:53 [debug] 1370#0: *17 http finalize request: 0, "/s3/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240pntm_384p.mp4?" a:1, c:2
2016/06/21 09:56:53 [debug] 1370#0: *17 ngx_child_request_finished_handler: error code 0
2016/06/21 09:56:53 [debug] 1370#0: *17 http wake parent request: "/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240p,ntm_384p,.mp4.urlset/master.m3u8?"
2016/06/21 09:56:53 [debug] 1370#0: *17 http posted request: "/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240p,ntm_384p,.mp4.urlset/master.m3u8?"
2016/06/21 09:56:53 [error] 1370#0: *17 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 212.181.123.156, server: _, request: "GET /hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240p,ntm_384p,.mp4.urlset/master.m3u8 HTTP/1.1", host: "ec2-52-51-226-35.eu-west-1.compute.amazonaws.com"
2016/06/21 09:56:53 [debug] 1370#0: *17 ngx_http_vod_handle_read_completed: read failed 502
2016/06/21 09:56:53 [debug] 1370#0: *17 http finalize request: 502, "/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240p,ntm_384p,.mp4.urlset/master.m3u8?" a:1, c:1
2016/06/21 09:56:53 [debug] 1370#0: *17 event timer del: 3: 1466503073137
2016/06/21 09:56:53 [debug] 1370#0: *17 http special response: 502, "/hls/00/0014c1d7-1cc8-46d5-89f4-92d4e7e19ec4/240p,ntm_384p,.mp4.urlset/master.m3u8?"
2016/06/21 09:56:53 [debug] 1370#0: *17 http set discard body
2016/06/21 09:56:53 [debug] 1370#0: *17 HTTP/1.1 502 Bad Gateway
Server: nginx
Date: Tue, 21 Jun 2016 09:56:53 GMT
Content-Type: text/html
Content-Length: 568
Connection: keep-alive

**Comment by erankor** [comment]
Yes, with your configuration it does. To get rid of the /s3 you need to add a slash at the end of the proxy_pass directive:
```
proxy_pass http://our-s3-bucket/;
```
This is documented here:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
```
If the proxy_pass directive is specified with a URI, then when a request is passed to the server, the part of a normalized request URI matching the location is replaced by a URI specified in the directive
```
if you want to get rid of the /hls as well, then you can change the location of the proxy_pass from /s3 to /s3/hls

**Comment by lsc** [comment]
Sorry about that. 

On a personal note, I got it to work. What I changed was doing this.

- remove the upstream block
- in the /s3 location, spell out the whole FQDN of our S3 bucket 
 
A big thank you for taking the time to answer my questions, if you happen to be in Stockholm I'll buy you a beverage of your choice. 

Our configuration looks like this now 
```
server {
        listen      80;
        server_name _;

        access_log off;
        error_log /opt/nginx/logs/vod_error.log debug;

        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        vod_mode remote;
        vod_metadata_cache metadata_cache 256m;
        vod_response_cache response_cache 256m;

        vod_upstream_location /s3;

        location /s3/ {
                internal;
                proxy_pass http://our-s3-bucket.s3-eu-west-1.amazonaws.com/;
        }

        location /hls/ {
                vod hls;
                gzip on;
                gzip_types application/x-mpegURL;

                add_header Access-Control-Allow-Origin "*";
        }

        location /hds/ {

                vod hds;
                vod_segment_duration 6000;
                vod_align_segments_to_key_frames on;
                vod_segment_count_policy last_rounded;

                add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
                add_header Access-Control-Allow-Origin "*";
                expires 100d;
        }

        location /crossdomain.xml {
                alias /opt/nginx/html/crossdomain.xml;
                access_log off;
        }

        location /status/ {
                vod_status;
        }
}
```

**Comment by erankor** [comment]
Glad to hear, thanks for the update

**Comment by jersobh** [comment]
I have the same issue, but it keep giving me 
ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client

**Comment by erankor** [comment]
I suggest you check the request that is going out to the upstream, and check why it returns 404. 
If you use plain http (not https) you can simply use tcpdump. Otherwise, you can compile with debug strings enabled and check the error log.

**Comment by jersobh** [comment]
I've changed it a bit. Now it returns the video (the /s3 endpoint) but still can't get the hls

**Comment by erankor** [comment]
what is the error?

**Comment by jersobh** [comment]
Failed to load http://x.x.x.x/hls/097d9164-5bc7-4312-a3ea-383c9b431481.mp4/master.m3u8: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 502.

 ngx_child_request_wev_handler: upstream returned a bad status 403 while sending to client, client: x.x.x.x, server: localhost, request: "GET /hls/097d9164-5bc7-4312-a3ea-383c9b431481.mp4/master.m3u8 HTTP/1.1", host: "x.x.x.x", referrer: "http://localhost/small/"


BUT the /s3 endpoint http://x.x.x.x/s3/097d9164-5bc7-4312-a3ea-383c9b431481.mp4 loads fine.

**Comment by erankor** [comment]
Well, the error is clear... nginx-vod-module got an error from the upstream. 
I suggest you capture the request to upstream (as I wrote above, either using tcpdump or nginx debug strings) and send the exact same request, you will surely get this error

**Comment by Stiff91x** [comment]
Hi guys, my cleaned nginx config:

    upstream kalapi {
                    server www.pr0t3ck.altervista.org:80;
            }

    server {
            listen 80;
            listen [::]:80;
            resolver 8.8.8.8;

    # vod settings
                    vod_mode remote;
                    vod_upstream_location /kalapi;
                    vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
                    vod_last_modified_types *;

                    # vod caches
                    vod_metadata_cache metadata_cache 512m;
                    vod_response_cache response_cache 128m;

                    # gzip manifests
                    gzip on;
                    gzip_types application/vnd.apple.mpegurl;

                    location /kalapi/ {
                            internal;
                            proxy_pass http://kalapi/;
                            proxy_set_header Host $http_host;
                    }

                    location ~ ^/p/\d+/(sp/\d+/)?serveFlavor/ {
                            vod hls;

                            add_header Access-Control-Allow-Headers '*';
                            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                            add_header Access-Control-Allow-Origin '*';
                            expires 100d;
                    }
    }

and this is the call: http://{NGINX_SERVER_IP}/kalapi/content/vod.mp4/playlist.m3u8
and the file is stored in: pr0t3ck.altervista.org/content/vod.mp4

every time i get 404 (nginx error.log is cleaned) and i don't know how to do it :(

Thank you very much!!!

**Comment by xXxSPYxXx** [comment]
@Stiff91x you cant call to internal location /kalapi.
Your location maybe like this:
`
                location /content {
                        vod hls;
                        add_header Access-Control-Allow-Headers '*';
                        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                        add_header Access-Control-Allow-Origin '*';
                        expires 100d;
                }
`

so you call is:  http://{NGINX_SERVER_IP}/content/vod.mp4/playlist.m3u8
