### ISSUE TITLE
Webvtt playback issue

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#343]
Hi Eran,

I have multi-profile encrypted mp4 files and webvtt file. Am using Mapped mode configuration to do on-the-fly conversion of dash/hls. For closed captioning, how we need to pass webvtt file ?

I need to pass it in mapping-json file under clip object ?

**Comment by erankor** [comment]
You need to add webvtt as if it were another video rendition, so, if you use a JSON like this https://github.com/kaltura/nginx-vod-module/#adaptive-set you'd need to add another element to the `sequences` array, that contains a single element clips array (like the existing elements there)
If you are using multi url (https://github.com/kaltura/nginx-vod-module/#multi-url-structure) you just need to add another sub url that will map to the webvtt file.
Note that by default the webvtt file is assumed to be English, to change that you need to set the `language` property on the sequence object to the 3 character code of the language (e.g. `eng`)

**Comment by Natarajan92** [comment]
CC are not displayed, but manifest file is having information about subtitle codecs in it. 

In Mapping Json am using as like this 

{
    "sequences": [
	{
            "clips": [
                {
                    "type": "source",
                    "path": "/var/bfs/test/lab/videoenc/video.vtt"
                }
            ]
        },
        {
            "clips": [
                {
                    "type": "source",
                    "path": "/var/bfs/test/lab/videoenc/video-700k.mp4",
                    "encryptionKey":"g4kQKd9XDUPp8G1m2quZwg=="
                }
            ]
        }
    ]
}

Example of manifest file 

<AdaptationSet
        contentType="text"
        lang="en"
        mimeType="text/vtt">
      <Representation
          id="textstream_en_0"
          bandwidth="0">
        <BaseURL>http://IP-Address:port/lab/videoenc/video-3000k.mp4/sub-f1.vtt</BaseURL>
      </Representation>
    </AdaptationSet>

**Comment by erankor** [comment]
You don't have an option to choose captions ? iPhone does not display them automatically, the user has to select the captions

**Comment by Natarajan92** [comment]
As i said,there is issue in playback of m3u8 file in apple https://github.com/kaltura/nginx-vod-module/issues/318.So am testing in STB with manifest.mpd file. Am not testing it in apple device. In STB it will automatically detect CC. If i pass webvtt file directly under video tag of HTML5 player it is displaying CC. When we try within manifest file by using vtt file path in mapping json. It is not displaying CC

**Comment by erankor** [comment]
Unfortunately, there are several ways to embed captions in a DASH stream, I've seen at least 3 completely different ways of doing that, so it possible that the device is expecting to get it in some different form. The format generated by this module is working on Shaka player.
Do you some MPD sample that is showing captions on the device ?

**Comment by Natarajan92** [comment]
Still now, we have tried by passing CC in video tag element of html5 page only. So i don't have sample MPD file that shows captions on device

**Comment by Natarajan92** [comment]
As i said, am passing webvtt file in html5 in <track> element. When i use pre-packaged Dash streaming Closed Caption is syncing properly. Same vtt file if i use for on-the-fly conversion, CC synchronization is having problem. 

sample html5 :

        <video autoplay controls crossOrigin="Anonymous">

        #this url for on-the fly conversion
           <source src="http://172.148.0.14:8005/lab/video/video-1200k.mp4/manifest.mpd"/>
       #this url for pre-packaged dash stream   
           
	  <track label="English" kind="subtitles" srclang="en" src="http://172.148.0.14/lab/video/video.vtt" default>
		</video>

Both are same assets, one is packaged and one is normal mp4file for on-fly-conversion, using same vtt file for both. Can you give details or idea on why this synchronization problem is coming

**Comment by erankor** [comment]
what is the timing difference between the captions and the video ?
also, send links to both mpds

**Comment by Natarajan92** [comment]
I will mail you the details and link to manifest files

**Comment by Natarajan92** [comment]
I have mailed you the link. please check

**Comment by Natarajan92** [comment]
Are you able to get details from that link's ?

**Comment by erankor** [comment]
I've just played it on Shaka player (http://shaka-player-demo.appspot.com/demo/) and as far as I can see the in band subtitles are in perfect sync, so I do not consider this a problem in this module.
Only relevant difference I can think of between the prepackaged version and the on-the-fly version is that the on-the-fly reports an initial PTS of 7508/90000 (~1/11 sec), while the prepackaged returns 0, but I doubt this difference is noticeable.

**Comment by Natarajan92** [comment]
Issue solved. Thanks Eran
