### ISSUE TITLE
Adaptive bit rate in nginx-vod-module in NGINX .

### ISSUE THREAD

**Issue by MonkeyMajik** [kaltura/nginx-vod-module#347]
there i have a problem about
Adaptive bit rate in nginx-vod-module in NGINX .

like where i post a url  http://192.168.192.101:11211/hlsnginx/,aa,aa_low,.mp4.urlset/master.m3u8 
there i found the m3u8 content like below:
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=323292,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
http://192.168.192.101:11211/hlsnginx/aa.mp4/index-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=323292,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
http://192.168.192.101:11211/hlsnginx/aa_low.mp4/index-v1-a1.m3u8 

but how can i get the content like:(set the domain and port and path invisible)
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=323292,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
index-f1-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=323292,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
index-f2-v1-a1.m3u8

my conf is :
location /hlsnginx{

 vod hls;
 vod_mode local;

 vod_base_urlhttp://192.168.192.101:11211;
  
 vod_segment_duration 16000;

 gzip on;
 gzip_types application/vnd.apple.mpegurl;
  
expires 100d;
add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
       }

**Comment by erankor** [comment]
add `vod_hls_absolute_master_urls off`

**Comment by MonkeyMajik** [comment]
But when i add  **vod_hls_absolute_master_urls off**

i found the sub request was wrong like i post the master request：
http://192.168.192.101:11211/hlsnginx/,aa,aa_low,.mp4.urlset/master.m3u8 

then i use   **vod_hls_absolute_master_urls off**

the sub request was 
http://192.168.192.101:11211**/hlsnginx/,aa,aa_low,.mp4/**index-f1-v1-a1.m3u8

so how can i get the right sub request like:

http://192.168.192.101:11211**/hlsnginx/aa.mp4/**index-f1-v1-a1.m3u8 ?

**Comment by erankor** [comment]
you are asking for something that doesn't make sense, the base url of master is:
`http://192.168.192.101:11211/hlsnginx/,aa,aa_low,.mp4.urlset`
if you tell the module to use relative urls, this will be the base of all index m3u8s, that's how the player turns the relative urls to absolute, the player is not familiar with multi url structure used by this module.
if you want the index m3u8 to look like this:
`http://192.168.192.101:11211**/hlsnginx/aa.mp4/index.m3u8`
then you have to use absolute urls in the master.
I can understand why in some cases absolute urls can be problematic (e.g. when the server behind a nat or something similar), but I don't really understand why you care about how the url looks like

**Comment by MonkeyMajik** [comment]
er ... because some video‘s url was need protected . i use a proxy program post the request inside。but the domain was revelationde by master m3u8 file

thanks

**Comment by erankor** [comment]
you can use `vod_base_url` to control the returned domain, the default is something like `$scheme://$http_host`

**Comment by MonkeyMajik** [comment]
the domain should have invisible but now i can only find same way to control the returned domain ，thanks all the same ^v^.
