### ISSUE TITLE
can't compile in Debian 32 bit

### ISSUE THREAD

**Issue by Classsic** [kaltura/nginx-vod-module#349]
I try compile on Debian 32bit and get this error:
`../nginx-vod-module-master/vod/mp4/mp4_parser.c: In function ‘mp4_parser_parse_stsd_atom’:
../nginx-vod-module-master/vod/mp4/mp4_parser.c:1941:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (size > end_pos - cur_pos)
            ^
cc1: all warnings being treated as errors
objs/Makefile:2084: recipe for target 'objs/addon/mp4/mp4_parser.o' failed
make[1]: *** [objs/addon/mp4/mp4_parser.o] Error 1
make[1]: Leaving directory '/root/nginx-1.10.1'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
`
Please, somebody have successfully compile vod module in 32bit?
Thanks.

**Comment by erankor** [comment]
Try changing this line from:
`if (size > end_pos - cur_pos)`
to:
`if (size > (uint32_t)(end_pos - cur_pos))`

The module compiled successfully in 32 bit a few versions back, but all our test environments are 64 bit, so this breaks frequently...

**Comment by Classsic** [comment]
yes, it works! but  I get this error:
`2016/06/29 23:48:18 [error] 1062#0: *19 ngx_http_vod_handle_read_completed: bytes read is zero while reading media header, client: 10.20.0.1`
when trying to test it.
I already have this config in 64bit deb, all the same.
Any idea what I missing?

**Comment by erankor** [comment]
this usually means the media file is invalid, does it play for you by itself ?
if so, please send it to me

**Comment by Classsic** [comment]
Yes, the mp4 are fine, how i can send an example to you?

**Comment by erankor** [comment]
Send a link to: eran.kornblau at kaltura dot com
But just to make sure I understand - 64 bit does not work either, right ?

**Comment by Classsic** [comment]
Hi, I recompile without aio, and get this error:
`     2016/07/04 15:57:52 [error] 12573#0: *21 ngx_http_vod_get_async_read_result: buffer size 0 is smaller than buffer offset 172 while reading media header, client: 10.20.0.1, server: , request: "GET /local/api/playlist/56f006922b10b8440f9a9cc6/5718cf4315e650ef2ce49bf6/1467644220000/1467647059990/1/index.m3u8 HTTP/1.1""`
Some trouble with buffer.c in 32bit?
The videos work on 64 bits, later I send to you the samples.

**Comment by erankor** [comment]
fixed here: https://github.com/kaltura/nginx-vod-module/pull/356

**Comment by erankor** [comment]
Btw, note that it may be possible that large (>2gb) files will not work well in 32 bit, for production use I'd strongly recommend 64 bit.

**Comment by erankor** [comment]
can this be closed ?

**Comment by Classsic** [comment]
Perfect! Thanks for fix it!
