### ISSUE TITLE
Remote mode with S3 and load balancer

### ISSUE THREAD

**Issue by lykata** [kaltura/nginx-vod-module#351]
Greetings!

I have been trying to set up ELB + EC2 instance + S3 without any success. Everything seems to work fine with only EC2 and S3. The problem seems to arise when a load balancer comes into play.

My nginx configuration with nginx version 1.11.1 is following: 
`./configure --add-module=../nginx-vod-module-1.7 --with-http_ssl_module --with-http_realip_module --without-http_rewrite_module --prefix=/opt/nginx --with-debug --with-cc-opt='-O0 -g'`

In my attempts to find out what the problem is I have used cURL and gdb. Here are my tests:

First test - curl directly towards ec2 instance (no proxy). Works like a charm!

`curl -k http://ec2instance.amazonaws.com/hls/c6/c6ee6e98-50d4-499c-8275-a31afcaf915c/,240p,.mp4.urlset/master.m3u8 
`

Second test - Local mode - Me pretending to be a load balancer, by providing my own IP in the X-Forwarded-For header. No problem whatsoever.

`curl -k http://ec2instance.amazonaws.com/local/c6/c6ee6e98-50d4-499c-8275-a31afcaf915c/,240p,.mp4.urlset/master.m3u8 -H "X-Forwarded-For : X.X.X.X"
`

Third test - Remote mode - Me pretending to be a load balancer, by providing my own IP in the X-Forwarded-For header. An empty answer is received.

`curl -k http://ec2instance.amazonaws.com/hls/c6/c6ee6e98-50d4-499c-8275-a31afcaf915c/,240p,.mp4.urlset/master.m3u8 -H "X-Forwarded-For : X.X.X.X"
`

I look at the debug log to see what's going on: 

2016/06/30 13:39:21 [debug] 29508#0: *146 http process request line
2016/06/30 13:39:21 [debug] 29508#0: *146 http request line: "GET /hls/c6/c6ee6e98-50d4-499c-8275-a31afcaf915c/,240p,.mp4.urlset/master.m3u8 HTTP/1.1"
2016/06/30 13:39:21 [debug] 29508#0: *146 http uri: "/hls/c6/c6ee6e98-50d4-499c-8275-a31afcaf915c/,240p,.mp4.urlset/master.m3u8"
2016/06/30 13:39:21 [debug] 29508#0: *146 http args: ""
2016/06/30 13:39:21 [debug] 29508#0: *146 http exten: "m3u8"
2016/06/30 13:39:21 [debug] 29508#0: *146 http process request header line
2016/06/30 13:39:21 [debug] 29508#0: *146 http header: "User-Agent: curl/7.38.0"
2016/06/30 13:39:21 [debug] 29508#0: *146 http header: "Host: ec2instance.amazonaws.com"
2016/06/30 13:39:21 [debug] 29508#0: *146 http header: "Accept: */*"
2016/06/30 13:39:21 [debug] 29508#0: *146 http header: "X-Forwarded-For: X.X.X.X"
2016/06/30 13:39:21 [debug] 29508#0: *146 http header done
2016/06/30 13:39:21 [debug] 29508#0: *146 event timer del: 13: 1467294021216
2016/06/30 13:39:21 [debug] 29508#0: *146 generic phase: 0
2016/06/30 13:39:21 [debug] 29508#0: *146 add cleanup: 0000000000A511B0
2016/06/30 13:39:21 [debug] 29508#0: *146 test location: "/local/"
2016/06/30 13:39:21 [debug] 29508#0: *146 test location: "/hls/"
2016/06/30 13:39:21 [debug] 29508#0: *146 using configuration "/hls/"
2016/06/30 13:39:21 [debug] 29508#0: *146 http cl:-1 max:1048576
2016/06/30 13:39:21 [debug] 29508#0: *146 generic phase: 2
2016/06/30 13:39:21 [debug] 29508#0: *146 generic phase: 3
2016/06/30 13:39:21 [debug] 29508#0: *146 generic phase: 4
2016/06/30 13:39:21 [debug] 29508#0: *146 access phase: 5
2016/06/30 13:39:21 [debug] 29508#0: *146 access phase: 6
2016/06/30 13:39:21 [debug] 29508#0: *146 post access phase: 7
2016/06/30 13:39:21 [debug] 29508#0: *146 ngx_http_vod_handler: started
2016/06/30 13:39:21 [debug] 29508#0: *146 http set discard body
2016/06/30 13:39:21 [debug] 29508#0: *146 posix_memalign: 0000000000A42D70:4096 @16
2016/06/30 13:39:21 [debug] 29508#0: *146 ngx_http_vod_handler: response cache miss
2016/06/30 13:39:21 [debug] 29508#0: *146 ngx_http_vod_state_machine_parse_metadata: metadata cache miss
2016/06/30 13:39:21 [debug] 29508#0: *146 malloc: 0000000000A43D80:8193
2016/06/30 13:39:21 [debug] 29508#0: *146 posix_memalign: 0000000000A45D90:4096 @16
2016/06/30 13:39:21 [debug] 29508#0: *146 http subrequest "/s3/hls/c6/c6ee6e98-50d4-499c-8275-a31afcaf915c/240p.mp4?"
2016/06/30 13:39:21 [debug] 29508#0: *146 ngx_child_request_start: completed successfully sr=0000000000A43530
2016/06/30 13:39:21 [debug] 29508#0: *146 ngx_http_vod_handler: done
2016/06/30 13:39:21 [debug] 29508#0: *146 http finalize request: -2, "/hls/c6/c6ee6e98-50d4-499c-8275-a31afcaf915c/,240p,.mp4.urlset/master.m3u8?" a:0, c:2
2016/06/30 13:39:21 [debug] 29508#0: *146 event timer add: 13: 60000:1467294021216
2016/06/30 13:39:21 [debug] 29508#0: *146 http posted request: "/s3/hls/c6/c6ee6e98-50d4-499c-8275-a31afcaf915c/240p.mp4?"
2016/06/30 13:39:21 [debug] 29508#0: *146 test location: "/local/"
2016/06/30 13:39:21 [debug] 29508#0: *146 test location: "/status/"
2016/06/30 13:39:21 [debug] 29508#0: *146 test location: "/s3/"
2016/06/30 13:39:21 [debug] 29508#0: *146 using configuration "/s3/"
2016/06/30 13:39:21 [debug] 29508#0: *146 http cl:-1 max:1048576
2016/06/30 13:39:21 [debug] 29508#0: *146 generic phase: 2  **This is where it starts to fail..**
2016/06/30 13:39:21 [debug] 29650#0: epoll add event: fd:8 op:1 ev:00002001
2016/06/30 13:39:21 [debug] 29650#0: accept on 0.0.0.0:80, ready: 0
2016/06/30 13:39:21 [debug] 29650#0: posix_memalign: 0000000000A5A100:512 @16
2016/06/30 13:39:21 [debug] 29650#0: *147 accept: 10.200.10.251:41799 fd:3
2016/06/30 13:39:21 [debug] 29650#0: *147 event timer add: 3: 60000:1467294021318
2016/06/30 13:39:21 [debug] 29650#0: *147 reusable connection: 1
2016/06/30 13:39:21 [debug] 29650#0: *147 epoll add event: fd:3 op:1 ev:80002001
2016/06/30 13:39:21 [debug] 29650#0: accept on 0.0.0.0:80, ready: 0
2016/06/30 13:39:21 [debug] 29650#0: posix_memalign: 0000000000A5A310:512 @16
2016/06/30 13:39:21 [debug] 29650#0: *148 accept: 10.200.10.198:1274 fd:12
2016/06/30 13:39:21 [debug] 29650#0: *148 event timer add: 12: 60000:1467294021318
2016/06/30 13:39:21 [debug] 29650#0: *148 reusable connection: 1
2016/06/30 13:39:21 [debug] 29650#0: *148 epoll add event: fd:12 op:1 ev:80002001

When I retry the same step with the gdb I get the following error:

`
Program received signal SIGSEGV, Segmentation fault.
ngx_http_get_forwarded_addr (r=0x7cba50, addr=0x7fffffffde40, headers=0x7cbb88, value=0x0, proxies=0x7e1b88, recursive=0) at src/http/ngx_http_core_module.c:2
800
`

From my understanding, the problem seems to have something to do with combination of a HTTP-request with X-Forwarded-For header (aka proxy request), vod_upstream_location (subrequest directive) and proxy_pass.

In my config below I have three endpoints including the two endpoints I have tested: /local/ and /hls/:
    

    upstream storage {
        server bucketname.s3.amazonaws.com:80;
    }

    server {
    listen      80;
    server_name _; 

    access_log /opt/nginx/logs/vod_access.log main;
    error_log /opt/nginx/logs/vod_error.log debug;

    open_file_cache          max=1000 inactive=5m;
    open_file_cache_valid    2m;
    open_file_cache_min_uses 1;
    open_file_cache_errors   on;

    vod_metadata_cache metadata_cache 256m;
    vod_response_cache response_cache 256m;

    location ^~ /s3/ {
        internal; 
	 proxy_pass http://storage/;
	 proxy_set_header Host bucketname.s3.amazonaws.com; # Has to be set in order to work
     }

    location /hls/ {
        vod_mode remote;
        vod_upstream_location /s3;
        vod hls;
        gzip on;
        gzip_types application/x-mpegURL;

        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
    }

    location /local/ {
        vod hls;
	vod_mode local;
	alias /home/ubuntu/test/;

        gzip on;
        gzip_types application/x-mpegURL;
        add_header Access-Control-Allow-Origin "*";
    }

    location /crossdomain.xml {
        alias /opt/nginx/html/crossdomain.xml;
        access_log off;
    }

    }

Any help would be much appreciated!

**Comment by erankor** [comment]
fixed here https://github.com/kaltura/nginx-vod-module/pull/352, try with latest master

**Comment by lykata** [comment]
Splendid! That was very fast, thank you. 
Tested and confirmed!
