### ISSUE TITLE
Premature close of connection 

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#357]
Hi Eran, 

Am facing a new problem on client prematurely closed connection.

Debug status of error log is below 

client prematurely closed connection (104: Connection reset by peer) while processing frames, client: IP-Address, server: localhost, request: "GET /gtg/gtg/video-1200.mp4/fragment-385-f1-v1.m4s HTTP/1.1", host: "IP-Address:port" 

What might be the issue.

**Comment by erankor** [comment]
If you occasionally get such an error it doesn't necessarily mean there's anything wrong, it just means the client closed the connection before the request was completed. If you are playing directly from this nginx server (not going through a CDN/proxy) it can happen, for example, if the client stops playing the video. closes the browser, loses network connectivity, etc.

**Comment by Natarajan92** [comment]
Oh !  Ok .

**Comment by Leonnash** [comment]
> If you occasionally get such an error it doesn't necessarily mean there's anything wrong, it just means the client closed the connection before the request was completed. If you are playing directly from this nginx server (not going through a CDN/proxy) it can happen, for example, if the client stops playing the video. closes the browser, loses network connectivity, etc.

hi ,i have the same problem ,  detail as below:

client prematurely closed connection while processing frames, client: 10.9.114.1, server: , request: "GET /hls/json/409514fb-d55c-40fc-9cea-de7f6f282758--19Cl6u-android-record--4119543/seg-1-v1.ts HTTP/1.1", host: "10.142.50.181:9200"

it always occurs the request that the certain mp4  sliced into HLS (mapped mode) ，but it runs  normal while restart nginx
process ...
expect for your reply ,thanks
