### ISSUE TITLE
Adaptive set JSON format in Mapped configuration 2

### ISSUE THREAD

**Issue by piotrekc** [kaltura/nginx-vod-module#359]
Hello,

I am trying to configure nginx-vod with mapped configuration.
It works with single clip. JSON content:

	    "sequences": [
	        {
	            "clips": [
	                {
	                    "type": "source",
	                    "path": "/var/content/output_2400k.mp4"
	                }
	            ]
	        }
	    ]

But with more than one clip:

	    "sequences": [
	        {
	            "clips": [
	                {
	                    "type": "source",
	                    "path": "/var/content/output_400k.mp4"
	                },
	                {
	                    "type": "source",
	                    "path": "/var/content/output_800k.mp4"
	                },
	                {
	                    "type": "source",
	                    "path": "/var/content/output_1200k.mp4"
	                },
	                {
	                    "type": "source",
	                    "path": "/var/content/output_2400k.mp4"
	                }
	            ]
	        }
	    ]

I am experiencing following error:
[error] 13901#13901: *38 media_set_parse_clips_array: sequence clips count 4 does not match the durations count 1 while sending to client

I use the master revision. 
I have discovered the similar issue was created and fixed (https://github.com/kaltura/nginx-vod-module/issues/235) by adding "context.expected_clip_count = 1;" line in a vod/media_set_parser.c file (https://github.com/kaltura/nginx-vod-module/commit/336194ae979ee53db740a5c4353b31ea7137a5a9).
In the commit (https://github.com/kaltura/nginx-vod-module/commit/274ab1fcf1a7ff982082a56b0d2d883a9bf5150d) these fix-line was removed.

Should I add some other parameters to the ngingx.conf or JSON file to make it work?
Thank you

**Comment by erankor** [comment]
Your JSON does not have the correct structure for an adaptive set, this JSON represents a sequential playlist, which is not what you want. Your JSON uses this structure: https://github.com/kaltura/nginx-vod-module/#playlist, while you should be using this structure: https://github.com/kaltura/nginx-vod-module/#adaptive-set (a sequence with multiple clips vs. multiple sequences with a single clip each)
Btw, the reason you are getting an error (and not having 400k play, then 800k play etc.) is that in case of a playlist the module requires that all the durations of the videos be specified in the JSON (for performance reasons) and your JSON does not have this info.

**Comment by piotrekc** [comment]
It works fine.
Thank you!
