### ISSUE TITLE
Compile Ubuntu 14.04 with libavcodec and libavfilter

### ISSUE THREAD

**Issue by sergiyshutov** [kaltura/nginx-vod-module#361]
Dear erankor.
Can't compile vod module in ubuntu 14.04.
I want use thumbs. If i install this deps: libavcodec-dev libavfilter-dev and compile vod module i have many errors with AV* etc..
apt-get install libavcodec-dev libavfilter-dev

**Comment by erankor** [comment]
We do not use these packages, we have our own ffmpeg package, maintained by @jessp01.
These are the commands I use to set it up:
```
echo 'deb http://installrepo.kaltura.org/repo/apt/debian jupiter main' > /etc/apt/sources.list.d/kaltura.list
aptitude update
aptitude install kaltura-ffmpeg
(echo "C_INCLUDE_PATH=/opt/kaltura/ffmpeg-2.1.3/include/" && echo "LIBRARY_PATH=/opt/kaltura/ffmpeg-2.1.3/lib/" && echo "export C_INCLUDE_PATH LIBRARY_PATH") > /etc/profile.d/kaltura_ffmpeg.sh
. /etc/profile.d/kaltura_ffmpeg.sh
```

**Comment by erankor** [comment]
can this be closed ?
