### ISSUE TITLE
Audio problem in hls.js (AAC PTS 1024?)

### ISSUE THREAD

**Issue by sergiyshutov** [kaltura/nginx-vod-module#367]
Dear erankor.

I have problems with hls.js
http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2Fhd25.freep2p.info%2Fvod_hls%2FXUBL1EZqxawlu70Cws62.mp4%2Findex.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=false&levelCapping=-1&defaultAudioCodec=undefined

Open Chrome debug console and you see this:
Invalid frame delta 1655.204081632905 at PTS 2364 (should be 2089.795918367347).

Also jump to 00:06:40 and listen audio. Somethning wrong with audio. Lagz, staks and otzer problems :)
I dont know why this hapens.

Also i have problem "invalid AAC sample duration at PTS" with other video. I found in hls.js source this code:
```
if (Math.abs(mp4Sample.duration - expectedSampleDuration) > expectedSampleDuration / 10) {
            // more than 10% diff between sample duration and expectedSampleDuration .... lets log that
            _logger.logger.trace('invalid AAC sample duration at PTS ' + Math.round(pts / 90) + ',should be 1024,found :' + Math.round(mp4Sample.duration * track.audiosamplerate / track.timescale));
          }
```

ps:
Flussonic have some magic AAC PTS 1024
https://github.com/brahimalaya/flussonic/blob/master/apps/erlmedia/src/mp4_writer.erl#L442
https://github.com/brahimalaya/flussonic/blob/master/apps/erlmedia/src/mp4_writer.erl#L469

**Comment by erankor** [comment]
does it play well on iPhone / iPad ?

**Comment by sergiyshutov** [comment]
erankor i dont have apple products. In flash player works fine, but when i try in hls.js i have this problems. Its seems problem in hls.js?

**Comment by sergiyshutov** [comment]
In dash.js all fine. Yeap. I think this is hls.js. erankor sorry for you'r time :)

**Comment by erankor** [comment]
Can you send a link to the original mp4 ? 
I think the timestamps are indeed off, and want to verify this problem exists in the original mp4.

When I look at the audio durations with ffprobe, they are all 2089:
```
root@pa-admin11 ~# /web/content/shared/bin/ffmpeg-2.7.2-bin/ffprobe.sh -i /tmp/seg.ts -show_packets -select_streams a 2>/dev/null | grep ^duration= | uniq -c
    520 duration=2089
```

But the diff in dts varies significantly:
```
root@pa-admin11 ~# /web/content/shared/bin/ffmpeg-2.7.2-bin/ffprobe.sh -i /tmp/seg.ts -show_packets -select_streams a 2>/dev/null | grep ^dts= | awk -F= 'NR > 1 {print $2-l} {l=$2}' | grep -v 2090 | grep -v 2089 | head
2059
2017
1880
2418
1880
1882
2418
1941
1970
2331
```
I think the problem is that hls.js tries to correct this on a frame by frame basis instead of just taking it as it is.

**Comment by sergiyshutov** [comment]
erankor https://yadi.sk/i/GUhu7BH-ssGJP

**Comment by sergiyshutov** [comment]
erankor this is original mkv file: http://hd25.freep2p.info/1/tmp/Astral.50643438382.mkv

**Comment by erankor** [comment]
ok there are variations in audio frame durations in the MP4 as well:
```
C:\opt\kaltura\nginx-vod-module\test>python print_mp4_durations.py \users\eran.kornblau\Downloads\astral5.mp4 | grep -A30 audio
audio
1024
987
965
966
1163
988
935
966
1229
966
965
965
1156
965
966
1163
988
935
966
1229
966
965
965
1156
965
966
1163
988
965
936
```

**Comment by sergiyshutov** [comment]
eran how yo fixed? i need reencode in ffmpeg? or what?

**Comment by sergiyshutov** [comment]
eran i check right now durations. video 01:42:22.136 and audio 01:42:22.142

**Comment by erankor** [comment]
yes, looks like it, i didn't check the MKV, but the frame durations in the mp4 are alternating. this is not about total video/audio duration, but about the duration of individual frames, it is not supposed to be changing this way in AAC

**Comment by sergiyshutov** [comment]
i can't find how to fixed :(
in ffmpeg i have:
[mp4 @ 0x343ea80] Non-monotonous DTS in output stream 0:1; previous: 115800, current: 114097; changing to 115801. This may result in incorrect timestamps in the output file.
[mp4 @ 0x343ea80] Non-monotonous DTS in output stream 0:1; previous: 115801, current: 115085; changing to 115802. This may result in incorrect timestamps in the output file.

**Comment by erankor** [comment]
sorry, can't help you with that, this means the timestamps in the source file sometimes go backwards, maybe there is some flag to ffmpeg that fixes it, don't know

**Comment by sergiyshutov** [comment]
erankor i think i found solution. 

ffmpeg -i file.mkv {avgs} **-async 1** out.mp4

**Comment by sergiyshutov** [comment]
If i convert file like that: `ffmpeg -i file.mkv {avgs} -af "aresample=async=1" out.mp4` all works fine.
erakor thank you very much for your response :)

**Comment by erankor** [comment]
great, thanks for the update

**Comment by sergiyshutov** [comment]
erankor i found better solution.
Guaranteed fix your audio.
`ffmpeg -i file.mkv {avgs} -af "aresample=first_pts=0" out.mp4`
