### ISSUE TITLE
how dose the encryption_key  Created?

### ISSUE THREAD

**Issue by MonkeyMajik** [kaltura/nginx-vod-module#372]
Hi,
Recently，im studying the code about nginx-vod-module，then i want to know when the encryption_key created？before ts request？after m3u8 build？
which function create encryption_key？i found the key in media_set.sequences.
But which function give the media_set.sequences value?
Thanks again.

**Comment by MonkeyMajik** [comment]
cur_sequence = ngx_palloc(r->pool,
		(sizeof(*cur_sequence) + sizeof(*cur_source) + sizeof(*cur_clip_ptr)) * uri_count);

so i want to know how dose cur_sequence get the encryption_key？

**Comment by erankor** [comment]
The encryption key for HLS AES is calculated in ngx_http_vod_init_encryption_key, this function evaluates the variable `vod_secret_key` and generates the key by calculating the md5 hash of the result. This variable is normally set to some secret + something that identifies the stream (e.g. `$vod_filepath`)
If your question is about DRM encryption keys (for CENC/FPS/PlayReady), these are not generated by this module, the module gets them from some external server in the DRM JSON.

**Comment by MonkeyMajik** [comment]
Thanks i got it
