### ISSUE TITLE
About Media encryption

### ISSUE THREAD

**Issue by MonkeyMajik** [kaltura/nginx-vod-module#374]
Hi
when i use Media encryption like
    **vod_hls_absolute_index_urls** off;
    vod_base_url https://yrc.cdeledu.com;
    vod_segments_base_url http://192.168.192.101;
the config is work.

must i to config the vod_hls_absolute_index_urls off?

then i found the m3u8's content is:

#EXTM3U
#EXT-X-TARGETDURATION:16
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="http://192.168.190.31/hlstest.php?path=/hlsts/aa.mp4"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:16.000,
seg-1-v1-a1.ts
#EXTINF:16.000,
seg-2-v1-a1.ts
#EXTINF:16.000,
seg-3-v1-a1.ts
#EXTINF:16.000,

the ts file's delivered  over http?

**Comment by erankor** [comment]
I don't understand the question, encrypted HLS should work regardless of the value of vod_hls_absolute_index_urls

**Comment by MonkeyMajik** [comment]
i mean i want make m3u8 and key files over https   ts files over http
so my configure is
vod_hls_absolute_index_urls off;
vod_base_url https://yrc.cdeledu.com;
vod_segments_base_url http://192.168.192.101;

then i got the m3u8 content is
#EXTM3U
#EXT-X-TARGETDURATION:16
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="http://192.168.190.31/hlstest.php?path=/hlsts/aa.mp4"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:16.000,
seg-1-v1-a1.ts
#EXTINF:16.000,


i want to know my configure is right？

**Comment by MonkeyMajik** [comment]
i mean  must i user the  vod_hls_absolute_index_urls off;？

**Comment by erankor** [comment]
no, you can use absolute as well

**Comment by erankor** [comment]
I don't see how you could have got this response unless you also have `vod_hls_encryption_key_uri` somewhere in your conf (I don't see it in what you pasted here)

**Comment by MonkeyMajik** [comment]
but when i use absolute the vlc can‘t work

my configure :

                vod hls;
               vod_mode local;

             **# vod_hls_absolute_index_urls off;**                                                    
              vod_base_url https://yrc.cdeledu.com;
               vod_segments_base_url http://192.168.192.101;
                 vod_segment_duration 16000;

               vod_secret_key "secret-$vod_filepath";
                if ($request ~* (.*mp4)/(.*)) {
                       set $request_needed_1 $1;
                    }
                 if ( $request_needed_1 ~* GET(.?)(.*)) {
                        set $request_needed $2;
                     }

                 vod_hls_encryption_method aes-128;
                 vod_hls_encryption_key_uri "http://192.168.190.31/hlstest.php?path=$request_needed\
   ";
                gzip on;
                  gzip_types application/vnd.apple.mpegurl;

                  expires -1;
                 add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";

**Comment by MonkeyMajik** [comment]
my m3u8 
#EXTM3U
#EXT-X-TARGETDURATION:16
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="http://yrc.cdeledu.com/hlsts/aa.mp4/encryption.key"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:16.000,
http://192.168.192.101/hlsts/aa.mp4/seg-1-v1-a1.ts
#EXTINF:16.000,
http://192.168.192.101/hlsts/aa.mp4/seg-2-v1-a1.ts
#EXTINF:16.000,
http://192.168.192.101/hlsts/aa.mp4/seg-3-v1-a1.ts
#EXTINF:16.000,
http://192.168.192.101/hlsts/aa.mp4/seg-4-v1-a1.ts
#EXTINF:16.000,

**Comment by MonkeyMajik** [comment]
this time i didn't use vod_hls_encryption_key_uri the m3u8 is like above but when i use vlc it didn't work

**Comment by erankor** [comment]
Did you try to download one of the TS segments? are you sure the base url is ok? does it play on iPhone?

**Comment by MonkeyMajik** [comment]
I have try to download one of the TS is OK 
my download url is: http://192.168.192.101/hlsts/aa.mp4/seg-4-v1-a1.ts
my https url is also Ok

when i didn't use encryption.key it‘s work
my m3u8 is：


my m3u8 
#EXTM3U
#EXT-X-TARGETDURATION:16
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:16.000,
http://192.168.192.101/hlsts/aa.mp4/seg-1-v1-a1.ts
#EXTINF:16.000,
http://192.168.192.101/hlsts/aa.mp4/seg-2-v1-a1.ts
#EXTINF:16.000,
http://192.168.192.101/hlsts/aa.mp4/seg-3-v1-a1.ts
#EXTINF:16.000,
http://192.168.192.101/hlsts/aa.mp4/seg-4-v1-a1.ts

**Comment by MonkeyMajik** [comment]
NOW It works must i config like this ?

    server{
	listen 443;
	server_name 192.168.192.101  yrc.cdeledu.com;
	
	ssl on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_session_cache    builtin:1000 shared:SSL:10m;
   	ssl_session_timeout  5m;
   	ssl_ciphers  HIGH:!aNULL:!MD5:!EXPORT:+MEDIUM;
   	ssl_prefer_server_ciphers  on;
  	ssl_certificate  /usr/local/nginx/conf/server.pem;
   	ssl_certificate_key  /usr/local/nginx/conf/server.key;
						
	location /hlsts{
		 access_log /var/log/test.log main ;

		 vod hls;
	 	 vod_mode local;
		 vod_secret_key "secret-$vod_filepath";
		 vod_hls_encryption_method aes-128;

		  gzip on;
     	  gzip_types application/vnd.apple.mpegurl;
 		
          expires -1;
         add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		 }				 

    }    
 

    server {
	listen       80; 
    server_name 192.168.192.101  yrc.cdeledu.com;
	root  html;

	
	 location /hlsts{

		  vod hls;
	  	  vod_mode local;

		  # vod_hls_absolute_index_urls off;	
		  vod_base_url https://yrc.cdeledu.com;						
		  vod_segments_base_url http://yrc.cdeledu.com;					
 
		  vod_secret_key "secret-$vod_filepath";
                  if ($request ~* (.*mp4)/(.*)) {
                          set $request_needed_1 $1;
                      }
 		   if ( $request_needed_1 ~* GET(.?)(.*)) {
                          set $request_needed $2;
                      }

		  vod_hls_encryption_method aes-128;
		 # vod_hls_encryption_key_uri "http://192.168.190.31/hlstest.php?path=$request_needed"; 
		  vod_segment_duration 16000;
	 	  gzip on;
     	  	  gzip_types application/vnd.apple.mpegurl;
 		
          	  expires -1;
         	  add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		 }
}

**Comment by MonkeyMajik** [comment]
must i config key in servers 443?

**Comment by erankor** [comment]
I only see 443 in your conf in the listen directive, is that what you referred to?
If so, then yes, nginx doesn't listen on 443 unless you tell it to, but you don't have to duplicate the config, you can use a single `server` section with 2 `listen` directives:
```
	server {
		listen	   80;
		listen	   443 ssl;
		...
```

**Comment by MonkeyMajik** [comment]
thanks, now i modify my config it works !
