### ISSUE TITLE
thumbnail capture

### ISSUE THREAD

**Issue by mediaproof** [kaltura/nginx-vod-module#376]
It is a wonderful module.

how to use the thumbnail capture? Is there a sample directive file for nginx?

The hls streaming was easy to set up. Looking for a similar pattern. 

URL was video/myvideofile.mp4/index.m3u8
location /video {
			vod hls;
                       vod_mode local;
	
			root /var/www/;
	
			gzip on;
			gzip_types application/vnd.apple.mpegurl;
	
			expires 100d;
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
		}

What would be the equivalent to get thumbnail capture working????

Thank you for insight or pointing to a wiki entry I missed.

**Comment by erankor** [comment]
you need to add a location like this:
```
location /thumb {
        vod thumb;
        vod_mode local;

        root /var/www/;

        expires 100d;
        add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
    }
```
and then the URL would be `thumb/myvideofile.mp4/thumb-1000.jpg`, where 1000 is the video offset in milliseconds.

**Comment by garybruckheimer** [comment]
wow!

s*it, i oversee that there is a thumbnail capture module include..

we really must thank eranker for all the hard work..you did an amazing job.

thx
gary


Am 21.07.16 um 10:25 schrieb erankor:

**Comment by erankor** [comment]
Thanks Gary :)

**Comment by mediaproof** [comment]
Yes thanks! And also thank you erankor for the answer!

**Comment by RecareLee** [comment]
Hi, @erankor 
    Does the thumbnail capture support map mode? that means parse mapped json and read the mp4 file to generate thumbnail.

**Comment by erankor** [comment]
Yes, it is handled at a different layer, it's transparent to the thumbnail capture module

**Comment by RecareLee** [comment]
Is there any difference between thumbnail and dash ? when i tried to use the same mapped json , it well supported dash , but with thumbnail , it failed and go to upstream request. Here is nginx debug logs:

 F[ngx_http_vod_module.c] L[4814] f[ngx_http_vod_handler] [debug] 13839#13839: *5 ngx_http_vod_handler: started
 F[ngx_http_request_body.c] L[590] f[ngx_http_discard_request_body] [debug] 13839#13839: *5 http set discard body
 F[ngx_http_vod_module.c] L[3877] f[ngx_http_vod_map_run_step] [debug] 13839#13839: *5 ngx_http_vod_map_run_step: mapping cache miss

**Comment by RecareLee** [comment]
Hi @erankor 
  What if the mapped json described multi-bitrate mp4 files?  How can i request the request the different bitrate file? actually what  thumbnail request uri is?

**Comment by erankor** [comment]
With default config, the file name is `thumb-1000.jpg`, 1000 is the offset in millis of the thumbnail in the video.
If you have multiple bitrates in the JSON, you'll need to use something like `thumb-1000-f1.jpg` in order to capture the thumbnail from the first file. If you don't add the `-f1` you will get an error (multiple sequences were supplied where only one is supported)
