### ISSUE TITLE
Servers optimization - Disk I/O impact for remote mode?

### ISSUE THREAD

**Issue by jsardas** [kaltura/nginx-vod-module#379]
Hi @erankor ,

Congrats for this awesome module and for the way you are actively maintaining it!
 
Based on #312, the actual packaging is done entirely in memory, and no manifests or segments are written to disk. Considering the remote mode exclusively, and thinking about servers optimization, are there other tasks of the module which would benefit from faster disk I/O?

For instance, when running the module in remote mode on cloud VMs where aspects such as CPU, memory, disks, network can be customized, would there be any significant performance benefits in assigning local SSD drives (more expensive) instead of attached/mapped persistent disks?

I noticed enabling AIO is recommended for local and mapped modes, but the remote mode sample config also includes it...

Thanks!

**Comment by erankor** [comment]
It's a copy&paste error, I'll remove the aio & open_file_cache directives from there.
The module does not perform any disk I/O in remote mode, so there should not be any noticeable difference between SSD and magnetic disk.
However, if you will want to cache the segments themselves by proxying the requests through an nginx location with proxy_pass & proxy_cache, then naturally you will have disk access. 
Other than that, the access log is written to disk, but since we're talking about large requests (video segments), this is not going to be significant (you can also configure nginx to compress them)

**Comment by jsardas** [comment]
Thank you for taking the time to explain the details.

The segments themselves would be cached by an external CDN, which frees the VMs running the module from having to implement a local cache (or implementing an additional caching layer between these VMs and end-users).

I noticed you switched from using internal http upstreams to using standard Nginx upstreams at some point as described in c875dccba4a2e27e27423353eaaf502524a0ab1b. Am I right in assuming that if minimizing disk I/O operations is a priority for a given deployment, the standard Nginx variables to prevent writing to disk when proxying should be considered? (i.e. `proxy_max_temp_file_size 0` to prevent upstream responses that don't fit into memory from being written to a temp file locally)

I understand this may be outside the scope of the module itself, but since the module is using Nginx standard upstreams for the remote mode, I'd really appreciate your opinion.

Thanks.

**Comment by erankor** [comment]
When nginx-vod-module performs a subrequest, it passes a flag that tells nginx to keep the response in memory (NGX_HTTP_SUBREQUEST_IN_MEMORY) so these requests will never be written to a temp file. 
The only case in which the upstream request can be written to a temp file with nginx-vod-module is when serving an mp4 clipping request in remote mode, don't know if you use this feature or not.

**Comment by jsardas** [comment]
That's great! No additional Nginx customization would be required in that case to prevent writting to a temp file as part of the subrequests. Thanks again for the detailed explanation.
