### ISSUE TITLE
error after executing 'make'

### ISSUE THREAD

**Issue by Ayush-Amagi** [kaltura/nginx-vod-module#389]
after executing the ./configure cmd I run the make cmd and it is giving following error
/home/ayush/git/nginx-vod-module/vod/filters/audio_filter.c: In function ‘audio_filter_flush_encoder’:
/home/ayush/git/nginx-vod-module/vod/filters/audio_filter.c:1052:3: error: ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4263) [-Werror=deprecated-declarations]
   av_free_packet(&output_packet);
   ^
/home/ayush/git/nginx-vod-module/vod/filters/audio_filter.c: In function ‘audio_filter_read_filter_sink’:
/home/ayush/git/nginx-vod-module/vod/filters/audio_filter.c:1138:4: error: ‘av_free_packet’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:4263) [-Werror=deprecated-declarations]
    av_free_packet(&output_packet);

**Comment by erankor** [comment]
As I wrote here https://github.com/kaltura/nginx-vod-module/issues/370, ffmpeg changes their API more frequently then I intend to upgrade. Either use the Kaltura-packaged ffmpeg packages (instructions here https://github.com/kaltura/nginx-vod-module/issues/361) or disable nginx's 'treat warnings as errors' as explained in the first thread I mentioned.

**Comment by erankor** [comment]
Can this be closed ?

**Comment by Ayush-Amagi** [comment]
sorry for not replying...ya its solved now...thanks
