### ISSUE TITLE
Video clipping/trimming

### ISSUE THREAD

**Issue by MansoorMajeed** [kaltura/nginx-vod-module#390]
I was trying to get the video clipping work.  I just couldn't find a way to. I mean, I want to be able to view a video by specifying the start and end of it. For example,
`video1.mp4?start=10&end=20` would give me the video clip of 10 sec to 20 sec. Is it possible to do that using this module? or am I missing something? I'd really appreciate any help on this. 

Just to add, I am using it in remote mode, where I am getting the video from a google bucket. :)

**Comment by MansoorMajeed** [comment]
Just to add, I am using it in remote mode, where I am getting the video from a google bucket. :)

**Comment by erankor** [comment]
Yes, this is supported, you need to use `vod none` to enable the module in progressive download mode. If the original mp4 URL is:
http://your-nginx-server/your-location/video.mp4
Then with the default configuration, you need to use:
http://your-nginx-server/your-location/clipFrom/10000/clipTo/20000/video.mp4
The clipping offsets are provided on the path (not as query parameters) and they are milliseconds.

**Comment by MansoorMajeed** [comment]
Wow. That worked. Thank you so much. :) Should I close this issue or leave it here so that someone will find it useful in the future?

**Comment by erankor** [comment]
Closed. Don't worry, it is still searchable :)
