### ISSUE TITLE
Unknown directive vod_base_url in debian package

### ISSUE THREAD

**Issue by danielegobbetti** [kaltura/nginx-vod-module#395]
Hello and thanks a lot for releasing this project!

I am using the debian packages available under:
```
  http://installrepo.kaltura.org/repo/apt/debian
```
package version is:  1.8.1-3+b2
and the vod_status page reports as build date: May  8 2016 20:20:33

When I try to add the ``vod_base_url`` to my configuration, the software complains it's an unknown directive.
I took a look at the nightly debian repo, but it seems to me the package is at the same version.
Is the release of an updated package planned, or is it better if I compile from sources?

Best regards and thanks again for your efforts!

**Comment by erankor** [comment]
We'll most likely release a new version in about a week, you can build from source if you don't want to wait, it's pretty easy (not many dependencies)

**Comment by jessp01** [comment]
Hello @danielegobbetti,
Just released kaltura-nginx which includes tag 1.10 of the nginx-vod-module.
Installation instructions are here:
https://github.com/kaltura/nginx-vod-module#rhelcentos-rpm
https://github.com/kaltura/nginx-vod-module#debianubuntu-deb-package

Thanks,
