### ISSUE TITLE
Question: mp3 streaming

### ISSUE THREAD

**Issue by stueja** [kaltura/nginx-vod-module#397]
Hi,

yes, I know that this is a _video_ on demand module and that it will convert mp4 files to ts chunks. ;)
However, under which circumstances could it be possible with this module to stream mp3 files?

Possibly, I could convert every of my ~40k mp3s to mp4 or m4a. Are there easier ways I do not know of now?

Thanks alot,

Jan

**Comment by erankor** [comment]
mp3 codec is supported, however mp3 container is not. Easiest solution would be to repackage the mp3 files into mp4 with ffmpeg, without transcoding them (`-c:a copy`), this should be a very fast operation.

**Comment by stueja** [comment]
Thank you very much, worked like a charm in tenths of seconds (`ffmpeg -i audio.mp3 -c:a copy audio.mp4`) and will be streamed by nginx-vod-module. :D

**Comment by ithustle** [comment]
> Easiest solution would be to repackage the mp3 files into mp4 with ffmpeg, without transcoding them (`-c:a copy`)

Maybe is a dumb question ... but, how can I do that?

**Comment by ithustle** [comment]
> (`ffmpeg -i audio.mp3 -c:a copy audio.mp4`) and will be streamed by nginx-vod-module. :D

@stueja , can you explain with an example, how did you do that?

**Comment by stueja** [comment]
@ithustle, explain what exactly? The conversion? I guess it was exactly as it was written above.
Assume you have an mp3 file. Nginx-vod-module does not recognize it. So using `ffmpeg -i inputfile.mp3 -c:a copy nginx-capable-file.mp4` should work.
This command calls `ffmpeg` on the `inputfile.mp3` and commands it to `copy` the `a`udio using the original `c`odec to `nginx-capable-file.mp4`

**Comment by ithustle** [comment]
I get it but my question is... where to use ffmpeg? Should I convert all my files out nginx vod module ?

**Comment by stueja** [comment]
Ah, understand. This is in fact what I did -- I converted all relevant mp3 files manually. Since `ffmpeg` simply copies the information, it is a matter of maybe a second per song.

**Comment by ithustle** [comment]
@stueja thanks to clarify me
