### ISSUE TITLE
Support FLV Repackager

### ISSUE THREAD

**Issue by zhangqianliang** [kaltura/nginx-vod-module#405]
Support FLV Repackager?

**Comment by erankor** [comment]
No, only MP4 and MKV (experimental)

**Comment by Media182** [comment]
That's bit sad. We have tons of FLV videos in old archives.

**Comment by joaoserra** [comment]
@Media182 I'm a bit curious of why you need that. You can simply lossless convert your h264 FLVs to MP4 without reencoding. Note that Adobe Flash supports both MP4 and FLV formats.
