### ISSUE TITLE
Only local files in mapped mode?

### ISSUE THREAD

**Issue by bson** [kaltura/nginx-vod-module#406]
I want to verify there is no way for the JSON manifests provided to the nginx-vod-module in mapped mode by an intermediary to dereference remote content?  I.e., all media files must in fact be files local to the nginx server and can't e.g. reside in S3, OpenStack Swift, or another object store.  I believe this to be the case, but I'd like to verify before dismissing mapping of remote content as a potential approach...

**Comment by erankor** [comment]
It is supported, implemented by @eminden here https://github.com/kaltura/nginx-vod-module/pull/387

**Comment by bson** [comment]
Ah, fantastic!  Thanks @eminden!  I missed it because it's just one new key in the plethora... :)

When I get it working I can add an example for it.
