### ISSUE TITLE
Bad bandwith for HLS in jwplayer

### ISSUE THREAD

**Issue by deStrO** [kaltura/nginx-vod-module#412]
Hello,

I'm using JWPlayer for a project with nginx-vod-module. We don't have the quality selection due a bandwith issue. We contacted JWPlayer about it and they ran some test on our stream files and discovered that the bandwith wasn't equal.

Here are the mediastreamvalidator result:
MUST fix issues
--------------------------------------------------------------------------------
Error: Measured peak bitrate compared to master playlist declared value exceeds error tolerance
--> Detail:  Measured: 4296.43 kb/s, Master playlist: 778.59 kb/s, Error: 81.88%
--> Source:  http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-,480p,720p,1080p,.mp4.urlset/master.m3u8
--> Compare: http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-480p.mp4/index-v1-a1.m3u8
--> Detail:  Measured: 8531.69 kb/s, Master playlist: 1413.58 kb/s, Error: 83.43%
--> Source:  http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-,480p,720p,1080p,.mp4.urlset/master.m3u8
--> Compare: http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-720p.mp4/index-v1-a1.m3u8
--> Detail:  Measured: 10813.76 kb/s, Master playlist: 1772.54 kb/s, Error: 83.61%
--> Source:  http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-,480p,720p,1080p,.mp4.urlset/master.m3u8
--> Compare: http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-1080p.mp4/index-v1-a1.m3u8
--------------------------------------------------------------------------------
SHOULD fix issues
--------------------------------------------------------------------------------
Warning: #EXT-X-ALLOW-CACHE has been deprecated
--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-480p.mp4/index-v1-a1.m3u8
--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-720p.mp4/index-v1-a1.m3u8
--> Detail:  Line: #EXT-X-ALLOW-CACHE:YES
--> Source:  http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-1080p.mp4/index-v1-a1.m3u8

I don't know where to check if it's the encoding of the video who are fucking up or it's inside the vod-module.

Someone is experimenting the same thing?
Thanks

**Comment by erankor** [comment]
It seems your video has great variance in the bitrate, here is the average bitrate (in bps) per segment of the first 30 segments:
```
for i in `seq 1 30`; do curl -s -I http://storage.programmebeautytime.fr/hls/57d2904e9d6e9/57d2904e9d6e9-480p.mp4/seg-$i.ts | grep -i content-length: ; done  | awk 'NR < 4 {print $NF*8/2} NR==4 {print $NF*8/4} NR > 4 {print $NF*8/10}'
278240
891872
518880
6185200
929171
587462
609120
585056
563398
594682
647622
813664
811258
897888
799226
796819
806445
869011
847354
729440
893075
832915
772755
864198
873824
818477
938797
801632
731846
924358
```
You can see, for example, that the first segment has a bitrate of ~270kbps while the fourth segments has more than 6mpbs. 
nginx-vod-module calculates the bitrate by averaging the sizes of the first 100K frames (which is probably all frames in this case).
Maybe it would be more correct to change it to calculate the peak bitrate of each segment, or something like that (it's a bit unclear from the spec in what the granularity the bitrate should be calculated - segment by segment, per second, etc.). 
However, even if we change that, you will get a master manifest report 4mbps or more for a 480p video which doesn't make much sense, so I suggest you check your encoding settings.

**Comment by deStrO** [comment]
Okay thanks. I encoded them via ffmpeg with a script found on a website.

ffmpeg -y -async 1 -vsync -1 -analyzeduration 999999999 -i $FILE -movflags faststart -keyint_min 30 -x264opts "keyint=30:min-keyint=30:no-scenecut" -g 30 -filter:v "scale=iw*min(320/iw\,180/ih):ih*min(320/iw\,180/ih), pad=320:180:(320-iw*min(320/iw\,180/ih))/2:(180-ih*min(320/iw\,180/ih))/2" -r:v 30 -s 320x180 -b:v 320k -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 3.0 -c:a aac -ac 2 -ar 48000 -b:a 64k $NAME/$NAME-180p.$EXTENSION
ffmpeg -y -async 1 -vsync -1 -analyzeduration 999999999 -i $FILE -movflags faststart -keyint_min 30 -x264opts "keyint=30:min-keyint=30:no-scenecut" -g 30 -filter:v "scale=iw*min(640/iw\,360/ih):ih*min(640/iw\,360/ih), pad=640:360:(640-iw*min(640/iw\,360/ih))/2:(360-ih*min(640/iw\,360/ih))/2" -r:v 30 -s 640x360 -b:v 640k -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 3.0 -c:a aac -ac 2 -ar 48000 -b:a 96k $NAME/$NAME-360p.$EXTENSION
ffmpeg -y -async 1 -vsync -1 -analyzeduration 999999999 -i $FILE  -movflags faststart -keyint_min 30 -x264opts "keyint=30:min-keyint=30:no-scenecut" -g 30 -filter:v "scale=iw*min(854/iw\,480/ih):ih*min(854/iw\,480/ih), pad=854:480:(854-iw*min(854/iw\,480/ih))/2:(480-ih*min(854/iw\,854/ih))/2" -r:v 30 -s 854x480 -b:v 680k -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 3.0 -c:a aac -ac 2 -ar 48000 -b:a 96k $NAME/$NAME-480p.$EXTENSION
ffmpeg -y -async 1 -vsync -1 -analyzeduration 999999999 -i $FILE  -movflags faststart -keyint_min 30 -x264opts "keyint=30:min-keyint=30:no-scenecut" -g 30 -filter:v "scale=iw*min(1280/iw\,720/ih):ih*min(1280/iw\,720/ih), pad=1280:720:(1280-iw*min(1280/iw\,720/ih))/2:(720-ih*min(1280/iw\,720/ih))/2" -r:v 30 -s 1280x720 -b:v 1280k -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 3.1 -c:a aac -ac 2 -ar 48000 -b:a 128k $NAME/$NAME-720p.$EXTENSION
ffmpeg -y -async 1 -vsync -1 -analyzeduration 999999999 -i $FILE -movflags faststart -keyint_min 30 -x264opts "keyint=30:min-keyint=30:no-scenecut" -g 30 -filter:v "scale=iw*min(1920/iw\,1080/ih):ih*min(1920/iw\,1080/ih), pad=1920:1080:(1920-iw*min(1920/iw\,1080/ih))/2:(1080-ih*min(1920/iw\,1080/ih))/2" -r:v 30 -s 1920x1080 -b:v 1640k -c:v libx264 -pix_fmt yuv420p -profile:v baseline -level 4.0 -c:a aac -ac 2 -ar 48000 -b:a 128k $NAME/$NAME-1080p.$EXTENSION

I'm not a pro at video encoding, so if you have any tip, it will be nice :)

**Comment by anatolkaltura** [comment]
Hi deStrO,
I would suggest u -
- switch to 2 sec gop
- add maxrate and bufsize limitations ("-maxrate 680k -bufsize 1400k", it is recommended that bufsize should be able to hold ~2 sec of content)

I believe that this will solve your porblem.

Following is cmd-line  that we use for our transcodings:
ffmpeg -threads 1 -i SOURCE -c:v libx264  -subq 2 -qcomp 0.6 -qmin 10 -qmax 50 -qdiff 4 -coder 0 -x264opts stitchable -vprofile baseline -force_key_frames expr:'gte(t,n_forced*2)' -pix_fmt yuv420p -b:v 600k -s 640x360 -r 30 -g 60 -aspect 640:360 -c:a aac -b:a 64k -ar 44100 -ac 2 -map_chapters -1 -map_metadata -1  -f mp4 -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -trellis 1 -refs 1 -me_range 16 -keyint_min 20 -sc_threshold 40 -i_qfactor 0.71 -bt 200k -maxrate 600k -bufsize 1200k -rc_eq 'blurCplx^(1-qComp)' -level 30  -vsync 1 -threads 4  -y TARGET

Anatol

**Comment by erankor** [comment]
@deStrO, can this be closed ?

**Comment by tooolbox** [comment]
@erankor Totally disrelated and off-topic, I apologize, but I'm trying to debug an HLS stream and I came across your little script up there.  What's the purpose of piping the content length into awk and dividing it by a different number in certain cases?  (I'm unfortunately not familiar with awk so I'm not fully tracking with what you're doing there.)

I'm just looking for various ways to instrument and analyze a stream, thanks very much for any help.

**Comment by erankor** [comment]
@tooolbox, this was ages ago... but looking at the awk, the reason was probably that the stream used variable segment sizes - 2,2,2,4,10,10..., therefore - the first 3 segments are divided by 2, the 4th by 4 and any subsequent segments are divided by 10

**Comment by tooolbox** [comment]
@erankor Oh wow, like when you startup the stream, you get 2-second segments for the first couple, then 4-second segments, then 10-second segments?  I didn't even know that was possible, but cool.

**Comment by erankor** [comment]
Yes, that's what we use for our default configuration as well, it's supposed to allow the adaptive selection logic in the player to converge faster
