### ISSUE TITLE
Problems with video playback on IOS 10

### ISSUE THREAD

**Issue by Ivars** [kaltura/nginx-vod-module#414]
Hello,

After recent IOS 10 upgrade for Apple devices the nginx-vod-module -> flowplayer configuration we 
are using in our service stopped working with Flowplayer reporting: html5: Video not properly encoded.

On devices with older IOS (and all other browsers and devices we tested) everything works as before and there are no recent changes in configuration which may caused this error.

This problem only occurs for encrypted videos with key served from uri:

```
        location ~ ^/Movies/([^/]*)/.* {
            vod hls;
            vod_mode mapped;

            vod_upstream_location /streamdata;
            vod_hls_encryption_method aes-128;

            vod_hls_encryption_key_uri "https://xxx/hls/key/server/$1";

            vod_drm_enabled on;
            vod_drm_upstream_location /keyserver;
            vod_drm_request_uri "/$1";

        }

```

If the key is specified in the following way, then it works:

```
      location /Trailers/ {
        vod hls;
        vod_mode local;

        root /srv/video/trailers/;

        vod_secret_key "secret-$vod_filepath";
        vod_hls_encryption_key_file_name "trailer";
        vod_hls_encryption_method aes-128;

        }
```

Nginx log file reports that Nginx has successfully served index-f1-v1-a1.m3u8 and first seg-1-f1-v1-a1.ts file - so it seems that it's some bug in IOS 10?

Have you encountered any similar problem with IOS 10 ?
Maybe there are some additional configuration changes needed to serve videos for IOS 10 ?

**Comment by erankor** [comment]
What happens if you simply open the direct m3u8 URL in Safari ? (without flowplayer)
Do you see a request for the key on the key server ?

**Comment by Ivars** [comment]
Yes it seems that the key is requested from a key server, but the video does not start to play in Safari either.

To be clear - I just wanted to know if you have encountered similar problem with IOS 10. 

If no - then it can always be some other configuration or code issue on our service. 
Unfortunately there are so many variables involved when serving video..

I will let you know here if we will manage to solve this problem.

**Comment by erankor** [comment]
No, did not encounter this issue. 
Maybe you are missing CORS headers in the key response or something like that ?

**Comment by erankor** [comment]
Also, may be worth trying with SAMPLE-AES instead of AES-128. 
In SAMPLE-AES if the key is wrong you are likely to still get playback but you'll see some random noise, while with AES-128 a wrong key prevents playback altogether.

**Comment by erankor** [comment]
@Ivars, can this be closed ?

**Comment by Ivars** [comment]
Sorry for replying so late.

The problem in this case is a regression bug in Ios 10.x
https://www.bizify.me/test-if-your-ios-device-is-broken/

As it's described in the test page:
_The video player in iOS 7 and iOS 10 can not read cookies correctly. In iOS 7 no cookies can be read at all and in iOS 10 only cookies being set with an expire date can be read. Session cookies can not be read by the video player in iOS 10._

The solution in our case was to change php.ini session.cookie_lifetime = 86400 on a server serving video player (flowplayer) and hls encryption key.

**Comment by erankor** [comment]
Thanks for the update.
We have encountered issues with cookies in Safari, but you didn't say you were using cookies in previous posts...
Our solution is to avoid using cookies altogether, we are using only query string parameters, and we are making sure to propagate them from the master.m3u8 to the index.m3u8 and then to the segment requests.
