### ISSUE TITLE
keyFrameDurations unit

### ISSUE THREAD

**Issue by ocean-world** [kaltura/nginx-vod-module#417]
what is the unit of this array ? number of frames ? milliseconds ? is it the frame number in the video or really the duration
if I have the frames at position 1,25,30 on a video of 60 frames the array should be [25, 5, 30] ?

**Comment by erankor** [comment]
It is measured in milliseconds, I will add to the readme.
But I'm quite curious to know why you want to set this property ? we are currently using it only when we repackage live content, in this use case we are merging separate audio/video streams, and passing this property is required to have the streams aligned.

**Comment by ocean-world** [comment]
I can't align the keyframes perfectly in my video files, if I want accurate segments I need to provide the keyframes positions or to let the module find them.
Finding the keyframes is slow when the video file is remote and not possible when using a mixFilter.
Maybe I over-evaluate the importance of having segments starting with a keyframe and accurate durations and every client will work even if this is not accurate ?

**Comment by erankor** [comment]
If we're talking about a simple (single video) VOD use case, then you can just set:
```
vod_align_segments_to_key_frames on
vod_manifest_segment_durations_mode accurate
```
and it will have the same effect

**Comment by ocean-world** [comment]
yes, the problem is if you have non simple single files or many nginx sources that will do the same job for the same files

**Comment by erankor** [comment]
the performance impact of these settings is very low, if that's what you meant.
if you are using playlists, then you can't use them

**Comment by erankor** [comment]
also, to clarify, the settings I mentioned can work with an adaptive set, just not with playlists

**Comment by ocean-world** [comment]
If the file is remote the issue is the transfert time to analyse the file, the analyse itself can be fast, getting a 4Go file will take time.
so you confirm it's the duration and not an absolute time from the beginning.

**Comment by erankor** [comment]
1. Yes it's the duration
2. Pulling the metadata of the file has to be done either way, the module can't perform the packaging to HLS/HDS/... without it. Adding these settings will not result in more data being pulled for any request, it will just add some (probably negligible) CPU time

**Comment by erankor** [comment]
@ocean-world, can this be closed ?

**Comment by dcharbonnier** [comment]
yes, thx !
