### ISSUE TITLE
Problems with Simulated Live Stream

### ISSUE THREAD

**Issue by lelikg** [kaltura/nginx-vod-module#421]
Hi @erankor 

I am Getting the following errors on the stitch between vod files when generating a simulated live stream.

segmenter_get_live_window_start_end: end time 1475010993000 smaller than first clip time 1475010993000 while sending to client

And: 

segmenter_get_live_window_start_end: empty window (2)
segmenter_get_live_window_start_end: empty window (3)

Can send the link to the json + configs in private msg.

**Comment by erankor** [comment]
It means the local time on nginx-vod server is outside the range defined in the mapping JSON, so the module has nothing to return. This can either be some bug in the generation of the mapping JSON, or if you are using multiple servers, it can be caused by clock differences between them.

**Comment by lelikg** [comment]
I am indeed using a different server on the backend to return the json mapping, and the packager is running on a separate server. I will check the time if it's different or not. Thanks for the help @erankor and Shana Tova!

**Comment by erankor** [comment]
@lelikg, can this be closed ?

**Comment by lelikg** [comment]
Hi @erankor I haven't been able to resolve this error yet unfortunately.
I did check the times, they are synced between the servers with NTP so maybe the error is somewhere else?

**Comment by erankor** [comment]
You are probably not generating the JSON correctly, it must have enough clips so that nginx-vod always has what to return. For example, if you have videos A and B playing in an endless loop, you have to at least duplicate them to ABAB in order to have a smooth transition from B to A.
You can check out this sample: https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php

**Comment by erankor** [comment]
@lelikg, can this be closed ?

**Comment by lelikg** [comment]
Hi Eran, I haven’t solved this issue on my end yet, but you can close if you think it’s not on your end.

**Comment by erankor** [comment]
I don't think it helps to leave it open with the info provided so far.
There are two things I suggest:
1. run some tests with https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php, and compare your implementation to this sample
2. save the jsons you feed into nginx-vod-module to some log, this will enable you reproduce the issue once you see the errors in the error log. if you compile nginx-vod-module in debug, you can control the time it uses to calculate the live window, by sending a `time` parameter on the query string (unix time). this will enable you to reproduce the error, and make sure that the json you provide is adequate

**Comment by lelikg** [comment]
Thanks Eran, this module is awesome! :)
