### ISSUE TITLE
Akamai uri key not working, need a helping hand

### ISSUE THREAD

**Issue by garybruckheimer** [kaltura/nginx-vod-module#423]
anyone has issues with testing akamai validation and secure key requests?

Maybe i oversee some configuration.  Here are the steps to request secured uris for HLS with akamai token.

nginx config (i made sure that everything plays with secure and validation switched on). 
key 000000000000 was only set for this post.

            #vod hls on
            vod hls;

            # Akamai token on
            akamai_token_validate on;
            akamai_token_validate_key 000000000000; 
            akamai_token_validate_strip_token on;

            # secure module on
            secure_token akamai; 
            secure_token_akamai_key 000000000000;
            secure_token_types application/vnd.apple.mpegurl video/f4m application/dash+xml text/xml;
            secure_token_akamai_acl "$baseuri*";
            secure_token_expires_time 100d;
            secure_token_cookie_token_expires_time 0;
            secure_token_query_token_expires_time 1h;
            
so far so good.

On the token i generate an key with current timestamp

-n __hdnea__ -s 1475400252000 -A sha256 --key 000000000000 --acl /hlsdrm2/testpattern.mp4/*  --window 6000

I received token back:
__hdnea__=st=1475400252000~exp=1475400258000~acl=/hlsdrm2/testpattern.mp4/*~hmac=f59c15eec6ea33e1e13d9dba3a9aa02a820880d6c4e05a4981dfa57baddba3c2

Now i tried to access the stream with
https://myserver.com/hlsdrm2/testpattern.mp4/master.m3u8?__hdnea__=5eec6ea33e1e13d9dba3a9aa02a820880d6c4e05a4981dfa57baddba3c2

Same not working with ?token=5eec6ea33e1e13d9dba3a9aa02a820880d6c4e05a4981dfa57baddba3c2

I need a helping hand, or is this an issue?

I checkout latest master. Thx!

**Comment by erankor** [comment]
I didn't quite understand what tool you are using to generate the token (the `-n hdnea -s ...` command)
But one thing that I noticed is that you are using timestamps in milliseconds while it should be seconds, e.g. instead of 1475400252000, it should be 1475400252.

**Comment by garybruckheimer** [comment]
i used original akamaiv2.jar token genertor to generate a test token.

i tried this command line:
java -jar AkamaiToken_v2.jar -n __hdnea__ -s 1475424012 -A sha256 --key
000000000000 --acl /hlsdrm2/testpattern.mp4/*  --window 6000

i also changed ms to seconds, but still getting 403 response when i use
this call for loading master list:

https://server.com/hlsdrm/testpattern.mp4/master.m3u8?hdnea=st=1475424012~exp=1475484012~acl=/hlsdrm2/testpattern.mp4/master.m3u8~hmac=8334c58cf7acb5b6173d796ab811d7437e59744a8692fa95c9d7830aa89113d3

do i oversee something?

thx for help.

Am 02.10.16 um 14:27 schrieb erankor:

**Comment by garybruckheimer** [comment]
Closed..Thx..
