### ISSUE TITLE
vod_hls_encryption_key_uri

### ISSUE THREAD

**Issue by arty777** [kaltura/nginx-vod-module#426]
vod_hls_encryption_key_uri

i want use external link here ? on php file (on another server) , who will generate key , is it possible? 
How generate key file , please explain  .

**Comment by erankor** [comment]
you should be able to use a configuration similar to the sample FairPlay configuration - 
https://github.com/kaltura/nginx-vod-module/#sample-configuration
but without setting vod_hls_encryption_key_format / vod_hls_encryption_key_format_versions (so that the player will not think it's DRM protected).
the upstream server needs to return to nginx-vod a JSON with the following structure:
[{
    "key": "GzoNU9Dfwc//Iq3/zbzMUw==", 
    "key_id": "YzJmODYxNzM3Y2M0ZjM4Mg=="
}]
key is the encryption key that should be used to encrypt the stream (in base64). key_id is irrelevant in this case, but you have to set it to something since it's required (you can set it to the same value as `key`)
note that the URL you set in vod_hls_encryption_key_uri has to return the binary 16 bytes of the encryption key (not base64)

**Comment by arty777** [comment]
vod_secret_key "GzoNU9Dfwc//Iq3/zbzMUw==";
vod_hls_encryption_method aes-128;
vod_hls_encryption_key_uri "http://api.externalserver.net/key.php";

vod_drm_enabled on;
vod_drm_request_uri /key.js;
vod_drm_upstream_location  /backend;


key.js is 
[{
"key": "GzoNU9Dfwc//Iq3/zbzMUw==", 
"key_id": "YzJmODYxNzM3Y2M0ZjM4Mg=="
}]


key.php from external server 
return the binary 16 bytes of vod_secret_key 
I understood everything correctly?

**Comment by erankor** [comment]
vod_secret_key is irrelevant in this case, this parameter is used when nginx-vod generates the key.
other than that it looks fine - nginx-vod will hit /key.js to get the encryption key (in JSON), and the player will hit key.php to get the encryption key (in plain binary).

**Comment by arty777** [comment]
We have touble to take a string and convert it to 16 bytes binary (plain binary). Meybe you know  simple variant? ))

**Comment by erankor** [comment]
http://php.net/manual/en/function.base64-decode.php ?

**Comment by arty777** [comment]
Work fine , i will soon paste whole config . 

Thank you

**Comment by arty777** [comment]
Working config for "DRM simulation" :) 

Backend+secure link module  BEGIN
upstream drm_backend {
        server 127.0.0.1:82;
        keepalive 100;
}
server {
listen       xxx.x.x.x:XX;
aio             threads=megapool_mp4;


location /video {
        rewrite /video/([a-zA-Z0-9_\-]*)/([0-9]*)/(.*)\.mp4$ /video/$3.mp4?secl=$1&sect=$2;
        secure_link $arg_secl,$arg_sect;
        secure_link_md5 PASSWORD$uri$arg_sect;
        if ($secure_link = "") { return 403; }
        if ($secure_link = "0") { return 403; }
        rewrite ^/view/(.*)$ /view/$1 break;
        root /store;

try_files
/drm/$1
/drm2/$1
/drm3/$1

=404;
}
location ~* key\.(js)$ {
root /usr/local/nginx/html;
}}
Backend+secure link module  END
file key.js  example
[{
"key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx=",.
"key_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
}]


###MAIN BEGIN
server {
..... 
####encrypt
vod_hls_encryption_method aes-128;
vod_hls_encryption_key_uri "https://REMOTE_SERVER_URL.com/a.php";
vod_drm_enabled on;
vod_drm_request_uri /key.js;
vod_drm_upstream_location  /drm_backend;
# vod settings
vod_mode remote;
.............
###MAIN END

file a.php from remote server - its key responser to decrypt ts files 

file a.php redirect to b.php  with new secure url 
<?php
$domain = 'maybenewdomain.com';
$name = 'b.php';
$secret = 'PASSWORD_NEW';
$time = time() + 1; // for 1 sec live
$key = str_replace("=", "", strtr(base64_encode(md5($secret . $time, TRUE)), "+/", "-_"));
$encoded_url = "https://" . $domain . "/$key/$time/$name";
header('Location: ' . $encoded_url);
exit();

you go to new URL with time live 1 sec ? after 1 sec file b.php will be expared 

file b.php 

1. Live 1 sec 
2. Check referer etc 

 if all fine then 
     $key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx=';
      echo base64_decode($key);


or 
die('Invalid')

**Comment by erald** [comment]
@arty777

Am trying to understand this but am not clear on what php and b.php exactly give. Am a newly with Nginx config and this is a bit confusing.
Could you give me a working example?
