### ISSUE TITLE
response caching

### ISSUE THREAD

**Issue by thaonv** [kaltura/nginx-vod-module#429]
Hi everyone,
I have a MP4 file include 1 video and 2 audio. How to cache response separate video and audio segment??
Thanks very much!

**Comment by erankor** [comment]
I don't really understand what you are asking, but you can choose the tracks that you want to include in the resulting stream - e.g.:
1. index-v1.m3u8 will return only the first video track
2. index-a1.m3u8 will return only the first audio track
3. index-a2.m3u8 will return only the second audio track

**Comment by erankor** [comment]
@thaonv, can this be closed ?
