### ISSUE TITLE
I have a question for "m3u8_builder m4p files" feature. 

### ISSUE THREAD

**Issue by fastlyos** [kaltura/nginx-vod-module#432]
Hello, guys

I don't understand this feature, 
HLS clients first request the .m3u8 manifest for a file in the location, then begin downloading the segments of video specified in the file. Again, NGINX-VOD handles the task of segmenting MP4-packaged content on the fly for HLS streaming.

How do not need to repacking(.ts & .m3u8) the mp4 file to HLS without recoding the content?
Thank you, guys.

**Comment by erankor** [comment]
I'm sorry, but I really don't understand what you are asking, can you explain this sentence:
"How do not need to repacking(.ts & .m3u8) the mp4 file to HLS without recoding the content?"

**Comment by fastlyos** [comment]
Hi, erankor

Sorry.
I said was mp4 file containers (filename extensions .mp4). With the HLS/VOD module, there’s no need to repackage existing mp4 content when introducing HLS adaptive streaming to users.

Tks and best regards.

**Comment by erankor** [comment]
nginx-vod-module takes care of repackaging the MP4 to MPEG-TS for HLS streaming, if that is what you meant.

**Comment by fastlyos** [comment]
Yes,

MP4 files into HLS (HTTP Live Streaming) services. I would like to know how the source server will no longer apply at the same time as MP4 files without having to download and save the file split for real-time service HLS .m3u8 / .ts files after conversion features that are at the service kaltura-nginx.

i.e) http://www.example.com/video.mp4/mp4hls/index.m3u8
Called from the following URL video.mp4
It auto generates a file index.m3u8.
------------------------------------------
Generates index.m3u8 file.
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=200000,RESOLUTION=720x480
/video.mp4/mp4hls/playlist.m3u8

Generates playlist.m3u8 ts file.
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:11.637,
/video.mp4/mp4hls/0.ts
#EXTINF:10.092,
/video.mp4/mp4hls/1.ts
#EXTINF:10.112,
/video.mp4/mp4hls/2.ts
#EXT-X-ENDLIST
---------------------------------
This Kaltura-Nginx is automatically generated?

**Comment by erankor** [comment]
It is extremely hard for me to understand what you write.
nginx-vod-module loads the relevant parts of the MP4 that are required to serve each request. For example, to generate the index.m3u8 it reads only the MP4 metadata in order to know its duration. To serve seg-1.ts, it loads only the frames contained in the first segment etc.
