### ISSUE TITLE
MSS: no matching streams were found, probably invalid segment index while reading media header

### ISSUE THREAD

**Issue by utu2016** [kaltura/nginx-vod-module#433]
Hi, 
I getting this error code when I'm trying to get the video fragments with url like this: xxx/ssc/test/QualityLevels(1000)/Fragments(video=0).

The manifest & the audio fragments are correctly retrieved.

Each single segment has GOP multiple of 5000 but with variable bitrate inside.

The nginx.conf is:

user xxx xxx;
worker_processes  1;
working_directory   /root/test/;

events {
    worker_connections  4096;
    multi_accept on;
}

http {
    server_tokens   off;
    include mime.types;
    default_type application/octet-stream;

 server {
        listen  80;
        server_name  localhost;
        client_max_body_size 0;

       set $MY_FOLDER /root/storage/;

        location /ssc/test/ {
            vod mss;
            vod_mode local;
            if_modified_since off;
            vod_mss_manifest_file_name_prefix Manifest;
            vod_segment_duration 5000;
            vod_manifest_segment_durations_mode accurate;
            vod_align_segments_to_key_frames on;
            alias $MY_FOLDER;
            expires 100d;
            add_header Last-Modified "";
            add_header Cache-Control max-age=604800;
            add_header Test true;
            etag off;
        }
   }
}

Looking in the MP4 xml,  I see these tags:
FTYP
MOOV
IODS
MHVD
TRAK ( for video)
 TKHD
MDIA
 MDHD
 HDLR
 MINF
 VMHD
 DINF
 DREF
 URI
 STBL
STSD
AVCC
BTRT
AVC1
STTS
CTTS
STSS
STSC
STSZ
STCO
TRAK (for audio part)
MDAT

Could you help me to understand this problem?

thanks

**Comment by erankor** [comment]
please send a link to the mp4 file

**Comment by utu2016** [comment]
hi, 
I found the problem: it's regarding to bitrate value used in the xxx/ssc/test/QualityLevels(1000)/Fragments(video=0) command.
