### ISSUE TITLE
thumb offset step by seconds

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#440]
Hi! I have installed kaltura-nginx from installrepo.kaltura.org for centos6.
We have video with gop size=25
I made this location:
```
        location /thumb {
        vod thumb;
        vod_mode local;
        alias /storage;
        add_header Access-Control-Allow-Origin "*";

    }
```

When i try to open http://ip-addr/thumb/test.mp4/thumb-18000.jpg
It opens jpg on 18 second of video.
If i try to open http://ip-addr/thumb/test.mp4/thumb-18500.jpg
then nothing new happens, it is still the same as thumb-18000.jpg.
So when i try http://ip-addr/thumb/test.mp4/thumb-19300.jpg - it is new, but it is equal to http://ip-addr/thumb/test.mp4/thumb-19000.jpg

So it seems to that offset is working properly only when step - is full second = 1000 miliseconds, is it possible to capture more precisely?

**Comment by erankor** [comment]
please send a URL to the mp4 file

**Comment by kuznetcoff777** [comment]
It is local testing now...i can give video for you can test it by yourself.
http://195.16.108.101/ftp/uploaded/test.mp4

**Comment by erankor** [comment]
I tested it now, it works well for me - I tested from 18000 to 19000 in 100 ms increments, all return different (I see the people walking). also, verified in the logs that a different frame is used each time:
```
grep 'frame index' /var/log/nginx/error.log
2016/10/26 16:19:05 [debug] 22192#22192: *10 thumb_grabber_init_state: frame index is 0
2016/10/26 16:19:06 [debug] 22192#22192: *11 thumb_grabber_init_state: frame index is 4
2016/10/26 16:19:07 [debug] 22192#22192: *12 thumb_grabber_init_state: frame index is 6
2016/10/26 16:19:08 [debug] 22192#22192: *13 thumb_grabber_init_state: frame index is 8
2016/10/26 16:19:09 [debug] 22192#22192: *14 thumb_grabber_init_state: frame index is 9
2016/10/26 16:19:10 [debug] 22192#22192: *15 thumb_grabber_init_state: frame index is 14
2016/10/26 16:19:12 [debug] 22192#22192: *16 thumb_grabber_init_state: frame index is 16
2016/10/26 16:19:13 [debug] 22192#22192: *17 thumb_grabber_init_state: frame index is 18
2016/10/26 16:19:13 [debug] 22192#22192: *18 thumb_grabber_init_state: frame index is 19
2016/10/26 16:19:14 [debug] 22192#22192: *19 thumb_grabber_init_state: frame index is 24
```
are you using the latest version ?
also, I suggest you enable debug messages, and run the same grep that I did.

**Comment by kuznetcoff777** [comment]
I use the version from http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
nginx -V
nginx version: nginx/1.8.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=kaltura --group=kaltura --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-http_spdy_module --with-threads --with-cc-opt=-O3 --add-module=./nginx-vod-module-1.10 --add-module=./nginx-secure-token-module-1.1 --add-module=./nginx-akamai-token-validate-module-1.0.1 --add-module=./nginx-module-vts-0.1.9



It is without debug. If i try to build nginx from sources(with add-module) with tle latest version of module i get this:
nginx -V
nginx version: nginx/1.10.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_perl_module=dynamic --add-dynamic-module=njs-1c50334fbea6/nginx --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-file-aio --with-http_dav_module --add-module=/home/rpmbuild/rpmbuild/SOURCES/nginx-dav-ext-module --add-module=/home/rpmbuild/rpmbuild/SOURCES/lua-nginx-module --add-module=/home/rpmbuild/rpmbuild/SOURCES/nginx-vod-module-master --with-http_v2_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'


/etc/init.d/nginx restart
nginx: [emerg] invalid value "thumb" in "vod" directive, it must be one of: none,dash,hds,hls,mss in /etc/nginx/nginx.conf:89

Seems tot that i did not mention something in a spec file for thumb support appears. Can you give the cue of what exactly should i insert in spec file for thumb support?

**Comment by erankor** [comment]
This means that ffmpeg was not detected when you ran configure, I'm using these commands to set it up:
```
echo 'deb http://installrepo.kaltura.org/repo/apt/debian lynx main' > /etc/apt/sources.list.d/kaltura.list
aptitude update
aptitude install kaltura-ffmpeg
(echo "C_INCLUDE_PATH=/opt/kaltura/ffmpeg-2.1.3/include/" && echo "LIBRARY_PATH=/opt/kaltura/ffmpeg-2.1.3/lib/" && echo "export C_INCLUDE_PATH LIBRARY_PATH") > /etc/profile.d/kaltura_ffmpeg.sh
. /etc/profile.d/kaltura_ffmpeg.sh
```
