### ISSUE TITLE
Question about base url for f4m

### ISSUE THREAD

**Issue by dabih** [kaltura/nginx-vod-module#442]
Hello!
We use the load balancer to select the optimal server.
The player receives a URL of the form http://loadbalanser/video/file/id
load balancer returns a 302 redirect to the optimal server
example, http: //best_server/a2/3d/a23d107fda2740c890822b1c2e5cf978/a23d107fda2740c890822b1c2e5cf978-,q1,q2,q3,.mp4.urlset/manifest.f4m

Thereafter, the player erroneously requests fragments from load balancer
http://loadbalancer/video/file/7f6053b93020c29b1de4ffef516b59b2/1477656885/frag-f1-v1-a1-Seg1-Frag1

Is it possible to specify a base URL in manifest.f4m?

**Comment by erankor** [comment]
Currently, the module always uses relative URLs in HDS, I'm not sure absolute URLs will be accepted by the player. I think I tested it once and it didn't work, but not 100% sure

**Comment by dabih** [comment]
As a temporary solution I try to add "baseURL" tag to f4m manifest with nginx sub_filter (not good solution)

I get something like this:
```
xmlns="http://ns.adobe.com/f4m/1.0"><id>/a2/3d/a23d107fda2740c890822b1c2e5cf978/a23d107fda2740c890822b1c2e5cf978-,q1,q2,q3,.mp4.urlset/manifest.f4m</id>
<baseURL>http://best-server/a2/3d/a23d107fda2740c890822b1c2e5cf978/a23d107fda2740c890822b1c2e5cf978-,q1,q2,q3,.mp4.urlset</baseURL>
<duration>1408.040</duration>
<streamType>recorded</streamType>
<bootstrapInfo ...
```

It's properly accepted by the player.

**Comment by erankor** [comment]
I see... that makes sense, I'm quite sure that when I tested it, I used an absolute URL in the `url` attribute of `media` and it didn't work, I didn't try baseURL.
Anyway - try this branch - https://github.com/kaltura/nginx-vod-module/tree/support-hds-absolute-url
You need to add this to your config:
`vod_hds_absolute_manifest_urls on`

**Comment by dabih** [comment]
Wonderfull!

I tested it on my server, everything works as expected.
Thank you so much!

**Comment by erankor** [comment]
Great, merged to master
