### ISSUE TITLE
vod_metadata_cache on disk

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#448]
Hi! This cache persists in memory. Is it possible to make directive for saving this cache on a disk?

**Comment by erankor** [comment]
This was discussed in a few other threads in the past, we currently have no plans to add it.

**Comment by kuznetcoff777** [comment]
Strange, i did not find any.
So anyway i just want to describe my sitation, maybe you will plan for adding it.
I use remote config and we have really great amount of videos and i put 16gig for this cache. As just users begin to download videos, cache is really fast reached the limit and i saw about 60MB/s of metadata cache_fetch counter. So ofcourse it leads to a lot of read requests on a backend NAS server. And it seems to that 32gig will not help me. I suppose that if it will store this cache on a disk, then it will not overload backend NAS server.

**Comment by kuznetcoff777** [comment]
Sorry, one question more. If this metadata cache is necessary only when preparing ts files? When all ts files from video are prepared and are in disk cache then it is not necessary to keep this metadata cahe?

**Comment by erankor** [comment]
The cache is intended to prevent the module from reading the same data over and over again when building different segments of the same video. 
With the cache enabled, the metadata is read once on the first request for video X (let's say index.m3u8), and used for all subsequent requests for fragments of this video (seg-1.ts, seg-2.ts etc.)
