### ISSUE TITLE
How can i change the segment url

### ISSUE THREAD

**Issue by wanglinSZ** [kaltura/nginx-vod-module#450]
Hi guys,
    Now we have a url like 'http://test.com/play/filename?token=12345',we want use the remote hls mode, but in the generated m3u8 index file, the "?token=12345" is not in the segment uri.Is there a way for me to 
generating this?
like "http://test.com/play/filename/seg-1-v1-a1.ts?token=12345"

**Comment by erankor** [comment]
Check out this thread - https://github.com/kaltura/nginx-vod-module/issues/87
It's quite old, but the answer hasn't changed - this module does not output any query parameters in the returned segment URLs. That thread suggests a different approach to securing the video (assuming that's what you're trying to do)

**Comment by wanglinSZ** [comment]
Thanks a lot @erankor .
Yes ,We need to securing the video as you guest,but we donnot use akamai CDN,the token is used for the remote video service.Now we have another way to resolve this problem.
