### ISSUE TITLE
Are HTTP-POST requests supported by vod-module?

### ISSUE THREAD

**Issue by utu2016** [kaltura/nginx-vod-module#453]
Hi,
We see that the module is able to manage the HTTP-GET request (ie. when a udrm request is handled); but we'd like to know if the vod-module supports the HTTP_POST request.
If yes, please could you provide us some more information/configuration/examples?
thanks

**Comment by erankor** [comment]
If you are referring to DRM license requests, then the answer is no, the licenses have to be issued by some other server, this module handles the encryption of the media.
