### ISSUE TITLE
Passing on query parameters on URL generation

### ISSUE THREAD

**Issue by bson** [kaltura/nginx-vod-module#454]
I can't seem to figure out a way to pass on custom query parameters.  We have some we use for various purposes, for example `v=67d974918ea9476bd131ded687fd1cbf`.  I can't figure out any way to make these "stick" for inner HLS manifest URLs and segment URLs.  So I'd like to submit a feature request for "vod_query_params" with $var expansion, that gets added to all URLs.  Or any other method that solves the same underlying problem.  Unless there is already a way to do this I haven't thought of! :)

Oh, if these could also be passed on to an mapping API endpoint (for mapped mode) that would be an even bigger win...

**Comment by erankor** [comment]
See this thread https://github.com/kaltura/nginx-vod-module/issues/450, this is currently not supported.
Can you explain why you need it ? for tracking purposes or something ?
It's should be pretty easy to add this feature, but it's currently low priority for us. If anyone here would like to add it, feel free to submit a pull request. 
Btw, I think it would be slightly more convenient to call it `vod_url_suffix` and have the user add the '?' in the value of the parameter. This will save the need to handle the '?' explicitly in the code - the result of the var expansion will just be appended as-is to the url.

**Comment by bson** [comment]
We use it primarily for versioning assets and cache busting, without having to change base asset URLs.  There are some good legacy reasons for us currently not to embed it in the URL path or we'd do that... that would probably be a better solution in the long term but gets us into a square peg round hole situation until we can retire some of our legacy systems.  :/

**Comment by erankor** [comment]
Hi @bson,

We've just completed a refactoring to nginx-secure-token-module - https://github.com/kaltura/nginx-secure-token-module/pull/35. Following the refactoring, the module is not limited to embedding tokens in returned manifest, but can add arbitrary query string parameters. You can set `secure_token` to whatever expression you want to embed on the query string of segment URLs, and it supports var expansion.
I believe this should answer your requirement.

Eran

**Comment by bson** [comment]
Nice, will take a look at it.  We're also looking at DRM solutions right now and this is another area where this might be potentially helpful.  Thanks!

**Comment by mkrn** [comment]
Sorry for commenting on a closed issue. Does anyone actually has a sample of how to pass a query param to all segments using the nginx-secure-token-module?
