### ISSUE TITLE
Subtitles language on multiurl

### ISSUE THREAD

**Issue by lucasdavila86** [kaltura/nginx-vod-module#456]
Hi Eran!

I've managed to add the subtitles file on the multiurl uri but, the module always identify the language as English.

I have a folder with the video and subtitle files like this:
BERNARDAALBA_TEATRIX_3000k.mp4
BERNARDAALBA_TEATRIX_spa_vtt.mp4

And I'm using the multiurl like this
http://10.255.255.101/vod/BERNARDAALBA_TEATRIX_,3000k,spa_vtt,.mp4.urlset/master.m3u8

The master playlist file shows up in this way:
>#EXTM3U
>
>#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP->ID="subs",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES,URI="index-f2.m3u8"
>
>#EXT-X-STREAM-INF:PROGRAM->ID=1,BANDWIDTH=4965429,RESOLUTION=1920x1080,CODECS="avc1.64002a,mp4a.40.2",SUBTITLES=">subs"
>index-f1-v1-a1.m3u8

Is there a way to instruct the module to identify the subtitle file as in spanish?
How can handle multiple subtitle languages?
Is the mapped mode the only way?

thanks in advance,
Lucas

**Comment by erankor** [comment]
At the moment, mapped mode is the only way. 
As far as I know, there is no WebVTT tag that can be used to indicate the language of the file, if there were, that could be the most elegant solution. 
It is possible to add, with a small effort, a URL param for that, it would look something like this:
`http://domain/prefix,cap1/lang/spa,cap2/lang/eng,suffix.urlset/master.m3u8`

**Comment by lucasdavila86** [comment]
Great! Thanks

**Comment by erankor** [comment]
Try the branch lang-uri-param, here is a sample request:
```
curl localhost:8001/local/hls/content/lang/,spa/test.vtt,bul/test.vtt,eng/test.mp4,.urlset/master.m3u8
#EXTM3U

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="es",NAME="español",AUTOSELECT=YES,DEFAULT=YES,URI="http://localhost:8001/local/hls/content/lang/spa/test.vtt/index.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="bg",NAME="български език",AUTOSELECT=NO,DEFAULT=NO,URI="http://localhost:8001/local/hls/content/lang/bul/test.vtt/index.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=628837,RESOLUTION=688x320,FRAME-RATE=25.000,CODECS="avc1.42c01e,mp4a.40.1",SUBTITLES="subs"
http://localhost:8001/local/hls/content/lang/eng/test.mp4/index-v1-a1.m3u8
```

**Comment by erankor** [comment]
@lucasdavila86, did you try it out ? can we merge and close this issue ?

**Comment by lucasdavila86** [comment]
Hi erankor, sorry for the delay. I've just read the notification.
I'm going to try it again.

**Comment by cenkalti** [comment]
If I put more than one subtitle of the same language, only one of them is present on the master playlist. Is there a way to put more than one subtitle of the same language?

Like http://domain/prefix,cap1/lang/eng,cap2/lang/eng,suffix.urlset/master.m3u8

**Comment by erankor** [comment]
The key for the subtitles is the label - nginx-vod-module will not return more than one subtitles track for a single label. By default the label is derived from the language, and setting the label on the URL is not supported. 
To have multiple labels for a single language, your options are -
1. use mapped mode and set the label field in the JSON
2. set the label on the hdlr atom in the MP4 file + enable vod_parse_hdlr_name

**Comment by erankor** [comment]
Yes, mapped mode works with hls, there is no coupling between the mode and the protocol.
There were no changes in this regard since the above comment was written, what is the gap?
