### ISSUE TITLE
Post installation script failing

### ISSUE THREAD

**Issue by MansoorMajeed** [kaltura/nginx-vod-module#472]
Hey guys, just came across this issue while installing the prebuilt debian package. It seems the default nginx conf is having some synax errors.

```
Processing triggers for man-db ...
Setting up kaltura-nginx (1.10.2-1) ...
update-rc.d: using dependency based boot sequencing
Reloading nginx configuration: nginx: [emerg] invalid number of arguments in "server" directive in /opt/kaltura/nginx/conf/nginx.conf:17
nginx: configuration file /opt/kaltura/nginx/conf/nginx.conf test failed
kaltura-nginx.postinst FAILED with: 24887 on line 68
Archving logs to /opt/kaltura/log/log_27_11_16_05_57.tar.gz...
cp: cannot stat `/opt/kaltura/log/*log': No such file or directory
tar: *log: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
dpkg: error processing kaltura-nginx (--configure):
 subprocess installed post-installation script returned error exit status 11
Setting up htop (1.0.1-1) ...
Errors were encountered while processing:
 kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by jessp01** [comment]
Hi @MansoorMajeed,

The value for the "server" directive is taken from the deb conf input presented to you during the postinst script for kaltura-nginx. 

What's the current value you have in /opt/kaltura/nginx/conf/nginx.conf, line 17?

**Comment by MansoorMajeed** [comment]
@jessp01 our current conf is fine, but the issue is with the default conf that comes with the package. The following is the line(in the default conf):

```
 15   http {
 16           upstream kalapi {
 17                   server ;
 18           }
 19
```

**Comment by erankor** [comment]
@MansoorMajeed, this is the template - https://github.com/kaltura/nginx-vod-module/blob/master/conf/nginx.conf.template#L16
The fact it's empty means you did not enter any value for the `WWW_HOST` parameter during installation.

**Comment by MansoorMajeed** [comment]
makes sense. I'll close it. Thank you. :)
