### ISSUE TITLE
Support loop mode in  sequences or clips?

### ISSUE THREAD

**Issue by zhangqianliang** [kaltura/nginx-vod-module#479]
For example, same clip or sequence, I want to loop 4 times, 5 times or -1(for unlimited times).

**Comment by erankor** [comment]
The module does not have this feature, but it is possible duplicate the clip multiple times in the JSON. 
For unlimited, I assume you are talking about live (doesn't really make sense for vod), and in this case, we have this sample script https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php that shows how to create to a live stream from N videos playing in a loop

**Comment by zhangqianliang** [comment]
Thank you for your supporting, thank you.
