### ISSUE TITLE
support remote files in mapped mode

### ISSUE THREAD

**Issue by zhangqianliang** [kaltura/nginx-vod-module#484]
I found that "support remote files in mapped mode" in 1.10 release. But how can organize json file for this?

I make my json file like this:

```
{
    "playlistType": "live",
    "discontinuity": true,
    "initialClipIndex": 171,
    "initialSegmentIndex": 153,
    "firstClipTime": 1480910000000,
    "durations": [83000, 7980000],
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "http://192.168.100.104:8080/vod/file/demo.mp4"
                },
                {
                    "type": "source",
                    "path": "http://192.168.100.104:8080/vod/file/test.mp4"
                }
            ]
        }
    ]
}
```

but not affect.

**Comment by erankor** [comment]
You need to set vod_remote_upstream_location to the path of an nginx location that should be used to issue the remote requests (a location that uses proxy_pass, see how vod_upstream_location is used in the sample configs)
In the json, path should contain only the path of the url.
In your example, the conf could be something like:
```
upstream remote {
        server 192.168.100.104:8080;
}
...
location ^~ /remote/ {
            internal;
            proxy_pass http://remote/;
}
...
vod_remote_upstream_location /remote;
```
and the json will have:
```
"path": "/vod/file/test.mp4"
```

**Comment by zhangqianliang** [comment]
Thanks

**Comment by janiel14** [comment]
@erankor Good morning, I'm having trouble configuring nginx-vod-module to work with mapped vod-mode using remote files. I have a unique server for streaming using nginx with vod-module and another remote server with nginx providing the files in http. But when I go to access the json file it gives the 404 error, however I can access the json file using CURL in the URL of the file it works but nginx does not access it.

NGINX-VOD-MODULE
`upstream stream {
        server x.x.x.x:8080;
}
server {
        listen 80;
        server_name my.myhost.com;

        vod_mode mapped;
        vod_remote_upstream_location /vodstream;
        vod_upstream_extra_args "pathOnly=1";
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;

        # vod caches
       # vod_metadata_cache metadata_cache 512m;
       # vod_response_cache response_cache 128m;
       # vod_mapping_cache mapping_cache 5m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        # file handle caching / aio
       # open_file_cache          max=1000 inactive=5m;
       # open_file_cache_valid    2m;
       # open_file_cache_min_uses 1;
       # open_file_cache_errors   on;
        aio on;

        location ^~ /vodstream/ {
            internal;
            proxy_pass http://stream/;
        }

	location /vodhls/ {
            vod hls;
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
    }
`
Arquivo JSON
`{
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "http:\/\/x.x.x.x:8080\/52\/galeria\/7e4e6b86de0b672f3c6fdd2089584ca60b59ea95_10485.mp4"
                }
            ]
	},
	{
            "clips": [
                {
                    "type": "source",
                    "path": "http:\/\/x.x.x.x:8080\/52\/galeria\/7e4e6b86de0b672f3c6fdd2089584ca60b59ea95_10486.mp4"
                }
            ]
	},
	{
            "clips": [
                {
                    "type": "source",
                    "path": "http:\/\/x.x.x.x:8080\/52\/galeria\/7e4e6b86de0b672f3c6fdd2089584ca60b59ea95_10487.mp4"
                }
            ]
	}
    ]
}`

**Comment by cenkalti** [comment]
@erankor Is there a way to specify different hosts for separate clip paths?

**Comment by erankor** [comment]
You can include the host as part of the URL, e.g. in the json write "/http/www.example.com/path/to/video.mp4" and then in the location that does `proxy_pass` use regex capture to split the scheme and domain/uri. Something like -
```
location /proxy/([^/]+)/(.*) {
    proxy_pass $1://$2;
}
```

**Comment by cenkalti** [comment]
@erankor Thank you very much. I'll try this...

**Comment by cenkalti** [comment]
It worked! Thank you.

I decided to use remote mode btw.

The config I have used:
```
server {
    server_name vod;
    listen 8181;
    resolver 127.0.0.1;
    vod_mode remote;
    vod_upstream_location /proxy;
    location / {
        vod hls;
    }
    location ~ /proxy/([^/]+)/([^/]+)/(.*) {
        include proxy_params;
        proxy_pass $1://$2/$3;
    }
}
```

I am sending clients to `http://{vod_host}/http/{remote_host}/{remote_path}/master.m3u8`.

**Comment by erankor** [comment]
Great, make sure to limit the set of allowed domains, otherwise your server could be used to stream any content. You can, for example, use nginx's map module to map any domain that is not whitelisted to some error domain.

**Comment by cenkalti** [comment]
@erankor thanks for the tip. We don't need it because we are only using this server internally, it is not open to the Internet.

The reason is that we are making some changes on the playlist before returning it to clients such as:
* Changing host from `127.0.0.1:8181` to `{remote_host}` present in path component.
* Encrypting path component to hide internal filesystem hierarchy on the server.
* Adding `?oauth_token=...` query parameter to allow only authenticated requests.

**Comment by kililixi** [comment]
@erankor hi,  I'm having trouble wih remote files in mapped mode.My English is not very good. 
I did it according to the above. It works, but very very slow, cannot play normally.

Enviorment: Linux Version  ```CentOS7```, Nginx Version  ```1.16.0```, and there is no ffmpeg.

I built nginx with ```./configure --prefix=/usr/local/nginx-vod --add-module=/home/nginx/nginx-vod-module/ --with-file-aio --with-threads --with-debug --with-cc-opt="-O3" --with-cc-opt="-O0"```

Here is my conf:
```
http {
        upstream jsonupstream {
                server 127.0.0.1:81;
        }

        upstream mp4stream {
                server 127.0.0.1:82;
        }

        server {
                listen 81;
                location / {
                        root /home/www/json/;
                }
        }

        server {
                listen 82;
                location / {
                        root /home/www/video/;
                }
        }
        server {
                # vod settings
                vod_mode mapped;
                vod_upstream_location /json;
                vod_remote_upstream_location /proxy;
                vod_upstream_extra_args "pathOnly=1";
                vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
                vod_last_modified_types *;

                # vod caches
                vod_metadata_cache metadata_cache 512m;
                vod_response_cache response_cache 128m;
                vod_mapping_cache mapping_cache 5m;

                # gzip manifests
                gzip on;
                gzip_types application/vnd.apple.mpegurl;

                # file handle caching / aio
                open_file_cache   max=1000 inactive=5m;
                open_file_cache_valid    2m;
                open_file_cache_min_uses 1;
                open_file_cache_errors   on;
                aio on;

                location ^~ /json/hls/ {
                        internal;
                        proxy_pass http://jsonupstream/;
                        proxy_set_header Host $http_host;
                }

                location ^~ /proxy/ {
                        internal;
                        proxy_pass http://mp4stream/;
                        #resolver 8.8.8.8;
                }

                location ~ ^/hls/ {
                        vod hls;

                        add_header Access-Control-Allow-Headers '*';
                        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                        add_header Access-Control-Allow-Origin '*';
                        expires 100d;
                }
        }
}
```
 http://127.0.0.1:81/test.json returns the following JSON:
```
{
	"sequences": [{
		"clips": [{
			"type": "source",
			"path": "/abc.mp4"
		}]
	}]
}
```

I have a mp4 file in ``` /home/www/video/```, so it can be access by ```http://127.0.0.1:82/xxx.mp4```,the mp4 file is about 170m, and here is the information about the mp4:
```
 Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isom
    creation_time   : 2016-07-01T19:38:33.000000Z
  Duration: 00:24:00.11, start: 0.000000, bitrate: 1010 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 813 kb/s, 23.98 fps, 23.98 tbr, 23999 tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2016-07-01T19:15:39.000000Z
      handler_name    : GPAC ISO Video Handler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
```
And then ,i use the url ```http://server/hls/test.json/master.m3u8``` in VLC Media Player, it works, but very very slow, it takes minutes to show a frame.
And here is the m3u8 file:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1006406,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.640029,mp4a.40.2"
http://192.168.45.129/hls/test.json/index-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=144588,RESOLUTION=1280x720,CODECS="avc1.640029",URI="http://192.168.45.129/hls/test.json/iframes-v1-a1.m3u8"

```
(I think it's a little different from .m3u8 in local mode?)
There is no errors in errors.log, but there is a lot of info access.log:
```
192.168.45.1 - - [18/May/2019:00:25:05 +0800] "GET /hls/test.json/seg-1-v1-a1.ts HTTP/1.1" 200 1242680 "-" "VLC/3.0.6 LibVLC/3.0.6"
127.0.0.1 - - [18/May/2019:00:25:07 +0800] "GET /abc.mp4?pathOnly=1 HTTP/1.0" 206 262144 "-" "VLC/3.0.6 LibVLC/3.0.6"
127.0.0.1 - - [18/May/2019:00:25:07 +0800] "GET /abc.mp4?pathOnly=1 HTTP/1.0" 206 262144 "-" "VLC/3.0.6 LibVLC/3.0.6"
127.0.0.1 - - [18/May/2019:00:25:07 +0800] "GET /abc.mp4?pathOnly=1 HTTP/1.0" 206 262144 "-" "VLC/3.0.6 LibVLC/3.0.6"
```
It's normal in local mode, or the mp4 is a local file in mapped mode.

Was there anything wrong with what I did? Can you give me some advices? 
Thank you very much!

**Comment by erankor** [comment]
1. Why are you using remote mode against localhost? or is this only for testing?
2. I suggest changing the access log format to also include $request_time, so that you'll be able to see how much time each request takes. Also worth printing the value of the range request header/content-range response header, in order to see which ranges are being requested
3. Don't think it matters much in terms of the slowness, but you are compiling with --with-debug and -O0

**Comment by kililixi** [comment]
@erankor Thank you for your reply.
1. yes, just a test. At first , i use fs like seaweedFS to storage the mp4 files, but it return code 301, so i changed to localhost for testing.
2. Ok, i will try.
3. So i should compile it with '--with-cc-opt="-O3' ? 

thank you !

**Comment by erankor** [comment]
3. Yes, we are using O3, however the difference between O2 & O3 is marginal

**Comment by kililixi** [comment]
@erankor Hi, i rebuild the nginx with  '--with-cc-opt="-O3' , it's better, but still took about 20s.(Is it normal in remote mode ? I mean that if i use a high performance computer , it will take less time ? I build    the nginx in a Virtural Machine which hava 2GB memory)
Here is the log_format
```
 log_format  main  'LOG: $remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" '
                          'request_time "$request_time" '
                          'content-range "$sent_http_content_range"';

 access_log /usr/local/nginx-vod2/logs/main.log main;
``` 
And here is a part of main.log :
```
LOG: 192.168.45.1 - - [20/May/2019:23:18:57 +0800] "GET /hls/test2.json/seg-82-v1-a1.ts HTTP/1.1" 200 142697 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "20.708" content-range "-"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 101337402-101599545/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 101599546-101861689/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 101861690-102123833/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 102082686-102344829/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 102304574-102566717/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 121276 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 102548279-102669554/181820464"
LOG: 192.168.45.1 - - [20/May/2019:23:19:01 +0800] "GET /hls/test2.json/seg-82-v1-a1.ts HTTP/1.1" 200 1393080 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.059" content-range "-"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 102656779-102918922/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 102900391-103162534/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 103116466-103378609/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 103378610-103640753/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 103640754-103902897/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 81043 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 103559711-103640753/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 103902898-104165041/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 89685 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 103813213-103902897/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 182630 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 104165042-104347671/181820464"
LOG: 192.168.45.1 - - [20/May/2019:23:19:01 +0800] "GET /hls/test2.json/seg-83-v1-a1.ts HTTP/1.1" 200 1775096 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.029" content-range "-"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 104293968-104556111/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 104539665-104801808/181820464"
LOG: 127.0.0.1 - - [20/May/2019:23:19:01 +0800] "GET /abc.mp4 HTTP/1.0" 206 262144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.000" content-range "bytes 104785719-105047862/181820464"
LOG: 192.168.45.1 - - [20/May/2019:23:19:01 +0800] "GET /hls/test2.json/seg-84-v1-a1.ts HTTP/1.1" 200 385400 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-" request_time "0.004" content-range "-"
```
Thanks you !

**Comment by erankor** [comment]
Since it's always very close to 20 sec, you're most likely hitting some kind of timeout.
Do you have some timeout set to 20? some proxy_xx_timeout maybe? I don't see it here, but the config isn't full...

**Comment by kililixi** [comment]
@eranko Hi. I don't think i dit it, there are some default configurations(like ```worker_processes 1 ``` and ``` events ```) outside the ```http```.  
Thank you !

**Comment by erankor** [comment]
Maybe it makes sense to go back to debug (--with-debug) + enable writing debug strings in nginx.conf (error_log directive).
Then, make a request to a single segment, and check the log to see where the 20 sec are spent. It's better not to use a player for this, since the player may issue multiple requests in parallel, making the log harder to understand.
