### ISSUE TITLE
live streaming with multiple bit rates

### ISSUE THREAD

**Issue by amoondra19** [kaltura/nginx-vod-module#492]
Hi,

I am using the playlist.php file to generate a live stream. 
I want to have multiple bit rates in my live streaming. Could you please let me know what an example json would like for this? The json file currently created by playlist.php looks like below and doesn't serve the prupose.

```
{
	"firstClipTime": 1481796958320,
	"initialClipIndex": 3,
	"initialSegmentIndex": 71,
	"discontinuity": true,
	"playlistType": "live",
	"durations": [341160, 341160, 341160, 341160],
	"sequences": [{
		"clips": [{
			"type": "source",
			"path": "\/var\/mapped\/abcd_360.mp4"
		}, {
			"type": "source",
			"path": "\/var\/mapped\/abcd.mp4"
		}, {
			"type": "source",
			"path": "\/var\/mapped\/abcd_360.mp4"
		}, {
			"type": "source",
			"path": "\/var\/mapped\/abcd.mp4"
		}]
	}]
}
```

I am using apache2(:80) as an upstream server and this is how I am accessing the playlist.

http://localhost:8001/mapped/playlist.php/disc/1/type/live/master.m3u8

I think I need to tweak the playlist.php file to serve my purpose but need an example for the json.

**Comment by erankor** [comment]
You need to add another element under the `sequences` array for each bitrate.
Here is a simple example of how adaptive bitrate looks like in the JSON:
https://github.com/kaltura/nginx-vod-module/#adaptive-set
Naturally you have to make sure the first clip in sequence 1 is the same video as the first clip in sequence 2, except that it has been encoded differently.

**Comment by amoondra19** [comment]
Thank you. I will try it.

**Comment by erankor** [comment]
@amoondra19, can we close this issue ?

**Comment by amoondra19** [comment]
Yes.
