### ISSUE TITLE
Install kaltura on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ahotnik** [kaltura/nginx-vod-module#494]
1. sudo su
2. wget -O - http://installrepo.kaltura.org/repo/apt/debian/kaltura-deb.gpg.key|apt-key add -
_result:ok_
3. echo "deb [arch=amd64] http://installrepo.kaltura.org/repo/apt/debian lynx main" > /etc/apt/sources.list.d/kaltura.list
4. apt-get update
_Reading package lists... Done_
5. apt-get install kaltura-nginx
```
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kaltura-nginx : PreDepends: kaltura-ffmpeg but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
6. Trying install kaltura-ffmpeg
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kaltura-ffmpeg : Depends: libass4 but it is not installable
                  Depends: libopenjpeg2 but it is not installable
                  Depends: libvpx1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Someone found a solution?

**Comment by ahotnik** [comment]
Multiverse enabled
```
## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://ua.archive.ubuntu.com/ubuntu/ xenial multiverse
# deb-src http://ua.archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://ua.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
# deb-src http://ua.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
```

**Comment by jessp01** [comment]
Hello,

For 16.04, use this repo instead:
```
deb [arch=amd64] http://installrepo.origin.kaltura.org/repo/apt/debian-11.16.0-xenial kajam main
```
Thanks,

**Comment by ahotnik** [comment]
Thank you. How to fully remove and install kaltura, because
```
root@root/# dpkg-reconfigure kaltura-nginx
/usr/sbin/dpkg-reconfigure: kaltura-nginx is broken or not fully installed
```

**Comment by jessp01** [comment]
\# aptitude purge kaltura-nginx
or if using apt-get
\# apt-get purge kaltura-nginx

Then set the repo as I said and:
\# aptitude update && aptitude install kaltura-nginx

**Comment by ahotnik** [comment]
After this 
```
Errors were encountered while processing:
 kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by jessp01** [comment]
Please post the entire terminal output from these commands.

**Comment by ahotnik** [comment]
Please.
```
Hit:1 http://ua.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ua.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                        
Hit:3 http://ua.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                      
Hit:4 http://installrepo.origin.kaltura.org/repo/apt/debian-11.16.0-xenial kajam InRelease                                
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Fetched 102 kB in 0s (133 kB/s)                                
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
kaltura-nginx is already the newest version (1.8.1-1+b4).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up kaltura-nginx (1.8.1-1+b4) ...
insserv: script kaltura-nginx: service nginx already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
ERROR:could not find /opt/kaltura/bin/kaltura-functions.rc so, exiting..dpkg: error processing package kaltura-nginx (--configure):
 subprocess installed post-installation script returned error exit status 3
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Errors were encountered while processing:
 kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by jessp01** [comment]
What does /opt/kaltura/log/nginx/error_log contain?

**Comment by ahotnik** [comment]
No such file.

**Comment by jessp01** [comment]
Sorry, there is a small bug there. To go around it, do:
\# touch /opt/kaltura/bin/kaltura-functions.rc
\# aptitude install -f
should be good after that.

**Comment by ahotnik** [comment]
Sorry, didn't understand.
I first need install nginx, after kaltura. Or first kaltura, after nginx?

**Comment by jessp01** [comment]
Perhaps I don't understand what you want to do. Do you just want to make use of the Nginx vod module, in which case, from where you are now, just run:
\# touch /opt/kaltura/bin/kaltura-functions.rc
\# aptitude install -f
and you will have the kaltura-nginx package installed and ready to go or do you want to install the entire Kaltura server? in which case you should follow:
https://forum.kaltura.org/t/kaltura-ce-ubuntu-16-04-x64/5008/3

The VOD module does NOT require the full Kaltura server in order to function, it can work by itself, by install the kaltura-nginx package.

**Comment by ahotnik** [comment]
Thank you for answer! 
Okey, after:
```
# touch /opt/kaltura/bin/kaltura-functions.rc
# aptitude install -f 
```
How can i repackaging my mp4 file to hls, dash? 
However, i wont build easy local project, where i upload mp4 file and repacking him to hls or dash. 
Found this module and try the fourth day install.
That's my goal. ty

**Comment by jessp01** [comment]
Read the documentation for the module here:
https://github.com/kaltura/nginx-vod-module/blob/master/README.md
As it says, the module supports 3 operation modes:
    Local - serve locally accessible files (local disk/NFS mounted)
    Remote - serve files accessible via HTTP using range requests
    Mapped - serve files according to a specification encoded in JSON format. The JSON can pulled from a remote server, or read from a local file

**Comment by ahotnik** [comment]
Hello. 
I compile nginx-vod-module to my nginx server. 
Have a link 
`http://localhost/content/test.mp4/manifest.mpd`
Рow can I beat on the quality, example 720,480,360?

**Comment by erankor** [comment]
Not sure I understand the question, but if you are asking about multiple bitrates, then you have to prepare the different renditions in advance and provide them to nginx-vod-module.
Regarding vod_moov_cache, it was removed long time ago, replaced by vod_metadata_cache (https://github.com/kaltura/nginx-vod-module/blob/master/CHANGELOG.md#20160203---added-support-for-matroska-container)

**Comment by jessp01** [comment]
Closing this issue since the original question as to installing the kaltura-nginx deb packageeeee was answered. If there are additional questions, please open a new issue and set a proper title for it.
