### ISSUE TITLE
$vod_set_id is empty

### ISSUE THREAD

**Issue by vs-adm** [kaltura/nginx-vod-module#495]
Module is working in mapped mode. The corresponding JSON is

```json
{
  "id": "12345",
  "sequences": [
    {
      "id": "12345",
      "clips": [
        {
          "type": "source",
          "path": "/full/path/to/file.mp4"
        }
      ]
    }
  ]
}
```

NGINX config sets `log_format`

```
log_format vodlog '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $bytes_sent '
                       '"$http_referer" "$http_user_agent" "$vod_set_id" "$vod_sequence_id" '
                       '"$upstream_http_x_session_id"';

...

access_log /var/log/nginx/access.log vodlog;
```

I see dashes on the last positions in the log lines

```
10.211.55.2 - - [20/Dec/2016:05:38:49 +0300] "GET /request/to/content/playlist.m3u8?sessionId=someToken&userId=1 HTTP/1.1" 200 944 "-" "curl/7.51.0" "-" "-" "-"
```

Is it supposed to have empty `$vod_set_id` here? BTW, is any way to have an access to upstream response headers?

**Comment by erankor** [comment]
This probably happens because the json is a very simple one, this makes the code take a slightly different path. 
Try adding the following 2 lines here https://github.com/kaltura/nginx-vod-module/blob/master/ngx_http_vod_module.c#L4552:
```
ctx->submodule_context.media_set.id = mapped_media_set.id;
sequence->id = mapped_media_set.sequences->id;
```
If it works for you, I'll merge it.

**Comment by vs-adm** [comment]
Yes, this patch worked for me. Here is PR #501

**Comment by erankor** [comment]
Merged, thanks
