### ISSUE TITLE
Map mode,the number of paths in json file was limited at 3

### ISSUE THREAD

**Issue by RecareLee** [kaltura/nginx-vod-module#502]
In our practice,we use nginx vod module to repackage hls live stream,but we found that when writed 4 paths in the "clips" filed, nginx  will throw following error:failed to parse json -1: end of data while parsing string (2), it only support 3 or less paths in the mapping json file, is there any solution about this issue or i write this json file incorrectly?
my practice json file is :  
"segmentBaseTime":1482728495000,
    "firstClipTime":1482732639000,
    "durations":[
       10000,10000,10000,10000
    ],
    "sequences":[
        {
            "clips":[
                {
                    "type":"source",
                    "path":"/mnt/live/0000autotest000020150501015802520000/512/20161223065132_885857_4035.mp4"
               },
               {
                    "type":"source",
                    "path":"/mnt/live/0000autotest000020150501015802520000/512/20161223065142_885857_4036.mp4"
               },
               {
                    "type":"source",
                    "path":"/mnt/live/0000autotest000020150501015802520000/512/20161223065152_885857_4037.mp4"
               },
              {
                    "type":"source",
                    "path":"/mnt/live/0000autotest000020150501015802520000/512/20161223065152_885857_4038.mp4"
               }
            ]
        }
    ]
}

**Comment by erankor** [comment]
You need to increase `vod_max_mapping_response_size`, the default limit for the size of the JSON is 1k

**Comment by RecareLee** [comment]
thanks! it works now, and another issue is we found that we write 5 paths of mp4 file in the mapping json file, in hls mode, it can show 5 list of ts file in m3u8file,but in mss mode, it only show 3 list of media record.  Is this caused by mss forced 2 lookaheadcount? the nginx error is : segment count 2 smaller than look ahead segment count while reading media header.

**Comment by erankor** [comment]
In MSS you need to have at least 3 segments to get a manifest. The reason is that when nginx-vod-module returns segment N, it has to know the timestamps of segment (N+1) and (N+2) in order to put them in the look ahead table (in MSS each segment contains the timestamps of the 2 segments that follow it)
Btw, when I tested it, I tried to disable look ahead entirely, but it did not work, it seems the players don't know how to work without it.

**Comment by RecareLee** [comment]
Thanks lot!, it seems that mss protocol forced it. Actually how to build a json file to map the same video source with different bitrate，for example, we have two MP4 files, they are the same video in two kinds of bitrate, how can i write the json file and send to the player, i just want the player to chose it's favorite bitrate. should i use mixfillter or dynamic fillter?  if possible, wish u could show me the demo json?

**Comment by erankor** [comment]
See this thread https://github.com/kaltura/nginx-vod-module/issues/492

**Comment by RecareLee** [comment]
Got it,thanks!

**Comment by RecareLee** [comment]
Another question, i have two different bitrate hls stream, when building the json file, i added 4 paths of mp4 file in birate1,and added 3 paths of mp4 file in birate2, how should i set the number of duration array elements?

**Comment by erankor** [comment]
you can't do that, the `durations` array applies to all bitrates, it must have the same number of elements as all the `clips` arrays.

**Comment by RecareLee** [comment]
OK，thanks erankor. I see  in thread #320 , you said that hls live streaming is still in the works, is there accutate time it can be released?

**Comment by erankor** [comment]
I was referring to the project that creates the JSON, from your questions it seems you are building the JSON yourself

**Comment by RecareLee** [comment]
I have met some trouble in handling hls live streaming. my source live stream is hls(ts), i want provide multi media-protocal service,such as hls, dash, mss,hds, the trouble is i must  save the ts source segements and repackage it to mp4,then building the json file for nginx-vod-moudle,so that the dash ,hls and mss manifest request can be served. if your module can add this function and support different packging live stream, it can be very helpful.

**Comment by erankor** [comment]
This is what this project does https://github.com/kaltura/liveDVR/
Unfortunately, not much documentation there...

**Comment by RecareLee** [comment]
Hi, erankor, is there any example that how to add drm info into dash mpd file?

**Comment by erankor** [comment]
there is a sample json here - https://github.com/kaltura/nginx-vod-module/#drm

**Comment by RecareLee** [comment]
Hi,erankor:
    can this module support on the fly drm info? 
we have a  media json ,inside it discribed 6 mp4 files, we want to encrypt the head 3 mp4 files with drm1 and   encrypt the last 3 mp4 files with drm2.

**Comment by RecareLee** [comment]
or how should we discribe multi contentprotection in dash mpd for different segments?

**Comment by erankor** [comment]
The drm info is requested per sequence, so if you have multiple sequences you can use different encryption parameters for them. However, from our experience, this doesn't work well, some devices don't like it, e.g. one problem we had was that on Android if one representation has Widevine+PlayReady and another has only Widevine the stream would not play. 
Maybe it's possible to fix this by having different drm info's rendered as different adaptation sets (in your example - one adaptation set for drm1 and one adaptation set for drm2), but at the moment this logic does not exist (multiple drm info's will be rendered under the same adaptation set)

**Comment by RecareLee** [comment]
Thanks a lot !  How to configure directives like vod_response_cache, vod_mapping_cache, vod_drm_info_cache, in my practice, I found that when configured these directives, for different json file, it always hit the same json response.  for example, "vod_response_cache vod_dash_json_res_cache 10m 180d;"  what the key  is for vod response cache ?

**Comment by erankor** [comment]
the keys are:
* vod_response_cache - the request URL (e.g. /x.mp4/index.m3u8)
* vod_metadata_cache - the MP4 file path (for local) or the full upstream URL (for remote)
* vod_mapping_cache - the mapping request URL or file path (for local mapping)
* vod_drm_info_cache - the DRM request URL
if you are using the latest version, it is possible that the DRM cache will not work as expected, the key for this cache was changed not very long ago

**Comment by RecareLee** [comment]
Another issue, in mapping mod, the vod_upstream_location is ”/proxy_json“， can i use proxy cache in this location? i found it doesn't work.  for example the "/proxy_json" as following: 
location /proxy_json
{
     internal;
     set $live_json_path "";
     rewrite_by_lua '
            ngx.log(ngx.DEBUG,"live map request uri:",ngx.var.request_uri)
            local _,_,live_json_path  = string.find(ngx.var.request_uri,"%?path=([^&]*)")
            ngx.var.live_json_path = ngx.decode_base64(live_json_path)
            ngx.log(ngx.DEBUG,"live map json proxy path:",ngx.var.live_json_path)
 ';
     proxy_pass $live_json_path;
     proxy_cache cache_json ;
     proxy_cache_valid 200 304 2s;
     proxy_cache_key $live_json_path;
}      there are no cache file in the cache_json path.

**Comment by erankor** [comment]
I don't think proxy_cache can work with nginx subrequests, but anyway, you can simply use the vod_xxx_cache directives to cache this stuff. These use memory cache which is faster, and since these responses are small, even few MBs should be enough.

**Comment by RecareLee** [comment]
Well, erankor,i found the vod_xxx_cache directives works perfectly!  And how to discribe the json file in mapped mode to let nginx-vod-module generate multi peroids in manifest.mpd?  there are no exmaple in the documentation...

**Comment by RecareLee** [comment]
Hi erankor, i guess i find the answers.  in my json file ,i configured the "discontinuity" directive in the value "true", In mapped mode for dash service, if i try the json file in "alias" mode, it can build multi periods in the manifest.mpd, but in the dash location if i configured vod_upstream_location, the vod_upstream_location can return this same json by "try_files" ,however, there are only one period in the manifest.mpd. it seems that by vod_upstream_location, nginx-vod-module thought the json's stream is  continuous stream. how should i configured the dash location if i must use vod_upstream_location to gererate non-continuous dash stream?

**Comment by erankor** [comment]
I think you have some mistake, this doesn't make sense, the processing of the json is completely detached from the way it was read. Maybe you see this behavior due to caching in the upstream server on in nginx-vod. You can enable debug messages to see which json nginx-vod actually got

**Comment by RecareLee** [comment]
You are right ! reankor , it  just because i configured the vod_force_continuous_timestamps  on in the dash location.  when i try dash live m4s service, i found some error in the error.log as follows: "segmenter_get_start_end_ranges_no_discontinuity: request for the last segment in a live presentation (1) while sending to client" , what does this mean?  cauce the json given to maniest requests are ahead than m4s requests?

**Comment by erankor** [comment]
In live, the last video segment is usually incomplete, for example, if the manifest points to 35 seconds of video, and the segment size is 10 sec, the last 5 seconds are incomplete until more data will arrive. 
This errors means that such an incomplete segment was requested by the client. The server blocks this request (instead of returning the 5 sec it has) so that this incomplete segment won't get cached in the CDN.

**Comment by RecareLee** [comment]
You are right ! reankor , it  just because i configured the vod_force_continuous_timestamps  on in the dash location.  when i try dash live m4s service, i found some error in the error.log as follows: "segmenter_get_start_end_ranges_no_discontinuity: request for the last segment in a live presentation (1) while sending to client" , what does this mean?  cauce the json given to maniest requests are ahead than m4s requests?

**Comment by RecareLee** [comment]
Thanks erankor! i try to use iframe m3u8 in hls request, but i found that in map mode, the iframe request reponse are different with index.m3u8 request response, for example, the iframe m3u8 is : #EXTM3U
#EXT-X-I-FRAMES-ONLY
#EXTINF:0.880,
#EXT-X-BYTERANGE:122952@376
seg-3-v1-a1.ts?
#EXTINF:0.120,
#EXT-X-BYTERANGE:99640@466052
seg-3-v1-a1.ts?

the index.m3u8 is : 
#EXT-X-MEDIA-SEQUENCE:18237092
#EXTINF:2.000,
seg-18237092-v1-a1.ts?
#EXTINF:2.000,
seg-18237093-v1-a1.ts?
#EXTINF:2.000,
seg-18237094-v1-a1.ts?

as you can see, the ts name in iframe m3u8 is differ with index.m3u8, when i try ts  discribed in iframe m3u8, there are some error throwed :     "f[segmenter_get_start_end_ranges_no_discontinuity] [error] 23857#23857: *4656 segmenter_get_start_end_ranges_no_discontinuity: segment start time 4000 is less than sequence start time 36473605000 while sending to client"
