### ISSUE TITLE
Problems with remote mode

### ISSUE THREAD

**Issue by SoleSS** [kaltura/nginx-vod-module#509]
I've got a stream: http://127.0.0.1:8001/ttv/pid/885c12f4175eae989d0c24c339ae2694883cfdb2/TV
i want to make a hls stream out of that...

my nginx conf:

	location ^~ /remote/ {
            internal;
            proxy_pass http://127.0.0.1:8001/;
            proxy_set_header Host $http_host;
        }

location ~ ^/hls/(.*) {
    vod hls;
    vod_mode remote;
    vod_upstream_location /remote/$1;
    gzip on;
    gzip_types application/vnd.apple.mpegurl;
    add_header Access-Control-Allow-Headers '*';
    add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
    add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
    add_header Access-Control-Allow-Origin '*';
}

i get 400 error when requesting url http://127.0.0.1:8001/hls/ttv/pid/885c12f4175eae989d0c24c339ae2694883cfdb2/TV: bad request

Looking for your help...

**Comment by erankor** [comment]
you need to add /index.m3u8 to the end of the url

**Comment by SoleSS** [comment]
Looks like not working :)
to /remote location args are not passed...

vod_upstream_location /remote/$1; gets $1 as arg (not ttv/pid/885c12f4175eae989d0c24c339ae2694883cfdb2/TV)

**Comment by erankor** [comment]
vod_upstream_location need to be a prefix to the url and it can't contain args.
You need to - 
1. change vod_upstream_location to /remote
2. since I assume you don't want /hls/ on the upstream requests, change `location ^~ /remote/ {` to `location ^~ /remote/hls/ {`, this will make nginx proxy module remove this prefix for you

**Comment by SoleSS** [comment]
still where is one small problem... /index.m3u8 also passed to upstream...

**Comment by erankor** [comment]
can you paste the config?

**Comment by SoleSS** [comment]
location ^~ /remote/hls/ {
            internal;
            proxy_pass http://127.0.0.1:8001/;
	    proxy_read_timeout 30;
	    proxy_connect_timeout 30;
            proxy_set_header Host $http_host;
        }

location ~ ^/hls {
    vod hls;
    vod_mode remote;
    vod_upstream_location /remote;
    gzip on;
    gzip_types application/vnd.apple.mpegurl;
    add_header Access-Control-Allow-Headers '*';
    add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
    add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
    add_header Access-Control-Allow-Origin '*';
}

I managed to connect... last attribute of upstream is optional and i've replaced it with index.m3u8 (http://127.0.0.1/hls/ttv/pid/1635a06a61b2f7fdd789a2eb8faa9db3dde3b2d4/index.m3u8) of course its a solution, but not as good as could be...

but another problem appeared... upstream is a live stream and looks like module just can't make a live playlist out of it...

then i tried to use a static stream, but still - no luck...
http://127.0.0.1/hls/static/another_stream/index.m3u8 module just disconnects after some time...

**Comment by erankor** [comment]
Well, it doesn't happen for me, took your configuration, only changed port 8001 to port 80, and hls to xhls (already had an hls location...). When I curl `myserver/xhls/test.mp4/index.m3u8` the upstream gets a request for `/test.mp4`. So maybe something outside of this config block is messing it up.
But I didn't quite understand what you wrote about live, the module is expecting to get an mp4, what is your upstream URL returning?

**Comment by SoleSS** [comment]
I have h.264 encoded http live stream accessible by VLC
i want to encode it to hls
(thats not a live stream, but i get it the same way: http://info-tech.pro/ttv/pid/5953213c22c304b4f2aab0029a0915fbadca3f8a/Sintel)

**Comment by erankor** [comment]
I don't know if you are referred to fragmented mp4 or something else, but live stream can't work this way. 
The vod URL you pasted looks like a normal mp4 now, but I got inconsistent results hitting it before (sometimes it had the mp4 headers, sometimes it didn't)

**Comment by SoleSS** [comment]
:) i've already used hls for streaming live video from camera... so "live stream can work" :)
but i agree that my stream is "special", and as i've already said: looks like module can't handle it :(

**Comment by erankor** [comment]
I wasn't talking about live in general, I was talking about live with nginx-vod-module.
I know HLS supports live :) this module supports it, but not with this input.
