### ISSUE TITLE
Iframe generation

### ISSUE THREAD

**Issue by keiskar** [kaltura/nginx-vod-module#514]
Hello,
Prompt as it is possible to form the iframe type: http://mysite.com/secure_link/iframe instead of links type: http://mysite.com/secure_link/video.mp4/manifest.f4m  ?

**Comment by erankor** [comment]
Are you asking about HLS iframes playlist?
If so, then it is supported, you need to use a file name of `iframes.m3u8` instead of `index.m3u8`.
This feature is only supported for simple vod scenarios (not playlist for example) and only in clear HLS (not AES-128/SAMPLE-AES)

**Comment by keiskar** [comment]
not quite, how to change a link to a video that did not use the index.m3u8/manifest.f4m

**Comment by erankor** [comment]
I'm sorry, I don't understand what you're asking

**Comment by keiskar** [comment]
convert url at http://mysite.com/secure_link/video.mp4/manifest.f4m  - > http://mysite.com/secure_link/iframe

**Comment by erankor** [comment]
Still not clear, can u send real urls that show what you're expecting ? 
Also, your sample used f4m, iframes playlist is supported only for hls

**Comment by keiskar** [comment]
I need to look on another link:
http://cdn.seasonvar.cc/hds/Deadpool2016.mp4/manifest.f4m -> http://cdn.seasonvar.cc/hds/Deadpool2016.mp4/iframe

**Comment by keiskar** [comment]
Redirection of such ?
`location ~* manifest.f4m {
	rewrite ^ iframe $scheme://$host$1 permanent;
}`

**Comment by erankor** [comment]
more like this:
```
location /hds/ {
rewrite (.*)/iframe$ $1/manifest.f4m last;
}
```

**Comment by keiskar** [comment]
In this embodiment, the link is not working, and get in the log errors have nothing
http://cdn.seasonvar.cc/hds/Deadpool2016.mp4/iframe

**Comment by erankor** [comment]
well, it is working for me, here's a full example with hls (same idea will work for all other protocols as well):
```
                location /local/hls/content/ {
                        vod hls;
                        vod_mode local;
                        rewrite (.*)/iframe$ $1/index.m3u8 last;
                        add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
                        expires 100d;
                }
```
and then it's possible to do this:
```
curl -s http://localhost:8001/local/hls/content/x.mp4/iframe | head
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
http://localhost:8001/local/hls/content/x.mp4/seg-1-v1-a1.ts
#EXTINF:10.000,
http://localhost:8001/local/hls/content/x.mp4/seg-2-v1-a1.ts
```

**Comment by keiskar** [comment]
Yes, I have the same
`[root@cdn ~]# curl -s http://cdn.seasonvar.cc/hls/Deadpool2016.mp4/iframe | head
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:2.000,
http://cdn.seasonvar.cc/hls/Deadpool2016.mp4/seg-1-v1-a1.ts
#EXTINF:2.000,
http://cdn.seasonvar.cc/hls/Deadpool2016.mp4/seg-2-v1-a1.ts`
But while checking through the player has an error for some reason, check here:
http://osmfhls.kutu.ru/

**Comment by erankor** [comment]
That's because OSMF relies on the file extension to detect which handler should play the content, once you removed the m3u8 from the URL it doesn't figure out it's HLS. 
If you use the original index.m3u8 URL in this player it plays fine. And also, if you take the iframe URL and play it in an iPhone it will work as well, since iPhone doesn't care about the file extension, it uses the content-type header to detect the format.

**Comment by keiskar** [comment]
Thx
