### ISSUE TITLE
Dynamic module

### ISSUE THREAD

**Issue by benbro** [kaltura/nginx-vod-module#515]
Is it possible to load vod as a [dynamic module](https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/)?
```bash
./configure --with-nginx-vod-module=dynamic
```

**Comment by jessp01** [comment]
Yes, see https://github.com/kaltura/nginx-vod-module/pull/281

**Comment by erankor** [comment]
yes, but the command you wrote is how it looks like for built-in nginx modules, for external modules it's something like this - 
```
./configure --add-dynamic-module=/path/to/nginx/vod/source
```

**Comment by benbro** [comment]
Will be useful to add this note to the README.
Thanks.
