### ISSUE TITLE
Error on vod_hls_encryption_method and vod_drm_enabled

### ISSUE THREAD

**Issue by davidoster** [kaltura/nginx-vod-module#516]
I am using the tag base 1.10 and I was trying at first with HLS and the vod_hls_encryption_method but when I was testing the nginx files (-t) it was coming up with unknown directive vod_hls_encryption_method.

Then I moved to dash and the use of DRM but again I had an unknown directive vod_drm_enabled.
Any ideas?

**Comment by erankor** [comment]
You probably have some problem with openssl. When you run configure, the module detects whether openssl is available or not, if it's not, it compiles with support for encryption. 
You can see it in the configure output:
```
adding module in ./nginx-vod-module
checking for OpenSSL EVP library ... found
```

**Comment by davidoster** [comment]
Oh! Thanks a lot! I will check again the output from the configure.

**Comment by RecareLee** [comment]
Hi, erankor, i want to know whether  i can  use nginx-vod-module to encrypt media in multiDRM at the same time?   that's mean common encryption

**Comment by davidoster** [comment]
Well there is definitely something wrong here,

**Output from nginx -V**
`nginx version: nginx/1.11.6
built by gcc 4.9.2 (Debian 4.9.2-10)
built with OpenSSL 1.0.2f  28 Jan 2016
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-ipv6 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_perl_module --with-threads --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-stream_realip_module --with-stream_geoip_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-compat --with-file-aio --with-http_v2_module --with-openssl=/var/tmp/install/openssl-1.0.2f/ --add-module=/var/tmp/install/lua-nginx-module-0.10.7 --add-module=/var/tmp/install/nginx-vod-module-1.10`

**--with-openssl=/var/tmp/install/openssl-1.0.2f/**

**Output from openssl version**
`OpenSSL 1.0.1t  3 May 2016`

**OpenSSL 1.0.1t  3 May 2016**

This is a custom docker image where the ./configure is like this:
(... omitted irrelevant code)
`...
ENV OPENSSL_VERSION 1.0.2f
...
RUN 
wget http://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz && \
tar -xzvf openssl-$OPENSSL_VERSION.tar.gz && \
...
./configure ...
--with-openssl=/var/tmp/install/openssl-$OPENSSL_VERSION/\
...
`

**Comment by davidoster** [comment]
Is there an official Docker image from you that builds nginx with nginx-vod-module?

**Comment by erankor** [comment]
@davidoster, Docker - we don't have one.
It worked for you with --with-openssl ? I am not sure it can work with it (I think openssl headers/libs have to be in the search path)
@RecareLee, yes, it is possible, you can return multiple pssh's in the DRM info JSON

**Comment by davidoster** [comment]
@erankor No it didn't work. I will change the way I build nginx.

**Comment by erankor** [comment]
@davidoster, did you try adding the openssl folders to the search path? did it work for you?

**Comment by davidoster** [comment]
@erankor It was quite hectic at work this week and I didn't have a chance to research it.
I wanted to ask you though, how do you build nginx? What are the parameters you use on ./configure?

**Comment by erankor** [comment]
I'm using a fairly simple configuration - 
```
./auto/configure --add-module=/opt/nginx-vod-module/ --add-module=/opt/nginx-secure-token-module/ --add-module=/opt/nginx_requestid/ --add-module=/usr/local/src/nginx_mod_akamai_g2o/ --add-module=/usr/local/src/headers-more-nginx-module/ --with-http_stub_status_module --with-file-aio --with-threads --with-cc-opt="-O3" --conf-path=/opt/nginx-vod-module-saas/conf/nginx.conf
```

**Comment by jessp01** [comment]
For the kaltura-nginx deb package, we use:
https://github.com/kaltura/platform-install-packages/blob/Lynx-12.9.0/deb/kaltura-nginx/debian/rules#L60

Similar for the RPM:
https://github.com/kaltura/platform-install-packages/blob/Lynx-12.9.0/RPM/SPECS/kaltura-nginx.spec#L120

Also see the script used for Travis CI:
https://github.com/kaltura/nginx-vod-module/blob/master/travis_build.sh#L25

Note that not all configuration options are needed in order for the VOD module to work. The basic configure command @erankor provided is all that's mandatory.

**Comment by davidoster** [comment]
I am still trying to figure the right way to have openssl being compiled against nginx sources without errors.
The NPN & ALPN versions are the ones that causing the problems.
If someone has managed to compile nginx with an openssl version 1.0.2 or above, let drop a line how he did it.

**Comment by erankor** [comment]
are you getting an error or it doesn't recognize openssl?
I've just tested on some machine that has 1.0.2  - 
```
grep 'define OPENSSL_VERSION_TEXT' /usr/include/openssl/opensslv.h
#  define OPENSSL_VERSION_TEXT    "OpenSSL 1.0.2h-fips  3 May 2016"
#  define OPENSSL_VERSION_TEXT    "OpenSSL 1.0.2h  3 May 2016"
```
configure identifies it successfully - 
```
adding module in /opt/nginx-vod-module
checking for OpenSSL EVP library ... found
```
and it builds without any errors.

**Comment by davidoster** [comment]
I manage to have it built, no worries at all. Check post #516
The problem is that when I put vod_hls_encryprion_method in nginx.conf the nginx -t returns unknown directive.

**Comment by davidoster** [comment]
I meant vod_hls_encryption_method

**Comment by erankor** [comment]
@davidoster, did you configure your environment to have openssl in the search path (e.g. by setting C_INCLUDE_PATH / LIBRARY_PATH)? does nginx itself find openssl if you don't pass the `--with-openssl` argument?
As I previously wrote, the with-openssl argument is not supported by nginx-vod-module, openssl has to be in the header/library search path, otherwise it will compile without encryption support.

**Comment by davidoster** [comment]
I didn't realize that the --with-openssl argument is not supported!!
To be honest you never mentioned it as such and neither the documentation states that anywhere, in order for us to know how to compile nginx when we need to include encryption.
Thanks for clarifying this.

**Comment by erankor** [comment]
I think I did... "It worked for you with --with-openssl ? I am not sure it can work with it (I think openssl headers/libs have to be in the search path)"

**Comment by davidoster** [comment]
I did a global installation of openssl before I compiled nginx and the encryption method works really well.
Thank you!
