### ISSUE TITLE
Missed dependencies

### ISSUE THREAD

**Issue by myuriy** [kaltura/nginx-vod-module#523]
kaltura-nginx[28673]: Starting nginx: /opt/kaltura/nginx/sbin/nginx: error while loading shared libraries: libfdk-aac.so.0: cannot open shared object file: No such file
kaltura-nginx.service: control process exited, code=exited status=127
Failed to start LSB: starts the nginx web server.

Fixed via 
$> apt-get install libfdk-aac

**Comment by jessp01** [comment]
Hi @myuriy,

We do not compile the ffmpeg used with kaltura-nginx with fdk support so I'm a bit confused as to why the nginx binary in your case ends up depending on libfdk-aac.so.0.

On my ENV:
```
# dpkg -l kaltura-nginx 
ii  kaltura-nginx               1.10.2-3           amd64              Nginx web/proxy server - for Kaltura
# ldd /opt/kaltura/nginx/sbin/nginx |grep fdk
returns nothing, that is, there is no dynamic dep on libfdk-aac.so.0
also, just to be on the safe side, I also made sure I don't have the libfdk-aac package installed to eliminate the case something in the code calls dlopen():
# dpkg -l libfdk-aac.so.0
dpkg-query: no packages found matching libfdk-aac.so.0
```
Can you please provide the output for the following on your ENV?
```
# dpkg -l kaltura-nginx
# ldd /opt/kaltura/nginx/sbin/nginx
# md5sum /opt/kaltura/nginx/sbin/nginx
# cat /etc/issue
```

Thanks,

**Comment by jessp01** [comment]
@myuriy - ping
?

**Comment by jessp01** [comment]
Closing due to lack of response. Please reopen with the relevant info if still relevant.
