### ISSUE TITLE
try_files

### ISSUE THREAD

**Issue by Vladislavik** [kaltura/nginx-vod-module#524]
Hi, when i have several storages on server, such  /storage1 /storage2 /storage3
i try load file with try_files:
```
root /;
try_files  /storage1$uri /storage2$uri /storage3$uri =404;
```
but kaltura nginx return 404 every time, when i reqest "/video.mp4/index.m4u8"

**Comment by erankor** [comment]
see here - https://github.com/kaltura/nginx-vod-module/issues/143

**Comment by Vladislavik** [comment]
ok but if i use proxy for request? Every chuck will try -e file? It is big stress for disk i think. If use redorect, i cand use proxy, becourse storage give me 302 redirect to storage with file.

**Comment by erankor** [comment]
Not sure what you mean, but don't think there will be any difference in IO between if -e and try_files, maybe try_files will be slightly more efficient in terms of CPU, but that's most likely negligible.
If you have 2-3 disks, if -e will probably be ok, but if you have more, IMHO a far better solution will be to store the paths of the files in some database, and use nginx-vod-module in mapped mode. This way, every request will look for the file in the right place from the start, without having to search multiple volumes.
