### ISSUE TITLE
23 ngx_http_vod_identify_format: failed to identify the file format while reading media header, client: 127.0.0.1, server: localhost, request: "GET /content/vid_P5.mp4/index.m3u8 HTTP/1.1", host: "localhost:8014"

### ISSUE THREAD

**Issue by mishtika** [kaltura/nginx-vod-module#525]
location /content {
            root /tmp/tv/ ;
            vod hls;
            vod_mode local;
            #vod_moov_cache moov_cache 512m;
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;

            gzip on;
            gzip_types application/vnd.apple.mpegur$;
        }

i hit this url http://localhost:8012/content/vid_P,5,6,.mp4.urlset/master.m3u8

but it give me the following error 
2017/02/12 17:04:16 [error] 5174#5174: *23 ngx_http_vod_identify_format: failed to identify the file format while reading media header, client: 127.0.0.1, server: localhost, request: "GET /content/vid_P5.mp4/index.m3u8 HTTP/1.1", host: "localhost:8014"

i do not understant why

**Comment by erankor** [comment]
This is usually an indication that the file is corrupt, are you able to play this mp4 file directly (in a browser/vlc etc.)? If so, please send a link to it

**Comment by mishtika** [comment]
yes it is playing in vlc player.. i have stored the file locally in /tmp/tv/contentvid_P5.mp4
Type : MPEG-4 video (video/mp4)

**Comment by erankor** [comment]
url ?

**Comment by mishtika** [comment]
http://localhost:8080/content/vid_P7.mp4

**Comment by erankor** [comment]
I meant a url that I can use to pull the file in order to check it...

**Comment by mishtika** [comment]
i have saved it locally...so how do i send u the url of the video ?

http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4

this is the video i downloaded when i try repackaging this video. it works perfectly fine.

but if i run the following command and then try to repackage it gives error 

cd ~/bin && ./ffmpeg -i ~/Desktop/movies/ETV.mp4 -threads 2 -c:a aac -strict -2 -b:a 32k  -c:v libx264 -b:v 32K -f flv /tmp/tv/content/vid_P6.mp4 -c:a aac -strict -2 -b:a 64k  -c:v libx264 -b:v 128K -f flv /tmp/tv/content/vid_P7.mp4 -c:a aac -strict -2 -b:a 16k  -c:v libx264 -b:v 16K -f flv /tmp/tv/content/vid_P5.mp4

**Comment by erankor** [comment]
`-f flv` in ffmpeg means - force output format to flv, so while you used mp4 as the extension, ffmpeg created an flv. you just need to remove this parameter and ffmpeg will automatically output mp4, according to the file extension (make sure to remove it from all 3 places)

**Comment by mishtika** [comment]
thank you that worked.. :)
But if i wish to keep -f flv then what changes should be done in this url  : http://localhost:8012/content/vid_P,5,6,.mp4.urlset/master.m3u8

**Comment by erankor** [comment]
flv container is not supported

**Comment by mishtika** [comment]
ohk thank you very much
