### ISSUE TITLE
Error with location

### ISSUE THREAD

**Issue by nvchungdl** [kaltura/nginx-vod-module#526]
Hello,

My mp4 file in /home/mp4/
I got error 404 not found when try to set location to /hls/, but it work fine if location is "/"

Work fine if config below and link http://myserver/Test.mp4/index.m3u8

`location / {
        root /home/mp4/;
        vod hls;
        vod_mode local;
        
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
}`

404 error if config location to /hls/ and link http://myserver/hls/Test.mp4/index.m3u8

`location /hls/ {
        root /home/mp4/;
        vod hls;
        vod_mode local;
        
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
}`

`2017/02/13 10:34:49 [error] 17757#17757: *312 ngx_file_reader_update_state_file_info: open() "/home/mp4/hls/Test.mp4" failed (2: No such file or directory), client: x.x.x.x, server: , request: "GET /hls/Test.mp4/index.m3u8 HTTP/1.1`

**Comment by KillerDiller** [comment]
You need to use `alias` inside the `location`, not `root`.

    location /hls/ {
      alias /home/mp4/;

See https://nginx.org/en/docs/http/ngx_http_core_module.html#alias.

**Comment by nvchungdl** [comment]
Thank you, it worked

How about with remote config ? I got same problem when config remote. Do i need change `vod_upstream_location /remote;`

to something else ?

**Comment by nvchungdl** [comment]
It's ok now, change location ^~ /remote/ to location ^~ /remote/hls/
