### ISSUE TITLE
EXT-X-I-FRAME-STREAM-INF missing

### ISSUE THREAD

**Issue by ddunkin** [kaltura/nginx-vod-module#527]
I see where the iframes playlist is generated, but I don't see where it is included in the master playlist with a `EXT-X-I-FRAME-STREAM-INF` tag.

**Comment by erankor** [comment]
This is currently not supported, the module does not include this tag in the master playlist.

**Comment by ddunkin** [comment]
Is there a reason not to include these? The iframes playlists aren't really useful if they aren't referenced from the master playlist.

**Comment by erankor** [comment]
There is no reason, it's just a matter of prioritization, if anyone here is interested, you are welcome to submit a pull for this feature

**Comment by erankor** [comment]
@ddunkin, had some time to add this feature... you can check out this pull https://github.com/kaltura/nginx-vod-module/pull/571.
Didn't try it on Apple TV yet

**Comment by erankor** [comment]
Verified on Apple TV
