### ISSUE TITLE
Setting up a nginx location (on the same server) in front of nginx-vod-module with proxy_pass and proxy_cache

### ISSUE THREAD

**Issue by nvchungdl** [kaltura/nginx-vod-module#528]
Hello,

I want to cache video segments to disk. 
When i try http://mydomain/proxy/Test.mp4/index.m3u8 it work fine, but segments links in m3u8 file still old link /hls/ like http://mydomain/hls/Test.mp4/seg-1-v1-a1.ts. How to change link in m3u8 file ?

My nginx config

`    location /proxy/ {

        proxy_cache my_zone;
        proxy_pass http://127.0.0.1/hls/;
        proxy_set_header Host $host;
    }
    
    location /hls {
        alias /home/mp4/;
        vod hls;
        vod_mode local;

        vod_bootstrap_segment_durations 3500;
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
    }`

**Comment by erankor** [comment]
you can either use `vod_base_url` to control the returned url (if the value ends with a slash it's assumed to include the url path) or use relative urls (vod_hls_absolute_index_urls off)

**Comment by nvchungdl** [comment]
Thank you
