### ISSUE TITLE
How to make it work with basic auth?

### ISSUE THREAD

**Issue by tapir** [kaltura/nginx-vod-module#529]
Here is my virtual host config
```
server {
        # Force SSL
        listen 80;
        server_name fs.myserver.com;
        return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl http2;
        server_name fs.myserver.com;

        root /var/www/fs;

        # SSL keys
        ssl_certificate /etc/letsencrypt/live/fs.myserver.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/fs.myserver.com/privkey.pem;

        location / {
                autoindex on;
                auth_basic "Restricted";
                auth_basic_user_file /var/www/fs/.htpasswd;
                vod_mode local;
                vod hls;
                vod_metadata_cache metadata_cache 512m;
                vod_response_cache response_cache 128m;
                add_header Access-Control-Allow-Headers '*';
                add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                add_header Access-Control-Allow-Origin '*';
                expires 100d;
        }
}

```

If I comment out auth_basic VLC can start the stream `https://fs.myserver.com/bbb.mp4/index.m3u8` without problems but when I enable basic auth and try `https://user:pass@fs.myserver.com/bbb.mp4/index.m3u8` nothing happens. It doesn't give an error. It just doesn't start.
 
Any ideas?

Thanks

**Comment by tapir** [comment]
Turns out this is VLC problem. Mx Player on android plays without a problem

**Comment by tapir** [comment]
On further research with VLC and MPV on the desktop I've noticed that some of the players can't play the video because segment URLs don't have the auth user and pass attached. So the playlist is fetched correctly but every *.ts file are unauthorized.

The only player that seems to work is MX Player for Android.

Is there something we can do on nginx side to circumvent this?

**Comment by erankor** [comment]
You may be able to configure vod_base_url so that it will have the user/password on it, e.g. `vod_base_url https://$remote_user:password@yourdomain`, not sure if there's a way to get the password from nginx though.
But personally I think this is not a good solution, IMHO tokenization is a much better solution for securing the stream. This can be done using both https://github.com/kaltura/nginx-secure-token-module for propagating the tokens, and https://github.com/kaltura/nginx-akamai-token-validate-module for validating them. It's probably also possible to set it up using nginx's secure link module.

**Comment by tapir** [comment]
I've found a module that gives $remote_passwd and now it works on 4 out of 5 players I've tried. VLC for android still gives problems but it's surely its own fault.

What kind of advantage does token have over basic auth? Considering the use case here is personal and not for some video service. Is there a performance penalty to use basic auth on every segment?

**Comment by erankor** [comment]
I don't expect any significant difference in performance, advantages for tokens as I see it - 
1. It will work on all devices/players - the request is a simple URL - you are not relying on the device supporting the user/password on the URL (which afaik has been deprecated, see section 3.2.1 in https://tools.ietf.org/html/rfc3986)
2. The token can be set with an expiration
3. The token can only be used to play the specific video for which it was created
