### ISSUE TITLE
Is it possible to feed the client with correct file name

### ISSUE THREAD

**Issue by tapir** [kaltura/nginx-vod-module#531]
When I open the stream `https://fs.myserver.com/bbb.mp4/index.m3u8` with VLC, the filename is shown as `index.m3u8`. Is it possible to set it to the actual file name which is `bbb.mp4`?

**Comment by erankor** [comment]
I don't know how VLC chooses the filename it displays, if it simply takes the filename part of the URL, then the answer is no. If there are other options to pass the filename (some HTTP header, tag in the m3u8 etc.) it may be possible. 
But, I don't really see why it matters, HLS/DASH etc. are mainly for web/mobile players, if you are targeting VLC, you can just use progressive download and you'll have the filename you want.

**Comment by tapir** [comment]
So I'm assuming I can't dynamically override the "index.m3u8" name from server side? With a directive or something?

**Comment by erankor** [comment]
You can override it with vod_hls_index_file_name_prefix, but you can't make it dynamic with this directive (it will be some other fixed string). If you really want to do this, you can use nginx's rewrite directive, to rewrite all requests for `.*\.m3u8` to index.m3u8
