### ISSUE TITLE
passing secure in url

### ISSUE THREAD

**Issue by erald** [kaltura/nginx-vod-module#532]
Am trying to understand how to pass arguments to the file. Just want to protect the link with the secure_link.

In my understanding things should be able to work here my config

```
upstream vod_origin {
  server cdn.example.com;
}

server {
  listen       8080;
  server_name  hls.example.com;
  
  access_log /var/log/nginx/hls.access.log;
  error_log  /var/log/nginx/hls.error.log info;
		# vod status page
		location /vod_status {
			vod_status;
			access_log off;
		}
		location ^~ /vod_origin/ {
            internal;
            proxy_pass http://vod_origin/;
            proxy_set_header Host $http_host;
    }
		#VOD Module Configurations
    location /videos {
            vod hls;
			#vod_secret_key "SomeSecret$vod_filepath";
			#vod_hls_encryption_method aes-128;
						
			vod_mode remote;
        		vod_upstream_location /vod_origin;
        		vod_upstream_extra_args "st=$arg_st&e=$arg_e";
        		

			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			add_header Access-Control-Allow-Headers "*";
			add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
			add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
			add_header Access-Control-Allow-Origin "*";
			expires 100d;
            root /home;

            #gzip on;
            #gzip_types application/vnd.apple.mpegur$
        }        
}

```
I then send the url http://hls.example.com:8080/videos/jas/videos_mp4/test.mp4/index.m3u8?st=iKD-RGJNrylaI2gxLL4PpQ&amp;e=1487275236

In the logs I see the mp4 file is being fetched but the third part does not have the arguments anymore and thus gives an 403 error.
`"GET /videos/jas/videos_mp4/test.mp4?st=iKD-RGJNrylaI2gxLL4PpQ&e=1487275236 HTTP/1.0" 206 4096 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
"GET /videos/jas/videos_mp4/test.mp4?st=iKD-RGJNrylaI2gxLL4PpQ&e=1487275236 HTTP/1.0" 206 509202 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
"GET /videos/jas/videos_mp4/test.mp4?st=&e= HTTP/1.0" 402 183 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
`
The error in the xls log

[error] 2848#0: *15743 ngx_child_request_wev_handler: upstream returned a bad status 402 while sending to client, client:

Which is understandable when the arguments are lost.

What am I doing wrong here? Or is this a bug in the system?

**Comment by erankor** [comment]
You pasted only the log of the upstream server, I assume that if you'll check the logs of the server running nginx-vod-module you will see that you have these parameters on the request for the m3u8, but not on the requests for the ts segments. 
To have the token parameters propagate to the ts urls, you can use nginx-secure-token-module. Adding these 2 directives should probably do the trick:
```
secure_token_types application/vnd.apple.mpegurl application/dash+xml text/xml;
secure_token $args;
```

**Comment by erald** [comment]
ok that is easy and works perfectly thanks
