### ISSUE TITLE
Problem mapped mode with remote files server

### ISSUE THREAD

**Issue by janiel14** [kaltura/nginx-vod-module#534]
@erankor Good morning, I'm having trouble configuring nginx-vod-module to work with mapped vod-mode using remote files. I have a unique server for streaming using nginx with vod-module and another remote server with nginx providing the files in http. But when I go to access the json file it gives the 404 error, however I can access the json file using CURL in the URL of the file it works but nginx does not access it.

NGINX-VOD-MODULE
`
upstream stream {
        server x.x.x.x:8080;
}
server {
        listen 80;
        server_name my.myhost.com;

        vod_mode mapped;
        vod_remote_upstream_location /vodstream;
        vod_upstream_extra_args "pathOnly=1";
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;

        # vod caches
       # vod_metadata_cache metadata_cache 512m;
       # vod_response_cache response_cache 128m;
       # vod_mapping_cache mapping_cache 5m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        # file handle caching / aio
       # open_file_cache          max=1000 inactive=5m;
       # open_file_cache_valid    2m;
       # open_file_cache_min_uses 1;
       # open_file_cache_errors   on;
        aio on;

        location ^~ /vodstream/ {
            internal;
            proxy_pass http://stream/;
        }

	location /vodhls/ {
            vod hls;
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
    }
`
Arquivo JSON
`
{
    "sequences": [
        {
            "clips": [
                {
                    "type": "source",
                    "path": "http:\/\/x.x.x.x:8080\/52\/galeria\/7e4e6b86de0b672f3c6fdd2089584ca60b59ea95_10485.mp4"
                }
            ]
	},
	{
            "clips": [
                {
                    "type": "source",
                    "path": "http:\/\/x.x.x.x:8080\/52\/galeria\/7e4e6b86de0b672f3c6fdd2089584ca60b59ea95_10486.mp4"
                }
            ]
	},
	{
            "clips": [
                {
                    "type": "source",
                    "path": "http:\/\/x.x.x.x:8080\/52\/galeria\/7e4e6b86de0b672f3c6fdd2089584ca60b59ea95_10487.mp4"
                }
            ]
	}
    ]
}
`

**Comment by erankor** [comment]
As I understand, you want to pull the json from a remote server, so you need to set vod_upstream_location as well, otherwise nginx-vod-module will try to load the json from a local file. Other than that, the urls in the json should be relative to what you put in vod_remote_upstream_location, they should not be absolute urls.
Either way, I suggest you check the error log, and compile with debug messages if needed.

**Comment by janiel14** [comment]
@erankor  Wow, really? Kkkkk was just using vod_upstream_location along with vod_remote_upstream_location. He was trying to use one or the other, never together. Many thanks worked out perfectly. If you have anything that can help, just tell me. Please leave your contact at janielbelmont@gmail.com again thanks.
