### ISSUE TITLE
m3u8 file is empty when I use LUA

### ISSUE THREAD

**Issue by massoudAfrashteh** [kaltura/nginx-vod-module#539]
I should call a HTTP address inside that block I'm serving HLS files. But when I put a LUA command M3U8 file is gonig to be empty.

```
        location /vod {
            
            alias /var/www/record/mp4/;
            vod hls;

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;

            content_by_lua 'os.execute("curl http://localhost:8090/notify")';
        }
```

**Comment by erankor** [comment]
You have 2 content handlers on the same location (vod hls and content_by_lua), it doesn't make sense. 
You probably need to use some other *_by_lua directive, like access_by_lua. 
Btw, you can make http requests with lua directly, without executing curl (https://github.com/pintsized/lua-resty-http)

**Comment by massoudAfrashteh** [comment]
Thanks I just need to do a HTTP GET (call a HTTP address) inside Nginx... I will find other ways to do that.
