### ISSUE TITLE
strange segments duration

### ISSUE THREAD

**Issue by dcharbonnier** [kaltura/nginx-vod-module#540]
the manifest give that 
```
  <SegmentTimeline>
                <S d="3992"/>
                <S d="2013"/>
                <S d="0"/>
                <S d="5988"/>
                <S d="4009"/>
                <S d="6005"/>
                <S d="8001"/>
                <S d="5988"/>
                <S d="4009"/>
                <S d="8001"/>
                <S d="5988"/>
                <S d="4009"/>
                <S d="6487"/>
                <S d="6005"/>
                <S d="6005" r="1"/>
                <S d="5988"/>
                <S d="6005" r="1"/>
```

but the video contain enough I frames :
```
➜  ~ ~/Downloads/bin/ffprobe -show_frames Downloads/b60758b4-d534-4ce0-8570-ae7bf423ff6e 2>&1|grep pict_type|nl|grep "=I"
     1	pict_type=I
   121	pict_type=I
   241	pict_type=I
   361	pict_type=I
   481	pict_type=I
   601	pict_type=I
   721	pict_type=I
   841	pict_type=I
^C
➜  ~ ~/Downloads/bin/ffprobe -v error -show_format -show_streams  Downloads/b60758b4-d534-4ce0-8570-ae7bf423ff6e |grep r_frame_rate           
r_frame_rate=60/1
```
and I'm using those settings :
```
        vod_bootstrap_segment_durations             2000;
        vod_bootstrap_segment_durations             2000;
        vod_bootstrap_segment_durations             2000;
        vod_bootstrap_segment_durations             4000;
        vod_segment_duration                        6000;
        vod_manifest_segment_durations_mode         accurate;
        vod_align_segments_to_key_frames            on;
        vod_segment_count_policy                    last_rounded;
```

Is it something I don't get or a bug ?

**Comment by dcharbonnier** [comment]
considering an implementation like https://shaka-player-demo.appspot.com/docs/api/lib_dash_mpd_utils.js.html#line201 d="0" is a huge problem

**Comment by dcharbonnier** [comment]
```
best_effort_timestamp_time=0.000000
pict_type=I
--
best_effort_timestamp_time=1.996044
pict_type=I
--
best_effort_timestamp_time=3.992078
pict_type=I
--
best_effort_timestamp_time=6.004756
pict_type=I
--
best_effort_timestamp_time=8.000800
pict_type=I
--
best_effort_timestamp_time=9.996844
pict_type=I
--
best_effort_timestamp_time=11.992878
pict_type=I
--
best_effort_timestamp_time=14.005556
pict_type=I
--
best_effort_timestamp_time=16.001600
pict_type=I
--
best_effort_timestamp_time=17.997633
pict_type=I
--
best_effort_timestamp_time=19.993678
pict_type=I
--
best_effort_timestamp_time=22.006356
pict_type=I
--
best_effort_timestamp_time=24.002400
pict_type=I
--
best_effort_timestamp_time=25.998433
pict_type=I
--
best_effort_timestamp_time=27.994478
pict_type=I
--
best_effort_timestamp_time=30.007156
pict_type=I
--
best_effort_timestamp_time=32.003189
pict_type=I
--
best_effort_timestamp_time=33.999233
pict_type=I
--
best_effort_timestamp_time=35.995278
pict_type=I
--
best_effort_timestamp_time=38.007956
pict_type=I
--
best_effort_timestamp_time=40.003989
pict_type=I
--
best_effort_timestamp_time=42.000033
pict_type=I
--
best_effort_timestamp_time=43.996078
pict_type=I
--
best_effort_timestamp_time=45.992111
pict_type=I
--
best_effort_timestamp_time=48.004789
pict_type=I
--
best_effort_timestamp_time=50.000833
pict_type=I
--
best_effort_timestamp_time=51.996878
pict_type=I
--
best_effort_timestamp_time=53.992911
pict_type=I
--
best_effort_timestamp_time=56.005589
pict_type=I
--
best_effort_timestamp_time=58.001633
pict_type=I
--
best_effort_timestamp_time=59.997667
pict_type=I
--
best_effort_timestamp_time=60.496678
pict_type=I
--
best_effort_timestamp_time=62.492722
pict_type=I
--
best_effort_timestamp_time=64.488756
pict_type=I
--
best_effort_timestamp_time=66.501433
pict_type=I
--
best_effort_timestamp_time=68.497478
pict_type=I
```

**Comment by erankor** [comment]
When you use `vod_align_segments_to_key_frames`, the segment boundary is pushed to the first key frame that follows. So, since the first segment boundary according to your conf is 2000, it will be moved to 3992, not to 1996.
It seems your file does not have perfectly positioned keyframes, you have a GOP of roughly 2 sec, but in some cases it deviates significantly, e.g. 66.5 instead of 66. 
If you are using ffmpeg to create these files, I suggest you use `-force_key_frames "expr:gte(t,n_forced*2)"` from my experience this creates perfect key frames. Even in cases where the frame rate is not integer (e.g. 29.97), it will create the key frame on the first frame after even second.

**Comment by dcharbonnier** [comment]
Yes ok, I can't have perfect keyframes in my process but what about the 0 ?

**Comment by erankor** [comment]
The module can't avoid the 0 in this case, since in SegmentTimeline mode the segments are requested by their index. A hack that may work for you, if all your videos are similar to this one, is simply to make the first bootstrap segment a bit smaller (e.g. 1900) As long as the key frame is not more than 100ms before its accurate position, it will work fine.

**Comment by dcharbonnier** [comment]
I tried with 1500 before seeing your answer and I got 
```
<SegmentTimeline>
                <S d="1996"/>
                <S d="1996"/>
                <S d="2013"/>
                <S d="1996"/>
                <S d="6005"/>
                <S d="8001"/>
                <S d="5988"/>
                <S d="4009"/>
                <S d="6005"/>
                <S d="7984"/>
```
that's way better than with the 2000, but no all my file are not exactly the sames. What is the consequence if the difference is more than 100ms ? The keyframes on the file are not perfect but there is one every 2s, so why do we get segments from 4 to 8 seconds ?

**Comment by erankor** [comment]
As I wrote, the key frame alignment is performed only forward - the boundary is pushed to the next keyframe, not to the nearest keyframe. If you use a fixed segment duration of 2 sec, and you have these roughly 2 sec GOPs, you are expected to get segments between 0-4 sec. 
If the difference is more than 100ms and you use 1900 as the bootstrap segment duration, then it is possible that this compensation will not be enough, and it will still miss the keyframe. e.g. if the first key frame is at 1800, the module will push the first segment to the next key frame.
I think the safest solution in your case, if you know that all videos have a GOP of roughly 2 sec, is to use a segment durations of at least 4 sec. In this case you will not get any empty segments.

**Comment by dcharbonnier** [comment]
thx
