### ISSUE TITLE
Load smil file?

### ISSUE THREAD

**Issue by troyhammonds** [kaltura/nginx-vod-module#548]
Is there something I need to enable to allow smil files to be used?

**Comment by troyhammonds** [comment]
Example request would be.

http://domain.com/application/videos/2016/07/159201_20160713_MP4.
smil/master.m3u8

**Comment by erankor** [comment]
The module does not use smil format, assuming what you want is to play a number of videos as an adaptive set, there are two ways to do it:
1. use a json file - the format is described in the readme, here is an example https://github.com/kaltura/nginx-vod-module/#adaptive-set
2. encode the different URLs of the various MP4 files in a single multi-url - https://github.com/kaltura/nginx-vod-module/#multi-url-structure

**Comment by erankor** [comment]
@troyhammonds, can we close this issue?

**Comment by sdahdaah** [comment]
it will be great if it can support .smil as plenty of systems have support for .smil and some of the providers are already using the .smil

**Comment by erankor** [comment]
@sdahdaah, there are no plans to add support for smil, but you should be able to translate it to the JSON format required by this module quite easily, but proxying the request through some PHP script (or similar)
