### ISSUE TITLE
Support for accessing content-length and content-range in CORS requests

### ISSUE THREAD

**Issue by whadar** [kaltura/nginx-vod-module#55]
In order to read the content-length and content-range response header we need the server to respond accordingly. At the moment we see the wildcard response header Access-Control-Expose-Headers: * which is not effective (in Chrome and probably in other browsers).

We would like to suggest adding few standard headers to the response: 
Access-Control-Expose-Headers: content-length, content-range, etag

**Comment by erankor** [comment]
The change was deployed, we now return these headers:
Access-Control-Expose-Headers: Server,range,Content-Length,Content-Range
