### ISSUE TITLE
Package kaltura-ffmpeg for newer ubuntu debian

### ISSUE THREAD

**Issue by tapir** [kaltura/nginx-vod-module#552]
kaltura-ffmpeg depends on libass4, libopenjpeg2 and libvpx1 which can't be found on > debian wheeze and ubuntu trusty. It would be nice at least if the packages could support latest ubuntu lts (16.04) and debian stable.

Thanks

**Comment by jessp01** [comment]
Hi @tapir,
Please see https://github.com/kaltura/nginx-vod-module/issues/494#issuecomment-268232786.

**Comment by tapir** [comment]
ah perfect! it would be nice to have it in readme.

**Comment by jessp01** [comment]
You are right:) We'll add it.
