### ISSUE TITLE
Support OpenSSL 1.1.0+ API changes

### ISSUE THREAD

**Issue by phillipseamore** [kaltura/nginx-vod-module#555]
Hi,

Wanted to test nginx compiled with OpenSSL 1.1.0 to see if CHACHA20 would improve HLS loading speeds over HTTPS but getting errors which I believe are due to API changes in OpenSSL.

The same errors appear for various header files:
`
/usr/src/nginx-vod-module/vod/mp4/mp4_aes_ctr.h:16:17: error: field ‘cipher’ has incomplete type
  EVP_CIPHER_CTX cipher;
`
Similar errors for "nginx-secure-token-module" and "nginx-akamai-token-validate-module" also.

**Comment by erankor** [comment]
Thanks for reporting! please try this pull - https://github.com/kaltura/nginx-vod-module/pull/556
I tested it only on 1.0, but according to the docs and the error you pasted, it should fix 1.1.
I'll handle the other modules afterwards

**Comment by erankor** [comment]
@phillipseamore, did you try it out?

**Comment by erankor** [comment]
@phillipseamore ?

**Comment by erankor** [comment]
tested by @jessp01
