### ISSUE TITLE
webm support?

### ISSUE THREAD

**Issue by troyhammonds** [kaltura/nginx-vod-module#559]
Hi,

Any chance of webm to hls,hds,and dash support?

-Troy Hammonds

**Comment by erankor** [comment]
See this thread about mkv support https://github.com/kaltura/nginx-vod-module/issues/549.
Webm is essentially mkv, with some additional restrictions, most notably - webm only supports VP8/VP9 video codecs and Vorbis/Opus audio codecs. These codecs are not supported in hls/hds, they are only supported in dash.
So, if you have webm, you can use this module to package it to dash (after enabling mkv support), but it is technically impossible to package it to hls/hds, it has to be retranscoded to h264/aac/mp3 first.

**Comment by erankor** [comment]
@troyhammonds, can we close this issue?

**Comment by troyhammonds** [comment]
Yes thank you.
