### ISSUE TITLE
Not working on some browser

### ISSUE THREAD

**Issue by ktrev** [kaltura/nginx-vod-module#561]
Hi,

We have successfully installed the module. We are having the following problems

1. In safari its only playing the audio. Video is not coming.

2. In firefox (on a Linux system)  it is showing **"The media could not be loaded, either because the server or  network failed or because the format is not supported"**

Can someone please guide us to solve this? Thanks

**Comment by erankor** [comment]
Please provide sample URLs

**Comment by ktrev** [comment]
https://videostreaming.mookit.co/hls/

**Comment by erankor** [comment]
I see this video is interlaced:
`
mediainfo \temp\test.ts | grep Scan
Scan type                                : Interlaced
Scan order                               : Top Field First
`
I don't think Safari supports interlaced, I suggest you try transcoding it to progressive first.
Regarding Firefox, it's not expected to work, it does not support HLS natively, you'll have to use a player like hls.js if you want to do that.

**Comment by ktrev** [comment]
Hi,
We have hls.js integrated with videojs-contrib-hls. We are using that player in our production site. Still its not working in firefox (on linux os only)[](url)

**Comment by jessp01** [comment]
Hi @ktrev,

https://videostreaming.mookit.co/hls/ plays correctly for me from my Ubuntu 14.04.2
\# dpkg -l
firefox                     52.0+build2-0ubunt

which version of FF are you using?

**Comment by ktrev** [comment]
My FF version is 52.0. When I visit youtube.com/html5 it says FF doesn't support H264 and MSE & H 264. Do you have any additional plugins installed?

**Comment by erankor** [comment]
Googling this up, I saw this - http://www.linuxveda.com/2015/04/02/enable-mse-native-html5-support-firefox-linux/
Did you try it out?

**Comment by jessp01** [comment]
ping @ktrev. Did you look at http://www.linuxveda.com/2015/04/02/enable-mse-native-html5-support-firefox-linux/? since the issue does not seem to be related to the VOD module, I think we should close this one. Thanks,

**Comment by ktrev** [comment]
Hi,

The shared link is not opening. It is giving 404 error.

**Comment by ktrev** [comment]
Hi,
The shared link is not opening. It is giving 404 error.

**Comment by erankor** [comment]
Right, looks like they removed it...
Anyway, googling for 'enable mse html5 firefox linux' returns several other pages that explain it, e.g.:
http://www.ghacks.net/2014/07/25/enable-mse-h2-64-support-youtube-firefox-right-now/
https://www.youtube.com/watch?v=OUfCsSch8Zk

**Comment by ktrev** [comment]
Hi,
Thanks. We will try this. It does not seem to be an issue with this module. We can close this issue. Thank you so much for the excellent support.
