### ISSUE TITLE
Add GET param to manifest response 

### ISSUE THREAD

**Issue by ahotnik** [kaltura/nginx-vod-module#562]
Hello!
How can i add some GET param to my URL that should be returned in manifest responses.
Example
was:
http://localhost/content/def.mp4/index-v1-a1.m3u8
become:
http://localhost/content/def.mp4/index-v1-a1.m3u8?m=blablabla
Thank you!

**Comment by erankor** [comment]
You can use https://github.com/kaltura/nginx-secure-token-module for that. If you add to your conf `secure_token m=blablabla` you will get your example (the value can contain nginx variables)

**Comment by ahotnik** [comment]
Thank you! Very helpful. All ok =)
p.s. Is there any other solution? Without this module?)
because now i have 70 servers where installed nginx without _nginx-secure-token-module_ =)

**Comment by erankor** [comment]
Wow, that's a big deployment :) 
nginx-vod-module doesn't have this feature, you can probably do it also with https://github.com/openresty/replace-filter-nginx-module, if you somehow have this module installed, but it will be less convenient (this module does regular expression substitutions on response bodies).
Btw, the reason it was developed as a separate module is that it makes it possible to add such tokens to any stream, not only streams generated by nginx-vod-module.

**Comment by ahotnik** [comment]
Oh thank for your answer) 
between my and your messages i haved 15 hours, and recompile nginx with this module in my servers :)
so thanks for kaltura and secure module, have a nice day!
