### ISSUE TITLE
OpenSSL EVP library ... not found

### ISSUE THREAD

**Issue by cc-brian** [kaltura/nginx-vod-module#564]
I realize this may not be directly related, but several threads have been discussing this issue.  AFAIK nobody has documented running nginx vod module with two different versions of openssl on the same system which does use encryption mechanisms.  Ideally, we document here and possibly add to readme docs as I feel this issue is going to continue to come up.

So after getting past issue:  https://github.com/kaltura/nginx-vod-module/issues/563

(thanks for the **awesome support** there)

I’ve run into the next issue: OpenSSL EVP library ... not found (during the configure)

In the initial instance I was running this config:  (case 1)

./configure --user=nginx --group=nginx --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --with-threads --with-file-aio --with-http_ssl_module --with-pcre --with-http_v2_module --with-http_sub_module  --with-http_auth_request_module  --with-http_stub_status_module --with-openssl=$HOME/sources/openssl-1.0.2k --add-module=$HOME/sources/nginx-vod-module-master

Which resulted in a segmentation fault discussed in https://github.com/kaltura/nginx-vod-module/issues/563

So I compiled and installed the openssl (1.0.2k) source to the default location of /usr/local/ssl.  I even **exported** the following paths based on issue 563 as well.

C_INCLUDE_PATH=/usr/local/ssl/include
LIBRARY_PATH=/usr/local/ssl/lib
LD_LIBRARY_PATH=/usr/local/ssl/lib (not sure I needed this one, but did anyway)

I then ran this config: (case 2)

 ./configure --user=nginx --group=nginx --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --with-threads --with-file-aio --with-http_ssl_module --with-pcre --with-http_v2_module --with-http_sub_module  --with-http_auth_request_module  --with-http_stub_status_module --with-cc-opt="-I /usr/local/ssl/include" --with-ld-opt="-L /usr/local/ssl/lib" --add-module=$HOME/sources/nginx-vod-module-master

I initially noticed unknown directive "vod_hls_encryption_method" which caused me to realize the openssl issue.  Which resulted in OpenSSL EVP library ... not found.

I’ve gotten the module up and running in this instance without encryption and it works great!  I’ll need encryption enabled so hence my dilemma.

How do I force the OpenSSL EVP library path?

Please advise.

Thanks!

**Comment by erankor** [comment]
You can simulate the openssl detection done in configure with this:
```
# cat test.c
#include <openssl/evp.h>

int main()
{
        EVP_CIPHER_CTX cipher; EVP_CIPHER_CTX_init(&cipher);
}
# gcc test.c -o test -lcrypto
```
If this compiles successfully, configure will work as well. 
Otherwise, gcc will complain about either not find evp.h or not finding libcrypto.a.

**Comment by cc-brian** [comment]
Thanks - Yes, it works, no errors on output.

However - I'm still not sure where to go from here as it's still not found during the compile of nginx using the case 2 config above.  Nginx does see my local install of openssl, but vod module does not.    It's only found when I run case 1, but that results in seg fault.

Is there any other way to force the path somehow?  Can I mod the ngx vod config file somewhere to force it to work?

**Comment by erankor** [comment]
I don't really understand how this is possible, but you can check objs/autoconf.err. 
For example, if I move the openssl headers on my server, after `configure` this file contains this:
```
...
----------------------------------------
checking for OpenSSL EVP library

objs/autotest.c:4:25: fatal error: openssl/evp.h: No such file or directory
compilation terminated.
----------

#include <sys/types.h>
#include <unistd.h>
#include <openssl/evp.h>

int main() {
    EVP_CIPHER_CTX cipher; EVP_CIPHER_CTX_init(&cipher);;
    return 0;
}

----------
cc -O0 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o objs/autotest objs/autotest.c -lcrypto
----------
...
```

**Comment by cc-brian** [comment]
Ah - now we're getting closer.  

So check this out:

checking for OpenSSL EVP library

/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x344): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3eb): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x464): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x50b): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x579): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x5db): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x613): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x69f): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x701): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x752): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

Does this mean anything to you?

**Comment by erankor** [comment]
Try to change this line in nginx-vod-module's config:
`ngx_feature_libs="$LIB_CRYPTO"`
To:
`ngx_feature_libs="$LIB_CRYPTO -ldl"`

Not sure why it's needed on your env, but that's how it seems from these errors

**Comment by cc-brian** [comment]
**YOU'RE  A ROCK STAR!!  

THAT WORKS!!**

I'm on centos 7 running a LEMP stack, so nothing really special otherwise.

What exactly did we change there?

**Comment by erankor** [comment]
Great! we just added another library to the openssl detection, it seems that on your env libopenssl.a is dependent on libdl.a, so we just added that second library

**Comment by cc-brian** [comment]
Awesome!

So my next stop along this journey is incorporating your other security token modules.  Will I have to mod them in a similar fashion since they also depend on openssl?

**Comment by erankor** [comment]
The other modules do not auto-detect openssl, they assume it's there because it's mandatory. 
So, assuming nginx core already loads libdl, it should work fine.

**Comment by cc-brian** [comment]
Excellent!

I really appreciate all the support here - top notch indeed.  👍

**Comment by erankor** [comment]
Thanks, I merged this change
