### ISSUE TITLE
mp4 parse error 

### ISSUE THREAD

**Issue by RecareLee** [kaltura/nginx-vod-module#578]
Hi erankor,
   In map mode, when i try dash mpd, and nginx-vod-module parsed mp4 file throwed error: 
f[mp4_parser_process_moov_atom_callback] [error] 40831#40831: *147420 mp4_parser_process_moov_atom_callback: no extra data was parsed for track while reading media header

what is the error actually means? is the mp4 file were not fit for this module?

**Comment by erankor** [comment]
It means the codec private data was not found, some codecs (e.g. h264) require some extra data (in addition to the video frames) in order to decode successfully.
Are you able to play this file directly in Chrome/VLC?
If so, please provide a URL.

**Comment by RecareLee** [comment]
Sorry, erankor i got no internet web server now,  i can play it directly in VLC player. if possible,  i can send the mp4 file to your by mail or send it to your cloud disk .

**Comment by erankor** [comment]
Can you upload it to dropbox or something like that?

**Comment by RecareLee** [comment]
well, i can not use dropbox cause sercurity reason, I just annotated the code where make sure have got extra data. finally it generated dash mpd and servered dash fragment. i don't know it's there any issue or risk for dash player to play it. I just found VLC 3.0 play this dash media, the sound track is not continuos and sometimes it will freeze.

**Comment by erankor** [comment]
I don't know if the missing extra data error is on the video stream or audio stream, but if it's the video then it is possible that the stream has the extra data "in-band" (SPS/PPS nalu before the IDR nalu). But anyway, I prefer to leave this restriction in place, it is possible that in some protocols (e.g. MSS) it won't play without it.

**Comment by RecareLee** [comment]
Hi, erankor
   When i configured  segment_duration  2s in vod dash location, for live service, i found the fmp4's duration is not accurately 2s . For example , (the second's fmp4 base decode time -  the first fmp4's base decode time) / timescale is nor equal 2.  
   mp4dump  fragment-3069398-f2-v1-x2.mp4 
[styp] size=8+20
[sidx] size=12+40, version=1
  reference_ID = 1
  timescale = 90000
  earliest_presentation_time = 552491514000
  first_offset = 0
[moof] size=8+2662
  [mfhd] size=12+4
    sequence number = 3069397
  [traf] size=8+2638
    [tfhd] size=12+4, flags=20000
      track ID = 1
    [tfdt] size=12+8, version=1
      base media decode time = 552491514000
    [trun] size=12+888, flags=f01
      sample count = 55
      data offset = 2678
    [saiz] size=12+60
      default sample info size = 0
      sample count = 55
    [saio] size=12+8
      entry count = 1
    [senc] size=12+1598, flags=2
      sample info count = 55


 mp4dump  fragment-3069399-f2-v1-x2.mp4 
[styp] size=8+20
[sidx] size=12+40, version=1
  reference_ID = 1
  timescale = 90000
  earliest_presentation_time = 552491722800
  first_offset = 0
[moof] size=8+2437
  [mfhd] size=12+4
    sequence number = 3069398
  [traf] size=8+2413
    [tfhd] size=12+4, flags=20000
      track ID = 1
    [tfdt] size=12+8, version=1
      base media decode time = 552491722800
    [trun] size=12+808, flags=f01
      sample count = 50
      data offset = 2453
    [saiz] size=12+55
      default sample info size = 0
      sample count = 50
    [saio] size=12+8
      entry count = 1
    [senc] size=12+1458, flags=2
      sample info count = 50
[mdat] size=8+938870

＞ 552491514000/90000=6138794.6
＞ 552491722800/90000=6138796.92

the time gap is 2.32s

**Comment by erankor** [comment]
do you have vod_align_segments_to_key_frames enabled? this setting adjusts the segment duration so that it will start and end on keyframe boundary.

**Comment by RecareLee** [comment]
Yes, @erankor, i have this directives disabled. but the video fragments' base decode time are still not continous.  I wonder whether it is caused by the origin mp4 files' duration are equal with the json discribed.

for that in the mapped json, it discribed each mp4file's duration by 2000 milis, however with some of the stream slicer's inaccurately cut, the real duration is not 2000 milis. especially the audio track duration is commonly shorter than the video track in the same mp4file, i don't know whether this kind of mp4 files would lead to  some potential issues.

**Comment by erankor** [comment]
Sorry, I just noticed I missed this thread.
I'm not sure I understand the issue, but even if you don't have align to key frames enabled, the fragments may not have the configured duration exactly. For example, if the video uses a frame rate of 29.97 (NTSC) it is not possible to cut an accurate 2 sec video fragment out of it - 59 frames ~= 1.968 sec and 60 frames = 2.002

**Comment by erankor** [comment]
@RecareLee, can we close this issue?

**Comment by RecareLee** [comment]
OK ! @erankor , Thanks again for your support !
