### ISSUE TITLE
Disk I/O in mapped mode with remote files and remote JSON?

### ISSUE THREAD

**Issue by jsardas** [kaltura/nginx-vod-module#585]
Hello,

When using the mapped mode with remote files only (vod_remote_upstream_location) and pulling the JSON from a remote server (vod_upstream_location), is it correct to assume that the module does not perform any local disk I/O?  (like what happens with the regular remote mode as described in #379)

Since both the actual media files and the JSON are pulled via Nginx subrequests to selected locations, I understand the responses for both cases are kept in memory based on the NGX_HTTP_SUBREQUEST_IN_MEMORY flag, like you also described in #379.

Would it be possible for you to confirm this?

Thanks.

**Comment by erankor** [comment]
Yes, that is correct

**Comment by jsardas** [comment]
Thank you!
