### ISSUE TITLE
Fragmented MP4 for HLS

### ISSUE THREAD

**Issue by zshenker** [kaltura/nginx-vod-module#591]
Now that iOS 10 is supporting HLS with Fragmented MP4 segments, wondering if there are any plans to support HLS with Fragmented MP4 instead of TS segments?

Ideally with clear/un-encrypted content it would be great if there was an option for the DASH fMP4 segments to be re-used for HLS and only different manifests generated.

**Comment by erankor** [comment]
Currently we have no plans to support this, it's listed somewhere on the todo, but with a low priority. The reason is that most of our use of DASH is for DRM, and as you wrote, it doesn't help there (DASH uses AES-CTR and HLS uses AES-CBC)

**Comment by zshenker** [comment]
@erankor Thanks for the quick reply on this. Even without sharing of segments between HLS & DASH, using Fragmented MP4 with HLS would mean that web browsers with MSE would be able to avoid the transmuxing from TS to FMP4 stage in Javascript.

Any suggestions as to the best approach towards implementing this feature?

**Comment by erankor** [comment]
Easiest solution to set it up would be to use 2 locations, one for hls (let's say /hls) and one for dash (/dash) that "see" the same mp4 files. The dash location will prepare the init segment and fragments, and the hls location will prepare the manifest. 
You can use nginx's sub module to edit the returned m3u8 to use the dash segments - 
1. Change `/hls/` to `/dash/`
2. Change `.ts` to `.m4s`
3. Add an EXT-X-MAP tag pointing to the dash init segment
Also, configure nginx-vod-module so that the segment URL prefix will be the same for both (by default hls uses `seg` and dash uses `fragment`).
Only thing that will require a code change is to force HLS to use unmuxed segments (by default in hls the audio and video are muxed together). You can patch it by removing the `muxed` flag here:
https://github.com/kaltura/nginx-vod-module/blob/master/vod/hls/m3u8_builder.c#L770

**Comment by flavioribeiro** [comment]
Just a heads up that we could be able to play fmp4 files on HLS by creating another location with a Lua script changing manifests as described on @erankor comment above. You can see the ngix.conf [here](https://gist.github.com/flavioribeiro/f2f889973a21b9e58f071c073e0f5cc9#file-nginx-conf-L67-L88). 

We didn't change the code to mutiplex the audio on m4s video segments yet so the playback doesn't have audio: http://video-dev.github.io/hls.js/demo/?src=http://35.184.67.151/video-media/hlsfmp4/2011/10/14/14299_1_occupy10-14-11_wg_,240,360,480,720,1080,p.mp4.urlset/master.m3u8

We'll be reporting the progress on this issue.

**Comment by erankor** [comment]
I don't think you should mux the audio with the video, instead you can just make the module generate unmuxed segments for audio/video, as I wrote above. This will enable reuse of segments between dash and hls (I'm quite sure muxed audio/video won't work in dash)

**Comment by flavioribeiro** [comment]
we could make it work with a separate sound track like this:
```
۶ curl http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_,240p.mp4,360p.mp4,480p.mp4,720p.mp4,1080p.mp4,.urlset/master.m3u8
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=361000,RESOLUTION=426x240,FRAME-RATE=29.970,CODECS="avc1.4d401f,mp4a.40.2"
http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_240p.mp4/index-v1-a1.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=26384,RESOLUTION=426x240,CODECS="avc1.4d401f",URI="http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_240p.mp4/iframes-v1-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=956535,RESOLUTION=640x360,FRAME-RATE=29.970,CODECS="avc1.4d401f,mp4a.40.2"
http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_360p.mp4/index-v1-a1.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=60114,RESOLUTION=640x360,CODECS="avc1.4d401f",URI="http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_360p.mp4/iframes-v1-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1551552,RESOLUTION=854x480,FRAME-RATE=29.970,CODECS="avc1.4d401f,mp4a.40.2"
http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_480p.mp4/index-v1-a1.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=91745,RESOLUTION=854x480,CODECS="avc1.4d401f",URI="http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_480p.mp4/iframes-v1-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2538930,RESOLUTION=1280x720,FRAME-RATE=29.970,CODECS="avc1.4d401f,mp4a.40.2"
http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_720p.mp4/index-v1-a1.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=140625,RESOLUTION=1280x720,CODECS="avc1.4d401f",URI="http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_720p.mp4/iframes-v1-a1.m3u8"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3727590,RESOLUTION=1920x1080,FRAME-RATE=29.970,CODECS="avc1.4d401f,mp4a.40.2"
http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_1080p.mp4/index-v1-a1.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=194605,RESOLUTION=1920x1080,CODECS="avc1.4d401f",URI="http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_1080p.mp4/iframes-v1-a1.m3u8"

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English",DEFAULT=YES,AUTOSELECT=YES,URI="http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_240p.mp4/index-a1-x3.m3u8"
```

http://video-dev.github.io/hls.js/demo/?src=http://35.184.67.151/video-media/hlsfmp4/2017/04/28/01234_1_webvtt-test_wg_,240p.mp4,360p.mp4,480p.mp4,720p.mp4,1080p.mp4,.urlset/master.m3u8

**Comment by erankor** [comment]
@flavioribeiro, thanks for the update, please share your conf in case someone else will want this feature

**Comment by flavioribeiro** [comment]
I documented all the stuff I did on https://github.com/flavioribeiro/nginx-vod-module-fmp4-hls

**Comment by erankor** [comment]
Thanks @flavioribeiro, closing this issue

**Comment by flavioribeiro** [comment]
@erankor ok, we're deploying this module here at @nytimes, we should make more progress on [that](https://github.com/flavioribeiro/nginx-vod-module-fmp4-hls) project later.

**Comment by erankor** [comment]
Just to update this thread that support for HLS/fMP4 was merged here - https://github.com/kaltura/nginx-vod-module/pull/668
There are still open todos for supporting encryption and iframe playlist
