### ISSUE TITLE
Sample configuration for Dash using local delivery

### ISSUE THREAD

**Issue by lvillarino** [kaltura/nginx-vod-module#592]
Hi:

Where I can find a configuration example for Dash using local delivery?

Thanks

**Comment by erankor** [comment]
You can take this sample - https://github.com/kaltura/nginx-vod-module/#local-configuration and change `vod hls` to `vod dash`.
Other than that, a couple of setttings that are recommended for dash:
```
vod_segment_duration 4000;
vod_align_segments_to_key_frames on;
vod_manifest_duration_policy min;
vod_dash_manifest_format segmenttemplate;
vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;
```

**Comment by lvillarino** [comment]
**location /content/ {
			root /web/;**

What will be the url that I have to call for the above setting and where I have to put the mp4 file on server.

Thanks

**Comment by erankor** [comment]
With location=/content/ and root=/web/ the files need to be under /web/content/. For example, if you have /web/content/somepath/video.mp4 the URL would be http://domain/content/somepath/video.mp4/manifest.mpd. 
If you don't want the /content as part of the file path, you can use alias instead of root.

**Comment by lvillarino** [comment]
This my nginx configuration

```
#user  nobody;
worker_processes  1;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log  logs/error.log  info;

events {
    worker_connections  1024;
}

http {
	server {
		# vod settings
		vod_mode local;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;
                
                vod_segment_duration 4000;
                vod_align_segments_to_key_frames on;
                vod_manifest_duration_policy min;
                vod_dash_manifest_format segmenttemplate;
                vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;

		# vod caches
		vod_metadata_cache metadata_cache 32m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

		# file handle caching / aio
		open_file_cache          max=1000 inactive=5m;
		open_file_cache_valid    2m;
		open_file_cache_min_uses 1;
		open_file_cache_errors   on;
		aio on;
		
		location /content/ {
			root /usr/local/nginx/html/;
			vod dash;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}
```
I put my file at /usr/local/nginx/html/content/testfile-720.mp4

I'm receiving an error when I call http://server/content/testfile-720.mp4/manifest.mpd

Entry error
`2017/04/30 06:15:59 [error] 2552#2552: *1 ngx_http_vod_validate_streams: no matching streams were found while reading media header, client: , server: , request: "GET /content/testfile-720.mp4/manifest.mpd HTTP/1.1", host: ""`

**Comment by erankor** [comment]
Most probable cause is that the mp4 file uses codecs that are not supported for dash, you can check with mediainfo. If that doesn't help, I suggest you will enable debug logs and check  what it says before this error.

**Comment by lvillarino** [comment]
How I enabled the debug logs ? and Where I can find a correct video to make sure that current setup works?

**Comment by erankor** [comment]
You can download some 'big buck bunny' sample that uses h264/aac, there are some torrents available on their site.
Alternatively, you can convert your video to h264/aac using ffmpeg.
