### ISSUE TITLE
epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too

### ISSUE THREAD

**Issue by mrcatman** [kaltura/nginx-vod-module#600]
I'm now testing using nginx-vod-module for getting external JSON  and combining files to a HLS playlist. When I try to watch it in players, the first file goes correctly, and the playlist's length is determined right. But then it just stops playing, and Nginx's error log tells:
`2017/05/14 12:10:33 [info] 14259#0: *34 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too (104: Connection reset by peer) while reading response header from upstream, client: 37.194.211.159, server: , request: "GET /content/playlist.json/seg-2-v1-a1.ts HTTP/1.1", subrequest: "/api/content/okno.mp4", upstream: "http://51.254.59.155:80/api/content/okno.mp4", host: "62.109.30.160"
2017/05/14 12:10:39 [info] 14259#0: *3 client closed connection while waiting for request, client: 37.194.211.159, server: 0.0.0.0:80`

Playlist:
`{
	"durations": [ 10000, 15000 ],
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/content/dummy.mp4"
				},
				{
					"type": "source",
					"path": "/content/okno.mp4"
				}
			]
		}
	]
}`

I found out that this problem happens only with files more than 3-5 MB, small files are handled correctly.
In the local mode it works with big files normally.

Also I tried some different servers with different Nginx or Apache configurations, but got same result.  Is the problem in nginx-vod-module?

**Comment by erankor** [comment]
Please provide the URL of the stream

**Comment by mrcatman** [comment]
Playlist URL: http://62.109.30.160/content/playlist.json/index.m3u8
JSON URL: http://playlist.myowntv.org/api/content/playlist.json

**Comment by erankor** [comment]
I am able to play this URL successfully in hls.js. Manually pulling the second segment with curl works fine as well.
But the bitrate of the second MP4 is very high:
```
mediainfo \temp\okno.mp4 | grep "bit rate"
Overall bit rate mode                    : Variable
Overall bit rate                         : 12.5 Mbps
Maximum bit rate                         : 16.0 Mbps
```
The size of first TS segment is 2MB and the size of the second is 16MB. This makes the player stall, and maybe some players just give up and cancel the request.
