### ISSUE TITLE
Documentation or Tutorial

### ISSUE THREAD

**Issue by suxonca** [kaltura/nginx-vod-module#612]
Sorry but I'm really newbie with nginx config file.
Please, Have you some another documentation tu run a sample step by step?
Some kind of tutorial that tell me which one are the static dirs and what is the output URL for HLS 

We are using a streamer now and I think that this can be a better solution for us.

thanks in advance.

**Comment by erankor** [comment]
If you want to set up a simple local configuration, you can:
1. install the nginx-vod package (https://github.com/kaltura/nginx-vod-module/#installation)
2. replace the nginx configuration with https://github.com/kaltura/nginx-vod-module/#local-configuration (the configuration that comes with the package is meant to be used with a Kaltura server)
3. remove all references to `fallback` in the configuration (fallback is a feature of proxying the request to a remote server in case the file is not found locally, you can start without it)
4. change `root /web/;` to point to where your mp4 files are stored
After these steps you should be good to go, but if it doesn't work, look at the nginx error log.

**Comment by erankor** [comment]
@suxonca, can we close this issue?
