### ISSUE TITLE
Stucks on big files

### ISSUE THREAD

**Issue by mrcatman** [kaltura/nginx-vod-module#613]
When making a live playlist from big files (300mb-1gb), the stream stops after ~30s and stucks.  Then if I play it again, it starts from the same place, even after a hour or two.

The files are held on the same server where nginx is, and the time is synced with the remote JSON server, so it's not a problem with download or time offsets.

The configuration is: (not full)
```
location ~ /content {
		vod hls;
		vod_mode mapped;
		add_header Access-Control-Allow-Headers '*';
		add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
		add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		add_header Access-Control-Allow-Origin '*';
		expires 100d;
	}
```

```
vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
vod_last_modified_types *;
vod_align_segments_to_key_frames on;
vod_max_mapping_response_size 1000K;
vod_manifest_segment_durations_mode accurate;
vod_metadata_cache metadata_cache 512m;
vod_response_cache response_cache 128m;
```

What can be the reason?

**Comment by erankor** [comment]
Any chance you are using a bitrate that is too high for the client? as in this issue - https://github.com/kaltura/nginx-vod-module/issues/600

**Comment by mrcatman** [comment]
No, these files even were tested before and worked correctly.

Some remarks about the error:
- in VOD mode, there are (probably) no such errors, I can freely move across the length of video playlist, even if it contains big files and is 10 hours long;
- The most times it happened just after I closed the players, and after a minute,
 when I turned them on again- the videos were on the same place and stucked after 30s;
- after the end of a video and changing it to a new one the stream starts to work properly, but again - just until the stream is not watched by anyone;  
- after this happens on a one playlist, the same problem happens with another ones;
- even small and tested before files then stop after a single length of M3U8 playlist;
- when I open the player in a new window, all goes correctly (probably something with caching),  but can also stop suddenly (the bitrate is normal, as I've already said).

**Comment by erankor** [comment]
Please send the stream URL

**Comment by erankor** [comment]
Also, what do you use to generate the JSON? do you use the sample playlist.php?

**Comment by mrcatman** [comment]
I use my own script:https://pastebin.com/Djv4tPSL
Example output: http://playlist.myowntv.org/api/content/1/1495886461

Example playlist: http://212.47.243.111/content/1/1495886461/index.m3u8


Now I made the cache bigger and added some caching headers like 
add_header Last-Modified "";
add_header Cache-Control "no-cache";

And the playback is going well now, but I don't know, will it be so later or not.

**Comment by erankor** [comment]
From a very brief look, the script is wrong, you can't have firstClipTime update all the time, this means you are changing the timestamps while the player is consuming the stream, it can't work. firstClipTime should have a fixed value until a clip is removed from the playlist, and when that happens it needs to be incremented by the exact duration of the clip that was removed.
Getting the logic right is not trivial, I suggest you look at the sample script (https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php) and implement your logic accordingly.

**Comment by mrcatman** [comment]
No, it's the same all the time, it's just being fetched from the JSON files like this: https://pastebin.com/ErqVeGxq (these are generated by a web-based broadcast studio on my site).

**Comment by erankor** [comment]
I'm sorry, but I don't have the capacity to debug custom scripts that are written to work with this module.
Please test with the sample script included with the module and see if it works for you.
