### ISSUE TITLE
error on hls aes128 encryption

### ISSUE THREAD

**Issue by RecareLee** [kaltura/nginx-vod-module#616]
Hi, i just use ngx-vod-module to serve hls encrypt stream, but i can not play. i try to analysis it , i found that i use openssl to decrypt the encrypted ts, in the result, the PMT is not correct.
the decrypted ts' head 16 bytes data are: 
4047 1000 0000 0db0 0100 00c1 0000 ee01
when modified it to be following:
4047 1000 0000 0db0 0100 00c1 0000 ef01
the decrypted ts can be played.

what is the reason?  really appreciate it.

**Comment by erankor** [comment]
please provide the stream URL and nginx.conf

**Comment by erankor** [comment]
btw, from what you pasted, looks like the IV is off by one

**Comment by RecareLee** [comment]
well @erankor , the stream just located in local sercure network where  can not be  accessed in outside. if it is ok , i can give you the drm json file and nginx configure.
drm json:
[{"pssh":[{"data":"TgIAAAEAAQBEAjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AWgBRAFMAUABSAEYAbABKAFMAcABDAHMASwBvAFMAawAxAGoAagB2AEoAUQA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgB6ACsAagBLAFcAUgBzAGYAcQBxADAAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+ADwALwBMAFUASQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=","uuid":"9a04f079-9840-4286-ab92-e65be0885f95"},{"data":"CAESEESPBGVJWZBKrCqEpNY47yUaClZFUklNQVRSSVgiGTAwMWNoMDAwMDAwOTA5OTAwMDAwMDExMzEqBVNEX0hE","uuid":"edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"}],"iv":0,"key_id":"RI8EZUlZkEqsKoSk1jjvJQ==","key":"41xmNrzFNvRxAkCMc1h7nA==","pos":"1496217600"}]

nginx conf:
location ~ ^/internal_tvod_ehls
{
    set $tvod_json_path "";
    set $vod_drm_json_path '';
    set $hls_key_uri '';

    vod hls;
    vod_mode mapped;
    vod_segment_duration 2000;
    vod_upstream_location /live_json;
    vod_upstream_extra_args path=$tvod_json_path;
    vod_max_mapping_response_size 10m;

    vod_response_cache tvod_ehls_json_res_cache 10m 7d;
    vod_mapping_cache  tvod_ehls_mapping_cache 10m 7d;

    vod_force_continuous_timestamps on;
    vod_secret_key "GzoNU9Dfwc//Iq3/zbzMUw==";
    vod_hls_encryption_method aes-128;
    vod_hls_encryption_key_uri $hls_key_uri;

    vod_hls_absolute_master_urls off;
    vod_hls_absolute_index_urls off;
    vod_hls_absolute_iframe_urls off;
    vod_hls_master_file_name_prefix index;
    vod_hls_index_file_name_prefix sec;

    vod_drm_enabled on;
    vod_drm_upstream_location /internal_proxy_drm;
    vod_drm_request_uri "?path=$vod_drm_json_path";
    vod_drm_info_cache tvod_ehls_drm_res_cache 10m 7d;

    vod_drm_single_key on;

    access_by_lua '
            --ngx.log(ngx.DEBUG,"jitp ehls tvod request uri:",ngx.var.request_uri)
            local _,_,tvod_json_path  = string.find(ngx.var.request_uri,"%?path=([^&]*)")
            ngx.var.tvod_json_path = tvod_json_path
            --ngx.log(ngx.DEBUG,"jitp ehls tvod json path:",ngx.var.tvod_json_path)

            local _,_,hls_key_uri = string.find(ngx.var.request_uri,"&keyuri=([^&]*)")
            ngx.var.hls_key_uri = ngx.decode_base64(hls_key_uri)
           ';

    allow 127.0.0.1;
    deny all;
}

**Comment by RecareLee** [comment]
i just attached the original ts file in zip format.

**Comment by erankor** [comment]
1. The format of the IV in the JSON is invalid, you passed an integer, while it should be base64 encoded 128 bit binary (same as key/key_id).
2. I don't quite understand what you are trying to do, there are two ways to work with HLS encryption - 
a. For clear keys encryption, nginx-vod-module generates the key based on a seed configured in nginx.conf - in this case you don't set any of the vod_drm_xxx params, you set vod_secret_key instead.
b. For FairPlay DRM - you do need to enable DRM in nginx.conf, a sample configuration for that is provided here https://github.com/kaltura/nginx-vod-module/#sample-configuration
It seems you are trying to do some mix of these two options, so it probably won't work.

**Comment by RecareLee** [comment]
Actually you are right @erankor, what if i do not set the IV in the json?  you said it is optional.
I want to use FairPlay DRM, the drm json is generated by another process, so should i off the vod_secret_key?

**Comment by erankor** [comment]
If you use FairPlay (vod_drm_enabled on) vod_secret_key will be ignored.
Regarding the IV, the spec says that if an IV is not specified it will default to the (one-based) segment index, expanded to 128 bit. This is working for us in clear key HLS AES, but IIRC it didn't work with FairPlay, so you should specify an IV in the JSON and make sure it's the same one you use to generate the FairPlay license.

**Comment by RecareLee** [comment]
well,  the drm server i used is verimatrix, i searched it's key generation response, there are no IV directive. 

 {
                "drmName": "VERIMATRIX_ITV",
                "streamingProtocol": "HLS",
                "keyData": [
                    {
                        "contentKey": {
                            "keyId": "ce921b9318921a84c924260cf3014865",
                            "key": "5be181052b30003f173fcc7186d21356",
                            "position": 1497253036
                        },
                        "drmData": {
                            "keyUrl": "https://80.80.60.242/CAB/keyfile?s=600&r=001ch00000090990000001130&t=DTV&p=1497253036&kc=b423c4064f8411e78ae5000c29879769&kd=3781e5da72da11cdd246ce90e72b6803"
                        }
                    }

**Comment by erankor** [comment]
Sorry, I'm not familiar with Verimatrix, maybe you should ask them what to use.
When no IV is specified the module uses the segment index expanded into 128 bit as the IV, this works well for HLS AES, but as I wrote above, didn't work for us with DRM. You can try to set it to zero ("AAAAAAAAAAAAAAAAAAAAAA==") maybe that will work, but I'm just guessing here...

**Comment by erankor** [comment]
@RecareLee, can this be closed?

**Comment by RecareLee** [comment]
OK ! @erankor , Thanks again for your support !
