### ISSUE TITLE
Unable to display VOD content

### ISSUE THREAD

**Issue by bigretromike** [kaltura/nginx-vod-module#617]
Hello, 

I install nginx-vod-module by adding proper source for Debian8.
I had to add wheezy sources because nginx use libopenjpeg.so.2 and not 5 (provided with Jessie)

My config file /opt/kalkura/nginx/cong/nginx.conf look like this:
```
worker_processes 1;

events {
        worker_connections 1024;
}

http {
        #upstream fallback {
        #       server fallback.kaltura.com:80;
        #}

        server {
                # vod settings
                vod_mode local;
                # vod_fallback_upstream_location /fallback;
                vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
                vod_last_modified_types *;

                # vod caches
                vod_metadata_cache metadata_cache 512m;
                vod_response_cache response_cache 128m;

                # gzip manifests
                gzip on;
                gzip_types application/vnd.apple.mpegurl;

                # file handle caching / aio
                open_file_cache          max=1000 inactive=5m;
                open_file_cache_valid    2m;
                open_file_cache_min_uses 1;
                open_file_cache_errors   on;
                aio on;

                #location ^~ /fallback/ {
                #       internal;
                #       proxy_pass http://fallback/;
                #       proxy_set_header Host $http_host;
                #}

                location /content/ {
                        root /var/www/;
                        vod hls;

                        add_header Access-Control-Allow-Headers '*';
                        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                        add_header Access-Control-Allow-Origin '*';
                        expires 100d;
                }
        }
}

```

Then I put mp4 inside /var/www; 
go into browser to 127.0.0.1 and see nginx welcome page
the i try to access 127.0.0.1/content/ and get error 400;

the /opt/kaltura/log/nginx/error.log show this
`2017/06/02 06:22:06 [error] 28272#0: *4 ngx_http_vod_hls_parse_uri_file_name: unidentified request, client: 127.0.0.1, server: , request: "GET /content/ HTTP/1.1", host: "127.0.0.1"`

/var/www is set to 777;

I comment out parts for fallback as mention in this issue: https://github.com/kaltura/nginx-vod-module/issues/612

Anything im doing wrong ?

**Comment by jessp01** [comment]
Hi @bigretromike,

The URL should be something like localhost/content/your.mp4/index.m3u8.
What are you getting when making that request?
Also, not reason for /var/www to be 777, in fact, it's bad practice.

**Comment by bigretromike** [comment]
as for 777 is know, but its a local server without access from outside just for testing.
it looks like when i request 127.0.0.1/content/big.mp4/index.m3u8 it try to open /var/www/content/big.mp4 so i moved mp4 into `content` directory (i was thinking that `content` is location for nginx)

Now i'm getting the file.
Can I use somehow non mp4 container video encoded with x264 (and others) for transcoding-on-fly ?

**Comment by erankor** [comment]
The module supports only mp4 container and mkv (experimental). If you have files that use other containers, easiest solution would be to repackage them to mp4 using ffmpeg (without transcoding)
Also, the module does repackaging but not video transcoding (audio transcoding is performed for rate change).

**Comment by bigretromike** [comment]
I was hoping that I would be able to throw ANY video file onto kaltura and it would transcode it on fly and server as dash vod stream. 
Do you have any idea how could I achive that without transcoding file before throwing it onto nginx ?

**Comment by jessp01** [comment]
You can install the Kaltura Server Community Edition. That will take care of the transcoding part and use the VOD module to serve them.
For more info on that, see:
https://github.com/kaltura/platform-install-packages/#documentation-and-guides

**Comment by bigretromike** [comment]
Thank you for pointing me to kaltura platform. Hope I will be able to install it and configure better than nginx-vod-module.

**Comment by bigretromike** [comment]
@jessp01 I check out that Kaltura Server CE, while I was reading how to use it I found one thing:
`In the Kaltura Community Edition,Live Streaming requires Flash Streaming Server software installed , such as Adobe FMS, Red5 and Wowza or alternatively, an Akamai CDN account.`
How come it use same module but use 3rd party server for streaming. 

Also as I want to dive deep in this solution I would like to know if this is possible:
Adding video (not only mp4/x264) to Kaltura Server CE, serve it as VOD and while client ask for that video transcode it on-fly while serving it as mpeg-dash (as vod and not live stream) or Server is just an overkill for this  problem ?

**Comment by jessp01** [comment]
Hi @bigretromike,

Not sure where you were looking but for Live Streaming, see:
https://github.com/kaltura/platform-install-packages/blob/Lynx-12.18.0/doc/install-kaltura-redhat-based.md#live-streaming-with-nginx-and-the-rtmp-module
A similar section exists in deb installation howto.

For VOD, like I said, this Nginx module is used by default. You can integrate with external CDNs [such as Akamai, Level3 and others] if you wish but it is hardly a must [where was it stated that an Akamai account is mandatory?]

The Kaltura Server can handle a variety of source videos in different formats and convert them into MP4s. Obviously, we cannot guarantee ANY format can be properly handled but we do test a wide range of sources.

**Comment by bigretromike** [comment]
> In the **Kaltura Community Edition**, Live Streaming **requires** Flash Streaming Server software installed , such as **Adobe FMS, Red5 and Wowza** or alternatively, an Akamai CDN account.

So I assume the pdf manual included in kaltura is wrong then, as live streaming using nginx-vod-module don't requires them (as it use ffmpeg). 

Also you did great work with kaltura (I starting to think that is a bit overkill for my side-project, but Im happy that I got it working and was introduce to it).

I can only recommend you to set proper 'topics' on github so more and more people would recognized this software as its a very powerfull tool. 

Also the .deb script don't install all necessary libs (it would skip libopenjpeg2, libaas4 even when wheezy is added to jessica), but after installing missing libs by hand before running script it work like a charm.

**Comment by jessp01** [comment]
Hi @bigretromike,

Can you please specify the location of the PDF in question? it is obviously not up to date...
As for the deb packages, the kaltura-ffmpeg deb declares all needed deps:
```
aptitude show kaltura-ffmpeg

Depends: libopencore-amrwb0, libx264-148, libopencore-amrnb0, libass4 | libass5, libgsm1, libvdpau1, libmp3lame0, libopenjpeg2 |
         libopenjpeg5, libschroedinger-1.0-0, libspeex1, libtheora0, libva1, libvpx1 | libvpx3, libxvidcore4, libvorbis0a,
         libvorbisenc2, libx265-87 | libx265-79, libvorbisfile3
```

Thanks,

**Comment by bigretromike** [comment]
As I purge my testing setup. I cannot give you the exact link, but it can quide you to it:
1. when you install freshly installed server on browser http://kaltura-host.example you then have 2 sections with link, first is for admin panel and second is to kmc? (dont know if I got that name right) the one to upload/manage content. 
2. on the upload page there is a manual (from i remamber on right top side)
3. the part i was refering to is about live streaming - I started to read it because same page didn't want to find my flash plugin on firefox (which I later resolve with updating it)

Great to hear that the documentation was not up to date (because now it make sense).
Hope that the manual will get updated as some of us `sometimes` want to read that ;-)

Have a great day

**Comment by jessp01** [comment]
Hi @bigretromike,

I believe the PDF in question is this one https://github.com/kaltura/kmc-docs/blob/master/pdf/KMC_User_Manual.pdf?

It is, indeed not up to date and I can see how, from reading it, one may be led to understand that an Akamai CDN account is mandatory for certain operations when, in fact, it is not.
We're in the process of remaking KMC completely, getting rid of Flash and replacing it with an Angular 2 based app. The docs will obviously be updated accordingly.

Thanks for reporting and have a nice, productive day.
