### ISSUE TITLE
Not sure if vod_open_file_thread_pool is working for me

### ISSUE THREAD

**Issue by frutality** [kaltura/nginx-vod-module#620]
This is not a bug. I just need some explanation and/or help, please.

I compiled nginx & nginx-vod-module on Ubuntu 16.04 using `--with-file-aio` and `--with-threads`. Added `vod_open_file_thread_pool` to config. Looking at 

> counters on the vod status page - open_file vs. async_open_file

And I don't get it. `open_file` counts are much more than `async_open_file`. Does it mean I have configured something wrong? There is full `vod_status` https://pastebin.com/Ah8m9fit (same video is playing in 2 browsers).

There are my updates of nginx configs:
nginx.conf: 
`thread_pool open_file_pool threads=32;`

sites_available/default server block:
```
vod_mode local;
vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
vod_last_modified_types *;

# Performance
vod_open_file_thread_pool open_file_pool;
vod_performance_counters abc; # Not sure what should be here

# Recommended DASH settings https://github.com/kaltura/nginx-vod-module/issues/592
vod_segment_duration 4000;
vod_align_segments_to_key_frames on;
vod_manifest_duration_policy min;
vod_dash_manifest_format segmenttemplate;
vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;

# vod caches
vod_metadata_cache metadata_cache 512m;
vod_response_cache response_cache 128m;

# gzip manifests
gzip on;
gzip_types application/vnd.apple.mpegurl;

# file handle caching / aio
open_file_cache          max=1000 inactive=5m;
open_file_cache_valid    2m;
open_file_cache_min_uses 1;
open_file_cache_errors   on;

location /storage/videos/ {
        vod dash;
        aio on;

        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
}

location /vod_status {
        vod_status;
}
```

**Comment by erankor** [comment]
That's actually a good sign :)
If you are getting a non-zero count on async_open_file, it means you configured it correctly. 
The reason the count of open_file is non-zero is due to the 'open_file_cache' - when a file handle already exists in cache, the open call completes synchronously. So essentially, in your configuration - open_file = open file cache hits, async_open_file = open file cache miss / "real" file open.
Btw, for this reason, I'd expect that the average execution time (sum/count) of open_file would be several orders of magnitude lower than async_open_file.

**Comment by frutality** [comment]
Ok then :)

> Btw, for this reason, I'd expect that the average execution time (sum/count) of open_file would be several orders of magnitude lower than async_open_file.

I checked and this is correct. `open_file` sum / count is 4536 / 888. `async_open_file` is 32750 / 8.

Sorry for bothering. Closing.
