### ISSUE TITLE
How to add water mark to video

### ISSUE THREAD

**Issue by msivakr** [kaltura/nginx-vod-module#621]
One of our clients has requirement of adding viewer IP address over video as water, 

Please suggest how we can get it?

**Comment by erankor** [comment]
We don't have this feature, in high level - video transcoding is too heavy to perform on-the-fly per request. It is possible to add an overlay on the player side, but naturally it won't be very secure.
There are solutions for embedding forensic watermarks in video that do not require transcoding (forensic = a watermark that is not visible to the end user). We have in the past integrated with Civolution's Nexguard technology to accomplish this.

**Comment by seedoubleu** [comment]
Is the forensic watermarks that do not require transcoding available now？It is useful for content protection.

**Comment by seedoubleu** [comment]
I saw #1127, and "an not open-source solution built on top of this module", can i have a link with the solution?

**Comment by erankor** [comment]
We have an integration with Nagra's NexGuard technology.

**Comment by seedoubleu** [comment]
hi erankor, I saw #1127, is the "a solution built on top of this module, but it's not open-source" you metion is the NexGuard? And can I have a link with how to use it? or samething introduce about the Nexguard technology work with nginx-vod-module. I don't know how to start.

**Comment by erankor** [comment]
Our integration with NegGuard is also not open source, not just NexGuard itself, sorry...
