### ISSUE TITLE
Live mapped streaming

### ISSUE THREAD

**Issue by sternj** [kaltura/nginx-vod-module#631]
A couple of questions regarding mapped configuration-- Firstly, with either a local or remote JSON file, what directive specifies its location? In addition to that, assuming that playlistType is set to "live", will this loop videos in the order specified by the JSON? Does this support duplicates? With all of these conditions, where is the destination of the stream specified or, alternately, how would a client access the stream?

**Comment by erankor** [comment]
1. the directive vod_upstream_location, if it's empty, nginx-vod-module will fetch the json from file (path is determined by nginx's built in root/alias directives), if non-empty, it should point to a location that uses proxy_pass and nginx-vod-module will issue a subrequest to this location to fetch the json (sample config here https://github.com/kaltura/nginx-vod-module/#mapped-configuration)
2. it's not enough to set the type to live, the json needs to be updated periodically in order to generate a live stream. If you want to play X videos in a loop - 
  a. set up nginx in mapped mode (can use a config similar to what I mentioned above)
  b. set up the upstream server to run this sample php script - https://github.com/kaltura/nginx-vod-module/blob/master/test/playlist.php (update the file paths). This sample script generates the appropriate jsons for nginx-vod-module in order to play the provided videos in a loop.

**Comment by sternj** [comment]
Two more questions-- First, the paths provided within the JSON are relative to the upstream server (that is to say, the videos will come from [upstreamURL]/[VidPathFromJSON]

Second, how on earth does the client access this stream? How does one start the stream?

**Comment by erankor** [comment]
1. Again there are 2 options :) as the JSON can be loaded from a local file or via HTTP, so can the MP4 files - 
  a. If you set `vod_remote_upstream_location` the MP4s will be read from a remote location, nginx-vod-module will issue a subrequest to the nginx location you set in this directive. In this case, the paths in the JSON should be the relative URIs of the MP4 files.
  b. If you don't set this directive, nginx-vod-module will try to load the MP4s from local files, in this case the paths should be absolute file paths accessible to the nginx server.
2. The client just builds a URL like - http://domain/hls/path/to/playlist.json/master.m3u8 and passes it to the player (e.g. on iOS you can just click on such a URL and it will open the native player and play it)

But anyway, what I would suggest is that you will play with it a bit - use the provided playlist.php, set it up on some server, build a URL to nginx-vod-module and check what you get in the nginx error log. Most of the problems are easy to understand from the error log.

**Comment by sternj** [comment]
I have been playing around, and I input a URL of the format http://localhost:8001/mapped/playlist.json/manifest.mpd and got an error thrown from VLC media player (and, if I looked at said URL in a browser, I got a 503 service unavailable error. Attached is my nginx.conf, what's going on here?

`#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;


    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;
	
        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm index.php;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
	    fastcgi_pass unix:/run/php/php7.0-fpm.sock;
	    
        }
	location ~ /\.ht {
		deny all;	
	}

   
    }

     server {
	listen    8001;
	

	location ~ ^/mapped/hls/enc/p/\d+/(sp/\d+/)?serveFlavor/ {
			vod hls;
			vod_mode mapped;
			
			vod_upstream_location /kalapi_proxy/;
			

			add_header X-Me $hostname;
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			expires 100d;
}

     }

}`

**Comment by sternj** [comment]
It may also be worth noting that this is the json file in question
https://gist.github.com/sternj/60758294478e5deee6f79792b898191e

**Comment by erankor** [comment]
What error do you have in the nginx error log?

**Comment by sternj** [comment]
017/07/10 10:30:47 [notice] 40716#0: signal process started
2017/07/10 10:30:53 [error] 40719#0: *1 media_set_parse_json: failed to parse json -1: expected , or } while parsing object, got 0x0 while sending to client, client: 127.0.0.1, server: , request: "GET /mapped/playlist.json/master.m3u8 HTTP/1.1", host: "localhost:8001"
2017/07/10 10:30:53 [error] 40719#0: *4 media_set_parse_json: failed to parse json -1: expected , or } while parsing object, got 0x0 while sending to client, client: 127.0.0.1, server: , request: "GET /mapped/playlist.json/master.m3u8 HTTP/1.0", host: "localhost:8001"
2017/07/10 10:30:53 [error] 40719#0: *7 media_set_parse_json: failed to parse json -1: expected , or } while parsing object, got 0x0 while sending to client, client: 127.0.0.1, server: , request: "GET /mapped/playlist.json/master.m3u8 HTTP/1.0", host: "localhost:8001"
2017/07/10 10:32:19 [notice] 40729#0: signal process started

**Comment by erankor** [comment]
This means the JSON read by the module was truncated, you should increase `vod_max_mapping_response_size` (the default value is 1K)

**Comment by sternj** [comment]
New errors below, with the JSON that I posted  in mind what's going on?
2017/07/10 12:54:38 [error] 7184#0: *1 ngx_http_vod_validate_streams: cannot have more than a single subtitle track and it cannot be mixed with other track types while reading media header, client: 127.0.0.1, server: , request: "GET /mapped/playlist.json/index.m3u8 HTTP/1.1", host: "localhost:8001"
2017/07/10 12:54:38 [error] 7184#0: *4 ngx_http_vod_validate_streams: cannot have more than a single subtitle track and it cannot be mixed with other track types while reading media header, client: 127.0.0.1, server: , request: "GET /mapped/playlist.json/index.m3u8 HTTP/1.0", host: "localhost:8001"
2017/07/10 12:54:38 [error] 7184#0: *7 ngx_http_vod_validate_streams: cannot have more than a single subtitle track and it cannot be mixed with other track types while reading media header, client: 127.0.0.1, server: , request: "GET /mapped/playlist.json/index.m3u8 HTTP/1.0", host: "localhost:8001"

**Comment by sternj** [comment]
Ok so I took the subtitle line out of things, all working now, but how do I make it not display the small banner at the bottom?

**Comment by erankor** [comment]
regarding the first error, it probably happened because you requested index.m3u8 and not master.m3u8 - index.m3u8 represents a single stream, so nginx-vod-module can't return both media and subtitles in this request. 
Regarding the second issue, is the JSON being generated dynamically by playlist.php? the JSON changes all the time, so if you saved it to file, it can't work this way (from the URL you pasted it seems like that is the case).

**Comment by erankor** [comment]
@sternj, can we close this issue?

**Comment by sternj** [comment]
Yes, all is working perfectly.
