### ISSUE TITLE
HLS Live mapped streaming

### ISSUE THREAD

**Issue by computationalcore** [kaltura/nginx-vod-module#632]
Regarding HLS streaming, I have a CDN caching the ts files, but the manifest generated by mapped mode isn't cached.  In my case it is a URL based join of recorded files, like https://URL/file1/file2/file3/file4 .../index.m3u8.

As an example, even if file3 is not ready at this case https://URL/file1/file2/file3/index.m3u8 it will join file1 and file2. After some time file3 will be available and the manifest will be updated to include the file3 ts segments. All other file1 and file2 probably are already cached by the CDN. 

If the nginx.conf never changes, file1 and file2 and the parameters of the json map only includes file3 without changing the others, is there a guarantee that the ts segments of previous join that had only file1 and file2 will be the same? 

Cause since URL will be the same, CDN will already cached them, even if the manifest updates, it will cache only the new ts segments. 

Thanks

**Comment by erankor** [comment]
If you are only adding files (i.e. you will never return file1, file3 and then file1, file2, file3) and you use discontinuity = true (the default), then it should be fine.
If you use discontinuity = false, the segments that fall on clip boundary contain frames from both clips, so it won't work well.

**Comment by computationalcore** [comment]
Thanks erankor
