### ISSUE TITLE
Try to search .mp4 files in multiple folders.

### ISSUE THREAD

**Issue by SemenSemenych** [kaltura/nginx-vod-module#635]
Hello! 
Thanks for very handy module!

I'm trying to use multiple folders for file storage. Mounted different hard drives.
e.g. 
_/storage/vod02 -- /dev/sda
/storage/vod03 -- /dev/sdb_ etc...

but i don't want to use multiple location for nginx configuration to avoid mess.

so i configured nginx with following location:

```
      location ~* ^/vod/(.+)$ {
            root /storage/;
            try_files  /vod02/$1 /vod03/$1 /vod04/$1 =404;
            open_file_cache off;

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }

```
and it successfully returned to me .mp4 files lied in folders /storage/vod02/ /storage/vod03/... 
wget http://site/vod/12345.mp4 returns me an mp4 file lying in folder /storage/vod03/...
But when i add 
```
      location ~* ^/vod/(.+)$ {
            root /storage/;
            vod hls;
            vod_base_url '';
            vod_cache_buffer_size 2m;
            vod_initial_read_size 256K;
            try_files  /vod02/$1 /vod03/$1 /vod04/$1 =404;
            open_file_cache off;

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
```
to get nginx-vod-module working i've got an 404 answer 
on 
_wget http://site/vod/12345.mp4/index.m3u8_

What is the right configuration for nginx to get this idea work? 
Thank Нou in advance.

**Comment by erankor** [comment]
try_files doesn't work with this module, it was discussed in multiple issues in the past, see here - https://github.com/kaltura/nginx-vod-module/issues/143

**Comment by SemenSemenych** [comment]
Thanks a lot! 
It works!
