### ISSUE TITLE
Segmentation fault on manifest.mpd generation

### ISSUE THREAD

**Issue by ilyaevseev** [kaltura/nginx-vod-module#637]
### Environment:

* OS = CentOS 7
* Nginx = 1.13.1
* OpenSSL = 1.0.2l and 1.0.2k (but no problem with system-wide 1.0.1e)
* nginx-vod-module = 1.18

### Problem:

* Nginx worker terminates with "segmentation fault" on handling https://my.server.org/dash/bbb/bbb_,270,540,1080,p_1.mp4.urlset/manifest.mpd request.

### The complete GDB "backtrace full" output:

* https://gist.github.com/ilyaevseev/eeec7ecbfddc4acb1fa4ca879101a176

### Nginx configuration command (splitted to multiline for better clarity):

    ./configure
    --prefix=/etc/nginx
    --sbin-path=/usr/sbin/nginx
    --conf-path=/etc/nginx/nginx.conf
    --error-log-path=/var/log/nginx/error.log
    --http-log-path=/var/log/nginx/access.log
    --pid-path=/var/run/nginx.pid
    --lock-path=/var/run/nginx.lock
    --http-client-body-temp-path=/var/cache/nginx/client_temp
    --http-proxy-temp-path=/var/cache/nginx/proxy_temp
    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp
    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp
    --http-scgi-temp-path=/var/cache/nginx/scgi_temp
    --user=nginx
    --group=nginx
    --with-compat
    --with-file-aio
    --with-threads
    --with-http_addition_module
    --with-http_dav_module
    --with-http_flv_module
    --with-http_mp4_module
    --with-http_realip_module
    --with-http_secure_link_module
    --with-http_slice_module
    --with-http_ssl_module
    --with-http_stub_status_module
    --with-http_sub_module
    --with-http_v2_module
    --with-stream
    --with-stream_realip_module
    --with-stream_ssl_module
    --with-stream_ssl_preread_module
    --with-openssl=openssl-1.0.2l
    --add-module=../nginx-vod-module-1.18
    --with-http_image_filter_module
    '--with-cc-opt=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/local/include'
    --with-ld-opt=

**Comment by erankor** [comment]
My guess is you have a mix of the two openssl versions in the build (e.g. use includes from one and libs from another).  We had this problem before - https://github.com/kaltura/nginx-vod-module/issues/411.
Saw you also submitted a pull for supporting --with-openssl, and not sure that is the correct way to do it.
If it's important for you to use 1.0.2 I'd suggest that you install it so that it won't require --with-openssl, this way both nginx and nginx-vod-module will definitely use the correct version, and this issue will probably be solved.

**Comment by ilyaevseev** [comment]
> My guess is you have a mix of the two openssl versions in the build (e.g. use includes from one and libs from another

Of course, I checked that:

- There is no openssl-devel package in my build environment and no /usr/include/openssl folder.
   Otherwise #411 occurs (yes, I saw it, but my current situation is not the same!)
- There are no linker references to system-wide openssl libs
  Both libssl.a and libcrypto.a are linked statically from the builtin folder:

      $ make -C /opt/home/evseev.i/rpmbuild/BUILD/nginx-1.13.1
      make: Entering directory `/opt/home/evseev.i/rpmbuild/BUILD/nginx-1.13.1'
      make -f objs/Makefile
      make[1]: Entering directory `/opt/home/evseev.i/rpmbuild/BUILD/nginx-1.13.1'
      cc -o objs/nginx \
      objs/src/core/nginx.o \
      ...
      objs/ngx_modules.o \
      -Wl,-E -ldl -lpthread -lpthread -lcrypt -L/usr/lib -lm -lluajit-5.1 -ldl -lpcre openssl-1.0.2l/.openssl/lib/libssl.a openssl-1.0.2l/.openssl/lib/libcrypto.a -ldl -lz -lgd \
      -Wl,-E
      make[1]: Leaving directory `/opt/home/evseev.i/rpmbuild/BUILD/nginx-1.13.1'
      make: Leaving directory `/opt/home/evseev.i/rpmbuild/BUILD/nginx-1.13.1'

- There are no runtime references to system-wide OpenSSL libs:

      $ ldd /opt/home/evseev.i/rpmbuild/BUILD/nginx-1.13.1/objs/nginx
      	linux-vdso.so.1 =>  (0x00007fff3a500000)
      	libdl.so.2 => /lib64/libdl.so.2 (0x00007f75a9ff3000)
      	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f75a9dd7000)
      	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f75a9b9f000)
      	libm.so.6 => /lib64/libm.so.6 (0x00007f75a989d000)
      	libluajit-5.1.so.2 => /lib64/libluajit-5.1.so.2 (0x00007f75a962e000)
      	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f75a93cc000)
      	libz.so.1 => /lib64/libz.so.1 (0x00007f75a91b6000)
      	libgd.so.2 => /lib64/libgd.so.2 (0x00007f75a8f6f000)
      	libc.so.6 => /lib64/libc.so.6 (0x00007f75a8bad000)
      	/lib64/ld-linux-x86-64.so.2 (0x00007f75aa203000)
      	libfreebl3.so => /lib64/libfreebl3.so (0x00007f75a89aa000)
      	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f75a8794000)
      	libXpm.so.4 => /lib64/libXpm.so.4 (0x00007f75a8581000)
      	libX11.so.6 => /lib64/libX11.so.6 (0x00007f75a8243000)
      	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f75a7fee000)
      	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f75a7db0000)
      	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f75a7b0a000)
      	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f75a78df000)
      	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f75a76bc000)
      	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f75a7492000)
      	libXau.so.6 => /lib64/libXau.so.6 (0x00007f75a728e000)

- There is no official OpenSSL 1.0.2 package for Centos/RHEL7 ([planned for RHEL 7.4 only](https://bugzilla.redhat.com/show_bug.cgi?id=1276310)), so the only way for installing runtime libs on the each production server is "./config && make && make install". That seems bad solution.
- I use Nginx+OpenSSL building scenario described here:
  https://gist.github.com/moneytoo/ab3f34e4fddc2110675952f8280f49c5
  Generated Nginx binary works well (core and all addons except nginx-vod-module).

**Comment by erankor** [comment]
did you try what I wrote on the pull request ?

**Comment by ilyaevseev** [comment]
My debugging says that "p" is assigned to NULL as result of mp4_encrypt_write_guid call:
https://github.com/kaltura/nginx-vod-module/blob/master/vod/dash/edash_packager.c#L179

This causes segfault on the next line.

**Comment by ilyaevseev** [comment]
> did you try what I wrote on the pull request ?

No. Segfault is more critical for me, I should solve it ASAP.

**Comment by erankor** [comment]
1. Yes, I saw that p is null in the backtrace you sent, but if you look at the code you'll see that it doesn't make sense - since there are at least 2 more memcpy's to p in this function before this line, and there are also several writes to p in the function that calls it. Therefore I'm quite sure the build is invalid
2. Please try my suggestion since I believe it will solve this
3. Why is it so important to use openssl 1.0.2 instead of the builtin 1.0.1?

**Comment by ilyaevseev** [comment]
1. I added prints to many places. "p" contains correct non-NULL value after returning from the vod_copy() at line 178 and NULL after returning from mp4_encrypt_write_guid at line 179.
1. What suggestion? About multiple openssl versions? I answered it above. Or about my pull? It does not refer to segfault.
1. ALPN and HTTP/2

**Comment by erankor** [comment]
2. I refer to what I wrote in the pull, and yes, I believe it has everything to do with the segfault. --with-openssl is NOT supported in the current master, I've stated that in a couple of issues in the past after people reported segfaults. Also, you wrote above that it doesn't happen when using the builtin openssl, which indicates the connection between --with-openssl and the crash
3. Ok, and can't you just set it up globally? for example, by exporting C_INCLUDE_PATH / LIBRARY_PATH?

**Comment by ilyaevseev** [comment]
## Bug fixed:

* I have quick&dirty fixed NGX_HAVE_OPENSSL_EVP checks only,
* VOD_HAVE_OPENSSL_EVP was unassigned,
* so [stub version](https://github.com/kaltura/nginx-vod-module/blob/master/vod/mp4/mp4_encrypt.c#L944) of mp4_encrypt_write_guid was compiled.

Thank You very much for tips!

**Comment by erankor** [comment]
Thanks for the update!
