### ISSUE TITLE
Dash/Hevc: Errors when using files with correct BT2020/HLG backwards signaling

### ISSUE THREAD

**Issue by blagsheep** [kaltura/nginx-vod-module#642]
Hi, we have the following scenario: 

We want to use dash adaptive streaming with 5 renditions of hevc with HDR HLG ranging from 540p50 to 2160p50. The setup works just fine with files that have the following signaling:

![mediainfo_signaling_hlg](https://user-images.githubusercontent.com/918650/27951232-7c373a30-6304-11e7-92f3-813c91850bf5.png)

The Dash Reference Player and also multiple test devices (smart tvs) can work with the manifest just fine. The encoding is done with ffmpeg / x265 with the following parameters (excerpt)

`.. -b:v 11680k -maxrate 23200k -bufsize 17520k -r 50 -c:v libx265 -pix_fmt yuv420p10le -preset medium -vf "yadif" -color_primaries bt2020 -colorspace bt2020_ncl -color_trc arib-std-b67 -keyint_min 75 -g 75 -x265-params 'keyint=75:min-keyint=75:scenecut=0:no-open-gop=1:output-depth=10:profile=main10:repeat-headers=1'
`
However, to be standard compliant with "ETSI_TS_101154v2.3.1.pdf (DVB AV Toolbox)" and use correct HLG backwards signaling, we have to deliver the files with different information in the meta data:

> 5.14.4.4.2 HEVC HDR UHDTV IRDs and Bitstreams using HLG105.14.4.4.2.1 Signalling of transfer characteristicsHLG10 is specified for HDR bitstreams intended to be decodable by HEVC UHDTV IRDs. The HLG10 signallingspecified below may also be used for HLG services where there is no requirement for the bitstreams to be decodable byHEVC UHDTV IRDs.Encoding: HEVC HDR UHDTV Bitstreams using HLG10 shall set VUI transfer_characteristics to the value"14" to signal the opto-electronic transfer function as Recommendation ITU-R BT.2020 [36] 10-bits.HEVC HDR UHDTV Bitstreams using HLG10 shall also contain thealternative_transfer_characteristics SEI message. The alternative_transfer_characteristics SEImessage shall be inserted on the HEVC DVB_RAP, and preferred_transfer_characteristics shallbe set equal to "18", indicating Recommendation ITU-R BT. 2100 [45] HLG system.NOTE 1: Recommendation ITU-R BT.2100 [45] HLG system has an identical Opto-Electronic Transfer Functionto ARIB STD-B67 [i.27], so the same preferred_transfer_characteristics value is used.

---

![vui_transfer_characteristic](https://user-images.githubusercontent.com/918650/27951410-212c0eee-6305-11e7-9f65-7239eb08b19c.png)

---

![alternative_transfer_characteristic](https://user-images.githubusercontent.com/918650/27951421-32ffa6e4-6305-11e7-8b71-13dd9498cd8d.png)

---

This means we have to adjust not only the "transfer characteristic" but also the "alternative transfer characteristic". This is something that x265 cannot do at the moment, see this request:
https://bitbucket.org/multicoreware/x265/issues/326/alternative-transfer-characteristics-for

To produce standard compliant files we choose to use the software SEIedit (https://hdr.avtop.com/hdr_solutions_avtop) which does not change the encoding itself but only adds / edits the metadate of the encoded file. We use these settings:

![seiedit1](https://user-images.githubusercontent.com/918650/27951905-c3725c48-6306-11e7-9a08-d7c9df587373.PNG)

---

![seiedit2](https://user-images.githubusercontent.com/918650/27951910-c8417286-6306-11e7-978a-ea1120086069.jpg)

---

After this editing we get a file with the following, correct "HLG / BT2020" signaling that is backwards compatible and standard compliant:

![bildschirmfoto 2017-07-07 um 11 24 42](https://user-images.githubusercontent.com/918650/27951943-e8b557da-6306-11e7-88b7-911aeceec92d.png)

This file plays well on all tested devices as progressive dl and it has the same characteristics as comparable reference files of other companies that we are not aloud to share here, obviously. This file is:

PROGRESSIVE
http://159.8.45.26/dl/test/55555/h265_12000.mp4

DASH
http://159.8.45.26/dash/test/55555/h265_,12000,.mp4.urlset/manifest.mpd

Progressive works fine, but when using the above dash manifest (no matter if only one rendition or several of the same meta data characteristic are used, compare: http://159.8.45.26/dash/test/55555/h265_,4180,12000,.mp4.urlset/manifest.mpd ), the dash packager does not work as expected and no files are delivered.

We activated the debug.log and get the following entries when trying to access the above manifest(s), no matter which player / client used:

`2017/07/06 17:01:53 [error] 9333#9333: *14 ngx_http_vod_validate_streams: no matching streams were found, probably invalid segment index, client: 77.180.69.242, server: localhost, request: "GET /dash/test/55555/h265_,12000,.mp4.urlset/fragment-2-a1-x3.m4s HTTP/1.1", host: "159.8.45.26", referrer: "http://dashif.org/reference/players/javascript/v2.5.0/samples/dash-if-reference-player/index.html"
`
The options for further debugging seem limited, so the question is: what leads to this error? 

We get the same "ngx_http_vod_validate_streams" errors when working with other reference files with standard compliant HLG / BT2020 backwards signaling, so I assume that our own video encoding and the meta data editing workflow result in standard compliant mp4 files that should work just fine with nginx-vod-module. The following differences in the manifest files can be found:

<img width="1873" alt="bildschirmfoto 2017-07-06 um 13 56 23" src="https://user-images.githubusercontent.com/918650/27952448-983d5bac-6308-11e7-99d3-0d171fb5f01a.png">

Left: working example, right: the manifest in question, just with more renditions. Please ignore the change in frame rate, we also tested with 50p for both HLG and HLG / BT2020 signaling with the same results. The change in bandwidth for the same bitrate versions is minimal and should be related to the added metadate. 

The change in codec values is the only difference of significance (I guess) and it should be rooted in the edited metadata (to be confirmed, but how?). However, some of the codec parameters in representations of the problematic manifest file (right one) can also be found in the working example, so the pure values should not be any problem. The described problem and entry in the error log can be reproduced with any of these files in the manifest:

http://159.8.45.26/dl/test/55555/h265_12000.mp4
http://159.8.45.26/dl/test/55555/h265_4180.mp4
http://159.8.45.26/dl/test/55555/h265_2180.mp4
http://159.8.45.26/dl/test/55555/h265_1480.mp4
http://159.8.45.26/dl/test/55555/h265_780.mp4

So my guess is, that "ngx_http_vod_validate_streams" is the place to look for the reason. However I could not fully understand how this works and we need your help to move forward :-)

I hope the problem description was comprehensive enough, me and my team are thankful for any hint or support and would be available to deliver more data, of course.

**Comment by erankor** [comment]
I could not reproduce it on my test server - downloaded http://159.8.45.26/dl/test/55555/h265_12000.mp4 requested the first four audio and video fragments, all completed successfully. 
Can you share your nginx conf?

A couple more thoughts -
1. The failed URL that you pasted is for an audio segment, you can try to test video-only with `manifest-v1.mpd` and see if that plays
2. Is there a chance you edited the file in place? most nginx-vod configurations use caching, if you have caching enabled on your conf, you should never update a file in place, create a new file instead.

**Comment by blagsheep** [comment]
@erankor thank you so much. It really was a caching issue and a result of our file distribution pipeline overwriting an earlier version of the file. 

With new files in different folders everything works as expected. We were just not thinking about caching as we never ran into problems before. Thank you!

**Comment by erankor** [comment]
Great, thanks for the update!
