### ISSUE TITLE
HLS doesn't play on Apple (Mobile)

### ISSUE THREAD

**Issue by jAndreas** [kaltura/nginx-vod-module#646]
I have the issue that the generated .m3u8 files from the vod-module seem not to be recognized nor played from mobile apple devices (testing on iPhone 5 & 6 with latest safari). The same HLS stream plays without any problems on OSX Safari (Mac and Win).
The same .m3u8 file also plays with hls.js / MediaStream on other browsers.

Is there anything to be considered for mobile-safari playback? Looking into a remote debugger, the resource tab says "an error occurred trying to load the resource" when selecting the index.m3u8. However, the file seems to be totally fine since I can download it from the webinspector:

    #EXTM3U
    #EXT-X-TARGETDURATION:4
    #EXT-X-ALLOW-CACHE:YES
    #EXT-X-PLAYLIST-TYPE:VOD
    #EXT-X-VERSION:3
    #EXT-X-MEDIA-SEQUENCE:1
    #EXTINF:4.000,
    seg-1-v1-a1.ts
    #EXTINF:4.000,
    seg-2-v1-a1.ts
    #EXTINF:4.000,
    seg-3-v1-a1.ts
    (...)
    seg-64-v1-a1.ts
    #EXTINF:3.762,
    seg-65-v1-a1.ts
    #EXT-X-ENDLIST

Nginx vod module config is as simple as:

                vod hls;
                vod_segment_duration 4000;
                vod_align_segments_to_key_frames on;

                vod_last_modified_types *;
                add_header Access-Control-Allow-Headers "origin,range,accept-encoding,referer";
                add_header Access-Control-Expose-Headers "Server,range,Content-Length,Content-Range";
                add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
                add_header Access-Control-Allow-Origin "*";
                expires 5d;

When I try to manually call a `.play()` on the video element (remote inspector) I receive this error:

     NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

Which seems not very helpful. Another strange thing is, that I can call `.fastSeek()` on the video element and this seems to work... I can see on the device how the video jumps to the sequence passed into the function, it just won't play the video.

ffmpeg -i output for the mp4 file in question:

    bitrate: 1015 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 854x480 [SAR 1280:1281 
    DAR 16:9], 877 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
    handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s

**Comment by erankor** [comment]
Maybe you need to use HTTPS, at some point (don't remember which version) Apple required that the stream will be pulled over HTTPS

**Comment by erankor** [comment]
@jAndreas, can we close this issue?

**Comment by jAndreas** [comment]
@erankor Yes. The issue was a whole different story. Most mobile Apple devices won't autoplay (or programmatically play) a video (regardless if it is .m3u8, .mp4 or anything), if the `<video>` element doesn't possess the attributes `muted` and `playsinline`.

So this hadn't anything to do with the vod module, sorry for the trouble.

**Comment by erankor** [comment]
Ok, thanks for the update
