### ISSUE TITLE
Cache invalidation on vod_mapping_cache?

### ISSUE THREAD

**Issue by fsouza** [kaltura/nginx-vod-module#647]
We're using mapped mode and we have a use case where we want to be able to add or remove captions from videos dynamically (mostly add captions - captions take longer to generate than the video so, we want to publish the video then add captions, but being able to remove the captions is important too).

Would it be possible to implement some way of invalidating entries on ``vod_mapping_cache``, have some kind of TTL there or even an option to burst this cache without having to restart nginx?

**Comment by erankor** [comment]
All caches in this module accept an optional expiration parameter (in seconds), if it's not supplied, there is no expiration.
Another possible solution is to generate a new stream URL - add some version on the URL. This is what we do when we want to replace a video. Using some kind of versioning to support video replacement is a must when using a CDN or caching proxies.

**Comment by fsouza** [comment]
Oh somehow I missed the expiration parameter. Sorry about that.

Yeah, we use CDNs, but we purge the content whenever we add/remove captions, so that's not a must :D 

Thanks!
