### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by xeptor** [kaltura/nginx-vod-module#66]
../nginx-vod-module/vod/dash/../mp4_encrypt.h:93: error: redefinition of typedef ‘mp4_encrypt_video_state_t’
../nginx-vod-module/vod/dash/../mp4_encrypt.h:25: note: previous declaration of ‘mp4_encrypt_video_state_t’ was here

nginx-1.6.3
linux-2.6.32-5-amd64
gcc version 4.4.5

**Comment by erankor** [comment]
Thanks, fixed.

Btw, @jessp01 added a hook on GitHub pushes that validates the build, to prevent it from breaking in the future.
