### ISSUE TITLE
Multiple streams with same language code (HLS, mapped-mode, playlists)

### ISSUE THREAD

**Issue by benweidig** [kaltura/nginx-vod-module#666]
Hi there,

thanks for this awesome module!

We're trying to serve HLS playlists in mapped-mode containing multiple languages.

If the languages are different (e.g. deu,ita) there isn't a problem and the .m3u8 is generated accordingly. But we have multiple streams with the same language (e.g. deu,deu,ita,ita), like a "normal" audio track, and a commentary track, for multiple languages.

So far we tried defining multiple sequences with explicit tracks, but the only thing that worked was only having 1 single stream per language per file, or the additional languagues won't be detected :-(

Do you have any ideas or can you point us in the right direction?

Ben

**Comment by erankor** [comment]
If I understand correctly what you're looking for, the solution is simple - you just need to set the `label` field on the sequences in the mapping json. The label is the string that will be displayed in the language selector, you could set it to `English - normal` and `English - commentary` for example. When a label is not specified, the module automatically assigns one according to the language (if set). When comparing tracks, the label is used and not the language, so if you have different labels on a couple of tracks, both tracks will appear in the output, even if they have the same language.

**Comment by benweidig** [comment]
Wow, that was a really simple solution, thx!

Works great on iOS, VLC ignores it, but that's not the problem of nginx-vod, the m3u8 is correct.
