### ISSUE TITLE
DRM Examples/known working solutions

### ISSUE THREAD

**Issue by matclayton** [kaltura/nginx-vod-module#667]
Sorry this isn't really an issue, but I wasn't sure where else to ask it.

Do you have a working example of PlayFair, Widevine and PlayReady DRM? Also which license servers have you tested with/would recommend?

**Comment by erankor** [comment]
I'm not sure what kind of example you are looking for, there is a sample Widevine JSON here - https://github.com/kaltura/nginx-vod-module/#drm.
Other than that, I can say that we've been using all 3 systems on production for a couple of years.
We have our own server for handling DRM, it generates the JSON for nginx-vod-module and also replies to license requests. Unfortunately, it's not open source.

**Comment by matclayton** [comment]
I was hoping the DRM server would be open source or you could point to an implementation you were using. I've not yet found any good documentation on how to implement the servers for each of the 3 DRM solutions and we were about to embark on making one, so was just hoping to avoid some extra work!

**Comment by erankor** [comment]
Sorry, can't help you with that. 
There were folks here who used this module with DRM, maybe they can share some tips / code
