### ISSUE TITLE
Setting vod_segment_duration in JSON

### ISSUE THREAD

**Issue by mazanov** [kaltura/nginx-vod-module#676]
Is it possible to make changes in nginx-vod-module, that will allow vod_segment_duration to be setted in JSON received from the upstream?

**Comment by erankor** [comment]
I need to check, will need to eliminate all references to conf->segmenter (since it's static) and use media_set->segmenter instead

**Comment by erankor** [comment]
@mazanov, try this pull https://github.com/kaltura/nginx-vod-module/pull/687

**Comment by mazanov** [comment]
Thanks! Will try

**Comment by erankor** [comment]
@mazanov, did you try it?

**Comment by mazanov** [comment]
We are testing it, thanks!
I'll text when ready

**Comment by erankor** [comment]
Ok, I merged the change since I want to create a new release in a few days, please close the issue if all goes well

**Comment by mazanov** [comment]
All is working, thanks!

**Comment by erankor** [comment]
Thanks for the update
