### ISSUE TITLE
HLS with multi rendition

### ISSUE THREAD

**Issue by utu2016** [kaltura/nginx-vod-module#678]
Hi,
I have this configuration:
...
        server {
            listen  80 default_server;
            client_max_body_size 0;
           vod_metadata_cache metadata_cache 512m;
...
           location /my_App/ {
                vod hls;
                vod_mode local;
                vod_hls_absolute_master_urls off;
                vod_multi_uri_suffix .csmil;
                alias /my_storage/my_App/;
            }

When I use this  url, all works fine:
     http://baseurl/my_App/subfolder1/subfolder2/content_1.mp4/master.m3u8
response is:
   #EXTM3U
   #EXT-X-STREAM-INF:PROGRAM-
   ID=1,BANDWIDTH=123183,RESOLUTION=384x216,CODECS="avc1.4d401e,mp4a.40.2"
   index-v1-a1.m3u8

but when I use a multi rendition's uri like:
    http://baseurl/my_App/subfolder1/subfolder2/content_1,2,.mp4.csmil/master.m3u8

a 404 Not Found is received.

Looking in the debug file I found that nginx try to open a file with name composed by the 2 rendition suffix (1 and 2) togheter:

.... [error] 24232#0: *107 ngx_file_reader_update_state_file_info: open() "/storage/my_App/subfolder1/subfolder2/content_12.mp4" failed (2: No such file or directory), client: 185.26.142.33, server: , request: "GET /my_App/subfolder1/subfolder2/content_1,2,.mp4.csmil/master.m3u8
 HTTP/1.1", host: "baseurl"

I already used  multi-rendition's uri with HSS, and all works fine.

We're using /nginx-vod-module-1.10.

please, could you help me to understand where is my bug ?
thanks

**Comment by erankor** [comment]
You wrote `content_1,2,.mp4.csmil/master.m3u8` if you want content_1 & content_2 it should be `content_,1,2,.mp4.csmil/master.m3u8` (with a comma before the `1`)

**Comment by utu2016** [comment]
Erankor....you're the best !!!!
thanks ....it work!

**Comment by erankor** [comment]
Great, thanks for the update
