### ISSUE TITLE
Corrupted segments with long videos

### ISSUE THREAD

**Issue by idanya** [kaltura/nginx-vod-module#684]
I'm trying to play a long video in remote mode - 8 hours video.
It starts ok, but after ~7 minutes it stops and the player hangs. If I'm trying to seek after that point it also hangs. 
Looking at the network activity I can see that after the seek new segments (with higher ids) are downloaded but the player can't play them. Tried to manually download a specific .ts file from after the seek and play it locally, looks like the video is running in fast-forward (high speed) - something is corrupted with the file.

This scenario happens after I changed the configuration to:
`vod_manifest_segment_durations_mode estimate;`
When using:
`vod_manifest_segment_durations_mode accurate;`
The video does not even start playing.

This happens in both DASH and HLS.
configuration that might be related:
```
vod_mode remote;
vod_segment_duration 4000;
vod_align_segments_to_key_frames on;
vod_manifest_segment_durations_mode estimate;
```

**Comment by erankor** [comment]
Please send a URL to the MP4 and full nginx conf

**Comment by idanya** [comment]
Configuration:

```
daemon off;
worker_processes  4;
error_log  logs/error.log info;

pid        logs/nginx.pid;
worker_rlimit_nofile 8192;

events {
  worker_connections  4096;
}

http {
	include    mime.types;
	index    index.html index.htm index.php;
	default_type application/octet-stream;

	log_format main '$remote_addr - $remote_user [$time_local]  $status '
	'"$request" $body_bytes_sent "$http_referer" '
	'"$http_user_agent" "$http_x_forwarded_for"';

	access_log   logs/access.log  main;
	sendfile     on;
	tcp_nopush   on;
	tcp_nodelay  on;
	server_names_hash_bucket_size 128;

	server {
			listen      80;
			server_name _;

			error_log logs/vod_error.log info;

			open_file_cache          max=1000 inactive=5m;
			open_file_cache_valid    2m;
			open_file_cache_min_uses 1;
			open_file_cache_errors   on;
			vod_mode remote;
			vod_segment_duration 4000;
			vod_align_segments_to_key_frames on;
			vod_metadata_cache metadata_cache 512m;
			vod_response_cache response_cache 256m;
			vod_upstream_location /storage;
			vod_upstream_extra_args $args;
			vod_base_url https://$host;
			secure_token_types application/vnd.apple.mpegurl application/dash+xml text/xml;
            secure_token $args;
			
			# gzip manifests
            gzip on;
            gzip_types application/vnd.apple.mpegurl application/x-mpegURL video/f4m application/dash+xml text/xml;
		
			location /storage/ {
				internal;
				proxy_pass http://localhost:3031/;
			}

			location / {
				location ~* \.(ts|m3u8)$ {
					vod hls;
					vod_expires 1d;
					add_header Cache-Control "public";
					add_header Access-Control-Allow-Origin "*";
				}
			
				location ~* \.(mpd|m4s|mp4)$ {
					vod dash;
					vod_expires 1d;
					add_header Cache-Control "public";
					add_header Access-Control-Allow-Origin "*";
				}
			}
		}
}
```


Link to mp4:
https://storage.googleapis.com/tempvid/video.mp4

**Comment by erankor** [comment]
The MP4 files looks corrupt to me, playing it in Chrome hangs at 7:27. 
Does it actually play for you?

**Comment by idanya** [comment]
You are right. It hangs now for me too (might be because I re-transcoded several times in my tests). I'll try to revert to a version that works and update.
Thanks!
