### ISSUE TITLE
Decrypt and serve file that encrypted by openssl aes

### ISSUE THREAD

**Issue by nguyenngocphuongnb** [kaltura/nginx-vod-module#686]
Decrypt and serve file that encrypted by openssl aes
I have a video file (mp4). I had encrypted that file using openssl aes-128-ecb with a key.
Is it possible to make changes in nginx-vod-module, that will allow nginx to serve that file?
It mean nginx will read encrypted file (from local or remote) ---> decrypt ---> stream to videojs?
If it is possible to do it via nginx-vod-module or any thing i can do with nginx-vod-module source to support this scenary, please let me know.
Thank you very much!

**Comment by erankor** [comment]
nginx-vod-module has support for encryption-at-rest, but it doesn't use AES-ECB, it expects MP4 files encrypted according to the common encryption standard (which uses an AES-CTR cipher). You can create such a file using mp4box or ffmpeg.
The advantage of this is:
1. Follows an accepted standard
2. When streaming DRM-encrypted DASH/MSS, the media frames can be served as is (without the need to decrypt+encrypt)

**Comment by nguyenngocphuongnb** [comment]
Thank you! I will try your suggestion method and report the result :)

**Comment by nguyenngocphuongnb** [comment]
I used ffmpeg with aes-ctr to encrypt the mp4 file. But i cant file any document about decrypt that file using nginx_vod_module. Can you show me the example?
Note that the file was pre-encrypted (it won't be encrypted by nginx_vod_module). And i need to decrypt then streaming it to videojs using nginx_vod_module. Thank you!

**Comment by nguyenngocphuongnb** [comment]
I tried to  encrypt video with this command:
```
ffmpeg -i my-birthday.mp4 -vcodec copy -acodec copy -encryption_scheme cenc-aes-ctr -encryption_key 76a6c65c5ea762046bd749a2e632ccbb -encryption_kid a7e61c373e219033c21091fa607bf3b8 my-birthday-2.mp4
```
Then i test with this command: 
```
ffplay my-birthday-2.mp4 -decryption_key 76a6c65c5ea762046bd749a2e632ccbb
```
The player was able to play my-birthday-2.mp4. There is no error occured.

Then i tried to serve my-birthday-2.mp4 with nginx-vod-module:
Source video location: /home/phuongnb/Documents/projects/personal-project/data/my-birthday.mp4`
Encrypted video location: /home/phuongnb/Documents/projects/personal-project/data/my-birthday-2.mp4`
nginx conf:
```
    listen 127.0.0.1:80;
    server_name  personal-project.local;
    root /home/phuongnb/Documents/projects/personal-project;

    location /data/ {
        root /home/phuongnb/Documents/projects/personal-project;
        vod none;

        vod_hls_encryption_method aes-128;
        vod_secret_key "76a6c65c5ea762046bd749a2e632ccbb";
        vod_mode local;

        add_header X-Me $hostname;
        expires 100d;
    }
}

```
In browser, i access:
`http://personal-project.local/data/my-birthday.mp4` : Everything is ok, video was played
`http://personal-project.local/data/my-birthday-2.mp4` : Video player appear but nothing to play. No error in nginx log
I tried switch to hls method with this config:
```
    listen 127.0.0.1:80;
    server_name  personal-project.local;
    root /home/phuongnb/Documents/projects/personal-project;

    location /data/ {
        root /home/phuongnb/Documents/projects/personal-project;
        vod hls;

        vod_hls_encryption_method aes-128;
        vod_secret_key "76a6c65c5ea762046bd749a2e632ccbb";
        vod_mode local;

        add_header X-Me $hostname;
        expires 100d;
    }
}

```
In browser, i access:
`http://personal-project.local/data/my-birthday.mp4/index.m3u8` : Everything is ok, video was played
`http://personal-project.local/data/my-birthday-2.mp4/index.m3u8` : Video player appear with message: "Video cannot be loaded". In nginx log, there is an error:
```
2017/09/01 14:13:01 [error] 16642#0: *10 mp4_parser_parse_frames: media is encrypted and no decryption key was supplied while reading media header, client: 127.0.0.1, server: personal-project.local, request: "GET /data/my-birthday-2.mp4/seg-1-v1-a1.ts HTTP/1.1", host: "personal-project.local"

```
Can you tell me what i was wrong? What configuration should i follow? Thank you very much!

**Comment by erankor** [comment]
You have to use mapped mode in order to use encryption-at-rest. In mapped mode, nginx-vod-module gets a JSON with the MP4 file path, and in this case, the encryption key. The JSON can either be fetched from some upstream server or from a local file.
The JSON structure for a single encrypted MP4 file is:
```
{"sequences":[{"clips":[{"type":"source","path":"/path/to/video.mp4","encryptionKey":"base64-encoded-encryption-key"}]}]}
```

**Comment by erankor** [comment]
@nguyenngocphuongnb, can we close this issue?
