### ISSUE TITLE
HLS DRM sample-aes encryption

### ISSUE THREAD

**Issue by nknighter** [kaltura/nginx-vod-module#689]
Hello,
I'm trying to understand code that encrypts the data for audio(AAC) stream in HLS. But I have no idea why ENCRYPTED_BUFFER_SIZE is 256 bytes?
https://github.com/kaltura/nginx-vod-module/blob/master/vod/hls/frame_encrypt_filter.c#L69

Apple Developer documentation says that it must be an integer multiple of 16.
https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW5
What is the reason to choose 256bytes or how does browser detect the size of encrypted blocks?

Thank you!

**Comment by erankor** [comment]
256 bytes is the chunk size, it's not the encryption block size, openssl takes care of splitting its input to the cipher block size (which is 16 bytes, as you wrote). 
The reason I'm doing it is:
1. A fixed chunk size is convenient - I don't have to allocate it, and it's freed when the function returns (nginx allocations, on the other hand, are normally freed only when the request ends)
2. Calling openssl per block is significantly slower than calling it once per multiple blocks, that is the reason I don't use a chunk of 16 bytes. While chunks larger than the 256 bytes I chose can be faster, the difference is quite negligible.

**Comment by nknighter** [comment]
Thank you! It's clear now.
