### ISSUE TITLE
DRM, json in the readme file should be ordered different?

### ISSUE THREAD

**Issue by AquileaSFX** [kaltura/nginx-vod-module#691]
Hello

I want to share this information.

The order in the json matters because I use to have key first and then key_id, but the KID was being generated by the key, not the key_id, I'm telling this because, in the readme, the json reads to be key first and then key_id, but that won't work. I hope this is clear and I hope this information is useful to you.

so the correct json format is:

[{
	"pssh": [{
			"data": "CAESEGMyZjg2MTczN2NjNGYzODIaB2thbHR1cmEiCjBfbmptaWlwbXAqBVNEX0hE", 
			"uuid": "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"
		}], 
	"key_id": "YzJmODYxNzM3Y2M0ZjM4Mg==",
        "key": "GzoNU9Dfwc//Iq3/zbzMUw=="
}]

Bryan

**Comment by AquileaSFX** [comment]
I hope anyone can confirm this so I can make a pull request.

**Comment by erankor** [comment]
The order of fields in a JSON object does not matter, this applies to all JSONs parsed by this module. The module sorts the keys/values of the objects in an array that has a predefined order.
I don't understand why you think the order matters, maybe you had some caching issue?

**Comment by AquileaSFX** [comment]
@erankor 

confirmed, it was cache, thank you to be alert on issues, we can close this one, the readme is ok.
