### ISSUE TITLE
segment not found when using mapped mode, with clipFrom supplied 

### ISSUE THREAD

**Issue by whatvn** [kaltura/nginx-vod-module#692]
Hello, 
I use vod module in mapped mode with json mapping file as following: 

```json

"playlistType": "vod",
"discontinuity": true,
"durations": [
119000,
3480000
],
"sequences": [
{
"clips": [
{
"type": "source",
"clipFrom": 269972,
"path": "/data/records/2017-09-09/31-1.stream/06-00.mp4"
},
{
"type": "source",
"clipFrom": 0,
"path": "/data/records/2017-09-09/31-1.stream/07-00.mp4"
}
]
}
]
}
```
the clipFrom parameter will be dynamically generated based on request url, this worked so far except sometimes segment request will be Not Found with vod-module error: 
```
2017/09/09 10:38:03 [error] 31674#31674: *690 mp4_parser_validate_stsz_atom: number of entries 154986 smaller than last frame 1183834724 while reading media header
```
There's 1 thing i noticed:
1. When the error occurs, if directive `vod_align_segments_to_key_frames` is off, turn it to on, segmented request will be ok 
2. When the error occurs, if directive `vod_align_segments_to_key_frames` is on, turn it to off, segmented request will be ok 

The problem is it happens  randomly even when `vod_align_segments_to_key_frames` is on or off, it behaves different on different videos, with some videos, `vod_align_segments_to_key_frames on` works, with other `vod_align_segments_to_key_frames off` works. 

I dont know what to do with it. 

One thing I tried to fix when generate `clipFrom` value, when the request coming, with clipFrom parameter, for example: 20000 (milliseconds), I will read video metadata  to see if second 20 of the videos contain the keyframe or not, if yes, `clipFrom` value will be 20000, otherwise, i will read the metadata until i got keyFrame and return the second that start keyframe. But this solution failed too. 

Can you please provide a way to fix this problem, even modify vod-module is the way i will give it a try. 

Thank,

**Comment by erankor** [comment]
Please provide the below info so that I can reproduce this issue -
1. URL to the MP4 file
2. mapping JSON
3. nginx.conf
4. failed segment URL

**Comment by whatvn** [comment]
1. mp4 files: 
http://50.7.136.90/08-00.mp4
http://50.7.136.90/09-00.mp4
2. mapping json: 
```json
{
"playlistType": "vod",
"discontinuity": true,
"durations": [
2224000,
1380000
],
"sequences": [
{
"clips": [
{
"type": "source",
"clipFrom": 1380000,
"path": "/data/records/2017-09-09/28-1.stream/08-00.mp4"
},
{
"type": "source",
"clipFrom": 0,
"path": "/data/records/2017-09-09/28-1.stream/09-00.mp4"
}
]
}
]
}
```

3. Nginx.conf: 

```ini
upstream kalapi {
        server 127.0.0.1:9000;
    }

    server {
        # vod settings
        error_log logs/error.log;
        vod_mode mapped;
        vod_upstream_location /api;
        vod_upstream_extra_args "pathOnly=1";
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;

        # vod caches
        #vod_metadata_cache metadata_cache 1024m;
        #vod_response_cache response_cache 128m;
        #vod_mapping_cache mapping_cache 5m 30m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        # file handle caching / aio
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        aio on;

        root /data/records;
        location ~ ^/api/hls-mix/(.*)$ {
            internal;
            proxy_pass http://kalapi/api/$1;
            proxy_set_header Host $http_host;
        }

        location /crossdomain.xml {
           root /data/jars;
        }

      
        location / {
            vod hls;
            #vod_align_segments_to_key_frames on;
            #vod_manifest_segment_durations_mode accurate;
            #vod_bootstrap_segment_durations 3000;
            vod_segment_duration 12000;
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
    }
```
4. Fail segment url: 
http://50.7.136.90/hls-mix/28-1.stream/start/1504945380/end/1504948980/seg-1-v1-a1.ts


Keyframe is set as interval 3s, I've checked myself using some h264 libraries to confirm it's 3s keyframe. 

With the setting above, if you uncomment `vod_align_segments_to_key_frames on;` then it will be fine, but there will be another video will fail, and if that another video failed, we comment `vod_align_segments_to_key_frames on;` again, it will be ok. 

Only the first and second segment will be fail, the 3rd one to the last will be ok.

**Comment by erankor** [comment]
I reproduced the error, was caused by a bug... please try with this pull - https://github.com/kaltura/nginx-vod-module/pull/702
Thanks for reporting!

**Comment by whatvn** [comment]
Thank @erankor, i've tried your patch and it seems there's no more segment not found. But in the mean time please keep this issue opened, I have to check some more. 
Since you've got all the file you need to reproduce this bug, i changed server's ip in issue's comment. 

Thank for your fantastic work

**Comment by erankor** [comment]
I merged the pull, please close this issue once the testing completes

**Comment by whatvn** [comment]
confirm it's fixed. Close this issue.

**Comment by erankor** [comment]
Thanks for the update
