### ISSUE TITLE
Is http_gzip_module required?

### ISSUE THREAD

**Issue by j-licht** [kaltura/nginx-vod-module#693]
In your compilation description you write "The module detects these packages during configure"
But when I run configure with these options `./configure --add-module=/path/to/nginx-vod-module --without-http_gzip_module` make failed with

`-ldl -lpthread -lcrypt -lcrypto -ldl -lavcodec -lavutil -lavfilter -lavutil -lxml2 -lpcre \
-Wl,-E
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: objs/addon/mp4/mp4_parser.o: undefined reference to symbol 'uncompress'
/lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:307: objs/nginx] Error 1`

So my question is, is http_gzip_module required or is there an anther issue?

**Comment by erankor** [comment]
You're right, zlib is not detected, it is assumed to be available. I will add a feature check for it

**Comment by erankor** [comment]
Please try this pull and let me know if it resolves the issue - 
https://github.com/kaltura/nginx-vod-module/pull/699
I tried with `--without-http_gzip_module`, but for some reason it didn't reproduce the issue.

**Comment by j-licht** [comment]
OK. With this patch it works.

**Comment by erankor** [comment]
Thanks, merged
