### ISSUE TITLE
is it possible to get audio label attribute from mp4 file in local mode?

### ISSUE THREAD

**Issue by bigexxx** [kaltura/nginx-vod-module#695]
if it possible, than how? what attribute i should set using ffmpeg? we have video files with multi audio tracks with identical language codes, we need to separate it through labels

**Comment by bigexxx** [comment]
after some code research, i found out that label was set in function: mp4_parser_parse_mdhd_atom, line: 476

lang_get_native_name(context->media_info.language, &context->media_info.label);

but we can set label by setting parameter in ffmpeg to handler_name, and it would be in hdlr atom, and if we modify function mp4_parser_parse_hdlr_atom , to parse variable string at the end of atom, we can set label... now i'am try to parse variable string in c code... but i don't know c )

**Comment by erankor** [comment]
That is correct, currently there is no way to set the label from MP4 atoms. However, if you use mapped mode, it is possible to set the label in the mapping JSON.
It is quite easy to parse this field from the hdlr atom, but I'm not sure whether the correct solution is to do that, or to extract it from a udta atom. From what I see in ffmpeg code, if the metadata of the track has a `title` item, it will write it a udta atom with `name` tag - https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/movenc.c#L2927

**Comment by bigexxx** [comment]
Maybe we can add it as option, to take title from hdlr or udta , it is
really useful if I don't want use mapped mode.

Or I may fork your project and add it by myself, but can you show me
snippet of code to parse variable string at the end of hdlr

**Comment by erankor** [comment]
try this pull - https://github.com/kaltura/nginx-vod-module/pull/701

**Comment by bigexxx** [comment]
Good! but it break generated manifest file, seems the label string have a buggy null character at the end...

**Comment by erankor** [comment]
It seems there is some mess around the encoding of this field, the sample I have has <byte length><string> without a null terminator, however the spec says `name is a null-terminated string in UTF-8 characters`. 
Anyway, I updated the branch, it should now support both options, please try again.

**Comment by bigexxx** [comment]
now it working perfect! thanks!

**Comment by erankor** [comment]
Great, thanks for the update

**Comment by erankor** [comment]
An update on this - I found that many files have the name of the encoder in the hdlr atom. Naturally, we don't want to use that as the label presented to the end user. At first, I thought about creating a list of hdlr names to ignore, but then I saw that there are many. 
As a reference, here is a list of some of the names I saw:
```
AAC Audio Handler
AAC audio
AVC Video Handler
Alias Data Handler
Apple Sound Media Handler
Apple Video Media Handler
Core Media Audio
Core Media Video
DataHandler
ETI ISO Audio Media Handler
ETI ISO Video Media Handler
GPAC ISO Hint Handler
H.264/AVC video
ISO Media file produced by Google Inc.
ISO Media file produced by Google Inc. Created on: 09/12/2017.
IsoMedia File Produced by Google, 5-11-2011
MP4 Sound Media Handler
MP4 Video Media Handler
MainConcept
Mainconcept MP4 Sound Media Handler
Mainconcept MP4 Video Media Handler
Mainconcept Video Media Handler
Mono
NellyMoser Handler
SoundHandle
SoundHandler
Speex Handler
Stereo
Telestream Inc. Dib Library - Transcoder2014.7 2014.42.138600
Text
VideoHandle
VideoHandler
sound
video
```
Since I don't want to start maintaining a list of encoder names, I made this feature optional, with the default being `off` - https://github.com/kaltura/nginx-vod-module/pull/706

**Comment by bigexxx** [comment]
yes, that is right decision, it should be optional
