### ISSUE TITLE
(local mode) why ignore audio tracks which doesn't have language, and why grouping same language codes

### ISSUE THREAD

**Issue by bigexxx** [kaltura/nginx-vod-module#704]
What the reasons for ignoring audio tracks which doesn't have language codes, why we can't just set it to "und" ? and why we grouping same langage codes without (or same) label to one first audio track when generate master manifest (hls or dash)

my suggestion to mark undefined languages with "und" lang code, and if track doesn't have label, set is as default to Track 1, Track 2, etc... so players like https://shaka-player-demo.appspot.com/demo/ can show all audio tracks regardless of langs or labels

**Comment by bigexxx** [comment]
oh i see, i found in docs config option to workaround for removing dublicate bitrates
vod_dash_duplicate_bitrate_threshold 0;

close issue

**Comment by erankor** [comment]
out of curiosity - why do you want to have these audio tracks in the output if they have the same label + bitrate?

**Comment by bigexxx** [comment]
Many files with audio tracks like this:

1. format: AAC, codec: AAC LC, bitrate: 128 Kbps, channels: 2, samplingrate: 48.0 KHz, language: , title:
2. format: AAC, codec: AAC LC, bitrate: 128 Kbps, channels: 2, samplingrate: 48.0 KHz, language: , title:
3. format: AAC, codec: AAC LC, bitrate: 128 Kbps, channels: 2, samplingrate: 48.0 KHz, language: , title:
4. format: AAC, codec: AAC LC, bitrate: 128 Kbps, channels: 2, samplingrate: 48.0 KHz, language: , title:
5. format: AAC, codec: AAC LC, bitrate: 128 Kbps, channels: 2, samplingrate: 48.0 KHz, language: , title:
6. format: AAC, codec: AAC LC, bitrate: 128 Kbps, channels: 2, samplingrate: 48.0 KHz, language: , title:

this files was encoded from vod, avi or mkv formats to h264,aac,mp4 with same audio bitrate 128Kbps but missed to set language and titles, this audio tracks is different (languages, commentaries and other)

counterquestion - what the use case to exclude any of audio tracks? if video file contains that tracks it should be visible and able to switch to i guess

**Comment by erankor** [comment]
but if the title is the same, how will the end-user know which track to choose? by guessing ? :)
the reason for removing duplicates is that if you have, for example, 6 renditions of the video in 6 files, and each one is muxed with an audio track, you will get 6 audio tracks. But usually you won't have 6 different audio bitrates, in our default encoding ladder, for example, we have only 3 (64k, 96k, 128k), and there is no reason to return these duplicates to the client.

**Comment by bigexxx** [comment]
> but if the title is the same, how will the end-user know which track to choose? by guessing ? :)
yes, by blindly guessing, by switch one by one, this is better than no choice

> 6 renditions of the video in 6 files
i think this case is only applicable in mapped mode or in multi url structure (with urlset affix), but in case of only one file with multiple tracks (i may wrong but i think this is most general case) this is wrong, no one put 6 same audio tracks in one video file )

i think thereis must be better solution to choose needed audio tracks, in mapped mode i think this is very simple by adding some value with desired audio tracks, for example in following format: 
[] = video-index0:audio-index0
[] = video-index0:audio-index1
[] = video-index1:audio-index0

in urlset format by providing some GET argument maybe in the same format (if adrgument is absent return all tracks)

guessing for duplicate tracks only by matching title and difference in bitrate little bit messy i think

anyway, by switching off vod_dash_duplicate_bitrate_threshold , all is good, and in my case this module is gem! Thanks!
