### ISSUE TITLE
upstream buffer is too small to read response while reading response header from upstream

### ISSUE THREAD

**Issue by kdunee** [kaltura/nginx-vod-module#709]
Hi,

I'm using `nginx-vod-module` v1.18 in mapped mode, with json playlist generated on demand by an external service. Surprisingly, it breaks down when the playlist is long enough. For [this playlist](https://github.com/kaltura/nginx-vod-module/files/1310876/2017-09-18T12-01-17_2017-09-18T12-10-37.txt) everything works fine, while [this one](https://github.com/kaltura/nginx-vod-module/files/1310879/2017-09-18T12-01-17_2017-09-18T12-32-37.txt) causes requests to the module to fail with error `502, Bad Gateway`.

nginx logs from the failed request:

`2017/09/18 15:54:38 [alert] 29054#0: *183 upstream buffer is too small to read response while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /vod/B827EB85CBCA_video0/2017-09-18T12:00:17_2017-09-18T12:30:37.json/manifest.mpd HTTP/1.1", subrequest: "/B827EB85CBCA_video0/2017-09-18T12:00:17_2017-09-18T12:30:37.json", upstream: "http://127.0.0.1:5876/B827EB85CBCA_video /2017-09-18T12:00:17_2017-09-18T12:30:37.json", host: "localhost:8495", referrer: "http://localhost:8000/`

I can still access the json by requesting it directly, and it seems like only the `nginx-vod-module` has a problem with it. Does anyone have a clue on how to solve this issue?

**Comment by ESPNMichaelKidd** [comment]
have you looked at https://github.com/kaltura/nginx-vod-module#vod_max_mapping_response_size ?

**Comment by kdunee** [comment]
Thanks!
