### ISSUE TITLE
Subtitle refrence in non-mapped mode ? 

### ISSUE THREAD

**Issue by mdale** [kaltura/nginx-vod-module#711]
Is there any documentation on the path mapping or url structure for subtitles to be included in the manifest output ? Is packaging in subtitles only supported in mapped mode ? 

thanks,
michael

**Comment by erankor** [comment]
Hi Michael, long time :) you add the subtitles in the same way you add an mp4 bitrate, e.g. if you use urlset, it can look like this:
`http://example.com/hls/videos/,video_400.mp4,video_900.mp4,subtitles.srt,.urlset/master.m3u8`
The module identifies the file format (file extension doesn't matter), and outputs subtitles with EXT-X-MEDIA:SUBTITLE and videos with EXT-X-STREAM-INF.
Subtitles are supported for all modes, supported formats are - SRT, DFXP, WEBVTT and CAP. Styles are supported only for WEBVTT (they are passed as is)

**Comment by mdale** [comment]
works great, thanks. ... we may be adding in a library for translation for libass soon ;)

**Comment by mdale** [comment]
is there a url argument mode to change the language title or any of the other tag args? 
=SUBTITLES,GROUP-ID="subs0",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES

**Comment by erankor** [comment]
You can set the language by adding `/lang/eng`, for example, on the previous sample, it can look like this:
`http://example.com/hls/videos/,video_400.mp4,video_900.mp4,/lang/eng/subtitles.srt,.urlset/master.m3u8`
The NAME attribute will be derived from the language code, setting a different name is currently supported only for mapped mode. While it is quite easy to add a param for that (similar to `lang`) it can make ugly URLs...

**Comment by mdale** [comment]
cool thanks.

**Comment by Rezhann112** [comment]
hi anyone can help me how to add srt file from json file mapping for the clip please ?

**Comment by erankor** [comment]
replied here - https://github.com/kaltura/nginx-vod-module/issues/242#issuecomment-1791456541
