### ISSUE TITLE
vod_hls_encryption_key_uri not working as I expected

### ISSUE THREAD

**Issue by cc-brian** [kaltura/nginx-vod-module#713]
server {
listen 443 ssl http2;
server_name cdn.domain.com;
vod_mode local;
vod_align_segments_to_key_frames on;
vod_manifest_segment_durations_mode accurate;
vod_secret_key "SomeSecret$vod_filepath";
vod_hls_encryption_method aes-128;

location /vod {
        aio on;
        vod hls;
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;
        vod_base_url "https://cdn.domain.com";
        vod_segments_base_url "https://cdn.domain.com";
}

index file generates this as expected, so everything works.

#EXTM3U
#EXT-X-TARGETDURATION:13
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://cdn.domain.com/vod/filename/400.mp4/encryption.key"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1

then I add this line in the location

vod_hls_encryption_key_uri "https://key.domain.com/$vod_filepath";

then the index file generates this and does not work

#EXTM3U
#EXT-X-TARGETDURATION:13
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://key.domain.com/"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1

I was expecting it would generate this:

#EXTM3U
#EXT-X-TARGETDURATION:13
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://key.domain.com/vod/filename/400.mp4/encryption.key"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1

I must be doing something wrong here.

Please advise.

Thanks!

**Comment by erankor** [comment]
Not all variables have values in all phases of the request processing, in this case, `$vod_filepath` doesn't have any value when the m3u8 is generated. Reason is that while in this case you may have a single file, in case of playlist, for example, the m3u8 may reference multiple mp4 files, so the value is undefined.
However, it seems that in your case you want to serve the encryption key from nginx-vod-module directly, so if you will just avoid setting `vod_hls_encryption_key_uri` at all, it will probably be what you want it to.
Other than that, it seems you are setting both `vod_segments_base_url` and `vod_base_url` to the same value, there's no reason to do it, setting `vod_base_url` is enough. `vod_segments_base_url` should only be used when you want to serve the segments from domain X and the manifests/encryption keys from domain Y.

**Comment by cc-brian** [comment]
Thanks for the quick reply.

In my case, I want to serve the encryption key directly, but I'm using another domain (with cookie protection) that points back to my local server, therefore the key is protected.  I realize there's other ways to do this, but this would work well for my current setup.

Is there  a way to set that up?

**Comment by erankor** [comment]
If it's ok to serve both the encryption.key and the index.m3u8 from the protected domain (both requests are small...), then you can set `vod_segments_base_url` to the regular domain and `vod_base_url` to the protected domain.
A different approach is to capture request uri without the file name part using nginx regex location, and use the capture variable in `vod_hls_encryption_key_uri`. Something like this:
```
location ~ (/vod/.*)/[^/]+ {
    ...
    vod_hls_encryption_key_uri http://key.domain.com$1/encryption.key;
}
```

**Comment by cc-brian** [comment]
Thanks erankor!  I used your first suggestion with the base urls and it works great!

**Comment by erankor** [comment]
Glad to hear, closing this issue
