### ISSUE TITLE
Need help with Chrome Android

### ISSUE THREAD

**Issue by lassos** [kaltura/nginx-vod-module#716]
I need help with Chrome Android

In desktop environment everything is woking fine.
I have installed jsvideo player with dash and hls extension.

But on my mobile phone (samsung galaxy s8)  the local hls playback doesnt work with chrome browser,
unfortunetally there is no console log or error displayed in the server logs, also not in the remote device inspector of chrome. 

Playing an external m3u8 playlist is working on my phone. Could you please take a look at my configuration and take a look at the player site. Maybe someone has a hint for me. It's difficult to debug cause there is no errror output at the browser or server.

nginx.conf:

```
			location /vodhls/ {

			alias /tmp/vod_hls/;
			vod hls; 
												
			# vod settings
			vod_mode local;
			#vod_hls_encryption_method aes-128;
			vod_hls_absolute_master_urls off;
			vod_hls_absolute_index_urls off;

			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			
			expires 10d;

			}
```

So the player ist located here:

`https://steflaweb.dnshome.de/xampp/htdocs/kunden/bgcit/community/3-5-2017/live_vod/player.php`

PlaylistUrl:

```
https://steflaweb.dnshome.de:8090/vodhls/videos/SampleVideo_1280x720_1mb.mp4/master.m3u8
https://steflaweb.dnshome.de:8090/vodhls/videos/SampleVideo_1280x720_1mb.mp4/index.m3u8
```

**Comment by erankor** [comment]
I'm getting a certificate error on this URL, curl says it's a self-signed certificate... 
probably the device doesn't like it.

**Comment by lassos** [comment]
unbelievable, it is working perfectly without ssl setup. thanks so much.
