### ISSUE TITLE
Mapped and remote mode not working if vod is none

### ISSUE THREAD

**Issue by jojolalpin** [kaltura/nginx-vod-module#722]
Hi,

Using remotes api and storage works if vod packager is hls or dash (did not test others) but not if set to none.
Requesting /example.json , json content is just returned, not processed, so remote upstream not used.

location / {
    vod none;
    vod_mode mapped;
    vod_upstream_location /jsonapi_proxy;
    vod_remote_upstream_location /storage_proxy/;
   ...

Thanks for this great module.

**Comment by erankor** [comment]
Mapped mode is supported with vod none, maybe the request hits a different location?
If you think that is not the case, please send full nginx.conf and request url.

**Comment by jojolalpin** [comment]
Hi,

Below is my nginx config with comments about request url above locations.
The last one does not work, the json is served and not processed.

Devito.json: The path is local file : "/opt/static/videos/devito360p.m4"
Devito_remote.json : the path is relative to upstream so only "devito360p.mp4"

NGINX.CONF:

worker_processes  auto;

pid		/var/run/nginx.pid;

events {
	worker_connections  1024;
	multi_accept on;
	use epoll;
}

http {
	include	   mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
		'$status $bytes_sent $request_time "$http_referer" '
		'"$http_user_agent" "$http_x_kaltura_f5_https" $http_x_kaltura_f5_remote_addr '
		'"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
		'$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
		'"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
		'$connection ';

	access_log  /dev/stdout  main;
	error_log   stderr debug;
	
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;

	keepalive_timeout 60;
	keepalive_requests 1000;
	client_header_timeout 20;
	client_body_timeout 20;
	reset_timedout_connection on;
	send_timeout 20;

	add_header X-Me $hostname;

	gzip  on;
	gzip_types application/vnd.apple.mpegurl;
		
	# common vod settings
	vod_metadata_cache metadata_cache 512m;
	vod_mapping_cache mapping_cache 5m;
	vod_response_cache response_cache 128m;
	vod_drm_info_cache drm_cache 64m;

	# common proxy settings
	proxy_connect_timeout 5;
	proxy_send_timeout 5;
	proxy_read_timeout 5;
	
	# common file caching / aio
	open_file_cache max=100 inactive=5m;
	open_file_cache_valid 2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors on;
	aio on;
	
	
	#### JSONAPI on 80
	server {
		listen 80;
		server_name jsonapi;

		location / {
			alias /opt/static/videos/json/;
		}
	
	}

	upstream jsonapi {
		server localhost:80;
	}


	#### LOCAL VIDEOS on 8003
	server {
		listen 8003;
		server_name localstorage;

		location / {
			alias /opt/static/videos/;
		}
	}
	
	upstream localstorage {
		server localhost:8003;
	}



	#### LOCALHOST STREAMING SERVER on 8001
	server {
		listen	   8001 backlog=1024;
		server_name  localhost;

		# internal location for vod subrequests
		location /jsonapi_proxy/ {
			internal;
			proxy_pass http://jsonapi/;
			proxy_set_header Host $http_host;
		}

		# internal location for vod localstorage
		location /localstorage_proxy/ {
			internal;
			proxy_pass http://localstorage/;
			proxy_set_header Host $http_host;
		}

		

		## SIMPLE MP4 LOCAL STORAGE DISPLAY
		# http://0.0.0.0:8001/local/content/devito360p.mp4 -> 200
		location /local/content/ {
			alias /opt/static/videos/;
			autoindex on;
			
			add_header X-Me $hostname;
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			expires 100d;
		}

		
		# non-encrypted
		
		# http://0.0.0.0:8001/mapped/hls/devito.json/index.m3u8 -> OK manifest
		# hls stream, json with local file path read
		# mapped
		location /mapped/hls/ {
			vod hls;
			vod_mode mapped;
			vod_upstream_location /jsonapi_proxy/;

			add_header X-Me $hostname;
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			expires 100d;
		}


		
		# http://0.0.0.0:8001/mapped/devito.json -> ok MP4 plays
		# mapped
		location /mapped/ {
			vod none;
			vod_mode mapped;
			vod_upstream_location /jsonapi_proxy/;

			add_header X-Me $hostname;
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			expires 100d;
		}


		# http:/0.0.0.0:8001/mappedremote/hls/devito_remote.json/index.m3u8 -> ok manifest 
		# mapped & remote
		location /mappedremote/hls/ {
			vod hls;
			vod_mode mapped;
			vod_upstream_location /jsonapi_proxy;
			vod_remote_upstream_location /localstorage_proxy/;

			add_header X-Me $hostname;
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			expires 100d;
		}


		# http:/0.0.0.0:8001/mappedremote/none/devito_remote.json -> serves the json 
		# mapped & remote
		location /mappedremote/none/ {
			vod none;
			vod_mode mapped;
			vod_upstream_location /jsonapi_proxy;
			vod_remote_upstream_location /localstorage_proxy/;

			add_header X-Me $hostname;
			add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
			expires 100d;
		}


		
		# redirect server error pages to the static page /50x.html
		#
		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
			root   html;
		}
	}
}

**Comment by erankor** [comment]
I checked it, this combination is indeed not supported, the support for remote urls in mapped mode is a late addition, and did not cover progressive download.
Anyway, try this pull - https://github.com/kaltura/nginx-vod-module/pull/723
I didn't fully test it yet to make sure it doesn't break other flows (e.g. regular remote mode), but it solves this issue as far as I can tell.

**Comment by jojolalpin** [comment]
Thanks a lot, I will have a look at it.

**Comment by jojolalpin** [comment]
Hi erankor,
Everything is running fine for all locations in the config above.
Thanks !

**Comment by erankor** [comment]
Thanks for the update, I ran a few more tests and merged it
