### ISSUE TITLE
Progressive download

### ISSUE THREAD

**Issue by momkin** [kaltura/nginx-vod-module#724]
How to enable Progressive download , so the user can rewatch the video without redownloading it like youtube ? i'm using local mode

**Comment by erankor** [comment]
For progressive download use `vod none`, but note that the module simply returns the mp4 file as-is. The mp4 file has to contain its metadata before the video frames, you can use ffmpeg's qt-faststart to fix that, if needed.
The advantages of using nginx-vod-module for progressive are:
1. Same flow for all delivery types (progressive, HLS, DASH etc.), e.g. the ability to map the URL to a file (mapped mode)
2. Support for clipping - if you add, for example, /clipTo/10000/ to the URL, the module will return an mp4 file that contains a portion of the original mp4 (similar to nginx-mp4-module)

**Comment by momkin** [comment]
so there is no way to enable downloading with hls ?? because currently its enly downloads a few seconds ahead :(

**Comment by erankor** [comment]
I'm sorry, don't understand what you mean by downloading with hls. You can set one location with `vod hls` and one location with `vod none` if that is what you need.

**Comment by momkin** [comment]
what i mean is when user playes a video , the video must start downloading so even if the user network stopped he can still watch the dowloaded video like youtube and others

**Comment by erankor** [comment]
The request is still quite vague... 
Progressive download = the client downloads the mp4 file (like any other file) and plays it while it's doing it. If that is what you want, then you can enable it with `vod none`, as I wrote above. 
If what you are trying to implement is offline playback, then it can be supported with HLS/DASH as well, for example, in iOS there are functions for downloading an HLS stream for offline playback. That is not my domain, but I know it exists.

**Comment by momkin** [comment]
what i mean is simple when user watches a video he should be able to reply the video without redownlading it again exactly like progressive download 

if i use vod none, i will lose all the hls settings like AES protection right ?

**Comment by erankor** [comment]
1. Yes, there is no standard for AES in progressive download
2. Make sure you return caching headers on the HLS responses, if you do, there is a chance the browser will save the video segments. But other than that, it's up to client, you can't control it from the server.

**Comment by momkin** [comment]
how to set header cache as you said please ?

**Comment by momkin** [comment]
i found this link https://www.wowza.com/docs/how-to-control-apple-hls-client-caching-ext-x-allow-cache


is this what you meant

**Comment by erankor** [comment]
nginx-vod-module always sends `#EXT-X-ALLOW-CACHE:YES` though I don't think it matters.
No, I was referring to the Cache-Control/Expires headers, you can use nginx's `expires` directive to return those. E.g. `expires 100d` returns caching headers for 100 days.

**Comment by momkin** [comment]
thank you mate ,, can you take a look at this screenshot and tell me if it possible to make it load the full progress bar bacause if you see the screen shot its only loading about some seconds only 

https://image.ibb.co/i3N4JG/Untitled2.png

**Comment by erankor** [comment]
You can't control it from the server side, but if you have control over the player, you can probably configure its buffer size. Some players have parameters for minimum/maximum buffer size, what you want is to increase the maximum.
