### ISSUE TITLE
The player does not support playback, but VLC is playable

### ISSUE THREAD

**Issue by Tinywan** [kaltura/nginx-vod-module#740]
+ url `http://nginx:8386/stream/http/oss.ww.com/data/913.mp4/index.m3u8`
## VLC
![qq 20171123160116](https://user-images.githubusercontent.com/14959876/33163059-7fdae116-d067-11e7-9dee-ccb448c6fcb8.png)
##  player 
![qq 20171123155923](https://user-images.githubusercontent.com/14959876/33162995-39859bac-d067-11e7-85c3-e89ef0219b16.png)
+  Error code
![qq 20171123160029](https://user-images.githubusercontent.com/14959876/33163032-62431150-d067-11e7-8c44-c1ad6bbc03a1.png)

**Comment by erankor** [comment]
I'm sorry, but there isn't any helpful info in this issue.
What player are you using? if it's browser based, are there any errors in the browser console? 
In browser based players, most common errors are -
1. Trying to load an HTTP stream from an HTTPS page
2. Missing CORS headers

If that is not the case here, please provide an accessible stream URL

**Comment by Tinywan** [comment]
Hi! Glad you can answer my question.
####  nginx.conf
```bash
    server {
        listen 8386;
        # vod settings
        vod_mode remote;
        vod_upstream_location /remote;
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;

        # vod caches
        vod_metadata_cache metadata_cache 256m;
        vod_response_cache response_cache 128m;

        #file handle caching / aio
        open_file_cache max=1000 inactive=5m;
        open_file_cache_valid 2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors on;
        aio on;

        location ~ /remote/([^/]+)/([^/]+)/(.*) {
            resolver 8.8.8.8;
            internal;
            proxy_pass $2://$3?$args;
        }

        location ~* ^/stream/(.*) {
            vod hls;

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
    }
```
#### play url 

```bash
http://nginx-vod.tinywan.com:8386/stream/http/oss.tinywan.com/data/201710008/video/1509184568478.mp4/index.m3u8
```
>  1.VLC playback is normal, but very card! It's unknown for what reason?  
>  2.VideoJs play is normal too , but very card! It's unknown for what reason?  
>  3.I use [aliplayer](https://player.alicdn.com/aliplayer/index.html) and [swfobject](https://github.com/swfobject/swfobject), but can not play

**Comment by erankor** [comment]
Don't understand what you mean by 'very card'... but, a few things that I noticed about this stream:
1. Don't know if it's the connectivity between my laptop and your server or your server and the upstream server, but each 10 sec segment takes me 30 sec or more to download. Naturally, with this speed, it can't really play smoothly.
2. The key frames do not seem to be properly spaced, there is no fixed GOP size. In the first two segments I see these key frame offests - 
2.683033
5.549700
9.149700
17.483033
The first 3 key frames fall in the first segment, which means the second segment has 7 seconds before the first key frame. For good playback experience, you should force a key frame every X segments (we are using 2 seconds) and have each segment start with a key frame. You can try to enable vod_align_segments_to_key_frames, but I doubt this will be enough in this case.
3. There is a ~2.5 sec difference between the start time of the video and the audio, this may cause issues as well.

**Comment by Tinywan** [comment]
@erankor Hello there! 
Means that the use of VLC playback will be fluent (especially at the beginning will play a little and then stop), I do not know if it is not the configuration parameters inappropriate?

**Comment by erankor** [comment]
I'm sorry, but it's hard for me to understand what you write. Regarding the configuration, it looks ok to me. The aio/open_file_cache params are irrelevant for remote mode, but that is not a problem.
Maybe you should try first with an mp4 with a lower bitrate, that will at least solve the speed/buffering issue.

**Comment by Tinywan** [comment]
@erankor Thank you.

**Comment by Tinywan** [comment]
#740 After the temporary upgrade bandwidth (1M-> 5M). Play normally
