### ISSUE TITLE
How to Install/Build nginx-vod-module on Ubuntu 16.04 with nginx secure_link_module

### ISSUE THREAD

**Issue by lvillarino** [kaltura/nginx-vod-module#741]
Setup an Ubuntu 16.04, ssh to the server and run the commands
 
apt-get update
apt-get upgrade
sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev unzip mc
cd /opt/
wget http://nginx.org/download/nginx-1.13.0.tar.gz
wget https://github.com/kaltura/nginx-vod-module/archive/master.zip
tar -zxvf nginx-1.13.0.tar.gz
unzip master.zip
cd nginx-1.13.0/
./configure --with-http_ssl_module --with-http_secure_link_module --add-module=../nginx-vod-module-master  --with-file-aio --with-threads
make
make install
cd /opt
wget https://raw.github.com/JasonGiedymin/nginx-init-ubuntu/master/nginx -O /etc/init.d/nginx
chmod +x /etc/init.d/nginx
update-rc.d nginx defaults
service nginx start

**Update crossdomain.xml**
nano /usr/local/nginx/html/crossdomain.xml
from https://gist.github.com/lvillarino/235832dc897cd6c6a494cdb85b099097

**Update nginx.conf**
cp /usr/local/nginx/conf/nginx.conf /usr/local/nginx/conf/nginx.conf.original
nano /usr/local/nginx/conf/nginx.conf
from https://gist.github.com/lvillarino/c341b4cefc667dc616d64aa93538ee2d

**Upload 3 videos files to /usr/local/nginx/html**
101_1.mp4
101_2.mp4
101_3.mp4

**Test Installation**

HLS URL
http://ip_address/hls/101_1.mp4/index.m3u8
http://ip_address/hls/101_,1,2,3,.mp4.urlset/master.m3u8

DASH URL
http://ip_address/dash/101_1.mp4/manifest.mpd
http://ip_address/hls/101_,1,2,3,.mp4.urlset/manifest.mpd

MP4 URL
http://ip_address/mp4/101_1.mp4

**Comment by lvillarino** [comment]
nginx.conf comment

```
#user  nobody;
worker_processes  1;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log  logs/error.log  info;
error_log  logs/debug.log  debug;


events {
    worker_connections  1024;
}

http {
	keepalive_timeout  65;

	server {
                index index.php index.html
        
		# vod settings
		vod_mode local;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;
                

		# vod caches
		vod_metadata_cache metadata_cache 32m;
		vod_response_cache response_cache 128m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

		# file handle caching / aio
		open_file_cache          max=1000 inactive=5m;
		open_file_cache_valid    2m;
		open_file_cache_min_uses 1;
		open_file_cache_errors   on;
		aio on;
		
		location /dash/ {		
			#secure_link $arg_md5,$arg_expires;
                        #secure_link_md5 "$secure_link_expires 12345";
                        
                        #if ($secure_link = "") {
                        #        return 403;
                        #}
                        #if ($secure_link = 0) {
                        #        return 410;
                        #}
                        
                        vod dash;
                        alias /usr/local/nginx/html/;

                        vod_segment_duration 4000;
                        vod_align_segments_to_key_frames on;
                        vod_manifest_duration_policy min;
                        vod_dash_manifest_format segmenttemplate;
                        vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;

			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
                
                location /hls/  {
                        #secure_link $arg_md5,$arg_expires;
                        #secure_link_md5 "$secure_link_expires 12345";
                        
                        #if ($secure_link = "") {
                        #        return 403;
                        #}
                        #if ($secure_link = 0) {
                        #        return 410;
                        #}
                        
			vod hls;
                        alias /usr/local/nginx/html/;
                        
                        vod_secret_key "mukkaukk$vod_filepath";
			vod_hls_encryption_method aes-128;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
                
                location /mp4/ {
                        secure_link $arg_md5,$arg_expires;
                        secure_link_md5 "$secure_link_expires 12345";
        
                        if ($secure_link = "") {
                                return 403;
                        }
                        if ($secure_link = 0) {
                                return 410;
                        }
        
                        vod none;
                        alias /usr/local/nginx/html/;
                }
                
                # vod status page
		location /vod_status {
			vod_status;
			access_log off;
		}
                
	}
}

```

**Comment by erankor** [comment]
Thanks @lvillarino, I'm not sure whether there's a question here, or you just posted this a guide, but note that currently the module does not work well with nginx 1.13+, see this isssue - https://github.com/kaltura/nginx-vod-module/issues/645

**Comment by mlevkov** [comment]
the link to crossdomain.xml is not leading to crossdomain.xml but rather to the nginx.conf contents, not sure if it is intentional, but I thought it would be worth mentioning

**Comment by ithustle** [comment]
@erankor , is this a valid way to install nginx-vod-module?

**Comment by erankor** [comment]
Yes, it looks ok, but in general, our recommendation is to use one of the pre-compiled packages - https://github.com/kaltura/nginx-vod-module#installation

**Comment by ithustle** [comment]
Okay. I finished the installation but when I used url test `http://domain/mp4/video.mp4` it return `403 Forbidden` the same if I call with my file.mp3. But if use `http://domain/video.mp4` it try to download the file but with `http://domain/file.mp3` the audio plays. 

Did I something wrong? I followed this tutorial ...

**Comment by erankor** [comment]
This configuration has 'secure link' enabled, you need to sign the url for it to work. If you don't need secure link, you can just remove it from the conf.

**Comment by ithustle** [comment]
One last thing... When I tried to install follow 

> Yes, it looks ok, but in general, our recommendation is to use one of the pre-compiled packages - https://github.com/kaltura/nginx-vod-module#installation

One last thing, when I tried to install follow the way that you recommend, was asked me if I use this with `Kaltura-server` or somenthing like that ... my question is:

Is it mandatory use `nginx-vod-module` with `Kaltura-server` or not?

**Comment by erankor** [comment]
If it was mandatory, we didn't have any reason to ask :)
You don't have to use Kaltura server...

**Comment by ithustle** [comment]
That's funny. Thank you.

**Comment by ithustle** [comment]
@erankor , I finished installation following [https://github.com/kaltura/nginx-vod-module#installation](https://github.com/kaltura/nginx-vod-module#installation) but I can't access server from browser. Did I miss some part?
