### ISSUE TITLE
Issue with long videos

### ISSUE THREAD

**Issue by BzBoz** [kaltura/nginx-vod-module#745]
Hello,
 
First of all I would like to thank you for this wonderful module.
Unfortunately, there is one issue that we have not been able to fix.
We use this add-on with HLS and it works great, except for long videos (5 hours and more).
 
This is a response from our technical support
> -----------------------------------
>  I've checked the logs and there's error from HLS module: frame count exceeds the limit 1048576 while reading moov atom. Means video have too many frames, so mod can't handle it.
> I don't see any solution for this since I'n not the author of this HLS module: https://github.com/kaltura/nginx-vod-module
> You can try to contact them and maybe they have some workaround about this.                        
> -----------------------------------
 
Any help with this?
Thanks.

**Comment by erankor** [comment]
There are two cases I can think of in which you'd get this error -
1. You have `vod_manifest_segment_durations_mode accurate` in your nginx.conf - this is the most probable cause, and you can simply remove it. We don't use it for HLS and it's working fine.
2. The error is on an iframes.m3u8 request - this may require some code change to fix, but in this case, I don't it should cause playback issues - the player will probably just continue without it.

**Comment by BzBoz** [comment]
Great, this fixed the issue.
Thank you.

**Comment by erankor** [comment]
Thanks for the update
