### ISSUE TITLE
ask about default configuration & url segmentation 

### ISSUE THREAD

**Issue by fullhdman** [kaltura/nginx-vod-module#747]
hello ,
i'm trying to install this | kaltura-nginx server with default configuration ,,
now where can i push the mp4 files from local server as multi-bitrate video ?
the server ip is : 127.0.0.1
server port : 88
now i add 1.mp4 file to /opt/kaltura/nginx/static
what is the link to use it via player ?
thanks

**Comment by erankor** [comment]
See my first comment here - https://github.com/kaltura/nginx-vod-module/issues/738

**Comment by fullhdman** [comment]
Hi ,
thank you i can re-stream the video now  ,,
can i use this module for stream mp4 files with multi bit-rate links without use multiple files   ?
1.mp4     ---> multi resolution as youtube ?

**Comment by erankor** [comment]
You can encode multiple renditions in a single mp4 file (each using a separate track) and the module will return them in the output. However, that would be less efficient in terms of IO compared to using multiple files (the relevant data for each segment request will be more sparse, so the module will end up reading more unused data)
If what you meant is that the module will generate these renditions by itself, then the answer is no. Video transcoding is a heavy task, so we don't do it on-the-fly.
