### ISSUE TITLE
Can't play HLS with FlowPlayer

### ISSUE THREAD

**Issue by code5381** [kaltura/nginx-vod-module#748]
Hi,

I can't play hls stream with flowplayer.

I installed nginx-vod-module on CentOS7 with VMWare. And I'm testing on Windows.
I think everything works fine on server side.  ( I can play following url stream with VLC player. ) 

http://192.168.0.41/content/oceans,6,9,15,00k.mp4.urlset/master.m3u8
http://192.168.0.41/content/oceans600k.mp4/index.m3u8

But, I can't play video with flowplayer.

# Configuation
```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

http {
        upstream fallback {
                server 127.0.0.1:80;
        }

        server {
                # vod settings
                vod_mode local;
                vod_fallback_upstream_location /fallback;
                vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
                vod_last_modified_types *;
                vod_force_playlist_type_vod on;

                # vod caches
                vod_metadata_cache metadata_cache 512m;
                vod_response_cache response_cache 128m;

                # gzip manifests
                gzip on;
                gzip_types application/vnd.apple.mpegurl;

                # file handle caching / aio
                open_file_cache          max=1000 inactive=5m;
                open_file_cache_valid    2m;
                open_file_cache_min_uses 1;
                open_file_cache_errors   on;
                aio on;

                location ^~ /fallback/ {
                        internal;
                        proxy_pass http://fallback/;
                        proxy_set_header Host $http_host;
                }

                location /content/ {
                        root /usr/local/nginx/;
                        vod hls;
                        vod_align_segments_to_key_frames on;
                        vod_segment_duration 12000;
                        vod_hls_absolute_index_urls        off;
                        add_header Access-Control-Allow-Headers '*';
                        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                        add_header Access-Control-Allow-Origin '*';
                        expires 100d;
                }
        }
}
```

# Error Log

2017/11/30 23:41:51 [alert] 1410#1410: worker process 1500 exited on signal 11
2017/11/30 23:41:51 [alert] 1410#1410: worker process 1506 exited on signal 11
2017/11/30 23:41:52 [alert] 1410#1410: worker process 1507 exited on signal 11
2017/11/30 23:41:55 [alert] 1410#1410: worker process 1508 exited on signal 11
2017/11/30 23:41:59 [alert] 1410#1410: worker process 1509 exited on signal 11

# Access Log
![1](https://user-images.githubusercontent.com/3893958/33436579-d3a9da06-d628-11e7-9b11-40b63a348e54.jpg)

# curl http://192.168.0.41/content/oceans600k.mp4/index.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:12
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:12.000,
seg-1-v1-a1.ts
#EXTINF:12.000,
seg-2-v1-a1.ts
#EXTINF:12.000,
seg-3-v1-a1.ts
#EXTINF:10.613,
seg-4-v1-a1.ts
#EXT-X-ENDLIST
# 
# curl http://192.168.0.41/content/oceans,6,9,15,00k.mp4.urlset/master.m3u8
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3952555,RESOLUTION=960x400,FRAME-RATE=23.974,CODECS="avc1.42c01e,mp4a.40.2"
http://192.168.0.41/content/oceans600k.mp4/index-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3952555,RESOLUTION=960x400,FRAME-RATE=23.974,CODECS="avc1.42c01e,mp4a.40.2"
http://192.168.0.41/content/oceans900k.mp4/index-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3952555,RESOLUTION=960x400,FRAME-RATE=23.974,CODECS="avc1.42c01e,mp4a.40.2"
http://192.168.0.41/content/oceans1500k.mp4/index-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=154471,RESOLUTION=960x400,CODECS="avc1.42c01e",URI="http://192.168.0.41/content/oceans600k.mp4/iframes-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=154471,RESOLUTION=960x400,CODECS="avc1.42c01e",URI="http://192.168.0.41/content/oceans900k.mp4/iframes-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=154471,RESOLUTION=960x400,CODECS="avc1.42c01e",URI="http://192.168.0.41/content/oceans1500k.mp4/iframes-v1-a1.m3u8"
[root@localhost logs]#

# Chrome log when I play http://192.168.0.41/content/oceans600k.mp4/index.m3u8 with flowplayer.
![2](https://user-images.githubusercontent.com/3893958/33436768-4bb09af8-d629-11e7-95e4-d94472331b2e.jpg)

And FlowPlayer has no problem. ( I can play hls stream using other media server.)

I'm very newbie to nginx-vod-module. Please help me.

Good chance to be my hero.  :)

Thanks in advanced.

Kevin.

**Comment by jessp01** [comment]
Hi @code5381,

What Nginx version are you using? Could it be 1.13 and above?

**Comment by erankor** [comment]
As @jessp01 wrote, most probable cause is this https://github.com/kaltura/nginx-vod-module/issues/645, currently Nginx 1.13+ is not supported.

**Comment by code5381** [comment]
http://b2max.iptime.org:9090/test/playerTest/index.html

**Comment by code5381** [comment]
Thank you very much! I use v1.12.0 and everything works fine.  you guys are my here! :)

**Comment by jessp01** [comment]
Glad to hear we're good:)
