### ISSUE TITLE
Skip to segment

### ISSUE THREAD

**Issue by gstrat88** [kaltura/nginx-vod-module#760]
First of all congrats for this great product.

I produce a 2hours playlist consisting of 2min mp4s. 
Because some of them are not available I am treating them as dynamic clips, in order to produce the missing part from somewhere else.

All this works great, my only problem is that when I want to start playing the video from other time position than 0, I have to wait two times, one for the first video to be produced and another one for the part I actually want.

So can it be somehow possilbe to skip the first segment call?

My current workaround is to pass a 0.1 duration placeholder video as first in the playist so to load this as first segment. I tried lowering the duration, but it seems to cause problems.

Any other idea?

**Comment by erankor** [comment]
You mean that the player doesn't allow you to seek before it gets the first segment?
One thing you can try, if I understand the problem correctly, is to use nginx-vod's clipping feature. I recently enhanced this feature to support complex playlist (not only single mp4 playlists), so you can add to the URL, for example, `/clipFrom/10000/` and it will remove 10 sec from the beginning of the playlist. You need to make sure to use only offsets in which you have a keyframe (the beginning of a clip is probably good) otherwise it won't play well.

**Comment by gstrat88** [comment]
I still want the whole video, using clipFrom would produce a smaller video right? I just want to seek to the desired position.

What can I do to use smaller durations in my placeholder workaround?

Another approach would be to serve another 2min placeholder for the first video, and then serve the right video if we seek back to the starting position. My problem here is how would i know that this is the first time and the other is not?

**Comment by erankor** [comment]
Right, clipFrom returns a shorter video.
But I'm not sure I understand what you're trying to solve - is it to save the client's bandwidth by avoiding the extra segment request? or maybe there is some cost associated with resolving the dynamic clip, and you'd like to avoid that until it's really needed?
Either way, if the player loads the first segment before it seeks, don't think there's anything you can do about it from the server. At the end, the server returns a manifest to the player, but it's the player who decides what to download from that manifest.
Regarding "What can I do to use smaller durations in my placeholder workaround?", not sure if that's what you meant, but you can have nginx-vod-module generate smaller segments in the beginning of the stream, with the `vod_bootstrap_segment_durations` directive. So, you can, for example, have a duration of 1 sec for the first segment, and 10 sec for any other segment.

**Comment by gstrat88** [comment]
The goal is not to wait two times to see the video. One for the first segment part, and one for the part after the seek.
Placeholder solution will work, a black frame at the begining is not a big problem.

Server side approach could be:
1) Produce a unique id for each playlist.
2) Using this id, using some redis etc check if first video has been requested, if not requested serve placeholder else serve video.

I will try if player can skip to segment (althouth I dont believe this is possible).

Thanks a lot for the answers!
