### ISSUE TITLE
segment gap

### ISSUE THREAD

**Issue by samanmohamadi** [kaltura/nginx-vod-module#761]
Thank You for the great work.
using shaka player, sometimes video lags which seems to be because of the gap.
Example console log when video lag:
```
Ignoring large gap at 31.978612
Jumping forward 0.41384299999999996 seconds because of gap starting at 31.958332 and ending at 34.416666
```

but if I manually create segments with MP4Box , video play smoothly. so I think it couldn't be an encoding problem.
nginx config:
```
        vod_segment_duration 4000;
	vod dash;
	add_header Access-Control-Allow-Headers '*';
	add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
	add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
	add_header Access-Control-Allow-Origin '*';
	expires 100d;
```

Also, number of video segments in both ways is 16.

**Comment by erankor** [comment]
Please provide:
1. The stream URL
2. The corresponding MP4Box URL
3. A URL to the MP4 file

**Comment by samanmohamadi** [comment]
[nginx-vod manifest](http://balad.show/api/video/6/manifest.mpd)
[mp4 file](https://drive.google.com/open?id=1vUL3-kaDcVbuPJ3-bb2MrtSnhhk-vlKr)
unfortunately, because of conflict between kaltura-ffmpeg and gpac I couldn't install MP4Box on server so the MP4Box url doesn't available online yet.

**Comment by erankor** [comment]
Try adding `vod_align_segments_to_key_frames on`, from what I can see, fragment 5 doesn't start with a key frame. I will probably change the default to on soon, since it seems to be a recurring issue...

**Comment by samanmohamadi** [comment]
Thanks, it seems to be resolved.
