### ISSUE TITLE
Subtitle selection

### ISSUE THREAD

**Issue by s47221288** [kaltura/nginx-vod-module#763]
Hello,
 
   I've one mp4 video file and its stream is look like this 

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Game_of_Thrones_S07E0100.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Game.of.Thrones.S07E01.Dragonstone.1080p.WEB-DL.DDP5.1.x264_CpT@CtHts
    encoder         : Lavf56.25.101
  Duration: 00:59:00.37, start: 0.021333, bitrate: 5387 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1912x1072 [SAR 1:1 DAR 239:134], 5020 kb/s, 23.98 fps, 23.98 tbr, 16k tbn, 32k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(tha): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 191 kb/s
    Metadata:
      handler_name    : SoundHandler
    Stream #0:3(tha): Subtitle: dvd_subtitle (mp4s / 0x7334706D), 1920x1080, 6 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler

    My question is how can I select (tha) subtitle with first video and first audio (eng) ? My current url is : https://kh67.sai8.live/hollywood/http2/disk-b/Game_of_Thrones_S07E0100.mp4/index-v1-a1.m3u8

**Comment by erankor** [comment]
Embedded subtitles are not supported - see this issue - https://github.com/kaltura/nginx-vod-module/issues/737.
You'd have to extract the subtitles to some external file first.
