### ISSUE TITLE
How to use alternative audio tracks with HLS VOD stream by ngin-vod-module

### ISSUE THREAD

**Issue by hoangthaibinh** [kaltura/nginx-vod-module#768]
Hi everyone,
I have an isue for everyone to answer:
I have an mp4 file "cliptest" including 2 audio tracks for multi languages, one for English and another for Vietnamese. When streamming hs vod need to alternative audio between 2 languages?
When i play with link: localhost/movies/cliptest/cliptest_MB.mp4/index.m3u8
If I use the link such as:
 localhost/movies/cliptest/cliptest_MB.mp4/index-v1-a1.m3u8
 localhost/movies/cliptest/cliptest_MB.mp4/index-v1-a2.m3u8
then The player plays back from the beginning rather than playing continuously
So how to configure to meet my requirements?
Thanks alot

**Comment by erankor** [comment]
If the audio tracks are tagged with their languages in the mp4, you can just use /path/to/mp4/master.m3u8 and you will get a manifest with the two tracks

**Comment by hoangthaibinh** [comment]
Hey Erankor.
I test with link localhost/movies/cliptest/cliptest_,MB,SD,HD,SU,.mp4.urlset/master.m3u8 by VLC but it has only 1 track. Here the image
![image](https://user-images.githubusercontent.com/30927963/34336119-0ba59a5a-e987-11e7-805e-f83d3b1e1c84.png)
My configure is 
server {
        listen 80;
        listen 1936;
        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        vod_hls_force_unmuxed_segments on;
        root /var/www/html;
        access_log off;
        location ~* \.(?:m3u8|ts)$ {
            access_log logs/hls_access.log;
            error_log logs/hls_error.log warn;
            vod hls;
            vod_hls_force_unmuxed_segments on;
            vod_hls_absolute_master_urls off;
            vod_hls_absolute_index_urls off;
           #vod_hls_master_file_name_prefix playlist;
           #vod_hls_index_file_name_prefix chunklist;
           vod_align_segments_to_key_frames on;
            vod_mode local;
            vod_metadata_cache metadata_cache 512m;
#            gzip on;
#            gzip_types application/vnd.apple.mpegurl;

            expires 100d;
#            add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
            add_header Last-Modified "";
            etag off;
            add_header Access-Control-Allow-Origin "*";
Please help me, I have to change link localhost/movies/cliptest/cliptest_,MB,SD,HD,SU,.mp4.urlset/master-v1-a2.m3u8.
it's done but play video at the beginning

**Comment by erankor** [comment]
Maybe your audio tracks are not tagged, please paste the output of mediainfo on the mp4 file

**Comment by hoangthaibinh** [comment]
here my video mp4 file
![image](https://user-images.githubusercontent.com/30927963/34336420-97d0b210-e989-11e7-8744-e1543e8c70eb.png)

**Comment by erankor** [comment]
I don't know what this tool is, but I don't see any languages on the audio tracks. If the tracks are not tagged then by default the module assumes they are equivalent and does not output multiple tracks.

**Comment by hoangthaibinh** [comment]
Dear erankor,
My file is karaoke video file, i have just upload to mediafire, please check for me. And if the vod module nginx support, pls show me the link to play it include 2 tracks. Thanks you.
http://www.mediafire.com/file/eagurcsxl53ij4j/cliptest_MB.mp4

**Comment by erankor** [comment]
The audio tracks are indeed not tagged... your options are -
1. Tag the audio tracks in the MP4 with ffmpeg or some other tool
2. Pass the languages on the URL - for example, if the original URL was `http://localhost:8001/local/hls/content/cliptest_MB.mp4/master.m3u8` the modified URL would be:
`localhost:8001/local/hls/content/,tracks/v1/,tracks/a1/lang/eng/,tracks/a2/lang/spa/,cliptest_MB.mp4.urlset/master.m3u8`
3. Use mapped mode and build a JSON where each track is a sequence and is tagged with the correct language

**Comment by hoangthaibinh** [comment]
Hi erankor,
I have just taged language vietnamese audio tracks in MP4 file by ffmpeg, the attact file is https://drive.google.com/file/d/1z9d64J51GiitNRypmaVrtuhArPdBGU4n/view
![image](https://user-images.githubusercontent.com/30927963/34341243-0dacd9e6-e9c6-11e7-8bfe-38bcfd1772cd.png)

After taged audio track, i did play it by link:  
http://10.10.10.19/movies/cliptest/cliptest_MB.mp4/master.m3u8 
but it has only 1 track audio.
And i test with the link of option 2, replace by below link but it wrong
http://10.10.10.19/movies/cliptest/ ,tracks/v1/ ,tracks/a1/lang/vie/ ,tracks/a2/lang/vie/ ,cliptest_MB.mp.urlset4/master.m3u8.

Please check back me file mp4 I sent and give me the solution as required.
Thanks!

**Comment by erankor** [comment]
From the screenshot, you changed both tracks to Vietnamese... You need two different languages if you want the module to return multiple tracks. The second URL that you pasted has a `4` after the urlset, and it too has the same language twice.

**Comment by hoangthaibinh** [comment]
I changed two different languages, one english, one vietnamese. But it does not work.  Please check for me
https://drive.google.com/file/d/16fAsi1TUbON6ZDMhSe59rx6K7SJIGfg3/view?usp=sharing
Thanks

**Comment by hoangthaibinh** [comment]
Now I have 4 mp4 files for adaptivebitrate: cliptest_MB.mp4, cliptest_SD.mp4, cliptest_HD.mp4, cliptest_SU.mp4 and all of mp4 files has the same language: the first audio stream is English and the second audio stream is Vietnamese. 
Could you fix correct this below link to pass the languages (include 2 audio tracks), I tried to follow you given, but did not succeed
http://10.10.10.19/movies/cliptest/tracks/cliptest_,MB,SD,HD,SU,.mp4.urlset/master.m3u8
Thanks

**Comment by erankor** [comment]
I downloaded the latest link you provided, it still doesn't have the languages. The video track is tagged with 'English' the audio tracks are not tagged with anything -
```
# mediainfo cliptest_MB.mp4
General
Complete name                            : cliptest_MB.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 29.0 MiB
Duration                                 : 6mn 17s
Overall bit rate mode                    : Variable
Overall bit rate                         : 645 Kbps
Season                                   : 1
Part                                     : 1
Genre                                    : Action &Adventure
ContentType                              : Short Film
Tagged date                              : UTC 2017-12-26 00:22:30
Writing application                      : Lavf55.12.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 6mn 17s
Bit rate                                 : 500 Kbps
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.072
Stream size                              : 22.9 MiB (79%)
Writing library                          : x264 core 138
Encoding settings                        : ...
Language                                 : English

Audio #1
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 6mn 17s
Bit rate mode                            : Variable
Bit rate                                 : 64.0 Kbps
Maximum bit rate                         : 76.7 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 2.88 MiB (10%)

Audio #2
ID                                       : 3
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 6mn 17s
Bit rate mode                            : Variable
Bit rate                                 : 64.0 Kbps
Maximum bit rate                         : 83.0 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 2.88 MiB (10%)
```
Regarding the format for multiple files, it should be something like this (for two files) -
```http://10.10.10.19/movies/tracks/,v1/cliptest_MB,a1/lang/eng/cliptest_MB,a2/lang/spa/cliptest_MB,v1/cliptest_SD,a1/lang/eng/cliptest_SD,a2/lang/spa/cliptest_SD,.mp4.urlset/master.m3u8```

**Comment by hoangthaibinh** [comment]
OK, my problem has been resolved. Thanks for your help

**Comment by hoangthaibinh** [comment]
Hey Erankor,
Thanks for your software,
Now I'm using module vod nginx for karaoke music (2 tracks audio, one for language English, another for Vietnamese)
There is a problem that you need to answer. When I select between track 1 and track 2 takes about 300 ms. I have tried with many different Video Karaoke files, resulting in the same error. 
How to configure the module Nginx Vod to avoid latency when converting between two audio tracks.
Thank you very much,
Bình
