### ISSUE TITLE
hls segment report "failed to open segment file"

### ISSUE THREAD

**Issue by wnpllrzodiac** [kaltura/nginx-vod-module#769]
look up nginx logs/error.log
found
`[error] 27894#0: *3044 mp4_to_annexb_write: zero size packet while processing frames,`
which cause ts segement http 404 error(content length in http response header is right, but got Empty http response body)

**Comment by erankor** [comment]
This error means there is some corruption in the MP4 file - it has a zero size h264 NAL unit. Try to play the MP4 directly, specifically around the time of the failed segment. If you see the MP4 plays correctly, please provide a URL for it.

**Comment by wnpllrzodiac** [comment]
thankyou. I will provide play url later. 
Keep in touch.

**Comment by wnpllrzodiac** [comment]
confirmed the origin media file is corrupted.
