### ISSUE TITLE
vod_base_url should respect forwarded protocol / scheme

### ISSUE THREAD

**Issue by vascofg** [kaltura/nginx-vod-module#771]
According to the main README:

>- If not set, the base URL is determined as follows:
>- If the request did not contain a host header (HTTP/1.0) relative URLs will be returned
Otherwise, the base URL will be $scheme://$http_host The setting currently affects only HLS and DASH. In MSS and HDS, relative URLs are always returned.

I believe there should be a standard way to return correct playback URLs for deployments behind a reverse-proxy (respecting the **X-Forwarded-Proto** header or something similar).

For now I'm using something like this, but it seems like a bit of a hack:
```
if ($http_host != "") {
	set $base_url "$http_x_forwarded_proto://$http_host";	#respect X-Forwarded-Proto
}

if ($http_host = "") {
	set $base_url "";	# no host header - use relative urls
}
```

**Comment by erankor** [comment]
Well, I don't think it's a hack, we're doing something similar, except we have some more cases to handle + we use custom headers. While it is possible to add this logic, I don't think we should... 
For example, in your case, you are using X-Forwarded-Proto, maybe in some other deployment, there will be a need to use X-Forwarded-Host as well. The default in the code handles the simplest scenario, if anything more complex is needed - that's what nginx variables are for.
