### ISSUE TITLE
help to support get tile thumb pic

### ISSUE THREAD

**Issue by wnpllrzodiac** [kaltura/nginx-vod-module#772]
Hi, I want to implement ffmpeg title filter to get thumb pic.
I neet to decode several key frame picture from media and input to 'tile' filter to generate a grid thumb (for example 5x5, every picture token from 5x sec such as 0sec, 5sec, 10sec, 15sec, 20sec ...).

But i found that in struct frame_list_part_s in thumb_grabber.c
function thumb_grabber_truncate_frames() and thumb_grabber_process()
can ONLY got a track
`track: frame_count 188, index 0, key_count 2, total_duartion 7841, offset 294419 `
when called http://192.168.1.1:9180/thumb/xxxx.mp4/thumb-300000.jpg
code run into "meet end", make generate 5x5 thumb failed.
Please give me some advise to get more frame from mp4 demuxer.
THX.
```
#ifdef ONE_PIC
		// decode the frame
		vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
			"thumb_grabber_decode_frame(), skip_count %d", state->skip_count);
		rc = thumb_grabber_decode_frame(state, read_buffer);
		if (rc != VOD_OK)
		{
			return rc;
		}

		vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
						"pFrame->pict_type: %d, linesize %d.%d.%d", state->decoded_frame->pict_type, 
						state->decoded_frame->linesize[0], state->decoded_frame->linesize[1], state->decoded_frame->linesize[2]);

		// if the target frame was reached, write it
		if (state->skip_count <= 0)
		{
			return thumb_grabber_write_frame(state);
		}
		
		state->skip_count--;
        vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
						"skip_count %d", state->skip_count);

		// move to the next frame
		state->cur_frame++;
		state->frame_started = FALSE;
#else
		int64_t pts = state->dts + state->cur_frame->pts_delay;
		vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
					"pts %d, dts %d, delay %d", pts, state->dts, state->cur_frame->pts_delay);

		if (state->cur_frame->key_frame)
		{
			// decode the frame
			vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
				"thumb_grabber_decode_frame(), skip_count %d", state->skip_count);
			rc = thumb_grabber_decode_frame(state, read_buffer);
			if (rc != VOD_OK)
			{
				return rc;
			}

			if (state->missing_frames > 0)
			{
				rc = thumb_grabber_decode_flush(state);
				if (rc != VOD_OK)
				{
					return rc;
				}
			}

			if (!state->has_frame)
			{
				vod_log_error(VOD_LOG_ERR, state->request_context->log, 0,
					"thumb_grabber_write_frame: no frames were decoded");
				return VOD_UNEXPECTED;
			}

			vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
				"pFrame->pict_type: %d, linesize %d.%d.%d", state->decoded_frame->pict_type,
				state->decoded_frame->linesize[0], state->decoded_frame->linesize[1], state->decoded_frame->linesize[2]);
	        rc = thumb_grabber_filter_frame(buffersrc_ctx, buffersink_ctx, state->decoded_frame, state->decoded_frame, 
	        	state->request_context->log);
			if (rc == 0)
			{
				return thumb_grabber_write_frame(state);
			}
			else if (rc != AVERROR(EAGAIN))
			{
				vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
					"thumb_grabber_filter_frame() error: %d", rc);
				return VOD_UNEXPECTED;
			}
		}

		state->dts += state->cur_frame->duration;

		// move to the next frame
		state->cur_frame++;
		//state->frame_started = FALSE;

		input_frame_t *last_frame = state->cur_frame_part.last_frame;
		if (state->cur_frame >= last_frame)
		{
			if (state->cur_frame_part.next == NULL)
			{
				vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
					"meet end");
				return VOD_UNEXPECTED;
			}
			
			state->cur_frame_part = *state->cur_frame_part.next;
			state->cur_frame = state->cur_frame_part.first_frame;

			vod_log_error(VOD_LOG_ERR, state->request_context->log, 0, 
					"jump to next part");
		}
#endif
```

**Comment by wnpllrzodiac** [comment]
[](https://iloveyaya.ga:9443/test/tmp/out.jpg)

**Comment by erankor** [comment]
I didn't quite understand this "But i found that in struct frame_list_part_s in thumb_grabber.c
function thumb_grabber_truncate_frames() and thumb_grabber_process()
can ONLY got a track"... but in general, the code is built to generate one frame per request. If in your case, the frames will always be close in time, maybe you can skip thumb_grabber_truncate_frames (which leaves only the GOP of the requested offset) and increase vod_gop_look_behind + vod_gop_look_ahead. I didn't try, but this should make the module load more frames around the requested time.
If the frames can be far apart, this is more problematic, as you will need to increase these parameters significantly, and it can be inefficient.

**Comment by wnpllrzodiac** [comment]
thank you.I will try as your guide.

**Comment by wnpllrzodiac** [comment]
one more question
from log below, i see thumb_grabber_process() called TWICE and thumb_grabber_decode_frame()
called ONLY ONCE, why nginx call xxx_process_function twice in one http request?
```
2018/01/05 14:21:03 [error] 46266#0: *71 thumb_grabber_process() while processing frames, client: 10.102.26.124, server: localhost, request: "GET /thumb/town.mp4/thumb-240000-w150-h100.jpg HTTP/1.1", host: "192.168.23.71:9180"
2018/01/05 14:21:03 [error] 46266#0: *71 thumb_grabber_process() while processing frames, client: 10.102.26.124, server: localhost, request: "GET /thumb/town.mp4/thumb-240000-w150-h100.jpg HTTP/1.1", host: "192.168.23.71:9180"
2018/01/05 14:21:03 [error] 46266#0: *71 thumb_grabber_decode_frame(), skip_count 0 while processing frames, client: 10.102.26.124, server: localhost, request: "GET /thumb/town.mp4/thumb-240000-w150-h100.jpg HTTP/1.1", host: "192.168.23.71:9180"
```

**Comment by erankor** [comment]
It's because the module is asynchronous... what happens is:
1. The first call to thumb_grabber_process tries to read some data from the first frame
2. Since this is the first time, the read cache is empty, and the request can't be completed. The requested read-offset is saved in the cache, and the function returns NGX_AGAIN to indicate that more data is needed
3. The main code of the module performs the read request, and when it completes, it calls the process function again
4. This time the cache is full, so the frame can be decoded
Note that this can repeat more than once, if the read buffer is small/the frames are large.

**Comment by wnpllrzodiac** [comment]
so good explanation. I am a nginx module developer rookie. Thankyou sincerely.
