### ISSUE TITLE
HLS base url segments 409 Conflict

### ISSUE THREAD

**Issue by surya432** [kaltura/nginx-vod-module#773]
hello, change base url segment with pull cnd zone with respond  409 Conflict
My server.conf
`location /hls/ {
                        alias /home/customer/drive/video/;
                        vod hls;
                        vod_bootstrap_segment_durations 2000;
                        vod_bootstrap_segment_durations 2000;
                        vod_bootstrap_segment_durations 2000;
                        vod_bootstrap_segment_durations 4000;
                        include /opt/kaltura/nginx/conf/cors.conf;
                        vod_segments_base_url http://abahaaj;
                }`
![image](https://user-images.githubusercontent.com/30190408/34646925-19b18224-f3a7-11e7-8f6e-dabb4a96c25f.png)

**Comment by erankor** [comment]
The module does not use this status, and nginx uses it only in the dav module, which is not relevant here either. So, I think it's coming from somewhere else, maybe CDN (from the screenshot it seems the requests hit some CDN first)

**Comment by surya432** [comment]
thanks for lot..
SOLVED..
