### ISSUE TITLE
Problem with Dolby audio AC3 codec by vod module

### ISSUE THREAD

**Issue by hoangthaibinh** [kaltura/nginx-vod-module#775]
Hello,
I tried the video file using dolby ac3 codec, but the result was only the picture without sound. So does nginx module support?
This link i've tested bellow:
https://drive.google.com/file/d/1iFVF-U3uNdF7QfGLcJtxoJLUEYZBxFqG/view?usp=sharing

Thanks you!

**Comment by erankor** [comment]
On which browser/device did you test?

**Comment by hoangthaibinh** [comment]
I test with VLC and IE Edge on PC

**Comment by erankor** [comment]
Which player did you use on Edge? Can you send the stream URL?
