### ISSUE TITLE
Module fails with 502 when loading Google Cloud Storage signed URLs

### ISSUE THREAD

**Issue by fsouza** [kaltura/nginx-vod-module#776]
We're trying to implement access to private GCS resources without proxying through yet another service, so we have a service that generates the JSON expected by nginx-vod-module with the paths signed as expected by GCS.

It seems like nginx is tampering with the query string parameters before sending the request to cloud storage. This is what the JSON looks like:

```json
{
  "sequences": [
    {
      "clips": [
        {
          "type": "source",
          "path": "/video-media/2018/01/09/75125_1_10calif-mudslides_wg_1080p.mp4?Expires=1518725711&GoogleAccessId=gcs-media-factory%40nyt-video-prd.iam.gserviceaccount.com&Signature=Xn7udpoAtdhu2SpkLklSBYLw7eMyKhcGhDPGDsZz53fGswrbJ8EQANKI%2BHLwBMCdnoaV0f%2FYdA9FOCr%2BU2wSLPY2FBMYek0zzW%2FNNGDZVNAZ0uwEXICoMEoY0Hu9j06XxC9aUDqUoASc7PwtzK8FrjazHu68C7HzIpMFZslPzrG6MiDWT3YPfsM5zubW3IIG10zK1YJyR%2FKxcu3QWHv56X%2B2P8p70piZ59ru9X7cO35boHUIfmfNhP%2Bf15t1k2SidKljZraGCECajz%2BvSUQ6OqYqLX6IMbZE7hH67LvP8%2BU6I48%2FbraUhPJfIrBaYAsn2TZmWcsVc6Sa0PKfHLsKLg%3D%3D"
        }
      ]
    },
    {
      "clips": [
        {
          "type": "source",
          "path": "/video-media/2018/01/09/75125_1_10calif-mudslides_wg_240p.mp4?Expires=1518725711&GoogleAccessId=gcs-media-factory%40nyt-video-prd.iam.gserviceaccount.com&Signature=ite3K%2BLm3C6sEpbZnChiBKELtHgUjDcMR5fy3ojKBNyN0%2FWNDH27QCkCv2kJdCBfBs7gfjxfMkRoCdAU%2B0ozww%2BAn5a0Q%2BF9LoLND6VoOUcD9Tkh9%2FjTS1JWYVQ%2FA%2BFMgVsE0yoQFWW3Q0d5Bj8T3Z02tsgjPZnfVCaiQ0BWU1SDi4pwZNVE7IuGLtguJd5oCwHrxS6lSgdjcWhhuJRyTKaWzoh9Mbk6ogoeu3GynfubdA3b6lu9NvQRoi99QlMNdY%2BaiIxZngbGZAYjYpygpk90Xt6GNphGP4dSsLTajoY6QG3eQt84A7RJSjo1By5%2FKTWM7o8lPZZbqCK6m5LsaA%3D%3D"
        }
      ]
    },
    {
      "clips": [
        {
          "type": "source",
          "path": "/video-media/2018/01/09/75125_1_10calif-mudslides_wg_360p.mp4?Expires=1518725711&GoogleAccessId=gcs-media-factory%40nyt-video-prd.iam.gserviceaccount.com&Signature=IMLOPnuS6rkkMmo7Yhjy2vHSN7aLs7QQTx2ERE6SHREd%2BHT9DlUdZ9L1QL9S3U80FZn0LCYYvRy%2BeKUjJgAE4rnevh0Aj38BqrtTbrB8fSmeDSBawInvysalYqADuJ04%2BCSj6Fn1CRW%2B0pqukPPrMZQGhqb434e%2F0yrYwk%2B%2FW1r3wCPfYHXMmzbZqh0dpICE3ms6zZrXtFCI2XdaQ6e4C1JsSqEoORAZloNDIJAHVG%2BpeviHSNxEyqeOf4iDwsiD%2FZB3VdQz1eJOr3FXbgH1Go2d7Kf6Z0XIr%2FRbjYvtyn4yeXROQNgPkPUYB4gecANnXGUnSHJk5ph1n8ZduQ14EQ%3D%3D"
        }
      ]
    },
    {
      "clips": [
        {
          "type": "source",
          "path": "/video-media/2018/01/09/75125_1_10calif-mudslides_wg_480p.mp4?Expires=1518725711&GoogleAccessId=gcs-media-factory%40nyt-video-prd.iam.gserviceaccount.com&Signature=EYL29E17Q8pQVXtwB%2BOHqoZulbm2VWmvRTpiy9JVA%2F8Kz89dqQiGd%2F31Wju6%2FCh0SgI2F3pKrR4nqZw0rfW1KnPYbQZeKdssOCYSpJj7XSGrAYmvhot53zZP8jiO5HJ%2FvWuYHefE%2BT925t1RD61QQ0z0NNIUh9R7DHO%2FefUixEm4dmwHED0b2HImPbDloXigMTpyJLipQ1%2Byb3vEGdhBB6LHY0h%2FQkpbq35wNGQ0BdtssAxQzYU9U5Iw1wRmSR3Z5KwutFHhxRTqbZYPx7UM0ouddLlUEzen%2BASQtd0CF7YelDTdLfRW2Mlazjez5i%2FySgZ44E9nfbV9krX4ANHkTQ%3D%3D"
        }
      ]
    },
    {
      "clips": [
        {
          "type": "source",
          "path": "/video-media/2018/01/09/75125_1_10calif-mudslides_wg_720p.mp4?Expires=1518725711&GoogleAccessId=gcs-media-factory%40nyt-video-prd.iam.gserviceaccount.com&Signature=eaMjHsxsrMomY9qh2oGOV%2B1g07uZI7gr35buQ4eGhDi7A2ieTHguzXdZw%2FamU4mh96744fOOWjqBoTjs25JEQ%2Fv38drrl4gNFZazj%2BO%2BT5CXBSNnh%2FqL5zmdt8Yy1Y3Gm5FAW1jCTYDFGUYLTmZ9YjpHfpk%2F9XhAa6u8pqOGPHmUhQm1dY9eRpeQc4LS6r3QzqB732dxGnYJ9TsUZx7eMAw0HZ9ROo6u2hPx%2BloPmD7VyP8l4015SMRVmbAVcuycRpBPxhzzMDxo%2F6W7Oz8R55Y8lBpvwA2Ia0cqD%2BjFN3TNTParypOe3dQvynrLWK8XCXp8txf4C9Fuw8%2BvYt%2FCTg%3D%3D"
        }
      ]
    },
    {
      "clips": [
        {
          "type": "source",
          "path": "/video-media/captions/75125_1_10calif-mudslides_wg_240p_095cf5d6-0a97-43bf-5db7-b09718785d20.vtt?Expires=1518725711&GoogleAccessId=gcs-media-factory%40nyt-video-prd.iam.gserviceaccount.com&Signature=aPEPyLltRXXORMHoWtRKkITsvTH1na2J7q9XJDmMRywg9dKtdeIE3otyl9bc0QpZisgVLkVeaL9mqFgB2HwM%2BeVg1bVajhMRDVAVB7e9Eb%2F8ir3veI%2Bbr5hp2tKU%2FiWJxiEDZjqA1MhYxAL06C59rr4ckyQciNtclXSUf%2B%2Bh%2BaGREjikabqjXGwv1yHO1MNRJK%2Bthr%2F4910t78JoGYG9%2B%2FOV1UTKq8s7qj7Os4rJMeA3XrHow9PZ1oYmPxz9ZT3xaHRX92gTgYfdhwcg32PMqytIjve3s9mN%2BwESAHFLbuB5kJSRFSFEVutErdMyEvGNJ6RYO2z5EYpVmM8KU0U%2B3Q%3D%3D"
        }
      ]
    }
  ]
}
```

I created a reproducer repo, in case anyone wants to take a look: https://github.com/fsouza/nginx-vod-signed-issue

It looks like Google is returning a 404 when the module tries to access the URL, but it works when I access ``localhost:3030/<GCS-path-with-querystring>`` manually. I couldn't find a way to debug which URL exactly the module is trying to access.

Please let me know if more info is needed!

**Note:** since signed URLs have an expiration date, the example I'm providing is only gonna work for 30 days, but I can update the example at any time!

**Comment by erankor** [comment]
That is correct, this is not supported. 
Two options I can think of - 
1. Use vod_upstream_extra_args - this configuration parameter lets you set the args (=query string) for upstream requests. Since you have a different token per file, you will have to somehow pass it in the JSON, you can use the sequence id for that - add an id field in the level of clips with the token. Then set vod_upstream_extra_args to `$vod_sequence_id`. However, looking at the code, there are two issues with this solution -
  a. I don't think $vod_sequence_id will evaluate correctly in this context
  b. The upstream extra args are cached, so you will get the same value for all URLs
both issues can be solved easily, if you want to try this approach, I can create a pull for you. 
2. Write an external module similar to ngx_aws_auth - the code can probably be copied and just have the token generation part modified. IMHO this is a better solution since it doesn't require the use of JSON and may be helpful for other people using GCS.

**Comment by fsouza** [comment]
Hey @erankor, thanks for the info!

Since GCS support AWS authentication, ngx_aws_auth would probably work (with the limitation that you can't use service account credentials in this case).

I'll give this a shot! :)

**Comment by erankor** [comment]
Great, if it doesn't work for you, check out this issue - https://github.com/kaltura/nginx-vod-module/issues/717
don't know if this change was merged to ngx_aws_auth or not
