### ISSUE TITLE
Struggling to play multiple FairPlay encrypted HLS asset in mapped mode configuration

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#778]
HI Eran, 

We are able to check playback of fairplay encrypted content with your module, but struggling to play multiple content with same configuration file. 

Nginx Configuration for HLS part is below 

location ~ ^/hls/([^-]+)-.* {
      	    vod hls;
	    vod_mode mapped;
	    vod_segment_duration 4000;
	    vod_align_segments_to_key_frames on;
	    vod_max_mapping_response_size 64k;
	    vod_upstream_location /kalapi_proxy/;
	    vod_media_set_map_uri hls/$1.json;
            
            vod_drm_enabled on;
            vod_drm_upstream_location /kalapi_proxy/;
            vod_upstream_extra_args "pathOnly=1";
            vod_drm_request_uri hls/$1.js;
            vod_hls_encryption_method sample-aes;
            vod_hls_encryption_key_uri "skd://yJMaebnWNU2VylNldmVyVXJsIR0vLzEwLcDjoiaHoj";
	    
     	

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;

	}

For each asset the "vod_hls_encryption_key_uri" will differ. So we are struggling to playback multiple asset. 

Can you help us to overcome this issue

**Comment by erankor** [comment]
This directive supports nginx variables, you can use them to pull the uri from the URL or from the mapping JSON (using `$vod_sequence_id`). 
Check out the sample in the readme - https://github.com/kaltura/nginx-vod-module/#sample-configurations, it captures the entryId parameter from the request URI and puts it in the encryption key URI.

**Comment by Natarajan92** [comment]
Hi Eran, 

Thanks for your explanation and idea to use "$vod_sequence_id" . It worked as expected in mapped mode.
