### ISSUE TITLE
MKV DASH manifest generation fails

### ISSUE THREAD

**Issue by lorenz** [kaltura/nginx-vod-module#780]
I enabled the experimental MKV support in nginx-vod-module, but I can't seem to get it to play any MKVs. The request to the mpd manifest fails with 
```
2018/01/21 03:46:18 [error] 7#7: *19 mkv_prepare_read_frames_request: read size 71483808420 exceeds the limit 16777216 while reading media header, client: 192.168.3.5, server: localhost, request: "HEAD /dash/test.mkv/manifest.mpd HTTP/1.1", host: "192.168.3.1:3030"
```
The request is obviously far too large (71GiB, the size of the whole MKV). I can't pinpoint where that value comes from though, probably something goes wrong when parsing metadata.

**Comment by erankor** [comment]
Please send a link to the MKV file, if you have a smaller one that shows the same behavior, that would be better

**Comment by erankor** [comment]
Another thought - any chance you have vod_manifest_segment_durations_mode set to accurate? please send you nginx conf

**Comment by lorenz** [comment]
You were right, I had set `vod_manifest_segment_durations_mode` to accurate (I copy/pasted the NYT config for testing). After removing that I hit (at least on the 71GiB file) `ebml_read_size: size 1733509 greater than the remaining stream bytes 212 while reading media header`.

On a smaller file I first hit `mkv_prepare_read_frames_request: read size 25127000 exceeds the limit 16777216` after the manifest was successfully generated, I therefore increased `vod_max_frames_size` to 128m, which caused this: `mkv_prepare_read_frames_request: read size 31036603 exceeds the limit 16777216`.

**Comment by erankor** [comment]
Please send URLs to a few sample files. 
In general, MKV support is low priority for us, if there is a simple fix for these issues, I'll push it, but if it's more complex, I may not have the time to devote to this. We initially added MKV in order to support VP9 codec, however, since ffmpeg now supports packaging VP9 within MP4, it became less important for us. That's the reason the feature is still in 'experimental' status...

**Comment by U-siro** [comment]
https://stream.oganime.tr4.win/blend_s03.mkv/manifest.mpd

**Comment by erankor** [comment]
I meant a URL to the MKV file, so that I can download it and reproduce the issue
