### ISSUE TITLE
How can I custom quality label of ABR videos?

### ISSUE THREAD

**Issue by zikoops** [kaltura/nginx-vod-module#781]
Hello, thanks for your great module!

is there a way to change quality label of ABR videos?  i'm now seeing your module is automatic getting quality from resolution of files but some videos have a strange resolution, e.g: 1920x808 or 720x366 so it will be showed on change quality selection of players as 808p instead of 1080p or 366p instead of 360p, that's quite strange for most of users who have not much knowledge about video.

**Comment by erankor** [comment]
Afaik, there is no attribute in HLS for setting the label of the video renditions. If what you meant is that the module will report a wrong resolution, I don't think this is a good idea. 
Devices may use this value for purposes other than the 'bitrate selection UI'.  This is what the spec says about this attribute - 
```
      RESOLUTION
      The value is a decimal-resolution describing the optimal pixel
      resolution at which to display all the video in the Variant
      Stream.
```
