### ISSUE TITLE
Multifolder same video filename?

### ISSUE THREAD

**Issue by sajkec** [kaltura/nginx-vod-module#782]
I'm trying to setup this module to support existing folder structure which uses multifolder structure but with same filename. Something like:
1080p: http://localhost/A/video.mp4
720p: http://localhost/B/video.mp4
480p: http://localhost/C/video.mp4

The structure of a multi URL should be: 
`http://<domain>/<location>/<prefix>,<middle1>,<middle2>,<middle3>,<postfix>.urlset/<filename>`

The main issue is see here is the **/** between the foldername (A) and filename (video.mp4). Is this something that we can solve with regular expressions, without complicating with ifs  (#143) or mapped mode? The folders are only A-Z.

**Comment by erankor** [comment]
There is no problem to use multi URL for this, the variable parts of the multi URL don't have to be only on the file name.
So, for your example above, you can use - http://localhost/,A,B,C,/video.mp4.urlset/master.m3u8

**Comment by sajkec** [comment]
Work perfectly, looks like i had a typo in my urls...
