### ISSUE TITLE
How to load JSON file to play Continuous live

### ISSUE THREAD

**Issue by kolevgeorgie** [kaltura/nginx-vod-module#785]
After successfully building a nginx with vod-module and experimenting with playing HLS in single and multi bitrate I  wanted to create a continuous live stream with pre-defined mp4 files and followed the json example but couldn't find the answer on how to use it to generate a m3u8 url and play it. Any suggestions?

To add some information: I have followed the information from other issues and created a directory (called webtv) and added this to the config file:

```
        location /webtv/ {
                vod hls; 
}
```

Called the file 1.json and added the following:
```
{
        "playlistType": "live",
        "discontinuity": false,
        "segmentBaseTime": 1451904060000,
        "firstClipTime": 1451917506000,
        "durations": [13000, 83000],
        "sequences": [
                {
                        "clips": [
                                {
                                        "type": "source",
                                        "path": "/opt/nginx_vod/html/uploaded/1_1.mp4"
                                },
                                {
                                        "type": "source",
                                        "path": "/opt/nginx_vod/html/uploaded/1_2.mp4"
                                }
                        ]
                }
        ]
}
```

Double checked, the files are there and use the same codec.

Then tried to open the following url: http://host/webtv/1.json/index.m3u8 and get a 404 Not Found. Opened the error log to find this:

`2018/01/29 15:52:02 [error] 1632#0: *12 ngx_http_vod_identify_format: failed to identify the file format /opt/nginx_vod/html/webtv/1.json while reading media header, client: 192.168.152.1, server: 192.168.152.132, request: "GET /webtv/1.json/index.m3u8 HTTP/1.1", host: "192.168.152.132"`

**Comment by kolevgeorgie** [comment]
Thank you for the detailed answer. Lets say that I edit the playlist.php file to point to the correct path to MP4 files and ffprobe. Then I add it to a folder /html/ and update the nginx.conf file with upstream kalapi pointing to the same address as the nginx-vod server? Then how do I request m3u8 url which for that stream?

**Comment by erankor** [comment]
Let's say you have this location -
```
location /hls/ {
  vod hls;
  vod_mode mapped;
  vod_upstream_location /kalapi;
}
```
If you hit `http://yourdomain.com/hls/some/path.json/master.m3u8` nginx-vod-module will perform an internal subrequest to `/kalapi/hls/some/path.json` (it adds vod_upstream_location as prefix, and removes the file name of the URL). 
You need to arrange it so that this URI will return the correct json.

**Comment by kolevgeorgie** [comment]
Excuse me if I can't follow everything, here is where I got to:

I have used the mapped-configuration sample and added the following location: 

```
location /hls/ {
  vod hls;
  vod_mode mapped;
  root /opt/nginx_vod/html;
  vod_upstream_location /kalapi;
}
```

It's good to mention that I have plalist.php file in html folder.
I have also commented:

```
#               location ^~ /fallback/ {
#                       internal;
#                       proxy_pass http://fallback/;
#                       proxy_set_header Host $http_host;
#               }

#       upstream fallback {
#               server fallback.kaltura.com:80;
#       }
```
And changed the address for upstream kalapi to localhost:80 and configured the nginx to work with php.

Then I opened a web browser and hit http://host/hls/webtv/test.json/master.m3u8 - 502 Bad Gateway
(webtv folder with test.json files are presented in /opt/nginx_vod/html/)

**Comment by erankor** [comment]
Did you configure a location that will execute the PHP?
Also setting root + vod_upstream_location on the same location doesn't make sense, because vod_stream_location implies that nginx vod module should perform a subrequest to get the JSON, while root is used for loading local files.
You can, for testing purposes, remove the `internal` from the kalapi location, this will enable you to query this location directly. Then, you should arrange it so that /kalapi/hls/webtv/test.json returns a valid JSON created by the php script. Once you get there, /hls/webtv/test.json/master.m3u8 should work fine.
Lastly, if you get an error (such as the 502 you pasted), look at the error log, you should have an informative message there.

**Comment by kolevgeorgie** [comment]
Lets say I put playlist.php on a Server2:
 Which URL would I need to access at Server1 (where nginx-vod is installed) to get hls stream based on json generated by playlist.php ?

**Comment by kolevgeorgie** [comment]
Follow up:

I've tried the method which you recommended by removing the internal from the kalapi location and hit server/hls/novo.json/master.m3u8 and the result is 404, here is the error log:

`2018/02/04 19:19:20 [error] 17732#0: *29 ngx_http_vod_identify_format: failed to identify the file format /opt/media/novo.json while reading media header, client: 192.168.152.1, server: home, request: "GET /hls/novo.json/master.m3u8 HTTP/1.1", host: "192.168.152.132:88"`

When I try to hit /hls/novo.json i get the following error:
`2018/02/04 19:29:22 [error] 17735#0: *30 ngx_http_vod_hls_parse_uri_file_name: unidentified request, client: 192.168.152.1, server: home, request: "GET /hls/novo.json HTTP/1.1", host: "192.168.152.132:88"`

**Comment by erankor** [comment]
What I wrote was to query /kalapi/hls... directly, not /hls (you don't need to remove the internal for /hls...). Regarding the first error, I already referred to it in my first comment - you probably didn't set the mode to mapped.

**Comment by kolevgeorgie** [comment]
Many thanks, playing the stream from static json worked!
