### ISSUE TITLE
MSS does not support track language(s)

### ISSUE THREAD

**Issue by tim-lansen** [kaltura/nginx-vod-module#786]
It seems that MSS lacks language support.

As shown here
https://msdn.microsoft.com/en-us/library/ee230810(v=vs.90).aspx
https://msdn.microsoft.com/en-us/library/ee673441(v=vs.90).aspx
microsoft place language code in server manifest as audio source property, and also use it in trackName:
`<audio src="audio-128k-deu.isma"  systemBitrate="128000" systemLanguage="de" >`
`<param name="trackID" value="1" valuetype="data"/>`
`<param name="trackName" value="audio-de" valuetype="data"/>`
`</audio>`
so it appears in StreamIndex element as Language property, and in URL pattern of client manifest:
`<StreamIndex Type="audio" Language="de" QualityLevels="1" Chunks="38" Url="QualityLevels({bitrate})/Fragments(audio-de={start time})">`

It would be great to support languages in MSS this way.

**Comment by erankor** [comment]
It is easy to add this property, but there is no mention of it in the latest spec - https://msdn.microsoft.com/en-us/library/ff469518.aspx. 
That is the reason I didn't include it in the first place...
Did you test with some MSS players and saw that they use this property?

**Comment by tim-lansen** [comment]
@erankor yes, we have been using this approach in production.
Most of players are able enumerate tracks by Language, and some of them can choose track by index (speaking about smart TVs and STB), and all of them use StreamIndex's URL pattern to generate requests.
To keep supporting hypothetical client that ignores URL property we can keep default pattern for the first mentioned audio/video/textstream track, and append language code starting from the second track.

**Comment by erankor** [comment]
@tim-lansen, check out this pull - https://github.com/kaltura/nginx-vod-module/pull/787

**Comment by tim-lansen** [comment]
Thank you @erankor, i see Language property appeared in StreamIndex.
But this still does not let server differentiate tracks with different languages: client will generate equivalent requests for all tracks using URL pattern (if tracks have same bitrate and timeline).

Microsoft's compromise suggestion is to use lang code in track's name in server manifest
_\<param name="trackName" value="**audio-de**" valuetype="data"/\>_
and in URL pattern in client manifest
_Url="QualityLevels({bitrate})/Fragments(**audio-de**={start time})_
(it is not necessarily the language code, the only requirement is that **trackName**s for different tracks must be different: audio1, xzcase, blabla...)

I suggest to add a new optional property **'trackName'** to sequence in layout JSON, map Fragments' param name to it (using **video/audio/text** by default), and oblige mss packager to select sequence by this name.
This solution will not break currently published content and workflows.

**Comment by erankor** [comment]
nginx-vod-module uses some bits of the bitrate in order to encode the track id (my assumption was that it's not important to have a very accurate bitrate). So, I don't think there is a real problem here - the bitrate reported in the manifest will always be different for different tracks.

**Comment by tim-lansen** [comment]
oh, i see, thanx =)

**Comment by erankor** [comment]
@tim-lansen, is it working for you? should I merge this change?

**Comment by tim-lansen** [comment]
@erankor yes )

**Comment by erankor** [comment]
merged, thanks
