### ISSUE TITLE
Noob question about regex in location

### ISSUE THREAD

**Issue by aldeluis** [kaltura/nginx-vod-module#788]
This is a noob question...

I'm trying to make this module work but doesn't understand why the first location works but the second one doesn't work:

```
location /hls/ {
  alias /var/www/videos/;
  vod hls;
}

location ~ /hls2/ {                                                                                                                              
  alias /var/www/videos/;
  vod hls;
}
```

Anyone knows? How can I debug this kind of troubles? Thank you!!

**Comment by xXxSPYxXx** [comment]
Add ~ to first location?

**Comment by erankor** [comment]
Check the nginx error log

**Comment by aldeluis** [comment]
Thank you for giving me a hand. I'm trying to understand it. This is my error log with debug enabled:

[log.txt](https://github.com/kaltura/nginx-vod-module/files/1694845/log.txt)

Working petition is at 12:12:02 and the non working one is at 12:12:04. I can see differences commencing at this debug line:
```2018/02/05 12:12:04 [debug] 20652#20652: *2 http script copy: "/var/www/videos/"```

This is my nginx.conf
[nginx.conf.txt](https://github.com/kaltura/nginx-vod-module/files/1694878/nginx.conf.txt)

Now I'm trying to understand that "http script copy".

**Comment by erankor** [comment]
Ah, now I see, I misread your first comment, I thought you wrote that hls2 works...
Anyway, the reason is that with "regular" (non regex) location, when mapping the URI to file path, Nginx adds the part that comes after the string set on the location. 
In other words - if you have `location /hls/` with `alias /base/`, if you hit /hls/something, nginx will look for /base/something. When you use regex location, Nginx doesn't do that, and it's up to you.
So you can for example do something like this:
```
location ~ /hls2/(.*) {                                                                                                                              
  alias /var/www/videos/$1;
  vod hls;
}
```

**Comment by aldeluis** [comment]
Perfectly explained. Now I have my nginx.conf edited with your suggestion.

There is new log line "http script capture" with the result of the regex pattern, but the module doesn't parse the multiurl structure as in the "location /hls/" and never find the files.

```
2018/02/05 16:52:48 [debug] 2269#2269: *1 http script copy: "/var/www/videos/" 
2018/02/05 16:52:48 [debug] 2269#2269: *1 http script capture: "devito,360p.mp4,.urlset/master.m3u8"
2018/02/05 16:52:48 [debug] 2269#2269: *1 cached open file: /var/www/videos/devito,360p.mp4,.urlset/master.m3u8, fd:-1, c:0, e:2, u:1
2018/02/05 16:52:48 [error] 2269#2269: *1 ngx_file_reader_update_state_file_info: open() "/var/www/videos/devito,360p.mp4,.urlset/master.m3u8" failed (2: No such file or directory), client: 159.89.96.50, server: , request: "GET /hls2/devito,360p.mp4,.urlset/master.m3u8 HTTP/1.1", host: "video.sctv.es"
```

[log2.txt](https://github.com/kaltura/nginx-vod-module/files/1699700/log2.txt)

(Sorry for the mistake with my first comment, it was my fault (swapped hls and hls2 locations) I edited it to make this thread coherent.)

**Comment by erankor** [comment]
Hmm... makes sense... instead of $1 in the `alias`, try to use `$vod_suburi`. This should resolve to something like `/hls2/devito,360p.mp4`. 
Once you see this working (the request will still fail, but you should see this path in the `open failed` error line), you can remove the /hls2/ prefix using nginx's builtin map module. Define another variable using map that is $vod_suburi without the /hls2/ and use it here. Note that you will need to enable `volatile` on the map definition, otherwise the variable will be cached and you will get the same value for all suburis.
Btw, after you do that, you can remove the `(.*)` from the regex, since you won't be using this capture anymore.

**Comment by aldeluis** [comment]
Great!. We are approaching the solution. I've created a map definition in the http context:
```
	map $vod_suburi $vod_suburi_crop {
		volatile;
		 "~/hls2/(.*)" $1; 
	}
```

And the location part in the server context
```
		location ~ /hls2/ {
			alias /var/www/videos/$vod_suburi_crop;
			vod hls;
		}
```

The manifests generated have the right files on it, but the properties (PROGRAM-ID, BANDWIDTH,...) are only from the last archive parsed from the URI. Example:

```http://video.sctv.es/hls2/devito,480p.mp4,720p.mp4,360p.mp4,.urlset/master.m3u8```

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=964877,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401f,mp4a.40.2"
http://video.sctv.es/hls2/devito480p.mp4/index-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=964877,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401f,mp4a.40.2"
http://video.sctv.es/hls2/devito720p.mp4/index-v1-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=964877,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401f,mp4a.40.2"
http://video.sctv.es/hls2/devito360p.mp4/index-v1-a1.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=43812,RESOLUTION=640x360,CODECS="avc1.4d401f",URI="http://video.sctv.es/hls2/devito480p.mp4/iframes-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=43812,RESOLUTION=640x360,CODECS="avc1.4d401f",URI="http://video.sctv.es/hls2/devito720p.mp4/iframes-v1-a1.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=43812,RESOLUTION=640x360,CODECS="avc1.4d401f",URI="http://video.sctv.es/hls2/devito360p.mp4/iframes-v1-a1.m3u8"
```

One more effect is that if an additional file is asked for parsing, vtt subs in this case, the petition is rejected with a 400 Bad Request:

```http://video.sctv.es/hls2/devito,480p.mp4,720p.mp4,360p.mp4,.en_US.vtt,.urlset/master.m3u8```

**Comment by erankor** [comment]
Try this pull - https://github.com/kaltura/nginx-vod-module/pull/791
What currently happens is that $vod_suburi does not evaluate correctly in this context.
Regarding the error 400, please check the error log

**Comment by erankor** [comment]
@aldeluis, did you try it out?

**Comment by aldeluis** [comment]
Yes! It's working now. The manifest from the regex location (location ~ /hls2/) is identical to the static one (location /hls/).

**Comment by erankor** [comment]
Merged, thanks for the update
