### ISSUE TITLE
Is there a way to change request in ".m3u8" to be able to cache them in a proxy server?

### ISSUE THREAD

**Issue by nxtbr** [kaltura/nginx-vod-module#793]
I setup a VOD near to our remote storage:

- http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/index.m3u8

And I am trying to setup a proxy cache near to our users:

- http://189.8.68.133/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/index.m3u8

But all ".ts" requests going to 159.203.75.158 instead of 189.8.68.133 as contained in the manifest:

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/encryption.key"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-1-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-2-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-3-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-4-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-5-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-6-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-7-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-8-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-9-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-10-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-11-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-12-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-13-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-14-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-15-v1-a1.ts
#EXTINF:10.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-16-v1-a1.ts
#EXTINF:7.000,
http://159.203.75.158/hls/nxtradiorock/Musicas/5a13cab930634c764f326740.mp4/seg-17-v1-a1.ts
#EXT-X-ENDLIST

Is there a way to change the the domain it use to generete the m3u8?

**Comment by erankor** [comment]
That is correct, btw, an alternative method to enable relative URLs is to use the vod_xxx_absolute_yyy_urls directives - 
- vod_dash_absolute_manifest_urls
- vod_hds_absolute_manifest_urls
- vod_hls_absolute_master_urls
- vod_hls_absolute_index_urls

**Comment by nxtbr** [comment]
guys, thanks so much for your time and help...

it worked like a charm!

**Comment by fsouza** [comment]
@erankor awesome, I didn't know about that :D
