### ISSUE TITLE
invalid value "thumb" in "vod"

### ISSUE THREAD

**Issue by perlethandersen** [kaltura/nginx-vod-module#795]
Hello,

I realise that other people have had this issue before me, but reading their issues haven't helped me so far so I'm going to ask myself.

I installed kaltura-ffmpeg which is 3.2 by saying sudo apt-get install kaltura-ffmpeg. It's located at /opt/kaltura/ffmpeg-3.2.

I have:
LD_LIBRARY_PATH=/opt/kaltura/ffmpeg-3.2/lib
LIBRARY_PATH=/opt/kaltura/ffmpeg-3.2/lib
C_INCLUDE_PATH=/opt/kaltura/ffmpeg-3.2/include

I configure by saying:
./configure --with-http_ssl_module --add-module=../nginx-rtmp-module-1.2.0 --add-module=../nginx-vod-module-1.22 --with-file-aio --with-threads --with-cc-opt="-O3"

It prints:
checking for libavcodec ... not found

and in objs/autoconf.err I found the line:
fatal error: libavcodec/avcodec.h: No such file or directory

However it IS present at /opt/kaltura/ffmpeg-3.2/include/libavcodec...

What am I missing (or what did I misunderstand)?

**Comment by erankor** [comment]
To test whether libavcodec exists, the module tries to compile something like this:
```
#include <libavcodec/avcodec.h>

int main()
{
  avcodec_send_packet(NULL, NULL);
  return 0;
}
```
You can save this to a c file, and run - `gcc test.c -o test -lavcodec`
This is expected to fail, due to the error you're getting, and in that case, you can debug it more easily.
For example, try to add the ffmpeg path explicitly to gcc with `-I/opt/kaltura/ffmpeg-3.2/include`, if this works, then you know that for some reason setting C_INCLUDE_PATH didn't work.

**Comment by perlethandersen** [comment]
It compiles both with and without adding the ffmpeg path explicity.
So I guess setting C_INCLUDE_PATH doesn't work for me?

**Comment by jessp01** [comment]
Hi @perlethandersen,

What Eran meant is for you to create a new file, say /tmp/test.c with these contents:
```
#include <libavcodec/avcodec.h>

int main()
{
      avcodec_send_packet(NULL, NULL);
        return 0;
}

```

Then, call GCC with:
```
$ /tmp/test.c -o /tmp/test -lavcodec
```
If it succeeds, we're good, otherwise, I imagine you did not export the C_INCLUDE_PATH LD_LIBRARY_PATH LIBRARY_PATH ENV vars. Run:
```
$ LD_LIBRARY_PATH=/opt/kaltura/ffmpeg-3.2/lib
$ LIBRARY_PATH=/opt/kaltura/ffmpeg-3.2/lib
$ C_INCLUDE_PATH=/opt/kaltura/ffmpeg-3.2/include
$ export C_INCLUDE_PATH LD_LIBRARY_PATH LIBRARY_PATH
```

Without the export, it won't work.

**Comment by perlethandersen** [comment]
I know and that's excatly what I did. And it succeeded.
I just tried to set ENV vars again as root and that fixed the issue.

Thanks.
And thanks for a great module!
