### ISSUE TITLE
Too short segment seams to breaks VideoJS playback/segment loading  (vod_segment_count_policy not working?)

### ISSUE THREAD

**Issue by benweidig** [kaltura/nginx-vod-module#796]
Hi,

we're using mapped mode with clips.

nginx 1.12.2 with nginx-vod-module@master.

Our HLS stream is composed of multiple clips with pregenerated JSON-playlists and everything works great except for some videos.

The player stops loading segments after encoutering a tiny segment (~928 bytes). I've obfusicated the URL because it's protected by Akamai tokens anyway. If you would rather want an URL to inspect I could try to setup an additional CDN without protection for testing.

```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
https://server/hls/playlist.json/seg-1-f3-v1-a1.ts
#EXTINF:10.000,
https://server/hls/playlist.json/seg-2-f3-v1-a1.ts
#EXTINF:10.000,
https://server/hls/playlist.json/seg-3-f3-v1-a1.ts
#EXTINF:0.520,
https://server/hls/playlist.json/seg-4-f3-v1-a1.ts
#EXT-X-DISCONTINUITY
#EXTINF:10.000,
https://server/hls/playlist.json/seg-5-f3-v1-a1.ts
#EXTINF:10.000,
https://server/hls/playlist.json/seg-6-f3-v1-a1.ts
```

As you can see there's a segment with 0.520 length, which is causing VideoJS to stop loading additional segments without throwing an error or stating a reason to stop loading.

I tried the following settings:
`vod_align_segments_to_key_frames` =>  `on/off`

`vod_segment_count_policy` => `last_long/last_rounded`
This settings didn't change the segments length, is it supposed to work in mapped mode?

`vod_manifest_segment_durations_mode` => `accurate`
Removed it again, after seeing that it is ignroed when using clips.

I'm pretty sure my video player is to blame for not loading the next segment, because the Kaltura HLS Test player works fine, but I was hoping to make some adjustments on the server side to make the player happy, instead of debugging/fixing bajillion lines of JS in `videojs-contrib-hls`.

If you can provide any insight or idea how to fix the tiny segment problem on the server side that would be great.

Keep up the awesome work!

**Comment by erankor** [comment]
I tested vod_segment_count_policy now with playlist, and it seems to work as expected -
```
# cat test.json
{"durations":[16397,10692],"sequences":[{"clips":[{"type":"source","path":"empty"},{"type":"source","path":"empty"}]}]}
```

last_short
```
# curl localhost:8001/mapped/test.json/index.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
http://localhost:8001/mapped/test.json/seg-1.vtt
#EXTINF:6.397,
http://localhost:8001/mapped/test.json/seg-2.vtt
#EXT-X-DISCONTINUITY
#EXTINF:10.000,
http://localhost:8001/mapped/test.json/seg-3.vtt
#EXTINF:0.692,
http://localhost:8001/mapped/test.json/seg-4.vtt
#EXT-X-ENDLIST
```

last_long
```
# curl localhost:8001/mapped/test.json/index.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:16
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:16.397,
http://localhost:8001/mapped/test.json/seg-1.vtt
#EXT-X-DISCONTINUITY
#EXTINF:10.692,
http://localhost:8001/mapped/test.json/seg-2.vtt
#EXT-X-ENDLIST
```

last_rounded
```
# curl localhost:8001/mapped/test.json/index.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:11
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
http://localhost:8001/mapped/test.json/seg-1.vtt
#EXTINF:6.397,
http://localhost:8001/mapped/test.json/seg-2.vtt
#EXT-X-DISCONTINUITY
#EXTINF:10.692,
http://localhost:8001/mapped/test.json/seg-3.vtt
#EXT-X-ENDLIST
```

Maybe this directive wasn't added in the correct location or something like that?
If you think the configuration is correct, please provide the nginx.conf and json file.

**Comment by benweidig** [comment]
Thx for the feedback. Of course it's working as intended, my test setup was wrong, sorry :-(

Forgot to change the `vod_base_url` to the correct test server, so it was getting the master.m3u8 from the test environment, but it contained links to the production system...

Once again thanks for the awesome support for this great module!

**Comment by erankor** [comment]
Thanks for the update :)
