### ISSUE TITLE
issue with caching after file changed

### ISSUE THREAD

**Issue by bigexxx** [kaltura/nginx-vod-module#799]
there is issue when i re-encode video, dash and hls unable to play due to old metadata... only if i restart nginx it will play normally

it is possible to flush cache? or even better to every time check modification time of file, and if it changed flush all cached data and re-read it

**Comment by erankor** [comment]
As mentioned on a few issues in the past - updating a file in place is not a good idea when it comes to video streaming. Even if you clear the nginx-vod cache, consider a client who downloaded the first X segments from version 1 and the following segments from version 2. Depending on the protocol/device this may cause playback errors.
A better solution is to create a new file, and have subsequent playback requests use a URL to the new file. This way, clients who started playing before the change get version 1 for all segments, and clients who started playing after the change get version 2 for all segments.
