### ISSUE TITLE
Support for proxy_intercept_errors on vod_remote_upstream_location?

### ISSUE THREAD

**Issue by fsouza** [kaltura/nginx-vod-module#801]
Use case is probably weird, but I figured I'd ask anyway: the idea is to follow redirects on ``vod_remote_upstream_location``. It works when I hit it directly, but when I go through the nginx-vod-module flow I just get a 308 back.

Here's what the location for ``vod_remote_upstream_location`` look like:

```
location /gcs-helper-proxy {
    rewrite ^/gcs-helper-proxy/(.*)$ /proxy/$1 break;

    proxy_pass http://gcs-helper;
    proxy_intercept_errors on;
    error_page 308 = @handle-redirect;
}
```

Let me know if more info is needed! :)

**Comment by erankor** [comment]
Sorry, this is not supported, but you should be able to make it work by adding another local proxy_pass - 1. nginx-vod-module calls location A that has proxy_pass into local location B
2. Location B does proxy_pass to the remote upstream. If a redirect is received, location B relays to location C (using error_page directive)
3. Location C does proxy_pass to the final destination (using $upstream_http_location)
