### ISSUE TITLE
Fragmented Mp4 as input 

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#804]
Hi 

Is it possible to do on-fly package for dash and hls by giving fmp4 file absolute path as input in JSON (Mapped mode configuration)  ?  

If i Use normal MP4 file am able to generate manifest files and playback is fine. But if i use fmp4 file as input than manifest file request gives below error 

*4 ngx_http_vod_validate_streams: no matching streams were found, client: x.x.x.x, server: localhost, request: "GET /bucket/TVN771026027MP4/TVN771026027MP4-/manifest.mpd HTTP/1.1", host: "x.x.x.x:xxxx"

In order to use fmp4 as input, do we need to change nginx.conf file ?

**Comment by erankor** [comment]
Fragmented mp4 as input is not supported

**Comment by Natarajan92** [comment]
Hi Erankor,

Thanks, To use VoD Module with fragmented file, we are processing below step

ffmpeg -i <fragmented mp4> -c copy <output.mp4>

Above way of de-fragmenting  the file will create any problem on playback while doing on-fly-packaging with VoD Module ?

**Comment by erankor** [comment]
The command looks ok to me

**Comment by Natarajan92** [comment]
Hi Erankor,
Thanks for your quick response

The above chat was deleted. So am adding the message for understanding purpose 

Question asked was 
To use VoD module for on-fly conversion we are trying below command to de-fragment the fragmented mp4 file 

ffmpeg -i <fragmented mp4 file> -c copy <output.mp4>

By doing so, will there be any problem on on-fly packaged asset playback
