### ISSUE TITLE
Error generating thumbnails

### ISSUE THREAD

**Issue by perlethandersen** [kaltura/nginx-vod-module#807]
Hello,

I'm using the module with great success. We just have one error.

For some reason, we can't generate a thumbnail from a specific offset on a specific mp4 video. The video is 34 minutes long and I'm trying to generate a thumbnail of 17 minutes in the video but it gives 400 Bad Request with: 
[error] 25023#25023: *4539 thumb_grabber_truncate_frames: did not find any frames (1) while reading media header
In the log.

The speific URL that I'm calling is like: thumbnails/_filename_.mp4/thumb-1019930.jpg
If I call thumbnails/_filename_.mp4/thumb-0.jpg it works
If I call thumbnails/_filename_.mp4/thumb-1999999.jpg (which is later in the video than 17 minutes) it works

And I can play the whole video with no problems.

The /thumbnails location is as simple as:

`location /thumbnails {
    vod thumb;
    vod_mode local;

    alias /location;

    expires 100d;
    add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
}`

What can cause this to fail, and how do I fix it?

**Comment by erankor** [comment]
It may be that you have some frame with extremely long duration (> 10 sec) before this position. You can check this assumption using ffprobe.
A possible workaround (if that is indeed the case...) is to increase vod_gop_look_behind.

**Comment by perlethandersen** [comment]
Cheers, erankor! It worked.

Thanks for the quick response.
