### ISSUE TITLE
nginx-vod-module/vod/segmenter.c:1905:6: error: this statement may fall through [-Werror=implicit-fallthrough=] on CentOS 7 using gcc 7.2.1 from SCL

### ISSUE THREAD

**Issue by colundrum** [kaltura/nginx-vod-module#814]
Hi,

I try to switch to lastest gccversion available using SCL but I obtain a fail.

**nginx-vod-module : tag 1.22**
**gcc (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)**

`cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -I/usr/include/ffmpeg -lavcodec -lswscale -lavfilter -DTCP_FASTOPEN=23 -fPIC -fopenmp -I/usr/include/ImageMagick   -Wno-deprecated-declarations  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/http/modules/perl -I ../../SOURCES/nginx-log-zmq/src -I ../../SOURCES/nginx-push-stream-module/src -I ../../SOURCES/nginx-push-stream-module/include -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../../SOURCES/nchan/src -I /usr/include/libxml2 -I ../../SOURCES/ngx_brotli/deps/brotli/include -I src/stream \
	-o objs/addon/enc/bit_cost.o \
	../../SOURCES/ngx_brotli/deps/brotli/enc/bit_cost.c
../../SOURCES/nginx-vod-module/vod/segmenter.c:`

> In function 'segmenter_get_segment_durations_accurate':
> ../../SOURCES/nginx-vod-module/vod/segmenter.c:1905:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
>    if (!media_set->audio_filtering_needed)
>       ^
> ../../SOURCES/nginx-vod-module/vod/segmenter.c:1910:2: note: here
>   default:
>   ^~~~~~~

Full log available at : https://circleci.com/gh/colundrum/custom_nginx_rpms/80

Thanks

**Comment by erankor** [comment]
Thanks, please try this pull - https://github.com/kaltura/nginx-vod-module/pull/815

**Comment by colundrum** [comment]
Hello,

Thanks a lot, it's ok with branch 1.22 with that method :
` git clone --single-branch --recurse-submodules -b 1.22 https://github.com/kaltura/nginx-vod-module.git
curl -LO https://patch-diff.githubusercontent.com/raw/kaltura/nginx-vod-module/pull/815.patch
cd nginx-vod-module && git apply --verbose ../815.patch && rm ../815.patch`

Success : https://circleci.com/gh/colundrum/custom_nginx_rpms/83

A last question : do you release new tag on new release or do I need to use master ?

Thanks a lot

**Comment by erankor** [comment]
Thanks, merged to master. 
Regarding the tag, I usually create one after I run the full regression tests, and release a new version to our production environment. It will probably take a while... better use master for now

**Comment by colundrum** [comment]
Thanks, now I use master.

Regards
