### ISSUE TITLE
make request arguments available in chunk url 

### ISSUE THREAD

**Issue by whatvn** [kaltura/nginx-vod-module#820]
Hello, 

Is there any way in current vod implement, i want to keep request argument pass in playlist request in ts chunk generated by vod module? For example: 

request index.m3u8: *http://host/dummy.mp4/index.m3u8?misc=abc* will generate:

```

http://host/.../seg1-v1-a1.ts?misc=abc
http://host/.../seg2-v1-a1.ts?misc=abc
....
```

Thank,

**Comment by erankor** [comment]
Can be supported using nginx-secure-token-module, discussed here - https://github.com/kaltura/nginx-vod-module/issues/454#issuecomment-265868648

**Comment by whatvn** [comment]
found solution last night, forget to close issue. Thank @erankor

**Comment by daimoniac** [comment]
@whatvn how did you resolve this issue?

regards
