### ISSUE TITLE
Install rpm timeout

### ISSUE THREAD

**Issue by RhuanGonzaga** [kaltura/nginx-vod-module#824]
[root@s128592 nginx-1.13.12]# rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
Retrieving http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
warning: /var/tmp/rpm-tmp.tjcWZe: Header V4 RSA/SHA1 Signature, key ID ba443ef2: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:kaltura-release-13.4.0-4         ################################# [100%]
[root@s128592 nginx-1.13.12]# yum install kaltura-nginx
Loaded plugins: fastestmirror
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://installrepo.kaltura.org/releases/latest/7/RPMS/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.

 One of the configured repositories failed (Kaltura Server),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable Kaltura

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=Kaltura.skip_if_unavailable=true

**Comment by jessp01** [comment]
Hello @RhuanGonzaga,

We had an outage yesterday.
All fixed now.

Sorry for the inconvenience and so let us know should you experience additional issues,
