### ISSUE TITLE
too big subrequest

### ISSUE THREAD

**Issue by jersobh** [kaltura/nginx-vod-module#831]
Hi there!
I'm getting this error while I try to get the hls:

2018/04/26 13:45:57 [error] 9926#0: *46 too big subrequest response: 153143 while sending to client, client: x.x.x.x, server: localhost, request: "GET /hls/097d9164-5bc7-4312-a3ea-383c9b431481.mp4/master.m3u8 HTTP/1.1", subrequest: "/s3/hls/097d9164-5bc7-4312-a3ea-383c9b431481.mp4", upstream: "http://x.x.x.x:80/mybucket/097d9164-5bc7-4312-a3ea-383c9b431481.mp4", host: "x.x.x.x"

This is my conf.:
``
server {

    listen	 80;
    server_name  localhost;
    vod_mode remote;
    vod_align_segments_to_key_frames on;
    vod_segment_duration 6000;
    vod_upstream_location /s3;
    vod_hls_absolute_master_urls off;
    vod_hls_absolute_index_urls off;
    vod_metadata_cache metadata_cache 1024m;
    vod_response_cache response_cache 128m;
    vod_performance_counters on;

location ~ \/s3\/hls\/(.*) {
             
		resolver 8.8.8.8;
                set $target http://s3-sa-east-1.amazonaws.com/mybucket/$1;
		proxy_set_header Host "s3-sa-east-1.amazonaws.com";
                proxy_pass $target;
        }

location /noException{
                proxy_pass	https://s3-sa-east-1.amazonaws.com/mybucket/;
        }

location /hls {
              vod hls;
              vod_mode remote;
              gzip on;
              gzip_types application/x-mpegURL;
              add_header Cache-Control "public, max-age=10800";
              add_header Access-Control-Allow-Origin "*";
        }

        #location ~ .(m3u8|ts) {
        #        
        #        vod hls;
        #        vod_mode remote;
        #        vod_upstream_location /s3;
        #        gzip on;
        #        gzip_types application/x-mpegURL;
        #       	add_header Access-Control-Allow-Origin "*";
        #}
        
        location /crossdomain.xml {
                alias /usr/local/nginx/html/crossdomain.xml;
                access_log off;
        }
        location /status/ {
                vod_status;
        }
}

upstream backend {
    server s3-sa-east-1.amazonaws.com:80;
    keepalive 512;
}
``

**Comment by erankor** [comment]
This is the result of changes introduced in nginx 1.13.10, please try with this pull - https://github.com/kaltura/nginx-vod-module/pull/836

**Comment by jersobh** [comment]
IT WORKED :D 
BIG THANKS

**Comment by erankor** [comment]
Great! thanks for the update
