### ISSUE TITLE
Not able to install Kaltura 

### ISSUE THREAD

**Issue by gankur76** [kaltura/nginx-vod-module#837]
I am very new to Katura .. 
want to replace nginx-rtmp module with  nginx-vod-module 

getting following error 
root@ubuntu:/opt/nginx/nginx-1.13.1# apt-get install kaltura-nginx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
kaltura-nginx is already the newest version (1.12.2-4+b1).
The following packages were automatically installed and are no longer required:
  adwaita-icon-theme aspell aspell-en at-spi2-core bc colord colord-data dconf-gsettings-backend dconf-service dictionaries-common emacsen-common enchant gedit-common gir1.2-atk-1.0 gir1.2-freedesktop
  gir1.2-gdkpixbuf-2.0 gir1.2-gtk-3.0 gir1.2-gtksource-3.0 gir1.2-pango-1.0 gir1.2-peas-1.0 glib-networking glib-networking-common glib-networking-services gnome-user-guide gsettings-desktop-schemas
  gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-x hicolor-icon-theme humanity-icon-theme hunspell-en-us kaltura-postinst libaa1 libaspell15 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data
  libatspi2.0-0 libavdevice-ffmpeg56 libavfilter-ffmpeg5 libcairo-gobject2 libcdparanoia0 libcolord2 libcolorhug2 libcups2 libcurses-perl libcurses-ui-perl libdconf1 libdv4 libenchant1c2a libepoxy0
  libexif12 libgd3 libgeoclue0 libgphoto2-6 libgphoto2-l10n libgphoto2-port12 libgstreamer-plugins-base1.0-0 libgstreamer-plugins-good1.0-0 libgstreamer1.0-0 libgtk-3-0 libgtk-3-bin libgtk-3-common
  libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libgtksourceview-3.0-1 libgtksourceview-3.0-common libgudev-1.0-0 libgusb2 libharfbuzz-icu0 libhunspell-1.3-0 libhyphen0 libieee1284-3
  libjavascriptcoregtk-4.0-18 libjson-glib-1.0-0 libjson-glib-1.0-common liblcms2-2 libltdl7 libnotify4 libopencv-core2.4v5 libopencv-imgproc2.4v5 libpangoxft-1.0-0 libpeas-1.0-0 libpeas-1.0-0-python3loader
  libpeas-common libpostproc-ffmpeg53 libproxy1v5 librest-0.7-0 libsane libsane-common libsecret-1-0 libsecret-common libshout3 libsoup-gnome2.4-1 libsoup2.4-1 libtag1v5 libtag1v5-vanilla libtbb2
  libterm-readkey-perl libv4l-0 libv4lconvert0 libvisual-0.4-0 libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-37-gtk2 libxcomposite1 libxft2 libxpm4 libxtst6 libyelp0 notification-daemon python3-cairo
  python3-gi-cairo sysv-rc-conf ubuntu-mono yelp yelp-xsl zenity zenity-common
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 120 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up kaltura-nginx (1.12.2-4+b1) ...
Job for kaltura-nginx.service failed because the control process exited with error code. See "systemctl status kaltura-nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript kaltura-nginx, action "restart" failed.
● kaltura-nginx.service - LSB: starts the nginx web server
   Loaded: loaded (/etc/init.d/kaltura-nginx; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-04-30 15:19:19 +08; 6ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 23436 ExecStart=/etc/init.d/kaltura-nginx start (code=exited, status=127)

Apr 30 15:19:19 ubuntu systemd[1]: Starting LSB: starts the nginx web server...
Apr 30 15:19:19 ubuntu kaltura-nginx[23436]: Starting nginx: /opt/kaltura/nginx/sbin/nginx: error while loading shared libraries: libx265.so.87: cannot open shared object file: No such file or directory
Apr 30 15:19:19 ubuntu systemd[1]: kaltura-nginx.service: Control process exited, code=exited status=127
Apr 30 15:19:19 ubuntu systemd[1]: Failed to start LSB: starts the nginx web server.
Apr 30 15:19:19 ubuntu systemd[1]: kaltura-nginx.service: Unit entered failed state.
Apr 30 15:19:19 ubuntu systemd[1]: kaltura-nginx.service: Failed with result 'exit-code'.
dpkg: error processing package kaltura-nginx (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)

root@ubuntu:/opt/nginx/nginx-1.13.1# service kaltura-nginx status
● kaltura-nginx.service - LSB: starts the nginx web server
   Loaded: loaded (/etc/init.d/kaltura-nginx; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-04-30 15:19:19 +08; 58s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 23436 ExecStart=/etc/init.d/kaltura-nginx start (code=exited, status=127)

Apr 30 15:19:19 ubuntu systemd[1]: Starting LSB: starts the nginx web server...
Apr 30 15:19:19 ubuntu kaltura-nginx[23436]: Starting nginx: /opt/kaltura/nginx/sbin/nginx: error while loading shared libraries: libx265.so.87: cannot open shared object file: No such file or directory
Apr 30 15:19:19 ubuntu systemd[1]: kaltura-nginx.service: Control process exited, code=exited status=127
Apr 30 15:19:19 ubuntu systemd[1]: Failed to start LSB: starts the nginx web server.
Apr 30 15:19:19 ubuntu systemd[1]: kaltura-nginx.service: Unit entered failed state.
Apr 30 15:19:19 ubuntu systemd[1]: kaltura-nginx.service: Failed with result 'exit-code'.

root@ubuntu:/opt/nginx/nginx-1.13.1# service kaltura-nginx start
Job for kaltura-nginx.service failed because the control process exited with error code. See "systemctl status kaltura-nginx.service" and "journalctl -xe" for details.

**Comment by jessp01** [comment]
Hello @gankur76,

The nginx binary fails to run because it relies on /usr/lib/x86_64-linux-gnu/libx265.so.87 which cannot be loaded:
> /opt/kaltura/nginx/sbin/nginx: error while loading shared libraries: libx265.so.87: cannot open shared object file: No such file or directory

This SO is provided by the libx265-87 package which, kaltura-ffmpeg relies on. kaltura-ffmpeg should have been fetched because kaltura-nginx declares is as a dependency. 

Is the kaltura-ffmpeg package installed? You can check with:
```
# dpkg -l kaltura-ffmpeg
```
If it is not, try to manually install it with:
```
# apt-get install kaltura-ffmpeg
```
if you get an error, post it here.

Like I said, by running:
```
# apt-get install kaltura-nginx
```
kaltura-ffmpeg should have been fetched and installed [if it was not installed already] and in turn, all the packages it depends on [including libx265-87] should have also been fetched and deployed. 

In addition to any errors you may see when trying to deploy kaltura-ffmpeg, post the output for:
```
# ldd  /opt/kaltura/nginx/sbin/nginx
```

Also, you didn't state that in the issue but from the versions, I presume we're talking about Ubuntu 14.04?

**Comment by jessp01** [comment]
ping @gankur76

**Comment by jessp01** [comment]
Closing due to lack of response. Feel free to reopen and provide the needed info should the issue persist.
