### ISSUE TITLE
Unable to build module from sources on ubuntu

### ISSUE THREAD

**Issue by rumaovijay** [kaltura/nginx-vod-module#843]
nginx-vod-module/ngx_buffer_cache.c: In function ‘ngx_buffer_cache_release’:
/home/nginx-vod-module/ngx_buffer_cache.c:390:71: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (entry != NULL && entry->state == CES_READY && entry->write_time == token)

This happens when I try to build this module on ubuntu 16.04

**Comment by erankor** [comment]
Please try this pull - https://github.com/kaltura/nginx-vod-module/pull/844

**Comment by rumaovijay** [comment]
If you try to build with these flags
--with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' \
the build fails mostly on date time it converts warning messages into error. I found 2 more places where fix needs to be there Above flags seem to be standard for nginx installation. Without these flags vod-module cannot be even added dynamically to out of box nginx installation as it requires matching of the flags. Please fix the errors

**Comment by erankor** [comment]
I only got this issue - #849, but I didn't set up all the optional dependencies... 
If you have more errors, please paste them here.
