### ISSUE TITLE
http://nginx.org/en/docs/http/ngx_http_hls_module.html#hls_forward_args

### ISSUE THREAD

**Issue by cjk7713** [kaltura/nginx-vod-module#846]
http://nginx.org/en/docs/http/ngx_http_hls_module.html#hls_forward_args
this module had this Syntax or like this

**Comment by erankor** [comment]
This was raised a couple of times in the past... we don't have it as an integral part of nginx-vod-module, but can be done using another module that we maintain. 
See this comment - https://github.com/kaltura/nginx-vod-module/issues/532#issuecomment-280537237

**Comment by cjk7713** [comment]
Are there any examples to demonstrate how to use this module? I want to implement token generated by code, and then push URL to access the user.
i use nginx plus hls module like this
def md5(text, isBackByte=False):
    """md5加密函数"""
    md5 = hashlib.md5()
    if isinstance(text, bytes):
        md5.update(text)
    else:
        md5.update(text.encode('utf-8'))

    if isBackByte:
        # 返回二进制的加密结果
        return md5.digest()

        # 返回十六进制的机密结果
    return md5.hexdigest()


def base64_encode(text, isBytes=False):
    """进行base64编码处理"""
    if isBytes:
        return base64.b64encode(text)
    return base64.b64encode(bytes(text, encoding="utf-8"))


def get_timestamp10():
    """获取当前时间长度为10位长度的时间戳"""
    return int(time.time())


secret = 'ss';  # 密钥--对应#st的哈希格式为 secret+url+e,e为时间戳单位s，url为请求地址  secure_link_md5 xiaozhong.com$uri$arg_e;
# path = '/hls/5553.mp4/index.m3u8'  # 下载文件
# path = '/hls/5553.mp4'  # 下载文件
path = '/333.mp4'  # 下载文件
# 下载到期时间,time是当前时间,300表示300秒,也就是说从现在到300秒之内文件不过期
expire = get_timestamp10() + 3600;
res = md5(str(secret) + str(path) + str(expire), True)
md5 = str(base64_encode(res, True))
md5 = md5.replace('b\'', '').replace('\'', '').replace('+', '-').replace('/', '_').replace('=', '')

print('http://192.168.136.45:8384/hls/5553.mp4/index.m3u8?' + 'st=' + str(md5) + '&e=' + str(expire))

**Comment by erankor** [comment]
There are sample configurations here - 
https://github.com/kaltura/nginx-secure-token-module/#sample-configurations

In general, this module has several different functionalities that can be used independently - 
1. Embedding of query parameters in manifest responses (this is what you initially asked for)
2. It can generate tokens for several CDNs that we integrated with (Akamai, CloudFront etc.)
3. It supports encryption of parts of the URL

So, you can for example, use only the first item, and just use this module to propagate the args which will have some other token format, or use also item 2, and use some of the formats that are currently supported.

**Comment by cjk7713** [comment]
I will not use Akamai, maybe I will use cloudfront. Can you show how to generate token?

**Comment by erankor** [comment]
We are using this PHP code to generate CF tokens -
https://github.com/kaltura/server/blob/Mercury-13.20.0/alpha/apps/kaltura/lib/storage/urlTokenizers/kCloudFrontUrlTokenizer.php

**Comment by cjk7713** [comment]
Thanks very much！

**Comment by cjk7713** [comment]
I want to ask this implementation process is
**cloudfront->nginx->client**
but,what we need is 
**nginx->cloudfront->client**

**Comment by erankor** [comment]
Not sure I understand the question, but in our setup nginx-vod-module is behind the CDN if that is what you meant. The client makes a request to the CDN (which is protected by token) and the CDN makes a request to nginx-vod-module (this second request is protected using some secret header that the CDN sends)
