### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by fanshur** [kaltura/nginx-vod-module#852]
If I have installed
# apt-get install kaltura-nginx
do i have to config
NB: I use localfile

**Comment by fanshur** [comment]
i am sorry my bad english
i mean 
if i finish install using code 
apt-get install kaltura-nginx

must i config again nginx.conf

**Comment by fanshur** [comment]
@erankor

**Comment by fanshur** [comment]
@erankor

**Comment by erankor** [comment]
the package contains a few template configurations that you can use, your selections while installing the package determine which template will be used

**Comment by fanshur** [comment]
so if i finish installed that package, so i just put the file to directory 
----sorry

**Comment by erankor** [comment]
I don't understand, it's working for you now? can we close this issue?

**Comment by fanshur** [comment]
is this true ????
![screenshot_5](https://user-images.githubusercontent.com/37214723/40523968-946b8e54-600a-11e8-8743-0c754e01c752.jpg)
![screenshot_6](https://user-images.githubusercontent.com/37214723/40523969-94a359ba-600a-11e8-9d6e-78f82e4b3f41.jpg)

**Comment by fanshur** [comment]
is this true  ??? please don't close 
![image](https://user-images.githubusercontent.com/37214723/40524059-fb086d12-600a-11e8-85f2-6b6cd49bfbda.png)
![screenshot_6](https://user-images.githubusercontent.com/37214723/40524093-28f0701c-600b-11e8-8c97-54895111429f.jpg)

**Comment by erankor** [comment]
I see you pasted the template conf for local mode, but don't understand what you're asking...
If you're having some problem using this module, I think it would be helpful to describe what this problem is

**Comment by fanshur** [comment]
sorry @erankor  can you check my vid
what wrong in my progress
[https://youtu.be/c5lrudAwgN4](url)

**Comment by erankor** [comment]
The request needs to be either .../index.m3u8 or ../master.m3u8. 
Also you did not specify the file extension (.mp4?), while I can't see it on the UI, it probably has some video file extension since it has an icon of a video...

**Comment by fanshur** [comment]
can u help me, that still not work
[https://youtu.be/sepVX4m8ito](url)
sorry .. pardon me 
can you give me a 
solutions 4 me , i using ubuntu 16.04 LTS

**Comment by fanshur** [comment]
@erankor

**Comment by erankor** [comment]
Check the nginx error log
