### ISSUE TITLE
Crash playing same video 

### ISSUE THREAD

**Issue by darkoromanov** [kaltura/nginx-vod-module#856]
When I start playing a video which is already playing on another device I get the following error:

`2018/05/18 11:16:49 [error] 9112#0: *79 mp4_to_annexb_write: zero size packet while processing frames, client: 192.168.0.185, server: localhost, request: "GET /video/demo/Simpsons%20Movie%20Trailer%20HD%20720p.mp4/seg-15-v1-a1.ts HTTP/1.1", host: "192.168.0.180:88"`

and the player crashes.

**Comment by erankor** [comment]
This error is usually an indication that the mp4 file is corrupt - it has an h264 NAL unit of zero size. Try to play the mp4 directly, you'll probably also get an error 140 - 150 sec into the video (assuming you are using the default 10 sec segments)

**Comment by darkoromanov** [comment]
I tried with other clients (I'm using a video player from an Android app) and it seems the issue was indeed with the movie file.
