### ISSUE TITLE
What is the best way to offer a single m3u8 VOD from a set of multiple mp4 with this module?

### ISSUE THREAD

**Issue by qhchen2** [kaltura/nginx-vod-module#859]
For example I have 4 15-min mp4 files and want to offer it as as a 1-hour m3u8.
It looked like the playlist.json of mapped mode could be used for that, but the test.json I made doesnt seem to concatenate the videos. Is it supposed to work this way?

The JSON used is similar to the example, but it has two 10s mp4. Both the JSONs and mp4s are in the folder /mp4/. What happens when I try to request `http://myServerIP:8081/hls/test.json/master.m3u8` in VLC
s that It plays a 20s video, runs for 10s, and then plays a second 20s video that runs for 10s. Shouldnt it be a 20s video that runs for 20s? If the playlist is supposed to stream several videos consecutively, why is the length of the video 20s two times instead of 10s two times?
```
{
	"durations": [ 10000, 10000 ],
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/mp4/video1.mp4"
				},
				{
					"type": "source",
					"path": "/mp4/video2.mp4"
				}
			]
		}
	]
}
```
The nginx config Im using is very simple, basically the the example for local mode but adapted for mapped.

```
worker_processes  1;
events {
    worker_connections  1024;
}

http {
	server {
        listen 8081;
		# vod settings
		vod_mode mapped;

		# vod caches
		vod_metadata_cache metadata_cache 512m; 
		vod_response_cache response_cache 128m;
		vod_mapping_cache mapping_cache 5m;
		
		# gzip manifests
		gzip on;
		gzip_types application/vnd.apple.mpegurl;

		location /hls/ {
			vod hls;
			alias /mp4/;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}
```
Does anybody know why the playlist runs as separate files, instead of just one file? The length of the m3u8 is 20s so it seems it should be able to run for 20s? Is there a different solution Im unaware of that this module offers?

**Comment by erankor** [comment]
If you send `"durations": [ 10000, 10000 ]` in the JSON, I'd expect it to play 10 sec from the first clip and 10 sec from the second clip, is that not the case?
If not, please provide a publicly accessible URL to the m3u8

**Comment by qhchen2** [comment]
Thank you for the response erankor. To answer your questions, VLC does play 10sec of the first 10sec mp4 and 10sec of the second 10sec mp4. It just does it in a weird way. It offers a 20 sec video that plays from 0:00 to 0:10 without issues and after reaching halfway of the 20sec the screen closes then reopens a different 20 sec video that plays until halfway. I also cannot fast forward to for example 0:15 15 seconds after the start. So I wondered if that is how the playlist works, as separate videos served in parts instead of one continuous stream.

I played around a little bit more and http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html gave the error
`{"type":"mediaError","details":"manifestIncompatibleCodecsError", "fatal":true}` furthermore
hlstester.com gave `Media error: no level with compatible codecs found in manifest`
The master m3u8 gives

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=223112,RESOLUTION=640x480,FRAME-RATE=25.000,CODECS="avc1.64001e,mp4a.6b"
http://myServerIP:8081/hls/test.json/index-v1-a1.m3u8
```

I encoded these mp4 with ffmpeg and maybe I did it wrong, so I made some new mp4 and used -acodec aac this time. Unfortunately the test2.json has the same behavior in VLC as before, however
http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html  and hlstester.com do play the mp4 as a combined 20s video this time as I intended, without errors and ability to fast forward immediately to 15 seconds.

So I doublechecked the mp4 files I created and the first one appears to not have proper video the last 5 seconds. That and the weird behavior in vlc plus the vlc error log saying things like `adaptive: Encountered discontinuity` leads me to believe its a mp4 encoding specific problem that VLC does not handle as well as regular HLS videoplayers (repeating the last well recorded frames for the 5 empty seconds. This time the master.m3u8 is

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=642665,RESOLUTION=1280x960,FRAME-RATE=15.151,CODECS="avc1.640020,mp4a.40.2"
http://myServerIP:8081/hls/test2.json/index-v1-a1.m3u8

but I dont see a big difference to the previous m3u8.

This leads me to the following question. Do you have a recommendation for how to encode mp4 with ffmpeg so I wont get similar errors like the one in the first situation? Ofcourse the missing frames is a problem only I can do anything about, but it looks like it is handled well enough by the videoplayer I plan to use. Im only wondering about your recommended vcodec and acodec settings. I suspect that aac is recommended because it removed some of the errors? What about the recommended videocodec?

**Comment by qhchen2** [comment]
I just spotted

```
Video codecs: H264, H265 (DASH/HLS), VP9 (DASH)
Audio codecs: AAC, MP3 (HLS/HDS/MSS), AC-3 (DASH/HLS), E-AC-3 (DASH/HLS), OPUS (DASH)
```

Even though I used `-acodec libmp3lame` earlier which gave unsupportedcodec errors, and MP3 is supposedly supported as audiocodec I can now figure out better codecs to use, I guess.
