### ISSUE TITLE
Mapped mode dynamic generation of JSON

### ISSUE THREAD

**Issue by cathmer** [kaltura/nginx-vod-module#862]
Hi,

I've written a FastCGI server in C++ to dynamically generate a JSON file which I then want to use in mapped mode. I'm having some problems with it though, because the video is not playing. My nginx config looks like this:

    http {
        sendfile on;
        #tcp_nopush on;
        aio on;
        directio 512;
        #include mime.types;
        default_type application/octet-stream;
    
    upstream fcgi_json {
        server localhost:8082;
    }

    #vod part
    server {
        listen 8081; # open port 8081 for access to vod
        vod_mode mapped;
        
        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        location ^~ /generate_json/ {
            internal;
            fastcgi_pass fcgi_json;

            fastcgi_param  QUERY_STRING       $query_string;
        }
        
        location ^~ /vod/ {
            vod hls;
            vod_upstream_location /generate_json;
            vod_upstream_extra_args "user=$arg_user&time=$arg_time";
            
            #add_header 'Cache-Control' 'no-cache'; # disable cache for now for testing purposes
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
    }

When I make a call with curl:
`curl "http://<my_ip>:8081/vod/index.m3u8?user=user1&time=10"`
it works as expected and returns an index file with a couple of segments. 
But when I try to play this URL in a HLS player (for example, http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html), it's not working. Nginx gives the following errors: 
2018/05/31 14:19:59 [error] 25193#25193: *4 upstream prematurely closed FastCGI stdout while reading response header from upstream, client: 80.114.175.222, server: , request: "GET /vod/seg-1-v1.ts HTTP/1.1", subrequest: "/generate_json/vod", upstream: "fastcgi://127.0.0.1:8082", host: "80.114.175.222:8081", referrer: "http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html"

And the access log shows this:
<my ip> - - [31/May/2018:14:19:55 +0200] "GET /vod/index.m3u8?user=user1&time=10 HTTP/1.1" 200 209 "http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
<my ip> - - [31/May/2018:14:19:55 +0200] "GET /vod/seg-1-v1.ts HTTP/1.1" 502 575 "http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"

So it seems that first, the FastCGI server is called with the original query. But after that, it makes another call with a segment file name, and the FastCGI server cannot handle this (obviously, I guess) so it does not return a JSON. Therefore, the player is not working. 

EDIT: While writing this, I've noticed that when I turn on caching the issue does not occur. However, this is for a short video, I'm wondering if this won't give issues for videos of an hour or more?

EDIT2: It seems that with caching enabled it does work, however, when I then change the query parameters it doesn't issue a new request to the FastCGI server, which is also not how it should work. Any ideas about this?

Thanks in advance.

**Comment by cathmer** [comment]
That was exactly what I was looking for, and it did indeed fix it, thanks a lot!
The FastCGI is called with the segment though, this is an example of the URI I have in the CGI server: /vod/seg-1-v1.ts?user=user1&time=2 (after adding the secure tokens, before that the query parameters were not present). 
The functionality of the FastCGI works fine.

I have one more question about caching. Because I would like to cache requests, because it seems quite redundant to have the FastCGI server create the same JSON for each segment. However, this seemed to cause the problem that if I change the query parameters it still won't issue a new request to the server, so I can't change the request as long as it's still in cache. Any thoughts on how I can get around this?

**Comment by erankor** [comment]
1. Maybe FastCGI behaves differently than proxy, and that's the reason you're getting the file name. When I use proxy I don't get the file name in the upstream.
2. Right, the cache key is the host+uri, excluding query params. A possible workaround is to pass the params on the URI in the upstream request. The client requests can still use query params, but the upstream requests will use the path. You can use `vod_media_set_map_uri`, and set it to something like `/vod/user/$arg_user/time/$arg_time`.

**Comment by cathmer** [comment]
That's a nice workaround mapping the queries to an URL, I missed that option. I decided to just put the parameters in the URL in the first place for now, that also works great. Thanks for the help, closing this now.
