### ISSUE TITLE
Limit number of segment files at once

### ISSUE THREAD

**Issue by entrailz** [kaltura/nginx-vod-module#863]
Hi there,

How do I limit how many segment files are sent? I only want them to load 10~ segments at a time, meaning the video will be less buffered.

Thanks.

**Comment by erankor** [comment]
This is determined by the client, not by the server. 
If serving directly from nginx (not via CDN) it may be possible to do some kind of rate limiting, but that may not be a good idea if the client wants to seek for example.

**Comment by entrailz** [comment]
Hi,

OK so I can't control how many .ts files are returned?

I have put in a rate limit of 1mb as I don't want them to flood the server, it is behind a CDN but it has to be cached first so want to reduce the load on the main server.

Thanks.

**Comment by erankor** [comment]
The question is about vod or live? I thought it was vod, but if it's live then you can use vod_live_window_duration

**Comment by entrailz** [comment]
Hey,

Its a VOD, so I guess I answered my own question there, can't really reduce the amount of ts returned or else it won't play it all...

Thanks!

**Comment by erankor** [comment]
Right, in vod, the manifest has to contain all the segments. 
You can use this module to create a live stream from a vod file, and then you have control over this, but that means a very different experience for the client (they can't seek, for example)

**Comment by entrailz** [comment]
Hey,

In my scenario I am using it to take an MP4 and make it work as HLS, so I can assume there is nothing I can do with this?

Thanks.

**Comment by erankor** [comment]
Not on the server, but if you control the player then you can. For example, hls.js has parameters for that

**Comment by entrailz** [comment]
Do you have any example of how to do that on the client? :) Perhaps a link to the docs.

**Comment by erankor** [comment]
I don't, but from a quick search I see hls.js has maxBufferLength & maxBufferSize

**Comment by entrailz** [comment]
Okay thx for your help!
