### ISSUE TITLE
vtt from url

### ISSUE THREAD

**Issue by samanmohamadi** [kaltura/nginx-vod-module#865]
Is it possible to get webvtt subtitle from URL, not file? because in my project subtitles are created dynamically.
for example `http://mydomain.com/api/subtitle/1/vtt `

**Comment by erankor** [comment]
It is possible if you use remote mode or mapped mode with `vod_remote_upstream_location`. 
It is not possible to pull the videos from files and the subtitles from URL, but if you need it, worst case you can configure a local proxy location to the video files, and use URLs for everything (the overhead would probably be small)

**Comment by samanmohamadi** [comment]
Thanks
