### ISSUE TITLE
Mapped mode: multiple audio streams for one video stream, allowing selection on client side

### ISSUE THREAD

**Issue by Euphe** [kaltura/nginx-vod-module#866]
Hello.

I have multiple audio streams in different languages. I want the client to be able to pick the audio stream.
How do I define that in JSON? 
Currently my configs are like this:
```
{
  "sequences": [
    {
      "bitrate": {
        "v": 350477,
        "a": 96473
      },
      "clips": [
        {
          "type": "source",
          "path": "/somefile.mp4",
          "tracks": "v1-a1"
        }
      ]
    },
}
```
As you can see a single audio stream is mapped to a single video stream.

**Comment by erankor** [comment]
If the audio tracks are tagged with a language in the mp4 (mdhd atom) you can just remove the tracks field and it should work (the tracks field you have in the JSON makes the module take only the first audio track).
If the tracks are not tagged in the mp4, you will need to have a sequence object for each language, something like -
```
{
  "sequences": [
    {
      "language": "eng",
      "clips": [
        {
          "type": "source",
          "path": "/somefile.mp4",
          "tracks": "v1-a1"
        }
      ]
    },
    {
      "language": "spa",
      "clips": [
        {
          "type": "source",
          "path": "/somefile.mp4",
          "tracks": "a2"
        }
      ]
    }
  ]
}
```

**Comment by Euphe** [comment]
Thank you!
