### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cashmeer** [kaltura/nginx-vod-module#869]
Hello, does this link work with your module? 

https://myhd08.online/stream/hls/1529107200/553777466263b5967c8338e14ff5378d/,720,480,360,p.mp4.urlset/seg-5-f1-v1-a1.ts

**Comment by erankor** [comment]
Yes, looks like it does.
Why?

**Comment by cashmeer** [comment]
Hello, my question is if I upload a 1080p video, will I be able to stream it with multiples qualities from one video ?  thanks

**Comment by erankor** [comment]
The module can serve multiple bitrates, but it does not perform transcoding - you have to prepare the different bitrates in advance, before you provide them to the module for packaging.
