### ISSUE TITLE
non-trivial mapping in progressive download

### ISSUE THREAD

**Issue by irv** [kaltura/nginx-vod-module#871]
Hi,

I can see from reading some older issues such as #673 that when using `vod none` you're more or less limited to returning the source mp4.

Is it possible to use mapped mode, specifically `clipFrom`/`clipTo` in this scenario? It seems you cannot use multiple clips within a sequence, or use a `concat` clip.

```
{
	"durations": [
		20000,
		10000,
		10000
	],
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"clipFrom": 0,
					"clipTo": 20000,
					"path": "/etc/nginx/vdc_100052359795.0x000019.mp4"
				},
				{
					"type": "silence"
				},
				{
					"type": "source",
					"clipFrom": 30000,
					"clipTo": 40000,
					"path": "/etc/nginx/vdc_100052359795.0x000019.mp4"
				}
			]
		}
	]
}
```

**Comment by erankor** [comment]
That is correct, in progressive download, the only manipulation that is supported is clipping - no concatenation, no rate change etc.
Track selection was recently added in this pull - https://github.com/kaltura/nginx-vod-module/pull/842/files, but wasn't merged yet. This is a naive implementation that only edits the metadata - the frames of excluded tracks is still being served to the client.

**Comment by irv** [comment]
Thanks - #842 is devious! is there a desire to avoid libavcodec for this?

**Comment by erankor** [comment]
This feature does not depend on libavcodec
