### ISSUE TITLE
Hls vod with nginx secure link model

### ISSUE THREAD

**Issue by momkin** [kaltura/nginx-vod-module#872]
Hello , i'm trying to protect my m3u8 files with ngx_http_secure_link_module 
this is my config 

        location /securetest {
        alias /home/user/public_html/wp-content/uploads/hls-videoshere/dash;
        secure_link $arg_md5,$arg_expires;
        secure_link_md5 "$secure_link_expires$uri live21.ir";
        if ($secure_link = "") { return 403; }
        if ($secure_link = "0") { return 410; }
        vod hls;
        # vod settings
        vod_mode local;
        vod_align_segments_to_key_frames on;
        vod_bootstrap_segment_durations 3500;
        vod_hls_absolute_index_urls off;
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';
        expires 100d;
        }

and when requesting link http://xxxxxxxx.com/securetest/isp-221ar.mp4/index.m3u8?md5=ySwtvOYnCbgxLfN7uXREng&expires=1530024921

it works fine but the video doesn't works i think because the ts segments also needs to use the new secure links can you please help me ?

**Comment by erankor** [comment]
See this comment - https://github.com/kaltura/nginx-vod-module/issues/532#issuecomment-280537237
