### ISSUE TITLE
Using non-source clips in concat mapped mode

### ISSUE THREAD

**Issue by irv** [kaltura/nginx-vod-module#873]
We have a specific use case where, based on the user, we need to restrict some portions of the audio. I can do this using multiple clips and clipFrom/clipTo for DASH/HLS, but then i need to implement my own restrictions on people requesting segments from the forbidden clips (as we're justing saying in the manifest/playlist jump from this sequence to another).

So I came up with an idea, where i could use `clipIds`, but the ids themselves encoded `clipFrom`/`clipTo` in the uri:
```
{
  "durations": [
    40000
  ],
  "sequences": [
    {
      "clips": [
        {
          "type": "concat",
          "clipIds": [
            "id1/10000/20000",
            "silence",
            "id1/30000/40000"
          ],
          "durations": [
            10000,
            10000,
            10000
          ]
        }
      ]
    }
  ]
}
```

i then specified a `vod_source_clip_map_uri` which responds with either a source clip or a silence clip based on the id, and turned the uri back into clipFrom/clipTo.

This generates the mpd/playlist correctly, but fails when we request a segment that maps to the non-source clip:
`media_set_map_source: missing path in source object while sending to client`

(I then spotted the reference to using a path of "empty" to see if i could trick it that way, but then i get a track mismatch).

it seems I could cheat this by pretending silence is a source clip, and having my upstream provide a silence source, but it feels like that's a lot of hoops to jump through.

Is there another way around this, or am I abusing the feature? :)

**Comment by erankor** [comment]
Right, this is indeed not supported.
The source mapping feature enables you to postpone the resolution of source clip => path. In the current implementation, the silence generator is treated as a different type of clip (it's not a source) so it doesn't work.
But I don't quite understand what you are gaining from this approach - it looks like you already have all the info when you create the JSON, so why have these extra mapping calls?

**Comment by irv** [comment]
You mean like this?

```
{

  "durations": [
    10000,
    10000,
    10000,
    3723439
  ],
  "sequences": [
    {
      "clips": [
        {
          "type": "silence"
        },
        {
          "type": "source",
          "path": "id1",
          "clipFrom": 10000,
          "clipTo": 20000
        },
        {
          "type": "silence"
        },
        {
          "type": "source",
          "path": "id1",
          "clipFrom": 30000
        }
      ]
    }
  ]
}
```

the mpd that's generated has 4 time periods (c1 to c4), and assuming a 1 second segment duration to make this easier to demonstrate...

Normal operation is you'll request `fragment-1-i1-a1-x1.m4s` to `fragment-10-i1-a1-x1.m4s`, followed by `fragment-1-i2-a1-x1.m4s` to `fragment-10-i2-a1-x1.m4s`... but there's nothing to stop you requesting `fragment-11-i2-a1-x1.m4s`, `fragment-12-i3-a1-x1.m4s`, etc.

By using the concat clip, you're hiding this internal structure

**Comment by erankor** [comment]
You won't be able to access parts that do not exist in the JSON, no matter how you manipulate the URL, you can try it.
But anyway, if what bothers you is the multiple periods, you can add `"discontinuity": false` to the JSON in top level - this will tell the module to render it in a single period.
The reason the default value is `true` is that when concatenating multiple videos, the encoding parameters will often be different (unless special care is taken to handle that), and it won't play. 
In your case, it is also likely that the 'silence' generated by nginx-vod-module will have different parameters than the original audio (e.g. sampling rate/number of channels) but with audio, I think it will probably still play fine.

**Comment by irv** [comment]
OK thanks - that's interesting... leaving `discontinuity` as default, it seems using the reference DASH.js player with the above, it is unable to play period 3 (silence), even though it can play period 1. if you jump past it in the scrub bar it carries on with period 4 ¯\_(ツ)_/¯

**Comment by erankor** [comment]
Please provide the stream URL

**Comment by erankor** [comment]
@irv, we pushed this fix today #878, it may solve some of the issues you experienced with the silence generator

**Comment by irv** [comment]
Sorry for the delay in getting back to you! I pulled #878 and produced this:
https://iiifauth.digtest.co.uk/resources/31_adaptive_audio_degraded.mpd
which does appear to be behave a bit better with dash.js nightly, thanks

**Comment by erankor** [comment]
Thanks, closing this issue
