### ISSUE TITLE
Split video and audio

### ISSUE THREAD

**Issue by tarasdryanih** [kaltura/nginx-vod-module#874]
Hello!
First I want to say thanks for this wonderful module.
Small introduction. I use .mp4 format with several audio tracks, and when I try to cache this chunks
I cache 3 different chunks but changed only audio I think it's not productive.
.mp4/index-v1-a1.m3u8
.mp4/index-v1-a2.m3u8
.mp4/index-v1-a3.m3u8
Have some questions:
1) Is it possible to split video and audio into separate chunks  and cache apart?
2) If not possible to make 1) maybe kaltura can send all audio tracks in one chunk?
3) When moov atom have same name of audio track kaltura send in manifest only first, it is possible to avoid this?
Sorry for my bad English.

**Comment by erankor** [comment]
I don't follow, where do you get these index-v1-a#.m3u8 URLs from?
By default when you request a master manifest for an MP4 that has multiple audio tracks, you get back a multi-audio manifest, where the audio is passed separately from the video. The first audio, by default, is being muxed with the video (to support old players that may not support multi audio) but the rest of the audio tracks are returned without video.
If it also possible to disable muxing completely, by setting `vod_hls_force_unmuxed_segments` to off in nginx.conf.

**Comment by tarasdryanih** [comment]
Yes you are right. I was knocked down by muxing completely. 
 Can you give me answer for third question or I explained incorrectly?
Thank you. You are best.

**Comment by erankor** [comment]
See this thread #840

**Comment by tarasdryanih** [comment]
Thank you
