### ISSUE TITLE
how to define expiration time in "vod_metadata_cache"

### ISSUE THREAD

**Issue by wnpllrzodiac** [kaltura/nginx-vod-module#877]
`vod_metadata_cache metadata_cache 512m 5m;`

means cache memory 512MB and expire in 5 minute, is it right? 
DOUBLE m?

**Comment by wnpllrzodiac** [comment]
In my scenario, **the file content will be changing even file name is the same.**
I deploy a FTP server, use FTP client to upload media file to server.
I want to verify if media is corrupted using nginx-vod-module.
Just get all ts segment though network.
If all segments got, the media file uploaded is GOOD.

**Comment by erankor** [comment]
Yes, in expiration, m = minute.
If it's only used for validation, guess it should be fine, for streaming, I think it's a bad idea, as explained in a few threads in the past.

**Comment by wnpllrzodiac** [comment]
I just rename media file(add some timestamp suffix) to avoid this problem.
