### ISSUE TITLE
Adaptive mapped playlist

### ISSUE THREAD

**Issue by gstrat88** [kaltura/nginx-vod-module#882]
Hello I am trying to setup an adaptive json playlist, but I am getting:

> ngx_http_vod_validate_streams: one stream at most per media type is allowed video=2 audio=2 while reading media header

My json is:
`{"durations":[3600000],"sequences":[{"clips":[{"type":"source","path":"\/mnt\/ALPHA\/test_MQ.mp4"}]},{"clips":[{"type":"source","path":"\/mnt\/ALPHA\/test_LQ.mp4"}]}]}`

Thanks!

**Comment by erankor** [comment]
What is the request you are making? any chance you are calling index.m3u8 instead of master.m3u8?

**Comment by gstrat88** [comment]
Oh thats exacltly the case :(. Thanks!!!!

**Comment by fmozer** [comment]
e .... this case has been solved yet?  thanks

**Comment by gstrat88** [comment]
> e .... this case has been solved yet? thanks

In my case there was not a problem at all. When you want to use adaptive streaming you have to pass the master.m3u8 url to the player.

**Comment by fmozer** [comment]
> > e .... this case has been solved yet? thanks
> 
> In my case there was not a problem at all. When you want to use adaptive streaming you have to pass the master.m3u8 url to the player.

Thanks for your answer, I may understand the use case of adaptive playlist wrong. The readme description of this part is not very clear, I will continue to experiment.
