### ISSUE TITLE
Strange 404 error

### ISSUE THREAD

**Issue by brooklyn097** [kaltura/nginx-vod-module#884]
Hello,

Thanks for your great work on this module.
I'm having an issue with my setup and this is really weird.
There are 2 files:

1: /e9/a8/c4/e9a8c4edddb6cab8705926285e37cb3d/720/720.mp4
2: /68/ac/ac/68acacd151d950794d53731aa335e915/720/720.mp4

I've done some test cases following:

1. Access via direct Url:

```
http://192.168.1.1:1234/e9/a8/c4/e9a8c4edddb6cab8705926285e37cb3d/720/720.mp4 - this works

http://192.168.1.1:1234/68/ac/ac/68acacd151d950794d53731aa335e915/720/720.mp4 - this works
```

2. Access via nginx-vod-module:

```
http://192.168.1.1:1235/e9/a8/c4/e9a8c4edddb6cab8705926285e37cb3d/720/720.mp4/playlist.m3u8 - this returns a 404 not found.

http://192.168.1.1:1235/68/ac/ac/68acacd151d950794d53731aa335e915/720/720.mp4/playlist.m3u8 - this works

```

Here is my config:

```
server {
	listen 0.0.0.0:1235;
	root /mp4;
	
		add_header "Access-Control-Allow-Origin" "*";
		vod_mode local;
		vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
		vod_last_modified_types *;
		
		location / {
		
			vod hls;
			vod_hls_absolute_index_urls off;
			vod_hls_index_file_name_prefix playlist;
			vod_segment_duration 4000;
			vod_multi_uri_suffix .abr;
			
			secure_token_types application/vnd.apple.mpegurl application/dash+xml text/xml;
			secure_token $args;
			expires 100d;
		
		}
}
```

Please help me to understand why i get 404 with the first file while both files are located on the same server and use the same configs and i even can download the first file by direct url, i've checked wit "ls" command and the first file is existing.

**Comment by erankor** [comment]
Check the nginx error log, it is possible that the file is corrupt (there are some errors for which the module returns 404 other than ‘not found’)

**Comment by brooklyn097** [comment]
I see this in log file

`ngx_http_vod_handle_read_completed: bytes read is zero while reading media header`

That means  the file is corrupt right?

**Comment by brooklyn097** [comment]
Yes it's corrupted, i can't open it as well.
Thank you for your support!
