### ISSUE TITLE
audio language not working

### ISSUE THREAD

**Issue by ehsansis0** [kaltura/nginx-vod-module#888]
hi

i want to play movie with multiple subtitle and audio language, i use this query for play movie with multiple audio language but master.m3u8 contains invalid data.
http://192.168.14.128/hls/,audio/101_fa.mp3,audio/101_en.mp3,101_270.mp4,.urlset/master.m3u8

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=130329,CODECS="mp4a.40.2"
http://192.168.14.128/hls/audio/101_fa.mp3/index-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=129692,CODECS="mp4a.40.2"
http://192.168.14.128/hls/audio/101_en.mp3/index-a1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=173047,RESOLUTION=270x152,FRAME-RATE=15.000,CODECS="avc1.64000b,mp4a.40.2"
```
http://192.168.14.128/hls/101_270.mp4/index-v1-a1.m3u8

101_fa.mp3 and 101_en.mp3 should described with #EXT-X-MEDIA:TYPE=AUDIO but as you show it described with #EXT-X-STREAM-INF:PROGRAM-ID. how to solve this problem? and please tell me how to add multiple subtitle to above query link.

media info of 101_fa.mp3:
```
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/iso2/mp41)
File size                   : 21.4 MiB
Duration                    : 22 min 46 s
Overall bit rate mode       : Constant
Overall bit rate            : 131 kb/s
Writing application         : Lavf58.2.100

Audio
ID                          : 1
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : mp4a-40-2
Duration                    : 22 min 46 s
Bit rate mode               : Constant
Bit rate                    : 132 kb/s
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 21.1 MiB (99%)
Default                     : Yes
Alternate group             : 1
```

and please tell me how to change language and name tag for audio language?
`LANGUAGE="en",NAME="English" or LANGUAGE="en",NAME="English Master"
`
thanks very much.

**Comment by erankor** [comment]
See this comment - https://github.com/kaltura/nginx-vod-module/issues/840#issuecomment-386265077

**Comment by ehsansis0** [comment]
thanks very much. could you please tell me that i used which link for get m3u8 with multiple audio.

**Comment by erankor** [comment]
The URL looks right for this mediainfo, is it possible that you are getting a cached response? maybe try to restart nginx?
If it still doesn't work, please provide a URL to the MP4 file, so that I can reproduce it.
