### ISSUE TITLE
DASH Manifest sets audioSamplingRate to "0"

### ISSUE THREAD

**Issue by idanya** [kaltura/nginx-vod-module#889]
For some files in our library, I can see the dash manifest audio representation contains `audioSamplingRate="0"`
In these cases, MPD is playing well in chrome and firefox but in IE/EDGE I get an error saying "Video Element Error: MEDIA_ERR_RC_NOT_SUPPORTED" (playing in dashif.org).

Changing the audioSamplingRate key to any other value fixes the issue and the video is playing on IE/EDGE. 

All files in our library are transcoded the same way... What can cause this value to be 0?

**Comment by erankor** [comment]
The sampling rate is coming from the mp4 stsd atom, it's probably not set correctly there.
Can you share a sample file?

**Comment by idanya** [comment]
[sample](https://storage.googleapis.com/tempvid/dash-issue.mp4)

**Comment by erankor** [comment]
Try this pull #890

**Comment by idanya** [comment]
Now that I've checked, HLS of the same video is also not working on EDGE.

**Comment by erankor** [comment]
From a short google on this - https://docs.microsoft.com/en-us/windows/desktop/medfound/aac-decoder
"Sampling rates above 48 kHz are not supported."
So, assuming Edge uses Media Foundation for decoding, this is not supposed to work.

**Comment by idanya** [comment]
Great find! Thanks!
I'll try transcoding it with 48 kHz

**Comment by jessp01** [comment]
Hi @idanya - can this be closed? Thanks.
