### ISSUE TITLE
ngx_http_vod_get_async_read_result

### ISSUE THREAD

**Issue by midoeg** [kaltura/nginx-vod-module#891]
We use [Lustre ](http://lustre.org/) filesystem to store MP4 files, however we noticed that error occurs when trying to access the manifest or segment files for the first time.
Somehow, after trying many times on the same file it works, so the problem seems like buffering or caching or something either in the module or Lustre itself.

`[error] 4845#4845: *528342 ngx_http_vod_get_async_read_result: not enough room for null terminator while reading media header`
`[error] 4845#4845: *528345 ngx_http_vod_get_async_read_result: not enough room for null terminator while reading media header`
`[error] 4838#4838: *528348 ngx_http_vod_get_async_read_result: not enough room for null terminator while reading media header`

What is the meaning of that error and how to avoid it?

**Comment by erankor** [comment]
The MP4s are accessed using file system or via HTTP?
As far as I remember, this is more like an assertion, it's not supposed to happen... 
Maybe the module tried to read X bytes, but somehow got X+1 bytes in return
