### ISSUE TITLE
Ubuntu 16.04 repo points to wrong .deb package

### ISSUE THREAD

**Issue by tecfu** [kaltura/nginx-vod-module#892]
```
404  Not Found [IP: 13.32.205.152 80]
E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-nginx/kaltura-nginx_1.14.0-1_amd64.deb  404  Not Found [IP: 13.32.205.152 80]
```
Looks like someone updated the package to kaltura-nginx_1.14.0-2+b2_amd64.deb but didn't update the repository.

**Comment by jessp01** [comment]
Hi @tecfu, any update on this? Thanks.

**Comment by tecfu** [comment]
Thanks for documenting a potential fix. I'm using https://github.com/NYTimes/nginx-vod-module-docker instead.
