### ISSUE TITLE
NOT compatible with libiconv 1.15?

### ISSUE THREAD

**Issue by wnpllrzodiac** [kaltura/nginx-vod-module#893]
iconv_open report error -22 in vod/subtitle/webvtt_format.c

`iconv_utf16le_to_utf8 = iconv_open("UTF8", "UTF16LE");`

should be changed to 
`iconv_utf16le_to_utf8 = iconv_open("UTF-8", "UTF-16LE");`

**Comment by erankor** [comment]
I tested today and verified this works on my version as well, pushed it here - https://github.com/kaltura/nginx-vod-module/pull/894.
Thanks!
