### ISSUE TITLE
MSS and PlayReady

### ISSUE THREAD

**Issue by ppllaxxa** [kaltura/nginx-vod-module#895]
Hello,

I am trying to launch MSS with PlayReady.
Below is example of pssh which we are using for nginx:
`[{
	"pssh": [
		{
			"data": "AAAClnBzc2gAAAAAmgTweZhAQoarkuZb4IiflQAAAraWAgAAAQABAIwCPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgArAEUAbgBvAFEAbABGAEYAVQB2AEMARgBnAG8AdwBxAGEAbgBKAFIAaABBAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AGoAbABrAFIAUABXAGYAUwBtAGcAUQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAGUAegBkAHIAbQAuAGMAbwBtAC8AYwBlAG4AYwB5AC8AcAByAGUAYQB1AHQAaAAuAGEAcwBwAHgAPwBwAFgAPQA2AEYAOQAyADcANAA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==",
			"uuid": "9a04f079-9840-4286-ab92-e65be0885f95"
		}
	],
	"key": "NnF+tOMHEezpPIrucNakMg==",
	"key_id": "+EnoQlFFUvCFgowqanJRhA=="
}]`

But when I am trying to play it in bitmovin it just stuck, in browser debug console I see that it download several segments, call license server, but no playable video. Could you please help to determine an issue?

There is protection node from manifest:
`<Protection>
<ProtectionHeader SystemID="9a04f079-9840-4286-ab92-e65be0885f95">AAAClnBzc2gAAAAAmgTweZhAQoarkuZb4IiflQAAAraWAgAAAQABAIwCPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgArAEUAbgBvAFEAbABGAEYAVQB2AEMARgBnAG8AdwBxAGEAbgBKAFIAaABBAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AGoAbABrAFIAUABXAGYAUwBtAGcAUQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAGUAegBkAHIAbQAuAGMAbwBtAC8AYwBlAG4AYwB5AC8AcAByAGUAYQB1AHQAaAAuAGEAcwBwAHgAPwBwAFgAPQA2AEYAOQAyADcANAA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</ProtectionHeader>
</Protection>`

There is MSS with PlayReady stream:
http://91.218.249.43:3030/mssdrm/devito,360p.mp4,480p.mp4,720p.mp4,.en_US.vtt,.urlset/manifest

**Comment by erankor** [comment]
With DRM, it's hard to say why it doesn't play, it can be many things...
But looking at what you pasted, the pssh sent to nginx-vod-module looks wrong - it's a full pssh atom, while you need to send only the pssh data (the WRMHEADER xml and the binary struct that precedes it). 
In this case - the first 28 bytes (base64 decoded) need to be removed.

**Comment by ppllaxxa** [comment]
Thank you for your advise, but I am not completly understand this one - "and the binary struct that precedes it",
data element in pssh should contains WRMHEADER xml (base64 encoded), is below data is ok?:
//48AFcAUgBNAEgARQBBAEQARQBSACAAeABtAGwAbgBzAD0AIgBoAHQAdABwADoALwAvAHMAYwBoAGUAbQBhAHMALgBtAGkAYwByAG8AcwBvAGYAdAAuAGMAbwBtAC8ARABSAE0ALwAyADAAMAA3AC8AMAAzAC8AUABsAGEAeQBSAGUAYQBkAHkASABlAGEAZABlAHIAIgAgAHYAZQByAHMAaQBvAG4APQAiADQALgAwAC4AMAAuADAAIgA+ADwARABBAFQAQQA+ADwAUABSAE8AVABFAEMAVABJAE4ARgBPAD4APABLAEUAWQBMAEUATgA+ADEANgA8AC8ASwBFAFkATABFAE4APgA8AEEATABHAEkARAA+AEEARQBTAEMAVABSADwALwBBAEwARwBJAEQAPgA8AC8AUABSAE8AVABFAEMAVABJAE4ARgBPAD4APABLAEkARAA+ACsARQBuAG8AUQBsAEYARgBVAHYAQwBGAGcAbwB3AHEAYQBuAEoAUgBoAEEAPQA9ADwALwBLAEkARAA+ADwAQwBIAEUAQwBLAFMAVQBNAD4AagBsAGsAUgBQAFcAZgBTAG0AZwBRAD0APAAvAEMASABFAEMASwBTAFUATQA+ADwATABBAF8AVQBSAEwAPgBoAHQAdABwADoALwAvAHAAbABhAHkAcgBlAGEAZAB5AC4AZQB6AGQAcgBtAC4AYwBvAG0ALwBjAGUAbgBjAHkALwBwAHIAZQBhAHUAdABoAC4AYQBzAHAAeAA/AHAAWAA9ADYARgA5ADIANwA0ADwALwBMAEEAXwBVAFIATAA+ADwALwBEAEEAVABBAD4APAAvAFcAUgBNAEgARQBBAEQARQBSAD4A

**Comment by erankor** [comment]
No, it's not, if you take the first pssh that you pasted and do -
1. base64 decode
2. strip the first 28 bytes
3. base64 encode
It should be correct.

**Comment by ppllaxxa** [comment]
Thanks a lot. Now it is working.
