### ISSUE TITLE
CEA-608/708 is not detected

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#896]
Hi, 

For clear Dash packaged asset streaming we are able to detect embedded CC but same when encryption is enabled in configuration file, client not able to detect the embedded CC

Same time we need to know whether we can signal the client for CEA-608/708 through dash manifest  file ? 

like below in mpd file 

> <Accessibility schemeIdUri="urn:scte:dash:cc:cea-608:2015" 

> value="CC1=eng"/>

**Comment by erankor** [comment]
This is problematic, I don't think there's any indication of CEA-608/708 in the MP4 metadata (only in the video stream) and nginx-vod-module doesn't read any video frames when it builds the MPD.
And anyway, I'm not sure this will help... did you try to add it manually to the manifest?
IIRC, the CEA-608/708 NALU are currently being encrypted, maybe the solution is to avoid encrypting them.
Do you have some working encrypted dash stream with CEA-608/708?

**Comment by Natarajan92** [comment]
Hi Eran, 

Manifest file is generated on-the fly based on request from client. So editing it manually is not possible unless we have option while packaging it through vod-module

Is it possible to avoid encrypting CEA-608/708 NALU

**Comment by erankor** [comment]
If you have absolute URLs in the manifest, you can just host it on a separate server

**Comment by Natarajan92** [comment]
Please check you mail. I have shared sample dash content

**Comment by erankor** [comment]
Try this pull #897 
I didn't test playback, only looked at the raw fragment...

**Comment by Natarajan92** [comment]
Hi Eran, Yes now CC (CEA-608/708) is working. 

Can you pls merge fix with master build ?

**Comment by erankor** [comment]
Merged

**Comment by Natarajan92** [comment]
Thanks ! It is working but we are seeing some problems on CC for MPEG-DASH Stream like below

Expected Word: THAT
Actual Word: THT

Same asset working fine for HLS stream. We are debugging on it.  Any suggestions, let us know

**Comment by erankor** [comment]
Probably an issue on the client side, the module doesn't do anything with the CC packets - they are passed as is for both HLS & DASH

**Comment by Natarajan92** [comment]
Thank you Erankor!
