### ISSUE TITLE
Get DRM protected video for playing it offline

### ISSUE THREAD

**Issue by ppllaxxa** [kaltura/nginx-vod-module#899]
Hello, Is there a way to download video with DRM protection, for playing it later offline on client side?

**Comment by erankor** [comment]
The module does not support generating a single file DASH stream, if that is the question.
But supporting offline DRM is possible, it requires client side implementation - I think iOS/tvOS, for example, have an API for downloading a FairPlay HLS stream. And I think Exoplayer supports it for DASH.

**Comment by ppllaxxa** [comment]
Hello, there is an example of offline playback of DASH with Widevine:
https://biograf-155113.appspot.com/ttt/episode-2/
There is mpd from this example:
https://storage.googleapis.com/biograf-video-files/videos/ttt-ep-2/mp4/dash.mpd
and there is my mpd from nginx-vod-module:
87.206.24.220:4000/dash/manifest.mpd

But my mpd is not working for offline playback. May be you could provide some advise where I should look?

**Comment by erankor** [comment]
The issue is probably in the DRM server, I'm not aware of anything that needs to be done on the packaging side in order to support offline DRM.
