### ISSUE TITLE
How to send verimatrix_key_id to nginx correctly?

### ISSUE THREAD

**Issue by Bragaman** [kaltura/nginx-vod-module#900]
Hello!
I have a problem making hls with verimatrix drm.
Here is my nginx config:
```
location ~ ^/kaltura/vodhls-vcas {
    rewrite ^/kaltura(?<drm_request_uri>/.*)/(?<!index-)\w+\.m3u8$ $1/master.m3u8 break;
    rewrite ^/kaltura(?<drm_request_uri>/.*)/(.*) $1/$2 break;
    vod hls;
    vod_drm_enabled on;
    vod_hls_encryption_method aes-128;
    vod_hls_encryption_key_uri "https://drm.some_drm.ru/CAB/keyfile?p=0&r=$vod_sequence_id&t=VOD";
}
```
Here is my json example:
```
{"sequences":[
      {"clips":[{"path":"/some_patha/9/36766477272ba9f0f404a7a88bc76a.mp4","type":"source","tracks":"v1-a1"}], "id":"6b82a41d20b796672f236ee64977100f"},
      {"clips":[{"path":"/some_path9/0/bf8597743e4955dedcc826ecfeecbd.mp4","type":"source","tracks":"v1-a1"}], "id":"6b82a41d20b796672f236ee64977100f"},
      {"clips":[{"path":"/some_path9/7/b81558a4a8aaba346f636d24547011.mp4","type":"source","tracks":"v1-a1"}], "id":"6b82a41d20b796672f236ee64977100f"},
      {"clips":[{"path":"/some_path5/d/920da50d3d5fd9b620314b2fe8b0c5.mp4","type":"source","tracks":"v1-a1"}], "id":"6b82a41d20b796672f236ee64977100f"},
      {"clips":[{"path":"/some_patha/b/f20196ac7fe9ea826dfc10e45cb3c7.mp4","type":"source","tracks":"v1-a1"}], "id":"6b82a41d20b796672f236ee64977100f"}
  ]
}
```
I want to have different vod_hls_encryption_key_uri for different content files.
At this moment I am using $vod_sequence_id with length more then 10 symbols to send verimatrix key_id to nginx_vod_module, but I think it is bad way. 
Witch param should I use instead $vod_sequence_id to using verimatrix_key_id less than 10 symbols? And how should I modify my json.

**Comment by erankor** [comment]
If the ids of all the sequences are the same (as in the sample JSON that you pasted), you can use `$vod_set_id` instead of `$vod_sequence_id` and move the `id` field in the JSON to the top level.

**Comment by erankor** [comment]
I thought about adding such a feature in the past - similar to the builtin `$http_xxx` or `$sent_xxx` variable prefixes, have `$vod_json_xxx` pull some variable from the json. So far it wasn't a high enough priority for us to add this feature, we may add it in the future.
But I don't understand why can't you use `$vod_set_id`, you want to have different values for different sequences?

**Comment by Bragaman** [comment]
Thank you for answer.
Yes, I can use $vod_set_id, but will it be the correct way? May it used for something else?

**Comment by erankor** [comment]
Currently, that is the best solution, the id provided in the JSON is not used for anything by the module, other than populating $vod_set_id.
