### ISSUE TITLE
Strange vod_segment_duration behaviour

### ISSUE THREAD

**Issue by kuznetcoff777** [kaltura/nginx-vod-module#904]
Hi! I have a video with gop=25 and on border of 5-6 seconds i have smaller gop size because of cut/concat operation
...
frame,I
frame,B
frame,B
frame,B
frame,P
frame,B
frame,B
frame,B
frame,P
frame,B
frame,B
frame,B
frame,P
frame,B
frame,P
frame,I
...

If I configure hls with **vod_segment_duration 1000;** then i get all segments of 1 second length:
curl http://192.168.0.244/hls/test.mp4/index-v1-a1.m3u8  | grep -v http
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
102  2976  102  2976    0     0  4273k      0 --:--:-- --:--:-- --:--:--     0
#EXTM3U
#EXT-X-TARGETDURATION:1
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:1.000,
#EXTINF:0.323,
#EXT-X-ENDLIST

I thought that 5-th segment would be less then one second.
If i configure **vod_align_segments_to_key_frames on;** then result is the same.

Why is that?

**Comment by erankor** [comment]
By default, the duration returned in the m3u8 is the duration that is set in nginx.conf, it may not be the same as the actual duration of the segments. You can add `vod_manifest_segment_durations_mode accurate` to get the real duration in the manifest.

**Comment by kuznetcoff777** [comment]
Oh, great, thanks!
