### ISSUE TITLE
security

### ISSUE THREAD

**Issue by wws19125** [kaltura/nginx-vod-module#909]
is there any way for authentication easliy just like nginx-rtmp-module, for example:
on_public http_url_callback?token
on_close  http_url_callback?token

**Comment by erankor** [comment]
I assume you meant on_publish... anyway, no, this is not supported. on_publish is used to authenticate the incoming RTMP connection, while here, the module gets HTTP requests, so you can use any existing nginx access phase authentication module (e.g. access_by_lua).
However, the more common method of protecting vod streams is to use tokenization. With tokenization, the application generates a URL that is signed with some secret, and the signature is verified when serving the content to the user.
There are multiple ways to set this up, e.g. with nginx's secure link module + our nginx-secure-token-module. If you use a CDN, the CDN should be the one verifying the token.

**Comment by wws19125** [comment]
> I assume you meant on_publish... anyway, no, this is not supported. on_publish is used to authenticate the incoming RTMP connection, while here, the module gets HTTP requests, so you can use any existing nginx access phase authentication module (e.g. access_by_lua).
> However, the more common method of protecting vod streams is to use tokenization. With tokenization, the application generates a URL that is signed with some secret, and the signature is verified when serving the content to the user.
> There are multiple ways to set this up, e.g. with nginx's secure link module + our nginx-secure-token-module. If you use a CDN, the CDN should be the one verifying the token.

tks, for now i want to add some codes base on your project
