### ISSUE TITLE
Wrong directive in example config 

### ISSUE THREAD

**Issue by xeptor** [kaltura/nginx-vod-module#91]
Common configuration directives

vod
syntax: vod segmenter
default: n/a
context: location
Enables the nginx-vod module on the enclosing location. Currently the allowed values for segmenter are:

none - serves the MP4 files as is
dash - Dynamic Adaptive Streaming over HTTP packetizer
hds - Adobe HTTP Dynamic Streaming packetizer
hls - Apple HTTP Live Streaming packetizer
mss - Microsoft Smooth Streaming packetizer 

---------------------------------------
But in your example

location ~ ^/p/\d+/(sp/\d+/)?serveFlavor/ {
            vod; #<----
            vod_mode mapped;
--------------------------------------
Result: 
[emerg] 16869#0: invalid number of arguments in "vod" directive in nginx.conf

**Comment by erankor** [comment]
Thanks, fixed.
When these samples were written the module only supported hls, so the vod directive had no arguments... :)
