### ISSUE TITLE
Adding #EXT-X-PROGRAM-DATE-TIME to live HLS streams in mapped mode

### ISSUE THREAD

**Issue by benwilber** [kaltura/nginx-vod-module#910]
Hello,

I am setting up simulated live streams from VOD files and would like to add `#EXT-X-PROGRAM-DATE-TIME` to the media manifest.  Presently I am just naively re-writing the manifests using `subs_filter` module to add the tag.  This isn't really that useful since the timestamps aren't accurate.  Ideally I would be able to specify the correct date time value in the mapping response JSON, but it doesn't look like that is possible.  Can you think of another way that I might be able to accomplish this?

Thanks!

**Comment by erankor** [comment]
We are using ID3 tags for time synchronization on live (`vod_hls_mpegts_output_id3_timestamps on`). 
Maybe you can use that instead?
Btw, just noticed the readme has a mistake there - it says the default value is `on` while in fact it's `off`, I'll fix it...

**Comment by benwilber** [comment]
Hi @erankor thanks for the help.  The main issue is that I am trying to get the actual `#EXT-X-PROGRAM-DATE-TIME` tag into the manifest, not just timestamps in the mpeg-ts stream.  It doesn't seem to be supported at the moment, so I'll have to get a little clever about it.  Thanks for you help though!

**Comment by erankor** [comment]
What I suggested still applies - we are putting the real timestamp (unixtime in millis) in the ID3 tag. 
So - the contents of the ID3 is the real timestamp, and its PTS/DTS are the "mpeg ts" timestamp.
