### ISSUE TITLE
Use-case question

### ISSUE THREAD

**Issue by sido420** [kaltura/nginx-vod-module#912]
I'm new to this video streaming etc thing and Nginx. My usecase is such that I need to be able to let users watch uploaded video files (converted by ffmpeg in mp4 format with certain encoding) in their browsers using HTML video tag.

Currently, I'm using http://nginx.org/en/docs/http/ngx_http_mp4_module.html to serve files but I guess thats not as efficient as actual video streaming. Please note that there is no live streaming as yet (its just simple video files uploads and playing).

Would this module help me stream user uploaded mp4 files to other users? Or, do I need another module like https://github.com/sergey-dryabzhinsky/nginx-rtmp-module to help stream the files on demand? 

Please explain.

Thanks in advance.

**Comment by erankor** [comment]
This question is a bit wide... In short, there are multiple protocols for streaming videos, the ones relevant for this discussion - 
1. progressive download - the player simply downloads the MP4 file and plays it while it does
2. HTTP based streaming protocols (HLS/DASH/...) - the video is partitioned into small fragments, which the player pulls from the server
3. RTMP - a streaming protocol developed by Adobe, this is supported mostly in flash. As flash is disappearing, so does the use of RTMP for playback (it is used widely for publishing live video)

If you have a single rendition of each video, you can just use progressive download, and you don't even need ngx_http_mp4_module (unless you also want to clip the videos on the server).
If you have multiple renditions of each video (e.g. 360p & 720p) and you want the player to choose between them adaptively, you need to use one of the HTTP streaming protocols, and this is what this module does...
Btw, as a side now, nginx-vod-module also has support for MP4 clipping (similar to ngx_http_mp4_module), so no reason to use both.

**Comment by sido420** [comment]
Thanks for the explanation.

Which is better (in terms of bandwidth and browser support etc) "progressive download" or "HTTP streaming protocols"? In the later case, I'd have to use ffmpeg to create multiple renditions. Or, if HTTP streaming is more efficient I can convert the single mp4 file/rendition to HLS (something this module does I believe).

How does the user upload live streams to web server from a browser? Can this module take that input and convert to a playable format for viewers?

**Comment by erankor** [comment]
If you have a single rendition, and you don't use DRM, you can simply use progressive download, I don't think there's any advantage to using the other streaming protocols in this case. In terms of browser support, progressive download has the largest coverage.
But naturally, if you want to provide a good experience across multiple devices (small screen/large screen) and network conditions, you should create multiple renditions...
Live is a different topic... if you want to allow users to stream live video, you need some streaming server to handle that, like nginx-rtmp-module, Wowza etc.
