### ISSUE TITLE
Total misunderstanding with vod_upstream_location

### ISSUE THREAD

**Issue by tarkhil** [kaltura/nginx-vod-module#913]
Hello
I'm running a fairly simple config

upstream informer {
    server 127.0.0.1:81;
}

server {
    listen 81;
    server_name _;
    location / {
        root /var/flvs/info;
        types {
            application/json mp4;
        }
    }
}
....
    location /informer {
         alias /var/flvs/info;
        types {
            application/json mp4;
        }

later, in vod hls section
       location /hls {
            vod_mode mapped;
            vod_upstream_location /informer;
            vod hls;

}

==> /var/log/nginx/error.log <==
2018/10/16 12:32:17 [warn] 2343#2343: *5 ngx_child_request_initial_wev_handler: upstream is null while sending response to client, client: , server: localhost, request: "GET /hls/video/20180307-Politkokteil_short.mp4/index.m3u8 HTTP/1.1", subrequest: "/informer/hls/video/20180307-Politkokteil_short.mp4", host: " ", referrer: "http:// /test1/"
2018/10/16 12:32:17 [error] 2343#2343: *5 ngx_http_vod_map_run_step: not enough room in buffer for null terminator while sending response to client, client:  , server: localhost, request: "GET /hls/video/20180307-Politkokteil_short.mp4/index.m3u8 HTTP/1.1", host: " ", referrer: "http:// /test1/"

curl http://127.0.0.1/informer/hls/video/20180307-Politkokteil_short.mp4

yields nice little json. 

Looks like I'm missing something QUITE simple.

**Comment by erankor** [comment]
If you want to use local jsons, you don't need vod_upstream_location, you can just replace it with `alias /var/flvs/info;` in this case (assuming that's the base folder of the jsons).
vod_upstream_location is needed only when the json should be fetched over HTTP.

**Comment by tarkhil** [comment]
Sorry, I'm a byte lost (it's like being a bit lost, but 8 times)

Can you please show me config, assuming my videos are in /var/hls/video and JSONs in /var/hls/info?

**Comment by erankor** [comment]
Something like this -
```
server {
	listen 81;
	server_name _;

	location /hls {
		vod_mode mapped;
		alias /var/hls/info;
		vod hls;
	}
}
```
As you probably noticed, the base path of the mp4s is not here, the module expects the paths in the JSON to be absolute, so `/var/hls/video` would be in the JSON itself.

**Comment by tarkhil** [comment]
Done as you've recommended.

# cat 20180307-Politkokteil_short.mp4
{"sequences":[{"clips":[{"type":"source","path":"/var/flvs/video/20180307-Politkokteil_short.360p.mp4"}]}]}

(yes, I've even removed all spaces)

# file /var/flvs/video/20180307-Politkokteil_short.360p.mp4
/var/flvs/video/20180307-Politkokteil_short.360p.mp4: ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]

     location /informer {
         alias /var/flvs/info/hls;
         #vod hls;
         #vod_mode mapped;
        # types {
        #     application/json mp4;
        # }
     }
curl from informer yields good JSON; upon uncommenting vod_mode and vod, 
2018/10/17 15:24:23 [error] 1150#1150: *278 ngx_http_vod_hls_parse_uri_file_name: unidentified request, client:  , server: localhost, request: "GET /hls-d/video/20180307-Politkokteil_short.mp4 HTTP/1.1", host: " "

I've even explcitly set prefix and postfix for vod_path_response and compares them against the file (match).

**Comment by erankor** [comment]
The URL is wrong, you need to add a suffix of `/master.m3u8` or `/index.m3u8`.
Btw, regarding prefix and postfix, it's an optimization, it should work fine even if it doesn't match.

**Comment by erankor** [comment]
This means it works for you now? :)
Can I close this issue?

**Comment by tarkhil** [comment]
Yes. Looks like documentation could be improved, how could I do it?

**Comment by erankor** [comment]
If you think something is unclear in the readme, you can open a pull request
