### ISSUE TITLE
I am new here , help me starting

### ISSUE THREAD

**Issue by Medow** [kaltura/nginx-vod-module#914]
hello:
I just discover this amazing module and i am confused with too many options (This is a good thing ofcourse).
I need to know how to do this using your module.
I have a php code that return a json file contain a urls of external video 
`[{"label":"SD","file":"https:\/\/video-mxp1-1.xx.fbcdn.net\/v\/t42.1790-2\/10749875_10153231382106729_1430298193_n.mp4?_nc_cat=111&efg=eyJ2ZW5jb2RlX3RhZyI6InNkIn0%3D&oh=6053ab08956f9aafafbafcbcbb7d4a15&oe=5BC9F10F","type":"video\/mp4"},{"label":"HD","file":"https:\/\/video-mxp1-1.xx.fbcdn.net\/v\/t43.1792-2\/10435682_10153231382156729_130140491_n.mp4?_nc_cat=103&efg=eyJ2ZW5jb2RlX3RhZyI6ImhkIn0%3D&oh=d3a012630616cb82ca3c18f87401923b&oe=5BC9E8E6","type":"video\/mp4"}]`

I need to play those url on my own jwplayer by converting the above urls to my domain for example
`[{"label":"SD","file":"https://mydomain.com/embed/first_random_stringe_generated_auto","type":"video\/mp4"},{"label":"HD","file":"https://mydomain.com/embed/second_random_stringe_generated_auto","type":"video\/mp4"}]`

How can i do this ?
And how to protect those videos from bing downloaded using various videos grabber?

Thanks.

**Comment by erankor** [comment]
I added this sample configuration - 
https://github.com/kaltura/nginx-vod-module#mapped--remote-configuration
It shows how to perform the setup you need.

Regarding protection against download, you can set up tokenization to prevent arbitrary people from being able to play the stream (there are some threads on that + explanation in the readme). You can also enable HLS-AES which will protect against naive downloaders. But in general, if you want to prevent download from someone who should be allowed to watch, I think the only solution is DRM (and even that can't protect against capturing the screen with a camera...)

**Comment by jessp01** [comment]
@Medow - can this be closed?
