### ISSUE TITLE
security Kaltura

### ISSUE THREAD

**Issue by beeform1** [kaltura/nginx-vod-module#923]
Hello,

I am new to kaltura and I would like to install the security module of the content.

but I do not really understand how it's going?

can you share a detailed documentation please?

like the location of files to modify, a command list to install the nginx module ...

thank you so much

**Comment by erankor** [comment]
This question is a bit vague, there are several things that can be considered as 'security features'.
Did you read https://github.com/kaltura/nginx-vod-module#security ?

**Comment by erankor** [comment]
Assuming you got the basic functionality working, enabling encryption for HLS is easy - you just need to add to nginx.conf:
```
vod_hls_encryption_method aes-128;
vod_secret_key "somesecret$vod_filepath";
```
I'm not sure whether that will prevent a video capturing tool from working, a simple one - maybe, a more sophisticated one will probably pull the key (as the player does...) and use it to decrypt the stream.

**Comment by citijk** [comment]
working configuration example using "secure_link" module"


```
        map $uri $hls_uri {
                ~^(?<base_uri>.*)/(.*).m3u8$ $base_uri;
                ~^(?<base_uri>.*)/(.*).ts$   $base_uri;
                ~^(?<base_uri>.*)/(.*).webm$   $base_uri;
                default                 $uri;
            }

server{
    server_name hls.example.com;

	vod_segments_base_url https://$http_host;
	vod_base_url https://$http_host;
	root /home/filme/download/;
	location / {
		deny all;
	}

	location /src {
                secure_link $arg_md5,$arg_expires;
                secure_link_md5 "$secure_link_expires$hls_uri enigma";
                if ($secure_link = "0") { return 410; }
                if ($secure_link = "") { return 403; }
		alias /home/filme/download/;
	}

	location ~^/s2/(?<md5>[^/]+)/(?<exp>[^/]+)/(?<b>.*)/(?<f>.*).ts$ {
		secure_link $md5,$exp;
		secure_link_md5 "$secure_link_expires/$b enigma";
		if ($secure_link = "0") { return 410; }
		if ($secure_link = "") { return 403; }
		rewrite ^ /$b/$f.ts;
		alias /home/filme/download/;
		vod hls;
		include cors.vod;
	}
	location /hls/ {
		vod_segments_base_url https://$http_host/s2/$arg_md5/$arg_expires;
		secure_link $arg_md5,$arg_expires;
		secure_link_md5 "$secure_link_expires$hls_uri enigma";
		if ($secure_link = "0") { return 410; }
		if ($secure_link = "") { return 403; }
		alias /home/filme/download/;
		vod hls;
		include cors.vod;
	}
}
```
to get links like:

//hls.example.com/hls/directory/src.mp4/index.m3u8?md5=PZRyYExZAGJvpHP9SNXaPg&expires=1548089721 
or //hls.example.com/src/directory/src.webm?md5=REqPrC7Q0vdxMZ53etE0pA&expires=1548089721

example in php

```
<?php
    function buildSecureLink($path, $secret, $ttl, $string="")
    {
        $pa = dirname($path);
        $expires = time() + $ttl;
        $md5 = md5( "{$expires}{$pa}{$string} {$secret}", true);
        $md5 = base64_encode($md5);
        $md5 = strtr($md5, '+/', '-_');
        $md5 = str_replace('=', '', $md5);
        return $path . '?md5=' . $md5 . '&expires=' . $expires;
    }
    function to_player_sec($val){
        return "//hls.example.com" . buildSecureLink($val, "enigma", 60*60*4);
    }
    $player = explode(" or ", str_replace("//hls.example.com", "", "//hls.example.com/hls/directory/src.mp4/index.m3u8 or //hls.example.com/src/directory/src.webm"));
    $player = implode(" or ", array_map("to_player_sec", $player));
?>

**Comment by sumonst21** [comment]
> working configuration example using "secure_link" module"
> 
> ```
>         map $uri $hls_uri {
>                 ~^(?<base_uri>.*)/(.*).m3u8$ $base_uri;
>                 ~^(?<base_uri>.*)/(.*).ts$   $base_uri;
>                 ~^(?<base_uri>.*)/(.*).webm$   $base_uri;
>                 default                 $uri;
>             }
> 
> server{
>     server_name hls.example.com;
> 
> 	vod_segments_base_url https://$http_host;
> 	vod_base_url https://$http_host;
> 	root /home/filme/download/;
> 	location / {
> 		deny all;
> 	}
> 
> 	location /src {
>                 secure_link $arg_md5,$arg_expires;
>                 secure_link_md5 "$secure_link_expires$hls_uri enigma";
>                 if ($secure_link = "0") { return 410; }
>                 if ($secure_link = "") { return 403; }
> 		alias /home/filme/download/;
> 	}
> 
> 	location ~^/s2/(?<md5>[^/]+)/(?<exp>[^/]+)/(?<b>.*)/(?<f>.*).ts$ {
> 		secure_link $md5,$exp;
> 		secure_link_md5 "$secure_link_expires/$b enigma";
> 		if ($secure_link = "0") { return 410; }
> 		if ($secure_link = "") { return 403; }
> 		rewrite ^ /$b/$f.ts;
> 		alias /home/filme/download/;
> 		vod hls;
> 		include cors.vod;
> 	}
> 	location /hls/ {
> 		vod_segments_base_url https://$http_host/s2/$arg_md5/$arg_expires;
> 		secure_link $arg_md5,$arg_expires;
> 		secure_link_md5 "$secure_link_expires$hls_uri enigma";
> 		if ($secure_link = "0") { return 410; }
> 		if ($secure_link = "") { return 403; }
> 		alias /home/filme/download/;
> 		vod hls;
> 		include cors.vod;
> 	}
> }
> ```
> 
> to get links like:
> 
> //hls.example.com/hls/directory/src.mp4/index.m3u8?md5=PZRyYExZAGJvpHP9SNXaPg&expires=1548089721
> or //hls.example.com/src/directory/src.webm?md5=REqPrC7Q0vdxMZ53etE0pA&expires=1548089721
> 
> example in php
> 
> ```
> <?php
>     function buildSecureLink($path, $secret, $ttl, $string="")
>     {
>         $pa = dirname($path);
>         $expires = time() + $ttl;
>         $md5 = md5( "{$expires}{$pa}{$string} {$secret}", true);
>         $md5 = base64_encode($md5);
>         $md5 = strtr($md5, '+/', '-_');
>         $md5 = str_replace('=', '', $md5);
>         return $path . '?md5=' . $md5 . '&expires=' . $expires;
>     }
>     function to_player_sec($val){
>         return "//hls.example.com" . buildSecureLink($val, "enigma", 60*60*4);
>     }
>     $player = explode(" or ", str_replace("//hls.example.com", "", "//hls.example.com/hls/directory/src.mp4/index.m3u8 or //hls.example.com/src/directory/src.webm"));
>     $player = implode(" or ", array_map("to_player_sec", $player));
> ?>
> ```
> 
> upd
> files structure note:
> 
> ```
> /home/filme/download =>
>     directory =>
>         src.mp4
>         src.webm
>     other_dir_videoname =>
>         src.mp4
>         src.webm
>     ...
> ```

Can you please write another snippet without the or condition so i can just use it for .m3u8? its making so difficult for actually.

**Comment by ufukomer** [comment]
@citijk I think this config is not working for [multi url structure](https://github.com/kaltura/nginx-vod-module#multi-url-structure) or maybe I'm missing something.
