### ISSUE TITLE
Kaltura 404 Was it hacked?

### ISSUE THREAD

**Issue by RootPeter** [kaltura/nginx-vod-module#928]
Hello,

Sqlite.bz2 404 appears when my new server is installed. Why?

code：

`[root@s169257 ~]# rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
Retrieving http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
warning: /var/tmp/rpm-tmp.L3neKN: Header V4 RSA/SHA1 Signature, key ID ba443ef2: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:kaltura-release-13.4.0-4         ################################# [100%]
[root@s169257 ~]# yum install kaltura-nginx -y
Loaded plugins: fastestmirror
Kaltura                                                                                                                                                                | 2.9 kB  00:00:00     
Kaltura-noarch                                                                                                                                                         | 2.9 kB  00:00:00     
base                                                                                                                                                                   | 3.6 kB  00:00:00     
epel/x86_64/metalink                                                                                                                                                   |  24 kB  00:00:00     
epel                                                                                                                                                                   | 3.2 kB  00:00:00     
extras                                                                                                                                                                 | 3.4 kB  00:00:00     
group_cloud-init-el-stable                                                                                                                                             | 3.0 kB  00:00:00     
sensu                                                                                                                                                                  | 2.5 kB  00:00:00     
updates                                                                                                                                                                | 3.4 kB  00:00:00     
(1/4): epel/x86_64/updateinfo                                                                                                                                          | 932 kB  00:00:00     
(2/4): epel/x86_64/primary                                                                                                                                             | 3.6 MB  00:00:00     
Kaltura-noarch/7/primary_db    FAILED                                          
http://installrepo.kaltura.org/releases/latest/7/RPMS/noarch/repodata/cf8a036f63bef2fa2bbebce7753b8ead1990a7c89e03f5fd2af67caafd0ed733-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

(3/4): Kaltura/7/x86_64/primary_db                                                                                                                                     | 122 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * base: mirror.cherryservers.com
 * epel: mirror.duomenucentras.lt
 * extras: mirror.cherryservers.com
 * updates: mirror.cherryservers.com
Kaltura-noarch/7/primary_db    FAILED                                          
http://installrepo.kaltura.org/releases/latest/7/RPMS/noarch/repodata/cf8a036f63bef2fa2bbebce7753b8ead1990a7c89e03f5fd2af67caafd0ed733-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/7/RPMS/noarch/repodata/cf8a036f63bef2fa2bbebce7753b8ead1990a7c89e03f5fd2af67caafd0ed733-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

 One of the configured repositories failed (Kaltura Server arch independent),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=Kaltura-noarch ...

     4. Disable the repository permanently, so yum won't use it by default. Yum

        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable Kaltura-noarch
        or
            subscription-manager repos --disable=Kaltura-noarch

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=Kaltura-noarch.skip_if_unavailable=true

failure: repodata/cf8a036f63bef2fa2bbebce7753b8ead1990a7c89e03f5fd2af67caafd0ed733-primary.sqlite.bz2 from Kaltura-noarch: [Errno 256] No more mirrors to try.
http://installrepo.kaltura.org/releases/latest/7/RPMS/noarch/repodata/cf8a036f63bef2fa2bbebce7753b8ead1990a7c89e03f5fd2af67caafd0ed733-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
[root@s169257 ~]# yum updata *kaltura*
Loaded plugins: fastestmirror
No such command: updata. Please use /usr/bin/yum --help
[root@s169257 ~]#`

**Comment by jessp01** [comment]
Hi @RootPeter,

Since installrepo.kaltura.org is a CDN endpoint and we've just released a new Kaltura Server version [14.8.0], it may take a little while for all edges to sync with the origin server.
If you're having issues with fetching http://installrepo.kaltura.org/releases/rhel7/RPMS/x86_64/repodata, please edit /etc/yum.repos.d/kaltura.repo and replace 'installrepo.kaltura.org' with 'installrepo.origin.kaltura.org'.

Do let me know if you encounter additional issues.

Thanks,

**Comment by jessp01** [comment]
Closing due to lack of response. Feel free to reopen should you still encounter issues.
