### ISSUE TITLE
Relative URLs for HLS and DASH with Host Header?

### ISSUE THREAD

**Issue by pacepace** [kaltura/nginx-vod-module#932]
I'm wondering if there is a way to serve relative urls for HLS and DASH even if I'm sending a host header?  Trying to configure so that I can have multiple CDNs request from the same origin, while using a host header because we need that for SNI application routing, rather than having separate origins for each CDN to deal with the host header issue...

**Comment by erankor** [comment]
```
vod_dash_absolute_manifest_urls off;
vod_hls_absolute_master_urls off;
vod_hls_absolute_index_urls off;
```
Btw, we are using multiple CDNs with absolute URLs, we just configure the CDNs to send the original host header to the origin.

**Comment by pacepace** [comment]
That did the job.  Thank you for the help!
