### ISSUE TITLE
LNK2019 unresolved external symbol _uncompress referenced in function _mp4_parser_uncompress_moov

### ISSUE THREAD

**Issue by wws19125** [kaltura/nginx-vod-module#933]
I was compiling this module on windows7 with vs2010 express ,I'm almost there,I still got an error there,
![image](https://user-images.githubusercontent.com/3598933/49292821-48c18700-f4e9-11e8-990e-7c68cdaf087b.png)

nginx.exe was generated success without nginx-vod-module

**Comment by wws19125** [comment]
![image](https://user-images.githubusercontent.com/3598933/49292460-43b00800-f4e8-11e8-8893-b97eb9e5d5ae.png)
![image](https://user-images.githubusercontent.com/3598933/49292467-46aaf880-f4e8-11e8-8d40-202b7be4eec4.png)
so would you help to resolve this problem,tks

**Comment by erankor** [comment]
This function is indeed coming from zlib, as you highlighted. If I understand correctly, you are statically linking this module with zlib sources, and in that case, you should check why the uncompress function wasn't exported from zlib. One possibility may be that the module is including zlib headers from version X and linking to sources/library of version Y.
That said, easiest fix is just to disable this feature - this code handles mp4s with compressed moov atoms, I've bumped into very few such files, as most encoders don't support it. If you set VOD_HAVE_ZLIB to 0, all the code that handles this feature won't be compiled, and this error would go away.

**Comment by wws19125** [comment]
> This function is indeed coming from zlib, as you highlighted. If I understand correctly, you are statically linking this module with zlib sources, and in that case, you should check why the uncompress function wasn't exported from zlib. One possibility may be that the module is including zlib headers from version X and linking to sources/library of version Y.
> That said, easiest fix is just to disable this feature - this code handles mp4s with compressed moov atoms, I've bumped into very few such files, as most encoders don't support it. If you set VOD_HAVE_ZLIB to 0, all the code that handles this feature won't be compiled, and this error would go away.

It's done,tks

**Comment by erankor** [comment]
Thanks for the update! 
Would be great if you could share some notes that explain how you compiled it on Windows, there was someone who asked about it before...

**Comment by wws19125** [comment]
I'll do it later

**Comment by erankor** [comment]
Thanks @wws19125!
