### ISSUE TITLE
avfilter / avcodec not found

### ISSUE THREAD

**Issue by jeffc030** [kaltura/nginx-vod-module#935]
I'm having a really difficult time getting nginx to compile with avcodec and avfilter.   I've rebuilt ffmpeg with both of them, and seems like it is there.  But I continue to get not found when configuring nginx. I'm on Ubuntu 18.04.  Any guidance would be much appreciated.  Trying to make use of the speed controls.

ffmpeg
ffmpeg version N-92590-gf7faaa8 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --prefix=/home/ubuntu/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/ubuntu/ffmpeg_build/include --extra-ldflags=-L/home/ubuntu/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/ubuntu/bin --enable-gpl --enable-libfdk-aac --enable-libx264 --enable-avfilter --enable-avcodec --enable-nonfree
  libavutil      56. 24.101 / 56. 24.101
  libavcodec     58. 41.100 / 58. 41.100
  libavformat    58. 23.102 / 58. 23.102
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100

< nginx ./configure >
checking for libavcodec ... not found
checking for libswscale ... found
checking for libavfilter ... not found

**Comment by erankor** [comment]
See this comment -
https://github.com/kaltura/nginx-vod-module/issues/795#issuecomment-366971362

**Comment by jeffc030** [comment]
Thanks.  This one was tricky.  Key was to --enable-shared on the ffmpeg build, and make sure not to have the deb packages installed.

**Comment by fahricetin** [comment]
Hi 
sudo apt  install libavfilter-dev
sudo apt install libavfilter
and also above command  installs libswscale.

regards
