### ISSUE TITLE
Error 503, if JSON size more then 1024 bytes

### ISSUE THREAD

**Issue by makss** [kaltura/nginx-vod-module#936]
Symptoms, `nginx_errors.log`:
~~~
379 media_set_parse_json: failed to parse json -1: expected 0x7b got 0x0 while sending to client
~~~

That such a surprise happened. ;-)
Why? 

ps: It seems a limitation [here](https://github.com/kaltura/nginx-vod-module/blob/83c135da27b7fb38c8097db251ee5792c5a6b1b1/ngx_http_vod_conf.c#L232).

**Comment by fsouza** [comment]
@makss if you need more than 1KB, you can set the config parameter [`vod_max_mapping_response_size`](https://github.com/kaltura/nginx-vod-module#vod_max_mapping_response_size)

**Comment by makss** [comment]
@fsouza , thanks for the reply, it helped me.

Maybe in the future it is necessary to increase the default value for the JSON file?

An interesting observation, for `vod_max_upstream_headers_size` 4K, and for 1K data itself.
It is assumed that by default the size of the headers is 4 times larger than the data,  something is wrong here. :)

**Comment by erankor** [comment]
The assumption is that 90% of the people who use mapped mode, use trivial JSONs that return a single MP4. For such JSONs, 1k should be more than enough.
The few users who use complex JSONs (playlists etc.) will indeed have to increase the value of this parameter.

**Comment by jeffc030** [comment]
Came here to post on this very issue.  So happy to see the answer right here for me :)
