### ISSUE TITLE
Performance advice

### ISSUE THREAD

**Issue by reyakov** [kaltura/nginx-vod-module#937]
Hi,
I'm building a video streaming site, can you advise me about hardware for about 100 CCU for per video.
In my mind, I will setup:
- Store video in Backblaze B2
- Nginx VOD remote
- Cloudflare for CDN

**Comment by erankor** [comment]
I think the way to approach this is to estimate the amount of origin traffic you're going to get, and plan accordingly. If you take a reasonably sized server, the limiting factor will most likely be the network.
The origin traffic depends on multiple factors -
1. The size of the catalog
2. The distribution of video being played (e.g. few "hot" videos / long tail content)
3. The caching ratio of the CDN - maybe Cloudflare can provide you some rough numbers for this (usually different for live vs. vod)
