### ISSUE TITLE
Growing clip size in remote mode

### ISSUE THREAD

**Issue by BrightSoul** [kaltura/nginx-vod-module#940]
Hello everyone and thanks for your efforts. This is such a great project.
I've configured a Linux machine as follows:
```
standard nginx used for cache -> nginx-vox-module (vod_mode remote) -> s3 storage
```
And everything is working fine and super fast, both in hls and progressive download flavors. 
See this video for instance. It's a 158MB video with a duration of 45 minutes.
[https://video.civicam.it/hls/torreboldone/2017/2017-12-27_cc_torreboldone.mp4/index.m3u8](https://video.civicam.it/hls/torreboldone/2017/2017-12-27_cc_torreboldone.mp4/index.m3u8)

Now, suppose I want to download a 1-minute fragment of that video near the beginning. Here's the URL for that. As expected, I get a 1-minute fragment with a size of 4MB.
[https://video.civicam.it/pd/clipFrom/1000/clipTo/61000/torreboldone/2017/2017-12-27_cc_torreboldone.mp4](https://video.civicam.it/pd/clipFrom/1000/clipTo/61000/torreboldone/2017/2017-12-27_cc_torreboldone.mp4)

Then, I want to download another 1-minute fragment but this time near the end. Here's the URL.
[https://video.civicam.it/pd/clipFrom/2001000/clipTo/2061000/torreboldone/2017/2017-12-27_cc_torreboldone.mp4](https://video.civicam.it/pd/clipFrom/2001000/clipTo/2061000/torreboldone/2017/2017-12-27_cc_torreboldone.mp4)
When I play this video, it has a duration of 1 minute as expected **but its size is now 107MB**. Why?
So, it seems the video metadata is correct but then the mp4 file includes all the video content up to that point (?)

Here's my configuration.
```
server {

        listen       127.0.0.1:8080;
        server_name  _;
        root         html;


        error_log  logs/error.log;
        access_log  logs/access.log;


        # vod settings
        vod_mode remote;
        vod_upstream_location /s3;
        vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
        vod_last_modified_types *;

        # vod caches
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;

        # gzip manifests
        gzip on;
        gzip_types application/vnd.apple.mpegurl;

        location ^~ /s3/hls/ {
                internal;
                proxy_pass https://****/;
                proxy_set_header Host ****;

                aws_access_key ****;
                aws_secret_key ****;
                s3_bucket ****;
                chop_prefix /s3/hls;
                proxy_set_header Authorization $s3_auth_token;
                proxy_set_header x-amz-date $aws_date;
        }

        location ^~ /s3/pd/ {
                internal;
                proxy_pass https://****/;
                proxy_set_header Host ****;

                aws_access_key ****;
                aws_secret_key ****;
                s3_bucket ****;
                chop_prefix /s3/pd;
                proxy_set_header Authorization $s3_auth_token;
                proxy_set_header x-amz-date $aws_date;
        }
		
        location ~ ^/hls/ {
                vod hls;

                add_header Access-Control-Allow-Headers '*';
                add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                add_header Access-Control-Allow-Origin '*';
                expires 100d;
        }

        location ~ ^/pd/.*?([^/]+)$ {
                add_header Content-Disposition 'attachment; filename="$1"';
                vod none;
        }

        location ~ /status/ {
                vod_status;
        }
}
```

Any advice on this? Thanks.

**Comment by BrightSoul** [comment]
Update: this seems to be an issue with the specific video file. Here's other issues I've observed with other videos:

- Clip size is correct, video is correct but no audio;
- Clip size is correct but no keyframe at the beginning, so there's a few seconds of black. Audio is correct.

**Comment by BrightSoul** [comment]
I managed to fix the clip size problem by running this ffmpeg command:
```
ffmpeg -i in.mp4 -movflags faststart -c copy out.mp4
```
Still no solution for the two latest problems: missing audio and missing initial keyframe.

**Comment by erankor** [comment]
Regarding the first issue, of large clip size - this file has 3 streams - video, audio, data. The video & audio streams are muxed nicely, but the data stream is not. There is some packet of the data stream that is 100MB apart from the audio/video for this time range. And, in progressive download, the module includes all unrecognized streams (in this case - data) in output .

# /web/content/shared/bin/ffmpeg-3.2-bin/ffprobe.sh -i 2017-12-27_cc_torreboldone.mp4 -show_packets 2>/dev/null | awk -F= '$1=="codec_type" {c=$2} $1=="pts_time" {t=$2} $1=="pos" {print c,t,$2}' | awk '$2>2001 && $2<2061' | sort -gk3 | tail -1
audio 2060.940000 126530077
# /web/content/shared/bin/ffmpeg-3.2-bin/ffprobe.sh -i 2017-12-27_cc_torreboldone.mp4 -show_packets 2>/dev/null | awk -F= '$1=="codec_type" {c=$2} $1=="pts_time" {t=$2} $1=="pos" {print c,t,$2}' | awk '$2>2001 && $2<2061' | sort -gk3 | head -1
data 2002.602000 14688846

126530077  - 14688846 = 111841231, which matches the response size you're getting.

**Comment by erankor** [comment]
"Clip size is correct, video is correct but no audio;
https://video.civicam.it/pd/clipFrom/1200000/clipTo/1260000/persiceto/2017/2017-12-20_cc_persiceto.mp4"
I'm getting audio here, maybe you replaced the mp4 file since you posted this?

**Comment by erankor** [comment]
Regarding the key frame issue, this is expected, for progressive download the module doesn't align the clipFrom to the next key frame. In our system, we force a key frame every 2 seconds during transcoding, so we just make sure to pass a clipFrom value that is a multiple of 2 sec, and that solves this problem.

**Comment by BrightSoul** [comment]
Hello and thank you so much for your replies.

> The video & audio streams are muxed nicely, but the data stream is not.
Ok, I might as well remove the data stream. The thing is, this videos come from different IP cams and encoders and I have no control over them. But I can use ffmpeg to somehow fix them without reencoding. The faststart flag seemed to help.

> just make sure to pass a clipFrom value that is a multiple of 2 sec
Right, will do.

> I'm getting audio here, maybe you replaced the mp4 file since you posted this?
Uhm, no, I didn't replace the file but I've realized I get no audio only when I play it with VLC. If I play it with Windows Media Player or the new Windows 10 Movies & TV app then I can hear it just fine. What a strange behavior, I wonder why VLC doesn't like it.

Bye and again, thanks.

**Comment by erankor** [comment]
No problem.
Regarding the first issue, if you want, you can patch the code so that it will ignore non-audio/video tracks - just add `else return VOD_OK;` after this if block - https://github.com/kaltura/nginx-vod-module/blob/master/vod/mp4/mp4_clipper.c#L1506

**Comment by BrightSoul** [comment]
Thanks, it's all clear now, I'm closing the issue.
