### ISSUE TITLE
Where is the Segment Store?

### ISSUE THREAD

**Issue by hellfire1980** [kaltura/nginx-vod-module#947]
While segment are slice on the fly when a vod file is request. Where actually is he segment .ts file stored?

**Comment by erankor** [comment]
It is not stored anywhere, it is built in memory and returned to the client.

**Comment by erankor** [comment]
No, the file is processed in chunks, as it is being requested. 
For example, if you request segment 10, nginx-vod-module will see which video/audio frames correspond to this segment, and process only them.
