### ISSUE TITLE
Support for FLAC in ISO-BMFF/MP4 for MPEG DASH packaging?

### ISSUE THREAD

**Issue by mforchner** [kaltura/nginx-vod-module#948]
Dear @erankor,

It has been possible for a while now to put flac into an mp4, e.g. with ffmpeg's experimental feature:
ffmpeg -i input.flac -strict experimental -c copy output.mp4 -y

Would it be possible to support mpeg dash packaging for files like this? We would have several client applications that should be able to play back the resulting manifest and it would be great to make this work.

This is an example mp4 file you could use for testing: https://bit.ly/2Ts3A6q  (h264 video, flac audio, works for direct progressive download playback in Chrome / FF on MacOS, for example)

Thank you for all your work, nginx-vod-module is just great!

---

See the topic in other projects:

- https://github.com/google/ExoPlayer/issues/4883 (incl. dash manifest example)
- https://googlechrome.github.io/samples/media/flac-in-mp4-for-mse.html

**Comment by erankor** [comment]
I tried the sample MPD from the ExoPlayer issue with Shaka player in Chrome & Firefox and didn't play, am I missing something?
The MP4 you included is playing correctly.

**Comment by mforchner** [comment]
I think it depends on the manifest structure then. The example manifest worked in exoplayer. Not sure if a manifest including flac will be handled by all players correctly out of the box, if flac is the only audio choice. This might need adaptions on player side, especially for playback in the browser. 

I'll try to create a working setup (manifest + player) for you to test.
