### ISSUE TITLE
support for widevine DRM?

### ISSUE THREAD

**Issue by wnpllrzodiac** [kaltura/nginx-vod-module#949]
I check edash_packager.c, NOT found code implement about widevine part.Only found fairplay and mss.
Did it mean No widevine support?

**Comment by erankor** [comment]
Widevine is supported - https://github.com/kaltura/nginx-vod-module#verified-configurations

**Comment by erankor** [comment]
In terms of nginx conf, something like this - 
```
location /edash/ {
	vod dash;
	vod_segment_duration 4000;
	vod_manifest_duration_policy min;
	vod_align_segments_to_key_frames on;
	vod_dash_manifest_format segmenttemplate;
	vod_dash_profiles urn:mpeg:dash:profile:isoff-live:2011;

	vod_drm_enabled on;
	vod_drm_request_uri "/drm/$vod_suburi";

	vod_last_modified_types *;
	add_header Access-Control-Allow-Headers '*';
	add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
	add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
	add_header Access-Control-Allow-Origin '*';
	expires 100d;
}
```
I'm not an expert on DRM, but in high level, you need some server that will generate the media encryption keys. This server should reply to nginx-vod-module's requests for keys. 
In our system, this server also handles client requests for licenses. In the case of Widevine, the license response is generated by Google, so our server proxies the request to them. I'm not sure if it has to work this way, maybe if you have a simple setup, you can just have the player connect to google directly.

**Comment by wnpllrzodiac** [comment]
thank You very much for the reply. I will do some research about it.
