### ISSUE TITLE
Multiple subtitle languages in HLS stream?

### ISSUE THREAD

**Issue by katsar0v** [kaltura/nginx-vod-module#950]
Is this possible yet? Currently I get only one subtitle language - "English". My url is:
`/hls/videos/video,_360p.mp4,_480p.mp4,_sub.vtt,.urlset/master.m3u8`

I want to add also spanish and german subtitles, am using this player - https://github.com/clappr/clappr

**Comment by erankor** [comment]
Yes, multiple subtitle languages are supported.
The URL you pasted seems to have only one (/hls/videos/video_sub.vtt). If you have multiple, you will to specify the languages, either using /lang/ or using mapped mode.

**Comment by katsar0v** [comment]
@erankor Thanks for the clarification. What would be an example for the url, so I could have both english and spanish subtitles?
`/hls/videos/video,_360p.mp4,_480p.mp4,_sub.vtt,_sub-es.vtt,.urlset/master.m3u8` <- is not working

**Comment by erankor** [comment]
something like -
`/hls/videos/,video_360p.mp4,video_480p.mp4,lang/eng/video_sub.vtt,lang/spa/video_sub-es.vtt,.urlset/master.m3u8`

**Comment by katsar0v** [comment]
@erankor are you sure this works?

My hls url: `/hls/chap-00/vid01,_360p.mp4,_480p.mp4,_720p.mp4,_1080p.mp4,lang/bul/sub_bg.vtt,lang/spa/sub_es.vtt,.urlset/master.m3u8"`

error: `[error] 10#10: *399 ngx_file_reader_update_state_file_info: open() "/opt/static/videos/chap-00/vid01lang/spa/sub_es.vtt" failed`

**Comment by erankor** [comment]
This is not like the sample I pasted, you'll have to copy the `vid01` to all parts, otherwise the `lang` won't be identified -
`/hls/chap-00/,vid01_360p.mp4,vid01_480p.mp4,vid01_720p.mp4,vid01_1080p.mp4,lang/bul/vid01_sub_bg.vtt,lang/spa/vid01_sub_es.vtt,.urlset/master.m3u8`

**Comment by katsar0v** [comment]
Oh, seems I got the syntax wrong (which is **also not documented**), will try again, thanks

**Comment by katsar0v** [comment]
It works! Thanks!
