### ISSUE TITLE
HLS + Widevine Classic

### ISSUE THREAD

**Issue by ppllaxxa** [kaltura/nginx-vod-module#954]
Hello,

Is it possible to deliver HLS+Widevine Classic using nginx-vod-module?

And is it possible to stream wvm format?

**Comment by erankor** [comment]
HLS + Widevine is supported, sample configuration here - https://github.com/kaltura/nginx-vod-module#sample-configurations.
But afaik that is not considered 'Widevine classic', widevine classic is WVM, which is not supported.
