### ISSUE TITLE
Build Installation Error

### ISSUE THREAD

**Issue by sheriffmarley** [kaltura/nginx-vod-module#961]
Hi,

since today I get an error if I try to build nginx with the vod module. End of last month havn't had any issues.

I'm using the latest master:
wget https://github.com/kaltura/nginx-vod-module/archive/master.zip;

1. Configure
./configure --error-log-path=/var/log/nginx/error.log --with-debug --with-http_auth_request_module --with-http_stub_status_module --with-http_mp4_module --add-module=../nginx-upload-module --add-module=../nginx-vod-module --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_realip_module

Result of make:
-ldl -lpthread -lpthread -lcrypt -lz -lcrypto -ldl -lpthread -lavcodec -lavutil -lm -lswscale -lpcre -lssl -lcrypto -ldl -lpthread -lz \
-Wl,-E
objs/addon/filters/audio_encoder.o: In function `audio_encoder_write_packet':
/root/nginx-1.15.8/../nginx-vod-module/vod/filters/audio_encoder.c:161: undefined reference to `audio_filter_alloc_memory_frame'
objs/addon/filters/volume_map.o: In function `volume_map_encoder_write_frame':
/root/nginx-1.15.8/../nginx-vod-module/vod/filters/volume_map.c:137: undefined reference to `audio_filter_alloc_memory_frame'
collect2: error: ld returned 1 exit status
objs/Makefile:348: die Regel für Ziel „objs/nginx“ scheiterte
make[1]: *** [objs/nginx] Fehler 1
make[1]: Verzeichnis „/root/nginx-1.15.8“ wird verlassen
Makefile:8: die Regel für Ziel „build“ scheiterte
make: *** [build] Fehler 2

**Comment by erankor** [comment]
It seems you have libavcodec but not libavfilter, try this pull #962

**Comment by sheriffmarley** [comment]
I installed `libav-tools ` and `libavcodec-extra ` but the issue still exists. libavfilter should exists in libav-tools, or am i wrong?

**Comment by erankor** [comment]
Sorry, I'm not familiar with these packages, we are compiling ffmpeg ourselves.
But anyway, unless you are using features like playback rate or gain control, you don't need to worry about it, 99% of the functionality does not depend on libavfilter.

**Comment by jessp01** [comment]
@sheriffmarley  - Please note that the VOD module can work against FFmpeg of version 3 and above [tested with up to FFmpeg 4.0.2 with libavutil.so.56, libavfilter.so.7 and libavcodec.so.58]. You did not state your Linux distribution but if the FFmpeg packages in its official repo are of an older version, it will not work. You can always deploy the kaltura-ffmpeg packages from our own repos [see the README for detailed instructions]. You can also install the kaltura-nginx packages so that you won't need to build the module at all.

**Comment by sheriffmarley** [comment]
That's weird since we're using the newest version of ffmpeg. Will take a deeper look into it. Thanks for the hints!

**Comment by jessp01** [comment]
Hi @sheriffmarley - any news on this?

**Comment by sheriffmarley** [comment]
@jessp01 havn't had time to tackle this. Guess will do it next week

**Comment by jessp01** [comment]
Hi @sheriffmarley,

Can this be closed?

Thanks,
