### ISSUE TITLE
DASH + CENC - PR is not working

### ISSUE THREAD

**Issue by ppllaxxa** [kaltura/nginx-vod-module#963]
Hello,

We are using ezedrm as pssh provider.
Below pssh was used for generating 'manifest' in attachment.
`[{"pssh": [{"data": "lgIAAAEAAQCMAjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4ASgBMAE8AQwBvADgAUQBaADkAVgBXAFAAQQBJAGQAcABKAC8AOQBpAGgAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBXAE0ATgBmAEEAdABEADYASwA3AHcAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AcABsAGEAeQByAGUAYQBkAHkALgBlAHoAZAByAG0ALgBjAG8AbQAvAGMAZQBuAGMAeQAvAHAAcgBlAGEAdQB0AGgALgBhAHMAcAB4AD8AcABYAD0ANgBGADkAMgA3ADQAPAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=","uuid": "9a04f079-9840-4286-ab92-e65be0885f95"},{"data": "CAESEKOCsyQZxFX1jwCHaSf/YocaCG1vdmlkb25lIhC9dDilWTbaQpoPVT+kow1GKgJTRA==","uuid": "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"}],"key": "PeGPlCfB3yy7kZun2d2k8w==","key_id": "o4KzJBnEVfWPAIdpJ/9ihw=="}]`

And we asked ezedrm to provide working example of DASH + CENC, 'ezdrm_example-mpd' in attachment.

What I could see here the difference is that in manifest which was generated by nginx-vod-module in section for PR we have only mspr:pro, but in example from ezedrm we have mspr:pro and cenc:pssh.
As a result example of ezedrm is working well, but manifest from nginx-vod-module is not.

Could you please help to understand what is the reason?
I renamed *.mpd to *.txt for attachment.

[manifest.txt](https://github.com/kaltura/nginx-vod-module/files/2900083/manifest.txt)
[ezdrm_example-mpd.txt](https://github.com/kaltura/nginx-vod-module/files/2900084/ezdrm_example-mpd.txt)

**Comment by erankor** [comment]
Did you actually try to add cenc:pssh and saw that it works?
There are many other differences between the manifests... e.g. the dash profile is different

**Comment by ppllaxxa** [comment]
Hello, I don't think that dash profile is the reason, because the same playlist without DRM is working well.

Regarding to 'Did you actually try to add cenc:pssh and saw that it works?' - I didn't find any settings in nginx-vod-module which allows to include cenc:pssh tag for PR in DASH manifest.

**Comment by erankor** [comment]
I meant that you can manually edit the MPD - if you are using absolute URLs, you can host the edited MPD on some other server/location

**Comment by ppllaxxa** [comment]
Ok, thank you, I will try.

Meanwhile, maybe you have some advise about playing DASH + PR (CENC) on WebOs 3.0/2.0?

**Comment by erankor** [comment]
We are using DASH + PR, but don't think we ever tried webOS. 
If you have PR working for you in Edge but not on webOS, it may be related to the security level in the license. We had this problem at some point, where a device would not play with licenses with SL3000, only SL2000.

**Comment by ppllaxxa** [comment]
Thank you for your help.
