### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

### ISSUE THREAD

**Issue by ppllaxxa** [kaltura/nginx-vod-module#968]
Hello,

We got an issue with playback in JW player:
https://developer.jwplayer.com/tools/stream-tester/

There is the stream:
https://api-develop.plsolutions.pro/streamer/dash/none/1e08cf62-9698-4646-8fe6-573a1e93ee14/x264/manifest.mpd

When we are trying to playback it we got an error:
net::ERR_CONTENT_LENGTH_MISMATCH

There is part of our config:
location ~ ^/streamer/dash/none/[0-9a-z-]+/(x264|x265)/(ld/|sd/|hd/|fhd/|uhd/)? {
			vod dash;
			# vod_dash_manifest_format segmentlist;
			vod_dash_absolute_manifest_urls off;
			# vod_base_url $1;
			vod_align_segments_to_key_frames on;
			add_header Access-Control-Allow-Headers '\*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
		}

Seems like Content-Length in header and actual length of response are mismatch.

**Comment by ppllaxxa** [comment]
Hello,

Seems like Content-Length in header and actual length of response is accurate. But for some reason downloading of segments for high resolutions takes very long time.

Do you have any thoughts?

**Comment by erankor** [comment]
How long does it take if you curl it locally from the nginx server? Are you using local mode or remote?

**Comment by ppllaxxa** [comment]
Yep, you are right. Segment was downloaded less then in 1 second from another pod in one network with vod-module. Seems like the problem in our environment. Thank you!
