### ISSUE TITLE
Option to use sequence id from mapped response in master playlists

### ISSUE THREAD

**Issue by gryphon** [kaltura/nginx-vod-module#977]
If we have changeable mapped response (for example if we are still processing video files on convertors) we need to set exact ID of required file instead its sequence number (f1,f2,f3...). Because if we cache responses we may get result for incorrect sequence if it changes an order in mapped response json.

**Comment by erankor** [comment]
If you set the sequence id in the JSON, and its length is less than 11 chars, it will be used instead of 'f' -
https://github.com/kaltura/nginx-vod-module/blob/master/vod/manifest_utils.c#L360

**Comment by gryphon** [comment]
Thank you, that works.
