### ISSUE TITLE
hds error

### ISSUE THREAD

**Issue by kernelheaders** [kaltura/nginx-vod-module#98]
Hello , 

I recieve this error ,

2015/05/25 15:25:34 [error] 2438#0: *3858588 hds_muxer_process_frames: no data was handled, probably a truncated file while processing frames, client: 1.1.1.1, server: *.*.*, request: "GET /xxxx/xxx/xx/xx/blabla_480p.mp4/frag-v1-a1-Seg1-Frag11 HTTP/1.0", host: "*.*.*.*", referrer: "http://player.swf..."

**Comment by erankor** [comment]
1. does the file play correctly in progressive download till its end ?
2. if so, can you share a URL to the file ?

**Comment by kernelheaders** [comment]
1. no , green screen . 
2. do you have mail to share URL ?

**Comment by erankor** [comment]
If it doesn't play in progressive download, then I don't understand what is the problem, the video file is corrupt, nothing this module can do about it.
If you think it's still relevant, you can send me the link to eran.kornblau at kaltura dot com

**Comment by kernelheaders** [comment]
i sent hds and mp4 links via email .

**Comment by erankor** [comment]
closing due to unresponsiveness
