### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ElektrikSpark** [kaltura/nginx-vod-module#986]
I am using the hls.js module to request the vod, but I am getting CORS errors despite setting the headers on my nginx.conf.

```
worker_processes  auto;
error_log logs/error.log debug;
events {
    worker_connections  1024;
}

# RTMP configuration
rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            # Turn on HLS
            hls on;
            hls_path /mnt/hls/;
            hls_fragment 3;
            hls_playlist_length 60;
            # record stream to folder /film/
            record all;
            record_path /film;
            # disable consuming the stream from nginx as rtmp
			deny play all;
        }
    }
}

http {
    sendfile off;
    tcp_nopush on;
    default_type application/octet-stream;

    server {
        listen 8080;

        location /hls {
            # Disable cache
            add_header Cache-Control no-cache;

            # CORS setup
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';

            # allow CORS preflight requests
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            root /mnt/;
        }
    }

    server {
        listen 8384;

        # vod caches
        vod_metadata_cache metadata_cache 256m;
        vod_response_cache response_cache 128m;

        # vod settings
        vod_mode local;
        vod_segment_duration 2000; # 2s
        vod_align_segments_to_key_frames on;

        #file handle caching / aio
        open_file_cache max=1000 inactive=5m;
        open_file_cache_valid 2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors on;
        aio on;

        location /vod/ {
            alias /film/;
            vod hls;
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
        }
    }
}
```

Please let me know what I am missing, thank you.

**Comment by erankor** [comment]
1. Did you verify the headers are indeed being sent & not more than once?
2. Any chance you are testing from an HTTPS site?

**Comment by ElektrikSpark** [comment]
Thank you for the response.  How would I go about verifying that the headers are set, or that the nginx-vod-module is being set up correctly?  I believe that my nginx.conf is correct, unless there is something that I am missing, so that leaves me to look at whether the location /vod/ is being set up in the first place.  I will continue testing things and report back if I find anything.

**Comment by ElektrikSpark** [comment]
It seems that something is not being set up correctly in relation to the nginx-vod-module.  If I were to try to request, from hls.js, a path that does not exist, such as ".../vodd/...", I get the same error.

**Comment by ElektrikSpark** [comment]
I guess what would help most is an example nginx.conf/implementation that I can reference.  I will look for something, but if you know of any great resources let me know.

**Comment by ElektrikSpark** [comment]
I have been following along with this resource, https://harry.web.id/2018/11/18/ubuntu-18-04-compile-nginx-rtmp-vod-hls/.  Is there something incorrect in this resource's implementation of the module?

**Comment by ElektrikSpark** [comment]
Do I have to convert the .flv files to .mp4 before the VOD can be created?

**Comment by erankor** [comment]
1. You should check the nginx error log
2. Yes, you need to package the files in MP4, FLV is not supported

**Comment by ElektrikSpark** [comment]
Sorry to continue this saga, but I hope this to be the last question.  I now have an mp4 file, but when I look at error.log there is one error for `ngx_http_vod_handle_read_completed: bytes read is zero while reading media header`.  #884 concludes that this is file corruption, but I am unsure what is causing this corruption as when I `ls -sh $file.mp4` there is a sizable amount of memory (latest test was 6.1M).  Could this error also indicate that no file is located at the requested path?  I will attach my current nginx.conf for some context.  Thank you again.
[nginx.txt](https://github.com/kaltura/nginx-vod-module/files/3158688/nginx.txt)

**Comment by erankor** [comment]
This error doesn't necessarily mean the file is small, it means it's corrupt.
Try to play the mp4 file directly, most likely, it won't play

**Comment by ElektrikSpark** [comment]
Since I was having trouble with using the rtmp server as input, I changed to the .flv file on a `exec_record_done` call.  This works, but if I start and end the stream again the file at /vod/streamkey/index.m3u8 is the same.  This is fine, but how do I access 'n' stream, or how do I overwrite index.m3u8 at a minimum.
