### ISSUE TITLE
No matching streams were found

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#987]
HI Eran, 

We tried to form a mp4 file from series of chunked m4s file. But NGINX VoD module gives below error while playing 

> ngx_http_vod_validate_streams: no matching streams were found

Media Info of mp4 file is 

General
Complete name                            : D:\SegMP4.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : iso5 (iso6/mp41)
File size                                : 10.5 MiB
Duration                                 : 1 min 48 s
Overall bit rate                         : 814 kb/s
Writing application                      : Lavf58.12.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 min 48 s
Bit rate                                 : 811 kb/s
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.117
Stream size                              : 10.4 MiB (100%)

Text #1
ID                                       : 1-CC1
Format                                   : EIA-608
Muxing mode                              : SCTE 128 / DTVCC Transport
Muxing mode, more info                   : Muxed in Video #1
Duration                                 : 1 min 48 s
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
Encoded stream size                      : 0.00 Byte (0%)
CaptionServiceName                       : CC1

Algorithm we followed to form a mp4 from m4s segments is 

`cat` init-stream0.m4s >> source.mp4
`for` i in `ls video0-640x360_high_1100*.m4s`; do echo $i; cat $i >> source.mp4; done

We are not able to generate MPEG-DASH or HLS stream with this MPEG4 file. Can you please explain us the issue and how to resolve it

**Comment by erankor** [comment]
Fragmented MP4 input is not supported, you will need to repackage it to regular MP4 (e.g. using ffmpeg)

**Comment by Natarajan92** [comment]
Hi Eran, 

Thank you for your explanation.

**Comment by Natarajan92** [comment]
Hi Eran, 

We faced another issue with slight difference in error description, So am using same ticket instead of creating new one.

Issue description : 

Client keep on loading for frames. Not closed playback. 

Nginx Access Log: 

`1x.x.x.x - - [13/May/2019:01:08:43 -0400] "GET /mnt/dashEnc/TestMP4/stb-/fragment-1707-f2-v1-x3.m4s HTTP/1.1" 404 324 0.000 "-" "Client" "-" - "-" "xx.xx.xx.xx:xxxx" 48120 - - 291 "-" "x.8xx.1x.x" "-" "-" "-" 43573 
x.x.x.xx - - [13/May/2019:01:08:43 -0400] "GET /mnt/TestMP4/stb-/fragment-1707-f2-v1-x3.m4s HTTP/1.1" 404 324 0.000 "-" "Client" "-" - "-" "x.x.x.x:xxxx" 48120 - - 291 "-" "x.x.x.xx" "-" "-" "-" 43574 ` 

In access log, we are seeing 404 response. It looks some issue on on-fly packaging

Error Logs:

`2019/05/13 01:04:18 [error] 48121#48121: *43546 ngx_http_vod_validate_streams: no matching streams were found, probably invalid segment index, client: x.x.x.xx, server: localhost, request: "GET /TestMP4/stb-/fragment-1707-f1-v1-x3.m4s HTTP/1.1", host: "xx.xx.xx.xx:xxxx"
2019/05/13 01:04:18 [info] 48121#48121: *43546 client 10.55.1.11 closed keepalive connection`

In error log, we are seeing error as ** no matching streams were found, probably invalid segment index**

Can you please suggest us on how to proceed further for solving this issue.

**Comment by erankor** [comment]
One possible reason may be that you have several renditions with slightly different lengths. This can make the request for segment 1707 (in this case...) work on one rendition, but fail on another.
If that is indeed the problem, setting `vod_manifest_duration_policy` to `min` would solve it.

**Comment by Natarajan92** [comment]
Yes you are correct, i have checked run time of each representation. Video files length is same but audio file length is higher

**Comment by Natarajan92** [comment]
HI, 

Its working as expected by setting  vod_manifest_duration_policy to min . 

Thanks,
Anand S
