### ISSUE TITLE
An error occurred after enabling DRM

### ISSUE THREAD

**Issue by yuanliuu** [kaltura/nginx-vod-module#988]
Hi @erankor !
I compiled the module correctly and it works well, thanks for your contribution. But I have a little trouble, after enabling DRM according to the doc, I can't get manifest.mpd and get the following error:

_ngx_http_vod_drm_info_request_finished: not enough room in buffer for null terminator while sending response to client, ..._

The following is my configuration:

**nginx.conf**
```nginx
location /dash/ {
	vod dash;
	vod_drm_single_key on;
	vod_drm_upstream_location /enc;
	vod_drm_request_uri /key.json;
	vod_drm_enabled on;

	add_header Access-Control-Allow-Headers '*';
	add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
	add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
	add_header Access-Control-Allow-Origin '*';
}
```
**DRM JSON**
```json
[{
	"pssh": [{
			"data": "CAESEGMyZjg2MTczN2NjNGYzODIaB2thbHR1cmEiCjBfbmptaWlwbXAqBVNEX0hE", 
			"uuid": "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"
		}], 
	"key": "GzoNU9Dfwc//Iq3/zbzMUw==", 
	"key_id": "YzJmODYxNzM3Y2M0ZjM4Mg=="
}]
```
Can you give me some advice to help me solve this problem?

**Comment by Yuanliuu** [comment]
"/enc" is a local dir, "/www/wwwroot/vod/enc"

server
{
	listen 80;
	server_name 127.0.0.1;
	root /www/wwwroot/vod;
    
	vod_mode                           local;
	vod_metadata_cache                 metadata_cache 16m;
	vod_response_cache                 response_cache 128m;
	vod_last_modified_types            *;
	vod_base_url                       "//$http_host";
	vod_segment_duration               9000;
	vod_align_segments_to_key_frames   on;
	vod_dash_fragment_file_name_prefix "segment";
	vod_hls_segment_file_name_prefix   "segment";
	vod_manifest_segment_durations_mode accurate;
    
	open_file_cache          max=1000 inactive=5m;
	open_file_cache_valid    2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors   on;
	aio on;
    
	gzip on;
	gzip_types application/vnd.apple.mpegurl application/dash+xml;	
	...	
	location /dash/ {
		vod dash;
		alias /www/wwwroot/stream/videos/;
		
		vod_drm_single_key         on;
		vod_drm_upstream_location  /enc;
		vod_drm_request_uri        /key.json;
		vod_drm_enabled            on;

		add_header Access-Control-Allow-Headers '*';
		add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
		add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		add_header Access-Control-Allow-Origin '*';
	}
}

**Comment by Yuanliuu** [comment]
> Can you paste the full config (this doesn't include /enc)?
> Are you using proxy_cache?

"/enc" is a local dir, "/www/wwwroot/vod/enc"

server
{
	listen 80;
	server_name 127.0.0.1;
	root /www/wwwroot/vod;
    
	vod_mode                           local;
	vod_metadata_cache                 metadata_cache 16m;
	vod_response_cache                 response_cache 128m;
	vod_last_modified_types            *;
	vod_base_url                       "//$http_host";
	vod_segment_duration               9000;
	vod_align_segments_to_key_frames   on;
	vod_dash_fragment_file_name_prefix "segment";
	vod_hls_segment_file_name_prefix   "segment";
	vod_manifest_segment_durations_mode accurate;
    
	open_file_cache          max=1000 inactive=5m;
	open_file_cache_valid    2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors   on;
	aio on;
    
	gzip on;
	gzip_types application/vnd.apple.mpegurl application/dash+xml;	
	...	
	location /dash/ {
		vod dash;
		alias /www/wwwroot/stream/videos/;
		
		vod_drm_single_key         on;
		vod_drm_upstream_location  /enc;
		vod_drm_request_uri        /key.json;
		vod_drm_enabled            on;

		add_header Access-Control-Allow-Headers '*';
		add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
		add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		add_header Access-Control-Allow-Origin '*';
	}
}

**Comment by Yuanliuu** [comment]
"/enc" is a local dir, "/www/wwwroot/vod/enc"

server
{
	listen 80;
	server_name 127.0.0.1;
	root /www/wwwroot/vod;
    
	vod_mode                           local;
	vod_metadata_cache                 metadata_cache 16m;
	vod_response_cache                 response_cache 128m;
	vod_last_modified_types            *;
	vod_base_url                       "//$http_host";
	vod_segment_duration               9000;
	vod_align_segments_to_key_frames   on;
	vod_dash_fragment_file_name_prefix "segment";
	vod_hls_segment_file_name_prefix   "segment";
	vod_manifest_segment_durations_mode accurate;
    
	open_file_cache          max=1000 inactive=5m;
	open_file_cache_valid    2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors   on;
	aio on;
    
	gzip on;
	gzip_types application/vnd.apple.mpegurl application/dash+xml;	
	...	
	location /dash/ {
		vod dash;
		
		vod_drm_single_key         on;
		vod_drm_upstream_location  /enc;
		vod_drm_request_uri        /key.json;
		vod_drm_enabled            on;

		add_header Access-Control-Allow-Headers '*';
		add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
		add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
		add_header Access-Control-Allow-Origin '*';
	}
}

**Comment by erankor** [comment]
This is not supported, the 'drm_upstream_location' (/enc in this case) must be a location with proxy_pass. In most deployments, there will be some server responsible for allocating the DRM keys and generating licenses to players, the proxy_pass location will call to this server.
You can, for testing purposes have the proxy_pass to localhost, to some other location that serves the static file.
