### ISSUE TITLE
Slow segmentation when using http upstream

### ISSUE THREAD

**Issue by kolevgeorgie** [kaltura/nginx-vod-module#994]
I have successfully configured a remote upstream which serves the file over http. But I noticed that it delivers segments with ~750-1000KB/s (4MB segment for 4+ seconds). which is low for videos high bitrate. To ensure that the issue is not network related I've done the following:

- nginx-vod is running locally on same computer where I'm trying to play the file.
- tested the connection to upstream - file is downloading with 70+MB/s speed.
- tested playing the same file but from local storage - segments are delivered with lightning speed (4MB segment for 300ms). 

Any suggestions how I can achieve fast delivery with remote locations?

**Comment by erankor** [comment]
You can try to -
1. Enable keepalive on the upstream
2. Increase vod_cache_buffer_size

**Comment by kolevgeorgie** [comment]
Increasing the vod_cache_buffer_size really helped, thanks!
