### ISSUE TITLE
support HLS stream .aac file list?

### ISSUE THREAD

**Issue by wnpllrzodiac** [kaltura/nginx-vod-module#995]
I know that vod module support audio track list(.ts file in PLAYLIST)
Can I do some config to make m3u8 playlist file is .aac(raw audio file ,not mux in mpegts container) ?

**Comment by erankor** [comment]
This is not supported, why do you want it?

**Comment by wnpllrzodiac** [comment]
iOS player will treat playlist with ts files as media has video track? I want to deliver a only audio vod service like story channel which media source is mp3 and aac raw video. But some single mp3 is bigger than 40MB. I want to do a segmentation op.

**Comment by erankor** [comment]
Other than slightly larger overhead, I don't think it makes any difference if the audio is packaged as MPEG-TS or raw AAC.

**Comment by wnpllrzodiac** [comment]
Yes. I give up the bad idea. Just let It go. ts file with aac track is good enough.

**Comment by erankor** [comment]
I don't think it's a bad idea :) just low priority from my perspective
